### ISSUE TITLE
upgrade v3.80 to v4

### ISSUE THREAD

**Issue by todaylogin** [moxi9/phpfox#100]
Question:  how to upgrade v3.80 to v4? safe all 3rd party modules work for v4?
WebSite is fully live

**Comment by Data66PF** [comment]
You need to check with third party vendors first and wait for them to update their modules and your theme if you use a third party theme as these things need updating. Most work but need adjusting.

**Comment by todaylogin** [comment]
Actually we are only using phpfoxmods.net 3 modules 1. Business Directory 2. Pbay & Autions 3. Offline payment gateways.
We are many time try to contact them for upgrade but they not any reply since 8 to 9 months.
We are worried about it please help us. we hope you will great support us!

**Comment by Data66PF** [comment]
Those modules are no longer supported as the main developer passed away. You will need to hire a developer to fix those modules as they also had issues in v3.8 for some things.

**Comment by todaylogin** [comment]
Please suggest us for new developers for these modules 
we are running business in thes modules. we want to safe data for v4.
Dear you are great.
we are phpfox clients from may 2013.
Please guide us for good developers with normal cost.

**Comment by todaylogin** [comment]
I am too small developer with initials stage. have any guide for adjustment? Please help us

**Comment by Data66PF** [comment]
Check with YouNet as they have most of these modules made and they have imports for them but still, it is v3.8 as no developers have updated their modules yet but at least, if you get their versions, they said they had plans to update them for v4.

**Comment by todaylogin** [comment]
its so difficult for us! if i became a developers can i do?

**Comment by Data66PF** [comment]
These are huge addons with a bridge, cart, gateway stuff. It is not a small job. I'm sure if you become a developer, you could learn but note that all of Brian's addons were made with v2 code so that is another battle to fight as they were not brought up to even v3 code.

**Comment by todaylogin** [comment]
please can you explain about a bridge in modules ?

**Comment by signupsi** [comment]
bridge for business directory is common functions ( library ) used in different modules by business directory etc
