### ISSUE TITLE
Short URLs .htaccess fails when running in FCGId mode

### ISSUE THREAD

**Issue by phpfoxmetro** [moxi9/phpfox#1000]
When PHP script execution mode is set to run FCGId (run as virtual server owner), trying to set short URLs fail. If you change the mode to run CGI wrapper (run as virtual server owner), then you will be able to set short URLs.

Please refer to this thread...  https://community.phpfox.com/forum/thread/53736/htaccess/

**Comment by raulw** [comment]
Same problem here, but I changed the .htaccess (like below) and is working with fcgi.

`<IfModule mod_rewrite.c>
RewriteEngine On
# RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(file)/(.*) PF.Base/$1/$2
RewriteRule ^static/ajax.php index.php
RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
</IfModule>`

**Comment by phpfoxmetro** [comment]
Thanks raulw.  Hopefully, phpFox endorses this fix.

**Comment by phpfoxmetro** [comment]
Any idea whether phpFox accept rauls recommendation as a reasonable fix?

**Comment by Data66PF** [comment]
@neil96 did we need to look at this? Would the fix break sites not on fcgi?

**Comment by neil96** [comment]
Our htacess code work well with apache. With other environment, we can make some wiki pages to guide them. (Just my though, we can discuss more with team)

**Comment by phpfoxmetro** [comment]
just to be clear - the provided code by phpFox core install DID NOT work as stated in the op.  And, it was on a LAMP - apache on CentOS 7 the provided fix by @raulw worked when tested on the same boxes that had previously failed.  This is not a one off issue as it has been addressed in the phpFox forums.

**Comment by Data66PF** [comment]
We need to ensure it won't break other sites. Right now, the current method works for many clients but we do know some clients have issues. This is why we need to check it as we can't control what everyone uses for hosting environments so we need to provide the basics and let clients take it from there. We will discuss with the technical team to see if the changes would adversely impact clients using the current methods.

**Comment by phpfoxmetro** [comment]
While I agree with your strategy, this statement "Our htacess code work well with apache. " as posted above could not be further than the truth.  For what it is worth, the issue can be duplicated on both Ubiquity Hosting and Rackspace servers with a clean install of CentOS 7.  I will be happy to assist in providing a test site that might help y'all mediate the issue.

**Comment by wlongdonstudio** [comment]
It would nice to give specifics on the settings of the server

**Comment by Data66PF** [comment]
as we can't reproduce this, can one of you please send a ticket with server and admin access to hello@phpfox.com ?

**Comment by PhpFoxJohnJr** [comment]
I see you closed this...I just reinstalled and came on the same issue again as this website is in a subfolder...I forgot I solved it the first time by changing the last line and it worked again.

	#RewriteRule ^(.*) index.php/$1 --------removed
           RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]

**Comment by Foxgerman** [comment]
I have the same issue on my site. Apache handler is set to FCGI and i was able to access my site with provided htaccess code on some urls, but not on home. Really strange. Does anyone has a working solution? Client site is offline and i have no idea how to fix that.
