### ISSUE TITLE
Video as APP is not compatible with video module

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#1002]
we have lot of module which extends video module 

New VIDEO app for phpfox 420 does not work with any existing 3.x custom modules, which extended Video module 

The custom modules break and its additional effort to make it work on video aPP 

Not happy about it

**Comment by Data66PF** [comment]
Please post feature requests at our forum but note that we already discussed this at the community.

**Comment by neil96** [comment]
A another note: Video App (in 4.2.0) and video module (in V3) completely separate, so you can't keep custom work from V3.
