### ISSUE TITLE
redis cache fails

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#1003]
Installing redis cache APP fails to install

**Comment by robert9592** [comment]
I cannot reproduce this issue on the testing sites (v4.2.0 RC). Can you give us more detail about this and which php of your site?

**Comment by signupsi** [comment]
![redis_error](https://cloud.githubusercontent.com/assets/13350517/12636017/d74a6adc-c54e-11e5-9c45-f174205213c0.JPG)

**Comment by signupsi** [comment]
this is running on standard WampServer Version 2.5
