### ISSUE TITLE
page issue while adding a pic to it

### ISSUE THREAD

**Issue by riteshinsan** [moxi9/phpfox#1004]
Hi,
whenever a new post is added to the page it shows the user has created a new post on the page. Consider for example a user "user1" who has created a new page named "news" and on this page a new post " India Wins the 5th ODI" so it shows like "user1 --> news --> India Wins the 5th ODI". Where as if the user post a pic on this page say "toi.jpg" then it is showing only "user1 --> toi.jpg" it does not show that on which page the pic has been posted.

Requesting you to make the change in such a way that if a user post the photo on the page it shows in the same way the one it is shown for the new post on it.

This is very urgent for us, so requesting you to make this ASAP.

This is noticed on all the versions.

Thanks
Ritesh

**Comment by neil96** [comment]
Fixed on V4.2.1
