### ISSUE TITLE
Hashtags have wrong date

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1007]
If you create a new hashtag and use it in some posts when it show in the trending block it has a wrogn date.

This hashtag is a new (created toaday) and is trending from since 26 January but in the block it shows that is trending since 19 January:

![Screenshot](http://i.imgur.com/7KrQNhr.png)

**Comment by neil96** [comment]
We cached hashtags data, in default, time to save cached is 180 minutues (setting tag.tag_cache_tag_cloud). You can find this setting in this link: index.php/admincp/setting/edit/?module-id=tag (first setting, value = 180). If you put this setting is 0, cached only remove when you clear cache manual.

**Comment by Data66PF** [comment]
We need to add the setting back to the menu when we find settings that are not in the Settings menu. Please add the Tags setting back to the menu for clients to find the settings without having to search as this used to show in V3.

**Comment by Data66PF** [comment]
Note that the date issue is due to the setting for how many days a tag can trend. It will show back to that date. If you set it to show back 1 day, it would show trending since yesterday. If you set it to show 7 days back, it will show trending since that date 7 days ago.
