### ISSUE TITLE
Photo categories are not listed

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1008]
We always used to show our categories and subcategories (if applicable when a main category was clicked).

We seem to have lost our categories from the photo section. 
![photo cat](https://cloud.githubusercontent.com/assets/6908282/12592962/bfb208fc-c43c-11e5-8216-b389b25682fc.png)

Please check that all sections that use categories show the categories in a menu such as V3 did. Some sections allowed for subcategories which would show up once a main category was clicked.

**Comment by Vivian-phpFox** [comment]
You can add category block from ACP

**Comment by Vivian-phpFox** [comment]
Should add Category block on photo.index page

**Comment by neil96** [comment]
Fixed on V4.2.1
