### ISSUE TITLE
Please don't make us dependent on Amazon or Someone who can host our videos.

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#1010]
Please don't make us dependent on Amazon or Someone who can host our videos. I Love Amazon but I still don't want to get dependent on amazon at any time I want my website to work and run even if I changed my Host or if I change my mind decided to host the website on my server. Well my videos are some where different from my server.HOW COOL is that? I don't get it I still miss the time I can access all my files together in one place.
Please don't recommend me to host my site at Amazon.

**Comment by Data66PF** [comment]
Please have feature requests or feedback in our https://community.phpfox.com or use our contact form at https://phpfox.com as our bug tracker is not for posting feedback as it slows development fixes.

**Comment by GreenMan123** [comment]
Well I still got no license for now but I want these features added to phpfox . I will soon buy the license but as far  I am concerned you have to do more (Add Features to Phpfox). And If you can Post these issues for me in the community.

**Comment by GreenMan123** [comment]
In my opinion it is a big BUG to get dependent in something for a company which is thriving to do more and achieve more. You can't reach your destination in the BACK of Someone.

**Comment by Data66PF** [comment]
We will open a feature request area soon other than the one in the forum.
