### ISSUE TITLE
Can you please make the image(Photo) in the Home Page(Login Page) rotate like the Picture do in bing.com it change it self after a time interval

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#1011]
Can you please make the image(Photo) in the Home Page(Login Page) rotate like the Picture do in bing.com it change it self after a time interval and make user interested and Expect something also I would the image to automatically come from the top viewed photo of users with Admin's(Staff) approval.

**Comment by Data66PF** [comment]
Please note that this feature exists in some extent in 4.2 coming today. Please do not post feature requests here. Please post at our community.
