### ISSUE TITLE
Pages and block 3

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1014]
When a block is added to space 3  it prevent pages frpm opening in second phase when see more is clicked. 

![screenshot-stage phpfox com 2016-01-27 20-42-16](https://cloud.githubusercontent.com/assets/13656046/12624306/03921b3e-c537-11e5-8f14-9d06c5188e0c.png)

**Comment by one44** [comment]
Try with about ten groups on a page it works with two or three but when there are a number only the bottom few work and the higher ones do not.

**Comment by Vivian-phpFox** [comment]
Can you reproduce on staging site?

**Comment by one44** [comment]
Will check but staging site did not have a block three last time I looked.

**Comment by one44** [comment]
Ok checked works fine there but on my site only works on bottom line when block three is used

**Comment by one44** [comment]
After further investigation two groups groupings work fine with ten or less but the other two have 29 groups and only the last bottom two work. If same script used seems to be a numbers of groups issue.

**Comment by neil96** [comment]
I can't reproduce on V4.3.0

**Comment by Data66PF** [comment]
Still cannot reproduce in Chrome testing and Safari. https://v4.phpfox.com/pages/category/3/group-or-community/
