### ISSUE TITLE
Marketplace no work v 4.2.0 

### ISSUE THREAD

**Issue by cympgo** [moxi9/phpfox#1015]
the Marketplace I can not see the details of the announcement when I click on the call. mosta the course that the system is working on the request, it is more.

https://v4.phpfox.com/marketplace/

I click on this publication to go to the link below , more work is not caught the request.
https://v4.phpfox.com/marketplace/22/cepillos/

**Comment by Data66PF** [comment]
We've fixed this issue. Please check and let us know if it works for you now. Thank you.
