### ISSUE TITLE
Select group registration method doesn't work | 4.2.0 Stable

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#1016]
As referenced in #800, the problem still exist.

Explained is:
I set to join my group is needed to been approved or just at invite.
If a member joins, I need to approve the membership, so I receive a notification.
I open the notification and instead of getting redirected to http://website.com/pages/1/pending I get redirected to website.com/pages/1/ and if I manually force the /pending after the address, it shows me a weird list below the main feed of the page of all the members that have requested to join the group, but I don't have any way to approve them.

https://cloud.githubusercontent.com/assets/12573563/12616062/76e84f6e-c509-11e5-8721-864497adde1f.png

And too, there doesn't show up any button to go on /pending

Tested with 4.2.0 Stable, both my community and stage site.

**Comment by Vivian-phpFox** [comment]
Design was changed. The "Pending Memberships" menu added in settings button
![1-29-2016 10-13-38 am](https://cloud.githubusercontent.com/assets/15936508/12666272/b19e63dc-c671-11e5-89f5-c7f23718d08c.jpg)
