### ISSUE TITLE
Page columns issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1017]
3 colum pages columns showing small from v3 upgraded site:
Counters updated
Cache cleared
Chrome
Windows 10

![download](https://cloud.githubusercontent.com/assets/8562514/12650999/3157f440-c5e5-11e5-85f3-1d6690be9738.png)

*3rd colummn empty and middle column small

**Comment by Data66PF** [comment]
Did you use the Rebuild Theme as mentioned in the blog release?

**Comment by Ylmzef** [comment]
Yes i did it to but i'm getting following result on blank page:

`{
    "run": "flavor_end();"
}`

**Comment by Data66PF** [comment]
Are you sure you are using the rebuild theme in the theme edit screen and not in the maintenance settings?

**Comment by Ylmzef** [comment]
I have done both settings.

**Comment by Ylmzef** [comment]
And some buttons showing like this, i think there a issue.
![download](https://cloud.githubusercontent.com/assets/8562514/12696190/fe921e02-c763-11e5-8534-4fea4ad3fa1d.png)

**Comment by Ylmzef** [comment]
Still waiting for this..

**Comment by Ylmzef** [comment]
The buttons are fixed after removed ScriptTechs's Admin View Private Messages app.
But there still block size issue..

**Comment by Data66PF** [comment]
Did you get the latest version of the app? I had seen an issue in it and fixed it recently.

**Comment by Data66PF** [comment]
As this is for the pages issue and not the button issue, that needs to be in a different report if it is not from an app. App issues need to be reported to the developer that made it.

In regards to the page issue, do you have a sitewide block in position 3 that might even be a hidden block such as analytics code or anything?

**Comment by Ylmzef** [comment]
I had a sitewide block in position 3.
I have changed it to position 12 and the issie fixed now thanks!
