### ISSUE TITLE
Homepage collapses if featured user block is off and registration setting is off

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1020]
V4.2.0 bootstrap theme with uploaded images for a background.
Registration is disabled as most do before opening their sites. This is the registration setting, not the registration block. That block will also get disabled automatically when the registration setting is disabled.

Featured guest user block for visitor page is disabled as most clients don't want it enabled.

Doing the above, we now see nothing for our visitor page as the entire center area collapsed. We need the background to be a "holder" or something so that it will not collapse if a site is being developed as all clients develop their sites before opening. We also have clients that disable the registration block and featured user block so they can showcase their front background image. For this entire set of reasons, we need to figure something out for this.

![visitor before](https://cloud.githubusercontent.com/assets/6908282/12656472/7b1659be-c5cc-11e5-9d39-49d1cbb6e905.png)

Register Disabled, featured guest user block disabled:
![visitor after](https://cloud.githubusercontent.com/assets/6908282/12656476/7d1b87d4-c5cc-11e5-9230-0255cd564505.png)

**Comment by Spaninet** [comment]
Also collapses when registration block is off if there are not other blocks in homepage.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#13
