### ISSUE TITLE
Pending approval Photo doesn't work eveytime 4.2.0

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#1021]
Using 4.2.0 and Bootstrap theme untouched, if you have the setting that a photo need to be approved to be shown when uploaded in the website by users, rarely can happen that a photo (or more) don't appear and it's impossible to approve them. I have to go in the Database and approve them editing columns and this isn't possible everytime, theremore even with so much photos.

This is the problem (in italian)
![image](https://cloud.githubusercontent.com/assets/12573563/12657556/39ba1a36-c604-11e5-9144-a31f9d65ee13.png)

Please, even just a temporary fix for this is possible? It is an important part of my community.

Thank you.

**Comment by optiroot** [comment]
Hello. 

I found the problem. 
Before 4.2 if a user uploaded a photo in their profile or in the main feed, these photos, were shown for approval in the photo module. 
Now not. 
Disabling the "requires approvation" if AN user uploads a photo in their profile / main feed, this doesn't show in the photo module. That is the same acting of when the "require approvation" is enabled. 

I have set too that the profile and cover photos must be shown in the photo module, but the photos shared via profile or main feed don't get shown. 

I guess this problem came from this:
I don't remember for what reason and in reply to which ticket but Data66 said that maybe it would be better to let the admin choose if profile and cover photos must be published and shared in the photo module. So maybe when phpfox developers made this feature, practically they have "hard-locked" (or at least i don't find the option) that photos that aren't uploaded in the photo module must not get shown. 

I hope that I have been clear because I can reproduce now having understand the problem everytime... 
So it isn't random... 

If you need more details please tell me.

**Comment by optiroot** [comment]
@Data66PF please can someone check this? 
I can reproduce this.

Before 4.2 photos shared via profile/status box were displayed in the public photo section, now not...
At least adding an option to enable/disable this as the profile/cover photo introduced in 4.2 could be great, because this is very important for my community as I think for so much other communities centered about photo sharing and so on.

Thank you!

**Comment by Data66PF** [comment]
Photos loaded to the feeds are never in the photo section. They never have been even in v3. They are comments and not content. That's why I made my Uplinks module and app. It shows the links to upload things right on the member dash where it is easier for them to find and where they will be added to content. Status shares have never been content (other than the new video app).

**Comment by Data66PF** [comment]
I tested and still cannot reproduce this as the photo that is loaded to the feed shows in photo/?view=pending the pending photos.

**Comment by optiroot** [comment]
I reopen this now, sorry so much.

So I don't understand the problem. For example, if I upload a photo, sometimes shows in the "Approval" section, and sometimes not. The counter still signs photos to approve, but if you load the page you don't get anything...

I don't understand the problem. I had to go in the Database to manually approve them...
If you need more details about this, I can give you debug data and so on..
It's important in my community this feature. Thank you.

**Comment by Data66PF** [comment]
Client responded to reopen. Can we have someone check it? @Vivian-phpFox maybe?

**Comment by Data66PF** [comment]
Or maybe we need someone to go to the site. If so, the client can submit a ticket with details for us if @neil96 might need to check on site.

**Comment by optiroot** [comment]
I could give too access to my website without problems. But actually I have an active community and enabling the "approve photo" feature can create so much troubles in users if we can't really approve them.

If we can concord a precisely time and day, I could do this. Thank you!

Neil already knows my website, so if he is available I guess is better.

**Comment by neil96** [comment]
@optiroot , sorry I can't remember your site and I can't reproduce on localhost. Could you submit a ticket with your site information? Thanks!

**Comment by optiroot** [comment]
Sorry for the late answer. Re-open this, please!

I'm going to send in a ticket my website informations. Thank you!

**Comment by Data66PF** [comment]
Is this resolved? Was there a ticket? If so, what is the ticket number?

**Comment by neil96** [comment]
Here is ticket ID #926886 (273). But we can't reproduce on client site too.

**Comment by optiroot** [comment]
Hello,

I deeply tested this with over 1500 photos uploaded by my users. This problem isn't present anymore, but there comes another one. This last one made some users that were uploading some photos unable to login (just 7-8 users, while I have 3000 users and more) so the percentage is low. But some users had issue. I can say it was pending photo feature because after disabling it, any user anymore had any problem. The users that already had the problem still couldn't login.
Upgraded phpFox to latest version solved the problem for them too.

I'll not enable this feature anymore for now... it requires testing, because is **really** creating troubles sometimes. This problem that created at me is difficult to reproduce, as you need to test on a production environment. I don't know, even opening a new ticket to tell you the problem, how to let you reproduce it. Now my website is fine, but everything was caused by this feature.
