### ISSUE TITLE
4.2 Stable: Creating a theme does not create a theme, only a flavor

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1022]
I am trying to create a separate theme. Under 4.1.2, the created themes showed under /themes/ directory. After creating a new theme in the them manager, cloning from Bootstrap default theme, there still remains only one theme in /themes directory...Bootstrap thereafter. The created theme name shows up under PF.Site/flavor.

I do not want a flavor of default bootstrap, I want a separate independent theme, that although not recommended, would still run as default theme if I deleted original /theme/bootstap theme altogether as I could do in 4.1.2
 
Where do store themes install to under this version?

**Comment by Data66PF** [comment]
This is how it is designed as it is all based on bootstrap and clients can then make any changes with css and html as our neutron theme will show the possibilities. You cannot delete bootstrap as it is a core product. 

We do have more improvements coming.
