### ISSUE TITLE
Apps Store: Can't upload screenshot

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1023]
Hi,

I was updating some screenshots from one of my app on the Store, but the images are not uploaded. 

This is the app:
https://store.phpfox.com/product/962/v4-videos-block-cespiritual

Thanks

**Comment by Data66PF** [comment]
I added an app yesterday and had no issue. Perhaps the image was too large or perhaps you tried when we were updating something. Can you please try again?

**Comment by cespiritual** [comment]
Just tried again to upload a jpg to the app and it's not working... The image is 160 kb

**Comment by Data66PF** [comment]
What browser and os? Make sure you are not on mobile.

**Comment by cespiritual** [comment]
I have tried in latest firefox and chrome.

Can you make a test? On one of your apps try to add a new image.

This video app is not a new one. I have just deleted the image that were there and tried to upload a new one and I can't.

Thanks

**Comment by Data66PF** [comment]
Ok it is not working now. It was working.

**Comment by Data66PF** [comment]
Please test this as it is fixed for me. You'll need to load new images for the ones that didn't work.

**Comment by cespiritual** [comment]
It's working now... thanks!

**Comment by Data66PF** [comment]
Thank you for updating this. :)
