### ISSUE TITLE
4.2 Stable: Creating a new Flavor, results in redundant Bootstrap theme

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1024]
When the theme (really a flavor) is created, and additonal theme named Bootstap identical to the default bootstap theme gets created.  Now I have 2 bootstrap themes. I cannot delete the redundant "Bootstrap" theme because the system sees it as a default theme, so for now I will put the axe to it in the database themestyle table.

Related:  Two files get created in the /flavors directory for the same theme name in addition to the existing bootstrap flavor. The theme was created only once. The extra file with created theme name may be that extra theme the admincp theme editor is seeing as "Bootstrap".

**Comment by Data66PF** [comment]
I believe this is by design as the default bootstrap theme right now is not advised to make any changes to due to issues that could break the theme. Doing this, it creates a bootstrap that can be edited in order to preserve the original default.

**Comment by Data66PF** [comment]
After an interesting debate at ScriptTechs, I find this process too confusing as we have two bootstraps for some clients but for mine, it is one Pegasus in admin but then I have a bootstrap and pegasus in flavors and a bootstrap in themes folders. I am confused as to what's what.

**Comment by Gatsby-PF** [comment]
Whatever this is, it is not industry standard best practice. Themes bootstrap or not, should be portable, drop in, selectable and user editable like they were in Neutron with the sync. I can see this regime leaving users wholly dependent on theme producers/cookie cutter themes, or limited by the Admin theme editor which is a big step down for me. The flavors you mentioned above do not have their own css files as mentioned in another post so how does something not get lost in an upgrade?

**Comment by Data66PF** [comment]
Team, Please see feedback from a client web developer who uses our script for his client sites http://scripttechs.com/forum/thread/3061/blood-starting-to-boil-again/view_19514/

**Comment by Spaninet** [comment]
New bootstrap cloned theme, every time is set as default it creates a new bootstrap theme.

Now I have 3 themes with the same name and can not be removed.

**Comment by RaymondBenc** [comment]
Fix is part of https://github.com/moxi9/phpfox/issues/1025

**Comment by Spaninet** [comment]
This issue is still in last version [4.2.2](https://github.com/moxi9/phpfox/issues?q=milestone%3A4.2.2+is%3Aclosed).

![](https://community.phpfox.com/file/attachment/2016/02/0ec246a475fc5d2ea03ca5e897b72e89.png)

**Comment by Data66PF** [comment]
Did you follow the steps in the blog? It is required. Did you ensure to remove any old themes that had problems?

**Comment by Spaninet** [comment]
- I have latest phpFox version.
- All steps in blog done.
- Issue still there. After creating a new theme, every time default theme is set as default a new theme of bootstrap appear in Themes.
