### ISSUE TITLE
Create "theme" does not have its own css file

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1025]
Only theme/ bootstrap has a css file for all themes according to inspector when created theme is set for default theme? How does that work?

**Comment by Data66PF** [comment]
Our documentation is opening soon.

**Comment by Gatsby-PF** [comment]
Can I at least get a basic explanation of how the existence of only one css file in the bootstrap core does not get lost on the next update since the folders create for the theme for some reason do not have their own in order to preserve custom changes or revert back to. Something is not right here and extra coffee is not helping me understand.

**Comment by RaymondBenc** [comment]
Fixed in 4.2.2.

**Comment by Data66PF** [comment]
When making a theme based on bootstrap the files would be found in PF.Site/flavors/yourtheme/assets/autoload.css for example as that is the css file.
