### ISSUE TITLE
blank feed entry

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1029]
4.2 stable using firefox and bootstrap theme

This issue is only with those  feed entries which don't have any text or media contents  like   user joining  or   if someone added another user  as friend  etc. when  we share such type of feed entry using share button  it appear as shown below
![image](https://cloud.githubusercontent.com/assets/406030/12668157/1bc4e272-c654-11e5-8e89-f93e96918b8a.png)

**Comment by neil96** [comment]
Fixed in v4.3.0
