### ISSUE TITLE
Cannot disable modules 

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#103]
Cannot find any option to disable modules

**Comment by Data66PF** [comment]
Are you using v4.0.2? Did you ensure to run the Find Missing Settings, clear cache and also Find missing phrases?

**Comment by lilman446** [comment]
To disable modules in admincp goto the menu for Maintenance then click Toggle Modules.

**Comment by signupsi** [comment]
thank you ; I was able to disable modules option under "Maintenance then click Toggle Modules."
