### ISSUE TITLE
Custom Field - Can not add Option

### ISSUE THREAD

**Issue by phpfoxmetro** [moxi9/phpfox#1034]
To Recreate

1.  Create a new Custom Field with type "Selection"
2.  Add Optiion 1
3.  Save Custom Field
4.  Go back edit the Custom Field
5.  Try and add another Option

There is no way to add addtional options.

**Comment by Data66PF** [comment]
Confirmed at staging server. Check the Custom Fields there and you will see I added Favorite Season with an option for Spring and saved it for this test. I now cannot add the rest of the options as there is no way to when editing the field.

**Comment by robert9592** [comment]
Fixed in v4.2.1
