### ISSUE TITLE
4.2 Stable new install: The login popup too wide.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1035]
Conditions:
PC full screen mode. Site was set to invite only. No access for guest on any menu items. Clicked on a menu item, access is correctly refused, and the login popup is presented.

But it stretches all the way from Los Angeles to New York. There in no name in the world wide enough to fill it.  It is behaving like it thinks it within the minimum threshold for mobile display.

**Comment by Gatsby-PF** [comment]
Update
Privacy settings are doing this too.

**Comment by Data66PF** [comment]
This generally happens when there is a missing phrase. Did you run Find Missing Phrases? I know you said new install but sometimes it can help to run that.

**Comment by Data66PF** [comment]
I can confirm it does this but if a site owner puts a block on those pages, it will lessen the display size. It simply fills the screen responsively by design. Will leave this unlabelled for our QC to determine if it needs to be changed. IMO it is fine as it is as it is not harming anything and will shrink if blocks are placed there.

**Comment by Gatsby-PF** [comment]
Using a moble stretch in a PC display is more due a programming kludge, than it has to do with responsive. I don't think blocks appear in password screen do they?

**Comment by Gatsby-PF** [comment]
One more observation. The primary login dialog (the one you get when directly clicking the LOGIN button does not do this and it is responsive.  So the one you get as a reaction of clicking on a disallowed menu item should to the same.

**Comment by Gatsby-PF** [comment]
The contact form is also doing this. Looks unsightly.
