### ISSUE TITLE
Nginx as Proxy Theme Issue

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1036]
Posting from developer feedback. Using Nginx as Proxy for static files fails with the theme and needs to be disabled. Please test and provide a fix if possible as this will cause issues for clients.

**Comment by optiroot** [comment]
Hello Data,

I was going to do right this in my server!

But do you mean using Apache for Dynamic files (php) and Nginx as a reverse-proxy for static files, that will pass every thread to apache when there is a dynamic file, right?

**Comment by Data66PF** [comment]
This is from a developer and a few clients having issues. I'm only posting for them as it's not something I know anything about.

**Comment by neil96** [comment]
Fixed on V4.4.0
