### ISSUE TITLE
Feed Not Loading Well

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1038]
Staging 4.2.1 and my live dev 4.2.0 tested on macbook pro with chrome. Log in to a site that was upgraded to see the issue in better detail. The feed is not loading well. It shows there are items in it but each space is blank. I have to refresh the page to load it. If I then surf to another page such as blog or market or wherever, and then go back to the main home page, the feed again does not load. 

I find that on my dev site, after a delay, it shows 619 new feeds and then it loads the feeds. There is something mucked up in the process here as it shows the same behavior (with less delay as there are less feeds) on the staging site. Note that those 619 feeds are  not new as this is a closed dev site with only me on in and I assure you I did not make 619 feeds over night.

**Comment by Data66PF** [comment]
This issue could also be related to #1031

**Comment by Ramstete** [comment]
i had similar problem and was the  apache compression for files

**Comment by haisay** [comment]
The same issue here.
the site loading slow too.

**Comment by lordofnos** [comment]
same issue on dev and live site

**Comment by raulw** [comment]
I have the same problem. The apache compression for files is disable (which I understand that can cause problems)

**Comment by Data66PF** [comment]
This might also be related to #1042

**Comment by neil96** [comment]
I can't reproduce this issue on V4.3.0. Could you ( @Data66PF ) test again on V4.3.0?

**Comment by Data66PF** [comment]
I don't have a site with enough content to tell. My dev site is 4.2.2. This test needs an upgraded site with a lot of content. At least several hundred feeds to load.
