### ISSUE TITLE
Friend Notification Remains Until Reload

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1039]
Staging 4.2.1. Have a friend request and accept it. Notification remains until you refresh the page a few times. I can surf around and the notification will remain for a while.

**Comment by aakash83** [comment]
sometimes the other notifications also don't disappear until we reload page.

**Comment by optiroot** [comment]
I can confirm this but for me it is enough to re-open the notification/message/request again one time, without the need to reload the page completely.

**Comment by neil96** [comment]
Fixed on V4.3.0
