### ISSUE TITLE
Posts posting to both feeds

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1041]
When posting to a members feed it is showing in main feed as well.  Tested on stage site.

**Comment by Data66PF** [comment]
This is normal behavior as the feed shows all activity. Did you mean that it is showing to non friends if the site feed is set to friends only? Is there something about it not working properly for privacy settings? This is how it has always worked even in v3.

**Comment by one44** [comment]
No my site always only showed posts to members feed and not main feed if posting is made to members feed only. Site has always been that way as I send new members a welcome message on their wall and it did not show in main feed.  From what I understood this was always the way it worked. Like Facebook with the two feeds.

**Comment by Data66PF** [comment]
I tested my v3 site before posting my comment above and it works the same. If it is a normal status post on a wall, such as a Hello, then it won't show in the main feed. If it is a gift or photo or some item like that, then it will show in the main feed. This is how it has always worked.

**Comment by one44** [comment]
ok so the issue is that I am using gifts now

**Comment by one44** [comment]
Ok tested without sending a gift and only posts to members feed.
