### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by Ramstete** [moxi9/phpfox#1043]
after i have login and i close the browser, if i open again the browser and i try to login in phpfox it keep the loading circle but not bring me inside, if i click  the logo icon (top left one) then i am inside my accoutn without had any chance to go through the login window.

phpfox 4.2.0 new installation
windows 10 o.s.
browsers: firefox,microsoft edge, chrome

**Comment by Data66PF** [comment]
This would be due to your browser cache as the session has not expired yet.

**Comment by Ramstete** [comment]
right some cache persistant i close this issue then
