### ISSUE TITLE
Hardcoded Forum Phrases

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1045]
Can't translate following phrases in admincp.

![download 1](https://cloud.githubusercontent.com/assets/8562514/12696703/91848292-c771-11e5-9e15-055f9d97acca.png)
![download 3](https://cloud.githubusercontent.com/assets/8562514/12696705/9f00fcde-c771-11e5-9f47-7dc78e9403a2.png)

**Comment by Ylmzef** [comment]
And (NEW THREAD)

**Comment by neil96** [comment]
Fixed in V4.2.1
