### ISSUE TITLE
Daily message limit issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1047]
Daily message limit not working with new im.
I set the daily message limit to 5 but users can send unlimited messages.

**Comment by Data66PF** [comment]
The IM disables the PM settings. You can use one or the other but not both. At this time, there are no settings for the IM to regulate what users can do in it.

**Comment by Data66PF** [comment]
Marked an enhancement as we need the settings back for this.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#10
