### ISSUE TITLE
music album

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1048]
music does not play in music album. tested on dev and stage.phpfox.com

**Comment by Data66PF** [comment]
Please provide a link to the music album and state the OS and browser tested.

**Comment by lordofnos** [comment]
tested on phpfox stage... just try to play album songs. os win10 with ff.

**Comment by Data66PF** [comment]
Tested on stage with win 10 and ff in all three of the albums that are on it. Each one plays. I click the pay icon to the left of the song and at the top of the songs, it shows a play bar. I click that play button and each song plays though for the song you shared I have to turn the volume up to hear it as it is a rather light sounding song.

**Comment by lordofnos** [comment]
ok, this does work for me too but it is not intuitive. i only clicked once. may be better to autostart the player when a track is clicked?

**Comment by Data66PF** [comment]
This is how it worked in v3 as well because I made a few blocks for songs and albums and saw it at that time. An improvement is a good idea but right now, this is working as designed.
