### ISSUE TITLE
upgrade routine

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1049]
since i had a problem with the upgrade routine i am looking for a save way to restart it. changing the version.sett.php back does only work on dev site but not on my live site. what else can i do to start the routine again?

**Comment by Data66PF** [comment]
Please describe the problem with upgrading and please state server specifications.

**Comment by lordofnos** [comment]
the problem was that the upgrade routine not started. system information shows version 4.2.0 and new theme manager works but the options that should be inserted in the databse are not there. i don´t know if other things change with the routine so i want to restart it. dev site on same server shows the upgrade routine so i don´t think that it is a server issue. maybe i had not the right permissions and that was the problem... had this some time before that permissions are not set right via ftp and this time i did not check before upgrading. i need to restart it.

**Comment by Data66PF** [comment]
I'll mark this an enhancement for us to make an option on upgrades to "restart" upgrade, if possible.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#9
