### ISSUE TITLE
[Find Missing Settings] Ends In White Screen

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#105]
After this most recent update 4.0.2, when I run the 'find missing settings' it appears to run through them all, but then ends in a white screen instead of a 'completed' screen in admin section.

**Comment by Data66PF** [comment]
I've not seen this. For all of the sites I ran this on, it ended with a list of modules. Do you see errors with debug? Do you have mod_sec enabled? My live server does and didn't have an issue but perhaps if you have mod_sec it could be blocking the process somehow.
