### ISSUE TITLE
Dark block cover image background

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1050]
I think this is more an enhancement then a bug but I found that if I add a generic cover image with white in it all the white shows as off white/greyish due to the background color. I changed it to transparent and it solved the issue I have attached css code as per FF inspect element. It may be a good idea to change the black block to a generic image with no background that will show on all members pages until a cover image is added. This would solve any issues and also add a cool feature to add a generic image to all members with or without wording instructions on all members pages. See attached image and see white areas that were affected.

element {
}
.cover_shadown {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: 100px;
    top: auto;
    background: rgba(0, 0, 0, 0);
    background: -moz-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(19, 19, 19, 0.4) 100%);
    background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(0, 0, 0, 0)), color-stop(100%, rgba(19, 19, 19, 0.4)));
    background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(19, 19, 19, 0.4) 100%);
    background: -o-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(19, 19, 19, 0.4) 100%);
    background: -ms-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(19, 19, 19, 0.4) 100%);
    background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(19, 19, 19, 0.4) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#131313', GradientType=0);
    background: transparent;
}

![screenshot-one44 net 2016-02-01 14-57-50](https://cloud.githubusercontent.com/assets/13656046/12718303/6ffd4f7e-c8f6-11e5-95f7-12239b0d85e4.png)

**Comment by Data66PF** [comment]
Do you still see this issue with 4.2.1?

**Comment by one44** [comment]
Cannot say as I have setup new theme with my fix which works.
