### ISSUE TITLE
Footer spacing

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1051]
The footer spacing when more page links are added to footer is too far right. It starts a new line too quickly and divider falls on new line it looks odd.
![screenshot-one44 net 2016-02-01 15-36-15](https://cloud.githubusercontent.com/assets/13656046/12718890/3964274a-c8fa-11e5-802d-47e93a6fa898.png)
![screenshot-stage phpfox com 2016-02-01 15-32-09](https://cloud.githubusercontent.com/assets/13656046/12718893/3fa36f12-c8fa-11e5-95f8-bca70d330494.png)

**Comment by Data66PF** [comment]
Dealing only with the footer menu issue, this is as designed and I like it this way. I'm sure though that some will not like it this way and some will. The top menu issue is already resolved in 4.3 with a setting for how many menus to show before making a drop down explore menu tab. I'll move this to feature requests for the footer issue.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#61
