### ISSUE TITLE
[v4.2.0] Search button not working

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1052]
The search button is not working in v4.2.0.

**Comment by Data66PF** [comment]
Please always provide details when testing. What browser and OS? did you test the demo site?

**Comment by Spaninet** [comment]
Tested with Firefox 44 for Windows in:

- My dev site
- http://v4.phpfox.com/
- http://stage.phpfox.com/

**Comment by Spaninet** [comment]
Tested also with Internet Explorer 11.

**Comment by neil96** [comment]
That's just icon, not a button. We will discuss with team and consider change it to button.

**Comment by Spaninet** [comment]
Ok.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#8

**Comment by karargaht** [comment]
Hi, @Data66PF search word can not be translated. Do not you know?

![ssss](https://cloud.githubusercontent.com/assets/8930862/13156121/9756c618-d689-11e5-9576-dd1c3e184053.png)

**Comment by Spaninet** [comment]
Ok.
