### ISSUE TITLE
[v4.2.0] Profile Picture Cropping Tool

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1053]
The tool to crop pictures is not working well in v4.2.0. I can't move the selected area, make it larger or smaller.

Tested in demo site with Firefox 44.

**Comment by Spaninet** [comment]
This bug will be fixed in 4.3?

**Comment by neil96** [comment]
I tested but it's working with any sites I have (without our demo site). I think it only demo issue. Did it happen on your site?

**Comment by Spaninet** [comment]
Yes, it also happens on my site.

**Comment by robert9592** [comment]
Fixed in v4.3.0
