### ISSUE TITLE
v3 video streams

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1057]
any news about bringing the videos (for me only streams are important) from v3 to the new video app? 

this is so important... phpfox 4.2.0 is realy nice and would be even better when users can keep old items like those v3 video streams.

maybe it would be good to not store streams in feed but in an extra video table so we are able to move old streams in? even better would be to use the old table?

please make us happy devs! ;)

**Comment by Data66PF** [comment]
We've already got this on our list to look at but this area is not for feature requests as you have this in the forum already.
