### ISSUE TITLE
Changing Phrase text has no effect

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1058]
v4.20 Changing the phrase text, "The feature or section you are attempting to use is not permitted with your membership level." has no effect.

**Comment by Data66PF** [comment]
Please make sure to clear cache when changing anything on the site as every change seems to require cache clearing. If you cleared cache and still had no results, please let us know.

**Comment by lueung** [comment]
Yup. Cache was cleared and viewed on several different browsers. Same thing, it would always display, "The feature or section you are attempting to use is not permitted with your membership level."

**Comment by Data66PF** [comment]
I cannot reproduce this on the 4.2.1 staging server at https://stage.phpfox.com

**Comment by lueung** [comment]
Did you change the permission of the disallowed are and look at it as guest? The phrase is change inside the phrase manager, but it still displays, "The feature or section you are attempting to use is not permitted with your membership level." to the guest that is not allowed to access the particular area.

**Comment by neil96** [comment]
How many language are you using on site?
How many phrase "The feature or section you are attempting to use is not permitted with your membership level." you can see in adminCP?
You change don't effect may:
- Language you changed not the same with language user is using (in case you use many languages)
- Phrase duplicate (#897),

**Comment by lueung** [comment]
One one and it's the default setup.

**Comment by neil96** [comment]
I tested again, but I can't reproduce with default code.

**Comment by lueung** [comment]
OK it seems to be working now. Weird.
