### ISSUE TITLE
[Activity Feed] Using No Limit Creates A Loop

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#106]
If you don't enter a number in the display limit for Activity Feed (assuming you want to always have them all available for viewing), it creates an endless loop. When you get to the very first activity done, it goes back to the most recent and scrolls pas them all again.

![image](https://cloud.githubusercontent.com/assets/6254165/8702820/19b6a13a-2ae8-11e5-820c-fab1aa24fcb3.png)

Ideally, if you choose to not have a limit, it would recognize the very first ever activity, and stop there.

**Comment by Data66PF** [comment]
I can confirm this but boy this would be a heck of a heavy load on a site with a lot of activity. Better have a mega server if you do this.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
