### ISSUE TITLE
Report post

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1060]
The report post option only works with comments and not original posts in 4.2 tested on staging site.This means members cannot report inappropriate posts only comments.

**Comment by Data66PF** [comment]
confirmed that in v3 we could report on the main status post and in v4 we cannot. we need this to work. It works for a comment on the main status post but not on the main post itself. Here is an image from it working in v3:
![v3 report comment](https://cloud.githubusercontent.com/assets/6908282/12784288/33dd020a-ca54-11e5-9406-5c207103f54b.png)

**Comment by neil96** [comment]
Fixed on V4.3.0
