### ISSUE TITLE
Blogs don't line up correctly in V4.2.1

### ISSUE THREAD

**Issue by SpeakLife** [moxi9/phpfox#1064]
I upgraded from V4.0.9 to V4.2.1. When I click on blogs I am noticing that it doesn't line up the blogs correctly even when I switch to different filters.

https://speaklife.com/blog/

**Comment by Data66PF** [comment]
This is related to #449 the missing tag feature. Will bug this as it directly relates to that issue and I don't want to close this as it is not a duplicate.

**Comment by Data66PF** [comment]
A quick solution to this is to enable hashtags on the site in the database but that is not something we can post here as it could cause clients that don't know database stuff to mess up their sites. Plus, enabling hashtags disables normal tags for future use. You might need to wait for us to enable the tag feature (normal tag) in that other bug if you are not able to work in the database.

**Comment by robert9592** [comment]
Fixed in v4.3.0

Note: Feature normal tag (topic) isn't supported anymore, now we always use hashtags feature.

**Comment by Data66PF** [comment]
We need to keep tags. Those of us that use tags need them for our sites.

**Comment by Vivian-phpFox** [comment]
To use tags (Topics) feature for module (blog, forum), you much set "Enable Hashtags" = "No" (ACP --> Settings --> Tag)
