### ISSUE TITLE
[4.2.0(build 18)] Events are NOT displaying for Guest - Invite Only Site

### ISSUE THREAD

**Issue by NetworkCycles** [moxi9/phpfox#1065]
[4.2.0(build 18)] Events are NOT displaying for Guest - Invite Only Site
(Linux Server)

1. My site is an Invite only site.

2. Created several events with privacy set at EVERYONE can see.

3. When I sign out and visit my events page, I get > No events found.

4. My settings for Guest is to view and browse Events module.

5. Log back in and I can see all events????? 

Bug or am I just lost???

Guest View:
![log_out_events](https://cloud.githubusercontent.com/assets/13318857/12790308/af21e776-ca6f-11e5-91e7-a2e01694da75.png)

Members View: 
![login_events](https://cloud.githubusercontent.com/assets/13318857/12790316/b5d39362-ca6f-11e5-8228-0d57c5e9d7d7.png)

**Comment by Data66PF** [comment]
Please see if the site is set to Friends Only Community and if so, please set that setting to No or False.

**Comment by Data66PF** [comment]
https://stage.phpfox.com/event/ events seem to display there.

**Comment by Data66PF** [comment]
Please upgrade to 4.2.1 as you need to run the most current release.

**Comment by NetworkCycles** [comment]
Wow! FIXED.  

The site was set to Friends Only Community.
