### ISSUE TITLE
BUG?-Blocks can not be deactivated.

### ISSUE THREAD

**Issue by edwingrivera** [moxi9/phpfox#1066]
I tried to deactivate some of the blocks (i.e. tags or friends online) and is not changing in the HOME page or pages.  I deleted cache and also have changed settings (blocks section) numerous times and it is still not working. Is this a BUG?

**Comment by Data66PF** [comment]
I can't reproduce this on v4.2.1. Please make sure you are using 4.2.1 and please make sure your cache is clearing. It works fine for me.
