### ISSUE TITLE
4.2.1b1Terms of service page uneditable

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1067]
I like the new terms of service page, but it does not allow editing of the content when opening the editor form the admincp Page setup. Text cannot be deleted or changed.

**Comment by robert9592** [comment]
I cannot reproduce the issue on my test sites, can you provide more detail about this or give some screenshots?

**Comment by Gatsby-PF** [comment]
Hi robert9592, I may be trying to edit it wrong.  I go to admincp > pages which lists TOS and Privacy pages.  I access the edit icon for tos, and I am unable to edit the latin text therein. Cannot delete, cannot insert, nothing.  What procedure did you use to edit on your test servers?  Maybe I am doing it wrong?

**Comment by neil96** [comment]
I did the same your process, it work fine on my test site.
Which OS and browser are you using? I tested on Mac with Chrome and firefox.

**Comment by Data66PF** [comment]
I also cannot reproduce at the staging server using a mac with chrome.

**Comment by Gatsby-PF** [comment]
Slim odds... three against one. I used Firefox 44 but will try other browsers. This was a new install not a update so whatever it is, its definitely not update related.

**Comment by Gatsby-PF** [comment]
It worked with Chrome, but not with Firefox 44 with NoScript (but all site requirements enabled).

**Comment by neil96** [comment]
> Firefox 44 with NoScript
Did you disable javascript? phpFox can't run correctly without javascript. 
Browser support disable javascript only for debugging.

**Comment by Gatsby-PF** [comment]
Noscript was set to allow everything, nothing including javascript was blocked. FF was in private mode (doesnt record history but allows cookies). When I get the time I will check it further but there are much more important things to get out of the way first. I can at least edit it with Chrome at the moment.

**Comment by Data66PF** [comment]
Is this resolved?
