### ISSUE TITLE
4.2.1b1: No Javascript tooltips for upper right icons in bootstrap theme?

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1068]
#The notification and settings icons to the upper right do not have text as Neutron them did, therefore having no associated text in Bootstrap theme, should at least have Javascript tooltip tags (subject to language selected by user). Currently, no tooltips are presented when hovering over.

**Comment by Data66PF** [comment]
Note that marking an Enhancement does not mean it is an accepted feature. It is just being marked for categorizing these issue reports. When we open our feature request area, hopefully soon, these sort of requests will have pending/accepted/denied/implemented sort of statuses.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#7
