### ISSUE TITLE
[Friend Request] Can't View Pending Requests

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#107]
If you send a friend request to another user, it, removes the 'Add Friend' option, of course, but it would be nice to have a way to see that you actually have a request out for that person, and cancel it if you choose too. Currently, it leaves no friend options on their profile page and the request just dormant forever, assuming they don't check or see it.

**Comment by Data66PF** [comment]
confirmed that we have lost the Friends menu with the friend/pending and the friend/accept links for users to easily manage incoming and outgoing friend requests.
