### ISSUE TITLE
Terms and Privacy Not in Footer Menu

### ISSUE THREAD

**Issue by starplan** [moxi9/phpfox#1071]
I upgraded from phpFoX 4.2.0-brc to 4.2.0-b18 edited the terms and privacy pages but cannot add them to the menu because the "Add To Menu" radion button options are missing.

Browser Firefox v43
Windows 7

**Comment by Data66PF** [comment]
I edited your report. As the terms and privacy pages already exist, there would be no option to "add to menu" as that is only there when making a new page.

However, we have not added the terms and privacy links to the footer as they are required to be for any site. Team, please add the menus to the default script for terms and privacy.

**Comment by Gatsby-PF** [comment]
I got it to show ok in 4.2.1b1 footer by using menu edit to add new Terms of Use in footer location for url /terms. This was for the default new terms of use page that came with this release.

**Comment by robert9592** [comment]
Fixed in v4.3.0
