### ISSUE TITLE
Images in feedand featured Image

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1072]
When an image is clicked on it goes to open the image in large view but then just hangs until a manual refresh is done. V4.2.1 upgrade site ff  W10 Raul Lazar  has same issue.

**Comment by Data66PF** [comment]
Is this on the staging or demo? What theme? Any apps that could interfere? Any issues in debug or in browser developer console?

**Comment by one44** [comment]
Not in staging and bootstrap theme and I cannot get debug to work as it keeps saying page cannot be found. This is in dev console

GET 
https://syndication.twitter.com/widgets/timelines/paged/682834601614639104 [HTTP/2.0 200 OK 0ms]
17:14:21.056 GET 
XHR 
http://secure.skysa.com/chat/03/ [HTTP/1.1 200 OK 63099ms]
17:14:26.466 GET 
http://secure.skysa.com/tracker/read/ [HTTP/1.1 200 OK 433ms]
17:14:43.362 GET 
https://syndication.twitter.com/widgets/timelines/paged/682834601614639104 [HTTP/2.0 200 OK 0ms]
17:15:02.104 GET 
http://secure.skysa.com/tracker/read/ [HTTP/1.1 200 OK 320ms]
17:15:13.368 GET 
https://syndication.twitter.com/widgets/timelines/paged/682834601614639104 [HTTP/2.0 200 OK 405ms]
17:15:17.707 GET 
XHR 
http://one44.net/static/ajax.php [HTTP/1.1 200 OK 1544ms]
17:15:24.224 GET 
XHR 
http://secure.skysa.com/chat/03/

**Comment by Data66PF** [comment]
The debug should be at PF.Base/tools/debug.php but your site is not directing it to the right place. Please check that the folder was not removed and that it has the files in it from your download.

**Comment by Data66PF** [comment]
In the browser developer console, do you see any issues in the console tab when clicking an image?

**Comment by one44** [comment]
It is where it is suppose to be PF.Base/tools/debug.php  but keeps giving me the same error.The console 

This is what shows in console tab

ET 
XHR 
http://one44.net/static/jscript/jquery/plugin/imgnotes/jquery.tag.js [HTTP/1.1 200 OK 0ms]
17:29:46.345 GET 
XHR 
http://one44.net/module/photo/static/jscript/view.js [HTTP/1.1 200 OK 0ms]
17:29:46.349 GET 
XHR 
http://one44.net/module/photo/static/jscript/photo.js [HTTP/1.1 200 OK 0ms]
17:29:46.352 GET 
XHR 
http://one44.net/static/jscript/switch_legend.js [HTTP/1.1 200 OK 0ms]
17:29:46.355 GET 
XHR 
http://one44.net/static/jscript/switch_menu.js [HTTP/1.1 200 OK 0ms]
17:29:46.358 GET 
XHR 
http://one44.net/static/jscript/jquery/plugin/imgnotes/jquery.imgareaselect.js [HTTP/1.1 200 OK 0ms]
17:29:46.362 GET 
XHR 
http://one44.net/static/jscript/jquery/plugin/imgnotes/jquery.imgnotes.js

**Comment by Data66PF** [comment]
our techs will need to help more as I'm not sure of the issue. will go test on my windows machine.

**Comment by Data66PF** [comment]
I've tested on my win 10 with chrome and ff and even installed my skysa bar just in case that was conflicting but I can't reproduce any issue like you describe. Our techs will need to test further with windows perhaps. I don't have a twitter app on my dev to test with. What app is that one?

**Comment by one44** [comment]
I have a twitter feed app from twitter which shows the twitter feed but as two others seem to have the same issue I think it is something else.

**Comment by Data66PF** [comment]
We need the other client that can reproduce this, and any others, to please also post here.

**Comment by Data66PF** [comment]
Please test this in 4.3 when we release it this week.

**Comment by Data66PF** [comment]
Is this still an issue?

**Comment by one44** [comment]
Working after latest 4.1.3 upgrade
