### ISSUE TITLE
unable to delete notifications individually

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1073]
latest phpfox with  bootstrap and chrome
There is no option to  delete notifications individually. we do have a  delete button on the bottom but when we hover over it it says "delete all notifications" . 
![image](https://cloud.githubusercontent.com/assets/406030/12826404/2ede2766-cb7b-11e5-9762-0ff9d859cfd4.png)

**Comment by robert9592** [comment]
Fixed in v4.3.0
