### ISSUE TITLE
User approval signup dialog broken

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1075]
I invited a new test user under ad admin approval registration option. The test registrant makes it past the email verification step, the system sent an email saying thank you for joining. It then gives them no notice that admin approval is pending, and would not let him sign in.

**Comment by Data66PF** [comment]
Confirmed. The user has no idea at all they are pending approval after accepting the invite, joining the site, verifying the email.

**Comment by robert9592** [comment]
Fixed in v4.3.0
