### ISSUE TITLE
4.2.1b1 New block placments

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1076]
When opening the view sample block placement link in the block editor all I see are block
11,7,2,4,12 which are just vertically stacked blocks that span left to right.

There is nothing that identifies numbers of left side or right side blocks like pre bootstrap neutron did.

The drop down block number selector in new block setup goes from 1 to 13, which leaves 1,3,5,6,8,9,10,11 ambiguous as to where they will show up if you assign them.  Is it the intent that we have to determine this experimentally? If they cannot all be fit into the example layout screen there should be a doc in the KB as to where all these map out to on the screen.

**Comment by Data66PF** [comment]
We need to improve this. Before, it did show all the placements.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#6
