### ISSUE TITLE
4.2.1.b1 - translating categories do not work properly

### ISSUE THREAD

**Issue by Ramstete** [moxi9/phpfox#1078]
There is a problem about the translating categories on blogs, forum etc etc,
following the tutorial: https://docs.phpfox.com/display/FOX4MAN/Translating+Categories
it works just one time then nothing more

here some images as example:
Phrases: http://grabilla.com/06203-f1854533-8d55-42f6-9662-8c6db05ebedf.html
HTML Code: http://grabilla.com/06203-597303a6-46a8-4b13-9901-99f3f5741ab6.html
Pasting Code: http://grabilla.com/06203-3a8f5cee-2fce-4e91-9d70-7cc82684b217.html
The result: http://grabilla.com/06203-b5e429bc-8504-4b0f-a11c-7911da736cb7.html

First time it work fine now, then next ones do not work

**Comment by Data66PF** [comment]
In the community forum, you said this is working for you now. It appears to be working for me too. If this is fixed, please close your issue report or have us close it.

**Comment by Ramstete** [comment]
to me is working also today so if it is working for you too we can close it
