### ISSUE TITLE
Custom Fields not working properly in admin cp

### ISSUE THREAD

**Issue by lilman446** [moxi9/phpfox#108]
When trying to add new custom fields and select Multiple Selection, Radio or Checkbox it does not come up with an area to add the selections see image attached. As well with this issue if you select Selection you only get one space for a Selection then there is no way to add more Selections see attached photo #2. I think this would be considered only one issue but i will break it into two if needed.

![cutomfieldcheckbox](https://cloud.githubusercontent.com/assets/12124965/8703085/0996c08e-2ae1-11e5-8d9a-3f5e6c12f013.png)

![cutomfieldselection](https://cloud.githubusercontent.com/assets/12124965/8703099/1637227a-2ae1-11e5-920a-385845e847a2.png)

**Comment by Data66PF** [comment]
confirmed
