### ISSUE TITLE
[v4.2.1] Changed colors do not appear in mobile devices #1026 

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1080]
Although you already close this issue it seems like it did not fix it for me even though I upgraded.

I did revert theme and you are right it does erase all changes (lucky) I wrote them down. But, I the checked a mobile device as well as used your little icons for mobile and tablet (pretty cool) in theme and it still shows original blue color and not the dark color I picked. I did clear the cache and turned my cloudfare onto development to not cache at all. This is on a galaxy s5.  I also tried it on a friends phone as well and it didn't change.

**Comment by Spaninet** [comment]
#1026 This bug is not solved in v4.2.1, v4.2.1b2 and v4.2.1b5.

**Comment by karargaht** [comment]
Yes, 4.2.2 with the problem continues...

**Comment by neil96** [comment]
I refixed this issue on V4.3.0
