### ISSUE TITLE
Extra Claim Button when using previous suggestion/fix by data and fix #966 

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1081]
I have been using Pages Mini Menu since 4.09 suggested by data which fix the missing Claim button as well as the share button.  Now in Fix #966 they added another claim button in this latest fix so now I have a claim button and a like button on the bottom right corner of the cover image and for my site I also have in block 1 I have Pages Mini Menu which consist of "Share" and another claim button. So I have two claim buttons on one page.  I could disable the mini menu but that would take away the share button.

Maybe this could be fixed later on...no rush but although it looks nice having the claim button on the cover image it is only going to be click one person one time so why cover even a small portion of the image for something that may or may not be ever click or needed. I still want it on the page but it should be on a Pages Mini Menu like you have it where claim, share and report should all be. By the way where is the report button...did we ever have a report button on pages?

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#5
