### ISSUE TITLE
Bootstrap Theme - Login Button

### ISSUE THREAD

**Issue by Lidercan** [moxi9/phpfox#1083]
Login - Register Buttons on Header not visible with Mobil Version.

**Comment by PhpFoxJohnJr** [comment]
What phone are you using.  It is showing up on my Samsung Galaxy S5.  You need to click on the grey square box with 3 white horizontal line inside the box.  It will bring up your menu and your login and register box.

**Comment by Lidercan** [comment]
Each can not find it. It would be even better, if both buttons would  visible.  At web Version it looks good. Why not in mobile? There was a proposal.

**Comment by PhpFoxJohnJr** [comment]
I agree...as an improvement but there are bigger fish to fry right now...

**Comment by neil96** [comment]
Please post a request [here](https://github.com/moxi9/phpfox-feature-requests):
