### ISSUE TITLE
Dependency in Amazon

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#1085]
I love your Product but still expect more from you. I like the way with the new Chat where it stays in the same server but still I see a big dependency in amazon for video sharing so please fix this  some reasons to mention for the dependency.
1) We are thinking of running social networking site why should we get dependent in AMAZON one day we wish if we could change the hosting company or we could change our mind and Host it in our server how is that going to go if we are dependent in Amazon for video sharing.
2) If Amazon Servers get down or fail we to fail.
3)  If Amazon changed there mind change the price we are the one to get hurt because we have to no where to go to host our video like they do and our software is very dependent in Amazon.
4) We are working Hard to make our Social Networking So big and so famous what should we get dependent in Amazon?
5) I would like to host my date in my server soon or later why should I get dependent in AMAZON?
------ I am trying to see the future please fix this before it is to late for us.

**Comment by Data66PF** [comment]
Please post feedback in our community forum.
