### ISSUE TITLE
[v4.2.1] Duplicate themes when new theme is created

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1086]
I have created a new theme cloning Bootstrap from AdminCP and now I have 3 themes, the one i created (has different name) and other 2 with the same name, bootstrap.

This issue is in v4.2.1 (incluiding b2 and b5). I had this issue in previous version.

**Comment by PhpFoxJohnJr** [comment]
I mentioned this to data but it was suppose to be fixed I thought with 4.2.1.  Glad I did not try it again to test as it seems to mess things up when you attempt to delete them.

**Comment by Data66PF** [comment]
duplicate of #1024
