### ISSUE TITLE
[v4.2.1] Theme Manager Issue

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1087]
When I have set as default the theme I have created ( #1086 ), the css, html, ... is inaccessible, it is not loading when editing the theme.

**Comment by Data66PF** [comment]
Please post one issue per bug report. Issue 1 is a duplicate of #1025

**Comment by Spaninet** [comment]
I've opened a new bug report to separate the issues.

**Comment by Spaninet** [comment]
This issue is not a duplicate.

The duplicate one is this issue report that you have closed: #1086

**Comment by Spaninet** [comment]
![](https://community.phpfox.com/file/attachment/2016/02/08120281f51b2889e15340c80b7c98bf.png)

**Comment by Data66PF** [comment]
Please test in 4.2.2 and please follow the steps in the blog posted.

**Comment by Spaninet** [comment]
I have the latest version and followed the steps in KB before opening this issue.

**Comment by Data66PF** [comment]
We've made improvements to theme management in 4.3. Please test when we release it this week.

**Comment by Spaninet** [comment]
I will try again in the new version.

**Comment by neil96** [comment]
Duplicate with #1255
