### ISSUE TITLE
[v4.2.1] Phrases Missing in Phrases Manager

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1088]
These are some phrases missing in Phrases Manager:

In Videos page:
- All Videos
- My Videos
- Select a video to upload
- or paste a URL
- "Latest" and "Most viewed" in sort bar.

**Comment by Data66PF** [comment]
The phrases are there, from looking at the code, but they are hampered by this bug https://github.com/moxi9/phpfox/issues/1098 so I believe this will resolve once that bug is fixed. Our techs can confirm that though so I'll leave this open for them to double check the code.

**Comment by neil96** [comment]
On Video app, we are using new phrase method (function _p), but still some error with this function, so these phrase don't display in phrase manager. It will fixed in 4.3.0.

**Comment by robert9592** [comment]
Fixed in 4.3.0
