### ISSUE TITLE
[v4.2.1] Phrase Manager Issue

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1089]
Search by "Phrase Variable Name Only" option in Phrase Manager is not working and search by "Phrase Text and Phrase Variable Name" option is not working well when searching a phrase variable.

**Comment by Data66PF** [comment]
Please give specific examples as it worked both ways in my test. 4.2.1 build 5
![phrasevar](https://cloud.githubusercontent.com/assets/6908282/12916703/688b3c76-cf02-11e5-854a-430c079acb37.png)

**Comment by Spaninet** [comment]
![](https://community.phpfox.com/file/attachment/2016/02/59b0a836b2c5b936c341736107918f19.png)

**Comment by Spaninet** [comment]
Another example:

![](https://community.phpfox.com/file/attachment/2016/02/b30df69cc193242fa6261829569ba6de.png)

1) It is searchin Phrase text instead of the Phrase variable.

2) If you search for user.find with Phrase Variable Name Only option slected, it shows 28 pages, but if you search for the same text with Phrase Text and Phrase Variable Name Only option slected it shows 27 pages.

**Comment by neil96** [comment]
In phrase manager, search by var_name, we don't support search variable included module and var_name. Example, you want to search phrase user.find, please use advanced search, select module user, put "find" in search field. Please don't use user.find in search field.
