### ISSUE TITLE
Upgrade from v3 to v4

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#109]
I found this in error_log:
PHP Fatal error: Class 'ComposerAutoloaderInitcd249303bbe174d09af1b995ba7eafea' not found in /home/xxx/public_html/PF.Base/vendor/autoload.php on line 7

**Comment by Data66PF** [comment]
Are you installing the developer copy? If so, you need ssh access to the server or install locally and here are more instructions for installing locally, http://scripttechs.com/article/352/how-to-install-phpfox-v4-on-xampp-local/

**Comment by Ylmzef** [comment]
I followed the steps in this http://support.phpfox.com/upgrading-phpfox/manually-upload-files/
Its not developer copy, im trying upgrade from v3 to v4.

I tried fresh developer copy under /dev folder, its not working too.
Im getting "Installing app tables" more than 2 hour.

**Comment by Data66PF** [comment]
Does the server meet the new requirements?

**Comment by Ylmzef** [comment]
Server configuarions:
PHP 5.4 configuared with GD and CURLSSL also EXEC function enabled.
PHP memory_limit = -1
MySQL 5.5
Apache 2.4

**Comment by Data66PF** [comment]
I guess your server doesn't support composer. Perhaps Ray will have an answer when he sees this ticket.

**Comment by Ylmzef** [comment]
I have installed v4.0.0rc2 with success.

**Comment by Data66PF** [comment]
Please ensure that SQL strict mode is not enabled on your server.

**Comment by Ylmzef** [comment]
Its now fixed.
