### ISSUE TITLE
[v4.2.1] Info Page Disappeared From Members Profiles

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1090]
Info page disappeared when viewing profiles of friends and other members.

**Comment by raulw** [comment]
Same problem here, but just for new users, the old ones still have it.

**Comment by Data66PF** [comment]
I'll confirm as we appear to have removed the info page but that's not a good thing to have done if it was on purpose as that's where the info block is where the user group and other info was found.

**Comment by Data66PF** [comment]
http://scripttechs.com/file/attachment/2015/10/ff30058b78013001dd8462f124a48562.png that block used to appear on the profile info page, as well as custom fields which seem to go better there. Clients should be allowed an option to show an info tab if we are thinking to remove it as most of us use that page on our sites so we don't crowd the profile.index page with too much stuff.

**Comment by robert9592** [comment]
Fixed in v4.3.0
