### ISSUE TITLE
4.2.1b5 Marketplace Undefined Index

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1093]
Post in the community that clicking a marketplace item doesn't open it. I tested on dev and find that with debug enabled, we see the issue:

Failed to load component: marketplace.marketplace.view (/home/sitedetails/public_html/site/PF.Base/module/marketplace/include/component/block/marketplace/view/marketplace.class.php)
undefined

**Comment by Data66PF** [comment]
A temporary solution for now is to go to your block manager AdminCP >> Blocks and click marketplace.view and then disable (don't delete) the Categories block as it has an error.

**Comment by canbesocial** [comment]
I tried disabling, Marketplace still broken, unable to open any listing.
http://beta.canbesocial.com

**Comment by Data66PF** [comment]
The client in the forum confirmed that my suggestion to disable the marketplace category block is working fine for them and it is working on my tests. Please make sure you are using current 4.2.1 build 5 and that you can see the marketplace as your site shows no listings to guests so it is probably set to friends only community. I don't think you are speaking of the same issue this bug is for.

**Comment by RaymondBenc** [comment]
Fixed in 4.2.2.
