### ISSUE TITLE
[4.2.1b5] Sharing a picture on your friend's wall issue

### ISSUE THREAD

**Issue by MichelangeloF** [moxi9/phpfox#1094]
If you share a picture on your friend's wall the picture will appear on your wall too.

**Comment by neil96** [comment]
Can't reproduce on https://v4.phpfox.com - chrome - ubuntu. Could you give us more information. Thanks!

**Comment by MichelangeloF** [comment]
I have an upgraded site. 
Please try to share a pic from a fan page with a friend of yours and the image will go on your wall too.
Otherwise, maybe this problem affects upgraded sites only.

**Comment by neil96** [comment]
What is original version of your site?

**Comment by MichelangeloF** [comment]
I started from 4.0.1

**Comment by MichelangeloF** [comment]
Tried again now and It did the same thing.

**Comment by neil96** [comment]
Fixed on V4.3.0
