### ISSUE TITLE
pages images in main feed

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1096]
why do users see images from pages in main feed when not following the page? is this working as designed or a bug? since the group duplicate feature is no longer available in v4 the main feed is flooded with pics from pages but most users are not interested in them. imho they should only be there if a user follows the page.

**Comment by Data66PF** [comment]
A majority of clients want pages' posts to show in the feed.

**Comment by Data66PF** [comment]
You can set the page to private to members only and it would hide the posts from the feed.

**Comment by lordofnos** [comment]
ok but my users don´t use this option and i should turn this on and off in admincp. like i showed on v4.phpfox.com the feed is flooded for all users and i have uploaded only 26 images as page ;) do you think this is what they want. in such cases it would be nice to have either grouping of posts or an option to turn this of.

**Comment by Data66PF** [comment]
Please post feature requests at the forum as this is only for bugs. We will have a place for feature requests later and this has already been asked for so we will close this one for now.
