### ISSUE TITLE
unfollow page problem with feed

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1097]
when unfollowing a page with permission photo view set to "members only" and last photos in feed of that page are more than defined maximum feed entrys the feed is empty and view more link does not work anymore. it reloads a blank feed and shows again a view more link. reloading the page does not solve the problem. it is difficult to explain maybe i can make a video. is it possible to upload a video private?

**Comment by lordofnos** [comment]
btw clearing cache or login again also doesn´t solve this. the only way to get the main feed back to the user is by setting page permission back to "everyone"... this is a big problem.

**Comment by Data66PF** [comment]
Can you make a test at our demo https://v4.phpfox.com ?

**Comment by lordofnos** [comment]
i have uploaded 26 images in a testgroup. you have to unfollow this and watch the main feed. then unfollow und check back to the feed again. maybe this is only an issue when the post are on top of the feed... i don´t know. please tell me directly when following so i upload another bunch of photos to test...

**Comment by Data66PF** [comment]
It would have been considerable help to have included a link to your page.

**Comment by lordofnos** [comment]
v4.phpfox.com

**Comment by Data66PF** [comment]
weird bug but confirmed on our demo.

**Comment by robert9592** [comment]
Fixed in v4.3.0
