### ISSUE TITLE
New Phrases on apps

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1098]
Hi,

In the apps I'm developing I always use this code to show phrases:
_p('Very Fly Sample Phrase')

I need to create my own phrases, so I thought that by using that code all the phrases in my app would be created on the phrase manager during instalation. But I see now that no phrase are created in phrase manager and so my clients can't translate them.

Am I doint something wrong? How can I add my own phrases to phrase manager and make them being added to the phrase manager of my clients website when they install the app?

thanks

**Comment by Data66PF** [comment]
This is how it is designed. The way it works, if you use a phrase variable, it is supposed to be able to be added to the phrase manager. Please see the tutorial for using variables, https://docs.phpfox.com/display/FOX4DEVDOC/Phrases and please let us know if it doesn't work for you.

**Comment by Data66PF** [comment]
Actually, that might not be right as the original phrase you made should work as a phrase for translating, otherwise, why use it? We need to look at this process.

**Comment by cespiritual** [comment]
Yes... if it is not used to create a phrase in phrase manager I don't need to use it on the code, I just echo the phrase with plain text. Another thing I see, is that when I create a new phrase on the phrase manager I can assign that phrase to a module, but not to an app. So how to create new phrase for apps that can be added to phrase manager during instalation?

**Comment by neil96** [comment]
Hi @cespiritual ,
On V4.2.1, we have some issue with _p function. The phrase created, but it can't manage in AdminCP. We are fixing it.

**Comment by neil96** [comment]
Fixed on 4.3.0

**Comment by cespiritual** [comment]
How will this fixe work for the apps that are already installed? Will the system detect them and add it, or do we need to click in a link on the Maintenance menu to make it detect the phrases and add them to the phrase manager?

Thanks
