### ISSUE TITLE
Settings don't work after instalation

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1099]
Let see if I can explain this...

In the settings of my apps I have a usergroup setting to show the app only to some usergroups, and a general disabling setting that by default is set to "no" to show the app.

So on the start.php I have this:
if (!setting('disable_marketplace') && user('usergroup_marketplace')){

If my disabling setting is "no" and my usergroup setting is "yes" then the block will show. And it works fine.

The problem is that during instalation this settings are not set, and so the app don't show. I need to go to settings and in the Disable setting set it to "yes" and then back to "no" and in the usergroup setting set it to "no" and then back to "yes" and only then the variable will assume the value and show the app. But this should be set by default during instalation.

So I have clients that after installing the app write back to me saying that the app don't show, although the variables are set by default to make it show. So I have to explain them to do the enabling/disabling on the settings for it to work, and this is not a solution.

Thanks

**Comment by Data66PF** [comment]
Did you set the default values in the json? 
```
"myapp_enabled": {
			"info": "myapp Enabled",
			"type": "input:radio",
			"value": 1,
			"js_variable": true
		},
```

**Comment by cespiritual** [comment]
I have it set like this:
		"disable_marketplace": {
			"info": "Disable Marketplace App?",
			"type": "input:radio",
			"value": 0
		}

E see that on your example you have a "js_variable". Could that be the one that will make it work on instalation?

**Comment by Data66PF** [comment]
It works for me like that as I followed the example in one of the github examples beore,  but value 0 means disabled in your "value" setting.

**Comment by cespiritual** [comment]
I will try with the js_variable and see how it goes. Yes, it's 0 because it means That I don't want to disable it. So "yes" to disable and "no" to show.

**Comment by cespiritual** [comment]
I have tested with the js_variable and make some test instalations and the problem still exist. The apps don't show by default and I need to disable/enable the settings for it to show.

**Comment by Data66PF** [comment]
odd as it works on mine. This is a v4 app and not a v3 module, correct?

**Comment by Data66PF** [comment]
Ok I deleted my app and tested it again in 4.2.1 and, though it is set to True and to 1 for enabled in the json, for some reason it is defaulting to disabled (No). We've changed something here as this worked fine before.

**Comment by Data66PF** [comment]
looking at the settings I have for my app, all of my settings work as my code example showed except the setting to enable the app on install. It works to enable it after install. This could possibly be done by design so that apps that need settings added (ID, Key, etc) can have those added before being enabled so they don't break the site. I do notice that on install, the app settings are open for the user to set them so I think this is how it is designed now, for safety on the client's site to prevent breaking a site as mentioned.

**Comment by cespiritual** [comment]
But the setting that I use to enable and disable the app is just a normal setting. I could Have used it for other reason then enabling/disabling the app. 

Because my setting is by default 0, then the problem is not here, but in the usergroup that by default is 1, and that after installl it is set to 0 ... Do you also use usergroup setting on your app? And after install is it set to 1 or 0 ?

**Comment by Data66PF** [comment]
Yes I have user group settings too. We are looking at this issue though

**Comment by RaymondBenc** [comment]
In your start.php, look for your line
```
if (!setting('disable_marketplace') && user('usergroup_marketplace')){
```
Replace with
```
if (!setting('disable_marketplace') && user('usergroup_marketplace', true)){
```
This should resolve your issue. For the **user()** function we need to pass a 2nd argument in order for the function to respect the default value. This function works a little different in comparison to the **setting()** function.

**Comment by cespiritual** [comment]
Thanks Raymond.. I will test it. And don't forget to add this information into the tutorial about usergroups.
