### ISSUE TITLE
Popup Messenger Window Does Not Adjust

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1100]
After clicking on the green button to popup the messenger in a new window, resizing the browser window does not adjust the messenger window.

**Comment by Data66PF** [comment]
Please always state the os, browser when posting.

I cannot reproduce this on a macbook pro El Capitan os, chrome browser.

**Comment by Spaninet** [comment]
### It does not adapt in mobile devices with small screens.

1. Clic in the IM icon and select a conversation.

![](https://community.phpfox.com/file/attachment/2016/02/3b80794e14693b0cb01a3f8d91477458.png)

The IM popup adapts to the screen.

2. Go back

When you go back the popup it does not adapt to the screen.

##### Tested on an 5" Android device with Firefox 44

**Comment by neil96** [comment]
Can you reproduce this issue on 4.3.2b3?

**Comment by Spaninet** [comment]
I haven't seen the last message.

I can reproduce this issue on last version (4.3.2b5).

**Comment by neil96** [comment]
OK, please give us detail steps to reproduce. Thanks!

**Comment by neil96** [comment]
I am waiting your reproduce steps.

**Comment by Spaninet** [comment]
See this video:

http://demo.tecnobina.com/XiaoYing_Video_1464782014731.mp4

1) From homepage go to an other page (Members, Video, Quiz, etc).

2) Click on IM App.

3) Select a conversation and then

4) Tap/Press the "Back button" on Android or the go back button in any browser/os

You will see that the pop-up does not adapt to the scree.

**Comment by neil96** [comment]
I tested with your steps you gave, but I can't reproduce. Could you test again.

**Comment by Spaninet** [comment]
Why is labeled "No Response"? Why closing this issue?

I have provided steps two times and a video where you can see clearly the issue. I have tested several times and still can reproduce this issue.

Tested last time in Stage (http://v4.phpfox.com/stage).

**Comment by neil96** [comment]
I can't reproduce this issue, even in your video, I can't see error.

**Comment by Spaninet** [comment]
You can see the error in minute 0:43 when I tap the 'Back' button in an Android device. You will see that the pop up doesn't fit the screen.

Browser: 🔥 Firefox and 🌐 Chrome
