### ISSUE TITLE
Installing Younetco v3 Contact Importer & then Uninstall causes site to go 500 internal error

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1101]
Even tho the phpfox document says it's ok to install v3 apps, Installing and then uninstalling Younetco's v3 Contact Importer module causes the phpfox4 site to go down and throws a 500 internal error.

What's the procedure to get the site it back up?

**Comment by neil96** [comment]
Contact importer from Younetco supported for V4 (https://store.phpfox.com/product/872/younet-contact-importer), why you don't install it?
This is bug tracker for phpFox core only. You can create new ticket from younetco, they will help you.
