### ISSUE TITLE
Explorer Tab Shifts Down

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#1102]
The explorer menu shouldn't shift down. I think this is a bug.
![glitch_menu](https://cloud.githubusercontent.com/assets/14006326/12907426/46d86890-ceb9-11e5-9f9f-80b340dd3934.png)

**Comment by Data66PF** [comment]
The explore menu is there to have the extra menus in it such as your knowlege base, auction, coupons, business directory, etc. Did you move them out of it?

**Comment by Data66PF** [comment]
We had a bug before regarding the inability to manage menus like we had in V3. We can't even see the Explore menu in AdminCP menu manager. I'll confirm this as there is no way to manage the menus. If we can't see the Explore menu, we cannot manage menus to put in it and make the site look better.

**Comment by ASNLifestyle** [comment]
No I did not move anything.

**Comment by neil96** [comment]
Fixed on V4.3.0.
Note: https://community.phpfox.com/forum/thread/54221/explorer-tab-on-main-menu/

**Comment by zohaibzobi2727** [comment]
How can we add drop down menu other than explorer?

There was an option for sub-menu in v3 which is no longer available in v4.

Any best solution?
