### ISSUE TITLE
Homepage banner not rotating for uploaded banners

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1103]
Upgraded site. Using a custom theme or default bootstrap. Posting per issue in community. Note that Rebuild core theme was run.

Upload some banners in the edit theme Homepage section.

Visit in chrome, safari, firefox but these are not rotating.

Delete all of those you loaded and instead feature some photos and you can see these rotate. The broken thing is the uploaded banners. This worked prior to this 4.2.1 build 5.

**Comment by Miroslav36** [comment]
I can confirm that featured photos rotate but photos uploaded via theme editor do not rotate for me as well (v 4.1.2 b5)

**Comment by PhpFoxJohnJr** [comment]
V4.2.1 the image rotates but it stutters.  It shows the original image and then quickly switches to the next one.  Sometimes it just stays on one image...very erratic and not smooth like 4.09.
