### ISSUE TITLE
Video Hides All Videos if Feed is at Friends Only

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1107]
Video app, 4.2.1. Using youtube shared videos. Posting at a client's request.

Set Feed to Friends Only. Log in as a non friend of the admin. Admin has previously shared several Youtube videos via the video section (not via loading them in the status). 

As a non friend registered user, you cannot see any videos.

Disable the friends only feed and now the registered user can see the videos. This setting should not impact the video section. It should only impact videos in the feed itself as it only should filter feed items.

**Comment by RaymondBenc** [comment]
Fixed in 4.3.0
