### ISSUE TITLE
[4.2.1] Repositioned Covers Issue

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1108]
Only a very small portion of the repositioned covers appear on mobile devices.

**Comment by Data66PF** [comment]
Please open one issue per report as we create a task per bug and need to put our revision numbers. Next time, please keep it to just one issue as we have asked. Thanks.

**Comment by Data66PF** [comment]
can't reproduce in iPhone 5c using standard sized cover photo image.
phone:
![img_0161](https://cloud.githubusercontent.com/assets/6908282/12975105/14f2c120-d087-11e5-8302-aaa3a8adb572.PNG)
desktop:
![pagecover](https://cloud.githubusercontent.com/assets/6908282/12975109/22a2943a-d087-11e5-8684-dacd80989945.png)

**Comment by optiroot** [comment]
I can confirm this.

Sometimes it shows all the photo with black below it (you can see the block near "Unlike") and sometimes it just shows the 50% of the cover. The rest is pushed up.

**Comment by neil96** [comment]
I saw the problem.

**Comment by Spaninet** [comment]
![](https://community.phpfox.com/file/attachment/2016/02/bc7cc0d02ebb489c2dbf485f5353931c.png)

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#60
