### ISSUE TITLE
Add Currency Brings Array to String Conversion

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1109]
v4.2.1  build 5. Debug is enabled as the adding currency is not working. 

Try to add:
Indian Rupee

Currency ID: INR
Symbol: I tried all of the following and none worked
``` &#8377;  ```
  ₹   
  ``` U+20B  ```
 8377 
Phrase: Indian Rupee

When you submit that, you get the array to string conversion
Exception thrown with message "Array to string conversion"

Stacktrace:
#13 Exception in /home/mysite/web/mysite/public_html/mysite/PF.Base/start.php:291
#12 Whoops\Exception\ErrorException in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/database/dba.class.php:688
#11 Whoops\Run:handleError in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/database/dba.class.php:688
#10 Phpfox_Database_Dba:insert in /home/mysite/web/mysite/public_html/mysite/PF.Base/module/core/include/service/currency/process.class.php:95
#9 Core_Service_Currency_Process:add in /home/mysite/web/mysite/public_html/mysite/PF.Base/module/core/include/component/controller/admincp/currency/add.class.php:41
#8 Core_Component_Controller_Admincp_Currency_Add:process in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:1006
#7 Phpfox_Module:getComponent in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:531
#6 Phpfox_Module:getController in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:318
#5 Phpfox_Module:setController in /home/mysite/web/mysite/public_html/mysite/PF.Base/module/admincp/include/component/controller/index.class.php:681
#4 Admincp_Component_Controller_Index:process in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:1006
#3 Phpfox_Module:getComponent in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:531
#2 Phpfox_Module:getController in /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1325
#1 Phpfox:run in /home/mysite/web/mysite/public_html/mysite/PF.Base/start.php:245
#0 require in /home/mysite/web/mysite/public_html/mysite/index.php:7

**Comment by RaymondBenc** [comment]
Fixed in 4.2.2.
