### ISSUE TITLE
[Block Columns] Possible To Adjust Column Widths?

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#111]
I couldn't find a place to do this so not sure if there is one. Is it possible to adjust the widths of columns? A common adsense width for their square ad is 336 width and some of the main widths of the site are at 300. It would be cool if we could adjust those widths so we can fit in those ad types (and other future mods/plugins that might need specific widths. :)

**Comment by Data66PF** [comment]
http://support.phpfox.com/themes/getting-started/ use that to make your own theme so you don't edit default as it's not recommended to edit default. Then go to AdminCP >> Themes and click on your theme. On the main edit screen scroll down until you see the settings for the column widths.

**Comment by RaymondBenc** [comment]
When editing your custom theme you can try to change the **Columns** variables, where by default **300px** is set for **columnWidth**.
