### ISSUE TITLE
v4.2.2 uploading a large photo to the cover increases height of the cover photo area

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1112]
When uploading a large photo to the cover photo area, it increases the height of the cover photo area on the profile page.

**Comment by Data66PF** [comment]
This has always worked like this.

**Comment by Data66PF** [comment]
Perhaps I don't understand the issue though. Using a normal cover size, http://kb.scripttechs.com/cover-image-for-phpfox/ do you see a different look than if you load some other size? If you do, what size are you loading so we can test?

**Comment by lueung** [comment]
So this is what I get when I look @ firefox image info and I see why there is a height increase vs no cover picture. "1,024px × 389px (scaled to 1,318px × 501px)"

**Comment by robert9592** [comment]
Do you mean that the height of the cover photo area increases after upload cover photo (the height is different between no-cover and has-cover)? If yes, this is not a bug, it works as designed.
