### ISSUE TITLE
v4.2.2 registration form at home page needs fixing

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1113]
1. The "Please reenter your email again below."  is nearly the same color as the background so very hard to see.

2. "Force Users to Reenter Email" on settings -> registration breaks registration form

3. Too much space in between each of the inputs.

4. No password confirmation option

People sometimes mistype their password only to find out they can't login. So option to re-enter password is needed during registration.

**Comment by Data66PF** [comment]
Please note that we need one issue per report as we have internal tasks we assign, revision numbers we make. Please separate these issues for us to check.

**Comment by lueung** [comment]
ok done

**Comment by Data66PF** [comment]
ok which one are you keeping in this one? if you opened a new one for each of the above and if this one isn't needed because of that, please feel free to close it.
