### ISSUE TITLE
"Force Users to Reenter Email" on settings -> registration breaks registration form

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1118]
If the "Force Users to Reenter Email" is enabled it breaks the registration form

**Comment by Data66PF** [comment]
Please give more info. Please always include browser and os you are testing with. Please include a screen shot for this one. 

It is unclear if you mean it breaks the design (I cannot reproduce this other than your other bug report) or if you mean it breaks the function of the form (user can't join).

**Comment by lueung** [comment]
I believe the "too much space" between registration inputs bug encompasses this issue so I'll close.
