### ISSUE TITLE
Member Profiles and pages does not work

### ISSUE THREAD

**Issue by ancelsan** [moxi9/phpfox#1119]
I have received a number of my site's users complain that the pages created by them do not work, always gives error. Another type of complaint that have arrived in my e-mail, is that new users are signing up and just can not get into their profiles. Nor can they, nor anyone can etrar, always gives error. I complained to the server, which is one of the best working with phpFox, and asked me to seek the support of phpFox to report the problem, because They analyzed and not with a server not. Here are some links below that exhibit this problem:

_http://orbati.com/fb-969415643128142/
_http://orbati.com/profile-25285/
_http://orbati.com/pages/114/
_http://orbati.com/pages/116/
_http://orbati.com/pages/115/

**Comment by Data66PF** [comment]
You are hosting with phpfoxsolutions?

I do see you are using cloudflare. Make sure your settings are correct and that you are not caching javascript and css.

**Comment by ancelsan** [comment]
Yes, my site is hosted in solutions phpFox, and all the cloudflare
configuration
has been done for them.

2016-02-13 13:58 GMT-03:00 Data66 <notifications@github.com>:

**Comment by Data66PF** [comment]
We can only handle one issue at a time. The CSS issue or the Pages / Profile feed issue. Please put only one bug in at a time. As I see a lot of errors on your site due to a google ad. I also see some embedded soundcloud javascript. Please remove any edits you have done, any ads, any embeds and please try the site with unedited default theme.

**Comment by Data66PF** [comment]
Please also try without that language pack as default as it has errors on the translations causing odd issues that I see in the pages categories for one.

**Comment by Data66PF** [comment]
Please disable cometchat for testing also as several clients have issues with it not working in this version. Basically, as your site is the only one with this issue, you need to troubleshoot with disabling things that are not standard to our script.

**Comment by ancelsan** [comment]
I did as you suggested! I withdrew the ads and reverted to the default theme
. I reitrei the cometchat and set as default theme English. But the biggest
audience of my website speaks in Portuguese. After I change into Portuguese?

2016-02-13 19:24 GMT-03:00 Data66 <notifications@github.com>:

**Comment by Data66PF** [comment]
Does it work with the things disabled? Other than a database issue I see at the moment, once that is resolved, please let us know if it works. If it does, then you could enable one thing at a time, checking to see if it works after adding. Such as, once you see if it is working with things disabled, then try enabling the language and see if it still works. If it does, try enabling one more thing and test again.

**Comment by Data66PF** [comment]
@neil96 we need someone to check this sort of issue if possible. It's rather odd as the pages load if the feed is disabled. If it is enabled, the pages do not load.

**Comment by Data66PF** [comment]
Please send us a ticket with admincp log in details and server ftp and phpmyadmin if you don't have cpanel. If you have cpanel, please send us that. Please go here, https://clients.phpfox.com/ which is our new client area and you will need to create a new password if you've not been logged in before to that area as it's new. Use your normal email that you use in the old client area. You can then send us a ticket with the details we need.

**Comment by Data66PF** [comment]
Issue is from a third party product, YouNet Feed Hooking. Please contact the vendor for assistance with this issue. Perhaps you need an updated product.
