### ISSUE TITLE
White page on install on step=language

### ISSUE THREAD

**Issue by kginstructor** [moxi9/phpfox#112]
Did a clean install from github, installation goes to a white screen after installing the DB and moving to language step. After stracing the httpd processes, I found this:

19612 sendto(17, "\274\0\0\0\3SELECT t.*, ts.style_id AS flavor_id, ts.folder AS flavor_folder\nFROM phpfox_theme AS t\nJOIN phpfox_theme_style AS ts\n\tON( t.theme
_id = ts.theme_id)\n\nWHERE t.theme_id = '0'\n/* OO Query */", 192, 0, NULL, 0) = 192
19612 recvfrom(17, "\1\0\0\1\r9\0\0\2\3def\6phpfox\1t\fphpfox_theme\10theme_id\10theme_id\f?\0\4\0\0\0\2+B\0\0\0;\0\0\3\3def\6phpfox\1t\fphpfox_theme\tparent_id\tpa
rent_id\f?\0\4\0\0\0\2!\0\0\0\0001\0\0\4\3def\6phpfox\1t\fphpfox_theme\4name\4name\f\10\0K\0\0\0\375\1\20\0\0\0005\0\0\5\3def\6phpfox\1t\fphpfox_theme\6folder\6fold
er\f\10\0K\0\0\0\375\tP\0\0\0007\0\0\6\3def\6phpfox\1t\fphpfox_theme\7created\7created\f?\0\n\0\0\0\3!\20\0\0\0007\0\0\7\3def\6phpfox\1t\fphpfox_theme\7creator\7cre
ator\f\10\0\377\0\0\0\375\0\0\0\0\0007\0\0\10\3def\6phpfox\1t\fphpfox_theme\7website\7website\f\10\0\377\0\0\0\375\0\0\0\0\0007\0\0\t\3def\6phpfox\1t\fphpfox_theme\
7version\7version\f\10\0\n\0\0\0\375\0\0\0\0\0;\0\0\n\3def\6phpfox\1t\fphpfox_theme\tis_active\tis_active\f?\0\1\0\0\0\1\t@\0\0\0=\0\0\v\3def\6phpfox\1t\fphpfox_the
me\nis_default\nis_default\f?\0\1\0\0\0\1\1\0\0\0\0A\0\0\f\3def\6phpfox\1t\fphpfox_theme\ftotal_column\ftotal_column\f?\0\1\0\0\0\1\1\0\0\0\0A\0\0\r\3def\6phpfox\2t
s\22phpfox_theme_style\tflavor_id\10style_id\f?\0\4\0\0\0\2+B\0\0\0C\0\0\16\3def\6phpfox\2ts\22phpfox_theme_style\rflavor_folder\6folder\f\10\0K\0\0\0\375\tP\0\0\0\
5\0\0\17\376\0\0\2\0\5\0\0\20\376\0\0\2\0", 16384, 0, NULL, NULL) = 830
19612 stat("/var/repos/ruletheseas/phpfox/PF.Base/vendor/dereuromark/media-embed/src/Core/Exception.php", 0x7ffe632d60b0) = -1 ENOENT (No such file or directory)
19612 lstat("/var/repos/ruletheseas/phpfox/PF.Base/../PF.Src/Core/Exception.php", {st_dev=makedev(253, 0), st_ino=1728125, st_mode=S_IFREG|0664, st_nlink=1, st_uid=
1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=652, st_atime=2015/07/15-15:12:18, st_mtime=2015/07/14-13:18:30, st_ctime=2015/07/15-14:56:38}) = 0
19612 open("/var/repos/ruletheseas/phpfox/PF.Src/Core/Exception.php", O_RDONLY) = 18

So, it's running this query:

SELECT t.*, ts.style_id AS flavor_id, ts.folder AS flavor_folder
FROM phpfox_theme AS t
JOIN phpfox_theme_style AS ts
	ON( t.theme_id = ts.theme_id)
	
WHERE t.theme_id = '0'
/* OO Query */

Nothing is being returned. So it throws an uncaught exception and dies with a 500 error. Unfortunately, this never gets logged anywhere, making it a pain to track down.

I added a row in both phpfox_theme and phpfox_theme_style with theme_id = 0 and then ?step=language returned:

{"message":"Setting up apps","next":"module"}

instead of a blank 500 error. However... by that point, the installation page is broken and refreshing returns to selecting the licensing step and you can't continue past the DB setup, as it can't handle the DB already being setup. Deleting the DB introduces the original error, ie missing default theme rows.

**Comment by juggalobook** [comment]
+1

**Comment by kginstructor** [comment]
After adding PF.Base/includes/settings/dev.sett.php, now I get this:

Whoops \ Exception \ ErrorException (E_USER_ERROR)
HELP
Query Error:Field 'folder' doesn't have a default value [INSERT INTO phpfox_theme (name, website, created, is_active) VALUES ('Neutron', NULL, '1437404068', '1')]

**Comment by kginstructor** [comment]
commit 22789ec87d727bad0daa788549250ba8b8e7c5d2
Author: Jay Ward <killinggameinstructor@gmail.com>
Date:   Mon Jul 20 14:01:37 2015 -0400

    Changing several columns to allow for NULL, otherwise install errors out since the columns don't allow for null and don't have a default value. Either will do, I just found it easier to allow for null rather than specify "" as default

diff --git a/PF.Base/module/theme/install/phpfox.xml.php b/PF.Base/module/theme/install/phpfox.xml.php
index 18100e8..6f02b19 100644
--- a/PF.Base/module/theme/install/phpfox.xml.php
+++ b/PF.Base/module/theme/install/phpfox.xml.php
@@ -255,5 +255,5 @@
        <user_group_settings>
                <setting is_admin_setting="0" module_id="theme" type="boolean" admin="1" user="1" guest="1" staff="1" module="theme" ordering="0">can_view_theme_sample</setting>
        </user_group_settings>
-       <tables><![CDATA[a:6:{s:12:"phpfox_theme";a:3:{s:7:"COLUMNS";a:11:{s:8:"theme_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"parent_id";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"created";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"creator";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"website";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"version";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"is_active";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:10:"is_default";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:12:"total_column";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"2";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:8:"theme_id";s:4:"KEYS";a:3:{s:9:"is_active";a:2:{i:0;s:5:"INDEX";i:1;s:9:"is_active";}s:8:"theme_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"theme_id";i:1;s:9:"is_active";}}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}}s:16:"phpfox_theme_css";a:3:{s:7:"COLUMNS";a:11:{s:6:"css_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"module_id";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"product_id";a:4:{i:0;s:8:"VCHAR:25";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"is_custom";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"file_name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:8:"css_data";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:17:"css_data_original";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"full_name";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"time_stamp";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:17:"time_stamp_update";a:4:{i:0;s:7:"UINT:10";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:6:"css_id";s:4:"KEYS";a:3:{s:8:"style_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"style_id";i:1;s:9:"file_name";}}s:10:"style_id_2";a:2:{i:0;s:5:"INDEX";i:1;s:8:"style_id";}s:9:"is_custom";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"is_custom";i:1;s:8:"style_id";}}}}s:18:"phpfox_theme_style";a:2:{s:7:"COLUMNS";a:15:{s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:8:"theme_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"parent_id";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:9:"is_active";a:4:{i:0;s:6:"TINT:1";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:10:"is_default";a:4:{i:0;s:6:"TINT:1";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"created";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"creator";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"website";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"version";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"logo_image";a:4:{i:0;s:8:"VCHAR:50";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"l_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:7:"c_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:7:"r_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:4:"KEYS";a:6:{s:10:"style_id_2";a:2:{i:0;s:6:"UNIQUE";i:1;s:8:"style_id";}s:8:"style_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"style_id";i:1;s:9:"is_active";}}s:9:"is_active";a:2:{i:0;s:5:"INDEX";i:1;s:9:"is_active";}s:9:"parent_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"parent_id";i:1;s:9:"is_active";}}s:10:"is_default";a:2:{i:0;s:5:"INDEX";i:1;s:10:"is_default";}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}}s:23:"phpfox_theme_style_logo";a:2:{s:7:"COLUMNS";a:4:{s:7:"logo_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:4:"logo";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:8:"file_ext";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:7:"logo_id";}s:21:"phpfox_theme_template";a:3:{s:7:"COLUMNS";a:12:{s:11:"template_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"is_custom";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"type_id";a:4:{i:0;s:8:"VCHAR:20";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:10:"product_id";a:4:{i:0;s:8:"VCHAR:25";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"module_id";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"html_data";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:18:"html_data_original";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"full_name";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"time_stamp";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:17:"time_stamp_update";a:4:{i:0;s:7:"UINT:10";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:11:"template_id";s:4:"KEYS";a:4:{s:8:"theme_id";a:2:{i:0;s:5:"INDEX";i:1;a:3:{i:0;s:6:"folder";i:1;s:7:"type_id";i:2;s:4:"name";}}s:10:"theme_id_2";a:2:{i:0;s:5:"INDEX";i:1;a:4:{i:0;s:6:"folder";i:1;s:7:"type_id";i:2;s:9:"module_id";i:3;s:4:"name";}}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}s:9:"is_custom";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"is_custom";i:1;s:6:"folder";}}}}s:18:"phpfox_theme_umenu";a:3:{s:7:"COLUMNS";a:3:{s:8:"umenu_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:7:"user_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"menu_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:8:"umenu_id";s:4:"KEYS";a:2:{s:7:"user_id";a:2:{i:0;s:5:"INDEX";i:1;s:7:"user_id";}s:9:"user_id_2";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:7:"user_id";i:1;s:7:"menu_id";}}}}}]]></tables>
-</module>
\ No newline at end of file
+       <tables><![CDATA[a:6:{s:12:"phpfox_theme";a:3:{s:7:"COLUMNS";a:11:{s:8:"theme_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"parent_id";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:0:"";}s:7:"created";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:0:"";}s:7:"creator";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"website";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"version";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"is_active";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:10:"is_default";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:12:"total_column";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"2";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:8:"theme_id";s:4:"KEYS";a:3:{s:9:"is_active";a:2:{i:0;s:5:"INDEX";i:1;s:9:"is_active";}s:8:"theme_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"theme_id";i:1;s:9:"is_active";}}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}}s:16:"phpfox_theme_css";a:3:{s:7:"COLUMNS";a:11:{s:6:"css_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"module_id";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"product_id";a:4:{i:0;s:8:"VCHAR:25";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"is_custom";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"file_name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:8:"css_data";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:17:"css_data_original";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"full_name";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"time_stamp";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:17:"time_stamp_update";a:4:{i:0;s:7:"UINT:10";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:6:"css_id";s:4:"KEYS";a:3:{s:8:"style_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"style_id";i:1;s:9:"file_name";}}s:10:"style_id_2";a:2:{i:0;s:5:"INDEX";i:1;s:8:"style_id";}s:9:"is_custom";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"is_custom";i:1;s:8:"style_id";}}}}s:18:"phpfox_theme_style";a:2:{s:7:"COLUMNS";a:15:{s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:8:"theme_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"parent_id";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:9:"is_active";a:4:{i:0;s:6:"TINT:1";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:10:"is_default";a:4:{i:0;s:6:"TINT:1";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:0:"";}s:7:"created";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:0:"";}s:7:"creator";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"website";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"version";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"logo_image";a:4:{i:0;s:8:"VCHAR:50";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:7:"l_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:7:"c_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:7:"r_width";a:4:{i:0;s:5:"USINT";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:4:"KEYS";a:6:{s:10:"style_id_2";a:2:{i:0;s:6:"UNIQUE";i:1;s:8:"style_id";}s:8:"style_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:8:"style_id";i:1;s:9:"is_active";}}s:9:"is_active";a:2:{i:0;s:5:"INDEX";i:1;s:9:"is_active";}s:9:"parent_id";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"parent_id";i:1;s:9:"is_active";}}s:10:"is_default";a:2:{i:0;s:5:"INDEX";i:1;s:10:"is_default";}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}}}s:23:"phpfox_theme_style_logo";a:2:{s:7:"COLUMNS";a:4:{s:7:"logo_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:8:"style_id";a:4:{i:0;s:5:"USINT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:4:"logo";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:8:"file_ext";a:4:{i:0;s:8:"VCHAR:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:7:"logo_id";}s:21:"phpfox_theme_template";a:3:{s:7:"COLUMNS";a:12:{s:11:"template_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:9:"is_custom";a:4:{i:0;s:6:"TINT:1";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}s:6:"folder";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:0:"";}s:7:"type_id";a:4:{i:0;s:8:"VCHAR:20";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:10:"product_id";a:4:{i:0;s:8:"VCHAR:25";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"module_id";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:4:"name";a:4:{i:0;s:8:"VCHAR:75";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:9:"html_data";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:18:"html_data_original";a:4:{i:0;s:5:"MTEXT";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:9:"full_name";a:4:{i:0;s:9:"VCHAR:255";i:1;N;i:2;s:0:"";i:3;s:3:"YES";}s:10:"time_stamp";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:17:"time_stamp_update";a:4:{i:0;s:7:"UINT:10";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:11:"template_id";s:4:"KEYS";a:4:{s:8:"theme_id";a:2:{i:0;s:5:"INDEX";i:1;a:3:{i:0;s:6:"folder";i:1;s:7:"type_id";i:2;s:4:"name";}}s:10:"theme_id_2";a:2:{i:0;s:5:"INDEX";i:1;a:4:{i:0;s:6:"folder";i:1;s:7:"type_id";i:2;s:9:"module_id";i:3;s:4:"name";}}s:6:"folder";a:2:{i:0;s:5:"INDEX";i:1;s:6:"folder";}s:9:"is_custom";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:9:"is_custom";i:1;s:6:"folder";}}}}s:18:"phpfox_theme_umenu";a:3:{s:7:"COLUMNS";a:3:{s:8:"umenu_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:14:"auto_increment";i:3;s:2:"NO";}s:7:"user_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}s:7:"menu_id";a:4:{i:0;s:7:"UINT:10";i:1;N;i:2;s:0:"";i:3;s:2:"NO";}}s:11:"PRIMARY_KEY";s:8:"umenu_id";s:4:"KEYS";a:2:{s:7:"user_id";a:2:{i:0;s:5:"INDEX";i:1;s:7:"user_id";}s:9:"user_id_2";a:2:{i:0;s:5:"INDEX";i:1;a:2:{i:0;s:7:"user_id";i:1;s:7:"menu_id";}}}}}]]></tables>
+</module>
