### ISSUE TITLE
Sharing does not work the first time

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1120]
![page](https://cloud.githubusercontent.com/assets/8930862/13026966/efe1cba0-d244-11e5-985c-2fa892cbaf22.png)

The same problem also applies to mobile.

Version: 4.2.2

**Comment by Data66PF** [comment]
Does it work for you on our demo https://v4.phpfox.com ? If not, what browser and os?

**Comment by karargaht** [comment]
It happens occasionally

Mobile and PC browser Chrome, win10

**Comment by Data66PF** [comment]
Please, what mobile device?

**Comment by karargaht** [comment]
LG G4, fortunately not very important
