### ISSUE TITLE
Top text on registration is same as the submission button

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1121]
The top text at the top of the registration section on the home page is the same as the submission button at the bottom.

**Comment by Data66PF** [comment]
When leaving bugs like this, please post a screen shot.

**Comment by lueung** [comment]
screenshot: http://prntscr.com/a2u37r

**Comment by Data66PF** [comment]
This is how it is designed but I'll mark it an enhancement and not close it yet.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#2
