### ISSUE TITLE
TinyMCE loading everywhere regardless of settings

### ISSUE THREAD

**Issue by KStenvall** [moxi9/phpfox#1122]
In the current 3.8 version of phpFox, if TinyMCE is selected as the WYSIWYG editor it loads everywhere regardless of the settings in AdminCP > Load TinyMCE on Controllers.

On the pages where it should not load my browser inspector shows the following error:

> Uncaught ReferenceError: Editor is not defined
> Loading TinyMCE for: text (common.js:50)

This is on a fresh install - no add-ons or 3rd-party themes.

_This was a bug in an earlier version and has returned._

**Comment by Data66PF** [comment]
Please post this in the v3.8 issue tracker. This is only for v4. https://github.com/moxi9/phpfox-v3-dist/issues
