### ISSUE TITLE
"Profile Succesfully updated" not translated...

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1124]
![sss](https://cloud.githubusercontent.com/assets/8930862/13030066/a7d60648-d2a6-11e5-952e-12806effb625.png)

**In profile update page**

Find the missing statements OK.

4.2.2 version

**Comment by Data66PF** [comment]
I'm not able to find the phrase in phrase manager. Confirmed.

**Comment by karargaht** [comment]
Thanks, We expect the next update :)

**Comment by neil96** [comment]
Fixed in V4.3.0
