### ISSUE TITLE
Staying Idle on a created page Bug

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1125]
This is on the default bootstrap

When a page is created and then saved. If you just let the site idle on that page for a long time (don't ask me how long as as I didn't time it) and you then click on "edit" at the bottom right it takes you to "http://yoursite.com/index.php/admincp/login/

Now if you enter your credentials you'll just be stuck at the same login screen. However if you click on the gear on the upper right and then "admincp" it takes you right into the admincp screen.

**Comment by Data66PF** [comment]
Do you mean front end page or admin created page? Note that the admincp, for security, has a timeout feature that will kick you out of admin. You can change that in the PF.Base/file/settings/server.sett.php near the bottom of the code.

**Comment by lueung** [comment]
admin created page

**Comment by Data66PF** [comment]
I stayed idle for 30 minutes and didn't see any odd behavior.

**Comment by lueung** [comment]
Are you creating "pages" in the community section or from the admincp in "page" ?

**Comment by Data66PF** [comment]
I'm doing as you said. Making a page in AdminCP >> Pages and then I'm on the front end seeing the page, with the edit at the bottom right. I sit on it a while and then click Edit but I need to log into admincp again as the timeout is set. Is there something else needed to do?

**Comment by Data66PF** [comment]
Ok I can confirm it a different way. Be logged into the site but not logged into admin yet. Go to a page you had made before (static page made in AdminCP >> Pages) and click Edit. Try to log into admincp as that is where you are (which is normal) but you can't log in (it simply submits the form and resets so the form stays there for logging in, it never completes the log in).

**Comment by robert9592** [comment]
Fixed in v4.3.0
