### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1128]
# http://www.site.com**/user/privacy/**

![account](https://cloud.githubusercontent.com/assets/8930862/13034985/9df74398-d34c-11e5-8b30-2028afd8b556.png)

# http://www.site.com**/admincp/**

![admin](https://cloud.githubusercontent.com/assets/8930862/13034984/9df6cc10-d34c-11e5-9cd2-ef3e7c3f27d5.jpg)

# http://www.site.com**/user/privacy/** and http://www.site.com**/user/profile/**

**Keyword: Date of Birth, birthday privacy and birthday sees the same function**

![date birtday](https://cloud.githubusercontent.com/assets/8930862/13034986/9df862a0-d34c-11e5-88cc-3b97108b0a7b.png)

# http://www.site.com**/user/browse/*

![from-to](https://cloud.githubusercontent.com/assets/8930862/13034988/9df974a6-d34c-11e5-8e04-115ec59f7b5f.png)

# http://www.site.com**/profile-id*
![reposti](https://cloud.githubusercontent.com/assets/8930862/13034987/9df8c254-d34c-11e5-954b-32ada4ae3ef9.jpg)

# http://www.site.com/*

![say](https://cloud.githubusercontent.com/assets/8930862/13034989/9dfb777e-d34c-11e5-988c-643ed275d876.jpg)

# http://www.site.com/

![shared](https://cloud.githubusercontent.com/assets/8930862/13035986/471d1882-d364-11e5-8c37-10884d363a51.png)

**Comment by karargaht** [comment]
**Admincp/maintenance/reparser**

![aaa](https://cloud.githubusercontent.com/assets/8930862/13036940/26697aea-d37d-11e5-8351-b736d9ce27b4.png)

**Comment by neil96** [comment]
I checked some phrases you reported, They are already phrase, but these are new phrases, language package from store may not update them.

**Comment by Data66PF** [comment]
@karargaht please be sure when checking phrases that you do a search in the latest release. Don't search in your language pack but instead search in the English pack. Please post one issue per report next time so that we can close the ones that are not bugs and confirm the ones that are.

**Comment by karargaht** [comment]
What is working? I've tried them all but not...

**Comment by Data66PF** [comment]
When you upgrade, each time you need to run the Find Missing Phrases (among other things that need to be done). Did you do that?

**Comment by karargaht** [comment]
Of course, I did a lot of times

Example: 

Reposition word of English but also available in Turkish is not coming.

"User.reposition" variable I installed myself did not happen again

**Comment by Data66PF** [comment]
The word in English only gets in your language by either you translating it or by the developer of the language pack translating it. It is not an automatic translation. Please translate any phrases that are missing from your Turkish pack or please have the developer that made it update it.

**Comment by Data66PF** [comment]
We need a tech to test all of these. I've tested Account and it does not change Front End when I change the phrase in the phrase manager and clear cache. This is a hard coded phrase that needs to be fixed. As the client has shown several in this report, it makes it much harder to confirm and use our internal revision numbers. In the future, for the client that posted, please post one issue per bug report for us as it makes it much easier to test and fix.

Confirm that Account is indeed hard coded and not using the phrase in my 4.2.2 site. Please (staff) test the rest of the reported hard coded phrases in this issue.

**Comment by neil96** [comment]
List of phrases you reported from up to down:
Account: Already added to phrase on 4.3.0
These phrases we use module name, on V 4.3.0, we changed to phrase:

- feed: Phpfox::getPhrase('feed.feed')
- Invite: Phpfox::getPhrase('invite.invites')
- marketplace: Phpfox::getPhrase('marketplace.marketplace')
- pages: Phpfox::getPhrase('pages.pages')
- photo: Phpfox::getPhrase('photo.photos')
- rss: Phpfox::getPhrase('rss.module_rss')
- tag: Phpfox::getPhrase('tag.tags')

> Keyword: Date of Birth, birthday privacy and birthday sees the same function

We use the same phrase, if you want to separate them, please post in [feature request,](https://github.com/moxi9/phpfox-feature-requests/issues) we will check and consider to separate it.

From, To: Confirm as missing phrase => added on V4.3.0

Reposition: => New phrase from previous version.

All phrase from video. Video use phrase menthod, there is a bug on 4.2.2, so it can't display on phrase manager. We fixed on 4.3.0. Note: all phrase from video is new phrase.

run, records => added phrase on V4.3.0

**Comment by karargaht** [comment]
Thanks @neil96 

Video app module will be translated?

**Comment by karargaht** [comment]
Hi, @Data66PF search word can not be translated. Do not you know?

![ssss](https://cloud.githubusercontent.com/assets/8930862/13156121/9756c618-d689-11e5-9576-dd1c3e184053.png)

**Comment by neil96** [comment]
Hi @karargaht , this phrase use the same way with video app. It will be fixed on 4.3

**Comment by karargaht** [comment]
Thanks @neil96
