### ISSUE TITLE
After registration the site stays on the registration page.

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#113]
After registration the site stays on the registration page and doesn't redirect to member page.

**Comment by Data66PF** [comment]
I'm not having this issue on my site or the PHPfox community site when I try to sign up. Are you using the current version of V4? What OS and browser are you using?

**Comment by orgazilla** [comment]
Sorry, I forgot I made this thread. I fixed the problem, it turned out to be an error on my part!
