### ISSUE TITLE
Fails to disable sitewide ajax 

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#1131]
Fails to disable sitewide ajax - there is no option in setting to disable sitewide ajax

**Comment by Data66PF** [comment]
This is how it is designed.

**Comment by signupsi** [comment]
I think there shall be option to disable .... 

additionally we exp Site getting slow like hell ..
when 4x came .. it seem like good option ..being fast was impressive 

now even on local host 3x is much faster compared to 4x
