### ISSUE TITLE
Safari Browser, Macbook Pro Blank AdminCP

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1132]
Per client post at the forum, if visiting AdminCP block editor or some other areas in admin and using Safari browser with a mac, the admincp blanks out. I see it has errors loading the css and javascript nanoscroller but am not sure that is the issue. Refreshing the page does not help. As a client is the one that reported to me, and I can reproduce it on my live 4.2.2 dev site, I'll confirm as a bug.

**Comment by wlongdonstudio** [comment]
thank you

**Comment by robert9592** [comment]
Fixed in v4.3.0
