### ISSUE TITLE
Popup boxes issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1133]
Popup boxes not showing when you click on any link if popup boxes are open.

Example click on "Add to Friends" button on any user profile than click on any menu links before close the popup box. Than try again to click on "Add to Friends" button on same or any user profile.

It's same for other popup boxes in the site too..

**Comment by Data66PF** [comment]
Do you mean the same issue shown in the screen shot on this bug https://github.com/moxi9/phpfox/issues/1063

**Comment by Ylmzef** [comment]
No. It's different.

**Comment by Data66PF** [comment]
confirmed at staging server on macbook pro with chrome browser. I did the exact steps mentioned.

**Comment by robert9592** [comment]
Fixed in v4.3.0
