### ISSUE TITLE
Unable to login... 

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1136]
Unable to login, registration is done. Many people have the same problem. No problems exist in your demo site, yes, but we unfortunately

I delete the site and set up 3 times.

All browsers on the same issue. PC and mobile... 

Os: Windows 10

https://youtu.be/6OdKh7BtZVk

**Comment by karargaht** [comment]
I think the same problem

https://community.phpfox.com/mobile/forum/thread/53970/login-not-working-v4-2/

Users can not login, we are really victimized

**Comment by Data66PF** [comment]
Please disable recaptcha app and clear cache and test. Let us know if that works.

**Comment by karargaht** [comment]
No, the same

**Comment by karargaht** [comment]
I turned off all the modules,
I don't set up an extra module 
I changed themes
I switched to another theme

Unfortunately, the problem could not be resolved

**Comment by karargaht** [comment]
![error](https://cloud.githubusercontent.com/assets/8930862/13108734/a66c959a-d57d-11e5-8c4d-27509330387d.png)

**Comment by karargaht** [comment]
Edge log

`{
    "content": "<div class="_block location_2" data-location="2"></div>The page you are looking for cannot be found.<div class="_block location_4" data-location="4"></div>",
    "title": "Page Not Found » Yerli Sosyal Paylaşım Sitesi!",
    "actual_title": "Page Not Found",
    "phrases": [],
    "files": [
        "http://www.sosyalken.com/static/jscript/editor.js",
        "http://www.sosyalken.com/static/jscript/wysiwyg/default/core.js",
        "var enable_private_message_block = "1";",
        "http://www.sosyalken.com/PF.Site/themes/bootstrap/flavor/bootstrap.css"
    ],
    "css": [],
    "breadcrumb": "<div class="row hide-overflow breadcrumbs-holder">
	<div class="clearfix breadcrumbs-top">
		<div class="pull-left">
			<div class="breadcrumbs-list">


				<a  class="ajax_link">
Page Not Found</a>
			</div>

		</div>
		<div class="pull-right breadcrumbs_right_section">



		</div>
	</div>
</div>
",
    "blocks": {
        "1": ["							
"],
        "2": [],
        "3": [""],
        "4": [],
        "5": [],
        "6": [],
        "7": [],
        "8": [],
        "9": [],
        "10": [],
        "11": [],
        "12": []
    },
    "search": "

",
    "menuSub": "							
",
    "id": "error_404",
    "class": " _is_guest_user ",
    "h1": "",
    "h1_clean": "",
    "error": "<div class="_block_error">
<script type="text/javascript">$Behavior.pageSectionMenuRequest = function() { }</script></div>

<div class="public_message" id="public_message"></div>
<div id="pem"><a href="#"></a></div>
<div id="core_js_messages">
</div>
",
    "has_left": false,
    "has_right": false,
    "controller_e": null,
    "meta": true,
    "keep_body": false,
    "selected_menu": ""
}`

**Comment by Data66PF** [comment]
Did you try the suggestion at the community? https://community.phpfox.com/forum/thread/53970/login-not-working-v4-2/?view=332672

**Comment by karargaht** [comment]
Unfortunately, it also has nothing to do with it @Data66PF

**Comment by karargaht** [comment]
logically, is trying to register the login is not made. so there is a problem of the login file. ajax, java, css etc.

**Comment by karargaht** [comment]
https://community.phpfox.com/forum/search?s=1&forum_id=0&search%5Bsearch%5D=login

**Comment by neil96** [comment]
@karargaht I have a quick test on your site. I saw all ajax requests can't work properly. I think this problem come from your server or third-party code not from our core code.

**Comment by karargaht** [comment]
hi @neil96 I solved the problem
I set up the website again, Going on in v3 module

**Comment by DarkGeometry** [comment]
Hi, karargaht!
I have this problem. How did you solve it?

**Comment by neil96** [comment]
Hi @DarkGeometry ,

This issue is very old. We can help you resolve the problem if you can post a thread on our [community](https://community.phpfox.com/)

Regards.
