### ISSUE TITLE
Admincp crashes if no Apps are loaded which invoke Core\Route\Group

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1137]
There appears to be a dependency built into the current system between the admincp and certain Apps.  This may cause problems as most people would consider Apps as optional code.

"Trying to get property of non-object" error occurs in /PF.Base/module/admincp/include/component/controller/index.class.php around line 322.  This is a menu array item that uses url object.
 `_p('Rebuild Core Theme') => url('/admincp/theme/bootstrap/rebuild')`

My suggestion is to place this code before the menu array definition:
`if(!class_exists('url')) {
new \Core\Controller;
}
`
With this change in place the Apps dependency is removed..
Note: with flavor app removed 'page not found' occurs when rebuild core theme selected.

**Comment by Data66PF** [comment]
flavor app is required. please don't remove it.

**Comment by phpFox-webwolf** [comment]
I do not plan on removing it.  The app (I think) is not visible in the apps display, so it should not be able to be easily removed except by ftp.

**Comment by Data66PF** [comment]
@neil96 can someone check

**Comment by neil96** [comment]
> With this change in place the Apps dependency is removed..

How you remove it?

**Comment by phpFox-webwolf** [comment]
Hi Neil,
I was looking for a way to disable apps through php coding.  If someone installed an app and then could not access their site, it would be a reasonable troubleshooting step to disable the app and see if it caused the problem.  Apparently, the only way to do that is to remove the app folder from the App directory.  Whether the app.lock file is present or not, a coding problem can still kill the site.
My first thought was to rename App folder and replace it with an empty App folder.  This is when I noticed the dependency.  The Site went blank and I traced the error to the admin menu item mentioned above.
I mention this because  it seems like a selectable menu item should stand alone without the need for an app.  It is the only item that uses the url object and so I suggested making the object available.
web

**Comment by neil96** [comment]
Hi @phpFox-webwolf 
You can't delete folder Apps. App is an important feature. 
If you don't like an App, you can uninstall it. All apps from our store can't make their site down, because we test it careful before approve.

If that's a core App, we have option disable/enable or uninstall.

**Comment by phpFox-webwolf** [comment]
This really isn't about App.  It is about the menu item.  A menu item calls a class that may not exist. If this happens, the site dies.  I have pointed it out.  You may do with it as you wish.

**Comment by neil96** [comment]
That class defined in App /PF.Site/Apps/PHPfox_Flavors (our core app and can't remove). If you can reproduce this issue with default code (don't remove any file), please report us.
