### ISSUE TITLE
Mute "Register" button on invite only site.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1138]
It seems pointless to include a register button in the visitor page of a mode (invite only) where it cannot be used. When a user clicks register in invite mode, they are presented with a second invite dialog over and above the existing one which also seems pointless. Suggest that the register button be hidden in cases where unconditional registration is not allowed. The invite dialog opens all necessary registration process by itself when an invited visitor responds to their invitation.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#3
