### ISSUE TITLE
forum_post_text table issue

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1139]
Hi,

I have just noticed that in v4 the table **forum_post_text** has the fields **text** and **parsed_text** with the same plain text in it. In v3 the **parsed_text** had html tags on it that we could use to show breaks of lines, images and so on.

How do I convert this plain text into html so the break in lines are respected when I echo this field content?

Thanks

**Comment by robert9592** [comment]
In phpFox v4, we have a built-in function "Phpfox::getLib('phpfox.parse.output')->parse()" to parse the plain text stored in db to html content for display. You also can use it easily on template file (*.html.php) with syntax: "{[plain_text_for_parsing]|parse}". 
For example, in "/PF.Base/module/forum/template/default/block/post.html.php", line 64, content of Forum Post is parsed by using: "{$aPost.text|parse|split:55}"

**Comment by Data66PF** [comment]
@cespiritual does the answer resolve this for you? If so, please close the issue. If not, please provide feedback.

**Comment by cespiritual** [comment]
Hi,

Yes... that's exactly what I need. Thanks.

You should made a tutorial with all the function we can use. It will be very usefull for developers.

Thanks Again

**Comment by Data66PF** [comment]
@neil96 or @robert9592 please make a tutorial for this

**Comment by cespiritual** [comment]
Hi,

I have tested it and all works fine by converting plain text into html, except for the smyles.

It don't convert into images this tags: :smiley: :thumbsup:

Is there another function for this?

Thanks

**Comment by robert9592** [comment]
@cespiritual, if you want to parse emoticon, the app "Twemoji Awesome" must be enable and the class of html element which contains the content must be added to "CSS Selectors" setting in app "Twemoji Awesome".

**Comment by cespiritual** [comment]
I have tried to add the classes **forum_content item_view_content twa_built** to the div where the content is displayed but didn't work. The **item_view_content** is in the CSS Selector.

Could this be because I'm using this on a modular App? But the core Forum is also a modular App.

Thanks

**Comment by robert9592** [comment]
Do you also add the class **twa_built** to the div? The class **twa_built** will be added to the element after its content is parsed to emoticon (by javascript scirpt). So, if you add this class to your element, the javascript script will ignore and won't parse its content.

**Comment by cespiritual** [comment]
Thanks Robert... I have removed that and all works fine now.
