### ISSUE TITLE
[Verification E-Mail] Not Being Sent

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#114]
I have a few members now joining who have contacted me letting me know they aren't receiving any verification e-mails (earlier users, including myself did with earlier updates). Is there a way to test this out and/or figure out why they aren't being sent and fix them?

I had them check both inbox and spam to make sure it wasn't sent there.

**Comment by Data66PF** [comment]
I use Mandrill for my sites and it works great for consistent delivery. I only use the send feature, not for incoming. It has a great dashboard for seeing if messages are sending, if they are bouncing and why they might be bouncing. It is the recommended mail delivery method for PHPfox clients. I made two tutorials for enabling it, well three really, http://store.phpfox.com/kb/article/603/using-mandrill-for-your-site-transactional-mail  and also http://scripttechs.com/article/318/using-mandrill-for-site-mail-with-phpfox/ . The third is also on my site. I use the free version of Mandrill for both sites.

**Comment by Data66PF** [comment]
Have you tried the suggestions? If so, did they work for you?

**Comment by Jinkers** [comment]
I've implemented Mandrill on the site and gave it a test run. Everything looks like it is working. Thanks @Data66PF
