### ISSUE TITLE
allowed to create 2 categories with the same name

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1142]
i'm being allowed to create 2 categories with the same name in Settings/Pages on admincp v4.2.2(build 1)

**Comment by Data66PF** [comment]
Please give more details. Are these the main categories? Are these the subcategories? Do you mean you can have two parent categories the same name? OR Do you mean you can have a parent category and a subcategory the same name as its parent? OR Do you mean that you can have two subcategories the same name?
