### ISSUE TITLE
all pages not showing

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1143]
After upgrading from 3.8 to 4.1.2 and 4.2.2(build 1) all my page not showing up
even though i update the categories for the non showing up pages
i still can't find them if i go to the search bar in pages
i can however see them listed once i press the page link
the page only show up when i look at the page list of if i search from the site search
they do not show up with i search using page search
all of these that had the problem came from a specific category
they are currently in moved to a different category but it seems like something is permanently damaged

**Comment by Data66PF** [comment]
What sort of category are they in? Is it one you created as a parent category and then a subcategory for it?

Is this only pages or is it groups? 

Do the pages / groups that don't show up in the search all have a main category and a subcategory?

**Comment by wlongdonstudio** [comment]
categories within the group

**Comment by Data66PF** [comment]
Tested at the live demo and I can't reproduce this. Do you see any errors with debug enabled?
