### ISSUE TITLE
Delete option on Pages is unclear 

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1144]
The delete option on Pages (the upper right gear) is unclear whether it is to delete the page or photo image.

**Comment by Data66PF** [comment]
The Change Cover is for changing and deleting the cover. The delete button is to delete the page. In the future, please post feature requests in the new feature request tracker for small improvements like this. I'll move this one.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#25
