### ISSUE TITLE
Client License Issue - Setting https domain results in http://https://website.com

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#1145]
If I set my domain in https:// when I choose the domain that uses the license, automatically in the right up corner it is shown as **http://https://website.com**.
I know this isn't so much important and we cold set even just http, but I'm afraid that the license gets invalidated for that website in this way.

Thank you!

**Comment by Data66PF** [comment]
@RaymondBenc please check this.

**Comment by optiroot** [comment]
I guess you can close this as now there is a New Client area. Right?
