### ISSUE TITLE
Mobile has no post as page/post as user option in pages and groups

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1146]
when posting a photo to a page from mobile it post as user
when posting from mac it post as page v4_2_2 (build 1)

https://www.dropbox.com/s/0ws5tbkx3z2o3gk/Screenshot%202016-02-18%2021.05.48.png?dl=0

**Comment by Data66PF** [comment]
To clarify, the desktop version in pages/groups for feed posts shows an option to post either as the page or as the user.
Mobile version on an iPhone 5c for my tests has no option to choose that.

**Comment by neil96** [comment]
I can't reproduce this issue.

**Comment by Data66PF** [comment]
This works in 4.3 at our staging site.
