### ISSUE TITLE
😍😍 translate to ߘͰߘ 

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1147]
😍😍 translate to ߘͰߘ v4_2_2(build 1) I don't see no smiley emoticon on the website
I copied 😍😍 from Internet and paste it in blank space once I hit submit it translate to ߘͰߘ

**Comment by Data66PF** [comment]
You need to use the smileys in the twemoji app. We can move this to feature requests if you want to be able to use copied smileys but right now, this is how it works.

**Comment by Data66PF** [comment]
Let us know if you want this moved. To use the Twemoji app that came with the v4.2 version, please just click the little smiley icon and a popup will show all of the available smileys.
