### ISSUE TITLE
[Messages] Can't Reply To Sent Messages

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#115]
Person A can send a message to Person B

Person B receives the message, but upon hitting enter to reply, it does not go through.

Person A can continue to send messages which Person B receives.

**Comment by Data66PF** [comment]
This works on the PF community and on my test sites. Do you have latest version? What browser and os are you using? What is debug showing? What is developer browser console showing?

**Comment by GloriousKoch** [comment]
Sorry, forgot to close this up. Turns out it was a fluke I think. I experienced it once and then it worked after that. Closing now. If I run across it again I'll open a new issue with more details.
