### ISSUE TITLE
No pagination to view more pages

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1152]
The default option to view pages is 10, 15, 20.  There's no pagination  to view more pages.

**Comment by Data66PF** [comment]
Pages autoload. Are they not autoloading when you scroll down the site? https://v4.phpfox.com/pages/category/1/entertainment/ Note that we have a feature request to change from this pinterest style loading to a pagination with numbers and arrows. If you mean that, please find the feature request and comment in it that you are also interested.

**Comment by lueung** [comment]
Are pages supposed to autoload? If so, I did not know that, as it is not auto loading.

**Comment by lueung** [comment]
OK. It took me a bit to see how the pages are displayed. It seems that it does auto-load if you on the the individual category, but it does not auto-load on "all pages" but displays a certain number from each category.

**Comment by Data66PF** [comment]
All pages only shows the various categories with a few selected ones.

**Comment by lueung** [comment]
Do you have the link with the pagination feature request? I've been getting the same request from 90% of my users and even I was thrown for a loop initially.

**Comment by neil96** [comment]
You can post your request here: [https://github.com/moxi9/phpfox-feature-requests](url)
