### ISSUE TITLE
Cannot edit feed in pages

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1153]
Feeds can be edited in other sections, but the feeds in pages cannot be edited.

**Comment by Data66PF** [comment]
Do you mean the actual first post (status post) or a comment? Note that the first status post can't be edited anyplace. If you mean comments to posts, I haven't tested.

**Comment by Data66PF** [comment]
Tested editing a comment to a post and it works fine in pages. Note that the original status post has never had an edit option but there is a feature request for one. Even in v3 it was never able to be edited.

**Comment by lueung** [comment]
Correct, it is the status.

**Comment by Data66PF** [comment]
Ok that is not a feature of our script. There is a feature request in the community for this though.
