### ISSUE TITLE
4.2.2

### ISSUE THREAD

**Issue by vanucci** [moxi9/phpfox#1154]
Cannot post in forums

when trying to post repsonse back is fill in text

**Comment by Data66PF** [comment]
Do you mean your own site? Please edit the title to be the description of what your bug is. 

Please let us know if this is your site, our demo, our community and what os and browser you are using.

**Comment by vanucci** [comment]
Was linked to a app ion the app store, BBCODE the developer has been notified, but not had confirmation of receipt
