### ISSUE TITLE
www prevents loading login screen

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1155]
Anyone site or anyone using www.domain.com, the login screen never loads.

**Comment by Data66PF** [comment]
https://community.phpfox.com/forum/thread/53970/login-not-working-v4-2/?view=332727 does that resolve it for you?

**Comment by lueung** [comment]
Yes. I used this instead:

RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]

**Comment by Data66PF** [comment]
Ok thanks. I had actually added this to our internal tracker last week but we need someone to send us log in details to see server issues with this as it doesn't break internally. I'll mark this a bug for now but if you can send a ticket to hello@phpfox.com with your server log in details and admin log in, we can have a core developer check too. I realize you fixed it with the posted solution that you show but the team did ask if one of our core devs can come check a site with the issue.

**Comment by neil96** [comment]
@lueung Is your problem because htaccess file? (It will work if you remove .htaccess file and error is you add it again)

**Comment by lueung** [comment]
No, I did not have the htaccess file. I did use the access file to correct the issue.

@Data66PF yes, I can send details.

**Comment by lueung** [comment]
@ data66pf: OK details sent

**Comment by Data66PF** [comment]
Thank you. I'll pass the ticket info to the core devs so they can check it.

**Comment by Ylmzef** [comment]
It's due of this issue: https://github.com/moxi9/phpfox/issues/748

**Comment by Data66PF** [comment]
ok referring to other report instead.

**Comment by neil96** [comment]
Please check status on #748.

**Comment by RaymondBenc** [comment]
@lueung We have applied a test patch on your site. Can you confirm if the issue has been resolved?

**Comment by lueung** [comment]
Yes I can confirm that I can now login via www, but, I'd like the default to be without the www. Will this cause any issues?

**Comment by Data66PF** [comment]
It is fixed in the script for 4.3 but applied to your site.
