### ISSUE TITLE
Message composing window disappear when clicking a link while leaving it open

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1156]
If a user has a message window open or composing or responding to a message, if a link on the main menu is clicked while leaving the message window open it will disappear and you can't get back to it unless you refresh and click on the message icon again, but all the stuff you've composed is also gone.

**Comment by Ylmzef** [comment]
https://github.com/moxi9/phpfox/issues/1133

**Comment by Data66PF** [comment]
please search before posting.
