### ISSUE TITLE
can't upload video

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1158]
Protocol "https" not supported or disabled in libcurl
can't upload video, it's a video being uploaded from my mac to site
https://www.dropbox.com/s/vij9lvvuzhwlf0e/Screenshot%202016-02-23%2022.25.28.png?dl=0
https://www.dropbox.com/s/9iirc551v1cdwsk/Screenshot%202016-02-23%2022.12.50.png?dl=0

**Comment by Data66PF** [comment]
Did you ask your host?

**Comment by wlongdonstudio** [comment]
Asking now

**Comment by neil96** [comment]
Did you resolve this issue?
