### ISSUE TITLE
[Date Of Birth] Year Stops At 1997

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#116]
Had a user born in 1999 sign up bring up to me that the years stop at 1997 on birthday choices. How does one go about editing the years for these forms?

Thanks. :)

**Comment by Data66PF** [comment]
Confirmed that we lost the dob setting from User settings.

**Comment by RaymondBenc** [comment]
Next release, **4.0.3** will include this fix and can be edited from **AdminCP >> Settings >> User >> Settings**
