### ISSUE TITLE
Cannot Edit Theme after clearing cache and running a Cronjob

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox#1160]
After upgrading website to phpFox latest versions (4.2.0 and above), clearing cache then running a Cronjob will automatically switch theme back to Neutron. Go to AdminCP >>> Themes >>> Edit (on Neutron theme) >>> instead of redirecting to editing page, it keeps refreshing.

**Comment by Data66PF** [comment]
Staff, please mark a bug if this is a bug. Thanks.

**Comment by robert9592** [comment]
We cannot reproduce in v4.3.0. Please help us to check it again on v4.3.0.
