### ISSUE TITLE
On Mobile The Site Malfunction - Neutron Theme

### ISSUE THREAD

**Issue by ajaymenonv** [moxi9/phpfox#1163]
If one opens the site in mobile one clicks login the fields for username and password does not shows up. For bootstrap theme it works but for others it does not work.  

community link for this issue is: https://community.phpfox.com/forum/thread/54230/on-mobile-the-site-malfunction/

**Comment by Data66PF** [comment]
The neutron theme is fixed. Please delete your current neutron and install the new one from the store. Note that deleting will remove any customizations to the default theme so please make sure you never edit the default themes.
