### ISSUE TITLE
Enhancement: Add "Not Currently Accepting New Friends" control.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1164]
Users should have the ability to set a control that politely advises a prospective friender that this user is not currently accepting new friends as the friend request is issued. Alternatively, the friend control could just drop out for the non friendable user(s) so the add as a friend option is just not possible if the control is set.

**Comment by Data66PF** [comment]
Please post feature requests at our feature tracker

**Comment by Gatsby-PF** [comment]
Forethought to the feature request was given before posting, however it seemed pointless to request an app developer to do that which can only be done realistically in the core. That is why I posted here as an enhancement.

**Comment by Data66PF** [comment]
Our feature request area is for things for us to make.
