### ISSUE TITLE
Enhancement: Add group access control to categories for modules other than forum. 

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1165]
The ability to restrict entire listing, event or blog categories to specific groups and friends or custom lists falling with in that group. Any member outside the group cannot access period. This already exists in forum category controls (which does not have the everyone, friends-only, friends of friends drop-down like most other modules). The idea is to standardize all module categories to group permissions drop down on one level, and to fine tune access possibilites within that group (groupwide, friends only, friends of friends, no one) on another level.

**Comment by neil96** [comment]
For feature request, please post here: [https://github.com/moxi9/phpfox-feature-requests](url)

**Comment by Gatsby-PF** [comment]
Forethought to the feature request was given before posting, however it seemed pointless to request an app developer to do that which can only be done realistically in the core. That is why I posted here as an enhancement.

**Comment by Data66PF** [comment]
As mentioned, our feature request area in Github is for us to add things to the core product. It is not a third party feature request area such as is in our forum.
