### ISSUE TITLE
IP ban issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1166]
I have added a IP address to banned IP addresss and selected Ban User option.
But the visitor can still register with same IP address.

**Comment by Data66PF** [comment]
You added it in the ban filter settings? Did you add it as a wildcard? Can you post a screenshot of the setting you've made? Can you post a screenshot of the user registered after the ban was set? Are you on v4.2.2?

**Comment by Ylmzef** [comment]
Yeah i added it in the IP ban filter settings likeas i mentioned.
I don't added it as a wildcard.
And i can't post screenshot because i remove the user every time.

**Comment by neil96** [comment]
> But the visitor can still register with same IP address.

But user can't login with banned IP.

**Comment by Data66PF** [comment]
If you would like this improved, please post a feature request, https://github.com/moxi9/phpfox-feature-requests

**Comment by Ylmzef** [comment]
User can login also add friends too.

**Comment by neil96** [comment]
Please make sure your cache cleared after you added new IP.

**Comment by Ylmzef** [comment]
I removed user already but like as mentioned the visitor can still register with same IP address.

**Comment by neil96** [comment]
I can't reproduce your report. Visitor can't login or register with banned IP.

**Comment by Ylmzef** [comment]
I have added a IP address to banned IP addresss.
After that i remove user from system.
But the same user can still register with same IP address.

**Comment by neil96** [comment]
I can't reprodcue with all information you gave me. I tested many times, but it's working fine.
Could you try again and give me more information. Thanks!

**Comment by Ylmzef** [comment]
![download](https://cloud.githubusercontent.com/assets/8562514/13908303/2ba388e0-ef00-11e5-980c-c71a1ff8fb32.png)
![ipban](https://cloud.githubusercontent.com/assets/8562514/13908304/2bb88966-ef00-11e5-9e90-72ef97cb4ce1.png)

**Comment by neil96** [comment]
Yes, banned IP still signup, but they can't login. I fixed this issue on 4.4.0.

**Comment by Ylmzef** [comment]
This still issue on 4.3.1

**Comment by neil96** [comment]
Please open new issue if you can reproduce on lastest version.
