### ISSUE TITLE
Deleting phpto don't remove like

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1167]
Hi,

When I delete a photo the like to that photo are not removed from the table phpfox_like

Didn't test with other content so you must check on that too.

Thanks

**Comment by Data66PF** [comment]
Team, please be aware of this https://github.com/moxi9/phpfox-v3-dist/issues/11 issue moved to internal tracker for us to fix. I believe the Like issue is the same as that issue (same problem) and the same that I just posted in chat earlier this evening. We need to look at both issues for a solution as it even appears in v3 so it is not a new issue.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#66
