### ISSUE TITLE
Privacy issue on posting to profile

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1168]
On the v4 test site, I signed up a user and set his privacy setting for posting to his profile to friends only.  Then I signed up as another user, went to the first user's profile and posted a message.  This problem was reported to me by a client and I was able to recreate it on my dev site as well as on the v4 test site.

I also tested v3.8 for this problem and found that it worked okay.

**Comment by Data66PF** [comment]
confirmed. This profile is set to only friends can share on the profile, https://v4.phpfox.com/profile-4942/ but my user https://v4.phpfox.com/profile-2614/ is able to comment on the profile. That setting used to work but something has broken it.

**Comment by neil96** [comment]
Fixed on v4.3.0

**Comment by Vivian-phpFox** [comment]
Duplicate #1130

**Comment by Data66PF** [comment]
Please double check this as it is a different issue. One is for a photo and the other is for a status post. Just making sure we checked both issues and not just the one issue. @Vivian-phpFox please verify.

**Comment by neil96** [comment]
#1130 is a part of this issue. I fixed both of them.
