### ISSUE TITLE
reCAPTCHA fails too much

### ISSUE THREAD

**Issue by Ramstete** [moxi9/phpfox#1169]
I have try many times to enable the reCAPTCHA plugin but everytime it give error when i try to solve the questions (which are correct) but seem like from home page is not going to connect properly with google,. I have noticed when captcha fail and phpfox send u to  domain.tlc/register and try again the recaptcha it sometimes works fine. 

Also there are problems of compatibility with Chrome and Microsoft Edge for what i have tested. It work less or more good only with Mozilal Firefox.

**Comment by optiroot** [comment]
Confirmed, I have the same problem.

**Comment by Data66PF** [comment]
Are you sure you did not also enable the phpFox default captcha setting?

**Comment by optiroot** [comment]
Yes, I'm sure. I have the default Captcha disabled...

**Comment by Data66PF** [comment]
I can't get it to fail in chrome. I'm using a mac.

**Comment by optiroot** [comment]
I know you can't reproduce it, but we are two clients which are able to reproduce the problem...
Maybe some other clients could find this bug too, because it's really strange. If you need some debug infos and so on, I could provide you them, in a way or another.

**Comment by Data66PF** [comment]
Our team will test more. If we can't reproduce it, we can't fix it as it is not something from our end, it would be something on Google itself. However, our team will test.

**Comment by Ramstete** [comment]
No seem more something about connection between hpfox and google. if i use it via domain.tlc/user/register/ it seem to work sometimes.

**Comment by Data66PF** [comment]
Can you all please make sure you have deleted the old recaptcha that you may have gotten from the store and only use the new one that loads with the script in 4.2.2? The old one was updated only in the one that comes with the script.

**Comment by Ramstete** [comment]
I have only the one which come with 4.2.2

**Comment by optiroot** [comment]
Me too; I have just one reCaptcha.

I say too that when I installed 4.2.2, I had problems and had to enable debug mode, which was caused by reCaptcha by Google, and after I deleted the folder in PF.Site/Apps, everything worked again; but the folder recreates by itself and for some time it worked, but after some days it stopped working...

What could be the problem?

**Comment by Data66PF** [comment]
@neil96 can someone else test this? I can't reproduce it at all.

**Comment by neil96** [comment]
I can't reproduce on my site. Could I test on your server?
Email me (neil@phpfox.com) your site url or comment here. Thanks!

**Comment by Data66PF** [comment]
Please be sure to start sending as tickets instead of emails via the new client area. Thanks!

Is this resolved or answered?

**Comment by optiroot** [comment]
Sorry, with holydays I didn't had time and forgot about it, too.

Please, re-open this!

I'm going to send my website details in this day. Sorry!

Thank you.
