### ISSUE TITLE
New registered members can't sign in...FIXED

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#117]
This was due to an error on my part, but I fixed it.

**Comment by Data66PF** [comment]
Is this for V3 or V4 and do you have any addons from V3 installed or any apps from v4?

**Comment by orgazilla** [comment]
This is for v4, I have the video feed v4 and recaptcha v4 installed...

**Comment by orgazilla** [comment]
Problem solved...this was an error on my part.
