### ISSUE TITLE
Cannot upload larger than 500k for Admin User Group Cover

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1170]
Regardless of the settings the admin the usergroup admin cannot upload cover photos over 500k

**Comment by neil96** [comment]
It's working normal. Please make sure you change property setting.

> User group setting "photo. photo_max_upload_size" 
> (Max file size for photos upload in kilobits (kb). 
> (1000 kb = 1 mb) 
> For unlimited add "0" without quotes.)

**Comment by lueung** [comment]
Yes. I just noticed that you have to change the "photo" setting. 

The "user" setting made me think that this was the setting which sort of confused things a bit.
---
 "Max file size for profile photos uploaded in kilobits (kb).
(1000 kb = 1 mb)
For an unlimited size limit add "0" without quotes. "

**Comment by Data66PF** [comment]
This is how it has always been though. Profile photos are avatars. We never had one specifically for cover photos.
