### ISSUE TITLE
PHPfox v3.7.7: A new page added by user and News Feed stopped populating for registered users, redirecting to Membership page.

### ISSUE THREAD

**Issue by mandarcjambotkar** [moxi9/phpfox#1171]
We have come across a weird issue. 

Ideally, when a registered user logs in, he lands on News Feed page. This is the standard behavior we have implemented. Suddenly, when registered user logged in, he was redirected to Membership page. Only Admin is able to see the News Feeds.

We have not done any changes in the code recently which might have impacted it. But an observation noted is - a new page was added by an user which was seen on News Feed and then this has probably started.

Can you please advise how to address this issue in v3.7.7. We can't disclose the website URL and hence asking for any suggestions you might have.

Thanks!

**Comment by Data66PF** [comment]
This is not for v3 issues. The issue you post is a bug in v3 and you'll need to upgrade to v3.8
