### ISSUE TITLE
Recaptcha replication

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1173]
When the green login is clicked, the recaptcha keeps replicating: http://prntscr.com/a8i6om

v4.2.2 bootstrap, centos 7.2, mysql 5.5.44, PHP v5.4.16

**Comment by Data66PF** [comment]
cannot reproduce at our demo https://v4.phpfox.com which uses the current recaptcha app and 4.2.2 bootstrap theme.

**Comment by lueung** [comment]
I'm also using the current 4.2.2 and downloaded the recaptcha from the admincp

**Comment by lueung** [comment]
This issue was caused by using the recaptcha from the app store which is not an updated version. The problem was resolved by using the recaptcha that came with the download.
