### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by toorta** [moxi9/phpfox#1174]
It seems that phpFox 4 stores strings in the database in a different way from phpFox 3. For example "```Beşiktaş```" was stored as "```Be&#351;ikta&#351;```" in version 3 but now it is stored as "```BeÅŸiktaÅŸ```".

How can we convert these strings into their original characters. Which class or function can we use. Is it possible to convert it in twig?

**Comment by toorta** [comment]
Any idea?

**Comment by neil96** [comment]
What's wrong in your report? I tested with your example, it display well on site.

**Comment by toorta** [comment]
I don't know there is something wrong or not. As explained in my first comment, while creating a page (pages module), the name of the page `Beşiktaş` is insterted in the database as `BeÅŸiktaÅŸ`. So it is displayed as `BeÅŸiktaÅŸ` while displaying in a twig template. We were using `{$aPage.title|clean}` in smarty templates (while we were developing modules) to display it. What will we use in twig template?

**Comment by Data66PF** [comment]
I cannot reproduce this with my Latest Activity app that has New pages showing in it and using the example. It also doesn't show like that in my My Pages block.

**Comment by toorta** [comment]
Just a simple question: If you create a page with the name `Beşiktaş`, does it store as `Beşiktaş` or `BeÅŸiktaÅŸ` in the database?

**Comment by toorta** [comment]
Ok, I have found my problem. Thanks anyway...

**Comment by Ylmzef** [comment]
Same issue can you please explain how did you fixed it?

https://community.phpfox.com/forum/thread/55039/special-characters-showing-worng/
