### ISSUE TITLE
Adding your IP to Settings -> Security causes login issues

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1176]
v4.2.2 bootstrap, centos 7.2, PHP v5.4.16, MySQL v5.5.44

Adding the admin IP to Settings -> Security causes login issues for staff where it prevents them from being able to login to the admincp unless the staff ip is also included. If the admin removes the IP's they will no longer be able to access the admincp including the admin which essentially locks out the admin.

**Comment by lueung** [comment]
Not on the demo, but I do believe it is associated with this: https://github.com/moxi9/phpfox/issues/1176

**Comment by Data66PF** [comment]
This is how that setting was set up. You add the IP addresses to it if you want to lock it. You need to add any IP addresses or they can't log in.

When you removed the IP's, did you then go clear cache on the server from PF.Base/file/cache ?

**Comment by lueung** [comment]
I cleared the cache from the admincp. I can't recall, but I might have cleared the cache on the server from PF.Base/file/cache manually via ftp. Does it make a difference?

**Comment by lueung** [comment]
Is it possible that this is also preventing me from making creating test account?

**Comment by Data66PF** [comment]
Is it working now that you have the .htaccess restored?  

Yes it matters to clear cache on the server when making a change like that with admin ip and settings that would impact things like that.

**Comment by lueung** [comment]
ok the admin works when I remove all Ip's but still having this issue: https://youtu.be/8UQ-otmSIwI

**Comment by lueung** [comment]
I am still having issues with phpfox not logging people in when they make an account as shown in the video. I just tried it on the phone and it did the same thing. So I'm getting lots of people that just leave.

**Comment by lueung** [comment]
OK I think I figured out the issues. Will close this and send in email as it is a really weird anomaly and can only be test on my server.
