### ISSUE TITLE
Content Not Viewable by Guest

### ISSUE THREAD

**Issue by mrfenix** [moxi9/phpfox#1178]
Just ran an upgrade from 3.7 to 4.2.2. When logged out, as a guest, if I visit the photos, music or blogs page it displays "No Photos Found". Or what ever is relevant to that section that I visited.

To see photos I have to physically click the "All Pictures" button on the left side. Which brings this URL: http://www.mydomain.com/photo/?view=photos. Unfortunately, Blogs and Music doesn't respond the same way.

The forum works fine.

**Comment by Data66PF** [comment]
Please note that by default the site is set to friends only in v4. This is mentioned in the community in a few threads in case that will help you. Please go in your admincp and set the site to not friends only if you want guests to view stuff. Please be sure to check the community before posting.

**Comment by mrfenix** [comment]
Then how come content was still viewable of clicking "All Pictures" ?

**Comment by Data66PF** [comment]
Please set the site not to a friends only site and see if it works.

**Comment by mrfenix** [comment]
Sorry Data, I'm still trying to find my way around the backend, where exactly do I find that please?

**Comment by Data66PF** [comment]
It should be in settings >> site settings. The search when you first click Settings and up on the right click in the search box, if you just put friend, it should find it faster for you if it works.

**Comment by mrfenix** [comment]
*hands over a glass of wine to say cheers* Thank you, that seems to have sorted it. Pictures are still accessible via the url when the site is set to "friends only: yes". I assume that is a bug still?

**Comment by Data66PF** [comment]
_cheers! woops, broke the glass_  We will have to test that as friends only setting should not allow guest view at all.
