### ISSUE TITLE
[Custom Block] Adsense Block Only Shows On Reload

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#118]
I am using a custom block to display some adsense ads. When I go to the pages they are, they do not show up unless I reload the page (F5). Happening almost consistently this way in the two different places I have them. Tested on Chrome and IE.

**Comment by GloriousKoch** [comment]
Not 100% sure if this would affect it or have anything to do with it, but it seems the static sidebar that doesn't always reload might be preventing the initial load of the ad? But then doing a full refresh, refreshes the entire thing and therefore doesn't block it?

Just a 100% guess there, but thought I'd add it.

**Comment by lilman446** [comment]
Do you have Cache JavaScript & CSS or Site Wide AJAX Browsing enabled? It will help to know this small bit of information.

**Comment by GloriousKoch** [comment]
I believe I have both enabled.

**Comment by GloriousKoch** [comment]
I disabled both of them and cleared the cache, and issue is still happening.

**Comment by RaymondBenc** [comment]
I haven't been able to confirm this but I can see this as an issue. We load all pages by default via AJAX and from what I recall adsense does not support this. Users would have to load such ads in an iframe, which we also know adsense does not allow. I'll run some tests and see what I can find.

**Comment by GloriousKoch** [comment]
Awesome thanks. I did disable site wide ajax setting in the back and it didn't seem to change it either, if that information helps.

**Comment by Data66PF** [comment]
I have the same issue for two apps I was making. Will be watching this for the solution :)

**Comment by RaymondBenc** [comment]
We found a solution for Amazon ads. I tested Google adsense locally and it worked fine for me.

@GloriousKoch can you paste your Google adsense code? I want to see if the code we are testing is the same or if Google updated their adsense code.

Thanks!

**Comment by GloriousKoch** [comment]
Here's the code with XXX replaced where account numbers are etc.:

<script type="text/javascript">
    google_ad_client = "XXX";
    google_ad_slot = "XXX";
    google_ad_width = 300;
    google_ad_height = 600;
</script>

<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

**Comment by Data66PF** [comment]
Google has new adsense code using async. Please use that because ads created with it work for our tests. We both tested on different sites. Thanks for your help.

**Comment by Data66PF** [comment]
Have you tried with new google code?

**Comment by GloriousKoch** [comment]
When I switched it to use the async code, the ad didn't show up at all, refresh or not. Here's the code using async that I'm using. My adblock extension doesn't even recognize it as existing on the page under the async code.

< script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" >< /script >
< !-- GameKrib | Member Dashboard | 300x600 -- >
< ins class="adsbygoogle "
     style="display:inline-block;width:300px;height:600px"
     data-ad-client="ca-pub-xxx"
     data-ad-slot="xxx"></ins>
< script >
(adsbygoogle = window.adsbygoogle || []).push({});
< /script >

**Comment by Data66PF** [comment]
Are you using v4.0.3?

**Comment by GloriousKoch** [comment]
I am, yes.

**Comment by Data66PF** [comment]
Ok thanks. This is working on my live development site so I'm not sure why your ad isn't showing. Maybe Ray will have an idea.

**Comment by GloriousKoch** [comment]
Do I need to possibly have some setting changed a certain way in the back end that I might not have for this new code? Like enabling "x" or something? Also, if it matters or not based on your tests I'm still using a custom block to insert the code, not hard entering it in.

**Comment by Data66PF** [comment]
I'll go test but I have to disable the Amazon ad app I made because google and amazon don't like each other.

**Comment by GloriousKoch** [comment]
Okay, I don't have Amazon app loaded so it won't be that for my issue for sure.

**Comment by Data66PF** [comment]
I haven't put it live in the store yet as it requires v4.0.4 to work. Could be the reason ours are working too.

**Comment by GloriousKoch** [comment]
Ah, gotcha.

**Comment by Data66PF** [comment]
I'm going to throw this as confirmed as now it doesn't work. There are too many issues with creating it this way. Did the user put it in an ad in the ad manager? If so, they can only choose block 50 for those due to the way Fern had it coded due to bugs in v3 but then it loses settings after set.

Did the user put it in a sitewide block? Yes? Well now it won't show up when before it did. Something is messed up again.

**Comment by Data66PF** [comment]
This works fine in 4.0.7

**Comment by GloriousKoch** [comment]
We are on 4.0.7 and still experiencing this issue. I still need to reload the page in order for it to show up properly.
