### ISSUE TITLE
Own notification

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1180]
When you like or send a message to a friend, you get a notification to yourself

**Comment by neil96** [comment]
I can't reproduce, could you give me more information to reprodcue it.

**Comment by lueung** [comment]
Just send a message or like something. You will see that you notification icons will lite up red. The other person on the other end should be getting the notification.cNot that you liked yourself.

**Comment by lueung** [comment]
I also noticed that the arched and then deleted messages are not actually deleted

**Comment by Data66PF** [comment]
Cannot reproduce at https://v4.phpfox.com

**Comment by lueung** [comment]
I will wait and see if can reproduce it on v4.3. I'll close it for now.
