### ISSUE TITLE
Cannot create photo albums on PAGES.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1183]
Create a new Page, then go to photos and click on the link to create new album an you get this

![albumissue2](https://cloud.githubusercontent.com/assets/14913734/13474929/c26fdb2c-e085-11e5-965b-34970e627912.png)

This happened on my site as well a phpfox demo site.

**Comment by Data66PF** [comment]
This is odd. I can create one as my admin user on my dev and on the demo. I cannot create one as a registered user on the demo or my dev. I checked user group permissions for photo albums and the users can create 20 albums. The user testing didn't have any albums made previously.

**Comment by Data66PF** [comment]
Tested in v4.3 and issue is the same.

**Comment by robert9592** [comment]
Fixed in v4.3.0

**Comment by PhpFoxJohnJr** [comment]
WOW!!!!  Impressive....fixed in 16 minutes.  Wish I could code like that :)
