### ISSUE TITLE
phpfox adds forward "/" slash at the end of url in when adding menu

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1184]
phpfox adds forward "/" slash at the end of url in when when adding url in the menu.

For example: http://yoursite.com/index.php/pages/?s=1&show=14

The result is: http://yoursite.com/index.php/pages/?s=1&show=14/  and displays a blank page

**Comment by Data66PF** [comment]
Are you adding a menu to an internal page? Just need to know for testing.

**Comment by lueung** [comment]
yes

**Comment by Data66PF** [comment]
I can't reproduce this on v4.2.2 using http://site.com/pages/3 as an example. Note that when pasting the url into the menu url, I remove the trailing slash as a common practice. Please try that. My site uses short urls for performance as that does speed site load.

**Comment by lueung** [comment]
I just noticed that if you use the full url it works fine, but if you only insert "pages/?s=1&show=14" then it adds the trailing slash @ the end. This was something I did not notice before. Interesting.

**Comment by Data66PF** [comment]
There are two ways to add a menu to an internal link. with the full url and via the method here https://github.com/moxi9/phpfox/issues/809
