### ISSUE TITLE
PHPfox 4.2.2-b1

### ISSUE THREAD

**Issue by paolspo** [moxi9/phpfox#1185]
PHPfox 4.2.2-b1
 during installation can't import language package, can't install. unfortunately i don't know what to do. thanks for support.
also i  opened it with edge, firefox, chrome and ie11, nothing changed, but its installed well on localhost 

![phpfox-importing-language](https://cloud.githubusercontent.com/assets/12977216/13513371/6a7f7df8-e1db-11e5-9fc7-3f2358292f40.PNG)

**Comment by Data66PF** [comment]
Please post questions at the community https://community.phpfox.com as this is a bug tracker only for bugs and there are no issues we have with installing to servers that support our script for paid licenses.
