### ISSUE TITLE
Unable to find app

### ISSUE THREAD

**Issue by dawomiit** [moxi9/phpfox#1186]
After updating from version **4.0.10** (probably, I'm not sure) to **4.2.2** my application stopped working. During sending a request to the API of my application I get below error.
> Unable to find this app

In the folder with the applications (**PF.Site/Apps**) are:
- PHPfox_Facebook
- PHPfox_Flavors
- PHPfox_IM
- PHPfox_Twemoji_Awesome
- PHPfox_Videos
- PHPfox_reCAPTCHA
- my appllication

Before update there was be only my appliaction. I checked whether the application is correctly loaded - **App::$_apps** variable in file **PF.Src/Core/App.php**. It turned out that only a **PHPfox_Facebook** application has been loaded. The problem occurs after the installation premium and development version.

To reproduce this error just install PHPFox 4.2.2 and send request to API (eg. http://example.com/index.php/api/module/action) and dump **App::$_apps** variable in file **PF.Src/Core/App.php**. There is only one app instead all apps in **PF.Site/Apps**.

**Comment by RaymondBenc** [comment]
This issue was a known issue in 4.2.* and we have resolved this for our upcoming release, 4.3.0.
