### ISSUE TITLE
Site owner admin account cannot use Pages forum Thread Tool unless site owner is admin or founder of pages

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1187]
The site owner admin account cannot use Pages forum Thread Tool to manage the forum unless site owner is admin or founder of pages, but instead is only presented with a subcribe option.

**Comment by Data66PF** [comment]
This is how it has always worked. You have a Subscribe and then at the bottom you can delete or edit the post. There have never been any other options. Please feel free to request it at our feature request section though.
