### ISSUE TITLE
In Edit Photo Move to option Showing Invalid phrase Value 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1189]
when we edit photo and select move to option In drop down its Showing Invalid phrase Value on v4.2.2
![edit photo inviald phrase](https://cloud.githubusercontent.com/assets/13433124/13625789/6e1f1eb4-e5e1-11e5-982a-d8347dc7775a.png)

**Comment by robert9592** [comment]
Fixed in v4.3.0
