### ISSUE TITLE
Script don't load when using ajax

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1192]
Hi,

Consider this script

```
<div id="my-store-717298"></div>
<div>
<script type="text/javascript" src="https://app.ecwid.com/script.js?717298&data_platform=code&data_date=2016-03-09" charset="utf-8"></script><script type="text/javascript"> xProductBrowser("categoriesPerRow=3","views=grid(3,3) list(10) table(20)","categoryView=grid","searchView=list","id=my-store-717298");</script>
</div>
```

This will load an ecwid shop into the page. If the page that have this code is loaded (not ajax) it works fine. The products are displayed. But if I click on another menu item and then return back to this page clicking on it's menu link, because the navigations is done with ajax the script no longer loads. I need to refresh the page for it to load.

How to make scripts load with ajax? I have seen the same thing happening when using script to load google charts.

Thanks

**Comment by Data66PF** [comment]
does the $Behavior tip in that issue help https://github.com/moxi9/phpfox/issues/914

**Comment by cespiritual** [comment]
Hi,
I didn't undertand quite well how to use that tip on this code. It seams that is something only for google adsense and not for universal script code.

Could some one explain how to make it work?

I'm stuck on this, because can't use google charts or other scripts on blocks and pages I do, because when I return to the page with ajax navigation, the script don't load, only loads after I refresh the page. 

thanks

**Comment by Data66PF** [comment]
It is for any javascript code. The example was showing how it would work with google but it's for any.

**Comment by cespiritual** [comment]
Is there a tutorial on this? And I need to make some core changes, is that?
I still didn't undestand how to implement this solution, and specialy, I would not like to make core changes.

**Comment by cespiritual** [comment]
I have tried that on a google chart script, and now the chart don't load. I'm putting the code inside a function, but then I need to call the function right?

Realy confused about this :)

**Comment by cespiritual** [comment]
Hi,

I have test the code above with $Behavior function like this:

```
<div id="my-store-717298"></div>
<div>
<script type="text/javascript" src="https://app.ecwid.com/script.js?717298&data_platform=code&data_date=2016-03-09" charset="utf-8"></script><script type="text/javascript"> 
$Behavior.store = function(){
xProductBrowser("categoriesPerRow=3","views=grid(3,3) list(10) table(20)","categoryView=grid","searchView=list","id=my-store-717298");
}
</script>
</div>
```
It loads when I refresh the page, but when I navigate using the menus (ajax navigation) it don't load.

Thanks

**Comment by neil96** [comment]
From V 4.4 admin can turn off full ajax mode, please turn off full ajax when add extranal js.

**Comment by cespiritual** [comment]
Can I turn off full ajax mode just to a specific module/app? What I mean is: if some one click on any menu link it works as ajax, but if it clicks on the menu link that goes to a page of that module/app the ajax will be turn off.

And Is there a way to turn of the ajax with code. Some function that I can call that will turn off ajax for that page.

Regards

**Comment by wetricks** [comment]
hello, 
did you find a solution of your problem ?
thanks

**Comment by cespiritual** [comment]
If you don't want ajax on  a specific menu entry, just edit that entry and add to the url the full path to that page: http://www.yoursite/module
