### ISSUE TITLE
Suspicious logic in setCookie

### ISSUE THREAD

**Issue by ghilton000** [moxi9/phpfox#1193]
In both v3 and v4, this logic in the setCookie function in include/library/phpfox/phpfox/phpfox.class.php does not seem right:

`(($iExpire != 0 || $iExpire != -1) ? $iExpire : (PHPFOX_TIME + (60*60*24*$iExpire)))`

The `($iExpire != 0 || $iExpire != -1)` condition always evaluates to true so there is no need to have this ternary expression.

The comment on the iExpire parameter says: "This is a Unix timestamp so is in number of seconds since the epoch.". Based on the comment, the method does what it says it will do, but the ternary expression is unnecessary.

The ternary expression would make sense if the method was trying to accept iExpire as a number of days and wanted to treat 0 and -1 as special values, but the `!= 0 || != 1` would have to be `== 0 || == -1`.

Thx.

**Comment by neil96** [comment]
Fixed on V4.3.0
