### ISSUE TITLE
getting info for any user

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1194]
Hi,

The function user() will allow you access the information of the active user. Is there a function that allow you to access the information of any user just by adding the user id to it? Something like user(4).

Thanks

**Comment by Data66PF** [comment]
please be sure to check all of our new documentation. :) https://docs.phpfox.com/display/FOX4DEVDOC/API+Functions the user info is there. hope that helps.

**Comment by cespiritual** [comment]
I did look into that. Very good information on that documentation.
In this link it explains how to get that info from DB:
https://docs.phpfox.com/display/FOX4DEVDOC/db

But my question was to know if there is a function like the user() to get all the info just by giving the user_id, so I could get, for example, the members avatar with the link to profile like this one: 
echo user()->photo_link; 

But this one is only for the active user. Is there a function for the other users?

Thanks

**Comment by neil96** [comment]
Please try this: 
```
$user = (new \Api\User())->get(19);
echo $user->photo_link;
```

or

` (new \Api\User())->get(19)->photo_link;`

with 19 is other user_id.

I think other questions like this you should ask on community. You can ping me there.

**Comment by cespiritual** [comment]
Thanks Neil... don't forget to update this tutorial with that info:
https://docs.phpfox.com/display/FOX4DEVDOC/user

ok... I will use the community for this type of questions.

Regards

**Comment by cespiritual** [comment]
Neil, just one last question:

The echo of the image shows a 120px size image. If I place that image inside a div with 90px size it works fine for images and it resizes to the new size, but for members that don't have images and show the letters with color background, when I resize the letters no longer show centered. How to prevent this from happening?

thanks

**Comment by neil96** [comment]
flagEnglisharrowgif
You can add more css to put letters in the center. Because we only support in some sizes. (May we have another best way, but I don't know)
Please remember to add more class or ID to your css, your css may effect to another place.

**Comment by cespiritual** [comment]
What do you mean by this: flagEnglisharrowgif
