### ISSUE TITLE
Sharing problem

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1197]
Hello :) 

When you share something , it works when sharing photo's , but when you share a status or anything else, it brings up the box "on your wall, on your friends wall" , and it gives the option to add text to it, but when you actually share it, it actually only share's the text you just put in and not the status you chose to share,  so obviously if you dont put in text, it'll say ----- share'd --------- (without saying anything) , I've tested it on the phpfox demo and its the same

**Comment by neil96** [comment]
Duplicate with #1029
