### ISSUE TITLE
site not loading well after upgrade

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1198]
Using latest phpfox with bootstrap, both mobile and desktop versions , chrome, firefox
After upgrading to new version 4.3 my website is not loading properly. it became too slow and feed is not loading at all. All other modules(blogs ,polls etc) are working fine and no speed issue also with them. but when i click "home"  to view the main page it become slow and don't load feed. I followed all the upgrade instructions ( rebuild theme (later i tried revert theme also), clear cache. even i deleted cache files manually).
![image](https://cloud.githubusercontent.com/assets/406030/13752888/1352ce5c-ea11-11e5-9934-583231f8c0a3.png)

**Comment by neil96** [comment]
Can I test on your site?

**Comment by aakash83** [comment]
yes you can register and test. www.virtualians.com . also on main page the top navigation buttons ( meesages ,notification and settings ) not working. on all other pages those buttons are working.

**Comment by aakash83** [comment]
@neil96

**Comment by neil96** [comment]
Hi @aakash83 ,
I checked on your site. I have seen the error in feed block.
Could you please submit a ticket with ftp and adminCp? So I can check in more detail.
Thanks!

**Comment by aakash83** [comment]
@neil96  I made u admin there.you can use your existing account as admin now. Is it enough for you to inspect this issue?

**Comment by aakash83** [comment]
@neil96

**Comment by Data66PF** [comment]
Please stop tagging neil. He will see it on Monday as the details came after he had left for the day.

**Comment by aakash83** [comment]
i did not tagged again after your response.thanks

**Comment by neil96** [comment]
Hi @aakash83 ,
Last week, I visited your site, I got a blank page. Now, I visit your site, I get a blank page again. So I can't check your issue?
Could you please create a ticket with ftp information. Your issue can't check without ftp. Thanks.

**Comment by aakash83** [comment]
I created a ticket and included ftp info. also I made you admin with the same account you registered on my website. thanks

**Comment by neil96** [comment]
Fixed on your site.

**Comment by aakash83** [comment]
Thanks it is working now.

**Comment by koch194** [comment]
Hello @neil96 ... Please i am having the same issue... with phpfox... I upgraded to to 4.2 and my home page cant load anymore. my website is http://fansbox18.com 
If i go to http://fansbox18.com/index.php/blog/ it loads the blog page. I just did 301 redirect to take my users to the blog page while i try to fix the index page problem. 

**The website cannot load on mobile devices. please i need assistance. ** Thank you!

**Comment by aakash83** [comment]
upgrade to latest version and it will be fixed.

**Comment by koch194** [comment]
i have been trying to download the upgrade... http://store.phpfox.com/download i cant see the like to the zipped file. @aakash83

**Comment by aakash83** [comment]
goto https://clients.phpfox.com/clientarea.php . login with your email and pass. then click "Your Active Products/Services"  (located in the center of page)  on the next page you can see " download latest phpfox"  under licence information.

**Comment by koch194** [comment]
Thank you @aakash83
