### ISSUE TITLE
[Mobile Issue] Very Out Of Line Content On Android 5.0

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#120]
When I check on my Android 4.3 it looks okay, however a user using a Note 4 with Android 5.0 said the website looks like this:

![image](https://cloud.githubusercontent.com/assets/6254165/8712528/41339716-2b2b-11e5-8aa9-9837f1ae84f6.png)

**Comment by MBonner702** [comment]
I am confirming this issue.

**Comment by MBonner702** [comment]
This issue was listed as a bug fix for v4.02 but still exists. I don't see the problem when I go to the phpfox community but it is happening. On more than one site apparently. 
Thanks for any help you can provide.

**Comment by Jinkers** [comment]
@MBonner702 - If you are still using the default theme, try making a new one and setting is as the default. I did that and it seems to have fixed the issue.

**Comment by MBonner702** [comment]
I don't know how to create themes...do I just create a duplicate of the first?

**Comment by Jinkers** [comment]
@MBonner702 Go to AdminCP->Themes. In the top right hand corner you should see "New Theme". Click that and Enter a new name for the theme. Let it do its work. Sometimes you need to leave the page (i just go the dashboard) if nothing is happening after a minute or two and go back. Once the new theme is there, click on it and down the bottom select 'Set as default'.
![image](https://cloud.githubusercontent.com/assets/7270030/8759881/017fe42e-2d44-11e5-98a4-db8b596b4b11.png)

**Comment by Data66PF** [comment]
Did you ensure to follow all of the steps when updating the site? http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ Log in to view. You need to do all of that to get new theme stuff imported, to get new settings and phrases.

**Comment by RaymondBenc** [comment]
When upgrading a theme and using the default theme, make sure to **Revert Theme** when you manage it. Since certain bug fixes are CSS related the product needs to rebuild themes with the new CSS changes and **Revert Theme** will do that.

The issue now is that this is only available for the default theme. I'll mark this case as a **Bug** so we can build a way to update all the themes with the latest CSS changes.

**Comment by RaymondBenc** [comment]
The upcoming release 4.0.8 will have a feature to Sync themes with our stock less files.
