### ISSUE TITLE
Recommended users keeps getting added & no way to control it

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1203]
Recommended users is getting out of control as new users signup to the site and keeps getting added to the browse section and no way to disable or control it.

**Comment by Data66PF** [comment]
The recommended users is a display of suggested users to friend, etc. It is supposed to be random though and I see it does not appear random at all. I think we need to check this just to make sure it is showing properly.

In regards to adding settings for it, please post a feature request as this is not designed to have settings.

**Comment by lueung** [comment]
I think it might help if we understood on it functions so maybe we can request for features to enhance it. Without any additional info, the only feasible thing I can of is to a feature request setting to disable in admincp.

**Comment by neil96** [comment]
Actually, that's suggest friend block. I changed phrase and made a setting to hide/show this block.
