### ISSUE TITLE
Can not view photo at detail b-day event on IE 11

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox#1204]
*Actual* 
Can not view photo at detail b-day event on IE 11 

*Expected* 
Can view photo at detail b-day event

**Comment by Vivian-phpFox** [comment]
Can not reproduce in V4.3. Can you reproduce on demo site?

**Comment by Nghiep-YouNet** [comment]
Thank you for your inform. This issue is happened on V4.2.2 . It seem that it has been fixed in V4.3.
