### ISSUE TITLE
Warning message displays at other pages when user select invalid data

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox#1205]
** Device: iPad - iOS 9.2.1 - Safari **
1- Create Blog and do not input anything
2- Click save >> warning message displays 
3- No select again and tap on other pages 

*Actual* 
Warning message displays at other pages 

*Expected* 
Should not display message at other pages

**Comment by Vivian-phpFox** [comment]
Cannot reproduce in V4.3

**Comment by Nghiep-YouNet** [comment]
Thank you for your inform. This issue is happened on V4.2.2 . It seem that it has been fixed in V4.3.
