### ISSUE TITLE
not in Phrase variables

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1206]
Put these variables in phrase table so that we can use it easily Regardless of its hard code values.
(Pending Friend Request) and (Manage Friends) In Timeline Menu
i check it in v 4.0.3
PFA the same.
![manage friends phrase](https://cloud.githubusercontent.com/assets/13433124/13773860/b86413f0-eac1-11e5-922d-45462f24c9d8.png)
![pending friend request](https://cloud.githubusercontent.com/assets/13433124/13773862/b8726892-eac1-11e5-825f-30e1c734e7f9.png)

**Comment by neil96** [comment]
Did you check on v4.3.0 or V4.0.3?

**Comment by SalmanKhan86** [comment]
i check it on PF latest release 4.3.0-b2

**Comment by neil96** [comment]
Fixed on V4.4.0
