### ISSUE TITLE
Menus fileld Active/Inactive option

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1207]
how can i Enable/ Disable Menus options.i have to go to database tables for status change to Active/Inactive. in Menus Toggle option need here,check PFA the same
![enable disable](https://cloud.githubusercontent.com/assets/13433124/13774182/9f704d26-eac3-11e5-9bd6-c1cc25369ec2.png)

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#86

**Comment by Data66PF** [comment]
This is a feature request so was moved to that section as it's always been like this for v4.
