### ISSUE TITLE
      admin Cannot remove post from others on admin wall need fix asap 

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1209]
admin Cannot remove post from others from from admin wall need fix asap even tho it confirms that feed is deleted. related to #1208

**Comment by Data66PF** [comment]
Is the user group setting set to allow it?

**Comment by lueung** [comment]
yes

**Comment by Data66PF** [comment]
I cannot reproduce this but my admin has the Feed settings for can delete other feeds at True and for can delete feeds from profile at true.

**Comment by Data66PF** [comment]
noting that your other bug report covers the issue of the can delete other feeds.

**Comment by lueung** [comment]
if someone post on your wall. You then go to your wall and try to delete. It will confirm that it is deleted, but in actuality it did not.

**Comment by Data66PF** [comment]
In my tests for admin user, it deletes fine for me. however, I have the setting for can delete other feeds at true.

**Comment by lueung** [comment]
I have the same settings

**Comment by lueung** [comment]
Are you deleting from the admin account's wall or someone else's wall? on someone elses wall it deletes fine, but not on the admin wall.

**Comment by lueung** [comment]
OK. I figured out how for you to reproduce it. 

1. Post to your admin wall from another account.
2. Click on the notification icon to see the post which will take you to your wall.
3. Now try to delete the feed post. It won't let you.

The bug will only occur by following the above steps. If you go directly to your wall by other means it will delete just fine.

**Comment by Data66PF** [comment]
doing those steps, I can reproduce it.
