### ISSUE TITLE
Can't use back button in browser after clicking on photo/create an ad

### ISSUE THREAD

**Issue by starplan** [moxi9/phpfox#1210]
Thought I'd bring this to your attention. I clicked on an image to view it, but when I clicked on the back button in my firefox browser I didn't go back to the previous page. On the same page of as the image I clicked on "Create an Ad" but could not go back using the back button in the browser. The latter happened in Chrome and Firefox.

**Comment by Data66PF** [comment]
Tested in Chrome at the https://v4.phpfox.com demo and I can hit the back button on the browser with no issue as it goes back to the previous page for me. Using a macbook pro, El Capitan os.

**Comment by starplan** [comment]
I noticed this on a Windows 7 computer using Firefox 44.2

**Comment by neil96** [comment]
Please check address bar, back button of browser is only available  when address (url) changes. Our platform is using full ajax mode, so many actions load with ajax so url is not changed.

If it's changed, and back button is still not working, please send us some screenshots. Thanks!

**Comment by shakti7188** [comment]
working fine with other sites- i tried with gmail, facebook, google search etc.
i checked again many times. yes it works but not in first attemp. see the screenshot.
![screen shot 2016-08-26 at 12 44 06 pm](https://cloud.githubusercontent.com/assets/8586180/17997224/e431a0de-6b8a-11e6-81f8-e8475c991e69.png)
