### ISSUE TITLE
Pages blog permission lets anyone that can view also create a blog even if not part of the group

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1213]
If someone is not part of a group of pages they should not be able to write to any pages even though they can view it.

**Comment by robert9592** [comment]
The owner can change permission settings of their group in Manage (Edit page) -> Permission tab. By default, when you create a page, it is a public page.

**Comment by Data66PF** [comment]
This is a bug. I created a page and in the page privacy are two settings regarding blogs. One is for viewing it and one is for posting (sharing). The way these are supposed to work is:

1. If anyone can view a group/pages blogs, then non members can view it.
2. If only members can share blogs, that means only members of the page can post a blog to the page. This is not working.

Please create a page or group. Please set the permissions for Can View Blogs to anyone and Can Share Blogs to Members only. 

Go post as a non member in a blog for that page/group and you will be able to do that. This is not working.

**Comment by Data66PF** [comment]
This is extremely important for privacy on the site. We cannot have non members posting to Pages and Groups when the permissions are set so they can't.
