### ISSUE TITLE
Denying Friend Request will display "Pending" indefinitely

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1215]
If your friend request is denied it will stay display "pending" indefinitely instead of resetting.

**Comment by neil96** [comment]
Did you change this setting to "No" (settings -> friends-> "Hide denied requests from pending list")

**Comment by lueung** [comment]
No what I mean is that it should reset instead of just hiding it and the person should get a notification that they are denied. If it's hidden then the person can't re-request. unless they are blocked.

**Comment by Data66PF** [comment]
This is working as designed. I have it set to No for "hide denied requests from pending list" so I can see the user still listed there. When I click their user image, I go to their profile. On that profile, I see Pending Request and I see Cancel Request. I can cancel the request there. 
![cancel request](https://cloud.githubusercontent.com/assets/6908282/15391171/b4338dfc-1d8d-11e6-9b1d-6d3dc8883fe5.png)

To change how this works, please file a feature request (for one item) or more than one feature requests if you want to change more than one thing.
