### ISSUE TITLE
Cannot send a message to non friends (pre-v4.3 users) even though privacy setting is set to accept messages from community 

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1216]
Cannot send a message to non friends (users before v4.3) even though privacy setting is set to accept messages from community. However, any pre-v4.30 can send a message to to any members that are post v4.3 update if their privacy setting is to accept message from community.

**Comment by Data66PF** [comment]
Is the user group setting for This setting tells if the user can only send messages to people in his/her friends list. at No?

**Comment by lueung** [comment]
Both users are in the same user group

**Comment by Data66PF** [comment]
Signed up a new user on my test site. Tested sending to another user who is not a friend and was on the site before the upgrade. It would not send. I then went and double checked and the registered users were set not able to send messages to non-friends. I set that to allow them to send to non friends and tested again. Now, the user can send the message without issue.

**Comment by lueung** [comment]
Seems I missed the, "This setting tells if the user can only send messages to people in his/her friends list" setting. Is it just me or is the wording not very descriptive ?
