### ISSUE TITLE
Twemoji in PM dropdown panel works only selectively.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1219]
The PM dropdown panel Twemoji is working on some installations but not others. It works okay on all other locations such as forums and blogs, just selectively not for PM.  The PM implementation is the only one where a popup (Twemoji selector) being opened from a popup (the dropdown panel (if it is in fact a popup)).  It works for some installations such as the staging server, but for others it does not.  Users relating on PM is probably where emoting gets used the most so this is important to make sure this works for all server setups.

**Comment by Data66PF** [comment]
In PM threaded messages, I see it has disappeared but it should still be there. Will mark this a bug. Am testing with normal PM and not with the IM chat enabled. Am testing in a threaded conversation as the Twemoji shows fine on first message but disappears thereafter.

**Comment by Gatsby-PF** [comment]
To be clear, the Twemoji icon exists in the PM message create panel, it just does nothing... it will not insert a twemoji in the message.  Your post refers to the twemoji successfully but temporarily displaying in thread message posts after it was inserted which is a different issue.
