### ISSUE TITLE
[Photos] Can't Remove Categories + Setting Doesn't Disable

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#122]
I'm unable to remove categories from the image feature in the admin section. I click one, hit delete, and it reloads, but doesn't actually go away.

When I set the setting to 'off' or 'no' (forgot which it is) for allowing them to set a category, it still shows up in the 'edit image' option.

**Comment by Data66PF** [comment]
Deleting a photo category is working for me. I delete, clear cache, and it is deleted. I cannot reproduce an issue with deleting.

For the second bug submitted (please use one per issue), did you test as a registered user or admin? Admin sees all.

**Comment by GloriousKoch** [comment]
The clearing cache fixed it for me. It just slips my mind to use that, as some setting work live and others like this seem to NEED the cache button pressed. Any idea why that is? Closing this one either way though, thanks. :)
