### ISSUE TITLE
Hav't received Passcode yet Debug Error

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1220]
when i click on Hav't received Passcode yet in sign in and with google 2 step verification enabled.
i found followings error in debug mode enabled in 4.0.3
![passcode error](https://cloud.githubusercontent.com/assets/13433124/13802083/2fbe2e26-eb5e-11e5-90bb-481c9540aa9f.png)

**Comment by neil96** [comment]
Fixed on V4.4.0
