### ISSUE TITLE
reCAPTCHA Not Showing in Sign up

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1221]
when i enabled reCAPTCHA in Admin Cp its not showing in sign up form and i am not able to sign up.after we click on sign up there is not activity.
check in 4.0.3

**Comment by Data66PF** [comment]
It is working on our v4.3 demo. Are you sure you have the correct recaptcha keys for your site? Please look in developer browser console and see if you have errors with it as it does require the keys to be correct at Google.
