### ISSUE TITLE
user group is not working as it should, to create a page or a block, with access to a particular group of users.

### ISSUE THREAD

**Issue by cympgo** [moxi9/phpfox#1222]
ATENÇÃO, QUEM TIVER COMUNIDADE ATIVA VERSÃO 4.3.0.
Anyone who has content of the page created for a User group in AdminCP , get tested ! take the url of this page and open another sailed as a guest without logging into the system and try to access this page .

---------------------------------------------------------------------------------------------------------------------------
DETAIL BELOW ERROR

Group of users is not working as it should, to create a pagiana or block access to a particular group of users, other groups can not access the page that is restricted to another group, it is expected!

Now for the bug , if the User is offline and enter the url of the page that was created for a particular users access he can see the contents without logged when the right was to be redirected to the subscription page . Eg is page is restricted access to grumpo admin users and another group that I created . if you access this URL will be able to see the contents of the page that was not to see.

**Comment by Data66PF** [comment]
duplicate #1196
