### ISSUE TITLE
4.3.0.b4 Search Users in admincp IP is cut off 

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1223]
v4.3.0.b4 Search Users in admincp IP is cut off in firefox : http://prntscr.com/ag6m0t

**Comment by robert9592** [comment]
Do you see the scroll bar at the bottom? Because pages in Admincp don't support responsive so if content is too long, we will have a scroll bar at the bottom.

**Comment by lueung** [comment]
Yep. You have to scroll all the way down. That is is really annoying to have to do that all the time to use it.

**Comment by neil96** [comment]
That's scroll only display on low resolution screen.
