### ISSUE TITLE
Blog summary is showing the full length of the blog in each summary.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1225]
What is supposed to be an index of  blog summarys is the full blog content in each summary.  The summaries are not lining up in their vertical columns properly.  There are great vertical gaps between summaries in some places.  I am not understanding the point of clicking on a link to the blog article from the summary index when the entire article displays in the summary already.
4.3.0b2

**Comment by Data66PF** [comment]
Odd. I'm not seeing that at the demo https://v4.phpfox.com/blog/ . Default BS theme?

**Comment by Gatsby-PF** [comment]
I checked this using the reverted, rebuilt bootstrap core I used with the last issue I closed and I no longer have the problem. This was in my theme.
