### ISSUE TITLE
Site is not loading Properly Localhost Server

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1227]
i have installed fresh PF site in my local development server.i am using nginx web-server on Ubuntu server.using latest v4.0.3 found following errors
![nginx error](https://cloud.githubusercontent.com/assets/13433124/13844953/f753be60-ec62-11e5-8966-75ed194239ed.png)

**Comment by Data66PF** [comment]
Please change your github issues to show v4.3.0 as it will confuse our techs if you keep posting 4.0.3

**Comment by SalmanKhan86** [comment]
@Data66PF ok

**Comment by Data66PF** [comment]
Please use v4.3.0 build 5 found in the client area.

**Comment by SalmanKhan86** [comment]
same problem. i use v4.3.0 build 5

**Comment by SalmanKhan86** [comment]
any update on this.

**Comment by SalmanKhan86** [comment]
solve this on priority

**Comment by SalmanKhan86** [comment]
solve this on priority

**Comment by Data66PF** [comment]
I have about 7 local installs and no issues loading it at all.

**Comment by Data66PF** [comment]
I've left it open for our core developers to test on other local set ups but please make sure you have downloaded the most recent files from your client account as there were some fixes for local install issues before and added to build 5 release.

**Comment by SalmanKhan86** [comment]
Using Nginx on Ubuntu Linux server not able to load site..

**Comment by neil96** [comment]
The issue with nginx was fixed on 4.3.1.
