### ISSUE TITLE
Android Neutron Timeline Issue

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1228]
in Android browser using latest v4.3.0 timeline alignment is not proper.i am using neutron theme
![screenshot_2016-03-16-17-18-12](https://cloud.githubusercontent.com/assets/13433124/13845026/4738b692-ec63-11e5-9a58-b821260f0b19.png)

**Comment by SalmanKhan86** [comment]
any update on this

**Comment by neil96** [comment]
Did you using 4.3.0?
On V4, we didn't support timeline anymore.
Neutron theme didn't core theme.

**Comment by SalmanKhan86** [comment]
i am using 4.3.0.you can see in screen show profile pic is appear over profile info text.so i say it timeline.

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.
