### ISSUE TITLE
Sign up and Login block Alignment Problem Android Neutron

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1229]
login and sign up is not loading properly. back screens is moving behind when we scroll up and down. everything is mix in it.using Neutron theme v4.0.3 Android Browser
![screenshot_2016-03-16-17-21-51](https://cloud.githubusercontent.com/assets/13433124/13845181/40d80e1e-ec64-11e5-8d50-c13cab9311da.png)
![screenshot_2016-03-16-17-22-45](https://cloud.githubusercontent.com/assets/13433124/13845183/40dc30f2-ec64-11e5-9447-327a6e9cc3af.png)
![screenshot_2016-03-16-17-23-19](https://cloud.githubusercontent.com/assets/13433124/13845182/40dbe7be-ec64-11e5-9175-3e517791ee21.png)

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.
