### ISSUE TITLE
FATAL error after upgrade

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1230]
latest phpfox with bootstrap
after upgrading to latest version my website was not loading well(only the main page and feed). Now I am getting this error message. it takes long time to load then in the end shows this message,
But this problem is only for main page (logged in) . I can browse forum , pages etc without any problem.

Fatal error: Allowed memory size of 176160768 bytes exhausted (tried to allocate 77 bytes) in /home/abccc/public_html/PF.Src/Core/App.php on line 453

This issue is related to #1198 . waiting response from @neil96

**Comment by Data66PF** [comment]
Please leave the other bug open for this but don't post duplicates. Please wait for neil to see the ticket Monday.
