### ISSUE TITLE
Like button is not shown in android phone. 

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#1231]
Like button is not shown in android phone.

**Comment by GreenMan123** [comment]
I have uploaded the snapshoot of this error in the demo site.

**Comment by SalmanKhan86** [comment]
pls also provide here snapshoot of this error

**Comment by GreenMan123** [comment]
![1458474548426](https://cloud.githubusercontent.com/assets/13588067/13904256/56589238-eeab-11e5-99f5-1658e951eb51.jpg)
![1458473299372](https://cloud.githubusercontent.com/assets/13588067/13904260/689e031a-eeab-11e5-81fe-372a749aa115.jpg)
![1458474605866](https://cloud.githubusercontent.com/assets/13588067/13904263/7aa1a9ae-eeab-11e5-8541-8ff927f63be5.jpg)

**Comment by GreenMan123** [comment]
This is the snap shoots which happens also in opera mini in android phone Also I have add the poke, send message,  and poke how they appear. Please make the like button visible/thumb/....

**Comment by GreenMan123** [comment]
![screenshot_2016-05-21-10-29-32](https://cloud.githubusercontent.com/assets/13588067/15447144/9e403da2-1f3f-11e6-8e6e-b6e24794e84f.png)

**Comment by GreenMan123** [comment]
Opera mini browser in Android phone

**Comment by neil96** [comment]
Our platform don't support Opera and Opera mini. You can refer to the list of supported browsers [here](https://docs.phpfox.com/display/FOX4MAN/Supported+browsers).
