### ISSUE TITLE
v4.3.b4 Status posts containing 2 or more paragraphs makes status vanish when "view more" is clicked

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1232]
Status posts containing 2 or more paragraphs makes status vanish when "view more" is clicked

**Comment by Data66PF** [comment]
https://v4.phpfox.com/profile-2614/?comment-id=134 can't reproduce this issue.

**Comment by lueung** [comment]
can lo longer reproduce this in v4.3.0.b5
