### ISSUE TITLE
Feed does not reflect where it was posted When Posting on Pages Status

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1235]
Feed does not reflect where it was posted When Posting on  Pages Status.

**Comment by Data66PF** [comment]
Please be more detailed with bug reports. Screenshots are necessary in some things such as things like this. Detailed steps to reproduce it are also needed for bug reports.

**Comment by lueung** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/13936651/7777757a-ef95-11e5-9c71-5fbb6b738c5f.png)

**Comment by neil96** [comment]
Fixed on 4.3.1
