### ISSUE TITLE
Sign up Button is not Showing After Enabling Google reCAPTCHA

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1237]
i have enabled google reCAPTCHA and put site key and secret key provided by google .after that sign up button is not showing in sign up page after verification by reCAPTCHA.  4.0.3
![recaptcha probelm](https://cloud.githubusercontent.com/assets/13433124/13910816/dd9b0ff8-ef4d-11e5-8083-035c659bcba1.png)

**Comment by neil96** [comment]
If you are using v 4.0.3, please upgrade to 4.3.0. Thanks!

**Comment by SalmanKhan86** [comment]
i am Already using 4.3.0

**Comment by Data66PF** [comment]
This is how it is designed as google recaptcha replaces the button. When a user completes their info and the recaptcha challenge, it will automatically proceed. Is it not proceeding for you?

**Comment by SalmanKhan86** [comment]
no its not proceeding for me after complete sign up and validate recaptcha
challenge

On Mon, Mar 21, 2016 at 3:51 PM, Data66 <notifications@github.com> wrote:

> This is how it is designed as google recaptcha replaces the button. When a
> user completes their info and the recaptcha challenge, it will
> automatically proceed. Is it not proceeding for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1237#issuecomment-199213182>
>



-- 
Thanks & Regards
Pankaj Garg
M.+91-9728598858

**Comment by Data66PF** [comment]
Does it work for you on our https://v4.phpfox.com demo?

**Comment by SalmanKhan86** [comment]
yes

On Mon, Mar 21, 2016 at 4:34 PM, Data66 <notifications@github.com> wrote:

> Does it work for you on our https://v4.phpfox.com demo?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1237#issuecomment-199226854>
>



-- 
Thanks & Regards
Pankaj Garg
M.+91-9728598858

**Comment by Data66PF** [comment]
Please check your site with developer browser debug open to see what errors you might have with your recaptcha. Make sure you are using the latest version of the script, 4.3.0 build 5, and the latest version of recaptcha. Make sure your recaptcha at google doesn't have any issues as I cannot reproduce any issues on my test sites or on the demo and you also can't reproduce any issue on the demo.
