### ISSUE TITLE
Groups' Admin Can't Approve Membership

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1239]
Per ticket 155.

As a Registered user, create a front end Group with privacy at Approval First.
As another user, join the page.
As the Group Admin (from step 1) click your Notification that someone joined the group and you will be brought to the group.
Now click the Pending Memberships and you will see the pending member.
Hover over their image to try to approve them but no box shows up to select them.

If you try the above as a Site Admin in a group you make, you can see the approval checkbox so this only seems to impact anyone other than a Site Admin.

**Comment by neil96** [comment]
Fixed on V4.3.1
