### ISSUE TITLE
v4 Quiz categories and settings not available

### ISSUE THREAD

**Issue by todaylogin** [moxi9/phpfox#124]
photos and quizzes categories  in not available in v4?

**Comment by Data66PF** [comment]
Please ask questions like this at the community, http://community.phpfox.com/forum/ as this issue tracker is for bugs. Thanks!

**Comment by Data66PF** [comment]
Updated title and confirm for the Quiz issue only. Photos issue is not confirmed as I can see settings and categories for it.

**Comment by lilman446** [comment]
I also can confirm Quiz issue only on both dev and live test site I can see Photo settings and Categories.

**Comment by Data66PF** [comment]
Oops I forgot quizzes don't have categories, didn't in v3 either. This would be an enhancement, not a bug.

**Comment by todaylogin** [comment]
so please tell us how to we add cats in this module

**Comment by Data66PF** [comment]
You would need a developer to add them or see if it is approved as an enhancement.
