### ISSUE TITLE
Pending Verification Members bug

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1240]
Latest phpfox with bootstrap
If our site is set to email verification  then a new member who did not verified his account  still have a profile link, is shown in New member block  and even we can send them message or Poke them. and we can send friend request to them.

**Comment by Data66PF** [comment]
So if you go to their profile, you can interact by poking, etc and it is not just with the block itself?

**Comment by aakash83** [comment]
yes

**Comment by Data66PF** [comment]
When you delete them in AdminCP, which method are you using? do you click the drop down next to the user image and select Delete, or do you click the checkbox and then click the delete at the bottom of the page?

**Comment by aakash83** [comment]
I got a lot of fake members in past couple of days . some of them i deleted by  selecting all option (when i have to deleted all from a search member page) on top   and then using delete button on the bottom of page. and some of them i deleted using drop down button located next to each member profile. 

I got that list by admincp >> search >> then selecting only show pending verification members

**Comment by Data66PF** [comment]
Odd because my New Members block that I made and is in the store is not showing pending members for me. I just tested it. I have it coded not to show them. So I don't know if you have a different one or if something is odd with your pending users.

I then tested deleting the users and they all deleted. I cannot reproduce any issue.

**Comment by aakash83** [comment]
ohh Got it. they are duplicates.
