### ISSUE TITLE
Blank White Profile Images

### ISSUE THREAD

**Issue by datascrub** [moxi9/phpfox#1242]
Members profile images went to white after upgrade from V3. Same members don't show up in a back end search from the control panel and when I try to email/message them it shows up in my notifications like the user sent it to me.

**Comment by Data66PF** [comment]
I can confirm there is an issue with upgrading but it is not on all upgrades. I upgraded three sites all on the same hosting yesterday and one of them had this issue. It is not all profiles either. It is only a small percent.
