### ISSUE TITLE
Google Adsense- v4.3 build 5

### ISSUE THREAD

**Issue by bamafanz** [moxi9/phpfox#1244]
Hello, 
Someone may have already posted this. Apologize if this has already been covered..
There seems to be an error with google adsense is v4.3 build 5. This is setting the google ad (sitewide)

https://docs.phpfox.com/display/FOX4MAN/Setting+up+Google+Adsense

Thanks...

**Comment by Data66PF** [comment]
I can confirm that with that code change, in build 5 it makes the share button at the status share, disappear when clicking the Photo share or Video share. If I remove the new $Behavior code and instead use the original Google ad code, things work fine. As this worked prior to updating his site to Build 5 from Build 4, I think we have an issue in Build 5 with that tutorial code. Will mark a bug but am not sure if it's just a matter of not using that code now and instead to use the original google code or if we will have issues with other things.

**Comment by neil96** [comment]
Google adsense and other ads service like adsense don't work well on full ajax mode site. So, from 4.4.0 we make a new setting allow you turn off full ajax mode.
