### ISSUE TITLE
Main forum Does not pickup on url if no space is used on bbcode

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1246]
for example: [b]http://whatever.com[/b]

**Comment by Data66PF** [comment]
this works fine in my tests

```
[link]http://scripttechs.com[/link]
[link][b]http://scripttechs.com[/b][/link]
```

**Comment by lueung** [comment]
What I mean is if you exclude link. For example if you don't include any tags it will just pickup the url,  but if you want to include bold then it no longer picks up the link without adding a link tag.

**Comment by Data66PF** [comment]
But if you are adding bbcode tags, you need to fully add the tags from what I recall.
