### ISSUE TITLE
Staff or admin cannot add self as admin of pages, but can add others

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1247]
Staff or admin cannot add self as admin of pages while in the pages admincp, but can add anyone else.

**Comment by Data66PF** [comment]
Well, this was designed to add friends as admin to the page. It was not designed to add self to page so really, it is working as designed. I'll move this to feature requests as we should have this ability to add ourselves as admin to a page/group.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#100
