### ISSUE TITLE
phpfox bbcode not standard for forum

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1248]
phpfox's bbcode appears to not be standard. tags like [url][/url] doesn't work.

No tag list anywhere. I guessed & found that [link][/link] did work.

This is another example why we need a basic WYSIWYG. Now imagine the non technical end user.

**Comment by Data66PF** [comment]
Questions should be asked at the community. If you have a bug, please let us know in this issue report. If you have a question, please post that at the community.

**Comment by lueung** [comment]
Would this be considered a bug since the tags like [url][/url] doesn't work? By guessing I found that [link][/link] did work

**Comment by Data66PF** [comment]
Isn't your bbcode url issue already in a bug report?

**Comment by lueung** [comment]
Yes that is a different issue with the url not getting picked if there is a space in the link

**Comment by Data66PF** [comment]
We have always used the [link] code though. If you go look in v3 it was the same. If you would like a tutorial for the codes we allow, please feel free to ask in the community section for requesting tutorials.
