### ISSUE TITLE
V4 Image sizes need to match for same width columns

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1249]
I didn't go through all the different areas but for this bootstrap theme the image sizes need to match for the column width.

Under pages there is the standard left block (I think all left blocks and right blocks are the same width) in which the images for Followers go three across.  PERFECT FIT :)

But under Profile page in the same block area shows liked pages and only two images go across which waste the third image that could fit on there if the images were not so big.

Someone needs to go through all the menus and whether it is followed, liked, my pages, favorite page...or whatever.  If it is in that size block they should all be the same :)  Good Luck.

![phpfox-following-image-just-right](https://cloud.githubusercontent.com/assets/14913734/14038043/5ee63222-f219-11e5-8fd7-dc7e7791db45.jpg)

![profile-page-like-image-too-large](https://cloud.githubusercontent.com/assets/14913734/14038049/674072f2-f219-11e5-919b-49a819824a09.jpg)

**Comment by Data66PF** [comment]
Marking a bug as we should be uniform throughout the site.
