### ISSUE TITLE
How to upgrade 3.8 modules to V4

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#125]
Can we expect basic how-to on what changes are needed to convert 3.x modules to 4 

I tested v4 upgrade of older 3.8 install ( with existing custom modules ) 

Install went fine and V4 came up 

However none of the 3.8 modules came up 

please assume that custom modules are extremely basic and just need to upgrade them to v4

**Comment by signupsi** [comment]
phpfox should have at least one document on what kind of changes are expected to migrate 3.x modules to 4.x

**Comment by Data66PF** [comment]
Each developer has to first update their addons in order for you to have updated addons. It is documented here in the github with examples and here, http://support.phpfox.com/

**Comment by Data66PF** [comment]
Please post questions in the community forum as the bug tracker is only for bugs. Thanks! http://community.phpfox.com/forum/114/neutron-v4/
