### ISSUE TITLE
Special Character In #tag Issue

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1251]
In #tag Special Character can be ignored so that it can become a sensible word.No one can use special char here if it is make a sense.check it on v4.3.0 build 5
![hashtag special char issue](https://cloud.githubusercontent.com/assets/13433124/14040765/90e636e2-f290-11e5-81f3-283393d80440.png)

**Comment by Data66PF** [comment]
I'm not sure what you mean. Do you mean that if someone puts test and then puts test!!! or test>>> that those two other tags should show with the first one? I don't think they should as there are special characters in languages that might make the words mean something else one way than the other and we would not want to lump everything together, if that is what you mean.

**Comment by SalmanKhan86** [comment]
yes
