### ISSUE TITLE
Trending Topics Auto update Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1252]
Trending Topics box is not auto updated.we have to refresh page to see new #tag trend in it.this is big problem in it.it can be auto updated.

**Comment by Data66PF** [comment]
These are cached. The tags have always refreshed when cache clears. This is working as it is designed to work. I suggest a feature request to add a setting for time to clear cache for tags but that also might not work well.

**Comment by SalmanKhan86** [comment]
for every time we can't clear cache. you think we appoint special person
for clear cache Always.

On Fri, Mar 25, 2016 at 5:34 PM, Data66 <notifications@github.com> wrote:

> These are cached. The tags have always refreshed when cache clears. This
> is working as it is designed to work. I suggest a feature request to add a
> setting for time to clear cache for tags but that also might not work well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1252#issuecomment-201253550>
>



-- 
Thanks & Regards
Pankaj Garg
M.+91-9728598858

**Comment by Data66PF** [comment]
I do note though that on my dev site, the tags show up pretty fast. When you are testing, are you not seeing your tags? I know there was a post about this once before and it was working as designed. I've left this open for one of our core developers to see it as I wanted their feedback in it as well. This is why I didn't close it.

**Comment by SalmanKhan86** [comment]
i my testing again and again but i don't see any tag in box without refresh
page.

On Fri, Mar 25, 2016 at 6:37 PM, Data66 <notifications@github.com> wrote:

> I do note though that on my dev site, the tags show up pretty fast. When
> you are testing, are you not seeing your tags? I know there was a post
> about this once before and it was working as designed. I've left this open
> for one of our core developers to see it as I wanted their feedback in it
> as well. This is why I didn't close it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1252#issuecomment-201271289>
>



-- 
Thanks & Regards
Pankaj Garg
M.+91-9728598858

**Comment by neil96** [comment]
This is how we designed, this block will cache in 180 mintues (you can change this time).

**Comment by SalmanKhan86** [comment]
i have changed it to 5 Minutes but still this box is not Auto Refresh...
Any Working solution for this,
