### ISSUE TITLE
SMS Service Not working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1253]
In India All these three sms services not works here due to some regulations-and-restrictions.how can we use this service.below are links for detailed info.
https://www.twilio.com/help/faq/sms/are-there-limitations-on-sending-sms-messages-to-indian-mobile-devices
https://www.nexmo.com/india/
https://www.clickatell.com/faqs/2015/10/12/india-sms-messaging-regulations-and-restrictions/

**Comment by Data66PF** [comment]
If you cannot use them there, you will need to have a developer extend the function to add one that you can use. As we cannot control external connections as to what they allow and don't allow, we cannot fix this issue. You would need to get a developer to make you one for your area.

**Comment by Ylmzef** [comment]
Twilio doesn't working for me too.
Clickatell working fine.

**Comment by SalmanKhan86** [comment]
can we use any other SMS Service
