### ISSUE TITLE
Unable to upload regular photo on profile page - not talking about profile or cover image.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1254]
This is on the phpfox demo site.

So once you become a member you can go to your profile page and there is no button to upload a photo.  Now if you hover your cursor over the profile image...yes you can upload a profile image.  But even after you do that you still cannot upload a regular picture to either alone or in an album.
Even if you upload a cover image which you can do...you still can't upload a regular image.

The only way to upload a regular image to your profile page is to go to the public photo module/menu and upload a image there and then when you go back to your profile page you will see a link to upload regular images.

![upload-photo](https://cloud.githubusercontent.com/assets/14913734/14051011/cd51e58e-f28d-11e5-814b-c9915ca750b3.jpg)

![upload-photob](https://cloud.githubusercontent.com/assets/14913734/14051015/dbaa045e-f28d-11e5-9660-ca6b469f33d4.jpg)

**Comment by neil96** [comment]
This is how we desgined. The photo menu only show if that user uploaded at least 1 photo (not cover or profile photo).

**Comment by PhpFoxJohnJr** [comment]
I am sorry Neil and please don't take offense but that is the just dumb.  So we must try to explain to our users that they need to go to the what they think is a public photo area and post a photo there before they can come back to their private area...their profile page to post a picture.  I know it easy to say that is how it is designed...but I have been in the computer industry for over 20 years and in the beginning coded from Visual Basic 4-6, VBA as well as Java so I will understand...so please explain why phpfox would set it up this way.

**Comment by PhpFoxJohnJr** [comment]
Also, on the same subject you may have save a few lines of code but having the photo menu and the blog menu connect with PAGES photo menu and blog menu was another error in judgment.  Now we are unable to restrict users from the main photo area or blog area where we may wanted to post ourselves without affect their PAGES areas as well.  It all or nothing so saving time reusing code something takes away feature that would improve your product.

**Comment by Vivian-phpFox** [comment]
User profile page integrate many modules from phpfox and third party, so there are more menus will be shown if do not restrict. We'll consider your opinion. Thanks for your posting.

**Comment by PhpFoxJohnJr** [comment]
Please remember I am only trying to help...I am old and too tired to keep relearning new technologies.  But remember the theory will never change.  I understand reusing code and it is what your suppose to do.  But, you can add additional functions (like in the photo and blog menu area) to be able to restrict or allow members to use certain areas.  To say this group can create blogs in all areas or post pictures in all areas or not in all areas defeats the purpose of reusing code.  As well as telling someone they need to go to the backdoor of your house the first time to be able to use the front door to me is confusing (in regards to the original problem).  Good night...and though I may be a pain...you have a great product and I am not going to hold back until you have a perfect product so you can sell a ton of software and become rich...isn't that what you want :)

**Comment by DuCarlion** [comment]
i do some crazy sh*t when i hit the drugs too hard too
turns out making designs on drugs only work for others on drugs
can you fox dudes introduce me to your dealer??
this would have taken some heavy stuff to get those wacked out ideas cooking.

seriously though JohnJr is right
its not how stuff be done and is kinda detrimental to try be different from the standard in this matter other plugins menus or not becoming involved
near any social script you can swing your d**k at has the option for users to upload via their profiles
explaining they cant a million and one times on this system is going to become mighty mighty annoying and result in a lot more drugs being needed
or was that the real design?

Feed it to em @JohnJnr and get us the good stuff
p.s fox dudes i was serious about meeting your dealer
mine ran out and its hell living live seeing everything from a normal perspective cough up the good stuff!!!
im just screwin with yous so dont like go having a hernia or anything
JohnJnr be right though

**Comment by PhpFoxJohnJr** [comment]
Unless there is another way that I am missing then I know I am right.  I have been in the computer industry for at least 30 years and my daughter just won first place in our entire state for Future Business Leaders of America (250,000 members strong) for Web Design and now is going to Nationals to Compete against the 50 states.

**Comment by Data66PF** [comment]
As this is working as designed, please file a feature request for us to consider the process.

Please read our terms before posting any bugs, feature request or comments as we've updated them and will start removing or editing as mentioned in the readme for each section - bugs or features.
