### ISSUE TITLE
[v4.3.0b5] Theme Manager Issue

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1255]
CSS and JS cannot be edited in theme that I cloned (Bootstrap), because the Theme Manager doesn't load the "text area".

- Clean installation
- v4.3.0b5

![Screenshot](https://community.phpfox.com/file/attachment/2016/03/eb990bef2a0fe1f15d6d3ba2ffa67a85.png)

#1087

**Comment by neil96** [comment]
I can't reproduce this issue. Could you give me more information?

**Comment by Spaninet** [comment]
1) In a clean site create a Theme (clone of bootstrap).

2) First set the theme you cloned as default, then go to Bootstrap theme and set it as default.

3) Finally, Edit cloned theme and click in CSS or JS "tabs". You will see no that the editor is not loading, and you cannot add or edit default code.

**Comment by neil96** [comment]
Tested again with your step you gave, I still can't reproduce.

**Comment by Data66PF** [comment]
Installed a fresh dev site. Did all of the steps on v4.3.0 build 5. I cannot reproduce the issue either.
