### ISSUE TITLE
V4 Short Url + NGINX issue

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1257]
Hi Good Day,

I successfully enable my short URL and everything is OK except 2 issue.

1. Welcome page - when I click login or register the loading is take a very longtime and did not show up. I need to click the Logo before it's working.

2. I can open or use all AdminCP menu except this:
<img src="http://s13.postimg.org/h5mjvs7hj/short_url.jpg"/>

I think we need to know exactly what Phpfox /etc/nginx/conf.d/default.cof and /etc/nginx/nginx.cof setup to follow correctly the all upgrade release with one setup server.

Thank You so much

**Comment by juniortimeline** [comment]
Please Up this Issue because this is very important to all Phpfox user's handle own dedicated server. Thank You!

**Comment by neil96** [comment]
Already fixed on 4.3.1.

**Comment by juniortimeline** [comment]
Thank You Mr. Raymond to give sometime for this issue  and I'm glad it is work now.

**Comment by rjdjohnston** [comment]
What's the recommended contents for nginx configuration?

**Comment by neil96** [comment]
@rjdjohnston Please try this configuration.
Install on your root domain/ Example http://your_domain.com/

```
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;


        root /usr/share/nginx/html;
        index index.php index.html index.htm;


        # Make site accessible from http://localhost/
        server_name your_domain.com;
        location ~ ^/index.php/.*$ {
                        try_files $uri $uri/ /index.php?$args;
        }


        location / {
                rewrite ^/file/(.*) /PF.Base/file/$1 last;
                rewrite ^/static/ajax.php /index.php last;
                rewrite ^/themes/default/(.*) /PF.Base/theme/default/$1 last;
                rewrite ^/(static|theme|module)/(.*) /PF.Base/$1/$2 last;
                rewrite ^/(Apps|themes)/(.*) /PF.Site/$1/$2 last;
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

Install on a path of your domain. Example http://your_domain.com/your_path/ 

```
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;


        root /usr/share/nginx/html;
        index index.php index.html index.htm;


        # Make site accessible from http://localhost/
        server_name your_domain.com;
        location ~ ^/your_path/index.php/.*$ {
                        try_files $uri $uri/ /your_path/index.php?$args;
        }


        location /your_path/ {
                rewrite ^/your_path/file/(.*) /your_path/PF.Base/file/$1 last;
                rewrite ^/your_path/static/ajax.php /your_path/index.php last;
                rewrite ^/your_path/themes/default/(.*) /your_path/PF.Base/theme/default/$1 last;
                rewrite ^/your_path/(static|theme|module)/(.*) /your_path/PF.Base/$1/$2 last;
                rewrite ^/your_path/(Apps|themes)/(.*) /your_path/PF.Site/$1/$2 last;
                try_files $uri $uri/ /your_path/index.php?$query_string;
        }


        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules
        }


        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
}
```

These config just reference purposes only. Base on your OS, OS version, nginx version, other application on your server. These configurations might change.

**Comment by rjdjohnston** [comment]
Couldn't even get the login page to load with this configuration.

Reverted back so at least I could get the login page to load. Once you hit submit the URL goes from: www.mysite.com/user/login to www.mysite.com/index.php/user/login

Does that explain anything?

**Comment by neil96** [comment]
Did you enable short-url?

**Comment by rjdjohnston** [comment]
It was enabled before the upgrade to 4.x. I assumed it would stay enabled.

**Comment by neil96** [comment]
Please double check your short-url setting again. It might have been reverted when you moved your server

**Comment by rjdjohnston** [comment]
Do you know where it's set in the database? I can't login to the site. :(

**Comment by rjdjohnston** [comment]
Where is the server.sett.php supposed to be located in v4?

I have one in /PF.Base/file/settings/ and this one I didn't edit. /PF.Base/include/setting/server.sett.php.new

**Comment by neil96** [comment]
With these questions, please ask on our [community](https://community.phpfox.com/forum/). Here only for bug tracker.
