### ISSUE TITLE
Under Mobile view when looking at pages claim, join, unjoin too close.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1259]
V4.3 - On my Samsung galaxy 4 it looks very odd.  When you hold it regular view the claim, join and unjoin bottom sit right below the category description with only maybe a one pixel separating them.  Looks very awkward.  Now if I turn my phone sideway or wide screen then the category text sits behind the buttons.

Here is an image off a website that show mobile version...I used the phpfox demo site.

![mobile-buttons](https://cloud.githubusercontent.com/assets/14913734/14061186/04a84b44-f348-11e5-8d85-4154418b2f2c.jpg)

Simple fix would be just move up the image, name and category up 5-10 pixels.

**Comment by Data66PF** [comment]
Where are they in your image?

**Comment by PhpFoxJohnJr** [comment]
Since mine is a private group PAGE...I have multiple green buttons like page claim and join button.  So the image above add another green button so it almost touches the text.  Looking at my Samsung galaxy 5 though  (I said 4 before..oops) the buttons do cut off the bottom of the text..

**Comment by neil96** [comment]
@PhpFoxJohnJr Could you give us more informatoin to reproduce this issue?

**Comment by PhpFoxJohnJr** [comment]
I can't create it on the phpfox site since I don't think you have a Pages Category for Groups so you can join the page.  But when I just went on you demo site and went to my ABC Book Store page on a mobile device you will see the unlike button and the top of the unlike button almost cuts of the bottom of the text.  You see this in the above image where you see "2 followers".  Now the above image is ok since there is only one button "unlike" but sometimes you can have two buttons in a row...unlike and claim button which then cuts the bottom of the text.  You need to add some top padding on the button or bottom padding on the text.  Remember this is for the mobile version when you hold your phone straight up (which most people do) compared to the side for a wider look.  It should be the easy fix for you :)  I have seen your work before :)

**Comment by Data66PF** [comment]
Please test once we release RC version.
