### ISSUE TITLE
Trouble installing Apps

### ISSUE THREAD

**Issue by ojaiweber** [moxi9/phpfox#126]
I've signed up for Github at the request of phpfox. I'm going to try and keep this short and sweet and hope someone can help me:

Issue: Try to install an app on my v4 site I get a 403 Forbidden Error. All apps get this.

Setup: I have a subdomain with the phpfox installed. I have a wildcard ssl on both my core site and the subdomain.  I did "enable shorturls" prior to the ssl on the subdomain. I've enabled the options to force users to log into https and I've secured pages with https in the options.

Any help? Are there particular folders/files in the cpanel file manager I should set specific permissions to?

**Comment by Data66PF** [comment]
What are the server logs showing?

**Comment by ojaiweber** [comment]
I know I'm a bit over my head...but where can I find that?  Im in the cpanel now and don't see anything under "error logs"

**Comment by ojaiweber** [comment]
So if I go to "find more apps" then to "get app" before I get the 403 forbidden error I briefly see fields that look like they may be requesting my phpfox licencse key information. Doing it this way also basically "iframes" the 403 error keeping the admincp menus to the left.  If I just try to add the app from the featured app area it 403's full screen.

**Comment by Data66PF** [comment]
Ray is going to need to help you further with this as my sites don't have issues but my sites on V4 are not live sites and not on https.

**Comment by ojaiweber** [comment]
No problem, thanks for trying. I'm trying to find the logs in phpmyadmin so far no dice.  Thank you for trying, I look forward to getting some insights from Ray! He sounds helpful.

**Comment by Data66PF** [comment]
If you disable https settings, does it work?

**Comment by ojaiweber** [comment]
So far nope.

**Comment by GloriousKoch** [comment]
Not sure if this is related, but when I try to install apps I got an error related to "ModSecurity" being on. I went to cpanel, and searched "ModSecurity" and hit a button to disable it. Doing so I was able to reload the apps page and install/view what I needed. After I was done, I renabled it in cpanel, because it sounds like it's important to have on, and I have no idea what having it off could cause. :P

**Comment by ojaiweber** [comment]
I don't have that option, but thank you for the input!

**Comment by Jinkers** [comment]
If you could post some more details (picture maybe of the error?) we should be able to help you some more. As GloriousKoch stated before we had to disable ModSecurity briefly to get ours to work.

**Comment by GloriousKoch** [comment]
I probably should have been more clear as well, just to be sure, @ojaiweber. Did you look for "ModSecurity" in your host's cpanel? Just so you didn't think I meant PHPFox's admin. Also, you may have, but just in case, use the search feature in your host's cpanel as well. There are sometimes options I have that don't show up on the dashboard unless I search for them. :)

**Comment by ojaiweber** [comment]
Thanks folks! I've attached two error screen captures.  The first "error 1" is when I click to get the app from the store part.  Error 2 is the screen cap when I try to install straight from the featured app area.

@GloriousKoch I cannot find that even when I search. I'll continue to try and hound it down since it sounds like that's my best option. Obviously from the screen caps you can tell I have hostgator.

Much thanks again. I really do appreciate it.

**Comment by GloriousKoch** [comment]
I'm not sure if its a permissions thing on github, but I can not see your attached images.

**Comment by ojaiweber** [comment]
Or user error...on my part. Sorry

<img width="1057" alt="app error 1" src="https://cloud.githubusercontent.com/assets/13368303/8739357/634fc380-2c00-11e5-8e05-b0fd0767fab2.PNG">


<img width="821" alt="app error 2" src="https://cloud.githubusercontent.com/assets/13368303/8739352/5237061c-2c00-11e5-9176-c11563fd1f7a.PNG">

**Comment by GloriousKoch** [comment]
Yeah, I use a different host, but that's more or less what I saw on my end. I'd contact HG's support (if I recall from the past they have quick/helpful live chat staff) and ask them where you could find modsecurity settings.

**Comment by ojaiweber** [comment]
SOLVED rule 123434 whitelisted. thank you all for the help!

**Comment by GloriousKoch** [comment]
Was that the solution or was it another thing? Just curious for others who may have similar issues. :)

**Comment by ojaiweber** [comment]
Well so I inquired for modrewrite disabling like you said and the help folks then had me trigger the error while "tailing apache" and then they found the rule error. Then they whitelisted that error.  They said it was safe to keep it whitelisted.

That's all I know and that's way over my head.

**Comment by Data66PF** [comment]
For anyone else having issues, I'm about to go disable some "apps" that are actually modules and this is breaking sites. Anyone that installed any of the V4 "apps" from Cespiritual, those are NOT apps and will break your site. I'm going to see how to fix this other site and post for the rest of you if you need it.

**Comment by Data66PF** [comment]
Actually, if you get the latest client build or developer build, you should see an error before trying to install any "apps" that are actually not apps. Try updating.

**Comment by Data66PF** [comment]
Is this still an issue?

**Comment by RaymondBenc** [comment]
When installing apps we provide a very long query parameter in the URL and some hosts with security features will consider this a risk. The URL simply contains a link to download the product, which is very long because it has a time delayed authentication token. We are going to change this instead to a short token that will instead ping our app server for the download URL, however we cannot change this with the next version iteration as it will require a little more testing.
