### ISSUE TITLE
Default style class fethcing wrong file

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#1260]
we trying to use getCurrentLogo($iId) and it throws exception

![style_error](https://cloud.githubusercontent.com/assets/13350517/14061348/45032bf6-f34c-11e5-8953-67c1d66fcbe9.JPG)
@

[](url)	Default style class	\PF.Base\module\theme\include\service\style\style.class.php
trys to fetch the file from 

PF.Base\theme\frontend\default\style\default\image\layout

where as the file is stored in PF.Site\flavors\bootstrap\assets\logos

is there support to to fetch files from bootstrap theme

**Comment by robert9592** [comment]
With new theme system on phpFox v4, we haven't used the function "getCurrentLogo($iId)" anymore. In stead of, you can get logo link of current theme via call this "flavor()->active->logo_url();".
We will also remove unused functions in next versions.
