### ISSUE TITLE
Share Problem on profile feed

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1261]
This screen shot is from PhpFox demo site and the same issue of my website. I'm using Google Chrome Desktop and mobile browser.
<img src="https://v4.phpfox.com/file/pic/photo/2016/03/a5c7153ee8b5053fba9be08ac96c73c3_1024.jpg"/>

**Comment by Data66PF** [comment]
Please provide more details when posting. What exact steps did you do? What device, browser, os? We always need details when you post bugs. Thanks.

**Comment by juniortimeline** [comment]
This screen shot is from PhpFox demo site and I'm using Google Chrome Desktop and mobile browser.

**Comment by Data66PF** [comment]
What steps did you do to produce it please?

**Comment by juniortimeline** [comment]
Just Share any post.

**Comment by neil96** [comment]
This issue already fixed in 4.3.1.

**Comment by GreenMan123** [comment]
There no way to cancel the share box
