### ISSUE TITLE
Responsive Problem Bootstrap Theme

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1263]
This screen shot is from PhpFox demo site and I'm using Google Chrome Desktop and mobile browser.

<img src="https://v4.phpfox.com/file/pic/photo/2016/03/3d4d22eebfbedd02d235bdf78e3c0f88_1024.png"/>

**Comment by Data66PF** [comment]
Is this at the https://v4.phpfox.com demo?

**Comment by Data66PF** [comment]
Please provide details when posting. Thanks.

**Comment by juniortimeline** [comment]
This screen shot is from PhpFox demo site and I'm using Google Chrome Desktop and mobile browser.

**Comment by lordofnos** [comment]
same at my site
