### ISSUE TITLE
Video Self Host

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1264]
Hi Good Day, It is cancel self hosting video on V4? I do have big amount of storage on my dedicated server and I don't want to use any third party storage to run my video files on my site.

Have another way to input my own mencoder and ffmpeg setting on my phpfox site? Thank You.

**Comment by Data66PF** [comment]
This is not for feature requests. Please post this sort of feature request at the community as we will not be bringing back the mencoder and ffmpeg via any core app.
