### ISSUE TITLE
comment cutoff in feed

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1267]
comment cutoff in feed does not work on stage.phpfox and my site. i mean it shows the cutoff after several comments but not with the number inserted in module settings... maybe the setting does not exist anymore?

**Comment by Data66PF** [comment]
Can you please give more info? I'm not clear which setting and what doesn't work as you provided no screenshots. "not with the number inserted in module settings" is what has me confused.

**Comment by lordofnos** [comment]
in feed settings: "Comment Cutoff on Feeds", "Define the cutoff for comments in each feed.".

it has no effect to put a number in...

**Comment by robert9592** [comment]
The setting "Comment Cutoff on Feeds" isn't used anymore, so in v4.4.0 we will removed it. In stead of, admin can use the setting "Total Comments in Activity Feed" in Comment settings (we also bring back Comment settings section in v4.4.0)

**Comment by lordofnos** [comment]
could you please tell me what the difference is between "comment cutoff" and "total comments"?
