### ISSUE TITLE
combine feeds when uploading multiple photos

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1268]
this feature was announced in the blog for 4.3.0 but does not work for me

**Comment by lordofnos** [comment]
ok, i have to try out if this only works when multiple photos are uploaded alle together. comming from v3 i wanted the feature back that same posts are combined even if the photos are uploaded one by one. maybe this is more a feature request and the combining works like designed? i have test again...

**Comment by Data66PF** [comment]
This is only for multiple photos uploaded at once. It is not for photos uploaded individually. Feature requests need to be put in the feature request tracker.
