### ISSUE TITLE
Difficult to see "claim" text against left green button background in pages

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1271]
Difficult to see "claim" text against left green button background in pages.

Is this button necessary given there is already a claim button on the upper right?

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14072741/2fa253c2-f491-11e5-8bcf-752ef3f952ed.png)

**Comment by Data66PF** [comment]
That block appears to not be enabled by default. I'll mark this a bug because we do have it in the block list. I notice we also seem to be missing the Report for pages but that would need to be a different issue report.

**Comment by PhpFoxJohnJr** [comment]
Sure...I see how rank here :)

https://github.com/moxi9/phpfox-feature-requests/issues/5

Title - "Extra Claim Button"

"By the way where is the report button...did we ever have a report button on pages?"

"With the new bootstrap theme looks like now the green claim button on the bottom left has now grey text so it is hard to see. "
