### ISSUE TITLE
Name of the Photos uploaded by the Users

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1272]
If any user uploaded a image, he must be having an option to put a significant name to the image, that will add a great value to the photos uploaded by the users.
![photo name](https://cloud.githubusercontent.com/assets/13433124/14076731/2bfff7f8-f502-11e5-92a0-5fbfe901fb9c.png)

**Comment by Data66PF** [comment]
This is working as designed as the user can edit the photo after they upload it. However, please feel free to add a comment to the feature request https://github.com/moxi9/phpfox-feature-requests/issues/91

**Comment by Data66PF** [comment]
Please don't test at the community forum. It is using different settings, different version, etc.
