### ISSUE TITLE
.htaccess missing / rewrite rule not found

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1276]
I have mod rewrite enable, but get the following.

"The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite."

Looking at the above. I'm assuming the .htaccess is supposed to be in the root of public_html... or is this supposed to be in the pf base folder?

**Comment by Data66PF** [comment]
Please ask questions at the forum. This is server related.
