### ISSUE TITLE
video app comments

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1277]
when commenting on videos the video goes not up in feed like other entrys do.

**Comment by Vivian-phpFox** [comment]
Can you reproduce on demo site?

**Comment by lordofnos** [comment]
oha, this was in my spam folder... i can reproduce it on stage.phpfox.com. just comment on a video and look for it in the main feed. it does not come to the top.

**Comment by neil96** [comment]
Thanks, now I can reproduce.
