### ISSUE TITLE
[Profile Pics] Pictures Overlap

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#128]
1. Person uploads a Profile picture.

2. Person uploads a new Profile picture.

3. When you go to their Profile picture page by clicking it...it shows the old one (guessing this is intentional, to save all old profile pics)...but it overlaps the current one.

![image](https://cloud.githubusercontent.com/assets/6254165/8739185/9fe6577c-2c06-11e5-86e9-c61a2c352de5.png)

**Comment by Data66PF** [comment]
confirmed

**Comment by RaymondBenc** [comment]
I ran in this problem a few days ago locally and fixed it then so this should be resolved with our next release, 4.0.4. If not, just open up a new case.

Thanks!
