### ISSUE TITLE
Issue with many friends profile

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1280]
I have a user on my site with -+1K friends on profile.
When the user try to login into site it can't loading after more 1K friends.

**Comment by Data66PF** [comment]
https://v4.phpfox.com/Data66/

cannot reproduce any issue. I have 1700+ friends and see no issues logging in, surfing the site, viewing my friends.

**Comment by Ylmzef** [comment]
It's not fresh installed site as v4.phpfox.com it's upgraded site.

**Comment by Ylmzef** [comment]
Also mostly friends on your profile without any data.
They are created for testing the site.
But on mine all friends active.

**Comment by Data66PF** [comment]
No, the users on my profile are real. We don't have created users other than about 10 staff. The rest can be spam or people testing.

**Comment by Data66PF** [comment]
Please send a ticket to support https://clients.phpfox.com if you are using most current version with no source edits.
