### ISSUE TITLE
Issue with E-gifts page (maybe other pages too) 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1282]
Hello :) 

I Just found out that there's a problem with the E-gifts page, I havent checked other pages, but a quick scan through , they seem to be alright, 

I'm on 4.3 build 5 and on neutron 

the writing is not there

![image](https://cloud.githubusercontent.com/assets/16384395/14155987/131d9c20-f6bc-11e5-9e83-12eb58d2154c.png)

**Comment by Data66PF** [comment]
Please make sure you fully upgraded and followed all of the steps in the upgrade tutorial as it looks like you are missing phrases.

**Comment by Data66PF** [comment]
With debug enabled, I can confirm we have an issue.
Exception thrown with message "Undefined index: aLanguages"

Stacktrace:
#13 Exception in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/start.php:335
#12 Whoops\Exception\ErrorException in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/file/cache/template/egift_template_default_controller_admincp_categories.html.php_admincp.php:19
#11 Whoops\Run:handleError in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/file/cache/template/egift_template_default_controller_admincp_categories.html.php_admincp.php:19
#10 require in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:3309
#9 Phpfox_Template:_requireFile in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:3295
#8 Phpfox_Template:_getFromCache in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:2578
#7 Phpfox_Template:getTemplate in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/module/module.class.php:592
#6 Phpfox_Module:getControllerTemplate in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/file/cache/template/adminpanel_default_template_template.html.php_admincp.php:132
#5 require in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:3309
#4 Phpfox_Template:_requireFile in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:3295
#3 Phpfox_Template:_getFromCache in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/template/template.class.php:2297
#2 Phpfox_Template:getLayout in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1490
#1 Phpfox:run in /home/mysite/web/mysite.com/public_html/subfolder/PF.Base/start.php:289
#0 require in /home/mysite/web/mysite.com/public_html/subfolder/index.php:9

**Comment by Lukey199223** [comment]
Thank you for confirming it as a bug :)

**Comment by RaymondBenc** [comment]
@Data66PF Can you reproduce this in our latest git build? I can't seem to reproduce this issue locally ATM.

**Comment by Lukey199223** [comment]
Its working on my site Now @RaymondBenc :) ,
