### ISSUE TITLE
Uploading music and music file limit

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1287]
Hello :) 

I've been testing for a couple of days

and the speed of uploading a song needs to be fixed, I'm uploading a 3 minute song and its taken about 15 minutes and its still uploading, And if I set the file limit of a song upload to more than 10mb (most songs I listen to are more than 10mb) And its setting it back to 10, 

for example, I edited the file limit to 100mb the other day and it jumped back to 10mb, I Want to turn the file limit off completely or put 0 in for unlimited like other options, 

I've been testing both these for a few days , I've disabled apps to see if thats interfering with the upload and i've taken all of my code out to see and its the same

**Comment by Data66PF** [comment]
This is controlled by your server settings, by your ISP upload speeds, etc.

**Comment by Data66PF** [comment]
Before I mark this not a bug, when you say it jumps back to the lower setting, do you mean in the user group setting that when you set the music upload, in that setting it is not saving, OR, do you mean that front end it doesn't show? If you mean only front end, that is a server setting and you should close this bug report as it is not a bug.

**Comment by Lukey199223** [comment]
Ye I mean in the user setting, I'm setting it to more than 10mb and its jumping back to 10 *_* ,
