### ISSUE TITLE
Uploaded Events banner image is not resized to correctly fit events index

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1289]
In the events main index page: http://www.site.com/index.php/event

The uploaded banner image is not correctly resized to show the full image.

**Comment by Data66PF** [comment]
Please test at our demo https://v4.phpfox.com as I don't see an issue.

**Comment by Data66PF** [comment]
Also, please see our posted instructions for posting bugs and please do include everything asked for.

**Comment by darksolar1** [comment]
This is what it should look like: 
![screenshot](https://cloud.githubusercontent.com/assets/17013208/14994320/409f450e-113d-11e6-8800-a8ecb91224f3.png)



This is what it actually look like: 
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14994324/4588d86e-113d-11e6-9cd3-ca9ca1745f10.png)

**Comment by neil96** [comment]
It's woking as designed.
