### ISSUE TITLE
Php Block 4.3.0 build 5

### ISSUE THREAD

**Issue by darkname** [moxi9/phpfox#1290]
admincp->Blocs->

when I create a blog with PHP Code: `<?php echo "hi"; ?>`

It does not display anything while this works in phpfox v3

**Comment by optiroot** [comment]
Is this bug strictly related to `echo` or for php code in general?

**Comment by darkname** [comment]
I think, it's general because if i write:
```
<?php
$test = true;
if($test){
?>1<?php
}
else{
?>2<?php
}
?>
```

it will display: 12
instead of: 1

**Comment by optiroot** [comment]
Yes, so it is general because otherwise there is something in core that locks some php functions, but limiting `echo` too could be strange as it is really safe as function.

So it is for php code in general.

**Comment by optiroot** [comment]
For core devs: this bug is present in 4.3.0b4 too, not only in b5.
