### ISSUE TITLE
Users can't see messages [4.3.0b4]

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#1291]
Hello,

So much of my users can't see messages clicking the icon, it is just blank. Any third-party plugin is causing the problem, as it seems.
So I don't undestand what's happening.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12573563/14244900/1bb1020a-fa5e-11e5-9fcc-52e9cae2e77b.png)

Thank you.

**Comment by Data66PF** [comment]
When you removed cometchat, did you ensure to restore the theme to remove the cometchat code? Did you check with debug enabled?

**Comment by Data66PF** [comment]
Please test at our demo https://v4.phpfox.com as I cannot reproduce this.

**Comment by optiroot** [comment]
Yes, I restored theme, removed CometChat code, cleared cache, when I tried.

I've try now too just to answer you and the problem doesn't change.

So it isn't from any of my plugins, I don't what's happening.

**Comment by Data66PF** [comment]
Please test at our demo as I asked. This is to rule out browser issues, etc.

**Comment by optiroot** [comment]
I cannot check in demo as in demo you use the IM chat app. Instead I have default messages.

**Comment by optiroot** [comment]
I tested some things and the problem is JS/HTML related because the data-url that the click opens works.
The `data-url` attribute for messages button is https://website.com/mail/panel/ and going in that link manually works.
So it seems that just the messages container doesn't get populated by data-url for some reasons.

**Comment by Data66PF** [comment]
I use default message on my site and still cannot reproduce this on any test sites.

**Comment by Data66PF** [comment]
tested again in 4.3.2 new release and still can't reproduce this

**Comment by optiroot** [comment]
As said the bug is difficult to reproduce, because this happens rarely on different accounts. I can't tell you  what causes this. My apps are not causing the problem as I tried even disabling them all.

What could I do about this? Any core dev could come to check? At least I and you understand the problem. It is really strange.

**Comment by Data66PF** [comment]
Please send a ticket to our support https://clients.phpfox.com .
