### ISSUE TITLE
Creates a play video box on some links when there's no video

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1292]
On some links, phpfox creates a video play when there isn't any video. 
https://news.bitcoin.com/panama-papers-bitcoin-stop-corruption/

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14246509/9fbd5f36-fa35-11e5-8c0d-a1b65eb9b189.png)

**Comment by Data66PF** [comment]
confirmed at PF demo using the link provided

**Comment by neil96** [comment]
I can't reproduce this issue.

**Comment by lueung** [comment]
Seems to be fixed in v4.3.1-b3
