### ISSUE TITLE
When uploading multiple images on pages, only one shows on the activity stream

### ISSUE THREAD

**Issue by wrsantiago** [moxi9/phpfox#1293]
If you create a page on the (pages modules) and later you try to upload multiple photos at the same time (batch upload) only one photo appeared on the activity stream on the page wall or the sites wall.

Core Version:
4.3.0(build 5) 

I remember uploading images on a previous version and all the photos appeared on the activity stream (pages wall and sites wall)
  
Thanks

**Comment by one44** [comment]
They now show like facebook
