### ISSUE TITLE
V4.3.1.b3 Hangs indefinitely when trying to delete theme "Home" banner images from admincp

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1294]
If you  try to delete theme "Home" banner images from admincp it hangs indefinitely.
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14268386/54fbf0ac-faa8-11e5-9f06-fba51ab7008e.png)

**Comment by neil96** [comment]
Could you give us more information?

**Comment by lueung** [comment]
Steps to reproduce:  Theme --> bootstrap --> home --> select an image to delete

It will not delete and hangs continuously  (spins forever)

**Comment by neil96** [comment]
I still can't reproduce.

**Comment by lueung** [comment]
environment: CentOS 7.2.1511, php 5.4.16, apache 2.4.6, mysql 5.5.44, FCGId mode
latest firefox & chrome

**Comment by neil96** [comment]
I can reproduce this issue when turn debug mode on.
