### ISSUE TITLE
after update to v.4.3.1-b3 I see this in modified file "1 file(s) failed."

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1297]
after update to v.4.3.1-b3 I see this in modified file "1 file(s) failed."

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14279967/eb54f076-fafd-11e5-9553-c36b16d2e855.png)

**Comment by Data66PF** [comment]
Cannot reproduce on my dev. Are you sure you never edited the default theme?

**Comment by lueung** [comment]
Positive

**Comment by Data66PF** [comment]
You should always make a theme based on the default and use that instead of default as the default shouldn't be changed since it requires revert and rebuild core when upgrading. Please try making your own theme based on the bootstrap and then reverting  and also rebuilding the bootstrap core.

**Comment by lueung** [comment]
What I did was upload the logo, fav icon and images so it wouldn't show my logo instead the phpfox logo every time. Then I'd simply just clone it into a new theme since there wasn't any code changes. I guess it is technically changed since it now include images, but I see what you mean. It might be a good idea to include instructions specifically not to upload any images into the bootstrap theme just for clarification. This way there is no confusion.

I will have to wait since I can't delete the images, due to this issue: https://github.com/moxi9/phpfox/issues/1294
