### ISSUE TITLE
Title overflow...

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1298]
on the small screen carries the title

![hsb2gq](https://cloud.githubusercontent.com/assets/8930862/14281650/145287b4-fb43-11e5-9f6a-d9fd3f7365bc.gif)

Version: 4.3.1

**Comment by Vivian-phpFox** [comment]
The lowest screen resolution for mobile and tablet, especially width is 320px

**Comment by Data66PF** [comment]
Please file a feature request in our feature tracker if you would like this changed. Thank you.
