### ISSUE TITLE
Admin search issue

### ISSUE THREAD

**Issue by Foxgerman** [moxi9/phpfox#1299]
There was an issue within admincp. To reproduce: Go to Tools->Settings and do a search for infodb. You should see an entry. Click on this and you get a redirect to admincp.

As i know this special setting was gone in v4, but still available in core language pack.

Here is a short screencast: http://foxgerman.com/admincp_issue.mp4

**Comment by jrann** [comment]
This also happens with the google api for check in page just refreshes.

**Comment by Karlos1xx** [comment]
solved?
