### ISSUE TITLE
HTML codes in news feed

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#130]
I have upgraded from v3 to v4 after upgrade i see html codes in news feed.

**Comment by Data66PF** [comment]
Make sure you are not using third party products from v3 in v4 as they need to be updated.

**Comment by RaymondBenc** [comment]
HTML is no longer permitted by default and requires an app to allow HTML on PF communities.

We will release a free app for this in a few days.

**Comment by Ylmzef** [comment]
I dont add it, i have upgraded from v3 to v4 also i had disabled in v3 too.

**Comment by Ylmzef** [comment]
I have upgraded to v4.0.3 but still the issue why you close my ticket?
