### ISSUE TITLE
Phrase issue in video app

### ISSUE THREAD

**Issue by Foxgerman** [moxi9/phpfox#1305]
There is a wrong formatting in video app: user commented on your video (shown in notifications)
The User is not shown as variable in phrase manager, there is a new entry with real username. 

Screenshots:

![bildschirmfoto 2016-04-06 um 12 45 56](https://cloud.githubusercontent.com/assets/5095754/14314170/0b50f8cc-fbf6-11e5-979b-1536e54446f7.png)

<img width="431" alt="bildschirmfoto 2016-04-06 um 12 51 58" src="https://cloud.githubusercontent.com/assets/5095754/14314185/18ce9860-fbf6-11e5-92cd-6d2a2036bab4.png">

**Comment by neil96** [comment]
Duplicate with #1274
