### ISSUE TITLE
 Privacy issue on posting to profile 

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1309]
This is the same issue as [Privacy issue on posting to profile  #1168](https://github.com/moxi9/phpfox/issues/1168).  It is repeated here because it was not fixed.  I just repeated the bug with v4.3.1(2).
I believe that the issue is with the feed template default block display.html.php file.  Older versions had conditional code to hide the form if privacy settings prevented profile postings.
`	{if Phpfox::isUser() && !PHPFOX_IS_AJAX && $sCustomViewType === null}
		{if (Phpfox::getUserBy('profile_page_id') > 0 && defined('PHPFOX_IS_USER_PROFILE')) 
			|| (isset($aFeedCallback.disable_share) && $aFeedCallback.disable_share) 
			|| (defined('PHPFOX_IS_USER_PROFILE') && !Phpfox::getService('user.privacy')->hasAccess('' . $aUser.user_id . '', 'feed.share_on_wall'))
			|| (defined('PHPFOX_IS_USER_PROFILE') && !Phpfox::getUserParam('profile.can_post_comment_on_profile') && $aUser.user_id != Phpfox::getUserId())
		}

		{else}
			{if !Phpfox::getService('profile')->timeline()}
				<div id="js_main_feed_holder">
					{template file='feed.block.form'}
				</div>
			{/if}
		{/if}
`

But the current version has no such restrictions:

`	{if Phpfox::isUser() && !PHPFOX_IS_AJAX && $sCustomViewType === null && $bUseFeedForm}
		<div id="js_main_feed_holder">
			{template file='feed.block.form'}
		</div>
`
Since posts can be made to profiles against their privacy settings it seems that there is no submission filtering either.  I believe that both are required.

**Comment by Data66PF** [comment]
@neil96 please test this.
