### ISSUE TITLE
Posting to profile causes Fatal error in AJAX

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1310]
After upgrading to V4.3.1(2) I started getting errors when posting to profile status.  The error was "end of file encountered:.

I found the problem in file feed template default block entry.html.php 
It requires an additional `{/if}`.  I beleive that it goes after this:
`row_feed_loop js_parent_feed_entry` on line 14.
update, I think the bootstrap entry file may have the correct coding.

**Comment by Data66PF** [comment]
@neil96 please test this.

**Comment by neil96** [comment]
Same issue with ticket 463.
