### ISSUE TITLE
Banner Image for homepage

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1312]
I do not see this as an issue on github but as of last upgrade banner for homepage does not load and leaves homepage blank.

![2016-04-07 08_40_11-free bdsm dating for a bdsm social dating website for bondage s m and fetish ki](https://cloud.githubusercontent.com/assets/13656046/14342819/f3c0a944-fc9c-11e5-93d2-05e868aa8ee5.png)

**Comment by Data66PF** [comment]
I'm not able to reproduce this on my test site. I do note that the client had posted at the forum that he's edited the default bootstrap css files which will break the script. Please revert bootstrap to default condition and please be sure to edit your custom css files for your flavor only.

If you have reverted and rebuilt bootstrap core and restored the original bootstrap css files to original condition and then fully cleared cache, let us know as right now, I cannot reproduce an issue. My custom theme is based on bootstrap theme.

**Comment by Data66PF** [comment]
Please try with 4.3.2 and please make sure the default bootstrap files have not been edited. I still cannot reproduce this.

**Comment by one44** [comment]
Ok fixed
