### ISSUE TITLE
Blogs added with visibility everyone not visible for guest users

### ISSUE THREAD

**Issue by supreshc-persistent** [moxi9/phpfox#1314]
phpfox v4.3
Blogs added with visibility set to 'everyone' are not visible for guest users.
Checked the query in code and it seems to be same for logged in user and guest user.

**Comment by Data66PF** [comment]
Please make sure the site is not set to Friends Only Community in admincp >>settings >> site settings

**Comment by supreshc-persistent** [comment]
Thanks!! that helped
