### ISSUE TITLE
Menu with http in url will not switch over when in https mode with page

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1316]
Menu with http in url will not switch over when in https mode

steps to reproduce
1. create a page
2. add menu with url to page using http

it will not switch over to https and say page not found.

**Comment by Data66PF** [comment]
If we are making a page, we can select to create the menu automatically. Are you saying you didn't allow the page to make a menu?

If you set the menu to http yourself, then you made an error doing that. This doesn't sound like a bug at all.

**Comment by darksolar1** [comment]
What I mean by that is that if you make a menu with a different name with the same link. For example:

1. You create a page: http://www.your.com/index.php/my-stuff/

2. now create a menu and call it, "just steff" with the url of: http://www.yoursite.com/index.php/my-stuff/

3. Now switch the site to run in https mode.

When you click on the link it will throw a file now found and the url will be something like: https://www.yoursite.com/index.php/page/view/

**Comment by neil96** [comment]
Could you try again with url value  only: "my-stuff"

**Comment by darksolar1** [comment]
if you just do "my-stuff" it works fine, but when there is an http in the url when creating the menu it. It doesn't switch properly to https.

**Comment by neil96** [comment]
This is how we desgined. Please read here for more information: https://docs.phpfox.com/display/FOX4MAN/Creating+or+Editing+Menus
