### ISSUE TITLE
Smashed text in mobile on home page

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1318]
Smashed text in mobile on home page. This is the text that is entered in the "Main content" of theme --> home of bootstrap.
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14351777/27288dae-fc9f-11e5-97c0-b30d44b641da.png)

**Comment by Data66PF** [comment]
Please read our instructions for posting bugs and include all details or the bug will need to be closed for lack of information.

**Comment by neil96** [comment]
Duplicate with #1226
