### ISSUE TITLE
Captcha not being displayed on Registration after enabling

### ISSUE THREAD

**Issue by supreshc-persistent** [moxi9/phpfox#1319]
Phpfox V4 

Captcha not being displayed on Registration Form after enabling from admincp, theme used is bootstrap.

the captcha code appears in the markup as hidden but with form tags wrapped to it which ideally should not happen as captcha is part of registration form.

Captcha works fine for the registration popup form.

**Comment by myphpbear** [comment]
Hello.

Captcha is not been displayed on the front landing page.
It's enabled in admincp, however when visitors arrive at my site, they are able to fill in the registration form, but are not able to complete the registration as the Captcha is not shown.
