### ISSUE TITLE
All the link are problematic

### ISSUE THREAD

**Issue by loev139** [moxi9/phpfox#132]
Please visit teenybook.com to review and check

**Comment by Data66PF** [comment]
Please disable any v3 stuff and clear cache. Please note that this is not for site issues. It is for bugs.

**Comment by loev139** [comment]
Please note this is completely new site without any V3 version staff!!!

**Comment by RaymondBenc** [comment]
Was your issue resolved? I checked the site mentioned in this post and couldn't find what links were causing the problem.

**Comment by loev139** [comment]
Yes, The problem, caused by development environment, was solved and all most nginx configuration needed to be modified.  I found a part configuration was designed to Apache, such as shot URL. Now I want to upgrade to 4.0.3 version, but I have modified a part of files so I want to know do you have any suggestion of minimum infection of files?

**Comment by Data66PF** [comment]
Will confirm this as clients at the forum are posting issues with short url and nginx so we might need a tutorial for that.

**Comment by RaymondBenc** [comment]
Correct, the Short URL in the AdminCP is designed for Apache mod_rewrite. That specific rewrite will not work on Nginx.

What other config values were needed to be changed? I personally develop under nginx and use a stock version of it, other then converting the rewrite rules.
