### ISSUE TITLE
Login Button not working on Iphone 6

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1320]
Latest Phpfox with bootstrap and tested with chrome,safari on IPhone 6
On Iphone 6 when I click the login button we get this page loader as shown below but the login form don't load.
![image](https://cloud.githubusercontent.com/assets/406030/14380576/7816a23c-fd80-11e5-97ae-723f95e5ccff.png)

**Comment by darkname** [comment]
That's weird, because yours does not also work on iPhone 5S and mine does. What if you show the menus ?

**Comment by aakash83** [comment]
vivian can u please test it on my website . www.virtualians.com .

**Comment by neil96** [comment]
I tested on your site and can't reproduce too.

**Comment by Vivian-phpFox** [comment]
I can reproduce this issue on your site. Kindly submit a ticket with details for us.

**Comment by aakash83** [comment]
can you please tell me which details you need. so I can include all required information in ticket.

**Comment by neil96** [comment]
We need adminCP and ftp to check your configs.
