### ISSUE TITLE
Wrong number of reviews show up on the developer profile page 

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox#1321]
The developer has more than 10 reviews, however it always shows the number of reviews is (4) and when user clicks on all review, it shows all of the reviews with a cut-off detail and without the option to view full message.

**Comment by Data66PF** [comment]
Please send this to us in a ticket as this is only for script bugs. Please go to your client area and send a ticket https://clients.phpfox.com/ as we need to keep this for script bugs. I'll add this to our internal tasks though.
