### ISSUE TITLE
Missing user iamges after upgrade

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1322]
Latest phpfox with bootstrap theme. using chrome on windows 10

After upgrade a lot of user images are missing including display images, cover photos and images shared on walls. But not all images some of them are loading and some don't. I checked directory permissions and it looks ok. I followed all post upgrade steps and cleared cache .
I enabled debug but phpfox don't show any error.

![image](https://cloud.githubusercontent.com/assets/406030/14381302/c2ff1ba8-fd85-11e5-9aa4-4922c8d57468.png)

![image](https://cloud.githubusercontent.com/assets/406030/14381291/a8e43cb2-fd85-11e5-85ec-cc041f11e189.png)

**Comment by Data66PF** [comment]
Please wait for 4.3.2 as we had a blog regarding some issues on upgrades.
