### ISSUE TITLE
PHPfox getblock issue

### ISSUE THREAD

**Issue by coolcoder07** [moxi9/phpfox#1323]
We are using phpfox v3.7 script. We are customizing the script as per the business needs and designed a new look for the solution.
We are using ajax calls drastically on the entire site to load contents dynamically.  For that we have defined several modules and created blocks as needed.  Most of our blocks are loaded using getBlock method with the help of $ajaxcall function.

To provide more clarity, refer the following sequence:

Step 1: Load Initial Module A from the controller.  The association of Module A with Controller is made using admin panel.

Step 2: The Module A Calls several other modules using {module name=(module_name.block_name)} 

Step 3: These further modules has few events which, using javascripts, calls the service file to do some database level operations and loads the blocks using getBlock method.

We have observed following two issues:

1. The javascript of the loaded block does not get executed.  The CSS effects does not shown properly.

2. In few cases, the Ajaxcall does not get executed.

**Comment by Data66PF** [comment]
This issue tracker is only for V4 bugs. Please post your questions at our community https://community.phpfox.com or, if you can't access it, post at my site http://scripttechs.com
