### ISSUE TITLE
Egift. Shows last gift. If scroll bar is @ bottom when switching categories.

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1325]
If the scroll bar is at the bottom, it will show the last gift @ the bottom when the category is changed.

**Comment by Data66PF** [comment]
Are you testing 4.3.1 ?

**Comment by lueung** [comment]
Yes

**Comment by Data66PF** [comment]
I'm not able to reproduce this. How many gifts do you have in the categories?

**Comment by lueung** [comment]
Varies from 15-18 per category. 

Steps to reproduce. 
1. Scroll the gift bar to bottom then start switching the categories. The scroll bar will remain at the bottom.

**Comment by neil96** [comment]
Can you reproduce on 4.3.2b5?
