### ISSUE TITLE
Egift: Cannot use points to purchase egift.

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1326]
Cannot purchase egift with points.

**Comment by Data66PF** [comment]
also cannot reproduce on v4.3.1 chrome browser, mac notebook.

**Comment by lueung** [comment]
Hmm... I don't even see an option to use points for purchase. Do you have the gateway enabled or off?

**Comment by Data66PF** [comment]
I have paypal enabled.

**Comment by Data66PF** [comment]
I've now disabled the paypal and only have points active for purchasing. Note that you still have to set the conversion rate in the settings for points at the user settings.

I have an egift set up as a year round gift and it costs 1 point.

My user groups are set to allow purchasing with points.

I go to the profile of someone I want to purchase a gift for. I click the gift that is for sale for 1 point.

My user has 280 points so there are enough to cover it. When I click the gift, I put something in the share box such as "this is for you!" and then click Share.

I now am at the page that tells me I need to purchase it and gives me the button to click to purchase for one point.

I purchase it and it deducts the point.

**Comment by lueung** [comment]
Perfect. Thanks!
