### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1327]
I am not sure why but when I upgrade I find that some my css changes are negated after each upgrade. These are only color changes and not layout changes. It seems that css is tweaked at each upgrade. I know in themes css can be tweaked but it is limited. Can all css for theme colors not be separated into a separate css file and all layout css in another file. IMHO this may prevent a lot of issues with sites after upgrades. When I upgrade I find some color css changes remain while others change to default theme css.  I must ad I have changed most css as I have a black theme with no white anywhere.

**Comment by Data66PF** [comment]
Please make sure that you are never editing any default css files. Every theme has its own autoload.css and autoload.less files found in PF.Site/flavors/yourtheme/assets/  and those are the only ones you should ever be working on. The default bootstrap should always remain intact and unedited.

**Comment by Data66PF** [comment]
I am unable to reproduce an issue on my dev site. Using a custom theme with custom css. Not sure if someone else can find an issue perhaps.

**Comment by one44** [comment]
Ok i see my mistake
