### ISSUE TITLE
Remove friend block in profile.index

### ISSUE THREAD

**Issue by marcelo-oliveira** [moxi9/phpfox#1328]
Guys, good morning.
We are trying to disable "remove friend block" from profile.index page, but it still there.
Follow attachs...
![phpfox-admincp-blocks-configs](https://cloud.githubusercontent.com/assets/6684425/14387028/c7e21d12-fd7d-11e5-8bcd-8f16e582bc11.jpg)
![phpfox-profile-blocks](https://cloud.githubusercontent.com/assets/6684425/14387032/d22cadd2-fd7d-11e5-9079-15b4e91953d6.jpg)

**Comment by Data66PF** [comment]
Tested on my dev and the Remove Friend block only disables if we also disable the Report User. As these are separate blocks, we need them to work independently.
