### ISSUE TITLE
Profile Info Page Stays Blank

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#133]
No information shows up on the profile info section...
![7-17-2015 4-40-19 am](https://cloud.githubusercontent.com/assets/13330878/8744328/56da2264-2c44-11e5-97f5-5fcd02eb9954.jpg)

**Comment by Jinkers** [comment]
@orgazilla. Go to the Admin CP->blocks->profile.info and if you see 
![image](https://cloud.githubusercontent.com/assets/7270030/8759825/267198e2-2d42-11e5-94e8-1c57a197573d.png)
that will be the leading cause of the issue. My work around is to go to Admin CP->custom fields->add new and make a new field called "About Me" and then change the controller of the user::cf_about_me to the custom field one that you created (under the 'custom' heading in the drop down menu). 

Hope that helps.

**Comment by orgazilla** [comment]
Didn't work! I noticed that the profile info page is blank on the community.phpfox.com site too...

**Comment by orgazilla** [comment]
Please fix this!

**Comment by GloriousKoch** [comment]
This page populates as soon as you give it information in your 'About Me' profile section. I agree it could be explained a bit better, but when info is entered it will populate there.

**Comment by GloriousKoch** [comment]
Did you create any boxes to be on that info page? By default, the About Me goes on your first page. If you set it to appear on the info page, it should go there instead.

**Comment by orgazilla** [comment]
I tried to create some custom boxes, but the boxes still won't show up. I hope they fix this...

**Comment by Jinkers** [comment]
So you have entered content in your profile settings and nothing shows up still?

**Comment by GloriousKoch** [comment]
Can you give us a screenshot of your admincp under the "Boxes" tab and the Profile.Info section?

**Comment by Data66PF** [comment]
Confirmed. The issue appears to be that the other custom field, About Me, is set to profile.index but it is expected to be seen in profile.info. This could be done by design. If anyone wants to change it, just change it in the block manager for the controller to be profile.info. This worked for me. If you already made a duplicate one though, it might not work for you as the script sometimes goes nuts if it has duplicates in it.

**Comment by Data66PF** [comment]
The about me is showing fine on the PF community, http://community.phpfox.com/profile-data66/ top left of the profile under the user image.

**Comment by Data66PF** [comment]
This appears to be working fine on the PF community and on my further tests.

**Comment by Ylmzef** [comment]
Its not just about section where is custom fields?

**Comment by shakti7188** [comment]
hi data66,

its not working fine..

check your page   http://community.phpfox.com/profile-data66/info/  
its blank

**Comment by Data66PF** [comment]
There is already a new bug for this.
