### ISSUE TITLE
not able to Setup PF Site on Nginx Web Server

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1331]
i have fresh install Latest v4.3.1 on Nginx Ubuntu server.but not able to login.Site is not working properly
PFA same
![nginx error](https://cloud.githubusercontent.com/assets/13433124/14427857/4299bd6a-0014-11e6-9fbb-e32809c8842f.png)

**Comment by Data66PF** [comment]
We had posted a blog regarding upgrading. Please do not do any upgrades or installs until we release 4.3.2.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1257 more info there. the fix is in 4.3.2 coming soon.
