### ISSUE TITLE
V4 3.0.1 build5 & 3.1.0 Deleting User on AdminCP not work

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1332]
I experience this issue since 3.0.1 build5 and I have fresh Install 3.1.0 but this problem is still exist.

1. When I try to delete some user on AdminCp, The "Delete" button is not work.
2. If I try to use drop down menu to delete user, but only loading and no action.

Thank You!

**Comment by neil96** [comment]
I can't reproduce reproduce this issue even when I turn debug mode on. If it happens on your site, please submit a ticket with your site information, I will check for you.

**Comment by juniortimeline** [comment]
Ticket Sent. Thank You Sir

**Comment by Data66PF** [comment]
cannot reproduce on my test site either. Please disable all apps and remove any customization, clear cache and please check again. We will respond in the ticket too.

**Comment by juniortimeline** [comment]
Before I install anything this bug is already on my site. This is the second time I refresh install my website. Thank You.
