### ISSUE TITLE
Supporting Gif's in E-gifts

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1333]
Hello :) , 

I Was testing my site a couple of days ago and I started to add E-gifts, I could see that the file extensions supported for e-gifts are  jpg, png, and Gif, 

but the Gif's dont work, you add a gif picture and its like adding a normal picture, Donna has said that this has never worked so I'm just wondering, will it be fixed soon ? :) 

thank you :) 

![image](https://cloud.githubusercontent.com/assets/16384395/14466460/da550848-00ce-11e6-88fc-5f4e75a378cd.png)

**Comment by Data66PF** [comment]
please post in feature requests
