### ISSUE TITLE
Languages box layout issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1334]
Language box layout showing complex.
Tested on v4.phpfox.com too.

![download](https://cloud.githubusercontent.com/assets/8562514/14479295/62ebbe92-011d-11e6-94d4-157dcd9f182a.png)

**Comment by Data66PF** [comment]
I don't see any problem.
![language](https://cloud.githubusercontent.com/assets/6908282/14489322/7b237f1e-013a-11e6-9556-3e0613d5286d.png)

**Comment by Ylmzef** [comment]
Okay than :smile:

**Comment by akvaskov** [comment]
It would have a better look if the text was aligned center left inside of a language block.
