### ISSUE TITLE
Strange random behavior with bootstap theme using chrome

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1337]
When using chrome and refreshing the browser, bootstrap themes exhibits strange behavior that is totally random at times. Cannot reproduce this using firefox.

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14499929/12bcac14-016e-11e6-8390-965e5d8ab5ef.png)
![screenshot2](https://cloud.githubusercontent.com/assets/17013208/14499995/460f5f62-016e-11e6-8479-041a25107715.png)
![screenshot3](https://cloud.githubusercontent.com/assets/17013208/14500000/4ba5907c-016e-11e6-82c2-e6b0fa879828.png)
![screenshot5](https://cloud.githubusercontent.com/assets/17013208/14500007/52b57e54-016e-11e6-8492-9509131fe0a0.png)

**Comment by Data66PF** [comment]
Looks like an app issue. Please test with all apps and customizations disabled and on an unedited default bootstrap theme.

**Comment by lueung** [comment]
I believe it may be related to the theme issue I reported earlier as this wasn't an issue prior to the update and nothing has change except for the update. Just to confirm I did do as you've suggested and it still occurs, but it's kind of random when it occurs.

**Comment by neil96** [comment]
Could you send me the site url that have this bug? I will check where this bug comes from.

**Comment by lueung** [comment]
Sure. I'll send it via phpfox support :)

**Comment by lueung** [comment]
There is something wrong with the phpfox ticketing system. It's seems to be stuck on an infinite loop when sent to hello. I keep getting a message that says ticket has been open.

**Comment by Data66PF** [comment]
Please note that when sending tickets, do not send to the email from before. Always log into the client area when opening tickets now. That old email only goes to sales where Neil and other core devs cannot see it. We have moved it to his department.

**Comment by Data66PF** [comment]
Did you check with YN to see if that app is updated to the current version? We don't have this issue on our testing sites without the app.

**Comment by lueung** [comment]
I've opened up a ticket with YN over the week-end. Haven't received a response yet.
