### ISSUE TITLE
Egift stops working after adding more categories and gifts

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1338]
During the first initial adding of egifts. it seems to work fine, but after a bunch more categories and gifts it stops working and shows the following when sending a gift with a message. It shows a blank message with the same date every time.

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14501944/d83c0a68-0176-11e6-97c4-bb000c6308f2.png)

**Comment by Data66PF** [comment]
How many categories and gifts?
