### ISSUE TITLE
Missing Phrases to translate in AdminCP

### ISSUE THREAD

**Issue by iogames** [moxi9/phpfox#1339]
Here you can find 3 phrases that are not included in the translation files:

AdmincP > Tools > Settings > Modules
- Event
- Feed
- Music
![error1](https://cloud.githubusercontent.com/assets/342235/14506919/686a83b6-017d-11e6-8bcb-a62c9ca1836a.png)

**Comment by Vivian-phpFox** [comment]
Can not reproduce on V4.3.1

**Comment by iogames** [comment]
Ok I will reinstall and let you know... I am the translator of Spanish, and 2 sites show the problem...

**Comment by Madtwister** [comment]
I run PF4.3.1b4 and I also have the same issue. I tried many times to find missing phrases and had no success.

**Comment by neil96** [comment]
Feed is already phrase, var_name: feed.feed
Fixed for music and event: var_name: event.module_event, music.module_music
