### ISSUE TITLE
Bank payment option in payment gateway

### ISSUE THREAD

**Issue by kosytedy** [moxi9/phpfox#1341]
It would be nice to add a payment gateway option that supports bank payment. The advertiser pays at the bank, then proceeds to your site and creates an advert, submits bank payment details like teller number, scanned photo, etc and the administrator either approves or rejects the advert. PayPal and most payment gateways don't allow payments going to many countries in Africa which is a big challenge and also makes PhpFox advert useless for Africans. Thanks.

**Comment by Data66PF** [comment]
This is the bug tracker and is not for features. Please post this feature at the phpFox forum but note that apps for this already exist.
