### ISSUE TITLE
Blogs do not open from pages

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#1342]
![2016-04-14](https://cloud.githubusercontent.com/assets/14006326/14527240/94d3b154-0216-11e6-988c-c09e6f4b683d.png)
When clicking on blog from any page other then the menu tab it will not open.

**Comment by Vivian-phpFox** [comment]
Can you reproduce on demo site?

**Comment by ASNLifestyle** [comment]
what is link to Demo site? will try but PHPFOX Solutions said they looked at it and thought it to be a bug in script and referred me back to here.

**Comment by ASNLifestyle** [comment]
FYI blogs do open on demo site. no blogs there but they do open.

**Comment by neil96** [comment]
It's working on our demo: https://v4.phpfox.com/pages/216/blog/

**Comment by Data66PF** [comment]
You have many apps. Perhaps an app or customization has caused your issue. We cannot reproduce this in our tests at the demo or my testing sites.

**Comment by websistema1** [comment]
I have had this error after updating - when viewing all blogs the words "null" You can see the link https://vsitut.com/blog/

**Comment by Data66PF** [comment]
This is not for support. If you need support, please send a support ticket via the client area https://clients.phpfox.com . The Null issue last time was due to an app.

**Comment by Data66PF** [comment]
As we cannot reproduce this on our demo or test sites, for those that can, please send a support ticket if you have purchased a support plan. Please ensure you are using default blog module and most current version when testing.

**Comment by websistema1** [comment]
The error appeared after updating to 4.3.2-b2. Before that there was no error. At the demo site, I tried to analyze the situation. Remove all the additional applications - error remained (Blogs only appear when you refresh the page by pressing the F5 key). When installing a new 4.3.2-b2 - no error.
