### ISSUE TITLE
Music upload max file size

### ISSUE THREAD

**Issue by Madtwister** [moxi9/phpfox#1345]
![music1](https://cloud.githubusercontent.com/assets/16197707/14560752/a88e5bb2-02df-11e6-84be-7f116df17c90.jpg)
![music2](https://cloud.githubusercontent.com/assets/16197707/14560753/a8933c90-02df-11e6-8275-63eb9e4578c9.jpg)
![music3](https://cloud.githubusercontent.com/assets/16197707/14560751/a88d2c38-02df-11e6-8b58-10383cb0b804.jpg)

The settings: Maximum file size of songs uploaded is set at 10360mb and when on site, it displays to the user, 2 mb max file size upload. For ex: Changes in photo module are applied to new changes and work fine.

There is also a mixed language on the page, French and English and the same is happening to v4.phpfox.com demo site.

**Comment by neil96** [comment]
Please check your server config (upload_max_filesize and post_max_size).

**Comment by Madtwister** [comment]
Then do you know why its working with photo module, I can change the file
size to what I want and not music?

I am hosted by phpfoxsolutions, this is no problem, I will check with them

Thank you

On Fri, Apr 15, 2016 at 7:59 AM, Neil <notifications@github.com> wrote:

> Please check your server config (upload_max_filesize and post_max_size).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1345#issuecomment-210437902>
>



-- 
Pierre et Chantal

**Comment by neil96** [comment]
It's working on demo: https://v4.phpfox.com/music/upload/
