### ISSUE TITLE
Music Upload a Song

### ISSUE THREAD

**Issue by Madtwister** [moxi9/phpfox#1346]
Mixed language on page, English and French and also on v4.phpfox

![music2](https://cloud.githubusercontent.com/assets/16197707/14562084/acd8049e-02e8-11e6-89ae-dfd66f20ed43.jpg)
![music3](https://cloud.githubusercontent.com/assets/16197707/14562262/9d9eece4-02e9-11e6-96ae-6f00ac911b50.jpg)

**Comment by Data66PF** [comment]
this is not on our demo as we don't have French on it. Perhaps your French language translation overwrote the default English for some phrases. 

Cannot reproduce on the live demo or on my test sites.

![upload](https://cloud.githubusercontent.com/assets/6908282/14601648/62467410-0531-11e6-9f68-80b8764204a3.png)

**Comment by Madtwister** [comment]
Phpfox 4.3.1b4

I tried Find missing phrases several times and I was not able to find; Choose file and No file chosen in Language phrase.  

In the filter, search for text, are you able to find these words? because I cant.

**Comment by neil96** [comment]
@Madtwister 
These phrases (Choose file and No file chosen) from the browser. You do not need to translate them, because it will change base on language on the brower of the user.
