### ISSUE TITLE
Language Phrase Problem & Renaming Menus

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1348]
I try to rename some words from Phrases and rename the word from menu but It's not change.
I try to disable all my 3rd party module, rebuild my theme core and clear cached but still not change.

Thank You.

**Comment by Data66PF** [comment]
Which menu? Did you clear cache?

**Comment by juniortimeline** [comment]
All Menu. Even some words on Language Phrase

**Comment by Data66PF** [comment]
This bug report is too vague. I can rename menus with no issue after cache is cleared when I rename the menu. To rename a menu, go to AdminCP >> Menus and click to edit the menu you want to rename. In my case, I chose Photo menu. I renamed it to Photo2 and the Spanish translation to Foto2 and it worked fine. I have no issues with languages and menus either. 

I cannot reproduce any issue in 4.3.1.

**Comment by Data66PF** [comment]
If still having issues, please submit a ticket to our support at https://clients.phpfox.com .
