### ISSUE TITLE
Not translated in the mobile view

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1350]
I just have the problem in the responsive view

![untitled](https://cloud.githubusercontent.com/assets/8930862/14589093/5520584a-04e2-11e6-9fcc-6cac0456059a.png)

and http://site.com/user/register

![register](https://cloud.githubusercontent.com/assets/8930862/14589512/99864756-04ec-11e6-9e00-a23706119453.png)

**Comment by karargaht** [comment]
Categories: Video page = **OK**

But Name: Create page and Save: Profie cover reposition saving **still same.**

**Comment by neil96** [comment]
@karargaht Please open a new issue with name and location you got it.
