### ISSUE TITLE
reproduce issue #326 -Picture upload is not behaving correct in Android OS

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#1351]
hi, even on 4.3.1 this problem is not solved.
i tested it on v4.phpfox.com and not found the gallery option to choose images on andriod OS in PHOTOS section.
Photo upload on status post works fine.
here is the snapshot 👎 
https://cloud.githubusercontent.com/assets/8586180/14415323/563d2f4a-ffbb-11e5-993f-2b87194e8caa.jpg

**Comment by shakti7188** [comment]
it's still not entertained .what's going on data66 ?

**Comment by shakti7188** [comment]
no its not fixed. please try again.  "gallery" option is visible is available on cover upload and status post photo upload  but not available on photo section upload photo (/photo/add). And solve it ASAP , its an embarassment .

**Comment by neil96** [comment]
I fixed in 4.4, please wait 4.4 release.
