### ISSUE TITLE
Video Title and Caption in Russian Displays Wrong

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1352]
At the phpFox demo, https://v4.phpfox.com/v/play/121849/  using this video to test, https://www.youtube.com/watch?v=Wgz_01aS7cI it shows as

Ð¤Ð¸Ð»ÑÐ¼ Ð½Ð¾Ð²Ð¸Ð½ÐºÐ° Ð´ÑÐ°Ð¼Ð°-Ð¼ÐµÐ»Ð¾Ð´ÑÐ°Ð¼Ð° 2015 2016. ÐÐ·Ð¼ÐµÐ½Ð°, Ð½Ð¸ÑÐµÑÐ°: "ÐÐ±Ð¼ÐµÐ½ÑÐ¹ÑÐµÑÑ ÐºÐ¾Ð»ÑÑÐ°Ð¼Ð¸" Ð¤Ð¸Ð»ÑÐ¼Ñ Ð¼ÐµÐ»Ð¾Ð´ÑÐ°Ð¼Ñ HD - YouTube

instead of the title and caption in Russian. Reported for a client.

**Comment by karargaht** [comment]
https://v4.phpfox.com/v/play/122029

![language](https://cloud.githubusercontent.com/assets/8930862/14674833/95db8eda-070e-11e6-902f-9266a156488e.jpg)

Turkish language problem...

**Comment by neil96** [comment]
@karargaht, I fixed for Turkish language too.

**Comment by akvaskov** [comment]
Hi, and how to get fixed files now? Thanks!
