### ISSUE TITLE
Pages Blog list show bbcode

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1353]
When clicking on the pages blog it shows the bbcode as it list the blogs

**Comment by Data66PF** [comment]
Do you mean for the image that might be in the blog? If so, this is how it works in the main blog area as well.

**Comment by Data66PF** [comment]
Please check at our demo.

**Comment by lueung** [comment]
I mean this: 
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14637773/82b9d0ae-0601-11e6-90fe-38106592251a.png)
