### ISSUE TITLE
non https doesn't switch properly for pages and results in page not found

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1354]
non https doesn't get switched properly for pages and results in page not found.

For example: http://yoursite.com/index.php/minion-pages/

Results in this: https://yoursite.com/index.php/profile/index/

which then produces a page not found.

**Comment by neil96** [comment]
Can't reproudce. Could you give detail site example.

**Comment by Data66PF** [comment]
Cannot reproduce at our demo. Please test at our demo https://v4.phpfox.com .

**Comment by lueung** [comment]
To reproduce the vanity URL need to be & www enabled 

Cannot reproduce on demo site because www and vanity url is not enabled.

**Comment by Data66PF** [comment]
Your examples never showed www.

**Comment by Data66PF** [comment]
This sounds more like a server issue or redirect issue than a script issue.

**Comment by neil96** [comment]
@darksolar1 Could you submit us a ticket?
