### ISSUE TITLE
non members of pages groups can post without being a member

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1355]
non members of pages groups can post without being a member. or  it could be that it is allowing them to post while it is pending.

**Comment by Data66PF** [comment]
Can you reproduce this or any of your other issues on our demo https://v4.phpfox.com ? Please always test there.

**Comment by lueung** [comment]
Yes I can reproduce on: https://v4.phpfox.com/pages/329/

![screenshot2](https://cloud.githubusercontent.com/assets/17013208/14635839/31a5347a-05f6-11e6-9bd1-f4b09f6d43a9.png)

**Comment by Data66PF** [comment]
What is the privacy at for that group? Is it set so that only members can post?

**Comment by Data66PF** [comment]
https://v4.phpfox.com/pages/354/ please test there.

**Comment by Data66PF** [comment]
Your page/group you made has no permissions set. It is set to anyone so yes, anyone can post.

**Comment by Data66PF** [comment]
How were you able to comment on it? Please provide all steps as my test user cannot.

**Comment by lueung** [comment]
Try again: https://v4.phpfox.com/stuff/pending

![screenshot2](https://cloud.githubusercontent.com/assets/17013208/14636963/8092afd0-05fc-11e6-92ae-06eec8c1d77b.png)

**Comment by lueung** [comment]
On the front end it doesn't show it, but it did in fact post it. There is also a problem if you try to click on pending.

**Comment by Data66PF** [comment]
This isn't for pending. It is for the issue to post to a private page. We have seen the issue.

**Comment by lueung** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17013208/14637314/8686e116-05fe-11e6-9a0b-059ce223e513.png)

**Comment by Data66PF** [comment]
We are already looking into the issue. Thank you for posting.
