### ISSUE TITLE
Pages group pending link does nothing

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1357]
Even tho the pending says 1 clicking on the link does nothing.
![screenshot2](https://cloud.githubusercontent.com/assets/17013208/14626600/fca7fd9c-05ba-11e6-8134-3f7ffc50b599.png)

**Comment by neil96** [comment]
Can't reproduce on V4.

**Comment by lueung** [comment]
Step to reproduce

1. as admin of site click to  join a group
2. from another as that group's admin, go the the group
3. The pending link will be something like this: https://yoursite.com/index.php/examplegroup/pending
4. clicking on pending. It doesn't do anything.

**Comment by lueung** [comment]
This is related to: #135 and #1356

**Comment by neil96** [comment]
From 4.4.0, we separated groups with pages. Please post new issue if you can reproduce on new version.
