### ISSUE TITLE
Homebanner issue

### ISSUE THREAD

**Issue by mobicomfi** [moxi9/phpfox#1358]
Issue is in Macbook Pro. If i go homepage and not logged in and click ex. create ad and sign in block pop up, then homebanner gone away and white backround left. Need to reload page, then banner comes back. Using Chrome and Safari, both has same problem. 

EDIT: I notice now that its not Mac fault, in windows has same problem

**Comment by Data66PF** [comment]
I think this is working as designed but will leave open for another tech to check. Tested at demo.
