### ISSUE TITLE
Can not DELTE user from adminCP

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#1359]
When I try to DELTE a user it does not do it. It brings up a dialogue box asking me if I am sure and when I click yes it still does not delete the profile I am trying to get rid of.

![2016-04-16](https://cloud.githubusercontent.com/assets/14006326/14630893/8cabf7cc-05de-11e6-9715-74b1db355fa5.png)

PHPFox Solutions has suggested it is a bug in the script.

**Comment by neil96** [comment]
We already have a issue (#1332)  like this, this bug come from third-party app. Could you disable all your apps and test again.
