### ISSUE TITLE
Feature images

### ISSUE THREAD

**Issue by MBonner702** [moxi9/phpfox#136]
How do you feature images in v4?

**Comment by Jinkers** [comment]
If you haven't figured it out yet @MBonner702 , once you click on the image to view it, on the post bit there is a 'settings/edit' icon in the top right corner of the post details. Click that and you will find the feature setting.

![image](https://cloud.githubusercontent.com/assets/7270030/8759789/15aa64fe-2d41-11e5-91b6-d40e8c5ac1c1.png)
![image](https://cloud.githubusercontent.com/assets/7270030/8759791/3ace4764-2d41-11e5-9949-381de42b9e09.png)
