### ISSUE TITLE
Newsletter does not support HTML code

### ISSUE THREAD

**Issue by jafxdesign** [moxi9/phpfox#1360]
Hello!
I have tried various times to send html newsletter but it will return plain with the same way the code was written in the users email box

maybe I am the only getting this error, I have searched for this error a number of times

thanks

**Comment by Data66PF** [comment]
I can reproduce this with v4.3.2 using google email in case we need to test per email system. I use the browser email version. I've not tested in thunderbird but since google is well known, the issue is seen there.

**Comment by TrueAmericans** [comment]
I see neil96 added the fixed lable, but where is the fix? 4.4 isn't released yet. We need it now in 4.3.2(build5).

**Comment by neil96** [comment]
@TrueAmericans Please wait 4.4.0 release.

**Comment by TrueAmericans** [comment]
Is it going to be any time soon? It's really bothering my members...

**Comment by TrueAmericans** [comment]
Why would you close a thread that hasn't been answered? This is very frustrating!!

**Comment by Data66PF** [comment]
Neil answered. He said it is fixed in 4.4 release. Please note that it was answered. We close all fixed bugs.
