### ISSUE TITLE
SMS Phone Number Issues

### ISSUE THREAD

**Issue by benjebli** [moxi9/phpfox#1361]
I think The SMS verification is not working at all, I have tried many ways... the phone number sample has less numbers then USA phones, and there is space between numbers, they means there is many ways to fill the number, and every time you get a message " if the phone number is correct contact the admin,  that is very confusing.
the example should be very very explained. And maybe it is better if you give the user the ability to pick his country flag from a list and then add the national number without any spaces or characters.
This service should be a big feature of phpFox, But For now i think it is useless.

**Comment by GreenMan123** [comment]
This happens to my site to please help?

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#152
