### ISSUE TITLE
The label module is not working properly

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1362]
The label module is not working properly.  Below is just a sample. Other labels are also available.

Version: 4.3.1 (4)

![tags](https://cloud.githubusercontent.com/assets/8930862/14671431/77bbd5d6-06fa-11e6-82b2-d9d586380183.jpg)

**Homepage**

![tag](https://cloud.githubusercontent.com/assets/8930862/14671435/7a0c0be4-06fa-11e6-9f29-c304ce0799ff.png)

**Tags Page**

![tagss](https://cloud.githubusercontent.com/assets/8930862/14671439/7c0f3ede-06fa-11e6-83ac-d5870ac428e8.jpg)

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1252 duplicate
