### ISSUE TITLE
Mobile Navigation menu not clickable

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1363]
Hello :) 

I've been testing again, and found that the "Mobile Navigation Menu" isn't clickable 

I've tested my sites code to see if there's any faulty line of code, I've taken all of the code out and put it in one line at a time and then tested it, and its still not working, I've also disabled all of my apps and turned them back on one by one to test it and its still the same,

so I'm pretty sure its a bug aha

**Comment by Data66PF** [comment]
Please test on v4.3.2 and at our https://v4.phpfox.com demo .

**Comment by Lukey199223** [comment]
Just tested it and its working in 4.2 :) , so I'll upgrade to 3.2 myself and it should work :) thanks Donna :)

**Comment by Data66PF** [comment]
I'll close this for now but if it is still an issue after, just let us know.
