### ISSUE TITLE
Can't install manually imported language in 4.3.1

### ISSUE THREAD

**Issue by liviufox** [moxi9/phpfox#1364]
i try to install language in 4.3.1
the language pack is exported from 4.2.2(i did all the translation)
i uploaded the folder and it shows in admin with button to "install"
but nothing is happening after installing.
(after clicking on "manual import" you can see the language with the install button and it starts to proceed ...it says:"importing phrases. please wait...." but after that it returns to the page where you can see the language but it's only english in the list.

**Comment by neil96** [comment]
It's working on my test site. In this step "importing phrases. please wait...." the site refesh many times before it completed..

**Comment by liviufox** [comment]
what language did you install...is it from the market apps or is it like in my case the one i did in 4.3.1 and exported?

**Comment by neil96** [comment]
I did as your steps that you provided above.

**Comment by liviufox** [comment]
i think we misunderstand each other....is it your language pack created inside admin(not installed from apps)?? .my language pack that it was exported is not bought from apps but created and translated by me. how can my own language pack make a call back with phpfox as long as is not listed in apps. i think this is the problem :when i manually import it, it does all the steps even the message that it was successfully installed but when you go to: settings>language the only language is english. i have tried it in 4.3.2 build 3 too

**Comment by cespiritual** [comment]
I have the same problem. I'm trying to import a v3 pack, I do all the steps here... I click in the install buttom, all goes well, in the end I get the sucessfull message, but my language pack don't show only the default one.

**Comment by liviufox** [comment]
the language pack i try to install is a V4 not a V3. i was thinking to install that one from v3 but Data told me not to do it as it might be different, so i translated nearly everything again, i did an export but after that when i did a script upgrade i had server errors. After errors i decided to reinstall the script with the latest version. On the new install i didn't have my language and i tried to install it, executed with all the confirmation messages but it's just not there. In my opinion is something to do with a call back on phpfox.  We can see if it really works if you are willing to do a test like this : create a new language inside the script (in V4)>> the new language is still in english>>try to translate some sentences that you can find later>> export the new language and after you have it exported delete it from the site>>now you only have english and a folder with the second language which you can upload and install on site. If is working for you in that way than it might me a problem on my side...but i guess the problem is like this: we try to install a pack from outside the app store and it doesn't have a call back to phpfox and that is the reason for not being installed.

**Comment by cespiritual** [comment]
I have solved the problem and installed v3 pack.

When I do all the process of "manual install" and in the end it says Sucessfull, the pack don't show on the list but all the phrases are added to the table phpfox_language_phrases. So the problem is that the pack is not created on the phpfox_language table.

The solution is to create manualy that pack to link it to the phrases.

I have donne that by running this:

```
INSERT INTO `phpfox_language` (`language_id`, `parent_id`, `title`, `user_select`, `language_code`, `charset`, `direction`, `flag_id`, `time_stamp`, `created`, `site`, `is_default`, `is_master`) VALUES
('PT', NULL, 'Portugues (PT)', 1, 'PT', 'UTF-8', 'ltr', 'png', 1184048203, 'N/A (Core)', '', 0, 0);
```
Just change the PT for your language code.

**Comment by LMG123** [comment]
Was this fix on RC1?

**Comment by Data66PF** [comment]
https://community.phpfox.com/forum/thread/55131/import-own-language-pack/ according to that thread, those clients are not having any issue importing.

**Comment by Data66PF** [comment]
Is this still an issue in 4.4.1 build 2?

**Comment by liviufox** [comment]
yes it is....i just tried it now
the only way is the one cespiritual explained above
