### ISSUE TITLE
Missing description for points

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1366]
Missing description for points

![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/14688378/4f8daf92-0710-11e6-88cc-dc1a04e42e5a.png)

**Comment by Data66PF** [comment]
Did you run find missing phrases? Did you ensure that a language pack had not deleted the default phrase?

**Comment by lueung** [comment]
Sure did

**Comment by neil96** [comment]
Our code end with module quiz. I think that from third-party module. 
![screen shot 2016-04-21 at 08 49 20](https://cloud.githubusercontent.com/assets/15936115/14695640/32b86f54-079e-11e6-9d7d-6cd1cd462c62.png)
