### ISSUE TITLE
No way to separate payment methods for Gifts and Points

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1368]
For example, I want to allow people to purchase points with paypal and only only allow egift to be purchased with points. The problem is if I disable the payment gateway, they will no longer will be able to purchase points. 

The point system is not very user friendly at all and could definitely use some improvements for ease of accessibility and features.

**Comment by Data66PF** [comment]
I have payment gateways disabled and it works fine for my tests. My users can purchase with points without issues. Note that feature requests to change features must be in the feature request area.

Please file a feature request for this.
