### ISSUE TITLE
Cannot import Language pack.

### ISSUE THREAD

**Issue by kengracing** [moxi9/phpfox#137]
Because there is no menu to import Language pack.

Must enter by yourself
yoururl.com/admincp/language/import
When I click install, no response.

**Comment by Data66PF** [comment]
I can confirm both issues.

**Comment by piramidesoft** [comment]
Still having the issue in 4.0.5.
No menu and no response if I "Install" with the manual link

**Comment by lupuspl** [comment]
The same issue, no menu to import.

**Comment by kengracing** [comment]
This bug remains.

**Comment by paolspo** [comment]
PHPfox 4.2.2 during installation can't import language package, can't install. unfortunately i don't know what to do. thanks for support

**Comment by Data66PF** [comment]
When a bug is closed, it is not looked at. If an issue persists, a client needs to open a new one in order for it to be tested again.
