### ISSUE TITLE
Music - Sharing Problem (still not working)

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1372]
This problem since 4.3.1 and still same problem. This screenshot is from PphpFox v4 Demo site.
Thank You!

<img src="https://v4.phpfox.com/PF.Base/file/pic/photo/2016/04/4976b1bf90a4a4661a8a31147028242c_1024.jpg">

**Comment by Data66PF** [comment]
What browser and os are you using? Please when posting issues always state the browser and os.

**Comment by GreenMan123** [comment]
Windows opera,Safari,Crome browsers

**Comment by Data66PF** [comment]
what version of windows? please always state the browser and os versions.

**Comment by Vivian-phpFox** [comment]
Duplicate #1261

**Comment by juniortimeline** [comment]
Vivian this is not a duplicate. This is about Music module only and not the same issue from ticket #1261.
