### ISSUE TITLE
fcgi

### ISSUE THREAD

**Issue by mikelcoreclark** [moxi9/phpfox#1373]
Ok I enabled short urls to see if that would help and it doesn't. The script, with this at fcgi mode, is looking for ajax in the main site root instead of in PF.Base and so it can't find it. I think your server is not displaying errors (display_errors must be enabled)
There is also an error showing in the developer browser console with debug enabled. I suggest to post all of this at github in two error reports. One for FCGI error finding ajax and let them know it was first not set to short urls and then set to short urls and both had the same result - it could not find ajax to post to the feed.
 - ScriptTechs
thanks
mikel

**Comment by Data66PF** [comment]
Issue is with third party app.
