### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by mikelcoreclark** [moxi9/phpfox#1374]
The second bug is the "syntax error, unexpected end of file" for the feed. 
…/¬file/¬cache/¬template/¬feed_template_default_block_entry.html.php_ajax.php45
Open: /home/lasanza/public_html/PF.Base/file/cache/template/feed_template_default_block_entry.html.php_ajax.php

<?php
Phpfox::getLib('template')->getBuiltFile('feed.block.content'); 
?>

<?php (($sPlugin = Phpfox_Plugin::get('feed.template_block_entry_3')) ? eval($sPlugin) : false); ?>
</div>

 ScriptTechs
thanks
mikel

**Comment by Data66PF** [comment]
issue is with third party app
