### ISSUE TITLE
Missing image Marketplace

### ISSUE THREAD

**Issue by jrann** [moxi9/phpfox#1375]
When adding featured listing for marketplace in block 3 core.index.member
It shows not found instead of image. phpfox v4.3.2
![marketplace no image issue](https://cloud.githubusercontent.com/assets/18630247/14761650/bf16bda8-09aa-11e6-9256-eaec02168cda.png)

**Comment by Data66PF** [comment]
confirmed on my 4.3.2 dev site with the feature listing block in marketplace.index also.
