### ISSUE TITLE
Bug# When trying to use share Song (Music - mp3) it has no options ie. your wall - friends wall

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1379]
![image](https://cloud.githubusercontent.com/assets/17736688/14932398/1ef62ff8-0e3b-11e6-9dd4-802a86b6ef6e.png)

**Comment by spirogg** [comment]
firefox is the only browser i tried it with. latest download today 4-29-16 from phpfox.com  pro version

**Comment by spirogg** [comment]
windows 10 pro,  uploaded mp3 then tried to share from home page. no share options

**Comment by Data66PF** [comment]
Search before posting please. https://github.com/moxi9/phpfox/issues/1261
