### ISSUE TITLE
adding managing states/provinces in countries

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1380]
Hi when managing states / provinces in settings >> countries>> managing

 it only allows you to add one and then you have to go to step 1 again

can we create an ADD button to the right of DELETE in manage states / provinces will be so much more productive and we can just keep adding :) PLEASE

![image](https://cloud.githubusercontent.com/assets/17736688/14932506/f1e2ef18-0e3c-11e6-8f7c-5f8b149ac375.png)

**Comment by spirogg** [comment]
sorry just noticed this was bug area not extra features also 

I will post in forums under correct category

**Comment by Data66PF** [comment]
Please read our posted rules for making reports. Feature requests are not for the bug tracker.
