### ISSUE TITLE
edit photo disable download - but Download button still there ? 

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1381]
hi windows 10 pro, firefox browser - added photo, editing photo so it wont download, but when save it still has the little image that will allow download of photo. gives error that it didnt download but the button should disappear.. see photos please

thanks
Spiro
![download-enabled-no-still-gives-option-to-download](https://cloud.githubusercontent.com/assets/17736688/14933739/a6056fd6-0e5e-11e6-98fb-8d613e91dbc2.JPG)
![download-button-for-photos-should-disappear](https://cloud.githubusercontent.com/assets/17736688/14933743/bb5452bc-0e5e-11e6-9bc0-32cdc17a9558.JPG)

**Comment by spirogg** [comment]
![no-popup-should-even-appear](https://cloud.githubusercontent.com/assets/17736688/14934185/1bbe9e50-0e6e-11e6-9e37-7f27d556dfed.JPG)

**Comment by Data66PF** [comment]
Are you testing as an admin user or registered user?

**Comment by spirogg** [comment]
admin

**Comment by Data66PF** [comment]
Please test as a registered user that did not upload the photo to the site.
