### ISSUE TITLE
add word - text wrap in Pages - like Privacy page - Terms Page etc please

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1382]
windows 10 pro, firefox browser latest version of phpfox as of today..

 when trying to edit pages its really not easy to add or edit text, should be a better editor..

or try to add word/text wrap in the editor for editing Pages - like Privacy page - Terms Page etc please

thanks

Spiro 

see photo
![privacy-and-terms-all-pages-add-word-wrap-please](https://cloud.githubusercontent.com/assets/17736688/14933948/fb6f97e2-0e65-11e6-8c9c-304224e452bd.JPG)

**Comment by spirogg** [comment]
can you configure this with another editor so we may have access to add / upload photos etc.. also

**Comment by Data66PF** [comment]
Please note that feature requests are not added in the bug reports. Please add a feature request to the feature request area. Please note that we take only one issue per report.
