### ISSUE TITLE
after posting blog and or forum home page center block need limit characters see photos

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1383]
windows 10 pro firefox browser, after adding a forum post ot a blog, when viewing the home page, the center block should have a character limit set not to exceed the box area or a slider bar to read further below

See photo
![post-forums-post-blogs-at-home-page-limit-characters-center-block](https://cloud.githubusercontent.com/assets/17736688/14934106/f2236b0e-0e6b-11e6-90b0-1f73d39ba919.JPG)

**Comment by neil96** [comment]
This is working as designed
