### ISSUE TITLE
blog editor need word wrap when in eidt mode as admin see photos

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1384]
windows 10 pro, firefox browser, latest ver phpfox - fresh install today 

In admin mode not user mode.

after adding a blog, you go to post and click edit, then click preview -  characters extend to far from inside the update window - needs to be wrapped. 

see photos
![preview-when-adding-a-blog-needs-wrap-in-text](https://cloud.githubusercontent.com/assets/17736688/14934197/c91d7c38-0e6e-11e6-8f06-614cecdba7a4.JPG)

**Comment by Data66PF** [comment]
Please read our posted rules for posting bugs. One issue per bug report. Please post the emoji issue separately. Once this is edited, let us know to reopen it.

**Comment by spirogg** [comment]
ok
