### ISSUE TITLE
polls, it shows all polls as 0 but in my polls there is 1 poll

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1386]
latest phpfox fresh install today, firefox browser, window 10 pro.

see photos

![all-polls-show-0-when-i-have-1-poll-in-my-polls](https://cloud.githubusercontent.com/assets/17736688/14934245/8f241558-0e70-11e6-84bb-cae93d82220f.JPG)
![my-polls-show-but-not-in-all-polls](https://cloud.githubusercontent.com/assets/17736688/14934246/9298ad98-0e70-11e6-95d3-ccac3adfa7cb.JPG)

**Comment by Data66PF** [comment]
Please change the site from Friends Only Community and then please check the site again. If this issue and your other issue resolve, please close these as that is how a friends only community works and the v4 version is set to Friends Only Community by default.

**Comment by spirogg** [comment]
same issue with it off just tried

**Comment by spirogg** [comment]
![freinds off](https://cloud.githubusercontent.com/assets/17736688/14936435/4b9ec570-0eb2-11e6-9833-ac89c17cbc58.JPG)

**Comment by spirogg** [comment]
same issue on your demo site phpfox demo
![demo-site-same-issue](https://cloud.githubusercontent.com/assets/17736688/14937030/7faeb84e-0ec0-11e6-9153-cf955c3b969f.JPG)

**Comment by neil96** [comment]
@spirogg I can't reproduce on my localhost and our demo.
It seems above screenshot from our demo do not relate to this issue.

**Comment by spirogg** [comment]
Maybe you fixed this issue when you fixed another issue. I'll wait till next update from phpfox and then continue to report
