### ISSUE TITLE
adding to lisitngs- then sell -then wont show in all listings- all the time ? really weird 

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1388]
hi so i added a house for sale in market place, then shared it to my home page (wall), then after a bit i marked it sold, so i went to market place again and it did not show in all listings

so went to my wall again and it was there.. clicked on it and it opens in all listings ( market Place) then i click on my listings - it still shows up there, but then click o all listings and its gone again ??
see photos

thanks
![click-on-photo-in-my-listings-then-opens-and-shows-in-all-lisitngs-again](https://cloud.githubusercontent.com/assets/17736688/14934389/1cfd7d76-0e74-11e6-9207-66bd95bc2034.JPG)
![from-home page-click-on-house-takes-you-to-market](https://cloud.githubusercontent.com/assets/17736688/14934394/2efe4d7a-0e74-11e6-807d-42f30dab0466.JPG)
![in-all-for-market-place-even-though-its-sold-but](https://cloud.githubusercontent.com/assets/17736688/14934397/35fd5936-0e74-11e6-9f75-b00fdaf05e1d.JPG)
![my-lisitng-shows-house-sold-but-then-click-on-all-again-and-not-there](https://cloud.githubusercontent.com/assets/17736688/14934399/3aa16388-0e74-11e6-928c-a09cb5e09559.JPG)
![the-sold-listing-is-not-there-any-longer-why](https://cloud.githubusercontent.com/assets/17736688/14934403/4e1d9170-0e74-11e6-9ce5-b5f0290019cb.JPG)

**Comment by Data66PF** [comment]
Please change the site from Friends Only Community and test again.

**Comment by spirogg** [comment]
its off same issue as admin in all 3 broswers
chrome edge firefox

**Comment by spirogg** [comment]
![freinds off](https://cloud.githubusercontent.com/assets/17736688/14936496/e57ecd24-0eb3-11e6-8ba5-d4b5aff21f99.JPG)

**Comment by spirogg** [comment]
i tried on your demo site and i get the same issue..

would only ask you after its marked SOLD ??. 
should it only show on users listing. (My Listing) if so then we can delete this bug report or close it. 
I am not sure how the script was built after item is marked sold. ? 
if it should still show to encourage users that someone has actually SOLD something on the market then its not working correctly. if not then it is working as should. @Data66PF @RaymondBenc

**Comment by Data66PF** [comment]
If an item is sold, it should not show in the active items. I believe this is working as designed. I'll test it next week. Note that the demo is a friends only community as well.

**Comment by neil96** [comment]
In default, **sold** listing won't display in **All listings**.
