### ISSUE TITLE
blog edit - preview - emoji does not show in preview mode

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1389]
windows 10 pro, firefox browser, fresh install 4-29 version pro
when editing  a post and clicking on preview you dont see the actual emojis 

@Data66PF i don't have those photos any longer deleted from my laptop. is this good enough ?
I am just trying to help :)

**Comment by spirogg** [comment]
as admin

**Comment by Data66PF** [comment]
Thank you for submitting this. Yes it is fine.
