### ISSUE TITLE
user info in firefox browser - cant scroll without site flickering never stays at bottom

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1390]
Hi when viewing user info page, it wont allow you to scroll to bottom of page, it keeps flickering and jumps back up - you can never see the bottom links in footer 

win 10 pro, firefox browser, latest version phpfox fresh install viewing as admin

![image](https://cloud.githubusercontent.com/assets/17736688/14936389/1dbc63ac-0eb1-11e6-88e2-8edc2a29763d.png)

**Comment by spirogg** [comment]
same issue windows 10 edge browser
Chrome browser latest version of all 3 browsers

**Comment by Data66PF** [comment]
Tested at demo. I can see the issue on a macbook as well. Chrome browser.
