### ISSUE TITLE
pages adding a cover photo not allowed from (add a cover >> Choose from photos as admin)

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1391]
win 10 pro, chrome browser, latest phpfox fresh installed yesterday, testing as admin, Friends Only Community=NO
hi when creating a page then trying to edit to add a cover then choose from photos selecting a photo then redirects you to photos page not adding a cover from photos - you click back to pages and there is no cover photo
![no-cover-photo-using-this-as-admin](https://cloud.githubusercontent.com/assets/17736688/14936797/e2f6048a-0eba-11e6-92b6-12129d0b78c3.JPG)

see photos
![add-a-cover-in-pages-user admin](https://cloud.githubusercontent.com/assets/17736688/14936776/a39900c6-0eba-11e6-843e-f06fda0bc75d.JPG)
![choose-from-photos](https://cloud.githubusercontent.com/assets/17736688/14936780/ad30c7c2-0eba-11e6-870e-9449a8613d09.JPG)
![select-any-one-of-the-2-photos](https://cloud.githubusercontent.com/assets/17736688/14936783/b7e88524-0eba-11e6-9724-6e52bfd79949.JPG)
![redirects-to-photos-and-does-not-add-photo-to-cover](https://cloud.githubusercontent.com/assets/17736688/14936789/c737aa14-0eba-11e6-9c15-2a4207e66d57.JPG)

**Comment by spirogg** [comment]
it does not work. it just takes you to photo page instead of giving you the option to select the photo and then add it to cover...

**Comment by Data66PF** [comment]
Yes it works fine for me. You have to select the photo you want to use after you click to choose photos. I tested at the demo. This works fine.
