### ISSUE TITLE
Adding params to the feed

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#1393]
Hi,

I was trying to add a feed from one of my apps, using this:

```
(new Api\Feed())->setUser(1)->post([
   'type_id' => 'My_App',
   'content' => [
      'title' => 'Feed Title',
      'text' => 'This is the feeds content...'
   ]
]);
```

It works fine, but I need to add also the item_id so I can link the feed with the item of my app. So I tried this:

```
(new Api\Feed())->setUser(1)->post([
   'type_id' => 'My_App',
   'item_id' => $item_id,
   'content' => [
      'title' => 'Feed Title',
      'text' => 'This is the feeds content...'
   ]
]);
```

But nothing is added to the field "item_id" in the table feed. 

Am I doing something wrong or there is a bug here?

Thanks

**Comment by neil96** [comment]
Current now, we don't support item_id. If you really need this param, please open a [request](https://github.com/moxi9/phpfox-feature-requests).

**Comment by cespiritual** [comment]
Well, I can always add the information directly on the Feed Table or create my own function, and make it compatible with corrent and past version of V4. But you should allow that to work in a way that we can add information to all fields on feed table in future updates.

Thanks

**Comment by Data66PF** [comment]
Since the bug area is only for bugs, we cannot address a request such as this here. Please submit the feature request if you want something to be considered.
