### ISSUE TITLE
Video Upload Progress Bar Issue

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1399]
I'm using google chrom to view the latest version of phpfox. When you upload a video the progress bar freezes and does not tell user when video is finished uploading. Also does not forward user to page to set video title after video is uploaded.

See attachment
![screenshot 10](https://cloud.githubusercontent.com/assets/19175383/15002836/77ed919c-1173-11e6-8b65-2b182bd20058.png)

**Comment by ashdelacroix** [comment]
@queenmother305 I've had the same problem since v4. I can't see any reason for it, and it's like this on every browser I try.

**Comment by SalmanKhan86** [comment]
i am having same problem. pls fix it

**Comment by queenmother305** [comment]
Interesting this hasn't been marked as a bug yet, especially since there's a similar issue with the photo uploader. Could they be related?

**Comment by Data66PF** [comment]
Do you all have the same issue on the live demo? Noting to test with family safe videos.

**Comment by queenmother305** [comment]
I have not tried on the live demo. I will look into that today.

**Comment by Data66PF** [comment]
Ok here is the issue. I've tested a few videos. Some were too big but there was nothing saying that. Instead, it showed a loading bar but nothing completed. Using developer browser debug, I see a status 404 error for the videos that would not load. One was:
{
    "error": "Not a valid file extension. We only accept: 3gp, aac, ac3, ec3, flv, m4f, mov, mj2, mkv, mp3, mp4, mxf, ogg, ts, webm, wmv, avi"
}

That was for a .mov file.

Another did finally show an error but it was:
Upload failed. Your file (1 Mb) is larger then our limit: 1 Mb

This needs further testing to find the issue as the errors are not showing in most cases or the errors are not correct, or the proper file format is being used but is not recognized. 

All of that is at the demo for testing. Using chrome on a macbook pro.

**Comment by GreenMan123** [comment]
Please fix this error for file uploading". (  vid3o, photo, document.... )

**Comment by GreenMan123** [comment]
Also please add to upload multiple files at once for users who want to upload multiple photos, videos.....

**Comment by SalmanKhan86** [comment]
Please fix this error

**Comment by neil96** [comment]
Fixed by @RaymondBenc

**Comment by solutionall** [comment]
Hey How to enable upload video?

**Comment by neil96** [comment]
@solutionall Please ask questions on our [community](https://community.phpfox.com/forum/).
