### ISSUE TITLE
Impossible to create a poll

### ISSUE THREAD

**Issue by JulienHenchoz** [moxi9/phpfox#14]
On PHPFox v4.0.0 rc2, creating polls don't work.
After submitting my new poll, I'm redirected to "/index.php/poll/0/<Poll name>/" but the poll is not created in DB. 
Though, an event is created in feed "Julien Henchoz created a poll - January 1, 1970 12:00 am".

**Comment by lilman446** [comment]
Issue seems to be fixed as of 5/8/2015 and a " ? " if you didnt put one in originally.
