### ISSUE TITLE
Error with install apps phpfox v4

### ISSUE THREAD

**Issue by lkb123vn** [moxi9/phpfox#1401]
You can look at this vidueo :

https://www.youtube.com/watch?v=SI4KZamoYqs

I'm not sure there is no error . I checked through the host information . It supports upload very good . But I can not install apps - such as video modules . It seems to only allow installing apps online -modules more difficult to do it . No measures are allowed to install it offline as bad the other versions ?

**Comment by Data66PF** [comment]
As we don't see a license for that domain, please contact us at the client area to verify the domain is valid. https://clients.phpfox.com

**Comment by lkb123vn** [comment]
Sorry i use license for localhost to test .
