### ISSUE TITLE
Blog attached images are not shown 

### ISSUE THREAD

**Issue by supreshc-persistent** [moxi9/phpfox#1405]
Attached images to blog content are not shown to other user besides its author itself

**Comment by neil96** [comment]
Can you reproduce this issue on our [demo](https://v4.phpfox.com/)?

**Comment by supreshc-persistent** [comment]
cannot add blog on demo site add blog redirects to
https://v4.phpfox.com/subscribe/

**Comment by neil96** [comment]
@supreshc-persistent I updated permission, please try again.

**Comment by supreshc-persistent** [comment]
https://v4.phpfox.com/blog/1032/test-blog-09051  

there is attachment for this blog but its not displayed if i view it without logged in

**Comment by supreshc-persistent** [comment]
How can i apply the fixed changes to my code?

**Comment by neil96** [comment]
@supreshc-persistent please wait version 4.4.0 release.

**Comment by segunmentis** [comment]
Hello, blog images are showing broken links in the general blog index page on version 4.3.2. How can i fix that?

**Comment by Data66PF** [comment]
That is not part of this bug and that is working as designed.
