### ISSUE TITLE
Mobile Photo Uploads Sideways

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1406]
Seems like most, maybe even all mobile users photos upload sideways. I am constantly having to rotate their photos. It is very time consuming for large sites with alot of members.

**Comment by queenmother305** [comment]
I should also mention mobile users are uploading the same photo two and three times which lets me know the upload routine needs to show progress to mobile users so they know their photo has completed being uploaded. Otherwise they assume it wasn't uploaded and they keep uploading it over and over. It is bad. I'm rotating and deleting over 100 photos per day.

**Comment by neil96** [comment]
Could you give us more detail about your problem. Thanks!

**Comment by queenmother305** [comment]
Yes I have noticed that the problem only appears to be with profile photos. I'm assuming the issue is mobile because I have tested profile photo uploading in all desktop browsers and it appears to be working fine. This morning when I woke up I literally had a dozen photos that I needed to rotate. The strange thing is the photos appeared to be correctly positioned in the users profile avatar but in the photos section avatar and when you click on the image itself it is sideways. It is very annoying because I have a high volume site. Out of 1,000 members that joined in the past 2 days, I have had to correct about 15% of their profile photos. I'm not sure if it's a specific phone causing the issue, or a specific file type, but whatever it is its popular and needs to be addressed. I should also note that people are uploading the same photo MANY times. They are not receiving confirmation the first time their profile is uploaded. So they continue to upload and upload thinking it's not working. I spent an hour this morning deleting duplicate photos. I have also noticed when i attempt to rotate the photos sometimes the rotation freezes mid-routine and never completes, then the photo disappears from the photo gallery. I would post screenshots but as my site is adult themed I wasn't sure if I should post it here. Can I post screenshots?

**Comment by Data66PF** [comment]
This used to be an issue in v3 with iPhones. At that time, it was fixed and servers needed exif_read_data https://community.phpfox.com/forum/thread/49553/unable-to-upload-photos/ but @RaymondBenc might recall why we had to change it back or what the issue was with mobile and sideways photos.

**Comment by queenmother305** [comment]
it's so strange data. their avatar looks normal. but the actual photos are all sideways. i'm literally spending 2 hours a day rotating photos. it's driving me nuts. very time consuming! perhaps this configuration you speak of is why users are not knowing their photo upload has completed as well. because they are uploading their profile photo over and over. i keep having to delete photos. there has to be a fix. iphones are among the most widely used mobile phones on earth.

**Comment by Data66PF** [comment]
It was hosting related so the one thread I linked might help and the exif_read_data() issue if your server does not have it enabled.

**Comment by Data66PF** [comment]
Confirmed at demo from an iPhone 5c. 
https://v4.phpfox.com/profile-2614/  note the turtle is in the right position on the actual profile photo. That is how it looks on my phone too.
![profile](https://cloud.githubusercontent.com/assets/6908282/15180133/bcad8802-174d-11e6-8481-abbdf44d4932.png)

However, look at the image in the feed and you will see it sideways and here in the photo section https://v4.phpfox.com/photo/3094/may-11-2016/

**Comment by queenmother305** [comment]
I'll look into that. If exif_read_data() is required for v3 to work properly then I think I probably already have it enabled because I am running my v3 site using my second phpfox liscence on the same server and I have never had this problem with v3. Anyway I uploaded a screenshot of the photo gallery this morning. I blurred out the adult content. Please note that all users circled are different users. This problem makes the site look really bad if you have a high volume community because it happens constantly. 
![screenshot 30](https://cloud.githubusercontent.com/assets/19175383/15180232/4a250016-174e-11e6-8812-5eb76cb2f52a.png)

**Comment by Data66PF** [comment]
But I already mentioned that this is a bug and provided an image.
