### ISSUE TITLE
Non active pages still on menu throws page not found

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1407]
Pages that are non active are still visible on the menu and throw a page not found when clicking on link.

**Comment by neil96** [comment]
Did you mean module pages (same with issue #1371) or the page you add in adminCP?

**Comment by darksolar1** [comment]
It's the one you add in admincp

**Comment by Data66PF** [comment]
I'm not able to reproduce this. I made a page in admincp >> pages. It showed fine on the front and in the menu. I then deleted the page and cleared cache. The menu disappeared once cache was cleared. Tested on live 4.3.2 development site.

**Comment by darksolar1** [comment]
No don't delete it, just disable it. Where it says, "active" just select, "no"
