### ISSUE TITLE
Important Settings Missing

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#141]
In the AdminCP the main important settings are not visible... (ie; Settings, Extensions, Products, Modules, Emoticons, etc.) We need these setting for Site Identification, functions, and appearance...

**Comment by Data66PF** [comment]
Modules are found in Maintenance
Settings is already there as Settings
Please see my bug report and add to it for further items #64 so he can get them all in one sweep. :)

**Comment by Data66PF** [comment]
There is a free app for emoji. I believe the other emoticons were disabled.

**Comment by TrueAmericans** [comment]
Apparently they don't work either... They don't show up anywhere on the site...

**Comment by Data66PF** [comment]
They work on the phpfox community site.
