### ISSUE TITLE
Some buttons do not work.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1410]
Some buttons in version 4.3.2 - b3 are inactive, such as the menu settings, the choice of language and others. By my own investigation I found a mistake in the address file template.class.php PF.Base \ include \ library \ phpfox \ template in 1600 line. If you replace this line to the line from the same file of version 4.3.0 - b2, then the problem disappears. 
![error 1600](https://cloud.githubusercontent.com/assets/15389101/15112883/b6019b24-15f9-11e6-8a33-dfdee9628897.png)

**Comment by neil96** [comment]
Note: This is a issue only on window.
