### ISSUE TITLE
Important Issue on Pages

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1412]
I have created a page on demo that i have created several weeks ago. Today I have added a cover and changed the name of the page, the Vanity URL and finally invited 5 firends and I got this error: **{"error":404}** . Now the page is damaged and is inaccesible.

URL of the page: https://v4.phpfox.com/apps

If I go to my Profile >> Pages >> And access the page this is what i get:

![Screenshot](https://v4.phpfox.com/PF.Base/file/pic/photo/2016/05/c86b3640ae9c665fb201c0864ec38d91_1024.png?t=573195598e9af)

**Comment by Data66PF** [comment]
The demo content is deleted automatically except for staff content. Are you sure the page still exists? Please do not use the demo for permanent content due to the nature of it refreshing to remove any possible spam.

**Comment by Data66PF** [comment]
This causes the script to have issues if we allow a name such as Apps as we have default Apps stuff. I have tested at the demo and my live testing site by making a page Apps (front end page) and then changing the vanity url to Apps. It produces the page not found issue. We need to show an error when users try to make pages that are part of our core terms/phrases/modules/features etc

**Comment by Spaninet** [comment]
You shoulds also show an error/message when trying to use reserved words in the scritp (urls, name of pages, apps...) as username.

Ex.: A user can sign up using "logout" as username. When you are loged in and try to go to profile (http://Site.Com/logout) you can't because the script logs out.
