### ISSUE TITLE
Photo not loaded when edeting a poll

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1413]
## Poll page
![](https://v4.phpfox.com/PF.Base/file/attachment/2016/05/c42ac25181459641405ebf1a1aaba334.png)
## Editing a poll
![](https://v4.phpfox.com/PF.Base/file/attachment/2016/05/f0d36306491d7fa7e0fb0c00483685e8.png)

**Comment by Data66PF** [comment]
As our demo content deletes after x hours, there could be an issue for that. Do you see the same issue on a new poll you make and then edit?

**Comment by erick260** [comment]
I've  also noticed this,  and waited for days. That Not Found Image is still their.

**Comment by Data66PF** [comment]
Yes but we need to know if it happens on a new one as our demo is set to delete everything other than staff stuff after x hours/days. This means that all photos other than staff, and some other content, is deleted. Please let us know if you make a new one and immediately edit it, if you have the issue.

**Comment by Data66PF** [comment]
Confirmed on my own testing site
