### ISSUE TITLE
Cannot  sponsor feeds

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox#1414]
We cannot sponsor feeds in 4.3.2

**Comment by Data66PF** [comment]
I am able to sponsor an item on my 4.3.2 dev site. I have the user group allowed to sponsor in feed. I go to a photo and click the options thing to bring up the various options and choose Sponsor in Feed.
It shows processed.

I then look at the main feed and it is sponsored in the feed.

Please provide full testing details as we request in our instructions for posting bugs.
