### ISSUE TITLE
Friends Dropdown Closes Each Time You Accept A Request

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1415]
I am using google chrome. I noticed when you attempt to accept a friend request in the dropdown it closes the drop down every time you accept someone. You end up having to open it over and over and over again. Also there is no link at the bottom of the dropdown to go to the friends request page so you can accept multiple users simultaneously. If someone has 100 requests they have to sit there and keep reopening the drop down and accepting requests 1 at a time. See attached.
![screenshot 31](https://cloud.githubusercontent.com/assets/19175383/15181297/794a4ec2-1754-11e6-85ee-74e16c8f9b58.png)

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-feature-requests/issues/12
