### ISSUE TITLE
Search Members

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1417]
Hi When a search is done for members in a country if no members are in DB page returns a blank response as if no search done should return a No members found report. Have not checked for ages, sex etc but any search with no results should return a No results found message.

**Comment by Data66PF** [comment]
https://v4.phpfox.com/user/browse/?search%5Bgender%5D=&search%5Bfrom%5D=&search%5Bto%5D=&search%5Bcountry%5D=AW&null=1&search%5Bcity%5D=&search%5Bzip%5D=&search%5Bkeyword%5D=&search%5Btype%5D=0&search%5Bsubmit%5D=Search&custom%5B1%5D=&search%5Bsort%5D=u.last_login&search%5Bsort_by%5D=DESC  confirmed
