### ISSUE TITLE
Incorrect formatting blog

### ISSUE THREAD

**Issue by websistema1** [moxi9/phpfox#1418]
#I have updated the site (4.3.2 build 4). After update "null" no error. A new bug in blogs - some parts of the text have the incorrect format. After refreshing the page (F5) - the text can be read.

![blog1_error](https://cloud.githubusercontent.com/assets/14079310/15236376/7d1910a0-18cc-11e6-88a5-17b78ace5ecb.jpg)

**Comment by Data66PF** [comment]
Can you post a sample blog at our demo and see if it works? https://v4.phpfox.com and please use the language you are having an issue with.

**Comment by websistema1** [comment]
Look - a reference to the demo site blogs (4.3.2 build 4):  https://vsitut.com/development/blog/

**Comment by websistema1** [comment]
I tested. The error occurs on the blogs before updating. New blogs after renovation work without error. Ticket can be closed. Thank you for supporting the developers of multilingual customer! :+1:
