### ISSUE TITLE
Incorrect formatting of the text

### ISSUE THREAD

**Issue by websistema1** [moxi9/phpfox#1419]
Updated to version 4.3.2 build 4. The error manifested itself again. It may appear on the wall of the site, names of people, in blogs, in the music section. Not all users have the bug. After removal of the incorrect text - error disappears. After refreshing the page (press F5 key) - a mistake, too, disappears.
The error is the same as in:
https://github.com/moxi9/phpfox/issues/461
https://github.com/moxi9/phpfox/issues/1418

![muzic_error](https://cloud.githubusercontent.com/assets/14079310/15292361/74b5421e-1b8b-11e6-8504-e8e05cb44ce0.jpg)

**Comment by websistema1** [comment]
Dear developers! I thought that this error will not happen. She reappeared. Do not be indifferent. Solve the problem please.

**Comment by neil96** [comment]
Could you give us detail steps to reproduce this issue. I can't reproduce it on my dev site.

**Comment by websistema1** [comment]
I installed the demo site: https://vsitut.com/development/ . Go to the blogs or videos - everything is visible. On the main site ( https://vsitut.com ) I delete text that contains unformatted text (errors).

**Comment by websistema1** [comment]
What changes do you need to do to fix this? Or do I have to wait for version 4.4.0?

**Comment by neil96** [comment]
Please wait version 4.4.0 release.

**Comment by SalmanKhan86** [comment]
when it comes
