### ISSUE TITLE
Bug in Server Settings Affects Photo Uploads

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#142]
I discovered there's a bug in the Server Settings "Use getID3 for Files Uploaded" and if set to true, you can't upload photos... If you turn it off, you can upload photos... This has been the whole problem that caused me to reload the site several times... Now ya know what needs fixing on that...

**Comment by Ylmzef** [comment]
Upgraded to 4.0.4 but still having this issue.

**Comment by TrueAmericans** [comment]
I have tested and have no problems uploading photos or avatars after upgrading to 4.0.4, so the problem others are having has to be because they still have getID3 active in their file uploads active...

**Comment by Ylmzef** [comment]
If the getID3 function not working its a bug than.
Disable the feature is not solution.

**Comment by Jinkers** [comment]
@ylmzef, that feature has been depreciated and no longer in use.

**Comment by TrueAmericans** [comment]
Maybe so, BUT, it's still there... I disabled mine in the Core settings before it was ripped to shreds... Anyone else will have to do it in the database... It is the only way to do it now... It still shows in the database settings...

**Comment by Jinkers** [comment]
Im 100% sure they can have a few lines of code that will clean that up during the next update should it be totally necessary.

**Comment by TrueAmericans** [comment]
It's necessary... We've already verified that... Even data66 identified it as a good find when I discovered it...
