### ISSUE TITLE
Relationships In Profile update reg.

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1421]
When a member sets relationship status there is no label to block and no instruction. If a leter for name is entered it does not show and block does nothing for avatar. This needs to be improved as it is extremely confusing and of no real help to members. see image
![2016-05-17 11_15_02-edit profile _ bdsm dating kink fetish bondage and kink social dating for b](https://cloud.githubusercontent.com/assets/13656046/15317453/d96a53ac-1c21-11e6-8ed3-e934c744396d.png)

**Comment by neil96** [comment]
![screen shot 2016-05-17 at 17 52 41](https://cloud.githubusercontent.com/assets/15936115/15319983/3244c5f8-1c58-11e6-936a-3ce7c82cb4fd.png) 
It's working fine with default theme. Your problem might text and background are the same color.

**Comment by one44** [comment]
Ok will recheck as another user reported same bug in community.

**Comment by one44** [comment]
No is an issue as phrase is missing same on phpfox demo site.

**Comment by neil96** [comment]
I checked on the demo. The phrase "user.search_friends_by_their_name" have been used in this case. Please check if it exists on your site.

**Comment by Data66PF** [comment]
Remember to always run "find missing phrases" for every update to your site. Always also ensure that if you have a language pack, that the developer of that pack included the default English phrase as it can delete the phrase if it didn't. I've seen this on sites before as a blank English text in the translation deleted the master English phrase because it set it as blank.

**Comment by Data66PF** [comment]
Checked on my dev site with default language and default theme. Works fine as on the demo. This is a site issue.

**Comment by Data66PF** [comment]
Reopened and bugged. I tested with a registered user in firefox with default theme. This isn't working on that account. It works on my admin account. Weird bug.
