### ISSUE TITLE
Friends Showing in Friends Block after deleting them

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1422]
I deleted all friends but they still showing in friends block in profile.

**Comment by neil96** [comment]
Please try clearing the cache and try again. We store cache most of the data to improve performance of site.

**Comment by Data66PF** [comment]
Cannot reproduce this. I logged in as a registered user that had a few friends. I deleted them from the Manage Friends page. I then go to my profile and the friends block is gone as I have no friends to show. I also logged in as admin user and went to that profile and no friends show. v4.3.2 latest build

**Comment by Spaninet** [comment]
I think that issue was due to browser cache.
