### ISSUE TITLE
Duplicate appending of listed features when entering subscription feature compare list

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1423]
Subscription feature compare entry screen is replicating and appending entire duplicate lists to itself after periodically saving while I continuing to move on making further entries.  Having entered less than 20 features for compare, I already have repeating pattern of appended lists of redundant features more than a hundred, perhaps hundreds(s) of items long.  Used Firefox latest.

**Comment by Data66PF** [comment]
Please provide a screenshot and step by step to reproduce this.
