### ISSUE TITLE
Adding categories to compare features lists.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1425]
Adding a category level to subscription features list would allow better communication of feature sets by clustering in web services such as:

Privacy
User to User
Private Messaging
Blog
Forums
Audio
Video
Ads
Marketplace

etc.  This would minimize the mental effort of potential users and help them avoid getting lost by attempting to digest and relate features in a long list to whatever categories they are innately interested in. By including a category level (which means features listed/clustered by category, not category list they have to click on first) they can proceed quickly to view features in categories that are important to them which will make it easier for them to decide (which means more conversions for the site).

**Comment by Data66PF** [comment]
Please note that feature requests should be in the feature request area. If this is not a bug, please close and put in the feature area.

**Comment by Data66PF** [comment]
Please post feature requests at our feature area. https://github.com/moxi9/phpfox-feature-requests
