### ISSUE TITLE
Subscription compare features list displays permissions in reverse order during registration.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1426]
For subscription packages 1, 2, 3 and 4 (1 having the least and 4 having the most permissions), the permissions given during setup displayed in reverse order when accessing the compare during the registration process.  The 1 package showed permissions I intended for 4 during signup.  4 displayed permissions intended for 1.  2 and 3 were reversed also.

**Comment by Gatsby-PF** [comment]
It looks as though this might not be a reversal as previously said as the attached image illustrates.  Adding background colors to each subscription revealed another layer of this issue that suggests rows are being rotated either from the html template or whatever is driving it.  I am suggesting that correcting the random row rotations will also correct the check, but both should be nonetheless verified.
![permutation](https://cloud.githubusercontent.com/assets/14284710/15379682/3504b110-1d5f-11e6-9bcb-576df4d69116.png)

**Comment by Gatsby-PF** [comment]
Also please take note of the irregular column width.  They should be exact percentages.

**Comment by Data66PF** [comment]
Can you please show the left column of names? Do you want this reopened? You seem to have closed it.
