### ISSUE TITLE
Subscription compare list readibility/usability suggestions

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1428]
A few enhancements would greatly enhance viewer friendliness in the subscription compare list over and above that mentioned elsewhere in the issues tracker.

Use subtle even/odd highlighting on the feature rows.

Where empty spaces exist instead of check marks, use a red X or slash through circle graphic to indicate "not" so it doesn't look like something is amiss like missing teeth.

The word subscribe should be default instead of purchase for the package links as some subscriptions may be free.

When a subscription has zero price (free), clicking on the purchase/subscribe link for that package should not take you to the payment gateway like it does now, but should resume the registration process as normal.

**Comment by Gatsby-PF** [comment]
As for the red x, the compare.html.php file is referencing accept.png and cross.png which exist in PF.Base\theme\frontend\default\style\default\image\misc
So this looks like the red cross was intended to display, but does not despite its being reference in the html and its presence in the above directory, therefore is a bug.

**Comment by Data66PF** [comment]
This is only for bugs and one at a time. If you mean we need to enhance, then that would be feature request for the feature tracker, one at a time. We cannot have more than one per issue as we have internal revision numbers for each item.

**Comment by Data66PF** [comment]
Please submit one at a time here https://github.com/moxi9/phpfox-feature-requests
