### ISSUE TITLE
Subscription compare mobile display not responsive

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1429]
Don't know how a compare display with X many side by side columns should even work in mobile view, as to display them serially vertical (one plan after another) defeats the concept of a multi column compare. 
One way may be to create mobile template and show in this format
(substitute Yes for checkmark graphic, no for red x):

Can create private forums
Plan 1     Plan 2     Plan 3     Plan 4
   No         Yes         Yes         Yes

Business related commerce in marketplace
Plan 1     Plan 2     Plan 3     Plan 4
   No          No          No         Yes

etc.

**Comment by Data66PF** [comment]
You can see this on my dev site, for our devs I mean. Used an iPhone 5c and went to my dev /subscribe/compare and cannot see the chart as it is not responsive.
