### ISSUE TITLE
[Profile Content] Members Told Me HTML Isn't Being Recognized In Profile Blocks

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#143]
Is there a setting I can't find or not there yet that would allow members to use HTML in their profiles? I know a version of PHPFox I used years ago allowed customization of a lot of things, including HTML.

**Comment by RaymondBenc** [comment]
By default ,HTML is disabled and there is no visible setting to enable this.

However, we are releasing a free app for those that wish to continue to use HTML on their sites. App should be ready this week.

**Comment by Jinkers** [comment]
Will this app allow for site wide HTML usage, or just for users to create content?
