### ISSUE TITLE
Feed Delete Problem relating to #tag

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1430]
when we delete feed relating to #tag then hash tag data is not removed from table. hash tag still showing in trending topic when there is not any feed relating to it.
![hasg tag problem](https://cloud.githubusercontent.com/assets/13433124/15394788/7f840e50-1df2-11e6-9b9e-10276cff6ff4.png)

**Comment by Data66PF** [comment]
Tags are cached. Does it still show after you clear cache?

**Comment by SalmanKhan86** [comment]
Yes

**Comment by Data66PF** [comment]
I think a core dev needs to check as the cache deletes from the db cache at the set interval (if I recall correctly) so I think it will clear after the cron runs for that. Will try to remember to look at my test site tomorrow.
