### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by iogames** [moxi9/phpfox#1431]
Here in:

http://MYSITE.com/v4/index.php/admincp/setting/edit/?module-id=user
the last option: "Require basic field" + details are not included for translation

http://prntscr.com/b60mnj

and while we are it, all the YES/NO options in settings are missing for translation too:

http://prntscr.com/b60n8i

**Comment by neil96** [comment]
All of them already phrases.

> "Require basic field" + details are not included for translation
It use phrase **user.setting_require_basic_field**. With setting, we use 1 phrase for both title and info.
> all the YES/NO options in settings are missing for translation too:
Yes and No in adminCP use phrase **core.yes** and **core.no**
