### ISSUE TITLE
Cant comment on main photo feed

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1433]
Hello :) 

 so when your on the home page , you can comment on satus's, but you cant comment on the photo' feeds you have to click onto them to comment on them,

I think there should be a comment section on the photo feed so you dont have to click on the photo to comment on it 

![image](https://cloud.githubusercontent.com/assets/16384395/15413236/09a9b6f6-1e26-11e6-85d7-eeb9743522f9.png)

**Comment by Data66PF** [comment]
I can comment on all photos added. Perhaps it is a theme issue. Please try with default.

**Comment by Lukey199223** [comment]
It works on the demo :) , I tested last night on the demo and it wasn working (maybe my laptop was playing up) but its working today :) , its probably just a simple Javascript issue in my site , I'll have a gander :)

**Comment by Lukey199223** [comment]
thanks Donna :)

**Comment by Data66PF** [comment]
Ok thanks for updating. Note that you can also close issues that you open, in the future, but I'll close this one for you.

**Comment by Lukey199223** [comment]
:)  thank you :)
