### ISSUE TITLE
sponsored Ad bug 

### ISSUE THREAD

**Issue by vizruta** [moxi9/phpfox#1436]
phpfox version :  V4
browser : all
i create a sponsored ad from a normal registered user and adjust time as per my need ...for example iam creating ad at 10am and i place the time to 10:30 and submit and when i check from admin account i see that the ad where the time was set to 10:30am will be changed to 15:47 and no matter what i try to do it wont change back to 10:30am from admin account also... is this a bug

**Comment by GreenMan123** [comment]
Have you checked the server time?

**Comment by Data66PF** [comment]
Confirmed. It is not using the proper time no matter what I do. I got the same results. I even made sure my site time zone was correct. I checked my user time zone and it was correct.
