### ISSUE TITLE
User defined blocks not positioning properly in visitors screen

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1437]
In core.members page, the friends online block uses block 1, and the activity feed uses block 2.  Block 2 (activity feed) centers properly between the friends online block and the Trends block in the right column.  These are all phpfox standard blocks.

In the visitor page however, there is a user defined block 1 in the left column, and an ad in the rightmost column, and when I attempt to use custom block 2 expecting it to take center position between the left column block and right column ad (as it does with these blocks in the core.members page), It instead justifies block 2 to the left of the screen and superimposes its content over the left blocks content (uses transparent background so is easy to see).

Please try this to see if you can duplicate it.

**Comment by neil96** [comment]
In visitor page, you can't add to middle block (block 7, 2, 4).

**Comment by Gatsby-PF** [comment]
That severly limits visitors page block customizability outside of the standard image/featured photo provided for in index-visitor.class.php for those of us who want something better that just a photo.

**Comment by neil96** [comment]
You can request this feature [here](https://github.com/moxi9/phpfox-feature-requests/issues)
