### ISSUE TITLE
Neutron theme problem (nav menu disappearing when clicking messages etc 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1439]
Hello :)

I've had this problem before,but then it fixed itself for a while now its back 

when you click the "messages,Notifications etc or go to another page, the navigation menu disappears

I'm using Neutron v4.3.2 build 3 , I've had the problem for the last few months 

thank you :)

![image](https://cloud.githubusercontent.com/assets/16384395/15557922/0b19c57e-22ce-11e6-92de-c8705887ac24.png)

**Comment by Data66PF** [comment]
Please be sure when posting bugs that you are also on current version.

**Comment by Lukey199223** [comment]
I'm almost sue, I am on the latest, build 5 is the latest, right ? :) 

I cant test it on the demo because the demo theme is bootstrap and obviously i'm using neutron aha, but ye the problem has been with the theme for about 3 months 

if we could possibly Keep this open, I'll double check to see if I'm on build 5, and test it :) 
thank you :)

**Comment by Lukey199223** [comment]
I wasnt on build 5 , I've upgraded and its still the same, the menu still dissipaters

**Comment by Lukey199223** [comment]
is there going to be a theme fix for this in 4.4 ? :) as the problem is sill in build 5 :)

**Comment by kizzel777** [comment]
I have the same issue. It's really annoying. Can't get it to stop.

**Comment by Lukey199223** [comment]
it is really annoying, I hope they can fix it or 4.4 :)

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.
