### ISSUE TITLE
when in music and adding featured music song, you select featured song link and share doesnt work

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1441]
after adding a song whether just clicking on the song and then trying to share, the pop up shows but nothing to share to ( WALL ) ??
same with featured songs, can't share even from home page
![share-in-music-not-working](https://cloud.githubusercontent.com/assets/17736688/15566280/8cee4072-22e5-11e6-8319-aaba19b8e1c4.JPG)
![when-adding-a-featured-song-then-clicking-on-the-link-try-to-share-but-not-working](https://cloud.githubusercontent.com/assets/17736688/15566285/99332c30-22e5-11e6-93e8-a679390e576f.JPG)
![share-still-not-working-for-music](https://cloud.githubusercontent.com/assets/17736688/15566293/a963f012-22e5-11e6-8ba2-9f89b113ac6e.JPG)

**Comment by neil96** [comment]
Duplicate with #1379 & #1261
