### ISSUE TITLE
when feture a song or unfeature a song we need to refresh for update to take place ?

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1442]
here is photo. i select edit and feature the song it doesn't add until i refresh.. when edit again and
![if-feature-song-or-unfeature-song-we-have-to-refresh-for-changes-to-take-place](https://cloud.githubusercontent.com/assets/17736688/15566708/fcf69502-22e7-11e6-9154-068cd730b049.JPG)
 unfeature song, again need to refresh to make change, should make change on its own without refresh

**Comment by neil96** [comment]
It's working as our designed.
