### ISSUE TITLE
title in video in another lang not showing characters correctly see photos

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1443]
videos from youtube - not cdn - characters are not shown in greek format ?
see photos below
![how-to-set-title-in-video-to-view-correct-characters-in-other-lang](https://cloud.githubusercontent.com/assets/17736688/15567092/f41311c0-22e9-11e6-88d1-21b305692a8c.JPG)
![how-to-set-title-in-video-to-view-correct-characters-in-other-langs](https://cloud.githubusercontent.com/assets/17736688/15567091/f41248bc-22e9-11e6-8d2d-61ae4dd9f5c3.JPG)

**Comment by neil96** [comment]
Are you testing on 4.3.2build5? 
If not, it duplicate with #1352

**Comment by spirogg** [comment]
I upgraded to . 4.3.2build5 . Sorry Was up so late all of my requests were with the update. It's Greek lang.

**Comment by spirogg** [comment]
Question ? - when you all fix something. Should we delete and re add videos or a blog post or whatever he issue maybe ? So we can test it is working. ? Or should it just work with what we have already ?!

Thanks

**Comment by neil96** [comment]
For this issue, we can't fix for already video on your site, just for new video. You can fix maunal by edit each old videos. Sorry for this inconvenient.
