### ISSUE TITLE
in pages - creating a blog, wording - emoji's do not wrap wording falls of pf the container

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1444]
in pages - creating a blog, wording & emoji's do not wrap wording falls out of the container

see photo
![in-pages-create-b og-after-all-done-we-try-to-preview-words-are-falling-out-of-container](https://cloud.githubusercontent.com/assets/17736688/15568041/70449430-22ef-11e6-9cc2-4cb0df3059c2.JPG)

**Comment by neil96** [comment]
Duplicate with #1389
