### ISSUE TITLE
[AdminCP-Store] I can't view Purchase History from AdminCP

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1445]
I cannot view the Purchase History from AdminCP.
I have enabled two-step verification.

When I try to see my Purchase History, I recive an email with a PIN, but when I put it in the AdminCP to login i get this error:

**Provide your license key.
Provide your license ID.**

Version: 4.3.2b5 Premium Installation

**Comment by Data66PF** [comment]
When you enter the id and key, does it work?

**Comment by Data66PF** [comment]
I cannot reproduce an issue. Please try again as we changed something in the store recently.

**Comment by Spaninet** [comment]
The issue doesn't appear now because the login was removed (incluiding the two-sep log in) from the store (https://store.phpfox.com/login).
