### ISSUE TITLE
Enter button doesn't work sometimes in some input boxes

### ISSUE THREAD

**Issue by kosytedy** [moxi9/phpfox#1446]
Enter button (key) doesn't work sometimes in all comment boxes and message box that pops up when you click 'Send message' in someone's profile page. I think a clear 'Send' button should be added. This also posses great threat to those using Opera mini mobile browsers as javascript doesn't work in the browser. But once there is a submit button, it eases everything. Thanks.

**Comment by kosytedy** [comment]
This happens mostly when using mobile browsers.

**Comment by GreenMan123** [comment]
Yes

**Comment by GreenMan123** [comment]
Please fix this is also happing in my site. Opera mini is the mosy usef browser

**Comment by neil96** [comment]
Our platform don't support Opera and Opera mini. You can refer to the list of supported browsers [here](https://docs.phpfox.com/display/FOX4MAN/Supported+browsers).

**Comment by kosytedy** [comment]
Please, I said 'it ALSO affects opera mini browser users', and not 'ONLY'. I'm not using Opera browser and yet I still experience the problem.

**Comment by neil96** [comment]
Could you give detail steps to reproduce?
