### ISSUE TITLE
[4.3.2b5] Cancel Option is not working

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1447]
The account cancellation option does not work for regular users (those who register directly or via facebook app) without admin rights.

![](http://i.imgur.com/zFUU8Fl.png)

- I haven't tested with Admin account.

**Comment by neil96** [comment]
I can't reproduce. Could you give us detail steps, thanks!

**Comment by Data66PF** [comment]
I can reproduce this on my dev site. The user has not entered a birthdate. Recaptcha is enabled. The password is correct. My user is a normal user registered via the standard registration form (not by facebook).

I click to cancel as a registered user.
I select a reason to cancel.
I don't fill in the extra text box.
I enter my password.

It shows as the above image.

I even changed my password and that worked fine to change the password. I then tried again and still get the error of invalid password.

**Comment by Spaninet** [comment]
Thanks @Data66PF for reproducing the issue.

**Comment by neil96** [comment]
This issue only happen with old users (created from v3)
