### ISSUE TITLE
[4.3.2b5] Cancel Account Page Style Issues

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1448]
![](http://i.imgur.com/zFUU8Fl.png)

Of the three profile photos, one is bigger than other two.

![](http://i.imgur.com/PV1Tm9L.png)

The two inputs are bigger than the screen on MOBILE.

- Tested in latest Chrome and Firefox for Android.

**Comment by neil96** [comment]
> The two inputs are bigger than the screen on MOBILE.

It's not bigger than the mobile, they just haven't padding.

**Comment by Spaninet** [comment]
No, it's not only the padding. On default Android browser the width of text area is twice the screen size. In latest Firefox and Chrome doesn't fit in the box.

![](http://demo.tecnobina.com/1.jpg)

**Comment by SalmanKhan86** [comment]
same problem found by me
