### ISSUE TITLE
cant upload multiple video's/photo's on status updates

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1449]
Hello :) 

so you can upload multiple photo's on the main Photo's page, but can only select one when uploading via a status update

we should be able to upload multiple using the status option seeing as we can upload multiple via the main page 

I dont know if this would class as an enhancement or not

**Comment by neil96** [comment]
This is an enhancement. Please request a new feature [here](https://github.com/moxi9/phpfox-feature-requests/issues).

**Comment by Lukey199223** [comment]
Sorry Neil I'll do it now :) , sorry, been super busy haha
