### ISSUE TITLE
Search Box Doesn't Show Pictures

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#145]
I don't know if this is an error or if this function is just underdeveloped...

![searchboxfail](https://cloud.githubusercontent.com/assets/13330878/8763700/4f6037c8-2d78-11e5-8128-7ddae2b55142.jpg)

**Comment by RaymondBenc** [comment]
fix https://github.com/moxi9/phpfox/issues/146

**Comment by orgazilla** [comment]
I uploaded the latest PHPfox files and this is now fixed!
