### ISSUE TITLE
Registration text is nearly same color as background

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1450]
If you enable DOB, gender etc.... the registration text is nearly the same color as the background

**Comment by spirogg** [comment]
Same here.

**Comment by neil96** [comment]
Could you give us some screenshots. It's working with default theme.
![screen shot 2016-05-30 at 09 39 14](https://cloud.githubusercontent.com/assets/15936115/15638415/835ca342-264a-11e6-962d-971f06c7cb1f.png)

**Comment by spirogg** [comment]
here are some snapshots updated to latest a couple days ago
![registration-page-cannot-read](https://cloud.githubusercontent.com/assets/17736688/15639250/10a68b20-25ef-11e6-849e-b0d23d635d6a.JPG)
![registration-page-cannot-read-1](https://cloud.githubusercontent.com/assets/17736688/15639252/160dc632-25ef-11e6-84af-c39944125fcd.JPG)
![registration-page-cannot-read-2](https://cloud.githubusercontent.com/assets/17736688/15639253/192271d8-25ef-11e6-86dc-bc4dbb9c1711.JPG)

**Comment by spirogg** [comment]
![registration-page-cannot-read-3](https://cloud.githubusercontent.com/assets/17736688/15639290/803f03a4-25ef-11e6-90f2-31e776b9b7e5.JPG)
![registration-page-cannot-read-4](https://cloud.githubusercontent.com/assets/17736688/15639288/80383de4-25ef-11e6-8d9f-f90dfa9274c9.JPG)
![registration-page-cannot-read-5](https://cloud.githubusercontent.com/assets/17736688/15639289/8039628c-25ef-11e6-84f9-a7522b12ffc9.JPG)

**Comment by spirogg** [comment]
is there a color setting for wording ( characters in registration to make them white ?

**Comment by spirogg** [comment]
Thanks neil96 :+1: :100:
