### ISSUE TITLE
Feed Ajax Load Error

### ISSUE THREAD

**Issue by toorta** [moxi9/phpfox#1453]
Some feeds (especially status updates) are not be able to load via ajax loading. Example code to load feeds:
`{% for feed in feeds %}
    <div class="feed_stream" data-feed-url="{{ url('/feed/stream', {'id': feed.feed_id}) }}"></div>
{% else %}
    <div class="message js_no_feed_to_show">{{ _p('There are no new feeds to view at this time.') }}</div>
{% endfor %}`

Please check the following image for the error:

![feederror](https://cloud.githubusercontent.com/assets/8483463/15628784/030bc822-2513-11e6-948f-dd40e1ca534f.png)

**Comment by neil96** [comment]
Could you give us a demo site to reproduce? I can't reprodcue with information you gave. Thanks!

**Comment by toorta** [comment]
Actually I have got this issue on a customers website. There may be another issue with other modules. I am closing the issue now. I will return if I get in my own demo. Thanks for your time...
