### ISSUE TITLE
custom gender did not import during upgrade.

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1455]
my v3 had a 3rd custom gender. after my upgrade i noticed that the profiles that were orginally marked as that 3rd gender have a blank space next to where their gender should be, you also do not have the option to search the 3rd gender on the browse page. but when i look in my admin panel the gender i created is there, it's not missing.

**Comment by neil96** [comment]
On v3, How did you add a new gender? Add from adminCP, use third-party app or other way?

**Comment by queenmother305** [comment]
I did it within the admin panel of V3.

**Comment by Data66PF** [comment]
I had Neutral for a gender on my dev site and it's still there after the beta upgrade. The users using that one for testing are still showing up.

**Comment by Data66PF** [comment]
Please test once we release RC version.
