### ISSUE TITLE
videos can still be watched in the feed by prohibited user groups.

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1456]
in the video app when you set "usergroup can watch video" to NO, the usergroup can still watch the video in the feed. if a usergroup is not supposed to be able to watch videos, it should include videos in the feed. when they click a video in the feed they should be redirected to the subscribe page just like they are when they attempt to watch a video on the main video index page. this is extremely important due to the added cost of zencoder and amazon now associated with the video app. every video stream costs the site owner money. this needs to be fixed.

**Comment by neil96** [comment]
This issue fixed on 4.4.0
