### ISSUE TITLE
German umlauts and Smilies

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1457]
There is a change in phpfox.class.php that breaks germanumlauts and smilies in the feed. it is only an issue when loading the site with a click on the sitelogo or when showing a users profile via profile link (ajax?) not when doing a refresh with the browser. on the picture you see the file from b3 and b5...
![umlauts](https://cloud.githubusercontent.com/assets/13225682/15654190/47aa4a64-2692-11e6-85a2-e012288e592c.jpg)

**Comment by neil96** [comment]
Could you give us some example phrases?

**Comment by lordofnos** [comment]
this example uses all: Während Adam lacht, jagen zwölf Boxkämpfer Eva quer über den großen Sylter Deich - für satte 12.345.667,89 €uro

**Comment by neil96** [comment]
I still can't reproduce with phrases you gave.
Tried with user status, add blog, change full name to German.

**Comment by lordofnos** [comment]
i also can not reproduce it on v4.phpfox.com. on my own site i can but when i use the old phpfox.class everything works fine.

**Comment by neil96** [comment]
Could you send us a live demo can reproduce this issue?

**Comment by lordofnos** [comment]
i could send you a private link. i just tested it again. with the file of build 5 i can reproduce it but when changing back to build 3 there is no issue.

**Comment by neil96** [comment]
Ok! Please [submit](https://clients.phpfox.com/supporttickets.php) us a ticket.
