### ISSUE TITLE
Store allegedly does not inform YouNet customers that the YouNet Core is required.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1458]
A client recently purchase the YouNet Gateway app and claims the store never informed about the YouNet core dependency.  If not, it should, or provide the opportunity to install it first.  She had to download and install it separately from the site. I have never used it so i don't know how that works.

**Comment by neil96** [comment]
As [comment](https://community.phpfox.com/forum/thread/54866/younet-advanced-payment-gateway-did-not-install#post336956) of Younet from community. Their Apps don't need YouNet Core.
