### ISSUE TITLE
YouNet app purchased from phpFox store did not appear in customers YouNet client area

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1459]
YouNet did not display an app purchased through the store in the clients client area on the YouNet site. I don't know who works out the integration between the store and them, but sugget that fact be passed along to them by Ray or whoever does the store.

Unless it is supposed to work that way, but it wouldn't make sense.

**Comment by neil96** [comment]
Please submit ticket for YouNet to ask this feature.
