### ISSUE TITLE
[Relationships] Profile Pictures Not Showing

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#146]
When searching for a name when you choose Engaged, Married, etc. it shows a long url, vs the actual picture names.

![image](https://cloud.githubusercontent.com/assets/6254165/8764216/35afebe2-2d97-11e5-86ca-608409789e78.png)

**Comment by GloriousKoch** [comment]
This seems to have come up in the past here: https://github.com/moxi9/phpfox/issues/24 but it's happening to me on the latest Premium version.

**Comment by RaymondBenc** [comment]
I am unable to reproduce this locally. Based on the fixes provided in #24 it seems to be CSS related. If you are using the default theme try to go to your **AdminCP >> Themes >> Neutron**. Then look for the link **Revert Theme**. This should import the CSS fixes. Let us know if this helps. Thanks!

**Comment by RaymondBenc** [comment]
Actually, after further investigation this has not been fixed for users with images. #145 might be related at this point.

**Comment by orgazilla** [comment]
Problem solved!
