### ISSUE TITLE
[4.3.2b5] Admin cannot edit user registred with Facebook in AdminCP

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1463]
1) Create an account using the Default Facebook App.

2) Log in as Admin and then go to AdminCP >> Search >> Edit the user created in step *1 and modify gender or any other field except the email and then save changes.

3) You will get this error: 

**There is already an account assigned with the email "MyEmail@Mail.com". If this is your email please login here.**

**Comment by Data66PF** [comment]
Is this still the case with v4.4 RC?

**Comment by Spaninet** [comment]
No. I tested today and seems and I am not getting the error. Mybe it's fixed.
