### ISSUE TITLE
Muting nave menu item for guest access

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1464]
Some time ago, there was a post that requested muting items in the nav menu when the group (in this case Guest, but could be any) does not have permission to access the service, or has been disabled in some future control setting in menu settings. I cannot find it now and I am wondering what consideration has been given to this and where it is now.  Please advise. 

Thanks.

**Comment by Spaninet** [comment]
Yes, there is an option called  "Hide Main Menu" in AdminCP >> Settings >> Settings (Under user), that hides the menu for guests. It doesn't deactive the modules or any page/section. It only hides the main menu.

**Comment by neil96** [comment]
@Gatsby-PF What's error here?

**Comment by Gatsby-PF** [comment]
Spaninet: Thanks.  This feature addition went right past me.

neil96:  Never said anything about an error my friend. Was just wondering what direction they took this in as it was posted a few months back.  It is now a selectable control in the settings so thank whomever for adding it.

**Comment by neil96** [comment]
@Gatsby-PF Here's for bug tracker only. Please post on communty or feature request.
