### ISSUE TITLE
forget password : mail bug

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#1468]
Forget password is working fine but
it' showing admin email address in every mail.
for e.g
On forgot password page i submitted " xyz@gmail.com" (user email) and i recieved email in "xyz@gmail.com" with forget password instructions. but the email mentioned was  "admin@sitename.com"(admin email) instead of xyz@gmail.com (user email).

THis was the text of mail :
"
    Hello member name,

    You have requested for us to send you a new password for admin@sitename.com.

    To confirm this request, follow the link below:
    https://www.sitename.com/user/password/verify/?id=de630fb37da26ac432509170507d899d

    Kind Regards,
   Sitename Team
"
NOTE : This is an important fix , So we cant wait for the next upgrade version ,please mention the fix here. so that we can fix it on our site.

**Comment by neil96** [comment]
> Hello [user_full_name] 
> 
> You have requested for us to send you a new password for phpFox Demo. 
> 
> To confirm this request, follow the link below: 
> https://v4.phpfox.com/user/password/verify/?id=cfa5ba78ae33eac46cffdbe938a35032	
> 
> Kind Regards, 
> phpFox Team  

I have just tested on demo. It don't show admin email as you said. Please check your setting again.
