### ISSUE TITLE
[Relationships] Connecting To Another Person Doesn't Always Work Properly

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#147]
We're having issues getting the relationship feature to work properly. In trying a handful of times, only once did we get linking to another person to work...(Player A is Engaged to Player B).

Currently, tagging someone in it sends a notification to the other player, but it doesn't say WHAT they're notified for. Just says you have one from Player B and only choice is to confirm it.

I think to work in a make sense way it should go like this:

1. Player A links Player B via relationship option (Engaged/Married, etc.)
2. Player A's feed shows JUST the "Engaged" or "Married" until Player B confirms.
3. Player B gets a notification: Player A has tagged you in their Relationship Field as "Engaged/Married"
4. If Player B denies, Player A's feed stays as just Engaged or Married.
5. If Player B accepts, both feeds change/show they are "Engaged/Married" to each other.

If one or the other ever changes their status, the other's feed should reflect the change as well, at the very least by removing the name link, if possible.

**Comment by Data66PF** [comment]
I'll confirm the issue with no message for what type of notification and this is a feature request I had asked for in the old feature request system. I still agree that any sort of "friend, relationship, etc" sort of notification should state to the user getting it what this notification is for as it caused me to confirm being married to another user on the phpfox forum as I thought it was just a friend request. 

Will confirm as an enhancement. Note that my confirmations are just to designate what type of issue this is. It is not a confirmation that it will be made into a feature as only Ray can decide that.
