### ISSUE TITLE
Hashtags Cyrillic again do not work properly.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1470]
Hashtags Cyrillic again do not work properly. Opens posts everything.
https://v4.phpfox.com/hashtag/%D0%A5%D0%B0%D0%BC%D0%B5%D1%81/

**Comment by Spaninet** [comment]
The issue is not with Cyrillic. Hashtag links don't work for any alphabet. It doesn't filter the posts with that hashtag.

**Comment by Criotin** [comment]
We should expect a fix for this problem?

**Comment by Spaninet** [comment]
Of course, we should expect a definitive solution.

**Comment by Criotin** [comment]
Well thank you. When can we expect the release of version 4.4.0?

**Comment by Spaninet** [comment]
@Criotin I don't know. I am not from phpFox staff.

**Comment by Criotin** [comment]
Not fixed.

![hashtag](https://cloud.githubusercontent.com/assets/15389101/18485271/dee56746-79f4-11e6-82f2-2a29dc54af4d.png)

**Comment by Data66PF** [comment]
Fixed bugs cannot be reopened. If you find bugs that are not fixed, you need to open a new issue (one issue per bug) and in the new issue, reference the fixed bug please.
