### ISSUE TITLE
Private messages thread view does not update

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1471]
When private message thread view is open and the remote correspondent sends a new message, the message thread does not refresh and update to show the new message. In order to read the new message, one has to close the message thread and re-open it everytime someone responds to a message.

**Comment by Data66PF** [comment]
Confirmed at forum and on dev site but with v4.3.2. Will test 4.4 later.

**Comment by neil96** [comment]
That's private  messages, and it don't support real time. Users have to refesh page to get new messages.
If this feature support real time, why did we create more IM?

**Comment by Data66PF** [comment]
Well this is not working well then as it is a poor user experience not to clear out the notification. This works perfectly in v3. Are we saying that we failed to design this with the user in mind for just using normal IM and not IM Chat? We need to look at the overall user experience as this is not the way to do it, having it work in Chat and not in general IM without chat enabled.

**Comment by RaymondBenc** [comment]
This is currently how it is designed with the base Messenger. It is not a real-time messenger system unless using the IM. If you are having another issue not related to real-time message updates please feel free to open a new issue.

Thanks
