### ISSUE TITLE
Another Video Issue - Categories Issue

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1473]
I noticed that even though the video issue where you could only see 12 videos on the video index page, there are still problems when you click on video categories. Many videos that have been set to those categories are not appearing. For example 17 of my videos were set to a specific category when they were uploaded. But when I click on the category in the block on the left of the video index page only 3 videos appear under that category.

**Comment by Data66PF** [comment]
Can you reproduce this at the demo?

**Comment by queenmother305** [comment]
I have not tried but I can tell you it's happening on both my sites. the fresh install site, and my upgraded site.

**Comment by queenmother305** [comment]
I forgot to mention my problem was with videos actually uploaded. Not shared. So IDK about the links and stuff. I just know when I upload a video they aren't appearing in the categories.

**Comment by Data66PF** [comment]
Yes, the issue is for the entire video app.
