### ISSUE TITLE
user profile pic NOT FOUND

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1476]
i followed all the instructions from https://docs.phpfox.com/display/FOX4MAN/Cleaning+up+V3+Files+after+Upgrade
the folders including pic attachment etc folder are all filled with past pic and profile pic
but it's still showing me now in the 4.3.2. b5 upgrade that pic not found.

![screenshot 2016-06-09 09 49 45](https://cloud.githubusercontent.com/assets/3644262/15932793/ff63eb20-2e2a-11e6-9254-664c587eaaae.png)

**Comment by Data66PF** [comment]
I don't believe this is a bug. Your not found issue is not seen on other sites. I believe this is a site issue, perhaps a bad upgrade or folder permissions.

**Comment by Data66PF** [comment]
I just checked with my son who upgraded a v3 site yesterday and this issue is not present. Your issue is probably a site issue itself.
