### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by sql-inject0r** [moxi9/phpfox#1477]
Removed

**Comment by Data66PF** [comment]
We already have our team doing deep security analysis for v4.4 . However, we do appreciate reports. Please next time do so in a proper manner, via a ticket to us as a public area is not good to post this sort of thing as it leaves it in the open. It is possible our team already found and fixed this for v4.4 (if it still existed in the current code). Here is a link to report next time, https://clients.phpfox.com/submitticket.php and please choose Sales. Thank you.
