### ISSUE TITLE
Page speed issue

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#1480]
Dear Team, 

I have pulled this report from Google developer's page speed insights for v4.phpfox.com demo site of PHPFox and came across this: https://goo.gl/MwcNXJ

Can we have them fixed:
1) Eliminate render-blocking JavaScript and CSS in above-the-fold content
2) Prioritize visible content
3) Minify JavaScript
4) Leverage browser caching
5) Minify CSS
6) Optimize images
7) Reduce server response time

**Comment by SalmanKhan86** [comment]
This must be close ASAP.
Good Points for Increase Site Performance

**Comment by Data66PF** [comment]
Please wait for our 4.4 release as we are already making many improvements. This is closed as it does not follow our posting rules and we already are making many optimizations. You can open a new issue after 4.4 releases, one issue at a time per our terms.
