### ISSUE TITLE
I can not find HTML file

### ISSUE THREAD

**Issue by Karlos1xx** [moxi9/phpfox#1482]
## I can not find HTML file in FTP
I can modify it
![screenshot at giu 15 15-47-49](https://cloud.githubusercontent.com/assets/18431636/16082332/35cfab82-3311-11e6-9f10-710fe43037a1.png)

**Comment by Data66PF** [comment]
Please ask questions at the community https://community.phpfox.com as this is only for bugs and not for questions.
