### ISSUE TITLE
profile pic on pages

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#1483]
using the 4.3.2 b5
on all my pages the profile pics shows up as this
https://www.dropbox.com/s/9le77i4vfbo5l0d/Screenshot%202016-06-15%2016.43.42.png?dl=0

when i go in to manage page it it's like this, the picture is there
https://www.dropbox.com/s/2i06mo3feuo8kuf/Screenshot%202016-06-15%2016.45.47.png?dl=0

how to fix the link to my page?

**Comment by neil96** [comment]
Can you reproduce this issue on our demo?

**Comment by wlongdonstudio** [comment]
http://www.toproadliveradio.com

**Comment by Lukey199223** [comment]
I'm also on build 5 and do not have this problem :) , Maybe some error with your code ? :) ,

**Comment by wlongdonstudio** [comment]
i think the upgrade from 3.8 to 4.3.2 b5 scrabbled everything just need to know what to change so all the image can be reflected

**Comment by Lukey199223** [comment]
:) , what I do when there's something wrong with my Javascript or html, I copy the code from the default theme and paste it into your code section, it saves you the time of trying to find the problem in your code :)

**Comment by neil96** [comment]
@wlongdonstudio I checked on your site. You are using 4.3.2, but some files of your code seem not up to date.
Images show "**not found**" because file not exist/or deleted on your server.

**Comment by Lukey199223** [comment]
I have been testing, and I have this issue also , my sever is fine, I'm on build 5 , my codes etc are fine
