### ISSUE TITLE
Video Uploading Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1484]
when we finished video uploading share button text change to uploading... in video section we are not able to upload new video as when we click on it nothing open.
Check it on v4.3.2 b5
![video uploading issue](https://cloud.githubusercontent.com/assets/13433124/16334947/9aa9d67e-3a21-11e6-8249-661cfd751a1f.png)

**Comment by Data66PF** [comment]
Is this seen at our https://v4.phpfox.com demo?

**Comment by SalmanKhan86** [comment]
yes having same problem its text changed to Save

**Comment by SalmanKhan86** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13433124/16335559/f8101f0a-3a24-11e6-84b4-fd73b8368524.png)

**Comment by Data66PF** [comment]
Testing on a macbook pro with chrome. I cannot reproduce the Save not going away after I click to Save the video. I tested with a video in the feed and one in the main video section.

**Comment by SalmanKhan86** [comment]
i checked into https://v4.phpfox.com demo.its having same problem. in video uploading its not showing any processing(% how much video uploaded). after uploaded a rounded spin is processing and text changes to save that not going anywhere until we have refresh whole page completely.
i checked with OS Windows 7 with Chrome browser
![wewwwe](https://cloud.githubusercontent.com/assets/13433124/16403787/6a8cf780-3d16-11e6-9400-d28b82ccfb86.png)
![jkjkjlkjlk](https://cloud.githubusercontent.com/assets/13433124/16403795/7138ff66-3d16-11e6-9a97-012d1f0cfe70.png)

**Comment by Data66PF** [comment]
Does it do it on our staging, http://v4.phpfox.com/stage/ ?

Please state the OS and browser version when replying (I know you said win7 but we need to verify that).

Can you also reproduce it from a different OS and browser?

**Comment by SalmanKhan86** [comment]
i have't other OS so that i am not able to test it on different OS. i am able to reproduce it on window 7 with Chrome Browser
