### ISSUE TITLE
Photo Alignment Issue Neutron Theme

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1485]
when we open full view photo then its problem in Alignment. with v 4.3.2 b5 Neutron Theme
![photo alignement](https://cloud.githubusercontent.com/assets/13433124/16355640/b2be9984-3ada-11e6-9638-1c187d7ad834.png)

**Comment by Lukey199223** [comment]
I thought I was the only one with this problem haha, there's a couple of problems with the neutron theme, their really annoying, but phpfox are awesome so I'm sure they'll fix it :)

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.

**Comment by Lukey199223** [comment]
Ah  right aha, Well it was best for you to remove it :) , I'm using neutron so I'm wondering if there's a chance of these being fixed in the next week ? :)

**Comment by Lukey199223** [comment]
Thanks for getting back Donna :)
