### ISSUE TITLE
[4.4.0-beta1] Video App - Edit link not working in comments

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1488]
Share a video, add a comment and then try to click the edit link. You will see that is not working. It redirects to "Page not found" page.

**Comment by neil96** [comment]
I can't reprodcue, could you give us more steps.

**Comment by Spaninet** [comment]
1) Go to Video page (Video App)

2) Share a video from YouTube, Vimeo or any video plataform

3) Add a comment in the video

4) Clic "edit" link to edit the comment that you just added. You will see that goes to an inexistent page instead of showing the text area to modify the comment.

**Comment by Data66PF** [comment]
http://v4.phpfox.com/stage/v/play/69/inline#?type=text&&simple=true&id=js_comment_text_5&call=comment.updateText&comment_id=5&data=comment.getText

**Comment by Data66PF** [comment]
This is confirmed on staging
http://v4.phpfox.com/stage/v/play/69/
