### ISSUE TITLE
[4.4.0-beta1] Video App - Notification for liking or commenting own videos

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1489]
I get a notification every time I comment or like my own videos.

**Comment by neil96** [comment]
I can't reproduce on my side. Your videos is uploaded file or shared from youtube? Is your site upgraded?

**Comment by SalmanKhan86** [comment]
i am having same problem.video does't liked and i himself get notification for same.
Tested on [4.4.0-beta1]
![video like problem](https://cloud.githubusercontent.com/assets/13433124/16404383/25a6ac00-3d1c-11e6-835a-eaccd707cc7c.png)

**Comment by Spaninet** [comment]
👍
