### ISSUE TITLE
v3 to v4

### ISSUE THREAD

**Issue by todaylogin** [moxi9/phpfox#149]
please guide us full path and procedure v3.80 to v4.0.2
manually upgrade reference is only for v4.01 to more not v3 to v4.
Please crear for v3 to v4 upgrade process ?

**Comment by todaylogin** [comment]
http://support.phpfox.com/upgrading-phpfox/manually-upload-files/

**Comment by Data66PF** [comment]
That is how it works for my upgrades. I just did the same method. Did you try it? It worked for all of the test sites I upgraded. Note to try on a development clone of your site and not a live site.

**Comment by todaylogin** [comment]
yes i tried!
Dear i am so confused about that one side you say that v3 modules installed successfully in v4 using root directory PF.Base its good and i tested. well done.
and other site upgrade process not action required for directory(All site files and folders are on 99.99% different place).
I am not understand that how to upgrade and how to import data from v3.8 to v4?
My feelings about upgrade v3 to v4 is a serious joke

**Comment by Data66PF** [comment]
Don't use any third party v3 modules in v4 as they will need some updates so disable those and disable third party themes before upgrading. Then upload the files and run the upgrade process as it shows. It's not hard. Please ask questions in the community as this is for bugs only.
