### ISSUE TITLE
[4.4.0-beta1] Report an item Problem Neutron Theme

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1492]
when we report an item and we does't choose any category then notice appear in its back window and after reported item report box doesn't hide.
![reported items](https://cloud.githubusercontent.com/assets/13433124/16406156/076e6cf6-3d2a-11e6-8113-c018cbc2b5c6.png)

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.
