### ISSUE TITLE
[4.4.0-beta1] Old database issue (Pages)

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1493]
I've restored the backups, but only for pages does not work. Categories and content don't.

![pages](https://cloud.githubusercontent.com/assets/8930862/16411907/26eda800-3d32-11e6-9d80-a52cb9a49d4e.png)

**Comment by neil96** [comment]
>Pages backup

What did you mean?

**Comment by SalmanKhan86** [comment]
this mean they have switched to old db backup

**Comment by karargaht** [comment]
Yes, the old database is not working (only pages)

**Comment by neil96** [comment]
>Yes, the old database is not working (only pages)

Did you upgrade your database to 4.4?

**Comment by karargaht** [comment]
I made a new setup.

**Comment by Data66PF** [comment]
Are you trying to import from a database backup to a fresh install? This is not covered in github issues. Please do not try importing an old db into the v4.4 fresh. Please follow our instructions for upgrading your development, not live, site.
