### ISSUE TITLE
[4.4.0-beta1] The group and video name issue

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1494]
Group name and video name not seem

![groups](https://cloud.githubusercontent.com/assets/8930862/16411975/7b37438a-3d32-11e6-9895-b0d89ed4b791.png)

**Comment by neil96** [comment]
Did you clear cache?

**Comment by SalmanKhan86** [comment]
i think you are using old database

**Comment by karargaht** [comment]
New setup with solved the problem.

**Comment by neil96** [comment]
If you want to use old database, please upgrade your database to 4.4.
