### ISSUE TITLE
[4.4.0-beta1] Language files for export are 0 Kb

### ISSUE THREAD

**Issue by websistema1** [moxi9/phpfox#1496]
Unable to save the language pack (Russian, Ukrainian) - the file contains no data (0 kb). See more at: https://community.phpfox.com/forum/thread/54985/i-need-a-magic-trick/

**Comment by neil96** [comment]
I tested on phpFox 4.4.0-beta1 and php 5.6, it's working. Which php version are you using?

**Comment by websistema1** [comment]
php 5.4.45 (cgi-fcgi) | MySQL 5.1.73

**Comment by neil96** [comment]
I tried with centos 6.7, php 5.4.45 but I can't reproduce this issue.
This problem occur in all language packages or just with Russian, Ukrainina?

**Comment by websistema1** [comment]
For any language

**Comment by neil96** [comment]
Could you try to install a new site and check again? This issue might 3-rd apps or upgrade step was missed.
That will be great if you have a live demo that we can reproduce it.

**Comment by neil96** [comment]
Now I can reprodce this issue with **debug mode on**. It's working if I turn off debug mode.

**Comment by websistema1** [comment]
Updated server, I have now installed Centos 7 | PHP 5.6.23. After the installation of the new site, the English language file can be saved. After installing the Russian and Ukrainian language is a problem - all the language files (including English), after saving a size 0 kb.
