### ISSUE TITLE
Problem with ajax login block with core.force_https_secure_pages set to true

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1497]
After enabling the above setting, the login block would not display (eternal loading) with an error message concerning Access-Control-Allow-Origin being different.  I was able to make it work by adding this to the htaccess file: 

```
    Header set Access-Control-Allow-Origin *
    Header set Access-Control-Allow-Headers "Content-Type"
```

Even with this in place, I get warning: "Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen."

This may be related to this issue: https://github.com/moxi9/phpfox/issues/1392

**Comment by neil96** [comment]
Please also turn this setting **core.force_secure_site** to true.

**Comment by Data66PF** [comment]
This is not how it should work. We have many clients that only want to set the login, etc as secure as we always could in v3. We need this setting to work as it always did as not all clients want the entire site https secure. This will drive away sales and force clients to leave.

**Comment by Data66PF** [comment]
@neil96 or someone, we need to check this before release.
