### ISSUE TITLE
another recurring video issue smh

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1499]
i couldve swore this issue was also marked fixed. i have hundreds of videos, yet some categories appear to be empty when people click on them. i double checked by editing the videos to see which category they are assigned to and the videos have indeed been saved to the categories yet they are nowhere to be found when clicking on the actual categories in the little menu on the side! this is horrible for video based sites like mine. it is effecting my money because it appears we have very little content!

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1473 please search before posting. Please note that open issues did not make it into the beta yet. They made it into the next release.
