### ISSUE TITLE
Change available modules on pages

### ISSUE THREAD

**Issue by JulienHenchoz** [moxi9/phpfox#15]
On PHPFox v4.0.0 rc2, I'd like to change the displayed module on Pages (displayed on top-right in the header of Pages). I searched the admin interface for this but I couldn't find the solution.

Strange thing is, "/index.php/pages/<Page ID>/blog/" works and displays the blogs related to the page, but it does not appear in the top-right menu.

![cobweb_ _social_networking_community_-_powered_by_phpfox](https://cloud.githubusercontent.com/assets/888157/7322850/036f2c76-eaab-11e4-8dc1-c2564bed5ca8.png)

**Comment by RaymondBenc** [comment]
Currently not possible, however we are developing hook placements to allow apps to alter this features behaviour.
