### ISSUE TITLE
cannot access announcements in admin after upgrade

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1500]
tried to delete an old announcement and cannot do it because when i click announcements in the admin panel it just refreshes the admin panel.

**Comment by LMG123** [comment]
Still not working.
After submiting the announcements they don't show.
 4.4 RC Released Fresh Install.

**Comment by neil96** [comment]
@LMG123 I can't reproduce this issue. Please check again "start date" and "Target user", if you still get this issue, please open new issue with detail steps to reproduce.

**Comment by LMG123** [comment]
@neil96  Hello, Yes I did check everything several times also the time stamp on the server just in case.
here is a video: https://www.dropbox.com/s/faupo7emmmjtbkc/announcements.mp4?dl=0
