### ISSUE TITLE
Status privacy button not filling box Height (Neutron theme) 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1501]
Hello :) 

I've found another problem with the neutron theme, I'm on build 5 , but this has been a problem since 4.2 

I've also tested this on the default neutron theme

the height of the status privacy button (everyone etc) , doesn't cover the height it should, so its not the same height as the share button 

![privacybutton](https://cloud.githubusercontent.com/assets/16384395/16490551/12178b0c-3ed2-11e6-9761-ee6c694a816a.png)

I hope all the issues with neutron get fixed soon :)

**Comment by neil96** [comment]
I see your screenshot does not look like neutron theme. Your code was modified?

**Comment by Lukey199223** [comment]
sorry for the late reply Neil , I Was using my theme haha, I've changed to the neutron default theme, for the screenshot :) 
![everyone](https://cloud.githubusercontent.com/assets/16384395/16543301/fe94660a-40c4-11e6-93dd-c7bed8d604f2.png)

**Comment by Lukey199223** [comment]
Sorry about the background being still blue, I changed it on the default before I knew changing defaults is a no no aha

**Comment by neil96** [comment]
On default neutron theme, we don't set background for privacy button. This problem because your custom theme.

**Comment by Lukey199223** [comment]
There is a background colour on the default button when you hover over it :) I'll add it to my custom to do list :)
