### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by OboyKing** [moxi9/phpfox#1502]
Photos uploaded from the photo section does not show up on main dashboard .and when you click on a photo you've uploaded the photo won't show up...
![1818534617](https://cloud.githubusercontent.com/assets/20237833/16513946/ebafac32-3f68-11e6-9025-473440f18639.jpg)

**Comment by Data66PF** [comment]
What version are you testing?

**Comment by OboyKing** [comment]
Hi Data 66.....i am using  4.4 Beta

**Comment by Data66PF** [comment]
Please test on our staging site https://v4.phpfox.com/stage after we release our RC version
