### ISSUE TITLE
Photo Enlarge Not Closing

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1503]
when we click on photo to enlarge it then click on close button does't do anything.photo is not closing.Test With v[4.4.0-beta1]  with Neutron theme.
![photo upload close problem](https://cloud.githubusercontent.com/assets/13433124/16521762/b88e2308-3fb6-11e6-927a-dc0c72a2bc83.png)

**Comment by neil96** [comment]
This feature is working on bootstrap theme. 
Neutron now is not default theme, so please wait for next version of neutron theme.

**Comment by Data66PF** [comment]
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.
