### ISSUE TITLE
Setting Data Cache Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1505]
when we change data cache to Redis and Memcache then revert back to file system does't work. after that site does't load anything. when we change to redis or memcache two files generate in file>settings that never get deleted when we change it to back file system. some entries also insert in language_phrase table.
v4.4.0 beta1
![cache driver setting](https://cloud.githubusercontent.com/assets/13433124/16538702/93cb741a-4049-11e6-83dc-eaf7c5d23892.png)
![cache settings](https://cloud.githubusercontent.com/assets/13433124/16538703/9400c084-4049-11e6-85a6-501f604f6dd5.png)

**Comment by spirogg** [comment]
I have seen the same issue. The site or admin CP doesn't load after this. Not sure if we delete those 2 files if the site will be visible again.

**Comment by spirogg** [comment]
OK I forgot to mention. I didn't have redis setup and did change drop down to redis then memcache then back to filesystem. That's when site went blank. Then I reinstalled and setup redis and added info for host etc.  and now if I change back n forth to filesystem redis memcache and back to filesystem the issue is no longer there... my site does not go blank . 

Just FYI.

**Comment by Data66PF** [comment]
So this is resolved once you set up redis as the tutorial mentioned to do? https://docs.phpfox.com/display/FOX4MAN/Redis as it will cause an issue if not following the tutorial to have it enabled first. If that is the case, this is not a bug as the tutorial said to follow the steps.

**Comment by Data66PF** [comment]
https://docs.phpfox.com/display/FOX4MAN/Cache+Options and that tutorial

**Comment by spirogg** [comment]
Yes @Data66PF  Maybe a warning do not change unless you have set up. Etc  etc. On that setting. Page. Cause if you don't have set up it will disable your site.  :)

**Comment by Data66PF** [comment]
Agreed it needs a warning. Will mark a bug but it's not really a bug. However, it should have a warning since clients seem not to read the tutorials.
