### ISSUE TITLE
Pages small image

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1506]
4.4  release The small image for pages and groups not showing and name etc needs a background block to show regardless of image color. see attached.
![2016-07-02 16_32_53-baroness v social networking community](https://cloud.githubusercontent.com/assets/13656046/16540931/0df79cc4-4076-11e6-9086-d6f9c0893d8b.png)

**Comment by neil96** [comment]
We have a dark gradient background on pages/groups title. The pages/groups' title always readable for any background.

**Comment by Data66PF** [comment]
Please always keep issues to only one thing. This will be for the Image missing. The other issue can be in a new topic but I'm not seeing an issue on the various ones I tested on my 4.4 with default bs theme.

**Comment by one44** [comment]
I think this is an upload issue as even avatars seems not to work.

**Comment by neil96** [comment]
@one44 default on groups, avatar does not display.

**Comment by Data66PF** [comment]
So this is working as designed then?

**Comment by one44** [comment]
This needs an explenation as 
1 generic cover uploaded
2  Page cover uploaded
3 Avatar for page uploaded Not showing
Does this mean this has been removed?????

**Comment by Data66PF** [comment]
Please let us know. Is this for Pages, http://v4.phpfox.com/stage/pages/ or the new Groups app, http://v4.phpfox.com/stage/groups/ as your issue is not able to be reproduced in Pages.

The Groups app is different than our Pages module. If you mean new Groups App, please edit this bug report for Groups App.

**Comment by Data66PF** [comment]
You will note that at our 4.4 staging, if you look at a Pages page, it shows the avatar. If you look at a Groups app Group, it does not as it was not designed to.

**Comment by neil96** [comment]
@one44 
1 => You can set default cover for pages, groups and user in theme manager.
2 =>  Pages/groups admin or user can upload new photo to replace default cover.
3 => Avatar will display on user, pages, not display on groups.

**Comment by Data66PF** [comment]
We need to keep Pages bugs separate from Groups App bugs as they are two different things. For Groups app, this is working as designed. If you see the issue with the Pages module, please open a new bug report but check our live 4.4 stage site as it shows fine there.
