### ISSUE TITLE
4.4.0 beta 1 - when uploading music mp3 just says uploading... never refreshes to complete

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1508]
Hi I did fresh install of beta 4.4.0 and tried to uploaded a mp3 file without adding a name for it or a category - then it just keeps spinning saying uploading...  5-6-7-10 mins or more and never uploads.. - so can we make it impossible to even allow a user to select upload 
( just make the upload button not active unless we have the required name and category in order to upload )

So I tested and was actually able to add a mp3 with no category, just a name for it.... but when clicking on the name of the mp3 that I uploaded (without a category)  it doesn't show up.

can we add a required field on both category and naming of music mp3 and the upload button wont allow upload if both these fields are empty please ?

![music-uploading-just-keeps-spinning](https://cloud.githubusercontent.com/assets/17736688/16543556/291b0472-409f-11e6-822b-0d31c1469536.PNG)
![testing-mp3-no-category](https://cloud.githubusercontent.com/assets/17736688/16543605/7213b0e0-40a2-11e6-80a6-2ca2a87e7e09.PNG)

 

Thanks

**Comment by neil96** [comment]
I can't reproduce this issue on 4.4.0beta1. Please check your mp3 file size,  and config max_upload_filesize on your server.

**Comment by spirogg** [comment]
OK able to upload file size fixed. But can we make category and naming of mp3 both a requirement. ? 

Thanks

**Comment by neil96** [comment]
With default code, you can't do that.
