### ISSUE TITLE
Marketplace Module Problem in V4

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#151]
a) Existing listings are not available/not showing for new registered users. Even if the "Listing Privacy is for Everyone". But if the new registered user becomes friends with the owner of the listing that's the time the registered user will see the listing.

b) I created 2 sub categories on the same parent category. Guess what, the listing I created under 1 sub category is appearing twice on the listing with the same info including time and date created, meaning it is showing duplicated.

c) Search by Country or by keyword also not working.

**Comment by Data66PF** [comment]
Please post one issue per report so we can mark them as fixed for each one when they are fixed but please be sure to search the bug tracker before posting. Thank you.

**Comment by RaymondBenc** [comment]
For issue "a)", the site by default is set to **Friends Only Community**. Disable this option under **AdminCP >> Settings >> Name & Copyright" to allow anyone to view listings posted publicly in each section.

**Comment by Verdz** [comment]
You mean issue B & C are both fixed? What I have to do now?
