### ISSUE TITLE
beta 4.4.0 mp3 not same size in home page and members page one border one without

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1511]
hi i uploaded mp3 file then shared it .. then clicked on home page and i see one has border around it and wording of shared etc is different, plus the size is different see photo. this also is happening when selecting a member to view there page 
![mp3-upload-vs-shared-one-has-border-other-does-not-same-mp3](https://cloud.githubusercontent.com/assets/17736688/16543641/e384b196-40a4-11e6-949e-26f1f4edc997.PNG)
![mp3-upload-vs-shared-one-has-border-other-does-not-same-mp3-home-page](https://cloud.githubusercontent.com/assets/17736688/16543640/e37f021e-40a4-11e6-9522-fdd8a194873b.PNG)
![mp3-upload-vs-shared-one-has-border-other-does-not-same-mp3-home-page-](https://cloud.githubusercontent.com/assets/17736688/16543642/e386fca8-40a4-11e6-93bf-cce32adc8b90.PNG)

**Comment by neil96** [comment]
What is the bug here? It was working like this in previous version.

**Comment by spirogg** [comment]
Is there suppose to be a border around some of the mp3 players  and  no borders around other mp3 players ?
