### ISSUE TITLE
Video does not fit screen (Responsive)

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1513]
**First-sharing**

![1](https://cloud.githubusercontent.com/assets/8930862/16545456/f904c080-4133-11e6-92c3-a299fbb2e933.png)

**second-sharing** (share the same thing again)

![2](https://cloud.githubusercontent.com/assets/8930862/16545457/08bc7536-4134-11e6-9d3e-d65de6a7d280.png)

V: 4.4

**Comment by spirogg** [comment]
OK this is same issue on my mobile phone  chrome browser beta 4.4.0. So seems it was fixed. 

Thanks. 
![screenshot_20160704-000455](https://cloud.githubusercontent.com/assets/17736688/16551301/8274a338-417c-11e6-87a2-ff88b8329aab.png)
