### ISSUE TITLE
beta 4.4.0 - groups, adds double the group you created see photo

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1516]
beta 44.0 - groups, adds double the group you create 

see photo

![broups created only 2 groups but it doubles them each](https://cloud.githubusercontent.com/assets/17736688/16553569/f351d53c-418e-11e6-94b5-2046bfab894c.PNG)

**Comment by neil96** [comment]
Could you give us detail steps to reproduce?

**Comment by Data66PF** [comment]
Are you sure the server is using php 5.5 or up? Are you sure you have no third party apps or modifications to this test site? I am also unable to reproduce your issue which seems the same issue you have in pages.

**Comment by spirogg** [comment]
Using php 5.5 cloud Linux with cagefs , mariaDB no modifications. Freshly installed yesterday 
Changed two folders to 777 when installing. Changed back one folder to 755 and left other at 777 
Seems redis and redis cache might be issue. I am going to reinstall fresh database also and leave settings alone other than friends only OFF. Post back in a few.

**Comment by neil96** [comment]
Do you have a live demo that can reproduce this issue?

**Comment by spirogg** [comment]
Not sure what happened. But seems all is OK now after reinstall of new database even with redis no double but sometimes I see scripts HTML instead of the page - that was with redis on redis cache and bundle JavaScript & CSS. 
I reverted back to no redis or redis cache or Bundle and just filesystem for cache and works good after clean cache. Not sure why other setting gives me an issue.
