### ISSUE TITLE
beta 4.4.0 - pages, adds double the page you created see photo

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1517]
beta 4.4.0 - pages, adds double the page you created see photo

**Comment by spirogg** [comment]
beta 4.4.0 - pages, adds double the page you created see photo
![pages double](https://cloud.githubusercontent.com/assets/17736688/16553693/aa88481c-418f-11e6-928c-c808fa70a414.PNG)

**Comment by neil96** [comment]
Could you give us detail steps to reproduce?

**Comment by Data66PF** [comment]
I also can't reproduce it.

**Comment by spirogg** [comment]
i am using Performance>> redis Enabled ... Data cache>> Redis cache, IM app ON with node.js  all redis and .js configured correctly.. 
php5.5 on cloud linux, MariaDB for mysql

if you click on update after creating the name of page or group it seems it makes a double, when you click on > far right side same line as name of page someti
![pages double](https://cloud.githubusercontent.com/assets/17736688/16563917/5575eac4-41ca-11e6-89cb-615f69d660e1.PNG)
![radio - update creates double](https://cloud.githubusercontent.com/assets/17736688/16563925/5ca59b78-41ca-11e6-9eb6-d2deb7c5c74c.PNG)

mes it does and some times it doesnt create double see photo

**Comment by spirogg** [comment]
OK I turned off redis, changed back to filesystem for cacge, turned off IM 
And it doesn't add double 
Seems redis is the issue here. 
Still I am going to test again with fresh install with me database and leave all settings as default and just enable redis and redis cache only. Then try again and see what happens. Will post back.

**Comment by spirogg** [comment]
Not sure what happened. But seems all is OK now after reinstall of new database even with redis no double but sometimes I see scripts HTML instead of the page  - that was with redis on redis cache and bundle JavaScript & CSS. 
I reverted back to no redis or redis cache or Bundle and   just filesystem for cache and works good after clean cache. Not sure why other setting gives me an issue.
