### ISSUE TITLE
unable to hide menu item for particular user group in phpfox 4.3.0

### ISSUE THREAD

**Issue by santoshbadal1111** [moxi9/phpfox#1518]
Can anyone tell how to hide menu item for particular user group in phpfox 4.3.0 as there seems no setting for showing and hiding menu in new version.

**Comment by Data66PF** [comment]
This feature does not exist. There is a tutorial at scripttechs for disabling via database or you can post a feature request in our feature request area if there is no one for this already. https://github.com/moxi9/phpfox-feature-requests
