### ISSUE TITLE
Translation shortcomings...

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1519]
**Creating pages and groups** (Name)

![translate](https://cloud.githubusercontent.com/assets/8930862/16561804/ce2d3650-4203-11e6-97e4-b67ef22233a2.png)

**Cover Reposition** (Save)

![save](https://cloud.githubusercontent.com/assets/8930862/16561926/73e6c354-4204-11e6-97d9-87fe7dd41b5e.png)

**Comment by neil96** [comment]
Fixed for phrase "Name" ans "Save".
Reposition was phrase (user.reposition)

**Comment by karargaht** [comment]
![screenshot_2016-07-05-10-57-48](https://cloud.githubusercontent.com/assets/8930862/16577750/9f0e3788-429f-11e6-980a-a14521cc5613.png)

Video sharing the same

**Comment by neil96** [comment]
Please open new issue.
