### ISSUE TITLE
Blank Site After Upgrade

### ISSUE THREAD

**Issue by Codethematrix** [moxi9/phpfox#1521]
After following the installation guide steps to upgrade to the 4.4 I get HTTP error unable to handle request. Side Note - It would be better if the fresh installation and upgrade instruction weren't in the same line of information.

**Comment by Data66PF** [comment]
As this is for bugs, you would need to ask in the https://community.phpfox.com user to user help forum for site issues. Enable debug to check for issues and ensure you did not upgrade a live site, followed all of the new upgrade steps, and have php 5.5 on the server.
