### ISSUE TITLE
4.40 Groups home page not showing

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1523]
![groups](https://cloud.githubusercontent.com/assets/20259022/16572448/b71f882c-4236-11e6-8b94-df2f75e1c3a2.png)
After the install, the groups homepage has no newsfeed. I am also not able to upload any photos or create blogs ect..

**Comment by neil96** [comment]
Could you display all 3rd and try again. A group has at least 1 member, but your screenshot it show 0 member.

**Comment by jhayden2000** [comment]
all 3rd?

**Comment by jhayden2000** [comment]
![apps](https://cloud.githubusercontent.com/assets/20259022/16572616/6ddcc614-4238-11e6-9f3c-d864a68dd438.png)

did you mean the apps i installed?

**Comment by neil96** [comment]
Sorry, I am mistake in typing. I mean disable 3rd apps.

**Comment by jhayden2000** [comment]
done, but still no change

**Comment by jhayden2000** [comment]
![apps](https://cloud.githubusercontent.com/assets/20259022/16572922/2cd5e75a-423c-11e6-872d-17045df539f9.png)

I have deleted them all now. and cleared cache. still no change

**Comment by neil96** [comment]
Could you turn off setting you said on #1522

**Comment by jhayden2000** [comment]
yes, that is off. if i had it on, i wouldn't be able to use the home page, so its definitely off.

**Comment by jhayden2000** [comment]
is there a way to reinstall the groups app?

**Comment by Data66PF** [comment]
Enable debug. I have the same issue but it is due to my server having php 5.4 and we require php 5.5 on this release. My issue shows an error on the feed with debug enabled.

**Comment by jhayden2000** [comment]
Thx Donna. I have debug on, but im not seeing any errors. after looking at my site overview. i see my php is 5.6. 
![overview1](https://cloud.githubusercontent.com/assets/20259022/16582988/7f433c74-4280-11e6-9fbd-a87756954c54.png)
![overview2](https://cloud.githubusercontent.com/assets/20259022/16582989/7f44132e-4280-11e6-88a0-d1e8466060cf.png)

**Comment by Data66PF** [comment]
Please ensure display_errors is enabled on the server so you can see errors if there are any.

**Comment by jhayden2000** [comment]
where do i find that at?

**Comment by Data66PF** [comment]
Your host will need to enable it in the php settings.

**Comment by Data66PF** [comment]
We believe your issues are hosting related though.

**Comment by jhayden2000** [comment]
Why do you think its hosting related? Anything you can point me to that leads to that answer?

**Comment by Data66PF** [comment]
This is working for everyone else (except those like me with php 5.4 on my server) and our lead core developer said they seem server related. You need to see what debug shows.

**Comment by jhayden2000** [comment]
ok, i will check with them and repl back when i know. thanks.

**Comment by jhayden2000** [comment]
Ok, so i have debug mode on and it is displaying errors now.. I tested it by turning on the threaded display option that i reported about in ticket 1522. i got this below when going tot he homepage:
![threadederror](https://cloud.githubusercontent.com/assets/20259022/16588383/b2d7aa0e-429c-11e6-9cfe-0ac1ab65e7a9.png)

So i know that debug mode is working.. but still when i go to the group menu, there is no error. I have made more groups to test and still no error.
![groups](https://cloud.githubusercontent.com/assets/20259022/16588487/2948f7ec-429d-11e6-86ab-876d0668686c.png)


Its almost like the app thinks its working as intended.

**Comment by Data66PF** [comment]
The error you show is the exact same error I showed before we released but was told it was due to PHP 5.4 being on the server. Since you say you have a higher version than that, then the error I have is not from my PHP version so I'll confirm this bug since I can reproduce the error and you have PHP 5.6 on your site.

**Comment by jhayden2000** [comment]
Thanks alot. :+1:

**Comment by Data66PF** [comment]
My mistake. My bug is different than your bug. I don't have that display actions. I have activity feed bug. Your bug shows for Likes. I don't have that. Sorry for the miss-confirm.

**Comment by jhayden2000** [comment]
The error i showed you was to prove that my debug mode was working. It wasn't the error i get for groups. i get no error for groups. At the bottom of that thread where i showed the pictures. I said the groups app acts as if it is running as intended.

**Comment by Data66PF** [comment]
Yes I know but the error you have is another error to fix. I believe you may have had a setting enabled that was removed as the displayactions block is removed from my 4.4 version and that error shows. The displayactions is in 4.3.2 though.
For your error, I can't reproduce it. I also can't post feeds though on my Groups. In looking in admincp >> blocks and checking groups.view blocks, I see duplicates for each one. 

I suggest checking in your blocks manager for groups.view and see if you have the blocks there for feed and the rest of the blocks. There should be several showing and they should be active for most of them.

**Comment by jhayden2000** [comment]
Well that is definitely part of the problem. i dont have a groups section in the blocks
![blocks](https://cloud.githubusercontent.com/assets/20259022/16591933/45eb915c-42ac-11e6-902c-b9d80c695e3c.png)

Is there a way to uninstall and reinstall the groups app? something obviously went wrong.

**Comment by Data66PF** [comment]
Are you 100% sure you ran all of the new upgrade steps when you upgraded? There were a few added to the upgrade routine.

**Comment by Data66PF** [comment]
If not, go to the upgrade tutorial and please run the rest of the steps.

**Comment by jhayden2000** [comment]
I was sure i did, but i just double checked and did them again to be sure. and the result is the same.

**Comment by Data66PF** [comment]
Well that's odd as I did a normal upgrade with all of the steps and when I enabled the Groups app, it had all of the blocks (but duplicated). Check to ensure all of the Groups app files loaded to the server.

**Comment by Data66PF** [comment]
Maybe one of our core devs, I believe Neil is in this ticket, will have an idea as to why your groups app is not installing properly. Sorry I could not help more. I don't have any idea why it didn't fully install other than maybe missing files.

**Comment by jhayden2000** [comment]
Thats cool. thanks for the help so far. i had not thought to check the blocks section.. @neil96  if you get a chance, maybe tell me how to either manually add the files or try to re install the groups app??

**Comment by spirogg** [comment]
When you go to apps do you see groups app and when you select it is it there ?

**Comment by jhayden2000** [comment]
@spirogg yes i see the groups app. and it has the settings and all there.. but as we mentioned above, i dont have any blocks for groups.

**Comment by spirogg** [comment]
Did you try the.convert old groups since you upgraded.

**Comment by jhayden2000** [comment]
no, i didnt have any.

**Comment by Data66PF** [comment]
This sounds like the app didn't fully install. Perhaps a server hiccup during the upgrade process. Try reloading just the groups app files and disable it, then enable it, then clear cache from PF.Base/file/cache (leaving the index.html in it) and then clear it in your admincp. Make sure debug is NOT enabled when doing this entire process.

**Comment by Data66PF** [comment]
http://v4.phpfox.com/stage/groups/2/

**Comment by jhayden2000** [comment]
Neil when i delete the cache, do i just delete the files in that directory or the folders too?

**Comment by neil96** [comment]
@jhayden2000 No, please click clear cache on adminCP only.

**Comment by Data66PF** [comment]
I had suggested clearing on the server as sometimes admin cache clear doesn't fully clear it.

**Comment by Data66PF** [comment]
Please test once we release RC version.
