### ISSUE TITLE
PDO_mysql already loaded error

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1525]
Every few page changes, i always end up getting this error below. The Tittle is always the same but the details change based on what page im going to.
![pdo](https://cloud.githubusercontent.com/assets/20259022/16585755/66380952-4290-11e6-8927-323c7b2b32bb.png)

**Comment by Data66PF** [comment]
Are you sure you don't have some third party products or plugins , apps or customizations? We don't use pdo_mysql.

**Comment by jhayden2000** [comment]
Yes. but i will check with my server hosts and see if they know what it is. i showed all my apps in another thread.

**Comment by jhayden2000** [comment]
ok. i think this can be closed. this looks to be an issue when i have on debug mode.
