### ISSUE TITLE
content in Blogs, polls, and music modules are repeating when you scroll down the page.

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1526]
Here is an example of when i first open up the music page. you only see one item:
![music](https://cloud.githubusercontent.com/assets/20259022/16590453/9f40baea-42a5-11e6-9043-f7336f2313dd.png)

No when i scroll to the bottom of the page, i get this:
![music2](https://cloud.githubusercontent.com/assets/20259022/16590474/bac5a168-42a5-11e6-980f-e256831e1d84.png)

This happens for blogs, polls, music, and marketplace

**Comment by Data66PF** [comment]
Can you reproduce this with default bootstrap theme? Please note that no edits can be done to the default bootstrap theme or it can break the site. The theme must always be rebuilt for each upgrade in order to pull in theme fixes and improvements.

**Comment by jhayden2000** [comment]
yes i did and no changes have been made to the default them at all. that is the Quinta theme the i switched to.
![musicboot](https://cloud.githubusercontent.com/assets/20259022/16592642/b1a09728-42af-11e6-92f7-350625bc247f.png)

**Comment by jhayden2000** [comment]
update.. this is also happening for events.

**Comment by neil96** [comment]
I can't reproduce with any modules. Is your site upgrade?

**Comment by jhayden2000** [comment]
yes its an upgrade

**Comment by jhayden2000** [comment]
FYI. im nto the only one with this issue. i found this from a user in the community section:
https://community.phpfox.com/forum/thread/54872/phpfox-v4-video-page-infinite-reload/

**Comment by Data66PF** [comment]
That was specific to the video app which is an app and not a module. Different thing.

**Comment by Data66PF** [comment]
Please test at our staging site.

**Comment by websistema1** [comment]
I have the same problem. Version php - php 5.6

**Comment by websistema1** [comment]
This links to repeating pages:
http://vsitut.com/marketplace/
http://vsitut.com/event/

**Comment by Spaninet** [comment]
I have the same issue too.

Upgraded from 4.3.2b5.

**Comment by Data66PF** [comment]
Please test once we release RC version.

Please note that if using Redis, there are specific things to set up.
