### ISSUE TITLE
Thumbnail is missing when you post a website link on newsfeed

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1527]
I try to post a few website links and they arent all coming up with thumbnails. Some of them are showing the link info, and then a blank space where the thumbnail should be:
![link1](https://cloud.githubusercontent.com/assets/20259022/16598765/696c61c6-42cd-11e6-9a8a-34b10d0aa49f.png)

**Comment by neil96** [comment]
This is not a bug. We find images thumbnail on meta tag, it will display blank if no image found.
