### ISSUE TITLE
Notification icon not showing a number when an alert comes in.

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1528]
Ive noticed on multiple accounts that im testing with that even though im getting emails, the notifications icon is not showing that i am getting any.

**Comment by neil96** [comment]
I can't reproduce on 4.4.0beta1.
Is your site fresh install or upgrade?

**Comment by jhayden2000** [comment]
its an upgrade from 4.3.0

**Comment by neil96** [comment]
Did you clear cache? Rebuild bootstrap Core? Remove old files?

**Comment by jhayden2000** [comment]
yes. we did it during upgrade, and i did it again today during a conversation with Data66

**Comment by Data66PF** [comment]
Did you set the cron? It is required now for many things other than Groups app.

**Comment by jhayden2000** [comment]
i have it turned on here.. is that what you mean?
![cron](https://cloud.githubusercontent.com/assets/20259022/16618255/690fc4fa-4356-11e6-9752-080d83546501.png)

**Comment by Data66PF** [comment]
The cron mentioned in the tutorial for upgrading.

**Comment by Data66PF** [comment]
Ok that is an old setting that I believe we disabled as we put all of it in the cron.php routine but Neil will need to confirm that.

**Comment by jhayden2000** [comment]
Donna, We definitely didnt do that, but as i follow the steps, it says that there is a settings section called "Cron" in admincp.. but i dont see that.. im starting to think my upgrade didnt go very smoothly.
![cron](https://cloud.githubusercontent.com/assets/20259022/16619976/98d5fdfa-435e-11e6-9191-070fa5940797.png)

**Comment by neil96** [comment]
@Data66PF Cron job is required for notification for groups. Other notifications still work without set cron.
I believe this error from layout or CSS.

**Comment by Data66PF** [comment]
Cannot reproduce at the live stage site. Perhaps someone edited the default bootstrap theme or styles or added module overwrite to it. Please try without any changes to bootstrap and with no module overwrite in the default bootstrap.

**Comment by Data66PF** [comment]
Just to clarify for the client. This bug report is not related to the cron but it is required to be set up as the following will not work unless you do:

1 cron for deleting old data in table "log_session"
1 cron for deleting old mail message
1 cron for downgrading expired subscribers.

**Comment by Data66PF** [comment]
Please test once we release RC version.
