### ISSUE TITLE
Pages and Groups Only have buttons to make photos and discussions but settings for everything

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#153]
For pages and groups, we have (or had) the ability to make blogs, etc. The settings for Blogs, Events, Music, etc are still there in the Manage Permissions. However, there is no way to make these things in a page as the menu when viewing a page only shows Home, Discussions and Photos. Confirmed in the PF community and in my test sites.

**Comment by RaymondBenc** [comment]
With the latest build here, I believe this issue should be resolved. Those extra modules should not be showing up there. I'll test again once v4.0.4 is out.

**Comment by Data66PF** [comment]
fixed in 4.0.7

**Comment by one44** [comment]
only events in menu ?????

**Comment by Data66PF** [comment]
Yes as those are for third party devs to add as apps.

**Comment by PhpFoxJohnJr** [comment]
So how many years do we have to wait for Blogs for pages when it was already there once?
