### ISSUE TITLE
No share button for events: working as intended?

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1530]
I noticed that there is no way to share an event other then copying and pasting the link. Everything else has a share button so i was wondering if that was working as intended..

**Comment by neil96** [comment]
It's available on feeds, but not avaible on event detail. If you want a share button on event detail, you can request [here](https://github.com/moxi9/phpfox-feature-requests).

**Comment by jhayden2000** [comment]
So the thought was to have users share by going down the newsfeed and finding the original post? Ok i will request it there. Thank you..
