### ISSUE TITLE
Theme cannot be uploaded: "Phrase" error

### ISSUE THREAD

**Issue by hybride** [moxi9/phpfox#1531]
Hi there, 

Creating any theme throws an error – "Unable to load phrase: New Theme". If the source code is modified (PFC.Src > Core > Phrase.php, line 36-7
`if (!isset(self::$_phrases[$language_id][$hash])) {
                error('Unable to load phrase: ' . $phrase);` 

to disable that line, you can create a theme, but then all wording in the live edit disappears. If you comment to enable again, you cannot access the theme.

**Comment by Data66PF** [comment]
I wasn't able to reproduce this on v4.4 when I made a theme for the new video on making themes.

**Comment by hybride** [comment]
Turns out, original subfolder installation was faulty; upon reinstalling it, system works now.
