### ISSUE TITLE
newsletter output with images show up as links

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1533]
I tested a newsletter today, (with BBCode editer) from which i copied and pasted the contents of a newsletter that i have saved in my google drive into the html field. In the HTML field, the newsletter shows:
![newsletter2](https://cloud.githubusercontent.com/assets/20259022/16633933/95d4da3c-4399-11e6-8345-cdfec6ee2a17.png)

But when it is sent to me, all the photos show up as links that i can click on instead of displaying the image.

![newletter3](https://cloud.githubusercontent.com/assets/20259022/16633979/cf3f3466-4399-11e6-993f-5e2fed3cb583.png)

**Comment by neil96** [comment]
@jhayden2000 
Our deafult Newsletter do not support **BBCODE**, If you want to send a email with image, please put original html here.
I tested and it's working.

**Comment by jhayden2000** [comment]
Ok.. wow. Thats like a step backwards from V3..
