### ISSUE TITLE
Photos still uploading sideways. SMH.

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1535]
Another bug I thought was fixed. Photos are still being uploaded sideways.

**Comment by Data66PF** [comment]
Can you please try it at our staging site http://v4.phpfox.com/stage/ and if it does it there, please link the post for us, or the photo or whichever.

**Comment by Data66PF** [comment]
That staging is v4.4 and please no adult images

**Comment by queenmother305** [comment]
There is no way for me to definitively test it there because I do not know which specific device is being used that are causing this issue. All I know is on my live site several members are still uploading photos that appear sideways despite the upgrade to beta and this issue being marked fixed.

**Comment by Data66PF** [comment]
Does your server have PHP 5.5 and up? I forget what you may have said before about that. Please ask a few of your users which device and browser. It will help us narrow down the issue. I'll test tomorrow with my iPhone 5c.

**Comment by Data66PF** [comment]
http://v4.phpfox.com/stage/photo/
http://v4.phpfox.com/stage/photo/46/image/ and two in the feed, plus the black cat. I can't reproduce it on the staging with an iPhone 5c

**Comment by Data66PF** [comment]
Please test once we release RC version.
