### ISSUE TITLE
Avatar Crop gone?

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1536]
when a user uploads a pic they are no longer taken to the avatar crop screen afterward.

**Comment by Data66PF** [comment]
Do you have the setting to force cropping enabled in user group settings? It is required to set and works fine on the staging for the group I set it to.

**Comment by Data66PF** [comment]
Well it seemed to work but once I tried to save it, nothing works on chrome. Will bug this in case we need to do something more to it.

**Comment by queenmother305** [comment]
I didn't have it set to force cropping because mobile users encounter alot of issues, however I remember you telling me that you guys were implementing a new crop routine. Is that in the current release? If not then I can't set it to force, I would have however still liked it to be optional.

**Comment by neil96** [comment]
This feature conflicts with IM app. Fixed on 4.4.
You can test again [here](http://v4.phpfox.com/stage/).
