### ISSUE TITLE
user side - when upload photo it says failed but no reason why ?

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1538]
![user-side-failed-image-no-reason-why](https://cloud.githubusercontent.com/assets/17736688/16689303/f3aef51c-44e7-11e6-9624-cfb9e5cd5261.PNG)

**Comment by spirogg** [comment]
Can we get a proper error why the img failed, not correct image file type or to large of image please, etc

**Comment by neil96** [comment]
Please check again config: "upload_max_filesize" on your server, usergroup setting "photo.photo_max_upload_size" on AdminCP and file size you uploaded.

**Comment by Data66PF** [comment]
This is actually working as designed as it was not designed to show a specific error message. IMO, this needs to be a feature request to change as a fix would require us to change the default routine.
