### ISSUE TITLE
pages - like and unlike- won't work on Home and Info - should this be called follow - unfollow ?

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1539]
hi beta 4.4.0-1 win10 firefox latest php5.5 

when you click on PAGES and try to click on like or unlike from Home or Info it doesn't work, but on all others it works example: Blogs Events Discussions Music Photos Videos unser these  if you click it will like or unlike. 

Also should this say Follow and UnFollow instead since it is saying how many followers see photo

![page-like-unlike-also-should-this-be-called-follow](https://cloud.githubusercontent.com/assets/17736688/16690695/b5831294-44ee-11e6-8f56-b455f6faebb0.PNG)

**Comment by spirogg** [comment]
PS this is fresh install of beta 4.4.0-1

**Comment by Data66PF** [comment]
Regarding not able to click, I cannot reproduce at our live demo https://v4.phpfox.com 

Regarding changing it, you can change it in the phrase manager but if you want us to change how something is designed, please file a feature request for that part.

**Comment by spirogg** [comment]
Closing now. Will request in feature request. Will wait for next version RC and test again. Thanks
