### ISSUE TITLE
Pages home and info can't select drop down or admin settings, IM, etc when in mobile chrome

### ISSUE THREAD

**Issue by spirogg** [moxi9/phpfox#1540]
Hi when you go to Pages , and click on home or  info, you cant select drop down or click on admin settings, IM, etc when in mobile chrome. Won't allow you click on those links. 
Fresh install 4.4.0-1 php5.5 Nexus 6p chrome browser.

**Comment by spirogg** [comment]
Sorry go to pages and select s page. Then try to click in one if the links to open drop down , IM - chat, view new friends etc. Doesn't work. 
Thanks

**Comment by neil96** [comment]
I can't reproduce. Can you reproduce on our stage [demo](http://v4.phpfox.com/stage/)?

**Comment by Data66PF** [comment]
I also can't reproduce this with macbook using chrome at our stage.

**Comment by Data66PF** [comment]
Please test once we release RC version.
