### ISSUE TITLE
[4.4.0-beta1] Friend Module - When Friend Suggestions is active icons are not loaded

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1541]
When 'Friend Suggestions' option in Friend Module is active, the icons (Fontawsome) are not loaded in the entire site.

**Comment by neil96** [comment]
Could you give us a screenshot?

**Comment by Spaninet** [comment]
![](https://community.phpfox.com/PF.Base/file/attachment/2016/07/82092a8de4a8b80d88f2e45f9e7b2240.png)

**Comment by neil96** [comment]
I can't preproduce on my localhost and [stage demo](http://v4.phpfox.com/stage/)
Do you enable any 3rd?

**Comment by Data66PF** [comment]
Please only use default theme and no third party apps when testing a beta.

**Comment by Data66PF** [comment]
Please test once we release RC version.

**Comment by Spaninet** [comment]
It's default theme with colors changed and other few changes.

OK.
