### ISSUE TITLE
[4.4.0-beta1] Countries - I've losed all states/provinces after upgrading

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1542]
After upgrading from v4.3.2b5 to 4.4.0-beta1 I have losed all states and provinces that I have added manually one by one for all countries.

**Comment by neil96** [comment]
I can't reproduce this issue on my side.

**Comment by Spaninet** [comment]
I haven't losed the countries. Only losed all states and provinces for all countries.

**Comment by Data66PF** [comment]
Please test on RC when released today

**Comment by Spaninet** [comment]
I have already losed everything and cannot test again.

**Comment by neil96** [comment]
Did you not backup your site before the upgrade?

**Comment by Spaninet** [comment]
No, sometimes I don't make complete backups.
