### ISSUE TITLE
[4.4.0-beta1] Important issues in feed

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1543]
- After upgrading I see a lot of duplicate posts.
- The feed is slower
- It's loading 3 times/pages and then begins from page 1.
- The main feed appears in some user's feed.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1526

**Comment by Spaninet** [comment]
This issue could be related to the issue #1526 that you mentioned but is not the same. This is for the main wall (news feed) and friends wall.

**Comment by neil96** [comment]
@Spaninet Did you enable Redis cache?

**Comment by Data66PF** [comment]
Please test at our staging site to see if it has the same issue. We have redis enabled there. Please make sure you did not upgrade a live site and that your site has no third party products since we said not to test the beta with any third party products.

**Comment by Spaninet** [comment]
It's affectting the upgraded site. In a clean site i have not seen this issue.

**Comment by Data66PF** [comment]
Just an FYI from our core developer:
"Just an FYI, there are 2 areas you can use Redis. One is in "Performance". This is used for the Feed and some other areas. This data is intended to be static. The other area is "Data Cache". If they use Redis in both areas, the 2nd area (Data Cache) will cause problems for the first area as it will constantly purge the cache. If they want to use Redis in Data Cache they have to use another Server (Host)."
Make sure you have it set up properly. 

Please test on RC when we release that.

**Comment by Spaninet** [comment]
OK.
