### ISSUE TITLE
4.4.0 Beta1 Filename visible while uploading images

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1545]
when we compose message and made some attachments full file name is visible to end users.this can be serious security issue.why full file name is visible here. Test on 4.4.0 Beta1
![message compose bug](https://cloud.githubusercontent.com/assets/13433124/16755292/b0b9474c-4818-11e6-9aca-5f4e92a9aaa6.png)

**Comment by neil96** [comment]
What's serious security issue here?

**Comment by SalmanKhan86** [comment]
it show the site full file path structure

**Comment by neil96** [comment]
It's not a bug. It's not hard to know file path structure of a site, event big sites.
