### ISSUE TITLE
Social Media Importer Picasa

### ISSUE THREAD

**Issue by wrsantiago** [moxi9/phpfox#1547]
Hello I am double checking the whole site before I take it live, the problem is that I just found that when I try to connect to picasa its open a window like this:

https://drive.google.com/file/d/0B6RQrVAoG6XGR1Q0Y0FEYXVrUWs/view?usp=drivesdk

With the openid,younetid????

Is this by default? Should I setup a new id? How do I do it?

Contacting BryZar suggested contacting YouNet and asking why their app is pointing to them. We think it should show your own id there but, as we have not used that app, we are not 100% sure. If you have a link to the app at the store so we can see the app's instructions, it might say where to set things up or perhaps they have a wiki for how to set up the openid information.

**Comment by Data66PF** [comment]
This is the official phpFox bug tracker. It is not for third party apps. Please contact younet at their site for issues with their apps.
