### ISSUE TITLE
Neutron 4.4 Beta Released Music not loaded

### ISSUE THREAD

**Issue by comemoreru** [moxi9/phpfox#1548]
Music not loaded......you can upload, but you need to click several times until the swapping will not start

**Comment by Data66PF** [comment]
Please test on RC when released today but please ensure not to test with third party products active.

**Comment by comemoreru** [comment]
Where can I check? the translation is bad ... I'm sorry.

**Comment by comemoreru** [comment]
ok

**Comment by comemoreru** [comment]
No, the problem remained.....Spinning Download icon ... If you repeatedly click on download, you download.

**Comment by comemoreru** [comment]
Everything is fine! Manually removing unneeded files /PF.Base/file/settings

**Comment by comemoreru** [comment]
Hi! What was that? it....my site was unavailable.....also was unavailable store.phpfox.com .... on my website there was a message : cannot find license.....It means that, if phpfox will not, then my website will not be too?

13.07.2016, 12:59, "Data66" <notifications@github.com>:
