### ISSUE TITLE
4.4 Groups mobile version Descriptions

### ISSUE THREAD

**Issue by bamafanz** [moxi9/phpfox#1550]
This may of already been reported. On mobile version the word Members is cut off in Groups

**Comment by bamafanz** [comment]
This applies to whether someone has Joined a Group or not a member of a particular group.

**Comment by Data66PF** [comment]
I can see on the live demo that if I visit with an iPhone 5c and log in. Then go to a Group in the Groups app, the Join/Unjoin covers the Members word.
v4.4 RC

**Comment by bamafanz** [comment]
Im on android, using Samsung 6
