### ISSUE TITLE
4.4 Page speed insights

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#1551]
Dear team, 

I checked the demo site https://v4.phpfox.com/ after V4.4 is updated. Still there seems to be issues with page speed performance which are crucial for SEO:

1) Eliminate render-blocking JavaScript and CSS in above-the-fold content
2) Prioritize visible content
3) Minify JavaScript
4) Optimize images

More details can be found using PageSpeed insights: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fv4.phpfox.com%2F&tab=desktop

**Comment by Data66PF** [comment]
Please test on your own test site and enable, https://docs.phpfox.com/display/FOX4MAN/Bundle+JS+and+CSS as our demo doesn't have it enabled.

**Comment by Data66PF** [comment]
We allow one issue per bug tracker. Our core developer will look at this after you test on your own site and if it has more than one issue in it, it will be closed.

**Comment by Data66PF** [comment]
As this is not really a bug report, but are feature requests, we will close this. Please note that gtmetrix is more for features than bugs and that each report must have only one item in it should you decide to file a feature request or several feature requests in our feature area.
