### ISSUE TITLE
4.4 CSS Validation issue

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#1552]
Dear team, 

V4.4 has noticed W3 CSS validation errors. It has been detailed out here: https://goo.gl/MKIGdh

**Comment by neil96** [comment]
@srikumar101 

There are some **CSS code** only understands on _this browser_, but do not understand on _the other browsers_. So when you scan error _under a certain standard_, you'll see errors, that is normal. I tried with facebook.

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.facebook.com%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en
