### ISSUE TITLE
4.4.0-RC1 Cover Pic Android 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1553]
cover pic size is not fit in mobile browser view with default theme.
![cover size bug](https://cloud.githubusercontent.com/assets/13433124/16829805/80d45b6a-49b8-11e6-8f86-df1e574f630c.png)

**Comment by phpfoxdev** [comment]
It's up to Cover Photo Size, for your specific need, it needs custom work.
