### ISSUE TITLE
4.4.0-RC1 Bundle JavaScript & CSS

### ISSUE THREAD

**Issue by comemoreru** [moxi9/phpfox#1554]
When switching on simultaneously Bundle the JavaScript & CSS and Redis URI , pass in the music, insert the audio file, click "upload" - link appears in a new window https://**********.EN/upload iblock

If you disable JavaScript & CSS there are no problems.

**Comment by comemoreru** [comment]
4.4.0-RC1 Bundle JavaScript & CSS 
Why when this function is enabled, there is a conflict with the site? Which file needs to be /PF.Base/file/settings/************* .sett.php ? the contents of this file?

**Comment by comemoreru** [comment]
![budle](https://cloud.githubusercontent.com/assets/13656185/16949823/7ab961ba-4dc5-11e6-8f5f-c037342f9fda.png)

**Comment by Data66PF** [comment]
Is this still an issue in our stable release?

**Comment by comemoreru** [comment]
Yes

28.07.2016, 16:24, "Data66" <notifications@github.com>:

**Comment by neil96** [comment]
Which php version are you using?

**Comment by comemoreru** [comment]
5.5

29.07.2016, 04:30, "Neil J." <notifications@github.com>:

**Comment by comemoreru** [comment]
php 5.5

**Comment by comemoreru** [comment]
Will fixed it in next version?

**Comment by SalmanKhan86** [comment]
4.5.0
