### ISSUE TITLE
Can't Post Announcements 

### ISSUE THREAD

**Issue by LMG123** [moxi9/phpfox#1558]
After submitting the announcements they don't show.
4.4 RC1 Fresh Install.
No Mods
PHP 5.6.13
Video proof: https://www.dropbox.com/s/faupo7emmmjtbkc/announcements.mp4?dl=0

**Comment by Data66PF** [comment]
Can you make sure open_basedir is not enabled?

**Comment by LMG123** [comment]
Here is what I got: http://prntscr.com/btdclj
Going to enable debug.

**Comment by LMG123** [comment]
Here is with debug enable when I submit the announcement:
http://prntscr.com/btdlxl
http://prntscr.com/btdm8y
http://prntscr.com/btdml4
I don't have any Idea how to read or fix this.

**Comment by LMG123** [comment]
@neil96 Can you please look into this?
If you need access to my cPanel or Site in order to find out if there is a server or script issue let me know.

**Comment by neil96** [comment]
@LMG123 I checked your issue but I can't reproduce. This problem might your server or site config. Please try again on other environment.
