### ISSUE TITLE
Problem with Left Menu's Scroll Bar

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#156]
The left menu scroll bar is very difficult to use . I tested it in IE, Firefox and Chrome. sometimes it don't respond and we have to use it by selecting an item and then using arrow keys.

**Comment by Data66PF** [comment]
What OS are you using to test?

**Comment by aakash83** [comment]
win 7 .

**Comment by Data66PF** [comment]
Can you provide a screenshot? I don't see a scrollbar on the left menu http://community.phpfox.com/

**Comment by aakash83** [comment]
1386 * 768 screen resolution , win 7. chrome,firefox,IE.  We also have a menu bar in admin panel's left menu but that one is working fine. only this one is problematic.
![image](https://cloud.githubusercontent.com/assets/406030/8861055/3ac3401c-3188-11e5-8214-ceef4603bc9d.png)

**Comment by Data66PF** [comment]
Tested with win 8.1 pro on firefox. Made my screen 1280 x 768 and saw the scroll bar when putting the mouse over the left menus but the scroll bar works fine for me. Marked this to test in win 7.

**Comment by djeber** [comment]
when you click on it doesn't work

**Comment by Data66PF** [comment]
That's why this is labelled for win 7 as it works fine for me in win 8.1 pro. I can move it and I can click any of the menus and it works.

**Comment by aakash83** [comment]
Now i upgraded to windows 10 and it is still not working. so the problem is not with OS.

**Comment by RaymondBenc** [comment]
What part of the scrollbar does not work? The links it self or clicking on the scrollbar? Does the mouse wheel not work in order to go up or down?

**Comment by aakash83** [comment]
links are working . problem is with scroll bar only.it don't move up or down when we click it to go up or down. the one in the admin panel is working normally.

**Comment by Data66PF** [comment]
Added it as bug status as several can reproduce it

**Comment by aakash83** [comment]
thnx you marked it as bug. plz remove win 7 label as it is not OS dependent.

**Comment by aakash83** [comment]
Same scroll bar in admin panel is also not working properly. sometimes it works and sometimes it don't. if it is possible please remove these scroll bars as we don't have a scroll bar in legacy theme.

**Comment by one44** [comment]
This issue still not resolved. This is a critical bug for those who want to or have added extra pages or functionality and used menu for navigation as it puts menu items off the screen below page size.

**Comment by one44** [comment]
This is still an issue with non neutron themes but by sync CSS under themes it works.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8

**Comment by one44** [comment]
Not sure but updating theme also helped fix this.
