### ISSUE TITLE
ssl PHPfox_Facebook

### ISSUE THREAD

**Issue by comemoreru** [moxi9/phpfox#1561]
/PF.Site/Apps/PHPfox_Facebook/assets/autoload.js
Сейчас:
$Ready(function(){$('.image_object:not(.fb_built)[data-object="fb"]').each(function(){var t=$(this),i=new Image(),src='**http:/**/graph.facebook.com/'+t.data('src')+'/picture?type=square&width=200&height=200';t.addClass('fb_built');i.onload=function(){t.attr('src',src);};i.src=src;});if(!$('.fb_login_go_cache').length){var l=$('#js_block_border_user_login-block form');if(l.length){l.before('<span class="fb_login_go fb_login_go_cache"><i class="fa fa-facebook-official"></i>Facebook</span>');}else{l=$('.guest_login_small.pull-right');l.append('<span class="fb_login_go fb_login_go_cache"><i class="fa fa-facebook-official"></i>Facebook</span>');}}$('.fb_login_go').click(function(){PF.url.send('/fb/login',true);});});

Нужно:
$Ready(function(){$('.image_object:not(.fb_built)[data-object="fb"]').each(function(){var t=$(this),i=new Image(),src='**https**://graph.facebook.com/'+t.data('src')+'/picture?type=square&width=200&height=200';t.addClass('fb_built');i.onload=function(){t.attr('src',src);};i.src=src;});if(!$('.fb_login_go_cache').length){var l=$('#js_block_border_user_login-block form');if(l.length){l.before('<span class="fb_login_go fb_login_go_cache"><i class="fa fa-facebook-official"></i>Facebook</span>');}else{l=$('.guest_login_small.pull-right');l.append('<span class="fb_login_go fb_login_go_cache"><i class="fa fa-facebook-official"></i>Facebook</span>');}}$('.fb_login_go').click(function(){PF.url.send('/fb/login',true);});});

**Comment by neil96** [comment]
Please use English here and write bug detail.

**Comment by comemoreru** [comment]
Sorry. The error POPs up if You have a certificate for your domain. A warning that the site is not protected. Therefore, it is necessary to replace http to https.........At /PF.Site/Apps/PHPfox_Facebook/assets/autoload.js

The next update of phpfox I just didn't want to replace it manually. Thank you!

**Comment by comemoreru** [comment]
The same vulnerability is present in paypal

**Comment by comemoreru** [comment]
Hi! I asked you, you forgot to rewrite to https
