### ISSUE TITLE
You cannot create a category Neutron 4.4 RC Released

### ISSUE THREAD

**Issue by comemoreru** [moxi9/phpfox#1562]
Instead of a category, instead of the text - here it is blog.blog_category_59e78fb0d3a6724ce9253c48fdcceae8

The same problem in all categories (forums, blogs, groups, etc.)

**Comment by neil96** [comment]
We use phrase for all categories, where did you see that phrase?

**Comment by comemoreru** [comment]
When I add a category, let's say in the blog.......instead of text  blog.blog_category_59e78fb0d3a6724ce9253c48fdcceae8

**Comment by comemoreru** [comment]
![fixsa](https://cloud.githubusercontent.com/assets/13656185/16903992/faa83012-4c95-11e6-8562-458e95ac8f37.png)

**Comment by neil96** [comment]
It's working on my side. Which data cache do you using?

**Comment by comemoreru** [comment]
redis

**Comment by comemoreru** [comment]
Replaced redis on , Cache Driver: file System .... it's working, everything is fine, correct

And what could be the problem with redis? I have redis server installed.... PHP version:
5.6.0beta1

**Comment by neil96** [comment]
With Redis, it's wroking after you cleared cache.

**Comment by comemoreru** [comment]
4.4.0-RC1 Bundle JavaScript & CSS 
Why when this function is enabled, there is a conflict with the site? Which file needs to be /PF.Base/file/settings/************* .sett.php ? the contents of this file?

**Comment by Data66PF** [comment]
Is that a different topic? Each bug report can be only for one topic.

**Comment by Data66PF** [comment]
I see you already reported the javascript issue in another bug report. Please keep it to that topic as this is not for that issue.

**Comment by comemoreru** [comment]
ok

**Comment by Data66PF** [comment]
Is this resolved?

**Comment by comemoreru** [comment]
yes
