### ISSUE TITLE
Nginx Connection Timing Out

### ISSUE THREAD

**Issue by rjdjohnston** [moxi9/phpfox#1563]
I upgraded to 4.3.x running Nginx. Finally got the site running with the Nginx config below. The problem now is the site runs way to slow. Something is making the connections time out and throw this error:

> 2016/07/19 18:14:10 [error] 15148#0: *212 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 180.76.15.139, server: www.mysite.com, request: "GET /ebcradiolive/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "www.mysite.com"

Here is my config:

`server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        client_max_body_size 500M;

        root /vhosts/greatphpfoxsite.com/html;
        index index.php index.html index.htm;

        # Make site accessible from http://localhost/
        server_name www.greatphpfoxsite.com;
        location ~ ^/index.php/.*$ {
                        try_files $uri $uri/ /index.php?$args;
        }

        location / {
                rewrite ^/file/(.*) /PF.Base/file/$1 last;
                rewrite ^/static/ajax.php /index.php last;
                rewrite ^/themes/default/(.*) /PF.Base/theme/default/$1 last;
                rewrite ^/(static|theme|module)/(.*) /PF.Base/$1/$2 last;
                rewrite ^/(Apps|themes)/(.*) /PF.Site/$1/$2 last;
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include /etc/nginx/fastcgi.conf;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_connect_timeout 60;
                fastcgi_send_timeout 180;
                fastcgi_read_timeout 180;
                fastcgi_buffer_size 128k;
                fastcgi_buffers 8 256k;
                fastcgi_busy_buffers_size 256k;
                fastcgi_temp_file_write_size 256k;
                #fastcgi_intercept_errors on;
                include fastcgi_params;
        }

    location ~* ^.+\.(jpg|jpeg|css|swf|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|js)$ {
            root    /vhosts/greatphpfoxsite.com/html;
    }

    location ~* ^.+\.(mp4|mp3|flv|mov|avi)$ {
        rewrite ^/(.*)$ http://media.worldviewweekend.com/$1;
    }

    location ~ /.htaccess { deny all; log_not_found off; access_log off; }
    location ~ /.htpasswd { deny all; log_not_found off; access_log off; }
    location = /favicon.ico { allow all; log_not_found off; access_log off; }
    location = /robots.txt { allow all; log_not_found off; access_log off; }
    
    location = /backup {
        deny all;
    }
}
                                                                                                                    1,1           Top
`

**Comment by neil96** [comment]
Please ask question on our [community](https://community.phpfox.com/forum/). Here for bug tracker only.
