### ISSUE TITLE
group app video issue

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1569]
earlier today i had a user in the 4.4.0 RC version that lost the "videos" option above the status field. so they saw the Post and Photo button, but no video button. I had them log off and back on and they were ok. Not sure if anyone else has seen this but i thought i should let you know.

**Comment by Data66PF** [comment]
This seems like a random site issue as I cannot reproduce it at our demo. Should you be able to reproduce this at our demo, please open another bug report as we will close this for now.
