### ISSUE TITLE
[4.4.0-RC] Groups App - Duplicate categories after upgrading

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1570]
I have duplicate categories in groups after upgrading from 4.4.0-Beta to RC.

![](https://community.phpfox.com/PF.Base/file/attachment/2016/07/3c6fd35d6a0910f1eb79bb4dfbec13b4.png)

**Comment by neil96** [comment]
This is bug of 4.4.0Beta. We fixed on 4.4.0RC for new site.
We don't fix in case upgrade from beta to RC.
