### ISSUE TITLE
[4.4.0-RC] Facebook Base App - No profile photo

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1571]
Registred users using facebook have blank profile photo and cover.

Facebook profile photo only appears in **AdminCp >> Search**.

In previous versions (eg: 4.3.2b5) was working fine.

**Comment by lordofnos** [comment]
Same issue for me... when browsing members the photo shows up but not on the profile or on the user menu at the top right.

**Comment by lordofnos** [comment]
Changing the app with an older version that worked before does not solve the issue.

**Comment by robert9592** [comment]
Please help us to check it again with current version of phpFox (4.4.2). If issue still happens please check your facebook app settings. We cannot reproduce it on our test sites.
