### ISSUE TITLE
Load comments via ajax breaks share

### ISSUE THREAD

**Issue by jhayden2000** [moxi9/phpfox#1575]
So, i painstakingly found this bug. i hope you guys can reproduce this. When i turn on "Load comments via ajax" the share button and the 3dot button in the marketplace, and blogs modules dissapear.

**Comment by neil96** [comment]
Which version did you test?

**Comment by jhayden2000** [comment]
RC1

**Comment by jhayden2000** [comment]
i have done a fresh new install with RC1

**Comment by robert9592** [comment]
This setting will be removed from phpFox 4.4.2
