### ISSUE TITLE
Problem with @Username

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1580]
when we search some users with @ sign then some html characters appears with username. in social Network sites this is not like the way its currently working. it can be appear as hyperlink with @sign +username. that looks like great without html characters.
i check it on Phpfox demo site 
![username with sign](https://cloud.githubusercontent.com/assets/13433124/17092742/2e4d0358-5262-11e6-81f6-f48d5dfec182.png)

**Comment by SalmanKhan86** [comment]
Need to modify attachFunctionTagger() function in feed.js

**Comment by Data66PF** [comment]
This is how it is designed. Once you hit the share, it will show the username. It has always worked like this. To change features, please file a feature request.
