### ISSUE TITLE
Language settings link

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1583]
There no language settings link in Admincp -> Settings

I can access it with url only "admincp/language/"

Upgraded site
Version 4.4

**Comment by neil96** [comment]
We moved it to main menu (below Themes).

**Comment by Ylmzef** [comment]
Can you update the upgrade instruction please?

https://docs.phpfox.com/display/FOX4MAN/Upgrading+Your+phpFox+Website

> Run Find Missing Phrases in AdminCP >> Settings >> Language and click to the left of the default English language to run this.

**Comment by neil96** [comment]
I updated on docs.
