### ISSUE TITLE
Nothing happens when photo uploading failed

### ISSUE THREAD

**Issue by akvaskov** [moxi9/phpfox#1585]
Hi,
When I'm posting big photos, uploading stops due to a size limit for images. The PF shows a respective list of failed uploads and that's all: there are no any buttons, for an instance, "Cancel" or "Continue". It makes users confused, they don't know what to do further.

![photo upload failed](https://cloud.githubusercontent.com/assets/18528411/17164247/1b3a55e0-53cf-11e6-809b-61fe10784219.png)

**Comment by comemoreru** [comment]
I agree

**Comment by Data66PF** [comment]
This looks to be a feature request but will leave for a core developer to determine.

**Comment by neil96** [comment]
I think so too. Please open a new request [here](https://github.com/moxi9/phpfox-feature-requests).

**Comment by akvaskov** [comment]
Hi,

I have moved this issue to the feather request section but from my point of view that's obviously a bug.
