### ISSUE TITLE
Google reCAPTCHA Problem 4.4.0 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1588]
when i enabled Google reCAPTCHA in apps with google site key and secret key then i am not able to  sign up error msg comes after green checked  (captcha failed Try Again).i have try many times but no result.i have fresh install Latest 4.4.0 Stable Version.i have not enabled Phpfox captcha in Setting>Registration.
![google recapcta](https://cloud.githubusercontent.com/assets/13433124/17176347/e861c300-5429-11e6-8b31-0f73f99ffcc7.png)

**Comment by SalmanKhan86** [comment]
Any Update on this

**Comment by Data66PF** [comment]
Does it do that for you on our demo?

**Comment by Data66PF** [comment]
My development site seems to work fine for recaptcha. I'm not using cloudflare on that particular dev site. Not sure if you are.

**Comment by SalmanKhan86** [comment]
i am having same problem with google recaptcha. i am surprise why this is can't reproduce at your end. what is cloudflare you are taking abount.
![recaptcha failed](https://cloud.githubusercontent.com/assets/13433124/17329208/3a6996be-58df-11e6-970c-649781bf65f0.png)

**Comment by neil96** [comment]
Could you set up a fresh site of 4.4.0 and check again this issue. This problem might come from server or site configuration.

To know what is cloudflare, please visit here: https://www.cloudflare.com/

**Comment by SalmanKhan86** [comment]
i have fresh install 4.4.0 and we are not using cloudefare

**Comment by Data66PF** [comment]
What does developer browser console show in the Network and Console tabs when you try to register?

**Comment by SalmanKhan86** [comment]
Developer browser Console results

![browser console](https://cloud.githubusercontent.com/assets/13433124/17436642/2659c8f2-5b36-11e6-869f-b605d657f72f.png)
