### ISSUE TITLE
Google reCAPTCHA Sign up Button

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1589]
when i enabled Google reCAPTCHA in apps with google site key and secret key then sign up button is missing.i have fresh install Latest 4.4.0 Stable Version.
![sign up button missing](https://cloud.githubusercontent.com/assets/13433124/17176398/3043fd00-542a-11e6-8587-a06ed186df03.png)

**Comment by Lukey199223** [comment]
I've never seen a sign up button anyway *_*

**Comment by Data66PF** [comment]
This was posted a few times before and explained that this his how google does it. They take over the sign up form submission with their own anti-spam recaptcha.
