### ISSUE TITLE
No "Photos" menu on user's page - Neutron 4.4.0

### ISSUE THREAD

**Issue by akvaskov** [moxi9/phpfox#1590]
When browsing any user's page (doesn't matter if it's own one or of any other user), there is no Photos menu. It means that if I want to browse photos, I need to list the feed down. Of course, that's not a right way.
![no photos menu on user s page](https://cloud.githubusercontent.com/assets/18528411/17204371/cebde76a-54ad-11e6-878e-4cbe97a654f5.png)

Another option is to put and use a respective "Photos" block on some sidebar or to try to find pictures through the "Photos" menu on the main menu ribbon but that's not a right and covinient way as well because the block can be removed due to any design issue and the "Photos" menu has own bugs (will described later in a separate issue post.

**Comment by Data66PF** [comment]
Please test at https://v4.phpfox.com as I cannot reproduce the issue

**Comment by akvaskov** [comment]
Hi Donna,

Really stange behavior of the system. Now the Photos menu appeared in my profile menu.

![user s photos](https://cloud.githubusercontent.com/assets/18528411/17239459/e53468b0-556c-11e6-9a9c-20b267e173ba.png)

But! I deceided to delete all photos. After I had done that, I realised that they disappered from the Photos page but they are still dispalyed in the Photos block on my profile page. What can be a problem? Caching of data?
![user s photos_after deletion_2](https://cloud.githubusercontent.com/assets/18528411/17239474/0ac30ca8-556d-11e6-8092-2eb80440b55d.png)
![user s photos_after deletion](https://cloud.githubusercontent.com/assets/18528411/17239477/0f19f99c-556d-11e6-9013-d487323c9dd0.png)

**Comment by akvaskov** [comment]
But now I have another question. I deceided to delete all photos. After I had done that, I realised that the Photos menu diappeared again. Is it right? Is it possible to keep this menu even if no photos were uploaded before? Is there any setting for that?
![user s photos_after deletion](https://cloud.githubusercontent.com/assets/18528411/17239694/cb4a4102-556e-11e6-8439-070bf8aa92b5.png)

**Comment by Data66PF** [comment]
This is working as designed. Please ask questions at the forum for settings as there is one for this but we need to answer at the community https://community.phpfox.com .
