### ISSUE TITLE
The "Photos" page shows images not properly - Neutron 4.4.0.

### ISSUE THREAD

**Issue by akvaskov** [moxi9/phpfox#1592]
Hi,

When I try to browse photos throught the respective menu in the main menu ribbon, I face some strange behavior of the system.
Please, check some screenshots below. I hope you will understand what I mean.
![my photos](https://cloud.githubusercontent.com/assets/18528411/17205198/62fd1d84-54b2-11e6-9f17-9d38753815bb.png)

![all photos](https://cloud.githubusercontent.com/assets/18528411/17205207/68dc8e42-54b2-11e6-87a5-7b8e4f73d90b.png)

![my albums](https://cloud.githubusercontent.com/assets/18528411/17205208/6cad020e-54b2-11e6-8712-77345b8ce492.png)

![all albums](https://cloud.githubusercontent.com/assets/18528411/17205212/70d693cc-54b2-11e6-9c20-c96b74fd1c33.png)

**Comment by Data66PF** [comment]
This is how it is designed. Photos loaded to the main feed are comments and not content.
