### ISSUE TITLE
Export of themes and apps not working

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1593]
On v4.4 final i can not export themes or apps. The zip-files have 0KB. Not fixed for me...

#1546 #1544

**Comment by neil96** [comment]
It's working on my side, even turn on debug mode. Which php version are you using?

**Comment by lordofnos** [comment]
tested with php 5.6.22. when debug mode is enabled it shows me "page not found". what else can i check?

it was a clean install with 4.4 beta, upgraded to rc, upgraded to final... same issue with all versions. export with 4.3.2 works fine.

**Comment by Data66PF** [comment]
Is this working for you now? You put a theme in the store so I assume it is working.

**Comment by lordofnos** [comment]
i designed the theme in 4.4 exported it with 4.3.2 and tested the exported zip on 4.4 ;) thats my workaround for the issue at the moment

**Comment by phpFox-webwolf** [comment]
I found this:
/var/web-hosts/phpFox40/public_html/PF.Base/module/admincp/include/service/module/module.class.php line 333 'PF.Base/module/' . PHPFOX_DS should read 'PF.Base/module' . PHPFOX_DS  (extra slash).  This fixed my export problem.

**Comment by lordofnos** [comment]
does not fix the theme issue. i will check the code in PF.Site\Apps\PHPfox_Flavors\lib\Flavor.php around line 359 export function...

**Comment by phpFox-webwolf** [comment]
Maybe line 399?  Why is there a backslash before Phpfox?
I had forgotten that there was a similar issue in the file PF.Base/module/admincp/include/service/product/product.class.php at line 170.  Try removing the \ at the beginning.

**Comment by neil96** [comment]
> /var/web->hosts/phpFox40/public_html/PF.Base/module/admincp/include/service/module/module.class.php >line 333 'PF.Base/module/' . PHPFOX_DS should read 'PF.Base/module' . PHPFOX_DS (extra >slash). This fixed my export problem with a product.

Thanks @phpFox-webwolf . Extra slash will be ignored by most systems. I fixed this issue. I will find and fix the same issues on our platform.

**Comment by lordofnos** [comment]
not working for me with themes on 4.4.1 dev site. exporting apps not tested yet...

**Comment by lordofnos** [comment]
i found out that with phpFox v4.4 i have to set "post_max_size = 30M" in php.ini to get the export working.

**Comment by neil96** [comment]
What's size of your apps/themes?
Is it working now?
