### ISSUE TITLE
Blog Report Option

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1596]
i have the option to Report my own blog.that really strange.how can i Report blog created by me.i have fresh install stable 4.4.0
![blog report problem](https://cloud.githubusercontent.com/assets/13433124/17249485/c9dbbafe-55bd-11e6-91f1-568709eb6c5b.png)

**Comment by Data66PF** [comment]
I can see this issue but it is like this on the entire site. I believe it would be considered an enhancement (feature request) to change the behavior.
