### ISSUE TITLE
Notification Tabs not clearing

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#1598]
All of the Notification Tabs takes opening them more than once to clear the notifications... Wasn't doing this in v4.3.2b5...

Version 4.4.0 Stable
CentOS v6.8 & cPanel on my Personal Private Dedicated Server
Firefox, Chrome, and IE

**Comment by SalmanKhan86** [comment]
Yes Same Problem i am also facing this issue.

**Comment by Data66PF** [comment]
Did you disable ajax? https://docs.phpfox.com/pages/viewpage.action?pageId=2097770 try that and clear cache and see if it helps.

**Comment by SalmanKhan86** [comment]
No we have't disable it

**Comment by Data66PF** [comment]
Try that as we asked please. With ajax on, this works as designed.

**Comment by Data66PF** [comment]
With ajax off, I cannot reproduce any issue. Please disable the ajax if you want this to behave differently as it works as designed with ajax on.
