### ISSUE TITLE
After 4.4 update, cover image & avatar does not show on pages 

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1599]
After 4.4 update, cover image & avatar does not show on pages on on the home and info pages, but shows on blog, forum, events etc...

**Comment by TrueAmericans** [comment]
The same thing is happening in the Groups too!

**Comment by comemoreru** [comment]
Run Rebuild Bootstrap Core routine.
Clear your cache.

**Comment by prepperz** [comment]
rebuild bootstap @ clear cache does not resolve it.

**Comment by comemoreru** [comment]
Application look can old installed and modified css

**Comment by neil96** [comment]
Please clear your cache first, then rebuild bootstrap core.

**Comment by comemoreru** [comment]
yes

**Comment by prepperz** [comment]
still same issue

**Comment by comemoreru** [comment]
remove all apps and clear the cache

**Comment by prepperz** [comment]
still same

**Comment by comemoreru** [comment]
you with what version of phpfox has been updated?

**Comment by comemoreru** [comment]
phpFox 3.9.0 (Legacy version)?

**Comment by neil96** [comment]
@prepperz I checked this issue on your site.
It's the same with #1605

**Comment by prepperz** [comment]
Ok. I am able to reproduce this issue. I asked if it was possbible if the, "remove files no longer used" could be the culprit in the support ticket, but you didn't bother looking in to it and dismissed it and told me I need to look at my source.  It's not the source.

This time I reproduced it on a stock set-up. The issue occurs when you select to delete files no longer used and then you select the SFTP option with localhost.

Once the files are deleted. Go to the pages and select one that you know has cover image and an avatar. You will no longer see them anymore.

**Comment by neil96** [comment]
Thank @prepperz , now I can reprodcue this issue.

You can fix this issue by go to Admincp -> block -> select "pages.view" -> remove block "Feed Timeline"

**Comment by prepperz** [comment]
OK. I just tried your solution. It didn't work and still has the same result.
