### ISSUE TITLE
After 4.4 update, the existing non image avatar that are displayed are smaller

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1600]
After 4.4 update, the existing non image avatar that are initals are smaller: 
![screenshot_1](https://cloud.githubusercontent.com/assets/19594886/17269832/e8f1020a-5621-11e6-848e-5a8144a68c01.png)

**Comment by comemoreru** [comment]
when you updated the entire update procedure is done?

**Comment by comemoreru** [comment]
Run Rebuild Bootstrap Core routine.
This will delete any changes made to the default Bootstrap theme. Be sure you are never editing this theme. Always make a clone of it and edit that instead as this routine must be run on each upgrade.
 
Go to Themes and select Bootstrap and click to Edit it.
On the left menu, at the bottom, click to see the options and select Rebuild Bootstrap Core.

If you are not using Bootstrap as the default theme, you might not see the Rebuild Bootstrap core in the Bootstrap theme as it will show up in the theme that you have set as the Default theme so click your default theme and you will see it there.
Alternately, you can also find the Rebuild Core Theme in Maintenance >> Rebuild Core Theme. This will do the same thing as above. You can do either method.

**Comment by comemoreru** [comment]
Clear your cache.

**Comment by prepperz** [comment]
yup. Did all those. default stuff.

**Comment by neil96** [comment]
If you didn't modify your theme, please try:
- Clear your cache.
- Revert theme.
- Rebuild boostrap core.

**Comment by prepperz** [comment]
Still the same issue

**Comment by comemoreru** [comment]
remove all apps and clear the cache

**Comment by prepperz** [comment]
no change

**Comment by comemoreru** [comment]
what is the website?

**Comment by comemoreru** [comment]
Create a file named debug.sett.php.
In that file, put the following code,
<?php
define('PHPFOX_DEBUG', true);
Upload it to your server to PF.Base/file/settings/

**Comment by neil96** [comment]
@prepperz I checked on your site. It seems you had uploaded missing files or your code was customized. Please:
- Double check your source code on your server (make sure you didn't miss any files).
- Please revert customized code (if you did)
- Disable all third-party apps
and try again.

**Comment by prepperz** [comment]
What missing files are you referring to? Do you mean phpfox?

**Comment by comemoreru** [comment]
copy again all the files

**Comment by comemoreru** [comment]
remove all software, download the new version

**Comment by prepperz** [comment]
Not sure I understand what you are saying. Do you mean to upload phpfox v4.4 to the server again?

**Comment by comemoreru** [comment]
Yes. but first delete your application after you complete the upgrade procedure

**Comment by comemoreru** [comment]
https://docs.phpfox.com/display/FOX4MAN/Upgrading+Your+phpFox+Website

**Comment by prepperz** [comment]
I followed the exact instructions before. I will upload v4.4. again.

What do you mean by, "delete your application after you complete the upgrade procedure?"

Are you referring to the, "remove files no longer used?" if you are, that's already been done.

**Comment by comemoreru** [comment]
apps

**Comment by prepperz** [comment]
that already been done
