### ISSUE TITLE
Short URL issue (4.4 new setup)

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1601]
I opened a new site. I installed 4.4. However, the short URL button does not work, It doesn't respond ever.

![screenshot](https://cloud.githubusercontent.com/assets/8930862/17270022/04d22bd6-5661-11e6-8db5-b699df4c100d.png)

I created  .htaccess

**Comment by comemoreru** [comment]
Replace units for two, the example in the file
[.htaccess.txt](https://github.com/moxi9/phpfox/files/391890/default.htaccess.txt)

**Comment by comemoreru** [comment]
![primer1](https://cloud.githubusercontent.com/assets/13656185/17270723/bd350d5e-5672-11e6-9d45-8c6c986240bb.png)

**Comment by karargaht** [comment]
The file already exists

**Comment by comemoreru** [comment]
Replace

**Comment by karargaht** [comment]
"Enable Short URLs " button doesn't work

**Comment by comemoreru** [comment]
look carefully at my file

**Comment by comemoreru** [comment]
RewriteRule ^themes/default/(.*) PF.Base/theme/default/$2

**Comment by comemoreru** [comment]
RewriteRule ^(.*) index.php/$2

**Comment by karargaht** [comment]
wow it worked. very thanks (:

**Comment by comemoreru** [comment]
Happy for you
