### ISSUE TITLE
When on Pages the user icons disappears

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1605]
The below row of icons disappears when on Pages
![screenshot](https://cloud.githubusercontent.com/assets/19594886/17276023/fc8534e4-56e9-11e6-8cae-c3445b087f85.png)

**Comment by comemoreru** [comment]
You have a lot of problems, how to solve them you don't know.... Turn to the professionals!

**Comment by neil96** [comment]
@prepperz Can I reproduce your issues on your live site?

**Comment by prepperz** [comment]
Sure, I'll send it via support

**Comment by prepperz** [comment]
ok info sent

**Comment by neil96** [comment]
@prepperz I checked on your site, this is error (error 500) on your site, not a bug from core. Please sure all your third-party apps compatible with phpFox 4.4.0

**Comment by comemoreru** [comment]
I told him about it) he didn't want to do it

**Comment by prepperz** [comment]
This problem is related to issue: #1599
