### ISSUE TITLE
User ban issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1608]
Whe i ban a user via e-mail or IP i select yes for ban user option.
But the user still showing on Registered user group.

**Comment by Data66PF** [comment]
They will show up unless you remove them. What I do is copy their username and their IP and their email to the ban filters. https://docs.phpfox.com/display/FOX4MAN/Managing+Ban+Filters . After that, I delete the user. This is how it is designed. It has always worked this way as the user is not in some other group, they are still in registered unless you delete them.
