### ISSUE TITLE
Clicking on View more from index page cycles forever

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1609]
If you just keep clicking on view more it will keep cycling forever.

**Comment by neil96** [comment]
I can't reproduce on our demo and my test site. Please give us detail steps to reproduce.

**Comment by prepperz** [comment]
This occurs for site that upgrading from 3.x to 4.4

Once logged in, from the home page. Just keep clicking view more.

**Comment by comemoreru** [comment]
)))))))))))))))))))))))))

**Comment by Data66PF** [comment]
You need to be sure you followed all of the steps for cleanup after upgrading from v3 to v4.

**Comment by prepperz** [comment]
Followed it exactly and that was on a barebones default site, no mods or anything. Anyhow I did a fresh install afterwards. Will do another test upgrade from 4.32 to 4.4 again on another site.
