### ISSUE TITLE
Remember me feature on login not working

### ISSUE THREAD

**Issue by dhanyashree91** [moxi9/phpfox#1612]
Remember me check box on login page is not working. Even if user selects Remember me check box and login to the application. Later re-login is not populating the password.

**Comment by Data66PF** [comment]
It is not to remember the password. It is to keep the user logged in. As long as they don't close the browser and clear cookies, they will stay logged in. If they want to remember passwords, they need to use a browser tool for that as our script doesn't have a feature like that as it would be insecure.

**Comment by dhanyashree91** [comment]
Without clicking remember me check box one can remain logged in, As long as they don't close the browser and clear cookies. I don't find a reason for remember me check box on login page when its of no use. And this was stupidest answer one can give as a developer.
