### ISSUE TITLE
Phpfox_phrase on front end

### ISSUE THREAD

**Issue by mrfenix** [moxi9/phpfox#1614]
It appears that the phrase variable is being pulled through to the front end under the "Recent" forum block. This isn't always displayed, it only shows up when the first bit of text in the thread is a quote. 

Using Phpfox v4.4. See below:

![recent_posts](https://cloud.githubusercontent.com/assets/234915/17450731/34c11ef0-5b62-11e6-9f4c-2eac9aaec1d9.png)

**Comment by Data66PF** [comment]
https://v4.phpfox.com/forum/thread/131/fitness-test-thread/ am I testing this correctly? If not, please do a test at our demo.

**Comment by mrfenix** [comment]
@Data66PF If you take a look at the "Recent Posts" here https://v4.phpfox.com/forum/2/general/ you can see a similar result where [quote] and BB codes are pulled through. Is there no way to strip it out?

**Comment by neil96** [comment]
@mrfenix I see your post from January, 2014. This issue might come from data of older version. Can you reproduce this issue with new posts?

**Comment by Data66PF** [comment]
The Quote and BBcode is due to the html being removed and how it works at our community so I believe that part is working as designed. As for your issue with phrase showing, did you check what neil asked?
