### ISSUE TITLE
Settings : This setting group has no available settings.

### ISSUE THREAD

**Issue by delixyr** [moxi9/phpfox#1615]
![firefox_2016-08-07_01-53-09](https://cloud.githubusercontent.com/assets/4602841/17458909/2a8b5ba4-5c42-11e6-93f9-acdf63cd060f.png)

I cant see any options under settings in Admin account.
Running 4.4.0

**Comment by Data66PF** [comment]
This looks like an install issue. As this tracker is for bugs, please either submit a ticket via the client area or please post at our community https://community.phpfox.com .

**Comment by SadiqUltra** [comment]
It not a bug. As phpfox is not compatible with strict SQL mode. I have solved this problem with following steps:
create a file:
```
sudo vim /etc/mysql/conf.d/disable_strict_mode.cnf
```
and add those line
```
[mysqld]
sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
Then restart mysql
```
sudo service mysql restart
```
Done :)
