### ISSUE TITLE
videos disappear when setting feed limit

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1617]
since the video app gets the links from the main feed the older videos disappear when setting a feed limit. it would be really nice if shared videos get their own area in the database instead of saving them within the feed record.

**Comment by Data66PF** [comment]
If you want a feature changed, please file a feature request in regards to having a separate database table.

In regards to the bug, we'll have to test.

**Comment by Data66PF** [comment]
Confirmed if we set the feed limit (days) it makes videos disappear.

**Comment by lordofnos** [comment]
this could be more a solution than a feature request ;)

**Comment by Data66PF** [comment]
That solution would be a bigger fix than an if statement :)
