### ISSUE TITLE
USA States dropdown not appearing when people register

### ISSUE THREAD

**Issue by zmediacritic** [moxi9/phpfox#1618]
On my website, getgroover.com, when people click REGISTER, a registration screen appears, when they select United States, a new dropdown of USA States should appear but it doesn't.

**Comment by Data66PF** [comment]
Confirmed that the states are not showing on registration after selecting the United States as the country. This works fine on the profile edit page though. It used to work on registration previously.

**Comment by zmediacritic** [comment]
Can someone fix it please? thanks! rob

**Comment by Data66PF** [comment]
We do fix the bugs. Please wait for it to be marked fixed and the version it will be fixed in. For now, have your users set their states in their profiles.

**Comment by LMG123** [comment]
This works fine for me on my fresh Install from today. 
http://prntscr.com/c3epfr
http://prnt.sc/c3elm3

**Comment by Data66PF** [comment]
My site is an upgraded, both are. Not sure if it's that or not but it is not showing for my installs. I did run all of the final stuff and states do show on profile selection.

**Comment by Data66PF** [comment]
Now this works. This is a random issue that could be a glitch with internet, browser, or site.

**Comment by zmediacritic** [comment]
So you cannot fix the bug? I don't understand what you are saying. rob

**Comment by Data66PF** [comment]
I tested again today and I can't reproduce it. It seems like a glitch perhaps. If you have support, you could send a support ticket or try to upgrade to 4.4.1 which was released today and follow all of the upgrade steps posted in the tutorial for upgrading. See if that helps.

**Comment by zmediacritic** [comment]
I'm sorry but I don't know what you mean when you say you can't reproduce it. Please go to my website www.getgroover.com and you can see the bug.  If I upgrade to 4.4.1, will I lose my theme and my addons from YouNet?  Rob

**Comment by LMG123** [comment]
Rob, Did you tried with the default theme?

**Comment by zmediacritic** [comment]
LMG123: I did not try with the default theme, I am using a theme I purchased from YouNetCo.com.

**Comment by LMG123** [comment]
Before any changes please BACKUP!
If you know how to do it try to enable the default phpfox theme and look if you see the states.

**Comment by Data66PF** [comment]
Please test with default Bootstrap theme to rule out theme issues. I cannot reproduce this issue now in my tests. Please be sure to clear cache after enabling the default bootstrap theme for testing.
