### ISSUE TITLE
Invite in Pages and Groups Not Working Right

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#1619]
This pertains to ver 4.4.0 Stable... When you want to invite someone or numerous members to you Page or Group it only gives you the first 30 members. Then you have to find others using email or name. Problem is, if they are in excess of the first 30 members, it won't find them. Why can't we have it like it was where you click on view more to go through the member list and select the members to invite? The way it is now you don't get to invite everyone you want to invite.

**Comment by Data66PF** [comment]
To be clear, we are looking at this for the Pages module and not Groups app as each bug needs to be for one thing. I will go test the Pages module at the demo where I have thousands of friends to test with. :)

**Comment by Data66PF** [comment]
I have thousands of friends on this account, https://v4.phpfox.com/Data66/friend/ and am able to search for any friend I am looking for. It finds them in my manage pages >> invite section. I enter the user name, such as Vivian, and hit enter, it then finds that user and displays them in the list.  If I enter just "viv" without quotes, it shows a few members that have viv in their names. This appears to work fine.

If you mean you want a listing to show all friends, that is not plausible as someone with 5000 friends like my account would crash the server bringing them all up to invite. However, you could submit the feature request but it seems too heavy a setting to consider.
