### ISSUE TITLE
Sharing Post in to other social sites

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#162]
Sharing icons like facebook or twitter are not showing up on the share under post. Even if all are "ENBLED" or "YES/ACTIVE") in my Share setting.

![sharing](https://cloud.githubusercontent.com/assets/13417524/8798383/93ebf6aa-2faa-11e5-9224-c20c3fe2dacd.png)

**Comment by Data66PF** [comment]
The share module is not enabled in the code yet. I am not sure it is going to be or if there will be an app for it or if it is meant for third party devs to add them

**Comment by Verdz** [comment]
I think this is a very good feature for any PHPfox site, hope this will be enable waiting for this feature.

**Comment by RaymondBenc** [comment]
The **Share** module has been depreciated with v4 and the feature to share to Facebook and/or Twitter is being developed as an app and will be released shortly.

**Comment by Data66PF** [comment]
There is also the Buffer App that is already in the store :)
