### ISSUE TITLE
Blog Image Link Show on the Blog Index

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox#1620]
Hi, Since you build this V4. I'm still waiting to improve the blog page. This image link is messing up the blog main page and for me this is not good to show the image address on public.

![blog](https://cloud.githubusercontent.com/assets/16037019/17566665/03847512-5f45-11e6-85eb-c404ef4479b9.jpg)

Thank You

**Comment by Data66PF** [comment]
This is how it is designed. You would need a feature request to change it.

**Comment by juniortimeline** [comment]
Yes. It would be great to hide this image link address. Thank you

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-feature-requests please check our feature requests and if a search doesn't bring up this request, please add it.
