### ISSUE TITLE
Main content limit and HTML?

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1624]
I'm adding some code  and the YouTube post in the main content section, but the background disappeared

![ssss](https://cloud.githubusercontent.com/assets/8930862/17636552/8db97a0a-60e6-11e6-86cf-151767768ee6.png)

![wwww](https://cloud.githubusercontent.com/assets/8930862/17636688/79ec37a0-60e7-11e6-8417-55f11fc40e51.png)

**## Version: 4.4.1**

**Comment by Data66PF** [comment]
I can't reproduce this on a cloned theme, noting that you can't edit the default bootstrap theme as it will cause issues and will get overwritten on each upgrade as it is part of the steps.
