### ISSUE TITLE
No thumbnails or images when sharing specific video page on Facebook

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1625]
When sharing a video page from phpfox site on facebook there are no thumbs or images of the video.

**Comment by Data66PF** [comment]
This appears working as designed. However, a core developer can confirm if so.

**Comment by prepperz** [comment]
If that is the case, then it is very sad as a social net. I think all old features of phpfox early days with an updated code base and functionality would probably do much better then what we have today by a longshot as a social net platform. IMHO.

**Comment by neil96** [comment]
IMO, It should be an enhancement.

**Comment by Data66PF** [comment]
Ok we will chose this as this is for bugs only. https://github.com/moxi9/phpfox-feature-requests for features, please file the request there @prepperz

**Comment by prepperz** [comment]
ok feature request is here: https://github.com/moxi9/phpfox-feature-requests/issues/216
