### ISSUE TITLE
Feeds on a members wall not truncated and appears cut away?

### ISSUE THREAD

**Issue by GQTool** [moxi9/phpfox#1626]
I noticed that feeds which show on a members wall are not truncated to # amount of text they are, what appears to be, displayed in a frame or insert and it cuts away the top of the text away. this occurs when you add a thread in a forum or  blog post. It looks broken and as if the text is not rendering to the user. I can see this in the demo site running 4.4.1. 

expected: As with other social media platforms, the text should be truncated, and not cut away the top of the text of a line which can not be displayed.

![text not truncated](https://cloud.githubusercontent.com/assets/20559501/17720243/c7069e70-6463-11e6-939e-b16de149a4e5.jpg)

**Comment by Data66PF** [comment]
For our core devs, he doesn't mean on the member wall (profile) but also on the main feed.
