### ISSUE TITLE
Admin approve threads before being made public error

### ISSUE THREAD

**Issue by GQTool** [moxi9/phpfox#1627]
v4.4.1  (MySQL 5.5.49) and trying to post a new thread and I am getting an error.

"no_items
undefined"

**This occurs when you set a user group type for peer to peer forum approval.**
1. Go to Admin
2. Go to user group settings > forum
3. Change for user group:
4. Approve threads before they are displayed publicly?: Yes
5. Can approve forum threads?: Yes
6. Approve forum posts before they are displayed publicly?: Yes
7. Can approve forum posts? Yes
8. Go to the site > forum
9. Create a new thread > submit
10. Approve thread > results in described error

"no_items
undefined"

**Once posted you can go back to settings and change:**
- Approve threads before they are displayed publicly?: No
- Approve forum posts before they are displayed publicly?: No
1. Clear Cache
2. Go back to Forum
3. Approve thread > results in described error.

Observed behaviour:

If you then delete the "Thread" post (that you can not approve) the count goes down 1, but the issue with this is that it never goes up 1 when you post the thread as you can not approve it. This is problematic if you only have 1 thread you would like new users to read and it says "0".

Expected: If this is not an option then we should not be allowed to set this configuration, or enable user group peer approval.

**Comment by Data66PF** [comment]
I can reproduce this but it won't be common for people to allow someone that can approve things to be needing approval as it defeats the purpose of the setting. However, I can reproduce it so will mark a bug for us to fix the issue. Perhaps the toggle for one should not work if the other is set or an error show regarding the conflicting settings.
