### ISSUE TITLE
Creating a page category requires refesh to see the actual name

### ISSUE THREAD

**Issue by GQTool** [moxi9/phpfox#1628]
V4.4.1 Using Firefox Latest, as per Spec for 4.4

Go to AdminCp > settings> pages>  create category> add name> save

Results in the code name of the category and you have to refresh the browser before the name appears.

![create a category](https://cloud.githubusercontent.com/assets/20559501/17725719/08612868-6491-11e6-80da-641376425e91.jpg)

Video Category shows no name until refresh.
![create a category video](https://cloud.githubusercontent.com/assets/20559501/17725790/a3c20520-6491-11e6-950b-233532ece312.jpg)

**Comment by neil96** [comment]
This is a cache issue, please clear cache and try again.
P.S: This issue is fixed on 4.5.0.
