### ISSUE TITLE
No online notification after v4.4 update

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1630]
I'm still getting email notifications, but no online notification.

**Comment by Data66PF** [comment]
Please test with default, unedited Bootstrap theme and ensure that all upgrade steps were followed, especially the finishing steps. I cannot reproduce any issue at our demo https://v4.phpfox.com with default, unedited theme.

**Comment by prepperz** [comment]
Yep. I can reproduce it on the demo site.

to reproduce

1. post on your status.
2. on another browser with a different account, like and comment on the status. 
3. now go around the site click on any site link, you'll notice there is no red ntification until you refresh.

**Comment by Data66PF** [comment]
Please post feature requests in our feature area, https://github.com/moxi9/phpfox-feature-requests

**Comment by prepperz** [comment]
OK I created a  feature request, but seriously? This is not a bug?  Who goes around the site hitting refresh all the time? Just sayin' lol

**Comment by neil96** [comment]
@prepperz The notification still update after some minutes, so I marked this as enhancement.
