### ISSUE TITLE
Deleting pages Video from main video link Does Not Delete feed

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1631]
When deleting a video, it does not delete the feed.

**Comment by Data66PF** [comment]
Tested at our demo and cannot reproduce this either.

**Comment by prepperz** [comment]
I can reproduce the issue on the demo site.

1. goto pages. create a page.
2. select the 3 dots then select video. paste in a youtube video.
3. select video from the main menu. then click on the video
4. click on the edit then select the delete option

you see that it is not completely deleted, See it on on the demo site: https://v4.phpfox.com/v/

You can see the video, "Imagine" song video remnants.

**Comment by Data66PF** [comment]
This bug said nothing about Pages. Please be more thorough with your bug titles. It is very important.
