### ISSUE TITLE
Groups page not showing up in amincp

### ISSUE THREAD

**Issue by ryanmiller159** [moxi9/phpfox#1632]
Users are limited with 500 kb group page photo. When viewing the user group setting under register user . there is no group page settings . 
![capture](https://cloud.githubusercontent.com/assets/21185363/17876099/74d209aa-68a5-11e6-8ded-e462dad4318d.PNG)

**Comment by Data66PF** [comment]
Please be sure to read our documents. https://docs.phpfox.com/display/FOX4MAN/Enabling+and+Managing+the+Groups+App. It would be good to bookmark our documents for future reference.
