### ISSUE TITLE
Meta keywords and Meta description

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#1633]
Dear team, 

I'm using v4.4.1b2, On Admin CP we have an option to set meta tags and meta descriptions for blogs, friends, photo, poll, quiz. 

These meta tags and description don't actually show up in respective pages even after setting them. 

For example. Set blog meta keywords to blog1, blog2

Go to your website.com/blog right click view source, it will not show blog1, blog2 in meta keywords, instead it is inherited from main site keywords. 

Please let me know if more information is required.

**Comment by Data66PF** [comment]
After setting, did you clear cache?

**Comment by srikumar101** [comment]
Yes Donna.. I did.

**Comment by srikumar101** [comment]
Also.. I see that SEO_META table in database in empty.. not sure where these meta fields are getting stored.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-feature-requests please post feature requests in our feature area.

**Comment by srikumar101** [comment]
But this is already there in V4.4 right.. its just that it is not working.. how can it be an enhancement.. shouldn't this be treated as bug when it exits in the current version and not working?

**Comment by Data66PF** [comment]
Our core developer marked it an enhancement so it must be something that would not be a currently supported feature.

**Comment by neil96** [comment]
@srikumar101 If you reload the page, the meta tags are correct, but if the page is loaded by ajax, the meta tags don't update, it still shows tags of the first page. But that isn't a problem because search engine or other sites do not use ajax to load a page.

**Comment by srikumar101** [comment]
Hi Neil.. 

I tried reloading the screen as well, however the meta keywords still reflect main pain keywords only and not the one I had set it to blog.

**Comment by Data66PF** [comment]
Please disable sitewide ajax.
