### ISSUE TITLE
New theme does not work. 

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1635]
When I create a new theme, this theme does not work. 

![new theme](https://cloud.githubusercontent.com/assets/15389101/17994821/da066df4-6b64-11e6-883c-e6a397c88721.png)

**Comment by neil96** [comment]
@Criotin Please give us more detail steps to reproduce this issue.

**Comment by Criotin** [comment]
I'm creating a new theme, then I go to the editing of the theme, and there is a white screen there, and I can change nothing .
https://community.phpfox.com/forum/thread/55249/pictures-and-notifications/

**Comment by neil96** [comment]
@Criotin I can't reproduce with your information you gave.
On that thread, I confirmed issue with upload profile photo. I quoted the post that I replied.

**Comment by Plofstoffel** [comment]
I had the same issue. 

Also see there is no "Design" Menu item.

I fixed it by copying Bootstrap Flavor to my new themes flavor.

Hope it helps

**Comment by neil96** [comment]
@Plofstoffel If you clone a new theme from Boostrap, you will see the "Design" menu. Your problem is different to this issue.

**Comment by Criotin** [comment]
I cloned a new theme from Bootstrap.

**Comment by Data66PF** [comment]
Curious if you set the default language to English and then try making another theme, does it work fine?

**Comment by Criotin** [comment]
Using the English language, the result is the same. Folders assets, flavor, HTML are created empty.

**Comment by Criotin** [comment]
![newtheme](https://cloud.githubusercontent.com/assets/15389101/18006868/6174e140-6baa-11e6-8e4b-dabbc0a69439.png)

**Comment by neil96** [comment]
It might only your site issue. Could you submit us a ticket with your site info, so we can support you better.
