### ISSUE TITLE
Browser back/next  button not working fine on phpfox

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#1636]
tested on v4 demo and community . - mozilla and safari on mac 

when we click back button on browser , the uRL changes but pages doesnt change.

**Comment by neil96** [comment]
I can't reproduce. On your PC, is it wroking fine with other sites?
Ref: #1210

**Comment by Data66PF** [comment]
This is ajax. It has to be refreshed to work. I have the same issue on some browsers until I enabled the browser settings. If I could remember which settings I would let you know. Some browsers are disabling things for "safety".

**Comment by shakti7188** [comment]
by browser setting - you mean setting in browser or in admincp ? if you are talking about setting in browser then dont bother to search becasue we cant ask our users to do that setting but if in admincp then i m intrested to the setting .

**Comment by prepperz** [comment]
I've notice this too. I think he means The back buttons work, but when it is click it does not go back in the same order.
