### ISSUE TITLE
The picture with Russian title is not loaded on avatar.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1637]
When I try to upload a picture with Russian title on avatar, rotating loading circle appears, and it lasts forever. The picture is not loaded.

**Comment by comemoreru** [comment]
Bundle JavaScript & CSS - INCLUDED?

**Comment by Criotin** [comment]
Где я могу это проверить?
Where I can check it?

**Comment by comemoreru** [comment]
/admincp/app/?id=PHPfox_Core&group=core_redis

26.08.2016, 12:30, "Criotin" <notifications@github.com>:

**Comment by Criotin** [comment]
Выключено
Turned off

**Comment by comemoreru** [comment]
You probably installed something left..... I can't reproduce it....

26.08.2016, 12:30, "Criotin" <notifications@github.com>:
