### ISSUE TITLE
Check-in Places.js

### ISSUE THREAD

**Issue by Plofstoffel** [moxi9/phpfox#1638]
HI,

I have a issue with the check in option. 

Google made some changes that will not allow location based services run on normal Http, it now requires Https.

And after moving to Https I still could not get it to work.

I recieved the following error:
places.js:544|Uncaught TypeError: Cannot read property 'LatLng' of undefined

However that is where the issue is en not the solution.

On Line 509 in places.js:
if (typeof google !== 'undefined') {

Needs to change to 
if (typeof google**.Map** !== 'undefined') {

This will fix the error.

The reason being that the script to Load google.Map is never inserted.

Regards,
Shaun

**Comment by neil96** [comment]
I test and it works with both http and https.
What errors did you get?
