### ISSUE TITLE
Notifications Buttons Not Working Right

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#1639]
Ver. 4.4.1, CentOS 6.8 Linux, cPanel current version... All Browsers...
When we get Notifications like Friends Requests, Likes and Comments, and Messages, you have to click on them 2 or 3 times before the number disappears like it's supposed to... Should only take one click like it has been in the past...

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1630 this is how it works with ajax.

**Comment by TrueAmericans** [comment]
Not True! Ajax makes things work... It doesn't make things require more to work...

**Comment by neil96** [comment]
@TrueAmericans We saw this issue and it fixed on 4.5.0.

**Comment by TrueAmericans** [comment]
Thank you neil96! I wonder how long before we get to that one since 4.4.2 was released today? Seems an awful long ways out.

**Comment by neil96** [comment]
Sadly, 4.4.2 is not included this issue. Please wait for next version.
