### ISSUE TITLE
Share Post Module Not Working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#164]
When we share someone post and haven't write anything in write box only first time its shows warning msg. after that its turn into InActive Mode and does't do anything

**Comment by Data66PF** [comment]
I can confirm this if the user doesn't follow the warning a second time and tries to post it without putting any text but it would be very odd for a user to do that.

**Comment by SalmanKhan86** [comment]
second time if i put text in it then it is not posted.just hang on that
![share post not working](https://cloud.githubusercontent.com/assets/13433124/8819318/f9799928-3068-11e5-802e-4357a1f1adb6.png)

**Comment by SalmanKhan86** [comment]
how can we remove this warning msg. 

so that user can share photo without write anything

pls suggest
