### ISSUE TITLE
deleting recaptcha app breaks the registration

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1642]
i don´t know if this is working as designed so i mention this issue here. when the recaptcha app is deleted in the apps folder the register button disappears.

maybe there should be a list of phpfox apps that are essential for the script to work? when clients dont use recaptcha or cdn apps it is obvious for them to delete those apps. another idea is to name the apps something like core_recaptcha. that would be also nice to whitelabel our sites. last but not least for security reasons...

**Comment by neil96** [comment]
reCaptcha is a CORE APP, if you don't use kindly disable it from adminCP.
