### ISSUE TITLE
Cyrillic alphabet in the database

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1643]
Instead of the Cyrillic alphabet in the database tables are written here such codes:

![cyrillic alphabet in the database](https://cloud.githubusercontent.com/assets/15389101/18092286/7056c1ba-6ed4-11e6-91d6-e602e46f97b4.png)

**Comment by Criotin** [comment]
If I put in the file:
PF.Base / include / library / phpfox / parse / input.class.php
on line 968 "return $str;" then the problem disappears.
How will this fix affect to the further operation of the system?
![cyrillic alphabet in the database 2](https://cloud.githubusercontent.com/assets/15389101/18092315/889b7630-6ed4-11e6-8354-4474d848909d.png)

**Comment by neil96** [comment]
Our database is designed to store all languages. When you view in database, it might display incorrect, but when you view in web, it will display correct.
The same with #248

**Comment by Criotin** [comment]
The problem is that these codes makes it impossible to search for some or other database data.
For example, in setting up "language / phrase" I ordered the word "друг", this word appears in the database as code and when searching of this word the result will be not found.
It is definitely worth to fix.

**Comment by neil96** [comment]
Is it search feature of phpFox or search feature from phpmyadmin (or something similar)?

**Comment by Criotin** [comment]
I translate new words into Russian in phpfox admin panel. When I search these words in the database phpmyadmin, they are not found the data, because they are in the form of codes there.

**Comment by neil96** [comment]
Does it work if you search on site?

**Comment by Criotin** [comment]
If the translated word is written with a capital letter and during the searching you write it with a capital letter, then it is found. If the translated word is written with a capital letter and during the searching you write it with a small letter, it is not found.

**Comment by senivoleg** [comment]
+ у меня тоже не работает
