### ISSUE TITLE
Searching to add Admin to Pages not displayed

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1646]
When searching for admins to add for pages, it only displays a maximum of 11, anyone after that does not show up. There's not even a pagination or a scroll option.

**Comment by Data66PF** [comment]
IMO there needs to be a limit. Once we start typing a name, it narrows it down. I don't believe that anyone would have more than one user with the same username. I believe this is working as designed for optimal performance. Querying too may database entries (example if a site has millions of members) can cause bad performance.

**Comment by prepperz** [comment]
Some names don't come up even with search

**Comment by neil96** [comment]
> Some names don't come up when typed

Which are names?

**Comment by prepperz** [comment]
Basically any profile from previous versions that contains, "profile-xx" in the username field will not show up in when searching to add admins for pages.

![screenshot](https://cloud.githubusercontent.com/assets/19594886/18235946/f3bb4e54-72ee-11e6-826a-84395c3c8573.png)

**Comment by neil96** [comment]
@prepperz It's working in my test.

**Comment by prepperz** [comment]
I can reproduce it on 2 sites

**Comment by neil96** [comment]
>I can reproduce it on 2 sites

Please help me reproduce it.

**Comment by prepperz** [comment]
in order to reproduce the issue the users must contain the follwing data as in the image. 

![screenshot_2](https://cloud.githubusercontent.com/assets/19594886/18261612/289bcb1a-73c8-11e6-8d99-f40830506909.png)

Steps to reproduce.

1. Goto to "pages"
2. click on, "create a page"
3. Click on "admins"
4. search for the user that contains the example data sets and they will not show up in the search.

**Comment by phpfoxdev** [comment]
The search still works fine on our demo. It seems to be your site issue.

**Comment by prepperz** [comment]
How exactly are you searching?

**Comment by Data66PF** [comment]
I tried it exactly as you said at the demo. Try it at our demo. https://v4.phpfox.com/profile-3/ you can see my profile is as you need it. Search Donna and it will come up if we are friends. It works fine in our tests.

**Comment by prepperz** [comment]
OK I'm not going any further. I am tired. I'm sure if anyone see it they'll report it. Maybe.
