### ISSUE TITLE
When creating an ad picture is not shown

### ISSUE THREAD

**Issue by letomdev** [moxi9/phpfox#165]
When you create an ad (v4.0.2), the picture uploaded is not shown... Just a grey rectangle...

![capture](https://cloud.githubusercontent.com/assets/4182940/8798758/06a7e1c8-2fa5-11e5-8fd7-2fc2273a5186.PNG)
![capture](https://cloud.githubusercontent.com/assets/4182940/8798790/4591e9e2-2fa5-11e5-86f2-a4b39c0f984c.PNG)

**Comment by Data66PF** [comment]
I cannot reproduce this with current 4.0.2 version. 
![v4ad front end](https://cloud.githubusercontent.com/assets/6908282/8802699/3021f6c4-2f91-11e5-951a-b0543b2bc49b.png)

**Comment by Data66PF** [comment]
Please test with v4.0.3 as I can't reproduce the issue.
