### ISSUE TITLE
 profile feed is looping ...is now friends with...

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1657]
After upgrading to 4.4.2 on profile index the entry "...is now friends with..." is looping again and again after the feed loads more items or the button "View More" is pressed. Tested on two client sites and phpfox demo. Solved when feed module is exchanged with previous version of the module.

![feedloopingb](https://cloud.githubusercontent.com/assets/13225682/18401051/dd2ad2d4-76d8-11e6-85f9-da8c269c8a7c.jpg)

**Comment by Data66PF** [comment]
I had reported this internally last week and I believe it is fixed for v4.5 but will mark it a bug since it's here.
