### ISSUE TITLE
At overflow requests can not be displayed notification

### ISSUE THREAD

**Issue by websistema1** [moxi9/phpfox#1658]
Hello. When a notification appears much - Ajax does not work, there is an empty pop-up window. This applies to notifications and messages. In a small number of queries are displayed normally.
![notifications](https://cloud.githubusercontent.com/assets/14079310/18420123/0506ecc4-7874-11e6-9ba3-d8a97507a486.jpg)

**Comment by Data66PF** [comment]
Are you seeing this on the demo too? Do you mean that you don't see the notification amounts for IM messages too or is it just that it goes blank?

What browser and OS?

**Comment by websistema1** [comment]
Version phpfox 4.4.2. The error occurs in all browsers, Windows 7. The number of notifications displayed - shows an empty window, like in the image below. If you change the settings in the Notification settings - error disappears. Then when you receive new notifications - the error appears again. Some people are no mistakes -  if they have little or no notification.

This same error is seen in the messages. If the message has a long text - error occurs. To fix the error - I find this message in the database and delete it. It is necessary to limit the number of characters in the messages - would then not have this error.

I think that this is a problem Ajax.

Sorry for bad english. Sincerely.

**Comment by websistema1** [comment]
Error most likely associated with third-party components - Advanced Notification System from YouNet. After its removal, the error does not appear. Please, can close the ticket.
