### ISSUE TITLE
Load JS error

### ISSUE THREAD

**Issue by Nghiep-YouNet** [moxi9/phpfox#1661]
Go to admin > settings > performace > Activate " Bundle JavaScript & CSS " . When this option is active, the site cannot load js file.

**Comment by Data66PF** [comment]
I cannot reproduce this on my 4.4.2 test site. Used several test apps that require js and they all work fine.

**Comment by maniacscorpio** [comment]
i am facing this bug too......  
https://community.phpfox.com/forum/thread/55383/quot-bundle-javascript-css-quot/
