### ISSUE TITLE
The problems with a hashtag in Russian.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1662]
The problems with a hashtag in Russian.

https://v4.phpfox.com/hashtag/%D0%A5%D0%B0%D0%BC%D0%B5%D1%81/

![hashtag](https://cloud.githubusercontent.com/assets/15389101/18498321/4e5291dc-7a3e-11e6-8670-f2412b2a05de.png)

**Comment by Data66PF** [comment]
Социальное

Tested that tag
https://v4.phpfox.com/hashtag/%D0%A1%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5/
