### ISSUE TITLE
Video Thumbnails on Video Index page repeat

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1664]
After upgrade the thumbnails on my video page are stuck in an infinite cycle. I remember this happening once before. When you scroll down and the next set of thumbnails loads they end up being the same as the first. I also noticed videos are not being displayed in the order they were uploaded.

**Comment by Data66PF** [comment]
Did you follow all of the new instructions for upgrading?

**Comment by queenmother305** [comment]
i followed all the instructions on the upgrade page under documentation.

are you suggesting it's cron related? pedro was kinda enough to set up my cron but if i am missing a specific setting would you mind pointing me to it?

i am unable to test this bug on the phpfox demo site because u guys dont have enough videos, only a few on 1 page.

**Comment by queenmother305** [comment]
data please have a look at www.blackm4m.com/v/ (WARNING NSFW) you will see all of my videos are out of order. the dates are not in sync. i can assure you all steps have been followed in perfect order, cron is set up, core was rebuilt, mods have been disabled, old files were removed, cache was cleared.

**Comment by Data66PF** [comment]
If you need help, please submit a support ticket to phpFox. If it is not a bug, you will need paid support though. As we don't see this on our demo or our testing site that has a ton of content, right now we can't say it's a bug. Our tech can look and if he thinks it not a bug, will let you know to purchase support.
