### ISSUE TITLE
After Upgrading My Theme Disappeared

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1665]
my theme is still on my server but not on my site or in the admin panel after i upgraded. my default switched back to bootstrap.

**Comment by Data66PF** [comment]
What version did you upgrade from? If an old one, with old theme methods, you should be able to do the import as the tutorial says. https://docs.phpfox.com/display/FOX4MAN/Merging+Your+Customized+4.x+Theme+Into+4.2.1 this seems more an upgrade issue than a bug.
