### ISSUE TITLE
Ban Filters in Admin Never Closes

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1666]
The tab menu for ban filters never closes. It blocks access to important parts of the admin panel and no other tab menus can be opened. See attachment...
![screenshot 32](https://cloud.githubusercontent.com/assets/19175383/18551583/0cca14f8-7b27-11e6-825f-fcf19338d2ea.png)

**Comment by Data66PF** [comment]
This is from a third party app. You should disable third party apps before upgrading and check to get updates from each one.
