### ISSUE TITLE
Ad in the Marketplace

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1667]
If you add to the name of the ad in the Marketplace the sign "%", then the page will not open "400 Bad Request".

Fix it.

**Comment by Criotin** [comment]
I think that this is due to the fact that I use the Russian language. There is no error in the pure phpfox with the English language.

**Comment by Data66PF** [comment]
Can you give us an example name? Is it an Ad or a Marketplace listing?

**Comment by Data66PF** [comment]
https://v4.phpfox.com/marketplace/3/porsche-panamera-i-turbo-10/ this works

**Comment by Data66PF** [comment]
Пончики по доступным ценам 10%  
that worked for me. What is not working for you please?

**Comment by Criotin** [comment]
I mean, I use the Russian language on the site, not in the name of the ad.

**Comment by Data66PF** [comment]
Did you change the database collation?

**Comment by Criotin** [comment]
I fixed this problem by yourself.
