### ISSUE TITLE
Groups Pending Memberships

### ISSUE THREAD

**Issue by Coxion** [moxi9/phpfox#1668]
GROUPS pending membership function not working if the PAGES module is inactive.
![screenshot_216](https://cloud.githubusercontent.com/assets/20811897/18577218/4807323c-7be8-11e6-90b1-e7262bbe0471.png)
![screenshot_217](https://cloud.githubusercontent.com/assets/20811897/18577220/4815d4c2-7be8-11e6-90da-09ebc845dae8.png)
![screenshot_218](https://cloud.githubusercontent.com/assets/20811897/18577219/480f3252-7be8-11e6-86f8-2c3061fa5085.png)

**Comment by Data66PF** [comment]
I can't even make a Group if Pages is inactive. Will confirm as some clients don't want Pages and the Groups app needs to work with Pages disabled.
