### ISSUE TITLE
Check in not working

### ISSUE THREAD

**Issue by warrisdeepsingh** [moxi9/phpfox#167]
the check-in sign in the add status bar over lay the share button and if i choose photo upload then it shows no check in and 

check in is not working in posts...
![ass](https://cloud.githubusercontent.com/assets/10062636/8807377/c5fe1336-2ff9-11e5-8f4d-036bcefcbc42.PNG)
![sxxz](https://cloud.githubusercontent.com/assets/10062636/8807381/cb1779fc-2ff9-11e5-8f19-bc65671bf4aa.PNG)

**Comment by Data66PF** [comment]
I'll confirm this because I can't find where to set the google api key now in v4.0.3 and the link to it from the setting for enabling the checkin doesn't work.

**Comment by RaymondBenc** [comment]
Feature has been depreciated in v4 and an app is under development to better work with Googles new API.
