### ISSUE TITLE
Clicks are not displayed on the advertisements.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1671]
Clicks are not displayed on the advertisements in the admin panel.

![advertisements](https://cloud.githubusercontent.com/assets/15389101/18756729/abb7652a-80f9-11e6-8cbd-0940b4b06373.png)

**Comment by neil96** [comment]
Do you enable module track? We use track to count number of clicks.

**Comment by Criotin** [comment]
Where is this module?

**Comment by Criotin** [comment]
This module track?

![track](https://cloud.githubusercontent.com/assets/15389101/18786819/7bde663c-81a8-11e6-8899-f119cca78895.png)

**Comment by Data66PF** [comment]
I can reproduce this on my test site but will test further.

**Comment by Data66PF** [comment]
No matter what I do, it is not showing clicks. It shows views fine though. I do have tracking enabled.
