### ISSUE TITLE
Empty translation files

### ISSUE THREAD

**Issue by iogames** [moxi9/phpfox#1673]
Recently some language packs has been removed because they contain at least 2 empty files:
- phpfox-groups.xml
- phpfox-v.xml

But since phpFox v4, all new phrases added goes to the file:
- phpfox-language.xml

and they mix together with phrases from: themes, apps, functions, etc
So the previous files remain empty nonetheless all the phrases need it are present in the mentioned file...

So is this a bug? I tried to separate all the phrases manually from groups & video´s app and place them in the correct file, but is very difficult since they are sorted by date, mixed, interlaced...

**Comment by Foxgerman** [comment]
Same behavior here.

**Comment by cespiritual** [comment]
yes... I'm having the same problem. My language pack was also removed.

**Comment by Data66PF** [comment]
We are fixing this and answering the tickets.

Groups and Video are apps, module-v.xml and module-groups.xml shouldn't exist when export language phrase.
We are going to fix this issue on 4.5.0.
Now, kindly remove these files and try again.
