### ISSUE TITLE
cannot migrate groups

### ISSUE THREAD

**Issue by vizruta** [moxi9/phpfox#1674]
after activating the groups app iam not able to migrate the groups created from pages to group app.

**Comment by Data66PF** [comment]
To be more specific. Client has more than 200 groups in the pages module. They are in custom categories with custom urls. The buttons to migrate the groups (choose between cron or browser) do not show up as it shows "no groups to migrate" when clicking the menu link to Migrate Groups.

Client has an external third party language on the site, custom theme and not sure if there are apps (third party).

**Comment by vizruta** [comment]
the issue seems to be with the custom category as it is not recognizing in the group app...hence i tried and edited the custom category to default category present in the pages then the group app identified the groups present...

hence i guess the issue is occurring only with the custom category .....though iam changing to default category and migrating all my groups to groups app and changing back to custom category

**Comment by neil96** [comment]
Is your issue resolved?

**Comment by vizruta** [comment]
nope it worsened even more...after clicking convert via cron iam seeing this from past 4 hours http://prntscr.com/cpzxnh and nothing is happening and i have a bad feeling all my groups will be deleted

**Comment by neil96** [comment]
What method did you use?
If you use cron job, did you setup cron?

**Comment by vizruta** [comment]
yes my site is handled by Data
