### ISSUE TITLE
V4.4.2 and 4.4.3 - 92 modified files in  /admincp/checksum/modified/

### ISSUE THREAD

**Issue by kaligula7** [moxi9/phpfox#1677]
Hello everybody!

I have one problem, maybe someone else has already encountered the same problem?

After upgrade from version 3.9 to 4.4.2 I had 92 modified file (/admincp/checksum/modified/).

![modif](https://cloud.githubusercontent.com/assets/21354832/18982326/8aff2aa6-86e5-11e6-909c-d7f8e921ef9e.JPG)

I installed version 4.4.2 in the "development" folder.
I have the same files modified in the new software.

![modif develop](https://cloud.githubusercontent.com/assets/21354832/18982335/9b0fd36e-86e5-11e6-8793-3e21587de4cf.JPG)

After updating to version 4.4.3 error persists.

**Comment by robert9592** [comment]
Did you follow all steps of upgrade process (https://docs.phpfox.com/display/FOX4MAN/Upgrading+Your+phpFox+Website)? Did you complete the step "Remove Files No Longer Used"?

**Comment by kaligula7** [comment]
Ja, das habe ich gemacht - alle schritte nacheinander.
Ich habe auch zum testen eine jungfräuliche version ohne update installiert - der selbe Fehler.

**Comment by Data66PF** [comment]
English only please.

As for this issue, I can reproduce it. We have the ticket from the client to be checked.

**Comment by kaligula7** [comment]
SORRY!

Yes, I did - all steps in sequence. 
I also installed for testing a virgin version without update - the same error.
