### ISSUE TITLE
/bin/bash: /home/haytt/public_html/cron.php: Permission denied

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#1679]
After setup the cron job, we are getting the mail says "Permission denied" (/bin/bash: /home/haytt/public_html/cron.php: Permission denied) in cron job notification.

Is it any wrong setting? need to any attention?

**Comment by Data66PF** [comment]
Please contact your host. This is not for hosting issues or set up issues. It is only for bugs.
