### ISSUE TITLE
Developer Request - User Group Settings for Apps

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#168]
Please add a tutorial for adding user group settings for apps as many apps will need settings per user group. We used to be able to add settings in AdminCP but I don't see that option for apps and I don't see any of the free app examples that have user group settings. I see Settings for the app such as:

```
"settings": {
		"m9_facebook_enabled": {
			"info": "Facebook Login Enabled",
			"type": "input:radio",
			"value": 0
		},
		"m9_facebook_app_id": {
			"info": "Facebook Application ID"
		},
		"m9_facebook_app_secret": {
			"info": "Facebook App Secret"
		}
	} 
```

**Comment by RaymondBenc** [comment]
More info at: http://support.phpfox.com/apps/global-and-user-group-settings/
