### ISSUE TITLE
External Links Warning

### ISSUE THREAD

**Issue by kaligula7** [moxi9/phpfox#1682]
External Links Warning = YES
Redirect external hyperlinks is running in the same window.
v4.4.3.

**Comment by Data66PF** [comment]
I can't reproduce any issue. I share a link in the feed, I click the link, it goes to a page warning that I am about to go offsite to the link and to click to continue.

**Comment by kaligula7** [comment]
Sorry for my English.

  Yes, that's right, a page warning that I am about to go offsite to the link and to click to continue opens. But it opens in the same Tab (Window), as the main site. When you click on a link with a redirect, the site offers again in the same Tab. You are leaving your site.
There is no option "target = blank" from the main site.

**Comment by neil96** [comment]
It has been working like this from old versions. Default external links will open in new tab, but when you turn this setting on, it will open in the same tab.
But you can request us this feature [here](https://github.com/moxi9/phpfox-feature-requests).
