### ISSUE TITLE
Cron issue in site

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#1683]
We are getting these error msges in Cron mail notification.

/home/ssssgrr/public_html/cron.php: line 1: ?php: No such file or directory
/home/ssssgrr/public_html/cron.php: line 3: syntax error near unexpected token `true'
/home/ssssgrr/public_html/cron.php: line 3: `ignore_user_abort(true);'

**Comment by neil96** [comment]
Please check again your cron job config, maybe you miss something.
