### ISSUE TITLE
Login / Register Button No Longer Work After Upgrade to 4.4.3

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1684]
Users cannot login or register via the two buttons.

![screenshot](https://cloud.githubusercontent.com/assets/19594886/19014081/39f9c2ca-87b1-11e6-883e-c1f9cb4f010e.png)

**Comment by Data66PF** [comment]
Please test with default theme and ensure you followed all upgrade steps. We cannot reproduce any issue at our demo.

**Comment by lordofnos** [comment]
try if it makes a difference using "www." in front of your sites url. depends on what is set up in your settings file.
