### ISSUE TITLE
Unable to delete remnant bad feed from the previous video delete bug

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1685]
This bug was supposedly fixed, but it did't fix the videos that where previous deleted. As the video remnants are still displayed and there is no way to delete it. 

![screenshot1](https://cloud.githubusercontent.com/assets/19594886/19055156/a6ddc306-8990-11e6-95fe-cf5eef0c4c63.png)
![screenshot2](https://cloud.githubusercontent.com/assets/19594886/19055155/a6daf5e0-8990-11e6-8daf-5fb9e3a304b3.png)

**Comment by Data66PF** [comment]
Are you sure you ran all of the new steps for upgrading? We had the bug on our demo before upgrading and it is resolved there as the video removed that had been there.

**Comment by prepperz** [comment]
Yep. Ran all the step and it did not remove the remnant video link

**Comment by Promastertr** [comment]
I have the same problem

**Comment by neil96** [comment]
@Promastertr Please upgrade to latest version (4.5.0b3)
