### ISSUE TITLE
After 4.4.3 update Gift backend is blank

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1687]
![egift](https://cloud.githubusercontent.com/assets/19594886/19104810/8e125afe-8aac-11e6-81bc-3a483c5b3ffc.png)

**Comment by neil96** [comment]
It may be phrases issue, please turn debug on and put error (if have) here.

**Comment by Data66PF** [comment]
I cannot reproduce this as I added gifts to the demo after it was updated to 4.4.3.

**Comment by prepperz** [comment]
I will send it via support as I don't want the url to be displayed here

**Comment by neil96** [comment]
I saw the ticket, this is a site issue only.

**Comment by prepperz** [comment]
Hmm... I little detail might help... thanks

**Comment by Data66PF** [comment]
Did you clear cache after toggling it off?

**Comment by Data66PF** [comment]
Ok I see. Tested on local and cleared cache. Disable egift and it still shows in menus.
