### ISSUE TITLE
When sharing as a page and then hovering the mouse over the page link sharer throws error

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1688]
When sharing as a page and then hovering the mouse over the page link share throws error. For example if I have a page called, "Stimpy" I share as a page. Then I hover over the page as user "Stimpy."

![screenshot](https://cloud.githubusercontent.com/assets/19594886/19213088/23861172-8d30-11e6-87b0-28a9c014570d.png)

**Comment by Data66PF** [comment]
We already had this on our internal tracker and is fixed for 4.4.3 build 2 coming soon.
