### ISSUE TITLE
Setting "minimum length for Username" does not work.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1689]
Setting "minimum length for Username" does not work.

![minimum length for username](https://cloud.githubusercontent.com/assets/15389101/19244715/4b2d1a66-8f26-11e6-85d1-f16070ba2562.png)

![minimum length for username 2](https://cloud.githubusercontent.com/assets/15389101/19244723/528a44aa-8f26-11e6-9906-121b07a40aa2.png)

**Comment by Data66PF** [comment]
In the future, please take all screenshots in English so we can verify the settings.

**Comment by Criotin** [comment]
![minimum length for username 3](https://cloud.githubusercontent.com/assets/15389101/19253024/ee2e16dc-8f50-11e6-8be9-8e43f2f7de95.png)

**Comment by neil96** [comment]
The setting is "Minimum length of **Username**", but in your screenshot, it's **full name**.

**Comment by Criotin** [comment]
Where and how can I set the settings that the minimum length of the name would have 3 letters.
