### ISSUE TITLE
Menu item "LANDING PAGE" in modules "PAGES".

### ISSUE THREAD

**Issue by kaligula7** [moxi9/phpfox#1694]
I'm missing a menu item "LANDING PAGE" in modules "PAGES".
After upgrading from v3. 9 to 4.4.2 can the user the modified values no longer reset. For example if I set in v3 as landing page "photos", then (after update) v4 I have as a landing page "photos"! And no way to change that back.

**Comment by Data66PF** [comment]
Please send a ticket with the subject Github bug 1694 and in the ticket please include AdminCP log in for us.

**Comment by kaligula7** [comment]
Hi Donna!
Like you said, I get a ticket.
