### ISSUE TITLE
Photo Details - "Set as Page's Cover Photo" menu option is hard-coded

### ISSUE THREAD

**Issue by Phong-YouNet** [moxi9/phpfox#1698]
"Set as Page's Cover Photo" menu option is currently hard-coded. We tried to integrate Photo into our developing apps. When going to Details page of item photo, there is menu option "Set as Page's Cover Photo" and there are no ways to modify to appropriate text.

**Comment by IsabellaJolie** [comment]
Follow this guide to support set cover. 
- Implement getPhotoDetails, should return correct phrase return array('set_default_phrase' => _p('Set as Group\'s Cover Photo'), ....), see PHPfox_Groups for more information. 
- Implement plugin "photo.set_cover_photo_for_item.php" plugin to support set cover photo for correct item. See PHPfox_Groups for more information.
