### ISSUE TITLE
Video post is not unified

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1702]
after sharing a video, likes and comments in news feed (main page) doesn't show up below the video. only on news feed post. Basicly it has two places for comments and likes.

**Comment by Data66PF** [comment]
Please post a screenshot.

**Comment by djafrika** [comment]
![ss](https://cloud.githubusercontent.com/assets/22333440/19488953/71b0def4-9569-11e6-9eb8-87c15e16eab0.jpg)
![ss2](https://cloud.githubusercontent.com/assets/22333440/19488956/75b58aea-9569-11e6-958b-5f3d6d219e98.jpg)
