### ISSUE TITLE
Delete comment on main feed (video)

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1703]
deleting comment bellow video news feed post results deleting whole post, not only that comment. Also, the prompt is saying you are about to delete video. (video doesn't get deleted)

**Comment by neil96** [comment]
Please give us detail steps to reproduce this issue.

**Comment by djafrika** [comment]
1. go here https://v4.phpfox.com/
2. post video (preferably on group)
3. add a comment on main feed below that video (not on video itself)
4. delete that comment
5. there you go...

**Comment by Data66PF** [comment]
https://v4.phpfox.com/webmasterzone I added a comment to that video and deleted the comment in the group feed and also in the main feed to test both. The video remains in the group feed.

**Comment by djafrika** [comment]
Yes, but it doesn't work as it's supposed to work. 
on main feed (sitewide activity), if you press delete button next to comment, it says like you are about to delete the whole video, not only the comment! so it doesn't work! Also it deletes that whole post from main feed. post and comments! it doesn't mather that video is not deleted, it's not working right...

Try this;
1.add a comment below the video in main feed (where it says donna >Webmaster zone)
2. click on delete comment
3. read what it says
4. click yes
5. check back on main feed
not to mention that comment is not shown on video itself...
but, that bug is posted here https://github.com/moxi9/phpfox/issues/1702
probably this bug will go away after issue 1702 is fixed...

**Comment by Data66PF** [comment]
The first one I tested I did as above and it deleted fine. The second one I tested, after cache clear, showed the notice to delete the video. This needs checking.
