### ISSUE TITLE
Profile Photo (feed)

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1704]
after uploading a profile photo, post on feed opens in another tab and the link is to profile instead of profile photo.
Same goes when tagged

**Comment by neil96** [comment]
The post on feed doesn't open in another tab, please give us more give about this.
The post link to profile is working as designed.

**Comment by djafrika** [comment]
it does... when full ajax is of...

**Comment by Data66PF** [comment]
I believe this is working as designed with ajax off but will let Neil determine that.
