### ISSUE TITLE
Like on profile photo (feed)

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1705]
if you are the only person liking that feed, it says "You, like this" <- comma shouldn't be here
and if there are two persons liking than it says "YouPerson like this" <- no comma and no space
Same goes when tagged on photo

**Comment by neil96** [comment]
Did you change the default phrases?

**Comment by djafrika** [comment]
Nope... go to your demo site and see for yourself...
![ss](https://cloud.githubusercontent.com/assets/22333440/19513780/7128e5ca-95f1-11e6-8b00-d8959b5dbd55.jpg)

**Comment by Data66PF** [comment]
It only seems to show like that on the profile and not on the main feed. https://v4.phpfox.com/profile-898/ confirmed.

**Comment by djafrika** [comment]
Actually is shows like that on both main feed and profile feed. This screenshot is from main feed. Check the url on screenshot...

**Comment by Data66PF** [comment]
I can't reproduce it on the main feed. I already confirmed the bug though.

**Comment by Data66PF** [comment]
I can now see it on the main feed after cache cleared. So this is in both areas.
