### ISSUE TITLE
Main feed hovercard for groups

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1706]
in news feed, when hovering over group name, hovercard doesn't phrase group category ex:"groups.groups_category"

**Comment by Data66PF** [comment]
Can you reproduce that at our demo https://v4.phfox.com ?

**Comment by djafrika** [comment]
on demo site hovercard is not showing up for groups... on my site it does???
![ss2](https://cloud.githubusercontent.com/assets/22333440/19489216/a22c051c-956a-11e6-9a2e-554cfa7c6886.jpg)

**Comment by Data66PF** [comment]
Are you sure you are on v4.4.3 build 2 as we fixed some of those issues from build 1. Please be sure you are using most current version when submitting bug reports and that all of the new steps in the upgrade tutorial were followed. Thanks.

**Comment by neil96** [comment]
This issue is fixed on 4.5. For now, please clear cache after create new category.
