### ISSUE TITLE
Groups Forum

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1707]
when trying to stick group forum thread via "Thread Tools" menu, error shows "Unable to find the page you are looking for."

**Comment by Data66PF** [comment]
Can you reproduce this at our live demo?

**Comment by djafrika** [comment]
![ss](https://cloud.githubusercontent.com/assets/22333440/19488406/0583420a-9567-11e6-96ed-00bad9b6b78c.jpg)
