### ISSUE TITLE
add php code in html files...

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#171]
Hi,

I need to know if it is possible to add PHP code inside the html files that are in the folder "views".

In v3 we could add PHP code in HTML files by using the tags {php}{/php}

This tags don't work on v4, but are there new ones that can allow me to add php code inside the html file? 

I have try changing the name from file.html to file.html.php and then call them from start.php, but still don't work.

Thanks

**Comment by Data66PF** [comment]
Quoting from Ray as I asked him about this already for you.
"we can't add {php} tags in the HTML files.Twig does not allow it. He does not have to use those HTML files.He can actually do everything in PHP files."

Hope that helps.

**Comment by cespiritual** [comment]
Thanks Data,

This leads me to another question.

Can I output the php results, with echo, without using html files? Can I do everything inside the start.php.

If so, how do I "echo" something inside the start.php into a block position without calling an external html file. How do I do all inside start.php.

If I use this:
[code]$object->block('core.index-member', 1, $View->render('@test/show.html', [
			'users' => $users->get()
		][/code]

This will call the show.html and show the final result there.

But I want to echo the final result inside the start.php into that block position. How to?

I know that this is an odd question, but I need to undestand if that is possible and how to achieve that.

Thanks

**Comment by cespiritual** [comment]
To be more especific about my question I show this exemple of code inside start.php

new Core\Route('/hello-world', function() {
    echo "Hello World!";
});

This will echo the phrase inside the page "hello-world"

My questions is how do we do the same, but instead of echo it into a page it echos into a block position?

Thanks

**Comment by RaymondBenc** [comment]
Here is one example of creating a block...

**start.php**
```php
<?php

return function(Core\App\Object $App, Twig_Environment $View) {
	new Core\Event('lib_module_get_blocks', function(Phpfox_Module $object) use($View) {

		$html = 'Block content can go here...';

		$object->block('core.index-member', 1, $View->render('@PHPfox_Block_Sample/block.html', [
			'content' => $html
		]));
	});
};
```

**/views/block.html**
```html
<div class="block">
	<div class="title">
		Block Title
	</div>
	<div class="content">
		{{ content }}
	</div>
</div>
```

So basically, with the PHP render() function we use, the 2nd argument is what you can use to pass any variables to the HTML file in order for it to echo in that position.

Hope this helps!
