### ISSUE TITLE
States Don't Drop Down When User Selects United States During Registration

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1710]
Just attempted to sign up to my own site. When I selected my country, the drop down box for states did not appear.

States Don't Drop Down When User Selects United States During Registration

**Comment by neil96** [comment]
I can't reproduce. Please double check your 3rd-party apps and themes. Might be there is a js error with them.

**Comment by PhpFoxJohnJr** [comment]
I have some younet products and I can't remember where I was but this just happened to me a few days ago.  I think I was trying to register a fake user for testing and I think the captcha failed and I had to re-entered...this is where it didn't show up...maybe or maybe not.  I know it happened though during the registration though.  I do have city in the registration as well.  I just tried it and it works ok but it did have a glitch somewhere...good luck.

**Comment by neil96** [comment]
@PhpFoxJohnJr Thanks for sharing!

**Comment by PhpFoxJohnJr** [comment]
So I know you closed this and maybe it is just our sites or add-ons...don't know. But when I click to register it comes up something (this time I didn't fill out the rest) but now it gives you the dropdown box.
Also, off this...just wondering how to make the city required as I check off in the AdminCp to put city in registration but how can I require it like the location does.

![registration](https://cloud.githubusercontent.com/assets/14913734/20899554/8453eb62-baf0-11e6-9a24-6910175cd2dc.jpg)
