### ISSUE TITLE
Browse Album Photos

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1718]
When you click on photo album and want to browse one by one photo from that album, on the thumbnail bar there are only that many photos as previously loaded thumbnails.

**Comment by neil96** [comment]
The thumbnail bar load photos in previous section, not photos in the same album.
If you'd like this feature, please send us a [request](https://github.com/moxi9/phpfox-feature-requests).

**Comment by djafrika** [comment]
omg! let's say you have 50 photos somewhere. never mind where. and ajax loads only 10 thumbnails, when you click on one photo, thumbnail bar will load only those 10! If you want to browse rest of them, you have to go back, scroll down, keep scrolling until all 50 thumbnails has been loaded and only then you will have all 50 photos on thumbnail bar... but if it's working as designed then ok...
