### ISSUE TITLE
Ajax calls on Apps

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#172]
Hi,

How do we make ajax calls with apps? With modules I have the file ajax.class.php under "include/component/ajax" where I put all the functions and then just call them like this:
$(this).ajaxCall('contentsystem.populargroups');

How do we do this with apps?

Thanks

**Comment by RaymondBenc** [comment]
We've added some info today on how to work with AJAX, more info can be found [here](http://support.phpfox.com/apps/ajax/).
