### ISSUE TITLE
Mail Count

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1721]
Mail count is not counting inbox messages. There is always 0. Sent messages shows proper count.

btw, what is the purpose of inbox, sent and legacy inbox?
Inbox and sent messages shows both the same messages and legacy inbox is always empty...

**Comment by neil96** [comment]
By default, We don't counting index messages. If you'd like this feature, please request us [here](https://github.com/moxi9/phpfox-feature-requests).

About question, please ask on our [community](https://community.phpfox.com/forum/).
