### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1722]
Some notifications vanish after you click on it and some don't.

**Comment by neil96** [comment]
We hide notifications after user read. It has always been working like this. Please request us [here](https://github.com/moxi9/phpfox-feature-requests) if you'd like to change it.

**Comment by djafrika** [comment]
It cannot "work as designed" if its not working properly! some notifications are removed when you click on it and some stay there indefinitely..

**Comment by phpfoxaccount** [comment]
If it's a case, please follow our guideline at https://github.com/moxi9/phpfox and post a new issue.

**Comment by djafrika** [comment]
ignoring a problem doesn't solve it

**Comment by phpfoxaccount** [comment]
@djafrika we do have policy for public github, please check again.

**Comment by djafrika** [comment]
Nevermind... I wanted to help by pointing out bugs that I encounter. I won't be bothering you anymore...

**Comment by djafrika** [comment]
Are you gonna fix this or pretend that this is not a bug? 
If you have some notifications that hide automatically when you click on them and others don't, then it's clearly not "working as intended"!!

**Comment by neil96** [comment]
@djafrika We will improve it. It will be accepted if you post a request. I attached the request link above.

**Comment by djafrika** [comment]
This is **not** a feature request. It is **bug**. 
You said that you _hide notifications once user clicks_ on one. So if a notification **doesn't hide** it is **not working as designed**!
Pls **fix it** or **make better notification system**...

**Comment by neil96** [comment]
Each site has its own business. With you, it can be a bug, but with other peoples, it's a feature. The issue you report that has been working like this many years ago.
We had confirmed it was enhancement, so please request us [here](https://github.com/moxi9/phpfox-feature-requests).
