### ISSUE TITLE
Gift Permalink

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1723]
When you send a gift to someone the permalink to it is set depending on where you are. 
If you are on the main feed, permalink points to that page, if on profile page, then it points to that profile.

**Comment by neil96** [comment]
I can't reproduce, could you give us detail steps.

**Comment by djafrika** [comment]
send someone a gift, then go on his profile page, click on date of that activity.
now, go to main news feed, do the same.
two different links for the same activity!

**Comment by phpfoxaccount** [comment]
If it's a case, please follow our guideline at https://github.com/moxi9/phpfox screenshot or detail steps would be appreciated

**Comment by djafrika** [comment]
go here https://v4.phpfox.com/
then here https://v4.phpfox.com/profile-3/
click on date/time below **AFRIKA > Donna(Data66)**
