### ISSUE TITLE
event category shows incorrect when display an event.

### ISSUE THREAD

**Issue by clarkyu** [moxi9/phpfox#1724]
![qq20161031-1](https://cloud.githubusercontent.com/assets/3412340/19838094/a6a27242-9f02-11e6-9fda-d7fd38d9a0ad.png)

**Comment by neil96** [comment]
This is a cache issue. It's fixed on 4.5. For now, please clear cache and it will work.

**Comment by neil96** [comment]
#1628

**Comment by clarkyu** [comment]
Actually, it doesn't work whatever you clear cache or not.

**Comment by neil96** [comment]
Are you using redis?

**Comment by clarkyu** [comment]
yes.

**Comment by neil96** [comment]
#1726

**Comment by clarkyu** [comment]
I founded that they are linked to Phrase Variable Name, rather than Phrase Text.
