### ISSUE TITLE
New profile picture

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1728]
When you add a profile picture, the gallery does not open. 
When you click on the picture goes to the profile page.

![screenshot](https://cloud.githubusercontent.com/assets/8930862/19847486/eb689d3c-9f4f-11e6-9fc4-1bf42258921f.png)

**Comment by neil96** [comment]
It has always working like this. Please [request](https://github.com/moxi9/phpfox-feature-requests) us a request if you'd like to change.
