### ISSUE TITLE
Video comment permission?

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1731]
when commenting on a video, I get this notice;
"_Your comment was successfully added, however this item requires that all comments be moderated by the owner before they are publicly displayed._"
User group has all permissions and the weird thing is that it only happens on some videos.

**Comment by neil96** [comment]
How do you reproduce it?

**Comment by Scheinwelt-Media** [comment]
can reproduce that issue on my site (4.4.3) when a video is posted in a closed group

**Comment by neil96** [comment]
Please test on 4.5.0b3 and tell us how to reproduce it.

**Comment by Scheinwelt-Media** [comment]
i can not reproduce it on the demo
