### ISSUE TITLE
Share Video tab on profile page missing

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1732]
On homepage, pages and groups there is **Status|Photo|Video** tab but on profile page there is only **Status|Photo**

**Comment by phpfoxaccount** [comment]
@djafrika please check before post as guideline, we already have the post for this.

**Comment by djafrika** [comment]
I don't understand why is this issue closed when it is not fixed??!!

**Comment by neil96** [comment]
It's duplicate with #1574

**Comment by djafrika** [comment]
There are 3 requests for fixing this issue and you have no plans fixing this... That's nice... 
And you are wondering why everyone is leaving...
