### ISSUE TITLE
Unable to delete pages status post immediately after entry

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1733]
Unable to delete pages status post immediately after entry unless the page is refreshed.

**Comment by neil96** [comment]
I can't reproduce. Please give us detail steps.

**Comment by prepperz** [comment]
use chrome

1. Goto a page you admin. 
2. post a status.
3. Delete the status

It will say unable to delete entry.

**Comment by neil96** [comment]
I did the same, it worked.
