### ISSUE TITLE
Addition to message in the marketplace.

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1736]
The seller may have a lot of ads.
It is necessary to make so that the mark would come to the seller with a message about what kind of ad is spoken about.
For example:
The user is interested in your ad:
"Clickable link-name"
Then the message is going.

![marketplace message](https://cloud.githubusercontent.com/assets/15389101/20114171/4f345bac-a604-11e6-8ee0-39966c452fac.png)

![marketplace message 2](https://cloud.githubusercontent.com/assets/15389101/20114183/558c38da-a604-11e6-9db1-ec1752d1646e.png)

**Comment by neil96** [comment]
Please request us this feature [here](https://github.com/moxi9/phpfox-feature-requests).

**Comment by Criotin** [comment]
Ок.
