### ISSUE TITLE
when upgrading from 4.4.3b2 to 4.5.0 beta1, it shows "We have found that the following table(s) already exist:"

### ISSUE THREAD

**Issue by clarkyu** [moxi9/phpfox#1737]
when upgrading from 4.4.3b2 to 4.5.0 beta1, it shows "We have found that the following table(s) already exist:" and can't go any further.

**Comment by phpfoxaccount** [comment]
Kindly be noticed: this issue tracker is to track the issues of the latest version. More information about Beta, RC can find at https://community.phpfox.com/forum/thread/43144/beta-and-rc-versions-of-phpfox/
