### ISSUE TITLE
Activities-points center uses the same phrase as Events Header.

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1738]
![activity](https://cloud.githubusercontent.com/assets/19594886/20252038/9b1d98da-a9ec-11e6-912e-87f27e3d10cb.png)

![events](https://cloud.githubusercontent.com/assets/19594886/20252042/a0e02b5c-a9ec-11e6-8ee7-278a69b79f7d.png)

**Comment by neil96** [comment]
This issue occurs because you had changed the phrase in AdminCP.

**Comment by prepperz** [comment]
You're missing the point of what the title says.
