### ISSUE TITLE
Mouse over "friends online" only shows the full name with avatar image

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1739]
Mouse over the friends online only shows the username with avatar image. If a user has not uploaded an image, it doesn't display the username.

**Comment by neil96** [comment]
Could you give us some screenshots?

**Comment by prepperz** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/19594886/20265529/8abd89ac-aa3f-11e6-9d41-9c72c47f6a46.png)

**Comment by aakash83** [comment]
I can reproduce this  on my community.

**Comment by neil96** [comment]
Confirmed, but it's full name.
