### ISSUE TITLE
Special Characters in User name converted to ASCII on Hover

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1740]
PF 4.4.3
While moving cursor over profile pictures for those using a special character in their user names .That character is converted to ASCII. as shown below.
![image](https://cloud.githubusercontent.com/assets/406030/20317399/25459a92-ab66-11e6-944a-91f365098f0e.png)

**Comment by neil96** [comment]
How do you get this block?

**Comment by aakash83** [comment]
It is an app by data66. But the issue is not limited to this block only. It shows the same while hovering a user photo in feed.

**Comment by neil96** [comment]
This repo for phpFox core issue only.
