### ISSUE TITLE
Incorrect Message Shown on Pending Invites and Pendinng Friends Request Page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1741]
PF 4.4.3 ,
Incorrect Message Show on Pending Invites and Pending Friends Request Page. If we have pending invites (which we sent) and pending friend requests Phpfox still display a message "There are no pending friends requests" .Also same for invites .
![image](https://cloud.githubusercontent.com/assets/406030/20308047/8e39ef68-ab42-11e6-874c-01c44ad0dc70.png)

**Comment by neil96** [comment]
It has been fixed on 4.5.0.
