### ISSUE TITLE
Alizarin theme JavaScript error

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#175]
If i click JavaScript in theme edit page im getting following error:

 file_get_contents(/home/xxxxxx/public_html/PF.Base/../PF.Site/themes/23/assets/autoload.js): failed to open stream: No such file or directory

**Comment by Jinkers** [comment]
Have you checked if the file itself exists? Perhaps it didn't download correctly/at all.

**Comment by Ylmzef** [comment]
Its installed with admincp, by reason of its a bug?

**Comment by Data66PF** [comment]
Check folder permissions. Failed to open stream is, most times, a permission issue with folder permissions on the server.

**Comment by Data66PF** [comment]
Oh I see it did not import those files. Confirmed. V4.0.3
