### ISSUE TITLE
Google ads breaks css

### ISSUE THREAD

**Issue by djafrika** [moxi9/phpfox#1757]
Ajax on.
If you have block with google ad on either block placement 1,9,3,10, then some pages won't load left and right columns. This happens every time you visit page that has left or right columns hidden and after that you visit a page that has left and right column shown. 
ex. if you go to page discussion (that has both columns hidden), and after that go on home page, you cannot see left and right blocks.
If you have site wide block with google ads on block placement 1,9,3,10, than pages that have left and right columns hidden won't load at all...
If you disable ajax, then it works fine.

**Comment by neil96** [comment]
Google ads do not compatible with ajax mode, please check [here](https://developers.google.com/adsense-for-ajax/). If you'd like using google, please turn off ajax mode.
