### ISSUE TITLE
[Images] Deleted Image Still Showing In Image Pages In 4.0.3

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#176]
I've updated to 4.0.3 and it doesn't look like the fix (https://github.com/moxi9/phpfox/issues/129) took part. Still showing blank spots where a deleted image is as shown here:

![image](https://cloud.githubusercontent.com/assets/6254165/8814509/4fa1ef00-2fdb-11e5-8150-ebf3825a766a.png)

**Comment by Data66PF** [comment]
Did you run the Counters?

There are a few steps when upgrading that are not mentioned in the upgrade steps. http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view it. I guess I should add the counters thing but it isn't always necessary. Try first to do these mentioned steps and then if that doesn't work, try running the update counters in maintenance.

**Comment by GloriousKoch** [comment]
Just ran the counters. Didn't realize that was a thing, haha. Seems to have fixed it.

**Comment by Data66PF** [comment]
I'll add that step to my tutorial. Thank you!
