### ISSUE TITLE
Birthdays display too many days ahead

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1760]
![screenshot](https://cloud.githubusercontent.com/assets/19594886/20791688/387ae36a-b78c-11e6-9bb3-9aeaec9bf990.png)

**Comment by Vivian-phpFox** [comment]
How many days in advance to check for birthdays?

**Comment by prepperz** [comment]
Are you asking how many days when the birthday should be displayed? If so it can be 2-7 days.

**Comment by neil96** [comment]
We asked you this setting: "How many days in advance to check for birthdays" (This setting tells how many days in advance should the script check for. 

Setting it to a number too high may beat the purpose of the feature. 

The results from this feature cannot be cached, so it is prone to becoming a slow down for your site. 

Keep in mind that you can disable this feature altogether in the setting friend.enable_birthday_notices)

By default, it's 7.

**Comment by prepperz** [comment]
I'ts always been left as default. Never touched the settings for this section.

**Comment by prepperz** [comment]
Strange. . Didn't have any issues with this til today. I cleared the cache and it the problem went away. Not sure sure what caused the glitch.
