### ISSUE TITLE
Privacy mode does not work

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#1761]
Hello.
Privacy mode does not work for links at pages (groups). Any user can add links at pages.
Please fix it.

**Comment by Criotin** [comment]
Video:
https://v4.phpfox.com/v/play/1605/

**Comment by neil96** [comment]
From 4.5, if a user does not have permission to share comment, the block _share_ will be hidden.
Please test again on 4.5. Thanks!

**Comment by Criotin** [comment]
Ok. Thanks!

**Comment by Criotin** [comment]
When the stable version 4.5.0 released?
