### ISSUE TITLE
Facebook Login button Visible even the Facebook Module is Disabled

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1768]
PF  4.5 Stable, Chrome , Firefox 
If we  disable  the Facebook  Apps in Admincp  the  Fb Login Button is still visible on  Index page (NonLogged in) .  on click  it redirects to a Page Not Found Error.
![image](https://cloud.githubusercontent.com/assets/406030/21011039/9c509d1c-bd4f-11e6-9df2-7dd1a287b7d2.png)

**Comment by neil96** [comment]
This is a cache issue, please clear cache after disable an app.

**Comment by aakash83** [comment]
Yes , After clearing cache it disappeared ,Thanks
