### ISSUE TITLE
Problem with preview panel

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#177]
whenever we click on messages or notifications etc we get a preview panel containing info related to clicked item  but this panel is not automatically disappearing when we click on any blank area anywhere on the page. So we again need to click on that item to close this preview panel.

i am using version 4.0.3 ( problem exists on your demo community also).

**Comment by Data66PF** [comment]
I can see this happens but it is not causing any issue for me. If I navigate to another area, for example, it closes. Is this causing some issue other than it doesn't close on clicking in a blank area?

**Comment by aakash83** [comment]
it don't disappears always when you navigate to another area. for example consider the scenario when you are viewing a photo . below you can see what type of problems we face while preview panel is there. if you click in comment box , preview panel will not disappear and you have somehow close it in order to comment.
![image](https://cloud.githubusercontent.com/assets/406030/8854678/6f8e2266-3161-11e5-9f2f-fda0726710f8.png)

**Comment by Data66PF** [comment]
Everything in the site is designed to be clicked to exit. I'll post this as an enhancement though to see if he'll change it.

**Comment by RaymondBenc** [comment]
Steps to reproduce? My panel actually closes for me, however it does not de-highlight the link.

**Comment by Data66PF** [comment]
1. Click the left Notifications or Messages link and the panel opens. 
2. Click in a blank area to the right of the screen, expecting to close it like the popup videos close if you click in a blank area. 

The box does not close. Have a small screen to see the issue in the image the user above posted. Be looking at a photo to see the issue best.

**Comment by aakash83** [comment]
Here is another similar example. 
When we send a friend request to another member. a popup opens containing a message as shown below.
![image](https://cloud.githubusercontent.com/assets/406030/8861966/af2bf502-318d-11e5-97ea-66579028b682.png)
 Now if we don't click "send friend request" and navigate away from this page this popup will stay there until we manually close it.

**Comment by RaymondBenc** [comment]
The side panel is designed to stay open, mainly to allow apps to engage a user while they browse the site (eg. IM or chat). This is theme related if a theme wants to close this panel on an **onclick** event anywhere on the site.

The issue with popups are the same, however I do understand the **Add to Friends** issue, I will change how we notify the user a request was sent to make sure it is removed afterwards.

**Comment by RaymondBenc** [comment]
Actually looking over the last issue with the **Add to Friends** this is how it is designed.

**Comment by aakash83** [comment]
so can you please guide me how to use that onclick event . i really want to change this.
