### ISSUE TITLE
AdminCP Not Showing Loading/Processing Icons

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#178]
When you change any of the settings, including making a new flavour, there is no loading/processing icons coming up. Most noticeable is when you click the submit button for a new flavour, the button extends to the left but nothing displays in the new area.

**Comment by Data66PF** [comment]
Confirmed. Without any progress meter or success notification, it looks like nothing happened.

**Comment by RaymondBenc** [comment]
Is this mainly related to anything in the Theme Manager?

**Comment by Data66PF** [comment]
For my tests it is as the whirligig icon spins for settings but there isn't one for theme stuff.
