### ISSUE TITLE
Does not properly parse internal links.

### ISSUE THREAD

**Issue by prepperz** [moxi9/phpfox#1781]
When internals links are pasted in the status or comments, it does not properly parse it. For example: https://v4.phpfox.com/pages/category/1/entertainment/

it will only show it as phpfox.com

**Comment by neil96** [comment]
It's working.
<img width="581" alt="screen shot 2016-12-13 at 09 10 27" src="https://cloud.githubusercontent.com/assets/15936115/21124869/0be768d2-c114-11e6-8d18-d26b32eb3241.png">

**Comment by prepperz** [comment]
No it does not. Click share and then look and the result.

**Comment by neil96** [comment]
It's how it look like: https://v4.phpfox.com/profile-1312/?link-id=138
What's wrong here?

**Comment by prepperz** [comment]
See the here can you tell the difference? Also it show's two urls. https://v4.phpfox.com/profile-1312/

**Comment by neil96** [comment]
Because you shared it two times (18 and 21 minutes ago)
<img width="580" alt="screen shot 2016-12-13 at 10 45 34" src="https://cloud.githubusercontent.com/assets/15936115/21126835/53e82966-c121-11e6-8dd4-e72a2fb19b0c.png">

**Comment by prepperz** [comment]
They are 2 different links
