### ISSUE TITLE
comments textarea

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1782]
when writing comments the textarea resizes but goes under the next feed entry. I need a fast fix for that because this kills my site. you can also see the issue on the phpfox demo. just put in 3 or more lines of comment.

**Comment by neil96** [comment]
For feature request, you can request [here](https://github.com/moxi9/phpfox-feature-requests).

**Comment by lordofnos** [comment]
this is not a feature request. it is a bug. check on your demo. you can n ot write more then 3 line and you can not see what you are writing. huge bug i would say.

**Comment by robert9592** [comment]
Hi lordofnos,

phpFox v4.5.0 build 2 that included the fix for this issue will be released soon in this week. Thanks for your report.
