### ISSUE TITLE
[Wisteria Theme] Sharing styling Issue

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#179]
When you share anything on the Wisteria Theme, the box shows up all white:
![image](https://cloud.githubusercontent.com/assets/7270030/8815850/603f3656-3062-11e5-9325-51a9d6024d04.png)
As you can see, the text is unreadable. Unless you highlight the page:
![image](https://cloud.githubusercontent.com/assets/7270030/8815855/6f124f4c-3062-11e5-91e2-045970c92f30.png)
I've made a simple change to my end, however it should be updated for the others as well. I simply changed .feed_share_holder background and border to { background: #262626; border: 1px #262626 solid; }.

That change yields the following:
![image](https://cloud.githubusercontent.com/assets/7270030/8816132/0c08005a-3066-11e5-83a2-6f226c7f1e71.png)

**Comment by Data66PF** [comment]
Confirmed

**Comment by Jinkers** [comment]
Just wondering if we could get an update on this?

**Comment by Data66PF** [comment]
This is a free theme and not really part of this bug area but I marked it a bug just in case he would address it here.

**Comment by Jinkers** [comment]
Ok. Thanks

**Comment by GloriousKoch** [comment]
Just for future reference, where would be the best place to post bugs about the PHPfox provided themes?

**Comment by Data66PF** [comment]
There will be a place in the community made for this as these are not here in the Github as separate apps/themes. The other free apps released by PHPfox are here in Github so for those, please put issues with them in their respective bug issue trackers. Thanks!

**Comment by neil96** [comment]
Fixed on 4.2.0
