### ISSUE TITLE
Multi step registration missing

### ISSUE THREAD

**Issue by one44123** [moxi9/phpfox#1791]
Cannot add additional registration steps so apps do not work.

![2016-12-14 05_36_02-admin cp _ manage settings _ bdsm dating social bdsm fetish dating bdsm dating s](https://cloud.githubusercontent.com/assets/22991731/21168838/db80dcb2-c1bf-11e6-8631-5788a271809d.png)

**Comment by neil96** [comment]
phpfox-feature-requests/#296

**Comment by neil96** [comment]
moxi9/phpfox-feature-requests#296
