### ISSUE TITLE
forum (search) Styling issue  on mobile ( forum search)

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1795]
Latest Phpfox , iPhone 6 , Chrome
![image](https://cloud.githubusercontent.com/assets/406030/21259198/aea132b0-c380-11e6-974b-359e8e1b0a34.png)

A Suggestion: It would be better if the search form is hidden behind a button OR put it inside a menu (Quick Links). It is taking a lot of space. Thanks

**Comment by neil96** [comment]
Moved to moxi9/phpfox-feature-requests#299
