### ISSUE TITLE
Video Posting Issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1796]
Latest Phpfox with Chrome.
I am not sure it is a bug or We consider it as a feature request.

Whenever We post a video (timeline or inside any module (Pages, Groups)) after posting Phpfox redirects us to the newly posted video.  Now If a user is posting a video which he/She consider as interesting  it means he/she already has viewed it , So   we don't need to  view it again.   Also,   This redirect take the current user away from the current page which is a bit annoying.  So  I request you to please think about this.
Thanks

**Comment by neil96** [comment]
Moved to moxi9/phpfox-feature-requests#298
