### ISSUE TITLE
migrate old module 

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#1798]
1) admincp/module/add shows pages not found 

but also shows a button New Module 

click on this button ends in endless wait 

This is certainly bug ( may be you do not want module/add --- but then it shall not end up in loading endlessly and there shall not be button New Module
![mnot](https://cloud.githubusercontent.com/assets/13350517/21283585/d63c64b4-c3d2-11e6-8bdb-3b29da855956.JPG)

Windows / wamp / firefox /phpfox/540b2
2) admincp/product/add does allow you to add a product on a form however - 
it does not effectively creates any product folder 
am not sure if this is how you intend to create product / module in this version 
 I end up with making no progress migrating old module or create new

**Comment by neil96** [comment]
We removed them (both menu and code)

**Comment by signupsi** [comment]
then how do u add module ? 
once u removed them ?
will u use product/add 
that does not create module

**Comment by neil96** [comment]
On V4, We only allow migrate module from V3. To create new plugin on V4, please [use app](https://docs.phpfox.com/display/FOX4DEVDOC/App+Development+Guide).
