### ISSUE TITLE
[Wisteria Theme] New Flavours Settings Not Copying

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#180]
When creating a new flavour with the Wisteria Theme, nothing gets cloned from the default flavour.
![image](https://cloud.githubusercontent.com/assets/7270030/8816161/651aa558-3066-11e5-9460-769dd55e8055.png)
Default theme works fine with new flavours. I've tried multiple installs of the theme however still same error appears. The lack of settings completely breaks the sites display.

**Comment by Data66PF** [comment]
This might be related to #175 as these new themes are missing files.

**Comment by Data66PF** [comment]
I'll confirm this but the error that I see is the same as for the other bug. I believe that once that issue is fixed, this issue will also be resolved.
