### ISSUE TITLE
 Video Settings not working  in AdminCP

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1803]
Latest Phpfox  with Chrome 
Already did  Mantinanace >> Find Missing Settings  and   Cleared Cache .

Video Settings are not working   if we Access   from  Admin CP >> Settings >> Search and then type "Video" .
![image](https://cloud.githubusercontent.com/assets/406030/21294212/103a9df0-c538-11e6-9ed6-57fc03f6bba0.png)

If we access video module  through Apps>> Video  we   cannot edit  Video Category Name .(I have only one category).

**Comment by neil96** [comment]
Video is an app, you can't search its settings. To view its settings, please go to manage apps -> select app video -> select menu settings.

**Comment by aakash83** [comment]
If we go to app >> Video > settings  we  cannot see  the following settings .

- Video Time stamp  , Video Meta Description , Autoplay , enable uploading vodeos , disable youtube related videos.

Can you please guide me how to access these settings??
