### ISSUE TITLE
[Offical PHPFox Site] Display Issues - Mobile

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#183]
As requested by Data66, the official information/knowledge base styling doesn't allow for a readable experience.
![image](https://cloud.githubusercontent.com/assets/7270030/8823098/a06c2a68-30ad-11e5-9ad1-d860444106a0.png)
The sidebar pushes the text on the right and into a tiny box. Applies to both the v3 and v4 pages.

**Comment by Data66PF** [comment]
Confirmed on iPhone 5c.

**Comment by RaymondBenc** [comment]
Update in regards to this issue, we are working on an App for PF that will be used as our default KB and the current KB will be closed thereafter, thus fixing the issue at hand as well.
