### ISSUE TITLE
Cancel Account gives "invalid password"

### ISSUE THREAD

**Issue by ojaiweber** [moxi9/phpfox#184]
I created a test  user and subscribed via paypal. (note: sandbox wouldn't work so I just did $1). It's a reoccurring plan.

When I click "cancel account" it gives me an error saying invalid password.  But it is correct.  Any help?

<img width="493" alt="cancel account error" src="https://cloud.githubusercontent.com/assets/13368303/8827045/e0905c44-304f-11e5-95c5-156bad213885.PNG">

**Comment by Data66PF** [comment]
Confirmed. V4.0.3.
