### ISSUE TITLE
Pages and Groups Manage Button is in Center of Avatar

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#185]
The button to manage the page is in the center of the avatar as reported at the PHPfox forum. This makes it too hard to see.

![manage page](https://cloud.githubusercontent.com/assets/6908282/8829579/618c00ae-3065-11e5-9a5d-d87b23981c66.jpg)

**Comment by Data66PF** [comment]
Confirmed

**Comment by RaymondBenc** [comment]
haha, true. I guess I wasn't to creative that day :smile:
