### ISSUE TITLE
upgrade to version v3.8.0-Ultimate Install phpFox currently I have version 3.7.0

### ISSUE THREAD

**Issue by zurdokm** [moxi9/phpfox#186]
I want to upgrade to version v3.8.0-Ultimate Install phpFox, but can not find the tutorial to do it, I could send the instructions to make the upgrade, thanks

**Comment by Data66PF** [comment]
Hello, the bug tracker is only for bugs, please ask questions like this in the forum for that. http://community.phpfox.com/forum/

Knowledgebasse with tutorials is found here, http://support.phpfox.com/
