### ISSUE TITLE
Account Settings page showing Undefined index: custom

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#187]
When i click on Account Settings link in left menu under profile picture, im getting "Undefined index: custom" error.

**Comment by aakash83** [comment]
for me it is working .

**Comment by Ylmzef** [comment]
I upgraded from v3, you too?

**Comment by aakash83** [comment]
no i have a fresh install on my localhost. still not upgraded my live community.

**Comment by Data66PF** [comment]
Mine works for my upgraded development site running on win 8.1 pro. I also don't see an issue on the PF community for this and I believe that was upgraded from v2. My local was upgraded from v3. Perhaps the upgrade didn't work right for you.

**Comment by Ylmzef** [comment]
Thus its bug of your upgrade script.
What is solutions?

**Comment by Data66PF** [comment]
As I said I cannot reproduce the issue. It works fine for me.

**Comment by RaymondBenc** [comment]
Try to enable debug mode so we can see the files/lines the error is originating from.

To enable debug mode, create a PHP file called **PF.Base/include/setting/dev.sett.php**

Then add..
```php
<?php
define('PHPFOX_DEBUG', true);
```
