### ISSUE TITLE
Images Don't Show Up In Blog View

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#188]
Images don't show up in blog view, but show up in the news feed.

![blogimagenotshowingup](https://cloud.githubusercontent.com/assets/13330878/8840667/8b8dadf6-30b2-11e5-9346-595ba35ff170.jpg)

**Comment by Data66PF** [comment]
confirmed that if we go to main feed, it shows as an image for images we put in a blog post but if we go to the main blog section, it shows as code. V4.0.3 tested.
