### ISSUE TITLE
The "Whats Up" Feature Doesn't Show Up on iPad Mini

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#189]
The "Whats Up" Feature Doesn't Show Up on iPad Mini
http://mobiletest.me/ipad_mini_emulator/?u=http://orgazilla.com

![orgazillaipadmini](https://cloud.githubusercontent.com/assets/13330878/8841646/a4f2a33a-30be-11e5-8cf2-d844c48e500e.jpg)

**Comment by SalmanKhan86** [comment]
can you able to find logout and account setting in iPad Mini phpfox V4

**Comment by orgazilla** [comment]
Nope! The option isn't on the iPad Mini version of PHPfox.

**Comment by Data66PF** [comment]
Confirmed on my iPad mini using Safari browser, iOS 8.4

**Comment by RaymondBenc** [comment]
Fixed in #195
