### ISSUE TITLE
Wall Comment Loading Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#191]
when we click on post comments which was higher than 10(default limit) is not loading ex: View All 15 Comments when its open in another browser tab
![comment loading problem](https://cloud.githubusercontent.com/assets/13433124/8842536/19f9738e-3119-11e5-8efe-a7704432f964.png)

**Comment by Data66PF** [comment]
This is how it has always worked for more comments or do you mean it does not open at all?

**Comment by SalmanKhan86** [comment]
Its open in another tab same as before without loading Previous comments.I
tested in windows 7 Mozila and chrome

**Comment by Data66PF** [comment]
Confirmed. Win 8.1 pro. Firefox latest. I don't see errors in dev browser console. http://community.phpfox.com/EmilySmith/?comment-id=168comment/ checking that comment. The view more is not opening up for me.

**Comment by SalmanKhan86** [comment]
Then what is solution for this.

Send from my Sony Xperia.

**Comment by pankajinsan** [comment]
Ok Thanks its labeled as bug

**Comment by Data66PF** [comment]
@SalmanKhan86 Note that I only test and label issues. I don't provide fixes. Please wait for him to get to this issue as there are several in front of it.
