### ISSUE TITLE
You Tube Video link is not working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#192]
Video link is not working here when we click on it its show page not found Error
![view video problem](https://cloud.githubusercontent.com/assets/13433124/8842611/00a0fdca-311a-11e5-8959-cfe5775df6b4.png)

**Comment by Data66PF** [comment]
Have you tried this today? It works for me. Win 8.1 pro with firefox.

**Comment by SalmanKhan86** [comment]
Not worked for me on window 7 both Mozila and Chrome

**Comment by Data66PF** [comment]
Ok another win7 one. Win7 seems to be an issue for things.

**Comment by aakash83** [comment]
this is not working in win 10 also. don't think these kind of errors depends on OS.

**Comment by RaymondBenc** [comment]
When clicking on the videos here: http://community.phpfox.com/videos/

Do you get the error on every video?

**Comment by SalmanKhan86** [comment]
Now its working fine for me.Still one problem is there.no option to close video window.we have to click on another side to close window but music still plays

**Comment by aakash83** [comment]
Still not working. playing videos at http://community.phpfox.com/videos/  was always working. the only problem with this section is that we don't have any option to close video.
The issue is the embedded video links in feeds are not working.  when we click on it it shows a "page not found" error.

**Comment by Data66PF** [comment]
That bug is in the video app. This section is only for bugs with the core product. https://github.com/moxi9/phpfox-videofeed/issues/1 for the video stays open.  Please don't put two issues in one report. This report is only for the links in the feed. The OP says that it works fine for him now to click a video in the feed and play it. If it is not working for you when you paste a link in the status share box and then click to play the video, please let us know as that is what this bug was opened as. What OS and browser are you using at our community to test this?

**Comment by SalmanKhan86** [comment]
as i mentioned earlier its not working properly.no option to close its window.even we close it using mouse click music still play.

**Comment by SalmanKhan86** [comment]
no option to close it.window 7 OS tested with chrome and Mozilla 
![video window](https://cloud.githubusercontent.com/assets/13433124/9329383/ba58f2c2-45ce-11e5-8017-8a009ec41c48.png)

**Comment by Data66PF** [comment]
As I mentioned, youtube app bugs go in the youtube app issue tracker I linked for you but the bug is already posted there.

**Comment by Ylmzef** [comment]
I have still this issue too on v4.0.8
But i don't get not found message when i click youtube link on feed i see currently page in iframe on the popupbox.
Chrome 45
Windows 10

**Comment by Data66PF** [comment]
Post youtube bugs in the youtbue app. This is not for youtube app issues

**Comment by Ylmzef** [comment]
I can't see any youtube app?
