### ISSUE TITLE
"Search" not working in v4.0.3

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#193]
In version 4.0.3 and on your demo community "search" is not working. it don't allow to input more than one character and just show "No results found" .  tested in chrome and firefox.

**Comment by SalmanKhan86** [comment]
i am also facing same problem.

**Comment by Data66PF** [comment]
What OS?

**Comment by Jinkers** [comment]
Same problem here on my 3 sites (2 tests, 1 live) and the PF site. I'm using windows 10. Same issue on my windows 7 and 8.1 machines too.

**Comment by SalmanKhan86** [comment]
i tested it on window 7 chrome as well as on Mozilla

**Comment by Data66PF** [comment]
Ok win 10 is still in beta as far as I know so I can't test that. I don't have win 7 but I'll go try a test again with 8.1 pro on latest firefox.

**Comment by Data66PF** [comment]
I am able to put several letters on the main user search with no issue. That would be the search at the top of the list on the left, above Requests. It pulls up a list of friends as it is designed to do. If I put a word such as install, and then hit enter, it goes to any "install" posts. I cannot see an issue. Please disable any browser add ons and test. This test was for win 8.1 pro.

**Comment by aakash83** [comment]
i am using windows 7

**Comment by Data66PF** [comment]
When you put a few letters in, does a friend's name come  up? that search is for friends. If you want to search for site content, you can put a few letters in and hit enter or you can hit the advanced search thing.

**Comment by aakash83** [comment]
it don't allow me to put more than one letter. after first letter it just shows "No results found" (in firefox and chrome). however in IE it behaves differently. in IE when i type first letter it shows the same message (No results found) but i can still type my query ( as you can see in the screenshot below I am still typing.) and i am able to get results also. 
![image](https://cloud.githubusercontent.com/assets/406030/8853767/9e8c9d4a-315c-11e5-9f0a-faf2b88da5e1.png)

**Comment by Data66PF** [comment]
Do you have friends on the site?

**Comment by aakash83** [comment]
no i  have only one user (admin).

**Comment by Data66PF** [comment]
Well that's a user search to search for friends though. Add some friends.

**Comment by aakash83** [comment]
then why it is working in IE though in IE the nature of error is bit different,

**Comment by aakash83** [comment]
BTW this search is not only for friends . it returns pages, members , threads etc
![image](https://cloud.githubusercontent.com/assets/406030/8854939/cb020972-3162-11e5-9b47-187efb516a6b.png)

**Comment by Data66PF** [comment]
It only does that for me after hitting enter as I had said before though

**Comment by aakash83** [comment]
what else i can say. tried my best to explain..........

**Comment by Data66PF** [comment]
I'm waiting for him to come check this one as I don't think it's a bug but maybe he can make an update to how it works. Please hold until he gets to this issue. thanks

**Comment by SalmanKhan86** [comment]
Now its works for me on Window 7 OS both Mozilla and chrome.But one problem is still there after type one character it show search result.don't wait for user type one or more character.

**Comment by SalmanKhan86** [comment]
show more result link is not not working.when we click on show more results it does't do any thing.windows 7 OS.tested on chrome and Mozilla
![search more result](https://cloud.githubusercontent.com/assets/13433124/9248872/589af2aa-41dd-11e5-94b7-3faf094f5e60.png)

**Comment by Data66PF** [comment]
Please post a new bug for that. Thanks!
