### ISSUE TITLE
 #tag Module Auto suggestion is not Working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#194]
in #tag Auto complete suggestion not working like other social sites.

**Comment by Data66PF** [comment]
When posting bugs would you please put the browser and OS as I can't reproduce this one either. PF community Win 8.1 pro and even on my iPad mini it shows the image with username.

**Comment by SalmanKhan86** [comment]
i am tested it on windows 7 OS both Mozilla and chrome.In #tag its not showing Auto suggestion for Already trending topics user have to type whole words for it.

![tag support](https://cloud.githubusercontent.com/assets/13433124/8867102/cee5c512-31e2-11e5-88a4-d3b69ededa31.png)

**Comment by SalmanKhan86** [comment]
is this added or still pending?

**Comment by Data66PF** [comment]
Enhancements will have a spot at the community for people wanting to submit ideas.

**Comment by SalmanKhan86** [comment]
it is not implemented yet.while this is logged an year ago.
