### ISSUE TITLE
Account Setting,logout option is not Available on iPad Mini

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#195]
i can't able to find Account Setting,logout option in this type of screen.its difficult to logout and perform other action without it.
![small screen problem](https://cloud.githubusercontent.com/assets/13433124/8842807/a2bb7a8e-311c-11e5-98f8-70f51f843e4b.png)

**Comment by Jinkers** [comment]
Agreed. Perhaps a toggle button that slides out the menu would be a better option?

**Comment by SalmanKhan86** [comment]
yes Agree with you

**Comment by Data66PF** [comment]
Confirmed on my iPad mini using Safari browser, iOS 8.4

**Comment by orgazilla** [comment]
The recent fix #195 didn't fix the problem.

**Comment by Data66PF** [comment]
V4.0.4 hasn't been released yet.
