### ISSUE TITLE
user group

### ISSUE THREAD

**Issue by ajay55555** [moxi9/phpfox#197]
How can I ADD any user as staff in admincp

**Comment by Jinkers** [comment]
For future reference, please post bugs here only and ask questions over at http://community.phpfox.com/.

To make a user staff on your site, go to AdminCP->Under the "Members" section click Search->Find the user you want to make staff->Click the little drop down arrow that is for their profile, and select "Edit User"-> Once the page has loaded, scroll down till you find "User Group" Select the group that you have set up for staff members. Once that is selected, scroll down to the bottom of the page and hit update. Job done.

**Comment by ajay55555** [comment]
Thanks It's work
