### ISSUE TITLE
User Uploaded Photo name Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#198]
when user post photo its default name shown in post which is looking very embracing and if i haven't write anything its post with place holder text "Say something about this photo... "
![photo name problem](https://cloud.githubusercontent.com/assets/13433124/8843903/6c7b9778-312c-11e5-8ef0-74120bbd45a1.png)

**Comment by Jinkers** [comment]
Does the name issue show up when you include some text with the photo?

**Comment by SalmanKhan86** [comment]
name issue remains same if i write some text with photo

**Comment by SalmanKhan86** [comment]
tested both on chrome and Mozilla OS windows 7
![name issue](https://cloud.githubusercontent.com/assets/13433124/8844177/aa7e8578-312f-11e5-909a-b929b12bcfb7.png)

**Comment by Jinkers** [comment]
I've tested on 2 live sites and a local xampp install. The name of the photo is the name of the photo that is being uploaded. If it is not then I don't know what is wrong. Having a feature to name the photo on upload would be a nice touch. Otherwise, I recall the image posting that place holder text being brought up before, but I can't remember where exactly. Will have to wait on @Data66PF to confirm these.

**Comment by orgazilla** [comment]
There will probably be a photo name rewrite option in the future.

**Comment by SalmanKhan86** [comment]
humm.yes @orgazilla agreed with you.photo name rewrite option is needed.what about say something text posted on wall

**Comment by Data66PF** [comment]
Confirmed that we need to enable the photo rename setting that seems not to be in the photo settings now.

**Comment by SalmanKhan86** [comment]
photo rename setting has't yet been enabled.its still same

**Comment by SalmanKhan86** [comment]
why photo name shown here that is uploaded by me.its looks very bad if my uploaded photo name is very long like 888888888888888-55666-55566-58556666-5555 this one.its appear there with this same name.  looks very embracing. pls improve this.

**Comment by one44** [comment]
Can pics not be changed to (Site_Name) 1,2,3,4,5, etc as this would help seo

**Comment by SalmanKhan86** [comment]
![photo name](https://cloud.githubusercontent.com/assets/13433124/10386696/17009cd8-6e78-11e5-9723-8f08e5d8d816.png)
