### ISSUE TITLE
[Image Counts] Adds Up From All Images

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#199]
Whenever someone updates their profile picture I believe it adds to their 'Total Image' count which appears on their profile menu bar. Clicking images then, shows no images there or at least an off count if they have other images. I'm not sure if this happens with feed photos, but I know those don't appear in your personal photos. Running the counters doesn't fix this.

My suggestion:

If possible, anytime you upload an image, regardless of where it is (New Profile Pic, Cover Photo, Activity Feed) it also adds it as an actual image to your image section in a respective folder. For example:

You could have three folders by default for each user: Profile Photos, Cover Photos, Activity Feed Photos. Uploading a photo using any of those features puts the photo in it's respective folder which allows for easy finding, editing, deleting if needed, etc.)

**Comment by Data66PF** [comment]
Feed images have always only been comments. This suggestion though was one wanted by other clients and a plugin had been made for v3 by webwolf. I think it would work in v4 perhaps and it's in my tutorials at my site.

However, I'll label this as an enhancement to see if he wants to change the process to add this feature.
