### ISSUE TITLE
PF Community, Clicking Notification shows Undefined

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#20]
V4 PHPfox community , main feed. Win 8 PC on Firefox 38.0.1

I had responded to a comment in the feed. The user responded back. I clicked the notification and got the following:

Undefined index: feed_total_like
undefined

**Comment by RaymondBenc** [comment]
I know this is a good while back, but do you recall what sort of feed it was (e.g. forum thread, blog etc...)?

Thanks!

**Comment by Data66PF** [comment]
Have two users as friends. User1 posts a status update. User2 comments on it. User1 gets a notification and clicks to see it. At the top of the feed shows the error of undefined index. Just tested again.

**Comment by RaymondBenc** [comment]
I believe this issue should be resolved in relation to the **undefined index**. If not, bump this post. :+1:

**Comment by Data66PF** [comment]
This is fixed.
