### ISSUE TITLE
how do I change rewrite

### ISSUE THREAD

**Issue by brutalbook** [moxi9/phpfox#202]
How do I set the rewrite so that it will stop adding /index.php/ to the path in the URL?

PF.Base/file/settings/server.sett.php is set to:

$_CONF['core.url_rewrite'] = '2';

Thanks.

**Comment by orgazilla** [comment]
Go to admincp, then go to settings and click short urls...

**Comment by Data66PF** [comment]
Please ask questions at the community http://community.phpfox.com as this is only for bugs.
