### ISSUE TITLE
[Activity Feed] Enhancement Request: Toggle Friends/Site

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#204]
There is currently an option to show the dashboard activity feed for everyone to be site wide or friends only. I think a great option would be a toggle button (if allowed by Admins per site) so that users can switch between friend feed and site wide feed without having to go to another page.

**Comment by Data66PF** [comment]
There is a V3 addon by YouNet that they will probably port into a V4 app but I'll mark this as an enhancement and see what Ray decides. We do try not to step on the toes of long time developers though.
