### ISSUE TITLE
Edit Profile Loading Issue

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#205]
Hi,

I noticed that when editing the profile using Chrome, the cursor change to a loading circle that never end. This issue turn impossible to click at profile tabs while editing your own user profile. 

This issue is happening with the Chrome 44.0.2403.89 on Windows 8.

**Comment by Data66PF** [comment]
I can't reproduce this in version 4.0.3 on chrome win 8.1. What do you see with debug enabled? What do you see in developer browser debug console in the network and in the Console tabs?

**Comment by aakash83** [comment]
I can reproduce this on your demo community. cursor is always in loading state however i can edit fields under "Basic Information tab" but "about me" tab is not working.
tested in chrome,Firefox, win7

**Comment by Data66PF** [comment]
Ok I see it now. It worked for me yesterday but today it doesn't if I don't refresh the page. 
SyntaxError: unterminated regular expression literal
http://community.phpfox.com/static/jscript/jquery/jquery.js?v=07d8f4d48b4175c00430bdd403d0fcf2
Line 27
