### ISSUE TITLE
Page Browser Horizontally Scroll

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#206]
Hi,
This isnt a bug, but is a UX problem. When browsing pages on Neutron theme in monitors with 1360 x 768 resolution, is necessary to scroll the page Horizontally to view the whole page content. In other hand the profiles fits well without the necessity of being scrolled.

This issue happens with my chrome 44.0.2403.89 and Mozilla 39.

**Comment by Data66PF** [comment]
Confirmed on the PF community and I'll mark this a bug in case it is one.
