### ISSUE TITLE
[Guest Dashboard] No Blocks Show Up Besides Signup

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#207]
I setup some blocks to show some featured users and an activity feed on the main dashboard page, however only the sign-up block shows up.

![image](https://cloud.githubusercontent.com/assets/6254165/8867636/dbb2755e-3199-11e5-83ab-e20c99326689.png)

![image](https://cloud.githubusercontent.com/assets/6254165/8867639/df5da4d0-3199-11e5-90e8-7c8cbd8dfef7.png)

**Comment by Data66PF** [comment]
Please note that questions should be asked at the community site if for making customizations. Note that the featured users block, if the app that is in our Github, is made not to show to guests. You will need to make a custom one if you want to show to guests. Please note that you have to enable user group settings for the feed.

**Comment by Data66PF** [comment]
If you would PM me at the PHPfox community or at my scripttechs site, I'll help you there. Note that I am on my own site more than the community.
