### ISSUE TITLE
"Say something about thia image" issue

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#211]
Hello,

I noticed that when you upload a image throught the feed and dont include any text about it, the script publish the default text. I think that in this case if no information in inserted the text should be empty insted of the default text.

**Comment by Data66PF** [comment]
Confirmed win 8.1 pro, firefox latest and this is a continuation of bug #198 . Confirmed at the pf http://community.phpfox.com/photo/1819/dog-is-sold/userid_51305/

**Comment by RaymondBenc** [comment]
Issued resolved for our next release, 4.0.4
