### ISSUE TITLE
After upgrade forum post showing html codes in news feed

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#212]
HTML was disabled in v3 but after upgrade i see html codes in news feed of forum posts images etc not showing of posts it was added with TinyMCE.

**Comment by Data66PF** [comment]
This looks the same as #188 but for the forum module and I see the issue in the Recent Posts block for it. Will confirm for the recent posts block. Main feed is fine in my tests.

**Comment by Ylmzef** [comment]
For me showing HTML code due to old TinyMCE, not bbcodes.

**Comment by RaymondBenc** [comment]
This is something we cannot fix internally as we no longer support HTML in any sections of our product. However, we have an app in development that is awaiting the release of 4.0.4 in order to be released.

**Comment by Ylmzef** [comment]
I have never used html on mysite.
Also on v3 too.
If you can check my other ticket you can see it's only about img and br tags.
For reproduce this issue please setup phpfox v3 than post on form with images atachments etc or use line breaks in status share with enter. Than update to v4 than you can see the html tags on news feed..

Thanks,
