### ISSUE TITLE
After upgrade some times news entry not showing in home page.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#213]
There no error codes etc news feeds entrys not showing.

**Comment by Data66PF** [comment]
Make sure you do not have the feed settings enabled for Activity Feed Entries Cache and Activity Feed AJAX

**Comment by Ylmzef** [comment]
Why do i need disable it?
It's very important for site speed.

**Comment by Data66PF** [comment]
No those settings are not very important. Those settings do not work. They are brought over from v3 and do not work.

**Comment by Ylmzef** [comment]
Now disabled, but still im getting sometimes this result as i click so much on home link in menu.

![download](https://cloud.githubusercontent.com/assets/8562514/8895090/dd9f4c58-33cd-11e5-9d20-c8c734b3e625.png)

**Comment by Data66PF** [comment]
Does your server fully support V4?

**Comment by Ylmzef** [comment]
Of course like i mentioned in other issues.

**Comment by RaymondBenc** [comment]
If a feed does not show, it is usually related to a JavaScript error on the page since it uses JS to load each feed. Enable **Firebug** on Firefox or Chromes developers tools to see what JS errors you are getting.

**Comment by Ylmzef** [comment]
I disabled Activity Feed Entries Cache & Activity Feed AJAX & redis cache its now fine.
