### ISSUE TITLE
Cant remove installed apps

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#214]
I click uninstall in apps settings page but cant get any result.

**Comment by Data66PF** [comment]
I can't reproduce this. Are you using 4.0.3? Do you see errors with debug enabled? Do you see the notice to provide an email and password confirmation before uninstalling an app? Which app?

**Comment by Ylmzef** [comment]
Debug mode enabled and its v4.0.3 site upgraded from v3.
Its not clickable.

**Comment by Ylmzef** [comment]
Still having this issue in 4.0.4 version.
If i click uninstall button im getting "The page you are looking for cannot be found." error.

**Comment by Data66PF** [comment]
Is this for new apps? Which app? Did you do the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view.

**Comment by Ylmzef** [comment]
Yes its about all phpfox apps for v4.

**Comment by RaymondBenc** [comment]
Sadly each issue you are coming in with we cannot reproduce and they all seem server/browser related. You will need to get in touch with us so we can test these issues on your server.

**Comment by Ylmzef** [comment]
I sended to you e-mail from phpfox.com 3 days ago but still no response..

**Comment by Ylmzef** [comment]
Im still waiting response from you.

**Comment by Data66PF** [comment]
Are you sure you emailed hello@phpfox.com? You can't send emails on the phpfox forum and have him respond there.

**Comment by Ylmzef** [comment]
I used contact form in phpfox.com

**Comment by Data66PF** [comment]
ok check for any replies in spam.

**Comment by Ylmzef** [comment]
Nothing.

**Comment by Ylmzef** [comment]
Still cant remove now in 4.0.5 its clickable and when i click uninstall button im getting "The page you are looking for cannot be found." error.
For all installed apps.

**Comment by srikumar101** [comment]
Even I have the exact same issue.. I am on 4.0..9.. I am unable to uninstall any app.. is there a way to manually delete them from SFTP?

**Comment by Ylmzef** [comment]
As seen:Each issue that i posted are not coming in with you cannot reproduce and they all seem not  server/browser related. 

@Data66PF & @RaymondBenc
