### ISSUE TITLE
Installation v3 Modular Apps in Upgraded site

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#215]
How can i install that was installed in my old v3 moduler after upgrade?

**Comment by orgazilla** [comment]
http://support.phpfox.com/admin-tips/installing-v3-modular-apps/

**Comment by Ylmzef** [comment]
Its for fresh install.
I asked it for upgraded site from v3.
We have already module files uploaded, but there no install button in admincp.

**Comment by orgazilla** [comment]
I think most V3 apps don't even work with V4...

**Comment by Data66PF** [comment]
You will need to wait for third party developers to make their modules for v4. Please note that questions should be asked in the PHPfox community as the bug tracker is not for questions.

**Comment by Ylmzef** [comment]
Installing v3 Modular Apps only for fresh installed v4 than?
Also check question label https://github.com/moxi9/phpfox/labels/question

**Comment by Data66PF** [comment]
I know about the question label. This is not for asking questions like that though. It is more for asking questions for developers. This is a bug tracker.
