### ISSUE TITLE
Cant add e-gifts more than one

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#216]
I cant add second egift in admincp from upgraded site.

**Comment by Ylmzef** [comment]
Also added picture of egift not showing.

**Comment by Ylmzef** [comment]
And i added categoris firs also disabled schulde. now im trying enable schulde option in categorie im getting following error:

Exception thrown with message "Undefined index: do_schedule"

Stacktrace:
#11 Exception in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:118
#10 Whoops\Exception\ErrorException in /home/xxxxxxxxxxx/public_html/PF.Base/module/egift/include/component/controller/admincp/categories.class.php:99
#9 Whoops\Run:handleError in /home/xxxxxxxxxxx/public_html/PF.Base/module/egift/include/component/controller/admincp/categories.class.php:99
#8 Egift_Component_Controller_Admincp_Categories:process in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:963
#7 Phpfox_Module:getComponent in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#6 Phpfox_Module:getController in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:307
#5 Phpfox_Module:setController in /home/xxxxxxxxxxx/public_html/PF.Base/module/admincp/include/component/controller/index.class.php:648
#4 Admincp_Component_Controller_Index:process in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:963
#3 Phpfox_Module:getComponent in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#2 Phpfox_Module:getController in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1278
#1 Phpfox:run in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:73
#0 require in /home/xxxxxxxxxxx/public_html/index.php:7

**Comment by Data66PF** [comment]
I can't reproduce this. Please wait for v4.0.4 to be released and see if it works for you then.

**Comment by Ylmzef** [comment]
Upgraded to 4.0.4 but still having the issue.

**Comment by Data66PF** [comment]
Did you do the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view.

**Comment by Ylmzef** [comment]
Now well but still the issue.

**Comment by RaymondBenc** [comment]
I was not able to reproduce the initial issue, however I was able to reproduce **Undefined index: do_schedule**.
