### ISSUE TITLE
After upgrade forum blocks showing complex

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#218]
![download](https://cloud.githubusercontent.com/assets/8562514/8892126/e581a330-3346-11e5-9ed3-56a5f256823d.png)

**Comment by orgazilla** [comment]
So, could you explain the problem...this picture doesn't show anything because everything is blurred out.

**Comment by Ylmzef** [comment]
Only text blurred, its about blocks width.

**Comment by Data66PF** [comment]
I can't confirm this. Did you change anything? Please go to AdminCP >> Themes and click the Neutron theme to edit it. At the left, select Revert Theme. Clear cache. 

If you are using a different theme, which one?

**Comment by Ylmzef** [comment]
I don't changed anything just upgraded from v3.
Also i do revert theme and cleared cache and im using default template of v4.

**Comment by Ylmzef** [comment]
Its now fixed after updated counters in admincp.
