### ISSUE TITLE
Forum Search redirects to home page without any search results

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#222]
When we  search something in forums>> some category   for example   on phpfox community   goto forum >> Neutron  and then  search something using the search box on top. it  will redirect you to your main page without any search results.  However  if we do this search on  the main forum page it works normally . Also  the search result page URL is looking bit strange containing lot of duplicates as shown below.

http://community.phpfox.com/?s=1&http%3Acommunity.phpfox.comforum114neutron-v4=&search%5Bsearch%5D=data66

Tested in Chrome and Firefox with Win7

**Comment by MBonner702** [comment]
Confirmed

**Comment by Data66PF** [comment]
confirmed win 8.1 pro, firefox, PF community and my dev site.
