### ISSUE TITLE
After upgrade from v3 to v4 im getting errors.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#223]
Im getting this errors in server error_log:

http://pastebin.com/5WiBnS2b

**Comment by Data66PF** [comment]
Those all look old from before this recent one. do you have any errors showing that are recent? You can either remove that log and see if a new log is created or just save a copy before removing it.

**Comment by Ylmzef** [comment]
Still same errors: http://pastebin.com/Htk8ZpaE
Phpfox v4.0.4

**Comment by RaymondBenc** [comment]
Based on the stack trace the error is **AH01797: client denied by server configuration**. If you have .htaccess rewrite rules try to [check this out](http://stackoverflow.com/questions/12140559/error-with-htaccess-and-mod-rewrite).

**Comment by Ylmzef** [comment]
AH01797: client denied by server configuration error is only for dev folder i have restricted the folder for other ips.

Please check other errors are for live site

**Comment by Data66PF** [comment]
We are unable to reproduce this with our test sites and no clients have confirmed this issue.
