### ISSUE TITLE
Double Pages

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#224]
When you create a page, you always get two of them instead of one.

![doublepage](https://cloud.githubusercontent.com/assets/13330878/8898745/6c64a7ec-33f8-11e5-8415-cddf1081411b.jpg)

**Comment by Data66PF** [comment]
I cannot reproduce this with v4.0.3, win 8.1 pro, firefox browser. Make sure you didn't accidentally click twice or it would have made two. Make sure you selected the subcategory after selecting the main category. (Example: Main Category is Band or Product and subcategory is Appliances)

**Comment by orgazilla** [comment]
I figured out this is an issue with one of my MYSQL tables...
