### ISSUE TITLE
Issue in mentions from comments

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#228]
![download 1](https://cloud.githubusercontent.com/assets/8562514/8918883/6640e588-34bb-11e5-9a7d-e67f5b5211bc.png)

**Comment by aakash83** [comment]
i can reproduce this on your demo community.

**Comment by Data66PF** [comment]
I believe this is related to #146 . Please test after 4.0.4 is released

**Comment by Ylmzef** [comment]
Still the issue on after 4.0.4!

**Comment by GloriousKoch** [comment]
Confirmed. Updated to 4.0.4 and I'm getting this with mentions as well.

**Comment by aakash83** [comment]
yes i can also confirm this with 4.0.4

**Comment by Data66PF** [comment]
Did you all ensure to follow the upgrade steps I posted http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in and upload a profile pic if you hadn't joined.

**Comment by aakash83** [comment]
this issue can be reproduced on PF community also.

**Comment by RaymondBenc** [comment]
Issue has been resolved for our next release 4.0.5, which should be released later today.

**Comment by aakash83** [comment]
i can see it is not resolved in 4.0.5 . i can reproduce this on your demo community.

**Comment by Ylmzef** [comment]
me too

**Comment by Data66PF** [comment]
reproduced on the PF community. Waiting to see if running the Update Counters will restore the old images as it should.
