### ISSUE TITLE
unable to delete friends feed items

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#229]
I can't see a option to delete friends feeds option appearing on my wall. I can only delete my own posted items. 

![image](https://cloud.githubusercontent.com/assets/406030/8920059/2f30496c-34c5-11e5-8e22-1d09a96b7135.png)

tested on PF community using chrome and firefox and win7.

**Comment by Data66PF** [comment]
As we don't have it set to allow users to delete other user's feeds, please test on your own test site with the user group setting set to allow users to delete other users feeds.

**Comment by aakash83** [comment]
can you specify which settings is this?? i can't find any setting like this.

**Comment by Data66PF** [comment]
Did you look in user group settings for the user group you are testing? Check in settings for feed and for comment as I'm not in admin atm

**Comment by aakash83** [comment]
ok i got it but  there is a problem . for example  I posted something on my wall  which one of my friend don't like and he don't want to see it on his wall so he simply delete that item. by doing this, that  item is also  deleted from my wall.  what my question was to  how users   can  hide something  that they don't like from their walls posted by their friends. but  it does not means that we delete the  original item.   hope u understand.

**Comment by Data66PF** [comment]
You'll need a customization or wait to see if a developer makes an app for that.
