### ISSUE TITLE
Upgraded to 4.0.4

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#230]
I upgraded as mentioned here http://support.phpfox.com/upgrading-phpfox/manually-upload-files/
But after upgrade stil all bugs from old versions.
Like delete notifications button.

**Comment by GloriousKoch** [comment]
Note that not EVERY bug in the issues list is fixed with this release. They work on them a bit at a time. Is the bug/bugs you're experiencing comparable to those listed as fixed in the blog post? If so which ones?

**Comment by Ylmzef** [comment]
It is fixed bugs, check fixed bugs list.

**Comment by GloriousKoch** [comment]
Okay. It's best to still keep the discussions for each individual bug in their own topic. It will make it easier to diagnose each one separately. I recommend closing this issue as it simply states "all bugs" and giving your feedback in the individual issues. :)

**Comment by Ylmzef** [comment]
I cleared cache from admincp but its showing "No cache date found."
It did not work.
Removed cache folder content after that its showing so small icon.

![naamloos](https://cloud.githubusercontent.com/assets/8562514/8921903/4e918908-34dc-11e5-9a21-468493f6ea7c.png)

**Comment by Data66PF** [comment]
Did you do the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view.

Closing as too vague. Please post ONE issue in ONE report for us to be able to test. Please check for open issues first.

**Comment by Ylmzef** [comment]
Now wel but still the issue.
