### ISSUE TITLE
V 4.0.4  layout problem

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#231]
Just installed v4.0.4 and spotted a layout problem . Page cover image has a lot of  blank space on both sides as you can see below.
![image](https://cloud.githubusercontent.com/assets/406030/8921033/269bf59c-34d1-11e5-85c8-4469f8152282.png)

tested with chrome, firefox , win 7 ,

**Comment by Data66PF** [comment]
Did you do the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view.

**Comment by Data66PF** [comment]
Oh I see you are talking about the community. I believe this is how that theme is designed.

**Comment by aakash83** [comment]
i think it was not like this in v4.0.3
