### ISSUE TITLE
problem with Videos module

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#232]
While browsing  http://community.phpfox.com/videos/   if  we play a video  then  without closing it  just click  on any empty space on the page (not video)  , Video  will disappear  but sill it is playing somewhere in background and we can hear the sound but we cannot see it .Now there is no way to close it or do any other action on it because it is just invisible. only solution is to refresh page. 

tested with  chrome, firefox , win 7

**Comment by Data66PF** [comment]
Video module bugs should be posted in the video module. https://github.com/moxi9/phpfox-videofeed/issues/1 but please see that open bug report.
