### ISSUE TITLE
Forum Thread  counter shows wrong value

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#233]
Goto  forum  then start a new thread , write something and  post it.  Number of replies will be shown as 2 even nobody replied to it.  see the screenshot below. 
![image](https://cloud.githubusercontent.com/assets/406030/8922036/d52529ba-34dd-11e5-81ea-34055625bf0a.png)
if  we click on this  counter value which is  2 in this case  then the script will change it to 1. can be reproduced on PF community.

**Comment by Data66PF** [comment]
I can't reproduce it. http://community.phpfox.com/forum/thread/52239/imma-test/ That thread shows two replies and the count shows 2 replies.

I see what you mean. You mean the post number for each post is off by 1 digit. I'll confirm that issue. @RaymondBenc Note that it is not the reply count in the main area, it is the post number.
