### ISSUE TITLE
Forum Permission Can't Change or edit

### ISSUE THREAD

**Issue by sithu015** [moxi9/phpfox#235]
I use Version 4.0.4. I can't change forum permission. Can select the User Group. But Can't change Forum Permissions. I try to click on Yes or No Button. But these button are not turn to red color.

**Comment by Data66PF** [comment]
Looks like he fixed that today in 3b960abc50e2614aba86bc532d542de8b3e329af

**Comment by RaymondBenc** [comment]
Correct, fixed in dev build and will be pushed to clients build later today.
