### ISSUE TITLE
Page photo issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#237]
If a page don't have a photo its showing white blocks in place of page photo.
http://community.phpfox.com/pages/
http://community.phpfox.com/pages/303/

**Comment by Data66PF** [comment]
v4.0.4 confirmed on pf community and test site.

**Comment by Ylmzef** [comment]
The still white blocks in place of page photo.

**Comment by Ylmzef** [comment]
still same issue on v4.0.8

**Comment by SpeakLife** [comment]
Yes I am still experiencing for 4.0.9 as well. I have a mobile application as well and the white blocks show up for the thumbnails. I was told it may not be parsed correctly.
