### ISSUE TITLE
[Activity Feed] Posted Youtube Videos 'Break' On Click

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#238]
When someone posts a youtube video, it generates the thumbnail in the post, which makes sense. However when you click the thumbnail image to play the video while still on the site, it pops a window up with an 'Page Not Found' error.

![image](https://cloud.githubusercontent.com/assets/6254165/8947626/2a67fbfe-356b-11e5-8af2-7d3f46ab4ba4.png)

![image](https://cloud.githubusercontent.com/assets/6254165/8947632/2e7a8270-356b-11e5-8084-be500aae85a4.png)

**Comment by aakash83** [comment]
i can reproduce it on PF community. in fact it was earlier posted by someone but i guess it was closed .

**Comment by Data66PF** [comment]
If this is for the video feed app, https://github.com/moxi9/phpfox-videofeed please post it to that app's issue tracker.
