### ISSUE TITLE
[Error Message] Image To Large Not Showing

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#239]
When a user uploads an image with a size that's too large for their permission level, it gives them a red box and doesn't upload. It needs to have words there telling them why it didn't work such as:

You can only upload images 'x' size and lower.

![image](https://cloud.githubusercontent.com/assets/6254165/8948126/946c0256-3571-11e5-9ba5-e2c5d2f5ec88.png)

**Comment by Jinkers** [comment]
confirmed on win 10, win8.1 pro and 7 on chrome and firefox. Both live dev site and community install.

**Comment by Data66PF** [comment]
In my v4.0.4 install, using win 10 on firefox, it shows an error message that the image failed. Are you using v4.0.4 and did you do all of the upgrade steps mentioned previously?

**Comment by Data66PF** [comment]
We are unable to reproduce this with our test sites.
