### ISSUE TITLE
Facebook connect profile photo issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#241]
Facebook connect users profile photo not showing: http://community.phpfox.com/photo/album/profile/420978/fb-1457912304534104/

**Comment by Data66PF** [comment]
Please post fb issues on the app issue tracker https://github.com/moxi9/phpfox-facebook/issues

**Comment by Data66PF** [comment]
Labeled as Community issue for now until Ray decides if it's a bug for this issue tracker or needs to go on the other issue tracker.

**Comment by Ylmzef** [comment]
Still issue!

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-facebook/issues please post fb issues there
