### ISSUE TITLE
Hide Main Menu option issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#242]
I enabled Hide Main Menu in admincp but its shwoing on password request	page etc.
Like as on phpfox community: http://community.phpfox.com/user/password/request/

**Comment by Ylmzef** [comment]
And its showing on ipad too from register page.

**Comment by Data66PF** [comment]
Confirmed on PF community but not sure if this is by design.

**Comment by RaymondBenc** [comment]
This setting is no longer used in v4. With the upgrade to v4.0.5 we have run a query to remove any settings we don't longer use.

**Comment by santoshbadal1111** [comment]
Can anyone tell how to hide menu item for particular user group in phpfox 4.3.0 as there seems no setting for showing and hiding menu in new version.

**Comment by neil96** [comment]
@santoshbadal1111 Please ask question at our [community](http://community.phpfox.com/)
