### ISSUE TITLE
echo into a block postion inside start.php

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#243]
Hi,

I'm trying to convert my v3 modules into v4 apps, but to do so in a easy way, I need to know how can I accomplish this:

To be more especific about my question I show this example of code inside start.php

new Core\Route('/hello-world', function() {
echo "Hello World!";
});

This will echo the phrase inside the page "hello-world"

My questions is how do we do the same (without calling for external html files), not to echo it into a page, like the example, but echo it into a block position?

Thanks

**Comment by RaymondBenc** [comment]
More info here https://github.com/moxi9/phpfox/issues/171#issuecomment-124160693

Note, v4.0.5 will introduce a new method to work with blocks, which will be much easier then the current method.
