### ISSUE TITLE
User profile page issue for showing pages of user.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#244]
Profile page of user showing all site pages of the site not user owned pages.

![naamloos](https://cloud.githubusercontent.com/assets/8562514/8973262/2c64aada-3663-11e5-9788-1807c20ada4a.png)

**Comment by Data66PF** [comment]
Confirmed on PF community viewing my profile as a guest.

**Comment by Ylmzef** [comment]
Stil not fixed on community site..

**Comment by RaymondBenc** [comment]
http://community.phpfox.com/profile-data66/pages/ Latest update looks fixed to me. Can you still confirm on your profile?

**Comment by Data66PF** [comment]
Be sure to fully clear browser cache before checking as it's fixed for me after a browser cache clear.

**Comment by Ylmzef** [comment]
Its now fixed.
