### ISSUE TITLE
Ads Do Not Display

### ISSUE THREAD

**Issue by whookka** [moxi9/phpfox#245]
I have deleted and re-entered all my existing ads, but they do not display. I have also checked chrome, ei, current browser firefox. I have html and basic image display ads, but neither are visible.   This is my first trouble report, please let me know if you need more info.
Thanks

**Comment by Data66PF** [comment]
Admin created ads are made in normal blocks. Did you make these ads in admincp?

I'll confirm this as there is a spot to add an ad in AdminCP Manage Sponsorships. Note though that with sponsorships created in AdminCP before, they would only show in block 50. At this time, for some reason, block 50 only shows on editing the ad, it does not show to create the ad.

If I edit the ad to change position to block 50, I get an undefined index Undefined index: c_ad_body 
Exception thrown with message "Undefined index: c_ad_body"

Stacktrace:
#12 Exception in /home/mysite/public_html/mysite/PF.Base/start.php:127
#11 Whoops\Exception\ErrorException in /home/mysite/public_html/mysite/PF.Base/module/ad/include/service/process.class.php:202
#10 Whoops\Run:handleError in /home/mysite/public_html/mysite/PF.Base/module/ad/include/service/process.class.php:202
#9 Ad_Service_Process:update in /home/mysite/public_html/mysite/PF.Base/module/ad/include/component/controller/admincp/add.class.php:106
#8 Ad_Component_Controller_Admincp_Add:process in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:963
#7 Phpfox_Module:getComponent in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:520
#6 Phpfox_Module:getController in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:307
#5 Phpfox_Module:setController in /home/mysite/public_html/mysite/PF.Base/module/admincp/include/component/controller/index.class.php:653
#4 Admincp_Component_Controller_Index:process in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:963
#3 Phpfox_Module:getComponent in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:520
#2 Phpfox_Module:getController in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1278
#1 Phpfox:run in /home/mysite/public_html/mysite/PF.Base/start.php:82
#0 require in /home/mysite/public_html/mysite/index.php:7
