### ISSUE TITLE
Theme Adminpanel does not save changes  

### ISSUE THREAD

**Issue by whookka** [moxi9/phpfox#246]
along with saving basic color changes, logo will not display on all browsers. 
Thank you

**Comment by Data66PF** [comment]
Which browsers? Are you using v4.0.4?

**Comment by whookka** [comment]
Sorry for not getting back sooner...other projects.    I have tested on all browsers and I am using 4.04. I have cleared all caches...The one thing I haven't done is clearing the ads and starting over. I was hoping it was a bit more seamless, but stuff happens.  Please let me know if you need more info.

Thanks

**Comment by RaymondBenc** [comment]
@Data66PF steps to reproduce? I tested to manage a theme and modify the **Body background color** and it updated on my end. I am testing now the logo issue.

**Comment by RaymondBenc** [comment]
I was able to reproduce the logo issue and fixed it for our upcoming release, 4.0.5.
https://github.com/moxi9/phpfox/commit/58cb1b2f67a13daf0fd0efd10db01a92ff2f7efc

Leaving the case open until I get more info from @Data66PF regarding the other issue.

**Comment by whookka** [comment]
Thank You Raymond
