### ISSUE TITLE
Problem with forum's feed items

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#247]
Forum feeds  appearing on a user wall are not pointing to main thread. they points to current reply which triggered this feed item. which makes no sense.

![image](https://cloud.githubusercontent.com/assets/406030/8975580/085e6c70-3681-11e5-991e-c369357d67c8.png)

**Comment by Data66PF** [comment]
It has always been designed this way. I made a fix for v3 at ScriptTechs but you'll need to make a fix or have a developer make one as this is how it's designed.

**Comment by aakash83** [comment]
if it is  designed like this then then is not a right way to design it. why not we get it fixed in V4. we payed for script  but can't pay for fixes as it is developer's responsibility to fix script's bugs. there are lot of issues like this where we get this reply " it is designed like this".
