### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by ESA55** [moxi9/phpfox#249]
Updates of new versions of v4 phpFox open a field to enter the database information and then present an error that says "We have found that the following table(s) already exist:"

See forum http://community.phpfox.com/forum/thread/52069/we-have-found-that-the-following-table-s-already-exist/

**Comment by Data66PF** [comment]
Please ensure you are using the licensed client version when installing to a webserver and not a developer copy as it requires the license keys in order to install properly.

**Comment by ESA55** [comment]
Solution: do not delete the installed files. Copy the files of the new version replacing the changed files . That's it ...
