### ISSUE TITLE
Enable debug mode issue from upgraded site

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#250]
I upgrade from v3 to v4 and i upload dev.sett to under /public_html/PF.Base/include/setting, but its not working. Then i upload it to under /public_html/PF.Base/file/settings there working it fine!

**Comment by Data66PF** [comment]
We have a new method of debug that will be posted soon.

**Comment by Data66PF** [comment]
To enable debug go to yoursite.com/PF.Base/tools/debug.php and enter your license key and id. This will toggle debug to enabled. Visit it again to disable debug when you are done.
