### ISSUE TITLE
Unable to write to temporary folder: /root/tmp/

### ISSUE THREAD

**Issue by webcityuk** [moxi9/phpfox#251]
Trying to upgrade from 3.8 to 4.04 and I get the error message:
Unable to write to temporary folder: /root/tmp/
When running the upgrade script: www.mysite.com/index.php?phpfox-upgrade=true
I've created a directory /root/tmp and /tmp with 777 permissions but still the upgrade stalls.

Can you suggest a solution?

**Comment by Data66PF** [comment]
This is only for bugs. Server issues need to be asked at the community.
