### ISSUE TITLE
Responsive layout issue in forums

### ISSUE THREAD

**Issue by delixyr** [moxi9/phpfox#253]
I had earlier reported an issue with forums [here] (http://community.phpfox.com/forum/thread/51893/forum-design-and-responsiveness/)
This had been solved but I still see the main content scrollable sideways to read the whole content in forums on my phone.
Device : Blackberry Q10
OS : BB 10 OS version 10.3
Browser : Inbulit default BB browser.

![img_20150803_070008](https://cloud.githubusercontent.com/assets/4602841/9030025/3ee9a9d0-39ba-11e5-8a33-790f85beee22.png)
![img_20150803_070014](https://cloud.githubusercontent.com/assets/4602841/9030026/3eed8dd4-39ba-11e5-9af3-efd1f84a0b07.png)

**Comment by Data66PF** [comment]
Please always state the device OS, version and browser used to test.

**Comment by delixyr** [comment]
Updated device details in the first post :)

**Comment by Data66PF** [comment]
We need other people with a blackberry to test this please. I don't see this issue in iPhone testing.

**Comment by Jinkers** [comment]
Confirmed blackberry z30

**Comment by Data66PF** [comment]
Marked a bug after confirmation from another user that can reproduce this.

**Comment by RaymondBenc** [comment]
For those using Blackberry, do you know the screens default resolution?

**Comment by delixyr** [comment]
Blackberry Q10
720 x 720 pixels (~328 ppi pixel density)

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by delixyr** [comment]
Thank you!

**Comment by Data66PF** [comment]
Fixed 4.0.10
