### ISSUE TITLE
[Activity Feed] Comments Disappear Past Two

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#254]
If more than two comments are entered on an activity thread, it 'hides' the rest, but doesn't show any way to view them, such as a "view more comments" option.

It DOES show okay on the actual image comments page though:

![image](https://cloud.githubusercontent.com/assets/6254165/9030470/17438020-3971-11e5-9e7c-d76ed5ba8282.png)

![image](https://cloud.githubusercontent.com/assets/6254165/9030475/209b0aee-3971-11e5-85a8-0783b488cbd5.png)

**Comment by Data66PF** [comment]
had you enabled the comments ajax cache setting? Any of those old cache settings for feed or comments had bugs. Now, the settings can't be seen so you would need to check the database. I can't reproduce this on Neutron default theme.

**Comment by Data66PF** [comment]
Ok I see what you are talking about. Please include settings next time for us. :)

Set the Comment cut off on Feeds to 2.

Make a few comments on a photo or something.

View the main feed and you will only see two of the comments with no View more or no indication that there are other comments.

Bug. V4.0.4

**Comment by SalmanKhan86** [comment]
is this issue relate with Previous Problem .pls check
Wall Comment Loading Problem #191
