### ISSUE TITLE
Event issue

### ISSUE THREAD

**Issue by mobicomfi** [moxi9/phpfox#256]
First: 
I cant choose event end time

Second:
I have in country list 2 countries Finland and Estonia. If i choose event location Estonia, then it shows still Finland and if i update, nothing change.

I have upgraded version from 3.8 to 4.0.4

**Comment by Data66PF** [comment]
Please only post one issue per bug report.

**Comment by Data66PF** [comment]
I've checked both issues with debug on. 

Issue #1 is confirmed, I see no way to put an end time or date.

Issue #2 is confirmed as this:

1. I go to edit the event I just created and change the country to Estonia
2. I save it and get an Undefined Index for event_id. 
Exception thrown with message "Undefined index: event_id"

Stacktrace:
#10 Exception in /home/site/public_html/site/PF.Base/start.php:127
#9 Whoops\Exception\ErrorException in /home/site/public_html/site/PF.Base/file/cache/template/event_template_default_controller_add.html.php.php:22
#8 Whoops\Run:handleError in /home/site/public_html/site/PF.Base/file/cache/template/event_template_default_controller_add.html.php.php:22
#7 require in /home/site/public_html/site/PF.Base/include/library/phpfox/template/template.class.php:3216
#6 Phpfox_Template:_requireFile in /home/site/public_html/site/PF.Base/include/library/phpfox/template/template.class.php:3202
#5 Phpfox_Template:_getFromCache in /home/site/public_html/site/PF.Base/include/library/phpfox/template/template.class.php:2491
#4 Phpfox_Template:getTemplate in /home/site/public_html/site/PF.Base/include/library/phpfox/module/module.class.php:567
#3 Phpfox_Module:getControllerTemplate in /home/site/public_html/site/PF.Src/Core/View.php:127
#2 Core\View:getContent in /home/site/public_html/site/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1519
#1 Phpfox:run in /home/site/public_html/site/PF.Base/start.php:82
#0 require in /home/site/public_html/site/index.php:7

**Comment by ASNLifestyle** [comment]
So will this be added to the next update?

**Comment by muhammadnaeemahsan** [comment]
hope!

**Comment by RaymondBenc** [comment]
1) The ability to add an end date from v4 has been removed. The technical functionality exists so an app could be created to simply display it via CSS.

**Comment by one44** [comment]
That makes no sense as all events have a start and finish time/Date

**Comment by ASNLifestyle** [comment]
After reviewing the event module again after new build you still can not add an end date.
