### ISSUE TITLE
Basic help!!

### ISSUE THREAD

**Issue by zslutzky** [moxi9/phpfox#261]
Our developer ditched us and now I'm installing the script by myself.  I really need some help as they totally left us in the dark.  And I hardly know how to code.  I am doing what it says in the readme.md and I did all the permission 0777 stuff and terminal stuff but now "open up your favorite web browser and fire up the web installer." <<what link is that? Can someone let me know?? Thanks!!!!!!!!!!!!!!!!!!!!!

also-- if I installed phpfox in a subfolder, do I need to "update" my licensed domain?

Honestly I;m not even sure where our developer licensed it.  this weird webmaster thing comes up when I  go to http://www.socialripple.org/index.php?do=/admincp/

thanks! wish I was a coder!

**Comment by Data66PF** [comment]
This is only for bugs but you can get help at the http://community.phpfox.com or at my scripttechs.com site.
