### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#262]
When i get notifications like for reply that i subscribed or messages, i click and read notifications but still blue warning badge appear.
![download 1](https://cloud.githubusercontent.com/assets/8562514/9077324/1a397704-3b2d-11e5-9aa0-42eddd037bb4.png)

**Comment by aakash83** [comment]
Already posted here #196 . hope it will be fixed in next version.

**Comment by Ylmzef** [comment]
It's about friend requests, but this about messages and notifications section.

**Comment by aakash83** [comment]
ok then a possible answer from them will be " It is designed like this"

**Comment by Data66PF** [comment]
Did you refresh the page after reading the notification?

**Comment by Ylmzef** [comment]
It was for 4.0.5 and now fixed on 4.0.7
The issue commented 22 days ago..
