### ISSUE TITLE
Buttons & text areas & input & forms elements issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#263]
I see the elements cant be realized/designed.
It's only for me so or it's already so?

![download 2](https://cloud.githubusercontent.com/assets/8562514/9077419/4966f8e8-3b2e-11e5-9fb7-feffbf623743.png)
![download 3](https://cloud.githubusercontent.com/assets/8562514/9077421/49686d0e-3b2e-11e5-8f69-febe8786c0a3.png)
![download 4](https://cloud.githubusercontent.com/assets/8562514/9077420/49677304-3b2e-11e5-81bb-d07a8731cdcd.png)
![download 5](https://cloud.githubusercontent.com/assets/8562514/9077423/4969cc30-3b2e-11e5-93cb-7b9c855917a7.png)
![download 6](https://cloud.githubusercontent.com/assets/8562514/9077422/4969b6aa-3b2e-11e5-84e1-4a3f7032c8a7.png)

**Comment by Data66PF** [comment]
You can still use template overrides if that is what you are asking. You can create a theme and change what you want changed. I'm not sure exactly what you are asking as you have more than one issue posted.

**Comment by Ylmzef** [comment]
Illustrate what I mean:
Do you know how many text inputs on this picture? :disappointed_relieved:
![download 6](https://cloud.githubusercontent.com/assets/8562514/9485375/c034c1ea-4bb8-11e5-97f0-c683ca0ecd63.png)

Answers is 3 :joy:
![download 7](https://cloud.githubusercontent.com/assets/8562514/9485378/c39337c2-4bb8-11e5-9797-43e2a8b3bc89.png)

**Comment by Jinkers** [comment]
Still failing to see what you are asking about.

**Comment by Data66PF** [comment]
Please only test things that are part of V4. Polls in the feed are not part of V4.

**Comment by Ylmzef** [comment]
It's upgraded site and i see still Poll button.

**Comment by Ylmzef** [comment]
Can i see anohter duplicate issue?

**Comment by Data66PF** [comment]
As there are themes in the store with these things changed, this is closed as all of the things can be changed. As for the status update buttons still showing, that is in another github to be removed from showing as they are not supported in v4.
