### ISSUE TITLE
Subscriptions compare issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#264]
I cant compare with free signup package. I can add it as free package for compare with paid membership package but if a already paid user click on purchase button of free package than paid user going again free user group.

**Comment by Data66PF** [comment]
This is normal. If a user clicks to change to free, it has always put them back in free.

**Comment by Ylmzef** [comment]
But there apear purchase button, you cant purchase for free things :)
And this not bug report this featered request.

**Comment by Data66PF** [comment]
We don't take feature requests in the Github bug reports.

**Comment by Ylmzef** [comment]
Can you change purchase button for free package than?
Its a bug & diversion i think

**Comment by Ylmzef** [comment]
I'm still waiting for answer.

**Comment by Data66PF** [comment]
Please post in the feature request area at the community as there is one now here, http://community.phpfox.com/forum/122/neutron-v4-feature-requests/

**Comment by Ylmzef** [comment]
I know but i think it's a bug.
You can't purchase free things or not? :smiley:
