### ISSUE TITLE
Multilangual for report categories

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#265]
Please add multilangual option for report categories.

**Comment by Data66PF** [comment]
Have you gone to the phrase manager and added the report categories?

**Comment by Ylmzef** [comment]
Please go to admincp/report/add/ you can add only category name.
There may be added extra options for other languages.

**Comment by Data66PF** [comment]
I'll confirm that we not only can't see a menu for the report categories but I see no way to add translations for it.

**Comment by Data66PF** [comment]
Just to clarify for @RaymondBenc , we need the menu for Reports admincp/report/ so we can see things being reported and as above, we need it multi-lingual.

**Comment by Data66PF** [comment]
Changed to critical as we need to be able to administer our websites and reports are very important.

**Comment by RaymondBenc** [comment]
https://github.com/moxi9/phpfox/commit/01f78816cafad6b231d57280e7f52bd684108b2b

**Comment by RaymondBenc** [comment]
For the Reports section, to add a phrase you add the HTML version of a phrase.

Example...
```
{phrase var='user.user_banned'}
```

**Comment by SalmanKhan86** [comment]
where can we add phrase in it.

**Comment by PhpFoxJohnJr** [comment]
Not sure why this is closed as I have 4.09 and there still is not an area that I can see to see reports and to add categories.  Although if I put in the url
 admincp/report/add/

I can get to it to add categories and see the reports.

**Comment by Data66PF** [comment]
The area is there for me in my 4.0.9. Go to Maintenance >> Reported Items.

**Comment by PhpFoxJohnJr** [comment]
WOW!  Been looking at this script on a daily basis for over a month and never clicked that since I assume maintenance menu was for maintenance of the code/software.

Thank you!  Hopefully this will help others as well.
