### ISSUE TITLE
Custom blocks not showing after upgrade

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#266]
I had custom blocks in v3 but after upgrade to v4 i cant find the blocks.

**Comment by Data66PF** [comment]
V3 blocks are not supported in V3 unless you've updated them yourself. Please check in your block manager for them.

**Comment by Ylmzef** [comment]
Where is blcok manager?

**Comment by Data66PF** [comment]
AdminCP >> Blocks

**Comment by Ylmzef** [comment]
I checked there already but can't find my custom php block.

**Comment by Ylmzef** [comment]
I can't find still the block.
It was coding of php more than 50 lines..
If v3 block not supported on v4 you need mention it for v3 clients.

**Comment by Data66PF** [comment]
It was mentioned that v3 stuff is not supported in v4 and needs to be remade. All v3 things are disabled for v4 (custom things) so as not to break the upgrade routine. Please make the block again with updated code if needed.

**Comment by Ylmzef** [comment]
It was just custom php block not a module or so.
Than custom html blocks not supperted too in v4?
