### ISSUE TITLE
User photo Albums not showin in profile page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#267]
http://community.phpfox.com/profile-natio/photo/

**Comment by Data66PF** [comment]
Seems fine to me. Clicking on his profile photo brings me to his profile photos also.

**Comment by Ylmzef** [comment]
I mean not profile photo. The url that i meantioned is for photos page of the user and there are no photos showing. or albums etc..

**Comment by Data66PF** [comment]
I see them but I'm on the friend list. Are you friends?

**Comment by Ylmzef** [comment]
No, im not on the friend list.
Im friend list on this user: http://community.phpfox.com/profile-239120/photo/
I see now photos of this user but not albums.

**Comment by Data66PF** [comment]
That user has only one photo. There is no setting to show as album now. Did you mean that?

**Comment by Ylmzef** [comment]
I have the albums test and test2 but there not showing the albums only showing photos.
http://community.phpfox.com/darbeg/photo/

Also album links:
http://community.phpfox.com/photo/album/2495/test/
http://community.phpfox.com/photo/album/2502/test2/

and this photo dont have any album why? http://community.phpfox.com/photo/2300/332079_417281678308841_2146215339_o/userid_408103/

**Comment by Data66PF** [comment]
As mentioned, and please note what I am asking.

"There is no setting to show as album now. Did you mean that?"

**Comment by Data66PF** [comment]
I'll just confirm that there is no Album menu link in the profile for this bug. It is only for the profile section.

**Comment by Ylmzef** [comment]
It's showing wrong for me on v4.0.6 upgraded site and using legacy theme.

**Comment by Data66PF** [comment]
![profile albums](https://cloud.githubusercontent.com/assets/6908282/9361127/04a4b250-4668-11e5-923f-128dee241ed7.png)

Please check with default theme and please ensure that you followed all of the upgrading steps. I have a tutorial for that at my site if you need it.

**Comment by Ylmzef** [comment]
I done it before I need to do it again?

**Comment by Data66PF** [comment]
Well I'm not sure it will reinstall but you could try loading it back to the site I guess. Default theme should always remain on the site, even if not used, because some things rely on it being there even when using a different theme as many things are based on that theme.

**Comment by Data66PF** [comment]
As for following the upgrading steps posted at my site, it needs to be done every time you upgrade the site.

**Comment by Ylmzef** [comment]
I updated again but it's still same.

**Comment by Data66PF** [comment]
You followed the steps for the upgrade and you are testing with the default theme?

**Comment by Ylmzef** [comment]
I removed default theme i follewed the steps and tested with legacy theme.

**Comment by Data66PF** [comment]
I mentioned not to remove default theme.

**Comment by Ylmzef** [comment]
i know but i don't use it.

**Comment by Ylmzef** [comment]
It's now fixed in v4.0.7
