### ISSUE TITLE
Members

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#268]
Members onlineshow as member number not member user name......................

**Comment by Data66PF** [comment]
Please do NOT post adult photos.

Please let us know details of what this is for. Is it for an app, a new theme, the default theme? Can you provide an example WITHOUT adult images?

**Comment by one44** [comment]
Ok Sorry was not thinking. It is a module I have contacted module developer.It is just hard to get hols of module developers as there are no longer links with each module or ap.
