### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#270]
Since upgrade code showing in forums
![2015-08-05 09_39_03-the complications of a bdsm mind adult social networking community for bdsm an](https://cloud.githubusercontent.com/assets/13656046/9080636/014a7120-3b56-11e5-8cd2-e9df0eea5016.jpg)

**Comment by mobicomfi** [comment]
Use this app and it goes back to normal http://store.phpfox.com/product/846/allow-html

**Comment by Data66PF** [comment]
Html is not supported by default in V4. The way to make it work is using the app. Note that we are not responsible for hacks to your site by you allowing html to be used on it. It was disabled for security.
