### ISSUE TITLE
member info 

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#271]
When click member info nothing happens. A popup shows  Live support for a second. Click member profile same result. If member has nothing to show the popup should say so. not a blank page.
![2015-08-05 10_24_42-king_grimbat - male - united states - new york adult social networking communi](https://cloud.githubusercontent.com/assets/13656046/9081436/94199502-3b5c-11e5-95b4-b85d279adb57.jpg)

**Comment by Ylmzef** [comment]
Was mentioned for 4.0.4 #234 but still not fixed in 4.0.5

**Comment by Ylmzef** [comment]
It's still not woking on 4.0.6

**Comment by CimborNet** [comment]
I have the same issue. 
I have long wanted to write it, but thought it was just me such problem.
As example: the user all the information filled in and him profile is open. But when somebody open his the profile section INFO nothing is displayed.

**Comment by Ylmzef** [comment]
If about section is blank it's showing nothing.
Like user gender location city custom fields etc.

**Comment by Jinkers** [comment]
Working perfectly fine for me on the PF Community Site. You need to understand that by default not all the items in the information section of the editing profile will be displayed under the info tab. You need to assign the blocks and controllers to the positions that you want them to be. Those basic details show up else where like under their name and on the right site of the default page.

**Comment by Ylmzef** [comment]
Its already enabled
![download](https://cloud.githubusercontent.com/assets/8562514/9398948/a262065a-47ad-11e5-806a-07b4303d7749.png)

**Comment by Ylmzef** [comment]
Still waiting response for this..

**Comment by one44** [comment]
This is working but I find I have duplication's so have had to remove most of the blocks.

**Comment by Ylmzef** [comment]
Info means not only about.
Info means gender, location, age all things about profile they need listed there too.
It was so on v3.
