### ISSUE TITLE
Share Text is Missing in Pages Post 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#272]
when we go to someone pages post then we can't able to share it.either share ribbon is not open or its open then why share text is missing in it Windows 7 OS
![share text missing in page](https://cloud.githubusercontent.com/assets/13433124/9081898/d74735ac-3b7d-11e5-9a3a-c4f9bcd4cc96.png)

**Comment by aakash83** [comment]
confirmed

**Comment by Data66PF** [comment]
It depends on the item. Go here, http://community.phpfox.com/wog/ and click a few of the different feed items. You will see that some allow sharing and some don't. This is by design and has been like this in v3 even.
