### ISSUE TITLE
Account Setting Not updated 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#273]
when we change name or something else its not getting updated in  Account Setting. Sometime it give Error 'Provide a valid Email Address' those Already we have in it.I think #pem in Address bar Url block it.
Windows 7 OS tested on Mozilla and chrome 
![account setting not updated](https://cloud.githubusercontent.com/assets/13433124/9084016/da5a37da-3b8c-11e5-9837-365abedace4c.png)
![account setting error](https://cloud.githubusercontent.com/assets/13433124/9084054/4060db56-3b8d-11e5-9e71-44d211c317fc.png)

**Comment by Data66PF** [comment]
duplicate. please search before posting bugs. #208
