### ISSUE TITLE
[4.0.5 Upgrade Issue] PF.src\Core\View.php

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#275]
When I get to the file listed in the subject uploaded, the entire site turns white and I can not do anything and there are no debug errors that show. Every other file from the 4.0.5 upgrade is present and the site comes back online when I replace the View.php file with the 4.0.4 version.

Not 100% sure what this file is or does, so leaving site in offline mode until I can get this fixed. Any idea on how to fix this or what would be causing it? Also, what it's used for? Thanks.

**Comment by Jinkers** [comment]
The error code as displayed by debug:

Twig_Error_Loader thrown with message "The "/home/obamnetw/public_html/mysite.com/PF.Base/../PF.Site/themes/11/html" directory does not exist."

Stacktrace:
#6 Twig_Error_Loader in /home/obamnetw/public_html/mysite.com/PF.Base/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:93
#5 Twig_Loader_Filesystem:addPath in /home/obamnetw/public_html/mysite.com/PF.Src/Core/View.php:17
#4 Core\View:__construct in /home/obamnetw/public_html/mysite.com/PF.Src/Core/App.php:71
#3 Core\App:__construct in /home/obamnetw/public_html/mysite.com/PF.Base/include/library/phpfox/plugin/plugin.class.php:91
#2 Phpfox_Plugin:set in /home/obamnetw/public_html/mysite.com/PF.Base/include/init.inc.php:177
#1 require in /home/obamnetw/public_html/mysite.com/PF.Base/start.php:34
#0 require in /home/obamnetw/public_html/mysite.com/index.php:7

creating the html folder at the displayed error address enables website to be viewed however most pages are not loading correctly. forums, polls(endless loop), and blog are not loading. URL changes however the site does not update or reflect. Refreshing (both normal and cleared cache) doesn't yield any changes.

Error's occurred once upgraded from 4.0.5. Tested on win10, 8.1 pro and 7 machine on chrome and firefox browsers.

**Comment by Ylmzef** [comment]
Same!

**Comment by RaymondBenc** [comment]
New distribution build has been released: https://github.com/moxi9/phpfox-dist/commit/b5703cdb0df6a25e1cc7274ef741d2a23ed33b09

That build has the fix included. Download the package and simply replace the file **/PF.src/Core/View.php**

The specific fix can be found here:
https://github.com/moxi9/phpfox-dist/commit/b5703cdb0df6a25e1cc7274ef741d2a23ed33b09#diff-12cf05dd0dd99d2b56b19766b27d96bf

**Comment by RaymondBenc** [comment]
Public fix will be released later today with v4.0.6.
