### ISSUE TITLE
Some Profile Pic Not Appears in Search V4.0.5

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#276]
some profile pics not appears when we search (v4.0.5) i check it on http://community.phpfox.com/
Windows 7 OS
![serach snaps not appear](https://cloud.githubusercontent.com/assets/13433124/9103462/31a8c5bc-3c1c-11e5-893c-a3aec30e2aa5.png)

**Comment by Data66PF** [comment]
confirmed with win 10 and ff. 
inspect element shows
```
<img fb":"10153477040323711"}"="" src="http://community.phpfox.com/file/pic/user/{"> 
```

**Comment by RaymondBenc** [comment]
The fix provided in https://github.com/moxi9/phpfox/commit/8f927af21f6ca6a97162e0d6c647eda11d292858 is for the PHPfox side of things. The core issue is related to the FB app https://github.com/moxi9/phpfox-facebook and will require an update once v4.0.6 is released.

**Comment by SalmanKhan86** [comment]
issue still remain same in v4..0.6.in v.4.0.6 i am not able to search anything when i type one character its erase automatically.same problem we found in v4.0.4 already there.
