### ISSUE TITLE
Birthday date not showing in signup forum

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#280]
After upgrade to 4.0.5 birthday date not showing in signup forum.

**Comment by Data66PF** [comment]
Will confirm as the setting is not found atm in User >> Settings.

**Comment by qsrs** [comment]
Gender is also missing

**Comment by RaymondBenc** [comment]
We've added back the AdminCP settings page for **Tools >> Settings >> User >> Registration** in v4.0.6.
