### ISSUE TITLE
Missing "phpfox.json" file.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#281]
Im getting missing "phpfox.json" file error when go to /PF.Base/tools/dev.php.

**Comment by Data66PF** [comment]
You need to go to /PF.Base/tools/debug.php.

**Comment by Ylmzef** [comment]
And what for dev.php?

**Comment by Data66PF** [comment]
Just do like mentioned. That is all that is needed. don't change or add anything.
