### ISSUE TITLE
Missing Add Phrase Button

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#282]
Hi,

This isnt a bug but a feature that I couldnt localise at admincp. The previous version (V3) has a add phrase option however the actual version (V4.0.5) dont display this option anymore.

I think that at phrase menu at admincp should exist a "add phrase" button equal other admincp settings.

**Comment by Data66PF** [comment]
I'll confirm the add phrase is gone but I think it's designed this way.

**Comment by RaymondBenc** [comment]
Is this in relation to an Admins perspective or someone developing a module?

**Comment by Data66PF** [comment]
For admin to add a phrase.

**Comment by leandrotavaresrocha** [comment]
is from a admin perspective. I own a multilanguage community and frequently I need to create multilanguage categories for pages, photos and blogs. Without this feature multilanguage community will be overloaded by categories.

**Comment by leandrotavaresrocha** [comment]
I forget to say, but recently I discovered that is possible to access the old add phrase routine typing "admincp/language/phrase/add/".

The problem of use this solution is that all phrases created are added to "ad" module.
