### ISSUE TITLE
Blogs in V4.0.7

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#283]
Posted blogs in previous version are not showing in V4.0.5

**Comment by Data66PF** [comment]
Were these from the default blog module or did you have a third party module?

**Comment by Verdz** [comment]
Default blog module.

**Comment by Data66PF** [comment]
Are you using short urls?

**Comment by Verdz** [comment]
YES

**Comment by Data66PF** [comment]
after upgrading to 4.0.7, I am not able to access blogs. I see an error undefined index aitems 

Exception thrown with message "Undefined index: aItems"

Stacktrace:
#10 Exception in /home/mysite/public_html/mysite/PF.Base/start.php:134
#9 Whoops\Exception\ErrorException in /home/mysite/public_html/mysite/PF.Base/file/cache/template/blog.controller.index.php:6
#8 Whoops\Run:handleError in /home/mysite/public_html/mysite/PF.Base/file/cache/template/blog.controller.index.php:6
#7 require in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:3235
#6 Phpfox_Template:_requireFile in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:3221
#5 Phpfox_Template:_getFromCache in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:2510
#4 Phpfox_Template:getTemplate in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:567
#3 Phpfox_Module:getControllerTemplate in /home/mysite/public_html/mysite/PF.Src/Core/View.php:135
#2 Core\View:getContent in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1519
#1 Phpfox:run in /home/mysite/public_html/mysite/PF.Base/start.php:89
#0 require in /home/mysite/public_html/mysite/index.php:7

**Comment by Verdz** [comment]
I can now access blogs in versions V4.0.6 and V4.0.7 and IE 11 and firefox nightly but not in Google Chrome and Safari. Using windows 7 64 bit.

**Comment by RaymondBenc** [comment]
Can the same issue be reproduced on our community? This was a known issue in v4.0.6 and requires a clear cache of template files in order for it to be fixed.

**Comment by Data66PF** [comment]
I had cleared it and did the template files but will do again.

**Comment by Data66PF** [comment]
Cleared cache again and still have same errors. Theme was reverted again. I cannot reproduce it at the community but I don't have debug running on that.

**Comment by RaymondBenc** [comment]
Is this on your public dev site?

**Comment by Data66PF** [comment]
Yes

**Comment by Data66PF** [comment]
Still have the same issue on my live dev and locals using this latest github version.
