### ISSUE TITLE
Missing gender selection during signup.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#284]
There no gender selection option during signup.

**Comment by SalmanKhan86** [comment]
how to add third gender in sign up

**Comment by Data66PF** [comment]
Cannot reproduce in v4.0.7. Enabled it in the Registration settings. As for how to add another gender, please ask at the community.

**Comment by Ylmzef** [comment]
It was for 4.0.5 "commented 20 days ago"
