### ISSUE TITLE
[4.0.5] [Links] Posted Links On Profile Result In Buggy Text (Mobile & Desktop)

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#285]
A member posted a link to another member feed.

The link posted was: https://anthropomorphicavocado.files.wordpress.com/2014/08/avocados-are-hardcore_01.gif

This is how it appears on the activity feed (Nothing there):
![image](https://cloud.githubusercontent.com/assets/6254165/9125798/55a4bab0-3c72-11e5-834c-6cafc6d98622.png)

This is how it appears on mobile:
![image](https://cloud.githubusercontent.com/assets/6254165/9125811/6ca26816-3c72-11e5-9a8e-0eceb0d1429f.png)

This is the actual link 'page':
![image](https://cloud.githubusercontent.com/assets/6254165/9125822/a2c53914-3c72-11e5-8174-f6b5d25c129c.png)

**Comment by Data66PF** [comment]
Is this still an issue?
