### ISSUE TITLE
Debug enabled causes error message for invalid user group setting for is spam free

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#286]
V4.0.5. Win 10 local development. Running the new debug routine
http://localhost/fox4/PF.Base/tools/debug.php

I had left debug on when I signed out of the site and closed the browser. When I went back to this site again later, I get the error message:

 Invalid user group setting param: core.is_spam_free 

Whoops\Exception\ErrorException thrown with message "Invalid user group setting param: core.is_spam_free"

Stacktrace:
#8 Whoops\Exception\ErrorException in C:\xampp\htdocs\fox4\PF.Base\include\library\phpfox\error\error.class.php:99
#7 Whoops\Run:handleError in <#unknown>:0
#6 trigger_error in C:\xampp\htdocs\fox4\PF.Base\include\library\phpfox\error\error.class.php:99
#5 Phpfox_Error:trigger in C:\xampp\htdocs\fox4\PF.Base\module\user\include\service\group\setting\setting.class.php:48
#4 User_Service_Group_Setting_Setting:getParam in C:\xampp\htdocs\fox4\PF.Base\include\library\phpfox\phpfox\phpfox.class.php:938
#3 Phpfox:getUserParam in C:\xampp\htdocs\fox4\PF.Base\module\user\include\service\auth.class.php:590
#2 User_Service_Auth:handleStatus in C:\xampp\htdocs\fox4\PF.Base\include\init.inc.php:199
#1 require in C:\xampp\htdocs\fox4\PF.Base\start.php:34
#0 require in C:\xampp\htdocs\fox4\index.php:3

**Comment by RaymondBenc** [comment]
Do you know the user group you were logged in as?

**Comment by Data66PF** [comment]
admin

**Comment by Data66PF** [comment]
cannot reproduce this now
