### ISSUE TITLE
Friends Only Community Setting Missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#287]
The Friends Only Community Setting is not there. It is found in Core settings on V3. We don't want our communities as Friends Only if we want a social network. Most of us want open communities. Please put the Friends Only Community Setting and Section Item Privacy Setting (as they go together) back for us to be able to turn them off.

**Comment by RaymondBenc** [comment]
Isn't the **Friends Only** setting in "Name & Copyright"?

**Section Privacy Item Browsing** is already enabled by default.

**Comment by Data66PF** [comment]
Sorry meant please put the section item privacy setting in there for us to disable. We don't want that setting, most clients. We want open communities. sorry for the mislabel.

**Comment by Data66PF** [comment]
For those looking to disable this for now, backup the database and go to your phpmyadmin. Go in the phpfox_setting table and find setting_id 135 or around there. var_name is section_item_privacy_browsing and set the value_actual to 0. Clear cache but note that if you have the Friends Only Community active then you must keep this setting enabled.

**Comment by RaymondBenc** [comment]
Have you tested "section_item_privacy_browsing"? It isn't part of the source routine any longer.

**Comment by Data66PF** [comment]
I've tested on my dev. With it enabled, the site has a long lag before loading. With it disabled, the site loads fast. Are we sure the script isn't doing something with this setting? I can't account for the huge difference in load times from it being enabled/disabled.
