### ISSUE TITLE
People Who Likes This Box Profile Pic Missing

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#288]
when we click on people who likes this. in pop up box some profile pic is missing there.those people with there actual profile. although default profile pic is coming.tested on V4.0.5 windows OS
![profile pic in like box](https://cloud.githubusercontent.com/assets/13433124/9129222/bab5f8f8-3cf2-11e5-977b-f36b0257c578.png)

**Comment by SalmanKhan86** [comment]
any solution for this.

**Comment by Data66PF** [comment]
Confirmed at PF community

**Comment by RaymondBenc** [comment]
Issue fixed for v4.0.8
