### ISSUE TITLE
Share status turns into Message

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#289]
when we share someone status we have to manually select one by one friends.its  big problem when i have thousand of friends.then share turn into Message.its not working like Photo sharing.also when person  open a shared msg in Message tab its looks like buggy long text and include all names with the msg shared.
![share status problem](https://cloud.githubusercontent.com/assets/13433124/9129544/ce075de4-3cf6-11e5-9c24-07acd9433182.png)
![share msg](https://cloud.githubusercontent.com/assets/13433124/9129550/d84e597e-3cf6-11e5-82b5-75be51094924.png)

**Comment by SalmanKhan86** [comment]
any solution for this

**Comment by Data66PF** [comment]
This how it's designed. Some things are shared only by emails as they are just comments on the site and not actual content.

**Comment by SalmanKhan86** [comment]
i know how its designed.but can you change this functionally so that working like as well as photo share. Another option can be added in this. in this way its working in both ways.

**Comment by Data66PF** [comment]
Right now we are not taking feature requests. We need to first focus on core bugs which cause the default features not to work as designed. Later, we can look at features perhaps.
