### ISSUE TITLE
Few Bugs in the v4rc2

### ISSUE THREAD

**Issue by warrisdeepsingh** [moxi9/phpfox#29]
in the blog category section it gives unlimited repeating of the same sections.
and same for forums 

changed registration name to split into last and first name and 
first name bar have some <div issues must see

**Comment by RaymondBenc** [comment]
For the first issue I wasn't sure how to reproduce this. Do you have a screenshot?

For the 2nd issue, how did you get to the option to split the last/first names?

**Comment by warrisdeepsingh** [comment]
Let me reproduce that issue

I will send you as soon as possible....

**Comment by warrisdeepsingh** [comment]
​Just scroll down and down and u will see endless reloading


and that was for 1st issue


let me find the reproduction for 2nd issue

i will contact u soon and please we are waiting for stable

On Mon, Jun 22, 2015 at 1:49 PM, warrisdeep singh <warrisdeepsingh@gmail.com
> wrote:

> Let me reproduce that issue
>
> I will send you as soon as possible....

**Comment by Data66PF** [comment]
I can't reproduce the first issue either. How many blogs do we need to have in the blog section to test and what browser/os are you testing with?

**Comment by Data66PF** [comment]
In regards to where the setting is for split first/last name, I had to find it by finding the v3 setting id and going to direct url, http://mysite.com/index.php/admincp/setting/edit/?setting-id_251/ and scroll down. Lots of interesting settings there lol.
