### ISSUE TITLE
Admin CP core Module is not open in Maintenance

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#290]
when we click on Maintenance>finding missing setting in admin cp then core module is not open it Redirect back to Dashboard.All other is opening well.Problem is with V4.0.5 Windows 7 OS
![core setting](https://cloud.githubusercontent.com/assets/13433124/9129677/7b5e19dc-3cf8-11e5-8241-f18caa250bdb.png)

**Comment by Data66PF** [comment]
The core module is not supposed to be there. http://yoursite.com/admincp/module/?view=all 
Core was removed from the list of accessible things.

**Comment by Data66PF** [comment]
Will bug this but I don't think it's a bug. However, running the Find Missing Settings does show Core in the list. We need Core as it's the Core. Not sure if we need to disable the links to all of those that show.

**Comment by SalmanKhan86** [comment]
not fixed yet.now its not showing anything after its finish find missing setting.its redirect back to dashboard.

**Comment by Data66PF** [comment]
That is how it is supposed to work.
