### ISSUE TITLE
How to add menus in profiles?

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#293]
If I add to the app.jason this:
"menu": {
    	"name": "Acme",
    	"url": "/acme",
    	"icon": "smile-o"
    }

It creates a menu item on the main menu, linking it to a page. How do we do the same for:
1 - Profile menus.
2 - Admincp menus.

Thanks

**Comment by RaymondBenc** [comment]
At the moment you can use internal hooks, similar to v3 to add menus.

In your app, create a folder called **hooks/**

For the users profile, create a file called **profile.service_profile_get_profile_menu.php**

In that file add:
```php
<?php

$aMenus[] = [
	'phrase' => 'Test',
	'url' => $aUser['user_name'] . '.test',
	'total' => 4
];
```

For the AdminCP, create a file called **admincp.component_controller_index_process_menu.php** and add
```php
<?php

$aMenus['<i class="fa fa-diamond"></i> Custom App'] = 'admincp.yourapp';
```
