### ISSUE TITLE
admincp.index on V4

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#294]
When I go to blocks in admincp I don't see the controler admincp.index

How do we manage blocks on admincp dashboard? And if I want to create an app to add a block to admincp dashboard what is the controller?

Thanks

**Comment by Data66PF** [comment]
http://support.phpfox.com/apps/blocks/ I've not checked in admincp but did you check the tips in that tutorial?

**Comment by cespiritual** [comment]
Yes, I have read that tutorial and the new way of creating blocks it's much easier.

But my questionis is about the admincp.index. I don't see it on blocks, and so I can't manage the dashboard blocks or add a new block to it.

Thanks

**Comment by Data66PF** [comment]
Admincp.index shows in my list when in the block manager to create a block.

![acp block](https://cloud.githubusercontent.com/assets/6908282/9150072/9c9bdf9c-3d95-11e5-9934-1c3e9e888566.jpg)

**Comment by cespiritual** [comment]
Yes, you are right. But on the left list the controller is not there, so you can't manage the blocks on admincp.index.

**Comment by Data66PF** [comment]
It should show up once a block is added to it. That's how it's always worked before for any page that can have blocks. A block needs to be added before it shows in the list. I found that issue with my app for amazon ads as sitewide didn't show on the list either but once the block was added, then it showed in the list.

**Comment by cespiritual** [comment]
I have created a new block on admincp.index. It shows on admincp dashboard, but now I can't disable it because on the left list there is no link for admincp.index controller.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-92 *
