### ISSUE TITLE
Forum buttons

### ISSUE THREAD

**Issue by lethality** [moxi9/phpfox#295]
Just getting to grips with all the changes and this caught my eye whilst browsing the community site.
I "get" that you want new content buttons, to be in the top right, but I really think that in a forum it'd be contextually logical to have it somewhere relevant (top or bottom of the thread). It's so unnatural to be going up to the corners for things like that.
Also, the 3 buttons that appear at the bottoms of post "like, share/report and quote" could do with some kind of on-hover tooltip.
Obviously this isn't a show-stopping bug, but as a webdesigner and heavy user of various forums, there's just some things you expect to be a particular way.

**Comment by Data66PF** [comment]
Thanks for the suggestions but this area is only for bugs. We will have an area for feature requests in the near future, at the community.
