### ISSUE TITLE
Share a Link Feature

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#296]
Hi,

I am not sure if this is a bug since there are small difference between phpfox v4 fresh install and v4 upgraded.

The feature of post links at feed form is no more avaliable, however still working if you had upgraded from a v3 install. In the case of a v3 upgrade the post link works however it doesnt fetch the website image as before only the website title and description.

**Comment by Data66PF** [comment]
Posting links works via the status on the left at the member home page. Yes, it does not grab the image any longer.

**Comment by leandrotavaresrocha** [comment]
But the link display a "space" for the image as usual in V3 on the left of the link description. If is not a bug for the module is at least a issue fir the theme since is weird a blank space at left where is supposed to have a image.

**Comment by Data66PF** [comment]
What do you mean weird blank space? I just shared two links on the community site and the only one with an issue is the one for my page/group. It just doesn't pick up the user image sharing it but that's in another bug.

**Comment by leandrotavaresrocha** [comment]
Data I made a couple of tests and this questions seems to be more complex.

If you are upgrading from v3 you still with the access to the "link" option at feed form equal blog and poll. If you share something using this option (link) there is a blank are where before should have a link. 

If you are working with a fresh install you dont have anymore the link option so if you need to share something you need to paste the link at feed form. Now we have the following situations:

1- If you share a link without "www" sometimes it recognize as a link sometimes not. Seems that if the link shared has a subdomain it recognize as a link however if you are typing without a subdomain or  "www" it paste as a text only.

2- If you share a link with www the script recognize the link and try to fetch information. In some cases it grab a image in others no. I couldnt identify what is the origin of the difference, but I will assume that this is a domain destiny problem.

3- If you share a link to a video like a youtube video it grab the image but the video display a error.

**Comment by leandrotavaresrocha** [comment]
Data should I open a new issue or we can continue with this issue here?

If you want to check take a look at my profile at phpfox community. I made the tests there and you can see what is happening except the blank image space that only happens when you upgrade from a V3 Install.

**Comment by Data66PF** [comment]
Don't open a new issue. Where is the link to your tests?

**Comment by leandrotavaresrocha** [comment]
I added you as friend in phpfox commmunity. Take a look at my profile to see my posted links

**Comment by Data66PF** [comment]
They look normal to me. This is how they look in my V3 site too. some get images and some don't.

**Comment by Data66PF** [comment]
I forgot to test on my upgraded dev site for the status share links that should be disabled on an upgrade. Will test and respond later.

**Comment by leandrotavaresrocha** [comment]
Thanks data,

I made some test again at phpfox community and seems to be working different now. Links now are just parsed, no more description or image. Videos from youtube, by example, are also parsed as links.

**Comment by Data66PF** [comment]
Please remember that you have to copy and paste the url from the browser in order for the grabber to grab it. Is that what you tested?

**Comment by leandrotavaresrocha** [comment]
Yes, this was what I did.

Take a look what happens when I post a youtube video: http://i.imgur.com/X7xDTrL.png

**Comment by Data66PF** [comment]
I'll confirm the issue with a youtube video posted in a status link. Tested that on my dev. The other issues I think are working as designed but Ray can check to see. Not sure if the videos are meant to be shared just in the video app though. If so, then the grabber that grabs the videos for the feed needs to be changed as it goes to a page not found error.

**Comment by Data66PF** [comment]
Tested with v4.0.7 and youtube videos still have an issue when shared as a link in status share. Tested at PF community.

**Comment by RaymondBenc** [comment]
I need a YouTube link to test? There are different methods and a specific one must be causing the issue.

Thanks

**Comment by leandrotavaresrocha** [comment]
Hi Raymond,

I my version 4.0.7 development site the following link display a page not found:

https://www.youtube.com/watch?v=UOvZKJlrtk8
https://www.youtube.com/watch?v=3Oe7Q8OCm5I

**Comment by Data66PF** [comment]
https://youtu.be/qTSDL94_Y7M  also that. Any youtube won't work. Tested again just now at my dev site if you want to check it @RaymondBenc  :)

**Comment by Data66PF** [comment]
Cleared cache again and still have same errors. Theme was reverted again. I cannot reproduce it at the community but I don't have debug running on that.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8

**Comment by DaveN21** [comment]
I've tried to find a solution to this everywhere. Data (love your work very much), you say it isn't a feature anymore in V4 but in one instance it seemed to be hidden in some db features. Just really need to know if I can reinstate the same functions in V4 like it shows in V3 Nebula via Admin or any other way.
![sharelinks](https://cloud.githubusercontent.com/assets/10481337/12062958/237a0b3e-affa-11e5-832d-4fa57e67a0f7.png) Thank you for any help.

**Comment by neil96** [comment]
Once issue closed, please open new issue and reference to related issue.
Thanks!

**Comment by DaveN21** [comment]
Thank you Neil, much appreciated, will do :-)

**Comment by theXtremenetwork** [comment]
we just installed v4.5 and url sharing is not allowed in any part of any feed.  When a url either  a website or a video is placed in the feed, a red circle with a line through it pops up blocking the posting of the link. There's no post anywhere showing how this is allowed. We've posted a ticket and no one responded. We have a youtube channel and share and promote our videos via our site, how is it that there's a video link option without actually being able to share the videos? Can someone please explain why v4.5 isn't allowing us to post urls? 
DonnaScriptTechs commented on Aug 8, 2015
Posting links works via the status on the left at the member home page. Yes, it does not grab the image any longer.
