### ISSUE TITLE
Page profile photo not showing in feed.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#299]
![download 1](https://cloud.githubusercontent.com/assets/8562514/9151678/b20b5fb2-3e0b-11e5-84ff-f882f1e6e798.png)

**Comment by Data66PF** [comment]
Confirmed at the PF community. My group avatar does not show in the feed.

**Comment by Data66PF** [comment]
This appears to be an issue when posting as the page.

**Comment by Data66PF** [comment]
Fixed in 4.1.0
