### ISSUE TITLE
Ad Creation Can Not Be Completed

### ISSUE THREAD

**Issue by whookka** [moxi9/phpfox#300]
from the url  /index.php/ad/add/   and then "create ad"

There are a couple of issues:
1) placement of ad does not save (this occurs under "create an ad" and "upload an ad")
2) Under "create an ad" back ground and border colors do not save

**Comment by Data66PF** [comment]
Is this an upgraded site? Note that only block position 3 works for front end ad creation as it uses the multi ads like facebook. You would need to disable other ad positions for old ads. There is no Upload an Ad in V4. There is no background or border colors in V4. Please ensure you have fully upgraded the site and are not using old add ons or old links to create ads. Please clear cache, run the find missing settings tool, do not use anything from v3 on the v4 site.

**Comment by whookka** [comment]
Got it...I just disabled the link from a menu prior to upgrading. However, there is still one question I have...how to set up pricing for sponsored items?

Thanks for the help

**Comment by Data66PF** [comment]
Questions are asked at http://community.phpfox.com as this is only for bugs.
