### ISSUE TITLE
Fan Page Issue(s)

### ISSUE THREAD

**Issue by whookka** [moxi9/phpfox#301]
I apologize for multiple issues in one post but with an image it might be better explained all at once.
1) There is no "About" section to promote the company or org
2) No website link to company or org 
3) How to adjust menu or menu options 
4) cover image (header layout) should menu and thumbnail be at bottom of cover image?
5) Short Urls are not recognized when posting (they do not auto load as they did in V3)
6) Deleting posts
<img width="695" alt="screenshot-whookka com 2015-08-08 15-58-10" src="https://cloud.githubusercontent.com/assets/13561300/9152081/d869999e-3de8-11e5-8e56-9e6c13848d6e.png">

Thanks very much for your time

Marty

**Comment by Data66PF** [comment]
One issue will be addressed per bug report. Please search before posting. Note that the About section is in another bug report already. 

We will address issue 6 in this report as the others are feature requests or questions of how things work and those go in the community. 

For issue 6, did you have the setting enabled for the user to be able to delete feeds and comments?

**Comment by Data66PF** [comment]
No response. Issue closed but if you find the issue again, please post a new issue report.
