### ISSUE TITLE
Script Errors +

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#303]
On a Fresh Install, Active Site, with Members Present, we're getting Numerous "Script Error" in place of posts, and when you click on "What's Up?" to post, we're getting "Too Many Recurrences" errors instead of the window to post with... What is the solution to these problems so it doesn't make users think they can't see the posts or make posts? I've noticed that the "Script Error" is present in the PHPfox Community Site as well... Wouldn't it be better to put the posting window, with the options, back in the Feed like it used to be? Folks are lost on how to post on these sites enough, and we're losing members as a result... For the cost of the license, so far, I can't see where this is a better version... The AdminCP is missing too many controls too!

**Comment by Data66PF** [comment]
Please post the actual error. One issue per bug report will be addressed.

**Comment by Data66PF** [comment]
I just tested at the PF community and see no error. Please post the error you see on your site (the actual debug is needed) and the screenshot of the error you get at the community.
