### ISSUE TITLE
User pics (in forums) not displaying properly in MS Edge

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#304]
while browsing your  demo community in MS edge i noticed this issue shown in screenshot. this issue is only with forums.
![image](https://cloud.githubusercontent.com/assets/406030/9153083/8f60ca3c-3e43-11e5-9207-70efac274406.png)

**Comment by Data66PF** [comment]
confirmed when logged in. guest view works fine though.

**Comment by RaymondBenc** [comment]
Can this only be confirmed on MS Edge? or is this a general bug? The styling looks off on that page.

**Comment by Data66PF** [comment]
That's how it looks in edge. It is really odd. I don't see that for other browsers.

**Comment by neil96** [comment]
I can't reproduce this issue anymore on V4.1.2 MS Edge and IE11. Please open new issue if you can reproduce it again on V4.1.2.
