### ISSUE TITLE
white space under page header image

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#305]
white space is appearing under page header image
![image](https://cloud.githubusercontent.com/assets/406030/9153112/e727c986-3e44-11e5-8774-78dd50b409df.png)

**Comment by Data66PF** [comment]
That is the border for the image. It helps to define the image. If it were removed it would be hard to see the image. See the before and after.
![before](https://cloud.githubusercontent.com/assets/6908282/9154267/9c93b956-3e54-11e5-96d7-bb46d8b484aa.png)

![after](https://cloud.githubusercontent.com/assets/6908282/9154268/9fe4163c-3e54-11e5-9018-63f0692312c2.png)

you can remove the background from the css if you don't want to see that but, if you end up with a dark image on a dark cover, you won't be able to distinguish between the image and the cover. 
```
.pages_header_info .pages_header_image {
    min-width: 100px;
    min-height: 100px;
    background: #FFF none repeat scroll 0% 0%;
}
```
remove the background or replace with a color you prefer.
