### ISSUE TITLE
Can't disable custom pages.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#308]
I can't disable custom pages in admincp.
I'm getting "The page you are looking for cannot be found." errorr.

**Comment by Data66PF** [comment]
Can't reproduce in latest 4.0.5.

**Comment by Ylmzef** [comment]
It can disabled now but it's showing same message after disabled.
There no information about disable/enable.

**Comment by phpfoxdev** [comment]
You could reproduce by creating a page in ACP, page will not show but the message "The page you are looking for cannot be found."

**Comment by Data66PF** [comment]
Please label the bugs critical, minor or major.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-40 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.
