### ISSUE TITLE
Withdraw Funds

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#31]
Hi,

I have see that in this new version we have on our dashboard a button that say "Withdraw Funds"

But when I click I'm redirected to the apps list and nothing happen.

is this a bug, or this option is not available yet?

Regards

**Comment by phpfoxist** [comment]
Yeah I can´t withdraw my funds!

**Comment by RaymondBenc** [comment]
ATM, this feature is still being tested. I have removed the link for our next push to the servers. We are still doing manual withdrawals until we have ran a few more tests on this feature.

**Comment by vajaymenon** [comment]
Hi,

Is this for neutron?
