### ISSUE TITLE
cover photo is not visible properly .

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#313]
cover photo is not visible properly on profile page. there should be some crop or drag and set image option. this is making profile page horrible.

**Comment by lupuspl** [comment]
I agree

**Comment by Data66PF** [comment]
It depends on the height/width of the image loaded. I just tested several and you need to load a fb size cover image for it. This is how it is designed. If you have some example of how it is not visible properly, such as a screenshot (not an adult image though, no porn allowed) please post one as this looks fine to me, http://community.phpfox.com/profile-data66/

**Comment by lupuspl** [comment]
I know that it depends on the height/width of the image loaded.
But users do not need to know that.

**Comment by shakti7188** [comment]
but we are not giving any instruction to our users for size or anything. And infact there was something for it in v3 too. why u are escaping from this in v4.  
see this profile -
http://community.phpfox.com/shakti123/

**Comment by SalmanKhan86** [comment]
i agree.also facing same problem. in v3 its working fine.but now its becomes images stretch

**Comment by Data66PF** [comment]
It is designed to span the area there. I loaded a normal fb sized cover photo on my profile and that works fine. Things have always done this even in v3 there were things with profile photos if someone loaded the wrong size or cover photos would stretch. I post on my live community site what things people need to know for the site. Most people can search fb cover photo and find a bunch of them that work fine.

**Comment by Data66PF** [comment]
I'm going to leave this open for Ray's input to see if maybe it can be changed to a smaller size within the script or if you will need a template designer to change it.

**Comment by lordofnos** [comment]
same here... cover photo is streching and squeezing when resizing browser window. tested with latest ff.

**Comment by one44** [comment]
This should have a crop so that a section of the image chosen will fit and only a minimum size of say 1200X 500 or larger can be uploaded for purpose like with Facebook and twitter.

**Comment by Data66PF** [comment]
Please post feature requests at the community as we are trying to clear up the bug tracker to be just bugs (things that don't work in the script as it was designed) for now. Later on, perhaps we can look at the feature requests in the community. For now, we need to focus on the non-working parts to get the most stable version for the core.

**Comment by one44** [comment]
ok will do
