### ISSUE TITLE
There are no new feeds to view at this time.

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#315]
The Feed doesn't allow viewing older feed post beyond the number set for primary view. In other words, if you set the display limit to 20, that's all you can view, period... It says "There are no new feeds to view at this time." and doesn't let you view the other posts... It used to say "View More" and you clicked it to view more posts, and it no longer does that... We are a NEWS Site and have 200 to 500 posts a day, so this needs a fix...

**Comment by Ylmzef** [comment]
Same! there restriction for older post i think.

**Comment by TrueAmericans** [comment]
If that's the case, we'll have to set the post limit to 10,000 posts....

**Comment by one44** [comment]
I have opposite problem view more shows but just adds more posts without clicking on it so all posts will be shown when you scroll down

**Comment by Data66PF** [comment]
confirmed

**Comment by Data66PF** [comment]
Please test in the community again as it seems to work now

**Comment by TrueAmericans** [comment]
Confirmed... Now... What do we do to make it work in ours?

**Comment by RaymondBenc** [comment]
When taking a closer look at the hidden setting, in the latest build (4.0.5) that specific setting is already overridden and is set to **0**, which has no limit on how old a feed is. So the issue here is something else, unless that setting is not being overridden.

As I cannot reproduce this locally we need to test it on a clients site that has this issue.

@Data66PF do you have any of the clients details on hand?

**Comment by TrueAmericans** [comment]
I just now resolved my issue with it by setting up my old 3.8 and then doing an upgrade to 4.0.5... I am not the only one who had the problem, but that is what cured mine... I now have the 'View More" problem resolved on my site... It's really strange that I had to do an upgrade to fix it, but it worked, but, it didn't work on a Fresh install of 4.0.5 by itself... Just thought I'd let you know how I fixed mine, Ray...

**Comment by RaymondBenc** [comment]
@TrueAmericans 

> I know it's off topic, but are we ever going to have a 3rd column like 1 and 3 like it was in the 3.x format?

That is more theme related, but i can say that there is a theme in development that will have a 3rd column, similar to v3.

> Most of all, are we ever going to be able to directly upload videos like we could in the older versions?

There is an app that is currently being tested internally for this specific feature and should be released for public beta testing within the next 2 weeks.

**Comment by TrueAmericans** [comment]
Thank you Ray! Again, I appreciate all your hard work!

Your friend always,
Ken
