### ISSUE TITLE
too much recursion errors

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#316]
This is one of many errors we're getting on a fresh install with members... It happens when we click on "What's Up?" to post something...
"too much recursion" (See Attached Screenshot)
![too much recursion errors](https://cloud.githubusercontent.com/assets/13389534/9156791/be78913e-3eab-11e5-9831-b96f0d94f3f1.jpg)

**Comment by Data66PF** [comment]
Can't reproduce it at the PF community. Please tell us what browser and os you use. Do you have any plugins or things from v3 installed on the site?

**Comment by TrueAmericans** [comment]
Happens with Windows 7, 8.1, and 10... I have all 3... Also have Latest Firefox and IE 11... Does it with both... Like I said, fresh install of 4.0.5, no 3.8 anything... Just 4.0.5...
