### ISSUE TITLE
Tagging  is not working properly in status share

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#318]
While writing a status  if we write  @ symbol  it don't display list of friends ( like it do in comments) so we have to type full name for a friend which we want to tag.

**Comment by Data66PF** [comment]
confirmed at the PF community

**Comment by SalmanKhan86** [comment]
some avatar is not showing when we search some one.i check on pf community.windows 7 os
![avatar not showing in tagging](https://cloud.githubusercontent.com/assets/13433124/9378263/a67b16ca-473d-11e5-926e-46fff632ebc7.png)
