### ISSUE TITLE
UI Problems With Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#319]
there are lot of problems in UI With Android OS both on Chrome and Mozilla.pls check these screen shot taken from Android Mobile.Tested With http://community.phpfox.com/
![screenshot_2015-08-09-21-59-26](https://cloud.githubusercontent.com/assets/13433124/9159613/a139cdc4-3f49-11e5-867a-44b1e8a61729.png)
![screenshot_2015-08-09-22-04-38](https://cloud.githubusercontent.com/assets/13433124/9159611/a138c5c8-3f49-11e5-875b-cdc10c831e8b.png)
![screenshot_2015-08-10-09-32-01](https://cloud.githubusercontent.com/assets/13433124/9159612/a1390b3c-3f49-11e5-9413-f88c08e1965d.png)
![screenshot_2015-08-10-09-40-40](https://cloud.githubusercontent.com/assets/13433124/9159616/a13d2f1e-3f49-11e5-8e61-4c52e64c071f.png)
![screenshot_2015-08-10-09-42-46](https://cloud.githubusercontent.com/assets/13433124/9159615/a13cc6c8-3f49-11e5-93ac-e901d91876d5.png)
![screenshot_2015-08-10-09-54-10](https://cloud.githubusercontent.com/assets/13433124/9159614/a13a5dca-3f49-11e5-96cc-dd618b87675d.png)

**Comment by SalmanKhan86** [comment]
any solution for this..

**Comment by Jinkers** [comment]
@SalmanKhan86 As this hasn't been tagged as a 'bug' it won't be of the highest priority on their list as I'm sure you understand. However, I am working on some css tricks of my own for fixing these issues which I will post once complete.

**Comment by Data66PF** [comment]
Please post one issue per bug report. Please test with latest 4.0.8. I'll close this for now so you can test and post one issue per post for us please.
