### ISSUE TITLE
Unable to add "new group" in custom fields in admin

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#321]
Unable to add "new group" in custom fields in admin. After clicking "create new group" i filled all details and clicked "add group", then nothing happend , it shown no message and just came to add custom feild page . but when i check for recently created group in "Groups drop down" in right there is no other group than "about me" (which is a default group existed already).

Thread  i already have on this topic : 
http://scripttechs.com/forum/thread/2546/unable-to-add-quot-new-group-quot-in-custom-fields-in-admin/

**Comment by Data66PF** [comment]
I answered you there that you must enable the settings that my tutorial showed to enable or the user group cannot have a custom field.

**Comment by Data66PF** [comment]
I'm going to open this as the latest version is not allowing it when the previous version had no issues. I am seeing "Select a module this custom field will belong to." but there is no module to select. This error does not show every time but I still can't create a custom group now when I could previously.
