### ISSUE TITLE
How to manage blocks apps?

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#322]
Hi,

All the free apps that I have installed, that use blocks, like feature members, are not listed on blocks in admincp. So, how can I manage them? How can I disable an app block, change it's position or controller?

Thanks

**Comment by Data66PF** [comment]
I put it in the start.php for the user to select the block position. That way, it's a setting. So I made the setting in the json file and then put that in the start.php for the position.

**Comment by cespiritual** [comment]
hummm... that could be a way. But you can select the block position but not the order of it with the other blocks. You can also have a setting for the controller, but I don't see in the apps examples a setting for creating a combo box with several options to select. We need a tutorial about this.

Thanks
