### ISSUE TITLE
Disable option for languages

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#324]
Can you add disable option for languages please?

**Comment by Data66PF** [comment]
That setting is still in user group settings.

**Comment by Ylmzef** [comment]
Did you mean "Can manage language packages?"

**Comment by Data66PF** [comment]
Yes

**Comment by Ylmzef** [comment]
How can i disable per language like on v3?

**Comment by Ylmzef** [comment]
@Data66PF @RaymondBenc I'm still waiting for solution for this since 11 august

**Comment by Data66PF** [comment]
V3 had no setting to disable by user group per language pack. Please don't tag us for closed issues.
