### ISSUE TITLE
Forum attachments issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#325]
Before enable short urls i attached some photos in forum.
After enable shorts url attached photos in forum and in feeds not showing because attachments urls still contain /index.php/.

Also i updated counters.

**Comment by Data66PF** [comment]
tested on an upgraded dev site. I cannot reproduce this. the attachments that are in the forum threads are still attached, photos attachments still show.

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
