### ISSUE TITLE
Feed Setting for Feed Limit (Days)

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#327]
The feed setting for how many days back to get feeds is missing. This is making the feeds not show when we have smaller sites and could be the cause of issue #315

**Comment by RaymondBenc** [comment]
Based on this comment https://github.com/moxi9/phpfox/issues/315#issuecomment-130213745

When I took a closer look at the issue, the setting for "Feed Limit (Days)" isn't in use anymore. The query does not include a limit on the time stamp of a feed like it used to. So issue https://github.com/moxi9/phpfox/issues/315 has another problem altogether, that I cannot confirm locally.
