### ISSUE TITLE
Not able to Add Image or Code in Ad Creation

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#33]
We installed v3 fresh install.
i tried to create a ad campaign in ad module.
after selecting image/HTML code combobox option I'm not getting the image uploading option neither HTML add space.

Please help that what is wrong with it?

**Comment by RaymondBenc** [comment]
Thanks for the report. ATM, Github does not have built-in support to move issues, so if you can submit this to the v3 repo that would be great. You can find it at:
https://github.com/moxi9/phpfox-v3-dist/issues

Thanks!
