### ISSUE TITLE
Special characters in hastags issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#331]
http://community.phpfox.com/hashtag/test%C4%B0test%C4%9Ftest%C3%B6test%C3%9Ctest/

**Comment by SalmanKhan86** [comment]
Also hashtag Auto Suggestion is not working

**Comment by Data66PF** [comment]
We take one issue per bug report so will only address the OP's issue.

**Comment by Ylmzef** [comment]
You can confirm this than from phpfox community

**Comment by Data66PF** [comment]
When testing special characters and stuff, would you please post the exact phrase you used to test with? This way, we can test faster. 

Confirmed. 4.0.5. used testİtestğtestötestÜtest to test with

**Comment by Ylmzef** [comment]
It's fixed but the uppercase letters showing as lowercase.
Uppercase letters are very important for hastags..

**Comment by Data66PF** [comment]
Please open a new bug and reference this one in it.
