### ISSUE TITLE
Can't Create a New Group for Custom Fields

### ISSUE THREAD

**Issue by ckersey2** [moxi9/phpfox#332]
When I try to create a new group for the custom fields, it does not save and will not let me create a new custom field for the group that I just tried to create. It does not show up in the drop down field for the group. I have even checked in the database and it does not get saved.

**This first Screenshot shows when creating the new group.**
![screen shot 2015-08-11 at 7 02 00 pm](https://cloud.githubusercontent.com/assets/13756203/9212959/8d47a8d2-405b-11e5-82db-714058492890.png)

**This screenshot shows trying to create a new custom field with the new group now showing up.**
![screen shot 2015-08-11 at 7 02 16 pm](https://cloud.githubusercontent.com/assets/13756203/9212961/913c3d0e-405b-11e5-84ef-6343521bf5af.png)

**Comment by Data66PF** [comment]
please search before posting bugs. #321 duplicate.
