### ISSUE TITLE
Can't remove Anti-SPAM Questions

### ISSUE THREAD

**Issue by ckersey2** [moxi9/phpfox#333]
I have created 3 Anti-SPAM Questions. I want to remove two of them. When I click the "X" beside edit, it does nothing. If I click edit, it will let me edit the question and answer but it does not give me the option to delete/remove it.
![screen shot 2015-08-11 at 7 58 14 pm](https://cloud.githubusercontent.com/assets/13756203/9213725/b98916ee-4063-11e5-8c76-0762ff637f05.png)

**Comment by Ylmzef** [comment]
Me too! I removed it in phpmyadmin.

**Comment by Data66PF** [comment]
Confirmed.
```
SyntaxError: expected expression, got end of script
Line 1
$Core.User.Spam.deleteQuestion( $(this).data(
```
