### ISSUE TITLE
[Mentions] No notifications.

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#334]
Testing on a 4.0.5 site, on chrome and firefox, windows 7, 8,1 and 10, when you mention a member it does not notify them. Unable to replicate on live PF community site as tagging is not working properly. Getting same error (lack of notification) on test site.

**Comment by Data66PF** [comment]
confirmed 4.0.5 test site

**Comment by RaymondBenc** [comment]
Note, the fix provided is for @ mentions in comments to any items that make it to the feed. User will receive an email, with a link to the specific post.
