### ISSUE TITLE
Send Friend Request Button is Missing

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#335]
when i want to send friend request to all friends of my already friend member.then one has to depend on mouse hover effect or directly go to timeline(time consuming task).mouse hover effect is not working properly.some time is appear other time not.try again and again waste lot of time.So better to put here a send friend request button so user can easily send friend request.
![send friend request problem](https://cloud.githubusercontent.com/assets/13433124/9216029/b0cfcd1e-40d0-11e5-8224-2d6bd9865260.png)

**Comment by Data66PF** [comment]
Why do you need to be friends with everyone on my friend list? Anyway, feature requests will have a spot in the community soon so developers can make apps.

**Comment by SalmanKhan86** [comment]
i don't want to be friends with your all friend list.its just part of testing case.User can try anything we have to put here best user interface.

**Comment by Data66PF** [comment]
Thing is those friends are clients and many don't want to be bothered so it's a bit of a sticky situation.
