### ISSUE TITLE
Special Character Email Notification Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#336]
i received email of friend request accept.in this special character creating problem. check  
![gmail notification problem](https://cloud.githubusercontent.com/assets/13433124/9220354/a386703e-40ff-11e5-919d-1305bca8f49a.png)
![gmail probelm](https://cloud.githubusercontent.com/assets/13433124/9220357/a6a0ff96-40ff-11e5-8006-4aa3392ab5e4.png)

**Comment by Data66PF** [comment]
I'll confirm this but in the past, these sort of things were due to the mail program and not the script. At least that was how they used to be marked.
