### ISSUE TITLE
Create Setting Option Missing Button

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#337]
In V3 we usually to have a option to create new settings to user groups at admincp, however in V4 I couldnt identify this feature.

Using the direct URL is possible to reach this option in V4 throught yoursite.com/admincp/user/group/setting/

**Comment by Data66PF** [comment]
This setting is no longer available.

**Comment by Data66PF** [comment]
Reopened so we can disable the direct link as we've done for other removed settings.

**Comment by leandrotavaresrocha** [comment]
So if this option is no more avaliable what we do if we want to create a simple setting?

I used this feature several times to create areas where only admins can access.

**Comment by Data66PF** [comment]
Perhaps Ray will keep it. I think most things are being done in the apps that developers make.

**Comment by RaymondBenc** [comment]
v4 handles all settings via an apps JSON file. We will work a way so this can soon be added via the AdminCP soon.
