### ISSUE TITLE
htaccess Problem

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#340]
Hi, I used below mentioned code in my htaccess file to redirect all pages from non-www to www pages(to solve canonical error) . i put it just below the "Rewrite Base/"

# Redirect non-www to www:
RewriteCond %{HTTP_HOST} ^mysite.com [NC]
RewriteRule (.*) http://www.mysite.com/$1 [R=301,L]

It worked fine for this purpose but my site stopped communicating with database after this. I rechecked after removing the code then it start working fine , i tried to clear cache first then putting this code in htaccess but still same problem exist. my email password not working, not able to fetch any user in user browser page. static content coming fine but dynamic data is not coming there.
Please help ..!!!

**Comment by Data66PF** [comment]
Was that something we told you to add? Where did you get that info? This seems to not be the code we provide. If you need help with questions, please ask in community.phpfox.com or please purchase a bug review for someone to come help you with site issues. Contact hello@phpfox.com to purchase a bug review if you would like that.

**Comment by shakti7188** [comment]
Dont be so rude first of all.

Second , i posted it in community.phpfox.com first but no body replied. And i m not asking to solve my personal site bugs here, you just need to confirm that this bug can be reproduced to your side or not to confirm that it's not a bug in your given script . I've paid for that script. To get a full n fine working script is my right. It's your mistake that your script has so many bugs that if something goes wrong then our mind automatically says that it can be a bug.

Lastly, the code i mentioned in htaccess is a common code to remove site duplication(canonical ) error. if any site want to survive then it's very obious exercise whether it is a phpfox site or a wordpress press.

**Comment by Data66PF** [comment]
You read what I said wrong. I wasn't being rude. I was asking if we asked you to add that so I would know if this was something posted someplace from us or from someone else so I believe you thought I was saying something else.

**Comment by shakti7188** [comment]
problem still exist.... have u guys noticed it yet or not ?   Without this code too , my website is not identifying  login on a www url . for example - if i m logged in on  http://website.com  and then visit  http://www.website.com  then it doesnt identify me and ask to log in.  I can not check it on your website as u r using community as a subdomain.

**Comment by one44** [comment]
Can this not be fixed with a Cpanel redirect instead of htaccess

**Comment by shakti7188** [comment]
there is no redirect option in cpanel

**Comment by one44** [comment]
![2015-09-18 12_10_08-cpanel x - main](https://cloud.githubusercontent.com/assets/13656046/9957194/7170968a-5dfe-11e5-8d47-1cad1e34a2b8.jpg)

**Comment by shakti7188** [comment]
this is also not working good.  now it shows "index.php" in every page url and says that page doesn't exist.

Please  try yourself once and tell if it is working for you?

**Comment by shakti7188** [comment]
actually www redirecting is not a problem that works by htaccess too and by cpanel too. But the problem is that i m not able to log in on www version
