### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#341]
This happens sometimes after I get done viewing pictures or maybe someones profile.

![error](https://cloud.githubusercontent.com/assets/13330878/9240208/958ebb26-4131-11e5-90ca-8938f138a970.jpg)

**Comment by Data66PF** [comment]
Do you see the same thing on the PHPfox community, http://community.phpfox.com?

**Comment by Data66PF** [comment]
Ok I see this on my dev site. Mine is TypeError: $(...).val(...) is undefined

**Comment by RaymondBenc** [comment]
@Data66PF steps to confirm on your dev site?

**Comment by Data66PF** [comment]
Just log in, go to admincp, clear cache and sometimes it will show then. It is a random bug.

**Comment by RaymondBenc** [comment]
I still haven't been able to reproduce this issue. I have seen it once a few versions ago, but nothing after that. I'll continue to keep an eye on it.

**Comment by Data66PF** [comment]
This appears fixed in v4.0.10. If you see the issue again, please let us know.
