### ISSUE TITLE
Content Delivery Network settings not available

### ISSUE THREAD

**Issue by ckersey2** [moxi9/phpfox#342]
I just setup a rackspace CDN for my v3.8 site which I am upgrading to v4 soon. I have a development version of 4.0.5. There is no way for me to configure the CDN at all. I even went to Maintenance >> Find Missing Settings and it does not show the Content Delivery Network option at all.

**Comment by Data66PF** [comment]
There is an app for Amazon so it looks like you'll need an app for rackspace but I'll double check.

**Comment by RaymondBenc** [comment]
Currently CDN support for v4 was removed to allow 3rd party devs to create apps for other content delivery networks. An Amazon app was released to show how this can be done and for Rackspace this would require an app for v4. I can personally look into creating this app once I free up some time on my end.

**Comment by PhpFoxJohnJr** [comment]
Here we are 6 months later and no support for CDN when it use to be there.  Would like to at least store my images and video on a different hard drive on my server since SSD cost so much.
