### ISSUE TITLE
Can't Save CSS Changes

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#343]
Hello!

I made some changes at css of a theme at "CSS" tab however seems that the script dont save it.

This issue is happening at phpfox 4.0.5

**Comment by Jinkers** [comment]
Have you tried pressing ctrl+s ? I find this works for me.

**Comment by Data66PF** [comment]
I can't reproduce this issue. BTW, great tip for ctrl+s @Jinkers . 

Please be sure to always clear cache when making any changes and do a hard page refresh.
