### ISSUE TITLE
Advertise issue

### ISSUE THREAD

**Issue by mobicomfi** [moxi9/phpfox#345]
I have problem with ads. If i click to my ad (there are webpage URL), then it redirect me to manage ads, if i logged in, and put my ad to inactive mode. Same thing if visitor click to ad, it redirect to log in section and put ad to inactive mode. I use version 4.0.5

**Comment by Data66PF** [comment]
How many clicks did you enable for it?

**Comment by mobicomfi** [comment]
1000 clicks, but it dont count clicks, only impressions are counted

**Comment by Data66PF** [comment]
Please post the bug for it not counting clicks as well if you tested from a different IP than the one submitting the ad. I can't reproduce any problem with click ads. It takes me to the url in the ad. The ad is not disabled after.

**Comment by mobicomfi** [comment]
I logged in with another account and from mobile. same thing, i click to ad and it redirect to ad managment. And i check from computer from admin account, ad is inactive. My site is upgraded from 3.8, is it possible, that some setting disturbe it or something

**Comment by Data66PF** [comment]
You should only have ads now in block 3 on the site. Please check for that. Perhaps the ad system is showing ads in other spots where they don't belong now?

**Comment by mobicomfi** [comment]
ads are all in block 3, this is right.

**Comment by Data66PF** [comment]
Did you ensure to disable all v3 third party themes, modules and plugins as those would need updating for v4?

**Comment by mobicomfi** [comment]
no, im not sure

**Comment by Data66PF** [comment]
please disable them then. They don't work in v4.

**Comment by mobicomfi** [comment]
So, i uninstall all modules and my site is updated to 4.0.7, but still same problem.
