### ISSUE TITLE
Can't delete friends if you have a cover photo

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#347]
PF community and development site. V4.0.5. Default Neutron theme. Have some friends.

Load a cover photo.

Get annoyed with a friend and decide to delete them.

Go to Friends on your profile and try to click Manage Friends. It won't click.

Delete the cover photo and try again and now you can click and delete the friend.

**Comment by lupuspl** [comment]
It still doesn't work. I removed cover photo and I can manage friends but with it I can't.

**Comment by Data66PF** [comment]
The upgrade has not been released yet.
