### ISSUE TITLE
Blank page on installation

### ISSUE THREAD

**Issue by delixyr** [moxi9/phpfox#35]
I am getting blank page on installation. Installation went fine.
Unknown: open(/tmp/sess_xxxxxxxxxxxxxxx, O_RDWR) failed: Permission denied (13)

**Comment by RaymondBenc** [comment]
The product needs to have write access to the servers **/tmp/**, which is assigned in PHP. Do you have access to your server to grant write access to the **/tmp/** folder?

**Comment by delixyr** [comment]
This issue occurs only with dev distribution. Not with phpfox-dist-master. I followed all the steps. Ran composer. Activated keys. And then blank website. I have set 777 to /tmp folder via cpanel.

**Comment by delixyr** [comment]
I think this has to do with the changes made to how phpfox handle sessions post the phpfox-dist-master release ? That one handles sessions with no issues.
