### ISSUE TITLE
Profile pictures album issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#350]
Some users profile photo not showing in Profile Pictures album.
Like this usser: http://community.phpfox.com/photo/album/profile/421428/fb-1192498437434404/

**Comment by Data66PF** [comment]
Please search before posting. #276

**Comment by Ylmzef** [comment]
I mean in abums page. Check link please.

**Comment by Data66PF** [comment]
The issue relates to it being from fb as the other github shows. It is being addressed.

**Comment by Ylmzef** [comment]
This a bug than?

**Comment by Data66PF** [comment]
this is a duplicate of the other bug report but yes, in that one it is labeled a bug.

**Comment by Ylmzef** [comment]
Do you mean this #276 ?
it's completely different issue what i mean

**Comment by Data66PF** [comment]
if you look at the link you provided, it shows at the end fb- and then a number. FB for Facebook. The photos from facebook users are not coming over.

**Comment by Data66PF** [comment]
If you are speaking of the photo albums not showing, that is also a different bug you can check for as it was confirmed before too.

**Comment by Ylmzef** [comment]
No,
Check this user profile: http://community.phpfox.com/fb-1192498437434404/
You see preofile photo?
Click on profile photo and go to "Profile Pictures" album.
See you there any profile photo?

**Comment by Data66PF** [comment]
As I said it is a duplicate of the other bug for profile photo albums. Search this issue tracker for album. You will see the other bug.
