### ISSUE TITLE
Theme remove issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#352]
I removed Alizarin theme but its still showing in admincp as Pending Installs.
I removed default theme too but its not showing.

**Comment by Data66PF** [comment]
You shouldn't remove default theme. Even in v3 it wasn't a good idea to remove default theme.

**Comment by Ylmzef** [comment]
Im using "Legacy" theme now.
Default theme removed.
"Alizarin" still in "Pending Installs"
Please check in your end..

**Comment by Data66PF** [comment]
I'm not going to remove the default theme as it's not a good idea to remove a default theme. That could mess up my site for other things that rely still on default even when using a custom.

**Comment by Ylmzef** [comment]
And what about that?

**Comment by Data66PF** [comment]
I cannot reproduce this on v4.0.5. When I installed Wisteria, I then deleted it and cleared cache and it removed. Same for Alazarin.

**Comment by Ylmzef** [comment]
For me well. Its upgraded site from v3

![download 1](https://cloud.githubusercontent.com/assets/8562514/9310329/59c54286-450f-11e5-9c8b-c9cd78185b2c.png)

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
