### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by djeber** [moxi9/phpfox#353]
the rtl style is broken and i am trying to fix it but i dont know where to enter the css values for it and when i searched i found this file PF.Base/theme/frontend/default/style/default/css/rtl.css
is this is the correct one ?

**Comment by Data66PF** [comment]
This is more a question than a bug. Please post at community.phpfox.com when you have questions as the bug tracker needs to be just for bugs. I'll leave this open in case he has time to answer but right now, we are focused on bugs so you might get a faster answer at the community.
