### ISSUE TITLE
Subscribe issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#354]
I enabled subscribe.
Added a membership package and im buying this package but im still on same membership.

**Comment by Data66PF** [comment]
I can't reproduce this. I enabled subscriptions. I set up a subscription that goes to my Silver group and the failure is set to registered group. I log in as a user in the registered group and go purchase that new subscription. This user is automatically now moved to the Silver group.

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
