### ISSUE TITLE
like & Comment Overlap Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#356]
in small screen or when using Mobile device people who like this section overlap over comment section. pls check screenshot.this test done on PF community with Android Mobile.
![screenshot_2015-08-10-09-32-01](https://cloud.githubusercontent.com/assets/13433124/9268001/b795e226-4276-11e5-9ecb-8c08e5e0a2ec.png)

**Comment by SalmanKhan86** [comment]
@Data66PF @RaymondBenc pls give any solution for this.no reply for this thread.whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy???????????????????????????

**Comment by Data66PF** [comment]
tested with iPhone 5c. I can see an issue with the responsiveness here though not like the image shows. Still, it is having an issue.

**Comment by Jinkers** [comment]
I'm unable to find an occurrence of this issue. Got any links @SalmanKhan86 in regards to some?

**Comment by SalmanKhan86** [comment]
go to any person timeline.check post that's likes more than 4 or 5.tested in your smart phone.you will be able to find this issue as well.

**Comment by Jinkers** [comment]
Not the cleanest solution but I have added the following to my css. 
.js_feed_comment_border { overflow: overlay; } 
It stopped it shooting out of the elements box for me.

**Comment by SalmanKhan86** [comment]
i can't find overflow:overlay.it does't have overlay property.

**Comment by Jinkers** [comment]
Its not a default setting. Go to AdminCP->themes->your current theme->css tab. Add the code there and make sure you  save it. Sometimes you need to control+s for it to save. Also if you havent already, you should make a new flavour of your current theme and edit that  instead of the default. If you make a new flavour be sure to select is as current/default theme.

**Comment by SalmanKhan86** [comment]
i am waiting for PF community developer to solve this issue.
