### ISSUE TITLE
Profile Menu problem Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#357]
in small screen or when using Mobile device Timeline menu section items not in proper position pls check screenshot.this test done on PF community with Android Mobile.
![screenshot_2015-08-09-21-59-26](https://cloud.githubusercontent.com/assets/13433124/9268025/21705adc-4277-11e5-9470-e8fe51d01bde.png)
![screenshot_2015-08-09-22-04-38](https://cloud.githubusercontent.com/assets/13433124/9268029/29b3cc56-4277-11e5-9f53-c7c50b08475f.png)

**Comment by SalmanKhan86** [comment]
@Data66PF @RaymondBenc pls give any solution for this.no reply for this thread.whyyy??

**Comment by Data66PF** [comment]
Please stop tagging me for stuff. I don't get paid for this. I get to it when I can.

**Comment by SalmanKhan86** [comment]
ok sir np

**Comment by Data66PF** [comment]
I don't see a way to enable timeline for profiles. On a default profile view, as I can't enable timeline view, I can confirm on an iPhone 5c that the above issue exists.

**Comment by Data66PF** [comment]
I'm a woman, pink avatar :)

**Comment by SalmanKhan86** [comment]
oohh.thats by mistake.Thanks Mam
