### ISSUE TITLE
Pages search not worrking

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#359]
Pages search not working: http://community.phpfox.com/pages/

**Comment by aakash83** [comment]
yes it is not working.also the url of search page looks strange. if we do search 2 times with same query, this is how it looks .

first search : http://community.phpfox.com/pages?s=1&view=&search%5Bsearch%5D=test
2nd search : http://community.phpfox.com/pages?s=1&view=&s=1&view=&search%5Bsearch%5D=test&search%5Bsearch%5D=test

**Comment by Data66PF** [comment]
confirmed at the community using firefox on win 10

**Comment by Ylmzef** [comment]
Still not working on v4.0.6
Can't find any results.
