### ISSUE TITLE
Error in Neutron

### ISSUE THREAD

**Issue by vajaymenon** [moxi9/phpfox#36]
Hi,
I have traced a glitch/error in neutron trial when we post some thing on some one else wall lets say :ajay post on david's wall then it should be ajay >david but it shows ajay >john.. but actually i never communicated with john

so please check if you want screen shots of error do let me know and i will send the same to you. My email id is - vajaymenon@rediffmail.com

Ajay

**Comment by RaymondBenc** [comment]
Were you able to replicate this on our [Community](http://community.phpfox.com/)? I tested a few cases locally and wasn't able to reproduce the issue.
