### ISSUE TITLE
unable to activate a block

### ISSUE THREAD

**Issue by belleman** [moxi9/phpfox#362]
With a fresh V4.05 I'm unable to activate a block. 

OS windows 10, browser google

**Comment by belleman** [comment]
![ex1 fw](https://cloud.githubusercontent.com/assets/13818999/9293201/49843c72-43ef-11e5-9327-7190df5fcda0.png)

**Comment by Ylmzef** [comment]
Same issue!

**Comment by belleman** [comment]
It looks to be just happening with Google. I was able to activate blocks windows 10 and browser yahoo

**Comment by Ylmzef** [comment]
It's issue on chrome v44

**Comment by Data66PF** [comment]
Confirmed in chrome with win 10.
