### ISSUE TITLE
crate ad campaigns Missing From Ad Module

### ISSUE THREAD

**Issue by Viewsfx** [moxi9/phpfox#363]
crate ad campaigns table missing to put ad code
thats the cause their is no option to put ad code and select layout in ad module
ad module extactly same as phpfox 3.8 only installer has been change
some code missing ad module installer
so should be correct the code of install.php

**Comment by Data66PF** [comment]
Ad campaigns are not added via admin cp now like they used to be. There are only ad sponsorships in block position 3. For admin ads, just put them in a block as that is how google sort of ads are done now.
