### ISSUE TITLE
Photo section privacy issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#364]
I upgraded my site from v3 to v4.
After upgrade on photos section (/photo) i see old users photos still with admin account but i cant see new users photos.

**Comment by Data66PF** [comment]
This is due to V4 being friends only community with section item privacy by default. Get the free app I released for admin to view all content. http://store.phpfox.com/product/854/admin-view-all-items

**Comment by Ylmzef** [comment]
Im not friends with older user but i see still the photos?

**Comment by Data66PF** [comment]
Then do you mean that photos don't show on the site if they are newly loaded to the site?

**Comment by Ylmzef** [comment]
No. I see old users photos that comming from v3 before upgrade in photos section.
But i dont see new users photos after upgrade to v4.
Also im not friends with old users.

**Comment by Data66PF** [comment]
Do you see them if you use the free admin app I mentioned?

**Comment by Ylmzef** [comment]
No i dont use any app.

**Comment by Data66PF** [comment]
Then try the app as I mentioned to. It's free.

**Comment by Ylmzef** [comment]
That is not sollutions.
Please install v3 firs and make some user and upload photos.
Than upgrade to v4.
You can see the old users photos in photo section.

**Comment by Data66PF** [comment]
Are you saying it didn't work? It's a free app.

**Comment by Ylmzef** [comment]
No. Its nothing to do with this topic.

**Comment by Data66PF** [comment]
I created a 3.8 site and had some users. One of them, not friends with admin, loaded images. I then upgraded the site. I can see the images of that user so I cannot reproduce your issue.

**Comment by Ylmzef** [comment]
You see? but phpfox say "The only sections that are public are the forums and pages."
You need not see unfriends photos..
http://blog.phpfox.com/2015/08/12/making-your-admin-omnipotent/

**Comment by Data66PF** [comment]
It also says that with the free app, Admin can then see everything. It's a free app.

**Comment by Ylmzef** [comment]
Why are you still doing to promote yout app?
I say its not about with your app. I give example from phpfox blog post.
I dont installed your app but i see old users photos in photos section that not my friend.

**Comment by Data66PF** [comment]
I'm not promoting a paid app. I'm trying to help you see the content on your site. At any rate, I cannnot reproduce your issue.

**Comment by Ylmzef** [comment]
I can give you my site details for checking.
Than you can understand what i mean.

**Comment by Ylmzef** [comment]
I found some upgraded sites please check those you can see photos.:
http://www.vookster.com/index.php/photo/
https://speaklife.com/index.php/photo/
http://one44.net/photo/ (Adult)

**Comment by one44** [comment]
Not a techie but is this not a settings issue from V3 to V4 are they saved in same Db table?

**Comment by Ylmzef** [comment]
No all section comming with private except forums and pages.
This means you don't need see other users photos in photos section as admin account too..

**Comment by Ylmzef** [comment]
I see still unfriends users photos on photos section with admin account.
Upgraded site..

**Comment by Ylmzef** [comment]
Stil waiting for this..

**Comment by Ylmzef** [comment]
Im waiting for this please check it!

**Comment by Data66PF** [comment]
I am not sure of your issue. You say you can see non friends photos as an admin. This is how it works though. Are you able to see non friend stuff with a registered user? If not, then that's how it works. If you don't want to see content on the site as an admin, go to the user group settings and set to no the setting for can see private items posted on the site.

**Comment by Ylmzef** [comment]
Raymon Bench says: "The only sections that are public are the forums and pages." here: http://blog.phpfox.com/2015/08/12/making-your-admin-omnipotent/

Than photos section private too? So admins can't see unfriends photos under photos section?

**Comment by Ylmzef** [comment]
@Data66PF @RaymondBenc I'm still waiting for solution for this since 17 august

**Comment by Data66PF** [comment]
Admins need to be able to admin the site or there could be illegal content posted and an admin would not see it. However, if you don't want to see stuff as admin, please do as I suggested above and change the setting.

**Comment by Ylmzef** [comment]
Why Raymon Bench says than this?: "The only sections that are public are the forums and pages."

**Comment by Jinkers** [comment]
What Raymond said refers to general users. As a general user, the only sections that are public are the forums and pages if you have a friends only community activated. Otherwise, the general users only see things from their friends and what is posted in the forums and pages. Admins, as Data has already explain, need to see all to administer the site and if you decided to change this, it is at your own peril if things go beyond your TOS and/or Privacy Policies etc.
