### ISSUE TITLE
Can't delete messages

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#366]
I can't delete messages.

**Comment by Data66PF** [comment]
Threaded mail is not able to delete. it can go in an archive. http://scripttechs.com/article/362/phpfox-v4-hide-mail-as-threaded-doesn-039-t-delete/ that is how to do it.

**Comment by Ylmzef** [comment]
I should to tell my all users this?

**Comment by Data66PF** [comment]
Yes as that is how it is designed to work. You could try putting the threaded mail setting to false and see if that still works. I'm not sure that setting works now.

**Comment by Data66PF** [comment]
I'll confirm that there is no button for the user to at least click to go to their mail where they can manage the messages (put them in the archive). for now, clients could make a simple menu via the menu manager.

**Comment by RaymondBenc** [comment]
Next version will have an archive link that will toggle actions for each message allowing users to archive a message.

![image](https://cloud.githubusercontent.com/assets/6339284/9516033/20b859f8-4ca6-11e5-9054-888be7720a30.png)
