### ISSUE TITLE
Cannot import Language pack.

### ISSUE THREAD

**Issue by kengracing** [moxi9/phpfox#367]
Bug from https://github.com/moxi9/phpfox/issues/137

This bug remains.
No menu to import Language pack and when I click install, no response.

**Comment by Data66PF** [comment]
Are you not able to get one from the Apps listed in the Languages section?

**Comment by lupuspl** [comment]
I have my own lang pack and I can't to import it.
I don't want lang from Apps.
There should be import menu.

**Comment by piramidesoft** [comment]
4.0.7 and issue still present

**Comment by Data66PF** [comment]
confirmed that there is no way to manually add your own language pack

**Comment by h22mike** [comment]
Any updates on this issue?

**Comment by Data66PF** [comment]
I already marked it a bug. Please wait for a fix. Thank you.

**Comment by h22mike** [comment]
Does it really takes so long to fix issues? What if there is a bigger issue than that? Will it get fixed in a year?
