### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#369]
Setting to limit characters to show in blog not working???

**Comment by Data66PF** [comment]
I'll have to test this when I can access blogs. Recent update made an error on my live dev site for blogs so I can't test this as I can't access them atm.

**Comment by one44** [comment]
Has this been confirmed ?????

**Comment by shakti7188** [comment]
Hi One44, 
I am facing same problem.

**Comment by Data66PF** [comment]
I can confirm it at the community.

**Comment by shakti7188** [comment]
Hi Data66 ,
v4.0.8 has launched i hope u can test it now and get some solution for it .
thanks

**Comment by shakti7188** [comment]
hello guys, it's a very small issue and you haven't solved it yet. Not good.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
