### ISSUE TITLE
Pages claim button is missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#370]
Per http://community.phpfox.com/forum/thread/52457/claim-a-page-button-seems-to-be-missing/ .

V4.0.5. Set the user group permissions to be able to claim a page.

Set an admin to handle page claims. (there is a spot in the Pages settings in admincp to Manage Claims so we have that part).

Go front end as a user who has joined the page and there is no button to claim it. This is for front end Groups too. The Pages/Groups module. 

We need the link/button to claim a page.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-18 *

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-18*
