### ISSUE TITLE
Location issue on pages

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#371]
Can't set location when create page.

**Comment by Data66PF** [comment]
What do you mean? Pages don't have a country setting if you mean that. If you mean you are using the free http://store.phpfox.com/product/849/check-in-beta then that would not be for this issue tracker. If you previously had the check in setting enabled, please disable it as that is not supported now.

**Comment by Ylmzef** [comment]
![download 1](https://cloud.githubusercontent.com/assets/8562514/9358973/0a5ccb66-468f-11e5-914a-716c6ed21a93.png)

**Comment by Data66PF** [comment]
That's not part of V4 now. Did you use the new checkin app?

**Comment by Ylmzef** [comment]
No.

**Comment by Data66PF** [comment]
ok as mentioned, the old checkin no longer works, use the free app with updated code

**Comment by Ylmzef** [comment]
It's upgraded site i see still the location section on pages..

**Comment by Data66PF** [comment]
Please disable the old checkin setting, clear cache and see if that works for you for now. You might need to go in the database to disable the setting if it is not showing in your manage settings. That will at least solve this issue for you. Alternately, if you install the free app (all Licensed paid clients have access to free apps) you can use that and it might work in pages and resolve this for you for now.

**Comment by Ylmzef** [comment]
Disabled it but i see still in page settings.

**Comment by Data66PF** [comment]
Did you fully clear cache and clear browser cache?

**Comment by Ylmzef** [comment]
Yes.

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
