### ISSUE TITLE
Cover issue on page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#372]
Can't upload cover photo for pages.
I'm getting "Add some text to share." notice..

**Comment by Viewsfx** [comment]
there is no repositon option to adjust cover image on wall

**Comment by Data66PF** [comment]
Are you testing at the PHPfox community?

**Comment by Ylmzef** [comment]
No. on my site.

**Comment by Data66PF** [comment]
Try at the community and see if it does the same

**Comment by Ylmzef** [comment]
It's working on community.

**Comment by Data66PF** [comment]
tested on my site and it works there. make sure folder permissions are good.

**Comment by Ylmzef** [comment]
Forder permissions are good.
It's upgraded site please check on upgraded site.

**Comment by Data66PF** [comment]
tested now on upgraded site using v4.0.6 new release and no issues seen.

ensure all third party products (themes, language packs, add ons, plugins) were disabled as those are not for v4 until those developers make them for v4. Ensure you fully cleared cache. Enable debug to see if there are errors.

**Comment by Ylmzef** [comment]
You check it before.
All modules are disabled.
Also cache cleared.

**Comment by Data66PF** [comment]
Like I said, I just upgraded another site to test it and it works fine for me on my UPGRADED site that I just upgraded to test with.

**Comment by Ylmzef** [comment]
You can't reproduced it on 19 aug. But it's now fixed on v4.0.8
Thanks!
