### ISSUE TITLE
phpfox v4 ad image not show 4.05

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#373]
Dear we installed fresh v4.05  ad uploaded and work. but not show image in ad?

**Comment by Data66PF** [comment]
I cannot reproduce this on a front end created ad. Admin ads are made in blocks.

**Comment by Data66PF** [comment]
![ads show fine](https://cloud.githubusercontent.com/assets/6908282/9355445/4f427e80-4647-11e5-8eb7-6ed2c7de358d.png)

**Comment by todaylogin** [comment]
2 errors for picture upload in our fresh installation 

No. 1 .  ad image not successfully upload in ad and not available in folder /file/pic/ad/  no thing year empty 

No. 2 main user profile image not upload so much delay....    and we upload from admincp ans edit user and change image successfully 

If this is not bug please give me error hint?  we are running for company. hope you give us guide line

**Comment by Data66PF** [comment]
We allow one issue per report.

**Comment by muhammadnaeemahsan** [comment]
ok Be considered ad image upload error issue!

**Comment by muhammadnaeemahsan** [comment]
Thanks!  both issues are solved in PHPFOX v4.0.6
