### ISSUE TITLE
word wrap and break words for Messages Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#374]
when we compose a message in Android OS its show word wrap and break words
![screenshot_2015-08-10-09-54-10](https://cloud.githubusercontent.com/assets/13433124/9355914/c8045764-469a-11e5-9e21-afaf82450d04.png)

**Comment by SalmanKhan86** [comment]
any update on this

**Comment by SalmanKhan86** [comment]
any update on this.still no one reply here..

**Comment by AnthonyKing** [comment]
what theme are you using?

**Comment by SalmanKhan86** [comment]
Now in V4.0.8 its don't show any pop up box.no option to reply to it.and menu link is not working.i am testing it on PF Community website Android OS
![screenshot_2015-10-08-15-54-16](https://cloud.githubusercontent.com/assets/13433124/10365006/7d447dac-6ddd-11e5-9d1d-41649d3e8e6b.png)

**Comment by Jinkers** [comment]
Samsung s4 Chrome Browser

I can confirm the original issue. However it isn't just applied to messages. Anything that 'drops down' from a button isn't adapting to the screen size, resulting in scrolling to read it. The 'subscribe' under thread tools is another example.

As for the newest issue, which would be best suited to a new issue report, I can also confirm that it APPEARS to not show up. In fact it does, however it does so at a zoomed level. If you rotate phone to a landscape position, it is viewable again.

**Comment by Data66PF** [comment]
We only do one issue per report so we will only address the word wrap issue.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed 4.0.10
