### ISSUE TITLE
Register and login button Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#375]
when we open forget password in Android OS.then in upper header bar register and login can be toggled. 
![screenshot_2015-08-10-09-42-46](https://cloud.githubusercontent.com/assets/13433124/9356047/b46d2dec-469b-11e5-8134-8e4b45bce5c1.png)

**Comment by SalmanKhan86** [comment]
any update on this

**Comment by SalmanKhan86** [comment]
any update on this.still no one reply here...

**Comment by SalmanKhan86** [comment]
is this Help wanted from my side.tell me

**Comment by Jinkers** [comment]
The 'help wanted' tag means that they want other devs/github users to help confirm the problem at hand.

Minus some spacing that could be between the two words, I can toggle them to my hearts content with an issue.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-63 *
