### ISSUE TITLE
Not Refreshing When Changing To Pages And Back Home

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#379]
With both ver 4.0.5 and 4.0.6, when you change from Home to a Page or Group, the page does not refresh to allow posting... If you Post, it doesn't publish... The only way is to manually refresh and then it will Post... The same thing if you go from a Page back to Home, or any other Page or Forum... I've tried both IE 11 and Firefox 40... I don't use Chrome under any circumstances because it is a malware in itself... This has been an ongoing problem since v4 was released...

**Comment by SalmanKhan86** [comment]
its problem with both chrome and Mozilla not auto refresh news feed.

**Comment by SalmanKhan86** [comment]
any update on this.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/468 same issue. should be resolved when that fix is released
