### ISSUE TITLE
Profile info not completely visible in cover pic

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#380]
when we upload light color cover image then info under name is not completely visible.Any solution you can change its design.
![not visible](https://cloud.githubusercontent.com/assets/13433124/9379091/666a7e98-4744-11e5-99d9-498308bbc99d.png)

**Comment by ajay55555** [comment]
Same problem here

**Comment by Data66PF** [comment]
I'll confirm this though it is a simple css edit, perhaps he will adjust that font.

**Comment by one44** [comment]
Not sure how this can be fixed as a white font will show on a dark image but a dark font wont show on a dark image. May need to be placed in a block that is static color but this affects design.

**Comment by Jinkers** [comment]
@one44 A simple solution is to use a heavier font type or to increase the weight of the font. Sometimes a combination of both is required.

**Comment by one44** [comment]
I understand but if the image is basic black or white it will not work an all members cover pics ???//
