### ISSUE TITLE
App controllers not recognized for blocks

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#381]
Making an app with a Group as per the tutorial for making those. Each page has it's id as page_route_mygreatmod or page_route_mygreatmod_yay for example. 

Trying to make a block via old or new methods is not working as it is not recognizing the mygreatmod or mygreatmod.yay as the controller. Blocks work fine though on default PHPFox controllers such as core.index-member.

**Comment by RaymondBenc** [comment]
Does this functionality not work on PF >= 4.0.7? http://support.phpfox.com/apps/blocks/

**Comment by RaymondBenc** [comment]
I've added a new routine here: https://github.com/moxi9/phpfox/commit/9889e19e19ebcdc9ade251b80c7afc3625f1709f

This should assist in the issues related this topic.
