### ISSUE TITLE
Ad Module bug

### ISSUE THREAD

**Issue by Viewsfx** [moxi9/phpfox#382]
Hi 
i am premium User,
i got an error in ad module when i click manage ad sponsorship there is a bug or may be missing code
in bottom of sponsorship no options to Add a New ad

Ads
No ads have been created.
   Add a New Ad
this missing in pf v4.0.5 or v4.0.6

i am geting this issue after update my site from pf v4.0.4. 
this bug is continue in pf v4.0.6

whatever i replace ad module from backup

Its working properly.

So please check ad module and correct missing code in next release.

Thanks you
Allbing

**Comment by Data66PF** [comment]
Ads are not added in admincp like that now. You can ad a front end ad or you can make a block for an ad. There is no place to make the other ads other than these two methods. Via a block or via a front end ad.

**Comment by Data66PF** [comment]
Closing as this is how it is designed. You either ad an ad via front end ad link or you make a block in admincp for the ad.
