### ISSUE TITLE
Can't open themes or apps from admin panel

### ISSUE THREAD

**Issue by warrisdeepsingh** [moxi9/phpfox#383]
When u go to Apps or Themes its shows all but opening any app or theme leads to 

The page you are looking for cannot be found.

www.xxxx.xx/admincp/theme/undefined&open=https%3A%2F%2Fstore.phpfox.us%2Fproduct%2F859%2Fandromeda

and opening http://www.xxx.xxx/admincp/store/?load=themes
results blank

**Comment by Data66PF** [comment]
What version are you testing? Did you fully clear cache if you upgraded to v4.0.6 and also do all of the steps mentioned for upgrading here, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/

**Comment by belleman** [comment]
I have this issue as well. I followed steps provided by script techs

**Comment by warrisdeepsingh** [comment]
Yeah i cleared the catch but still the same issue

i updated from 4.04 tp 4.06

**Comment by Data66PF** [comment]
Confirmed and a fix is coming soon.
