### ISSUE TITLE
settings to show new member registeration

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#384]
register block on front page missing.

**Comment by Data66PF** [comment]
Please state your version and what theme you are testing. I cannot reproduce this with v4.0.6 and default neutron theme at the community.

**Comment by one44** [comment]
Using 4.o.6 and wisteria

**Comment by Data66PF** [comment]
![wisteriareg](https://cloud.githubusercontent.com/assets/6908282/9407745/38a54b32-47da-11e5-8953-c93a78256d85.png)

I deleted the old wisteria and imported the new one and for me it works fine in v4.0.7

**Comment by one44** [comment]
Could only fix it by doing a reload of a backup that was working a few days before and then upgrading again.
