### ISSUE TITLE
Users search issue on admincp

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#385]
Users search not working on admincp.

**Comment by Data66PF** [comment]
Please be more specific and tell us what version you are testing, and how it is not working.

**Comment by Ylmzef** [comment]
v4.0.6
Search by gender or search by a word its shwoing not all results just 2.

**Comment by one44** [comment]
Same issue since 4.0.3  e mail search shows results but gives a blank page when you click on page 2,3, or last.

**Comment by Data66PF** [comment]
I can't reproduce this at the PF community running 4.0.7

**Comment by Ylmzef** [comment]
Not frontpage in admincp.

**Comment by Ylmzef** [comment]
I found the issue "State/Province" comming already selected same as my profile for me.

**Comment by Data66PF** [comment]
I tested in AdminCP at the PF community when I tested just so you know as I'm admin there.

**Comment by Ylmzef** [comment]
Please edit your profiile and select state/province for your account.
Than try again.

**Comment by Ylmzef** [comment]
It's still issue.
If you have state/province on your profile, it's search users same state/province on admincp users seacrh page!

**Comment by Data66PF** [comment]
Do you mean that if I put a state in my profile (which I have in my test site) that it will only search for users in that same state in admincp search? It won't look for other users at all?

**Comment by one44** [comment]
I think what he means is that if you enter it only shows page one. I have a similar issue when I enter a mail generic like gmail.com. It used to show all members using that generic mail but now only shows page one. As this is in admin and used as an admin function I ignored it as it is not critical for members useage.

**Comment by Ylmzef** [comment]
@Data66PF yes if you set any state for your profile than click "View More Search Options" from users search form on admincp. Your profile state comming as selected there on form.

**Comment by Data66PF** [comment]
Thanks for the extra steps to reproduce it. I can reproduce it at the community and at my development live site.
