### ISSUE TITLE
Can't create page

### ISSUE THREAD

**Issue by lupuspl** [moxi9/phpfox#386]
When I try to save a new page there is an error:
"The page you are looking for cannot be found."

**Comment by Data66PF** [comment]
Please ensure you are using the latest release, right now that would be 4.0.7. Please detail the bug better. Is it a front end Pages/Group? Is it a back end Admin Created page?

**Comment by Data66PF** [comment]
Tested on my dev site running 4.0.7. I went to AdminCP and created a static page there. It had no errors and created the page fine.

**Comment by lupuspl** [comment]
In ACP I try to create page.
When I try to save a new page there is an error:
"The page you are looking for cannot be found."
V4.0.7

**Comment by lupuspl** [comment]
It's ok now.

**Comment by manny12** [comment]
Can't create privacy terms page. When tried creating one got a "The page you are looking for cannot be found" response.

**Comment by Data66PF** [comment]
Did you clear cache? Are you using v4.0.7?
