### ISSUE TITLE
[Git Commands/SSH] Downloads Files but doesn't 'Update'.

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#387]
When using git to update to the new version, it successfully updates the files, however, when I go to the upgrade script page, it results in just hanging for an extra second or two before loading the default feed of activity of the site. I've checked the websites version and it still says it is 4.0.5. Any ideas why it is not updating?

**Comment by Jinkers** [comment]
Tried with updates to 4.0.6, 4.0.7 and now to the recent 4.0.8. Still same issue as above.

**Comment by phpfoxdev** [comment]
Hi, can you detail on how you updated? We just want to make sure we do understand the case. Few screenshots are appreciated.

**Comment by Jinkers** [comment]
I don't have screenshots available as I've had to upgrade by just a standard file upload (only way to get it to upgrade at the moment). Aside from that, my process is logging in site via SSH, navigating to the folder of which PHPFox is installed, and then executing 'git pull https://github.com/moxi9/phpfox-dist.git'. This proceeds to display the logs of all the items being downloaded/'updated' with a successful message at the end. I go to update the site, but it just redirects me to the standard logged in page of activity feed as if the new files didn't exist. I try the same command listed above again to confirm they have been downloaded, and I get a 'Already up to date' message.

**Comment by phpfoxdev** [comment]
- Please check your current branch or tag and you have pulled. May you pull old version.
- Does your account (ssh account) have permission to modify or create new files.
- Please compare const VERSION on file /PF.Base/include/library/phpfox/phpfox/phpfox.class.php before and after you pulled.

**Comment by Jinkers** [comment]
I'll give that all a go when I get a chance to get a test site up. I'll update this once I have.
