### ISSUE TITLE
Facebook Login Re-installation problem in V4.0.7

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#389]
Hi,

I uninstalled this app (Facebook Login) because when I'm trying to log in "in PHPFox ver 4.0.7" it is not working it just stop in the middle of the process so I decided to uninstall it.

Then I reinstalled it, but I cannot see it on my installed apps list. But when I check it on "My Downloads" list, it is there. picture attached.
![fblogin installation error](https://cloud.githubusercontent.com/assets/13417524/9413196/23c461ee-4839-11e5-807c-ea1dd4d644ea.jpg)

When I try to install it again it is asking for App ID or Github url.
![app id of github](https://cloud.githubusercontent.com/assets/13417524/9413204/3328ccf6-4839-11e5-9488-a136e3553ecf.jpg)

**Comment by Data66PF** [comment]
Issues with apps are to be posted in the app issue as you posted, https://github.com/moxi9/phpfox-facebook/issues/3 . This tracker is only for the core.
