### ISSUE TITLE
PF Community, Can't upload profile photo

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#39]
Trying to upload a profile photo. Was able to before, can't now. The loading icon keeps spinning and never uploads the profile photo.

Win 8.1 pro
Firefox latest and Chrome latest. Error in console is

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Now I have a blank profile photo
http://community.phpfox.com/ScriptTechs/

This previously worked using the exact same photo on a different account http://community.phpfox.com/profile-data66/ .

**Comment by RaymondBenc** [comment]
Thanks for the report. Issue should now be resolved.

**Comment by Data66PF** [comment]
Yes, it works now. Thanks. :)

**Comment by RaymondBenc** [comment]
Awesome!
