### ISSUE TITLE
Responsive theme issues: recent discussions block

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#390]
Recent discussions block can't scrollable on phpfox community.
Tested with iphone 6 plus.

![11909728_881298788573792_259815665_n](https://cloud.githubusercontent.com/assets/8562514/9421324/6ff5f93c-4871-11e5-9969-09c2f056ec25.jpg)

**Comment by Data66PF** [comment]
confirmed on iPhone 5C
