### ISSUE TITLE
Responsive theme issues: block 1 & 2 on members page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#391]
On members page side button for users search not clickable.
Tested with iphone 6 plus.

![11911932_881298795240458_1554805371_n](https://cloud.githubusercontent.com/assets/8562514/9421335/a7b0e666-4871-11e5-9224-8d904a556ba8.jpg)

**Comment by Data66PF** [comment]
confirmed iPhone 5C

**Comment by AnthonyKing** [comment]
try to use base 5 theme, unless the theme you are using is responsive

**Comment by Data66PF** [comment]
Base5 is not for v4. It is for v3. You've been giving a lot of advice in various bugs but all of it has been v3 advice. V4 is different. Note that v4 theme is responsive by default.
