### ISSUE TITLE
Responsive theme issues: categories buttons

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#392]
Categories button can't clickable.
Tested with iphone 6 plus.

![11944964_881298798573791_1066228018_n](https://cloud.githubusercontent.com/assets/8562514/9421347/d2482b6e-4871-11e5-95ff-2416dff0608f.jpg)

**Comment by Data66PF** [comment]
confirmed with marketplace for a test on iPhone 5C
