### ISSUE TITLE
Responsive theme issues: Profiles without profile photo

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#393]
Issue for name abbreviation for user without profile photo.
Tested with iphone 6 plus.

![11909610_881298791907125_1428748005_n](https://cloud.githubusercontent.com/assets/8562514/9421363/29185ec8-4872-11e5-9edc-bbc6074c8286.jpg)

**Comment by Data66PF** [comment]
confirmed iPHone 5c but there was another bug like this that I can't find now so this might be a duplicate.

**Comment by Data66PF** [comment]
Fixed in 4.1.0
