### ISSUE TITLE
Responsive theme issues: register & login button

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#394]
Register & login button showing complex.
Tested with iphone 6 plus.

![11923070_881298801907124_1181972859_n](https://cloud.githubusercontent.com/assets/8562514/9421369/5947b198-4872-11e5-9d40-4dbffae69de1.jpg)

**Comment by voarsh** [comment]
:+1: 
Yes, I've noticed a few issues with mobiles. E.G. Messaging is unusable on phones.

**Comment by Data66PF** [comment]
confirmed when logged out if clicking something a guest can't do, it shows as the screenshot on an iPhone 5c.

**Comment by Ylmzef** [comment]
But it's still not marked as bug..

**Comment by Data66PF** [comment]
I had but I guess it didn't save.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-65 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.

**Comment by Data66PF** [comment]
Sorry about that. The core developers were supposed to have done that.
