### ISSUE TITLE
Responsive theme issues: signup block

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#395]
Signup block on home page for visitors showing fixed and can't scrollable.
Tested with iphone 6 plus.

![11940697_881298805240457_519306133_n](https://cloud.githubusercontent.com/assets/8562514/9421385/96ac875c-4872-11e5-8fed-1a370f07efd3.jpg)

**Comment by Data66PF** [comment]
For all of your issues you just submitted, please state what device you used to test, OS version and browser.

**Comment by Data66PF** [comment]
I tested on my iPhone5c, default browser and, as your shot shows, the full sign up form shows up. I am not seeing the issue.

**Comment by Ylmzef** [comment]
![download 1](https://cloud.githubusercontent.com/assets/8562514/9787985/3e9bb9f2-57c7-11e5-90d9-ae3dbe685913.png)

You need click on this button.

**Comment by Data66PF** [comment]
I can't reproduce any issue as, once the page fully loads, I get a scroll bar on the right in my iPhone 5C. Maybe someone else can test with an iPhone 6.

**Comment by Ylmzef** [comment]
Still issue on v4.0.8.

**Comment by SalmanKhan86** [comment]
In Android OS its working fine tested on PF Community

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
