### ISSUE TITLE
Style issue in AdminCP Notes

### ISSUE THREAD

**Issue by MightyBranch** [moxi9/phpfox#396]
In the AdminCP Notes block, the **textarea** element has more padding on the left than on the right, causing it to look misaligned to the right side.

Tested using the latest versions of Google Chrome, Firefox, and Safari.

Phpfox version: 4.0.7(build 1)

**Comment by Data66PF** [comment]
I don't see an issue with this and that block doesn't impact any front end area that users would see. I did test and didn't see any problem. On mine, it looks uniform and even.
