### ISSUE TITLE
Unable to see all members

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#397]
As Admin, I should be able to see, or search for members when I click on the Members tab... I, nor other members are able to do that... All we see is Recommended Members and Recently Active...

**Comment by Data66PF** [comment]
Please use the search box on the right to view all members. Note that the setting is VERY heavy and is the reason V4 has been made as it has. Please do not post feature requests in the issue tracker.

**Comment by TrueAmericans** [comment]
There is no search box... Just the users I described above...

**Comment by Data66PF** [comment]
http://community.phpfox.com/user/browse/ when you go there, do you see the search box? If not, what browser and OS are you checking it with? I can see a search box with win 10 on ff latest.
