### ISSUE TITLE
Friends Online Doesn't Show

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#398]
No matter what I do, the Friends Online doesn't show and it used to with older versions... Everything is original in the Block for it, and is active, but no one shows, no matter how many there is... What can be done to fix this? I've tried all I know for it...

**Comment by Data66PF** [comment]
This is not part of the default script. This bug tracker is only for current default. Please ask customization questions in the community.

**Comment by TrueAmericans** [comment]
Then why is it defaultly included in the script?

**Comment by Data66PF** [comment]
Sorry I thought you meant something else. It is showing on my default install when I log in with a friend. It shows in the PF community. Are you having it on core.index-member with the default script?

**Comment by one44** [comment]
What are steps to set up this block

**Comment by one44** [comment]
I have same problem have it set as per a clean dev site installation but nothing showing.

**Comment by Data66PF** [comment]
After further testing, I found that if the old setting for Online Friends Via ajax, admincp/setting/edit/?module-id=friend found there friend.load_friends_online_ajax, is set to Yes, it will hide this block as I don't believe this setting is used so it will always show as not loaded.

Marked a bug 4.0.7
