### ISSUE TITLE
Google Recaptcha needs Update

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#40]
For V3.8 and for V4, we need an update to the Google Recaptcha as Google sent notices to everyone now to update to use the latest api, https://developers.google.com/recaptcha/intro .

Since 3.8 is still being sold, and since I see recaptcha still in v4, can we please get this updated for both versions? This is one of those things that we really, really need. Pretty please with a cherry on top? :)

**Comment by KStenvall** [comment]
Agreed. Many depend on Google Recaptcha as part of their spam protection. Please update 3.8 and 4.0.

**Comment by Data66PF** [comment]
A fix is here http://scripttechs.com/forum/thread/1864/new-recaptcha-product/view_13877/ but it will overwrite source files and does not work for comments if that setting is enabled. Works fine for registration and blogs (if the user setting for that is enabled)

**Comment by RaymondBenc** [comment]
reCAPTCHA will not be a part of v4 base. Free app released instead...
http://store.phpfox.com/product/782/recaptcha

We will update for v3.
