### ISSUE TITLE
Viewing Forum Posts

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#400]
When you click on a forum to view, part of the "Share" and "Thread Tools" is appearing in the forum post you're trying to view in Firefox... Other problems in IE... Don't know who made the themes other than the default, but they need to work the forum displays over...

**Comment by Data66PF** [comment]
State which theme you are testing please. Note that this bug tracker is only for the core product and default theme that came with it. We will need to make a place for the extra themes if this is for that.

**Comment by TrueAmericans** [comment]
Happening with ALL themes, and also, it won't let me remove or delete any of the posts, including any of my own...

**Comment by Data66PF** [comment]
I don't see the issue at the community viewing with win 10 on ff browser. My screen resolution is 1920 x 1080

**Comment by Data66PF** [comment]
I've still been checking this and I don't see any issue with this. I can delete posts as my user group is set to be able to delete posts. Are you still experiencing an issue?
