### ISSUE TITLE
Unable to Install any Apps in V4.0.7

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#401]
Tried to install apps in V4.0.7 but its not showing on the installed apps list.
![installed apps](https://cloud.githubusercontent.com/assets/13417524/9423635/9684c722-48d5-11e5-9179-3c31059ce591.jpg)

But when I check it on "My Downloads" list, it is there. picture attached.
![apps on downloads](https://cloud.githubusercontent.com/assets/13417524/9423648/ef4f6f88-48d5-11e5-9fca-7eba0d4df5bd.jpg)

When I try to install it again it is asking for App ID or Github url.
![app id of github](https://cloud.githubusercontent.com/assets/13417524/9423653/25337b44-48d6-11e5-84bb-0022cdc92a97.jpg)

**Comment by Ylmzef** [comment]
Try enabling CurlSSL on your server.

**Comment by Data66PF** [comment]
http://community.phpfox.com/forum/thread/52585/v4-apps-and-themes-suphp-and-other-issues/ please see if the tips in that thread help

**Comment by Data66PF** [comment]
Is this still an issue for you?

**Comment by Verdz** [comment]
YES,  I still have this problem.

**Comment by Verdz** [comment]
![unable to install apps](https://cloud.githubusercontent.com/assets/13417524/9853368/e9b22096-5b0b-11e5-8da0-97a86f7950a3.jpg)

This is what happening when I'm trying to install any apps. The AdminCP menu becomes double.

**Comment by Data66PF** [comment]
Perhaps you've made some changes to the site or are using something from V3? I cannot reproduce this issue.

**Comment by one44** [comment]
I had this problem and had to do a clean install from an old backup to fix it

**Comment by Verdz** [comment]
It's after the upgrade to V.0.7 I don't have V3 before.Sent from my Mobile-------- Original Message --------Subject: Re: [phpfox] Unable to Install any Apps in V4.0.7 (#401)From: Data66 To: moxi9/phpfox CC: Verdz Perhaps you've made some changes to the site or are using something from V3? I cannot reproduce this issue.

**Comment by sarfsiddiqui** [comment]
I was facing same problem at 4.0.7. Now after I installed 4.0.8 after clicking on 'Get It' on the app page, page loading starts that keeps on loading and never ends. 
![pic2](https://cloud.githubusercontent.com/assets/14808929/10053056/c0da753c-624b-11e5-8aa0-c0cd432307b2.PNG)
