### ISSUE TITLE
Video feed not opening for guest user

### ISSUE THREAD

**Issue by Gaac** [moxi9/phpfox#403]
After upgrading from 4.0.6 to 4.0.7, when opening the Video feed (/videos), or any video by guest (not logged in) user, an information occurs:

This resource requires an HTTP USER_ID header.

**Comment by Data66PF** [comment]
Video issues are posted in the video app issue tracker, https://github.com/moxi9/phpfox-videofeed

**Comment by Gaac** [comment]
Erasing lines 117-119 in /PF.Src/Core/Api.php temporarily solved problem.
