### ISSUE TITLE
[Custom Fields] Location selection

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#404]
In previous version of v4 (I believe it was around 4.0.3 and 4.0.4) I was able to create the new field and then select that field as block and have it placed where I required it to be. However, in 4.0.7, when creating a custom field it is automatically adding it in a fixed position (user's profile page)

Adding the custom field through the block system into a position is yielding two of those fields. There is no option to disable the default location of the newly created custom field, or to select its location.

Tested on live site and local install running.

**Comment by Data66PF** [comment]
This is working for me to get it on the profile.index page but, as the OP mentioned, it shows on both profile.index and profile.info though in block manager, the block only now shows where I moved it, to profile.index. Will confirm.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-97 *
