### ISSUE TITLE
Creating DB tables on apps instaltion.

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#405]
Hi,

What is the right syntax to create tables when an app is installed? 
In this tutorial explains that we can have an installer.php file on the root of the app:
http://support.phpfox.com/apps/install-uninstall-upgrades/

On V3 I used this to create tables in the DB:

$this->database()->query("CREATE TABLE IF NOT EXISTS `".Phpfox::getT('ces_online')."` (
  `user` int(9) NOT NULL,
  `url` varchar(500) NOT NULL,
  `activity` int(10) NOT NULL,
  `login` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;");

So will be the right systax this one here, inside the installer?
```php
$installer = new Core\App\Installer();
$installer->onInstall(function() use ($installer) {
$installer->db->query("CREATE TABLE IF NOT EXISTS `".Phpfox::getT('ces_online')."` (
  `user` int(9) NOT NULL,
  `url` varchar(500) NOT NULL,
  `activity` int(10) NOT NULL,
  `login` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;");
});
```
Thanks

**Comment by RaymondBenc** [comment]
Yes, that syntax looks correct. Have you ran into any problems with creating a table?
