### ISSUE TITLE
Friend request issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#406]
I have 2 accounts.
I sended friend request from my one to other account.
I denied request (/friend/accept/) from other account but when i surf to user profile on other sended account i see still "Pending Friend Request" and can't send again.

**Comment by Data66PF** [comment]
Did you click the x in the lower right corner of the profile pic when viewing the pending and click to remove it?

**Comment by Data66PF** [comment]
I'll confirm this as a bug since it should remove the pending request.

**Comment by Ylmzef** [comment]
Still issue on v4.0.9..
 i think it's critical bug for big sites because i have lot of "Pending Friend Request" data on database..

**Comment by t2nttn** [comment]
This is a setting on V3 with title: "Hide denied requests from pending list" discription: "If enabled, friend requests that were denied will be hidden from the Pending Friend Requests list.". Default value is false. It's mean after deny frriend request, it still display "Pending Friend Request".
On V4, still use this setting with default value is False. But in AdminCP, we can found this setting again.

**Comment by Data66PF** [comment]
Unfortunately, the setting is not found in the V4 AdminCP settings. The Friends settings are all removed.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-98 *
