### ISSUE TITLE
Sign Up text can't translatable

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#408]
Sign Up text on home page can't translatable on admincp.

**Comment by Data66PF** [comment]
I can't reproduce this. I changed the two Sign Up phrases to Sign Up Now and it shows that in the registration block.

**Comment by Ylmzef** [comment]
This issue 23 days old too like my other reports.
And it's fixed 12 days ago https://github.com/moxi9/phpfox/issues/200 :smile:
