### ISSUE TITLE
Problem filtering users in administration

### ISSUE THREAD

**Issue by d1a8lo24** [moxi9/phpfox#409]
When filtering users in the administration section and sorting by joined everything works fine but the pager to go from page 1 to page 2 is not writing the URL variables correctly.

When you hit search the URL has this on the variables (not showing the full URL as it has a lot of variables): 
http://localhost/index.php/admincp/user/browse/?page=2&search[sort]=u.joined

But when you click to show page 2 the URL has the following:
http://localhost/index.php/admincp/user/browse/?page=2&search[sort]=ujoined

Now is missing the period after the U to make it u.joined.

Just wanted to let you guys know this to fix it. 

Running the latest developers release v407.

**Comment by Data66PF** [comment]
confirmed
