### ISSUE TITLE
On the browse members section the "recently active" is not the recently active.

### ISSUE THREAD

**Issue by d1a8lo24** [moxi9/phpfox#410]
Its actually showing the newest members not the recently active members, the database query is sorting by joined descending and is using the getNewUsers() function.

**Comment by Data66PF** [comment]
confirmed

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-99 *
