### ISSUE TITLE
New htaccess rules for FastCGI not working

### ISSUE THREAD

**Issue by d1a8lo24** [moxi9/phpfox#411]
Quick test on a godaddy's virtual server running centos 6, with FastCGI as the php handler.

implemented the latest htaccess code for the short URL and any page except the ones that don't required short URLS just show a input undefined.

So a blank page with text.
At the same time when installing under FastCGI nothing works ones the application is installed. to fix this you need to enable on the php.ini variable "fix_pathinfo" to true or 1

**Comment by Data66PF** [comment]
Need other folks to test this one to confirm.

**Comment by Data66PF** [comment]
Another client posted that it is working with 4.0.9 for them. I use fcgi on mine and it works on my servers. I don't use godaddy as they've never been good for Fox sites.

**Comment by Data66PF** [comment]
Please test with 4.1.1 and please make a new ticket if you find issues still.
