### ISSUE TITLE
Verification mail issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#415]
I clicked verification link and mail email adres verfired.
But when i click again verification link its sending all time new verification mail..

**Comment by d1a8lo24** [comment]
2 things to check first on php mail()
1 make sure that your host has enable mail(). Many hosts in the past year have disable this.
2 check the port some may use 2626, 25 and others.

Do a quick php script to send an email using php mail() function if it works fine, then there is something going on with PHPMailer maybe is configure wrong.

I never use main but using smtp can couse problems if you're not using the right ports or the right authorization mechanism like either TLS or SSL etc..

**Comment by Data66PF** [comment]
Do you mean that you already verified the email and then decided to click it again to verify it?

**Comment by Ylmzef** [comment]
When i click vertification link on mail it's sending everytime new mail for already verified account.

**Comment by Data66PF** [comment]
Why would you click to verify it again if it is already verified?

**Comment by Ylmzef** [comment]
Because it's a bug, when you click it again the page should showing the account already verified but it's showing invalid verfication code..

**Comment by AnthonyKing** [comment]
try to sign up again, and make sure the mail settings are entered correctly

**Comment by Ylmzef** [comment]
@Data66PF i'm still waiting answer for this issue..

**Comment by Data66PF** [comment]
I still don't see why anyone would click it again after they are already verified. I think it is working as designed but left it open for him to see.

**Comment by AnthonyKing** [comment]
maybe u tried to edit the auto respond,

**Comment by Ylmzef** [comment]
It's sended every time mail it can be used for bad things..

**Comment by AnthonyKing** [comment]
i'll take a screenshot of my mail setting, maybe that might help you

**Comment by Data66PF** [comment]
Please post feature requests in the forum for now as we need to clear up the script bugs before checking for features and the feature request section is where we will check once we are at that point. Thank you.

**Comment by Ylmzef** [comment]
Is this feature requests for you?

**Comment by Data66PF** [comment]
For now this is as it is working how it was designed to work and it not something a majority of the people would do.

**Comment by Ylmzef** [comment]
Our server ip blacklisted because of this issue.
This not a feature requests or somethings else. This is a critical bug.

**Comment by Data66PF** [comment]
You should be using something like mandrill or sendgrid as your ip can get blacklisted due to false spam complaints too. As for this, I don't see how that causes your site to get blacklisted if someone clicks more than once on the verify email. They are the ones choosing to click to send the email.

**Comment by Ylmzef** [comment]
Alternatives are not always the best option.
I have stronge server and i'm not in favor of using alternatives.
And yes I have some competitors those ones choosing to click to send the email.
In short, they are doing misbuse this issue..

**Comment by Ylmzef** [comment]
@Data66PF @RaymondBenc I'm still waiting for solution for this since 25 august

**Comment by Data66PF** [comment]
This is a closed issue as it would be a feature request. Please don't tag us for closed issues.
