### ISSUE TITLE
Notifications issue for friends request

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#416]
Im online on site but if anyone sended me friend requests i cant get any notifications for that.
When i click "Requests" than i can see it.

**Comment by Jinkers** [comment]
Working perfectly fine for me on PF Community, local dev, live dev and live community.

**Comment by Ylmzef** [comment]
I tested on community too but there not working.

**Comment by Data66PF** [comment]
I can't reproduce this as I get new requests almost every day. What browser and OS are you testing with?

**Comment by Ylmzef** [comment]
Windows 10 with chrome 45.
It's not instant..

**Comment by Jinkers** [comment]
I have same specs as Ylmzef however it is working fine for me on all 3 of my sites, live, live dev and local dev.

**Comment by Ylmzef** [comment]
Why you closed the issue?
It's still not instant on v4.0.8

**Comment by Data66PF** [comment]
It is working for us in the way it was designed. I think maybe you want it to work like fb?

**Comment by Ylmzef** [comment]
I waited 3 minute or so than it's appeared as notification.
So it's not instant.
I have fast & powerful dedicated server owned only one site.
