### ISSUE TITLE
Friends aprove and denied button issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#417]
On page /friend/accept/
Default theme
Chrome
Windows 10

![download](https://cloud.githubusercontent.com/assets/8562514/9456858/049e7d12-4add-11e5-8317-630e9234cfe1.png)

**Comment by Data66PF** [comment]
confirmed

**Comment by AnthonyKing** [comment]
have you previously tried to edit the theme

**Comment by Data66PF** [comment]
We don't need to try to edit the theme. I've confirmed the issue as a bug already.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
