### ISSUE TITLE
Deledet member issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#418]
I deleted a user on admincp but its still showing on /user/browse/ page.

**Comment by Jinkers** [comment]
Have you cleared you site cache and browser cache?

**Comment by Ylmzef** [comment]
Yes.

**Comment by Jinkers** [comment]
Test on my live and local dev sites. Works fine. Can you still access their profile or is it just still being rendered in that one location?

**Comment by Ylmzef** [comment]
Can't access to profile but i see profile photo in the list.

**Comment by Data66PF** [comment]
Which list are they in?

**Comment by Ylmzef** [comment]
Url: /user/browse/
Recently Active

**Comment by one44** [comment]
It seems a lot of the issues are on sites upgraded from V3 IS IT A DB TABLE ISSUE?

**Comment by Data66PF** [comment]
nothing changed in the database so I don't think it's a db issue. I'll test on an upgraded site later.

**Comment by Data66PF** [comment]
I cannot reproduce this on an upgraded site. They only show if I don't clear cache. After clearing cache, they don't show.
