### ISSUE TITLE
Music genres issue

### ISSUE THREAD

**Issue by Gaac** [moxi9/phpfox#420]
When you have large number of genres (I had 165), music page and music tab in user's profile load forever and can not be loaded when clicked. When manually entering the address, they load.

Erasing whole music_genre table in database solves problem.

**Comment by Data66PF** [comment]
wow 165. I don't think it was intended to be that large. Perhaps the server couldn't handle that large a load when calling for all of the genres. Is it working fine now with a more manageable number?

**Comment by Gaac** [comment]
Hello,
yes, 165 ;) I am running small radiostation next to music portal based on
phpFox, and radiostation uses Radionomy's services, that have sooo much
genres :)

After reducing some (as christmas, politics or news-talk), 165 left.

Let me send you mysql dump with music genre table - for testing purposes,
and about me - I erased whole table leaving no genre at all; finding it
easier for users :)

I can add proper mp3s to proper genre later; and users.. they are lazy and
became lazier with time... ;) our time's case.

Anyway please let me know if/when you'd solve that bug, maybe i would think
of SoundCloud alike project.. that would use as large genre database in
fact.

Best,
David
