### ISSUE TITLE
Unable to find v3 plugins in v4

### ISSUE THREAD

**Issue by abhimanyubind** [moxi9/phpfox#421]
I don't see my plugins which I created in v3 module. Where I can see my added plugins in phpfox v4.

**Comment by Data66PF** [comment]
V3 plugins and modules don't work in V4. I'll confirm that there is no Plugin option for clients but I think it's designed this way now.

**Comment by abhimanyubind** [comment]
I am using v3 module in v4 and it is working properly however my concern was only related to plugin. How can I use a hook ?

**Comment by Data66PF** [comment]
Please wait for an update from the developer as I marked it a bug already.

**Comment by muhammadnaeemahsan** [comment]
Sure! Data66PF

**Comment by RaymondBenc** [comment]
You will have to enable Techie mode in order to create hooks. If you are using a premium install you can enable Techie mode by opening the file **PF.Base/file/settings/server.sett.php** then create a new line with the following code...
```php
define('PHPFOX_IS_TECHIE', true);
```

Log into your AdminCP and to your left in the main nav you will find a **Techie** menu.

**Comment by SalmanKhan86** [comment]
not working in v 4.0.8.i define('PHPFOX_IS_TECHIE', true); in  PF.Base/file/settings/server.sett.php.but nothing happen.

**Comment by Data66PF** [comment]
Did you click the Techie menu you see when enabling Techie?

**Comment by SalmanKhan86** [comment]
Techie menu link is not showing after set define('PHPFOX_IS_TECHIE', true); in server.sett.php

**Comment by Data66PF** [comment]
Let me go test.

**Comment by Data66PF** [comment]
maybe I'll ask monday if there is a way for clients to enable plugins

**Comment by SalmanKhan86** [comment]
ok Post here if any option available for it.

**Comment by PhpFoxJohnJr** [comment]
Just tried this and it does not work for me either....
