### ISSUE TITLE
Page like issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#423]
When i like a page, cant get any confirmation about like just hidding the like button.

**Comment by one44** [comment]
Page should do a refresh I did report this in another issue.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/468 duplicate

**Comment by Ylmzef** [comment]
This ticket 15 days old and it's 7 days.
I think you need check first old tickets.

**Comment by Data66PF** [comment]
I'm checking as I get to them thanks. Trying to do the best I can as I volunteer.
