### ISSUE TITLE
Pages categories issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#424]
Pages categories page not showing pages.
http://community.phpfox.com/pages/category/1/entertainment/
http://community.phpfox.com/pages/category/2/brand-or-product/
http://community.phpfox.com/pages/category/3/group-or-community/
http://community.phpfox.com/pages/category/4/local-business-or-place/
.....

I think its showing just liked pages.

**Comment by Data66PF** [comment]
This is how it is designed in a friends only community.

**Comment by Ylmzef** [comment]
But others showing on pages home page?
http://community.phpfox.com/pages/

**Comment by Data66PF** [comment]
Yes they show on the home page. I'll confirm that we need to hide them from the pages.index for friends only since they hide in the categories as that setting does.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-95 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.
