### ISSUE TITLE
Profile page Pages block issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#425]
Pages block showing all liked pages:
![download 3](https://cloud.githubusercontent.com/assets/8562514/9485286/91e78dd2-4bb7-11e5-923c-8bb530397d38.png)

And not showing totaal liked pages like Friends block:
![download 4](https://cloud.githubusercontent.com/assets/8562514/9485295/a4ac3210-4bb7-11e5-801b-63facd17ad6b.png)

**Comment by Data66PF** [comment]
confirmed as an enhancement but also will mark bug as this long block, if we have a lot of liked/joined pages/groups is too long aesthetically.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed 4.0.10

**Comment by Ylmzef** [comment]
It's now fixed but now when i click on the numbers it's closing  the block.

**Comment by one44** [comment]
confirmed

**Comment by Data66PF** [comment]
For closed bugs, if you find another issue, please open a new issue and reference the original bug for us please.
