### ISSUE TITLE
Invisible link and button on Privacy Settings page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#426]
![download 5](https://cloud.githubusercontent.com/assets/8562514/9485329/3188cb62-4bb8-11e5-873f-d55fc5c8a835.png)

**Comment by Data66PF** [comment]
I don't see this on the community. What browser and os are you using? Is it a desktop or mobile device? What screen resolution if a desktop?

**Comment by Ylmzef** [comment]
The screenshot from phpfox community. It's not visible you need select the area.
Chrome 45
Windows 10

**Comment by Data66PF** [comment]
This is why I asked your screen resolution as I don't see that arrow on my Win 10, Chrome latest, screen resolution of 1920 x 1080

**Comment by Ylmzef** [comment]
For me 1920x1080 but it's nothing to do with screen resolution.
It's due to html codes.

```<a href="http://community.phpfox.com/darbeg/" class="page_section_menu_link">View Your Profile</a>```

**Comment by Data66PF** [comment]
Ok it took some moving around of the mouse but I finally found the hidden arrow that you show. Thanks for the report. 

To reproduce, please hover the mouse at the top right of the privacy settings block and go up a little until you see that arrow show up. Tested in PF community.

**Comment by AnthonyKing** [comment]
try to edit your theme

**Comment by Data66PF** [comment]
No. I've confirmed this as a bug. I am part of the staff. This will be fixed as a bug thanks.

**Comment by RaymondBenc** [comment]
Can this still be reproduced on the community? The latest less files from our default theme has fixed this for me locally and on the community.

**Comment by Data66PF** [comment]
Yes, it is still at the community as : 
To reproduce, please hover the mouse at the top right of the privacy settings block and go up a little until you see that arrow show up. Tested in PF community.

**Comment by neil96** [comment]
Fixed in v4.0.10
