### ISSUE TITLE
Activity points

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#427]
Where show activity points show for user account or profile?  (v4 phpfox)

**Comment by Data66PF** [comment]
This doesn't show in the site now. I'll mark as confirmed though because we have settings for activity point conversion, purchase with points, and purchase points so we need a way to show the points still.

**Comment by muhammadnaeemahsan** [comment]
how to we see now? and when is active this feature ?

**Comment by Data66PF** [comment]
Wait for the developer to fix it please. They will post when it is fixed.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-93 *

For Clients: Activity points will now show on the profile:
![activity points](https://cloud.githubusercontent.com/assets/6908282/11120580/c246d8d0-891e-11e5-837d-b6086fcd0dc4.jpg)
