### ISSUE TITLE
Facebook Connect not working

### ISSUE THREAD

**Issue by QuillLittlefeather** [moxi9/phpfox#428]
I tried to login using facebook and i receive this error

We already have an account created with us with the same email you have on Facebook. Would you like to sync both accounts?

I have even tried this with a new facebook account using a new email address same issue

**Comment by Data66PF** [comment]
This issue tracker is only for the core. Please post issues with apps in that app's github issue tracker. https://github.com/moxi9/phpfox-facebook/issues
