### ISSUE TITLE
Authorize User Via Session Error

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#430]
PF v4.0.7. Live dev site. 

AdminCP >> Settings >> Security

enable Auth User Via Session. 

Clear Cache. 

Have debug enabled.

POOF. You cannot log in now. You get the following. You must now go in the db and disable that setting and manually clear cache.

Whoops\Exception\ErrorException thrown with message "Undefined variable: _SESSION"

Stacktrace:
#15 Whoops\Exception\ErrorException in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/session/storage/session.class.php:85
#14 Whoops\Run:handleError in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/session/storage/session.class.php:85
#13 Phpfox_Session_Storage_Session:remove in /home/mysite/public_html/mysite/PF.Base/module/user/include/service/auth.class.php:522
#12 User_Service_Auth:logout in /home/mysite/public_html/mysite/PF.Base/module/user/include/service/auth.class.php:153
#11 User_Service_Auth:__construct in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:248
#10 Phpfox:getObject in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:857
#9 Phpfox_Module:getService in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:474
#8 Phpfox:getService in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:550
#7 Phpfox:getUserId in /home/mysite/public_html/mysite/PF.Src/Core/Controller.php:17
#6 Core\Controller:__construct in /home/mysite/public_html/mysite/PF.Src/Core/Route/Group.php:10
#5 Core\Route\Group:__construct in /home/mysite/public_html/mysite/PF.Site/Apps/PHPfox_Base/start.php:201
#4 require_once in /home/mysite/public_html/mysite/PF.Src/Core/App.php:74
#3 Core\App:__construct in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/plugin/plugin.class.php:91
#2 Phpfox_Plugin:set in /home/mysite/public_html/mysite/PF.Base/include/init.inc.php:177
#1 require in /home/mysite/public_html/mysite/PF.Base/start.php:34
#0 require in /home/mysite/public_html/mysite/index.php:7

**Comment by RaymondBenc** [comment]
Was this the setting "**Authenticate Users via Database Session Log**"? I tried to replicate, no dice.

**Comment by Data66PF** [comment]
Yes. It is on the main dev and local devs.

**Comment by Data66PF** [comment]
I'll have to download this latest git again and see if it will fix the issues I have but my sites are all the released 4.0.7 current release.
