### ISSUE TITLE
Can't make an Ajax call

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#431]
Hi,

I'm creating an app that need Ajax Calls, but can't make it happen.

This are the steps I followed:

On autoload.js I have added this code:
```
$Ready(function() {
	$('.active-all').click(function() {
		var t = $(this);
		$.ajax({
			url: t.data('url'),
			success: function(e) {
				$('#show-all').html(e);
			}
		});
		return false;
	});
});
```
Then inside start.php I have added this one. But when I click on the link the call is not made.
```
new Core\Block('core.index-member', 1, function(Core\Block $block) {

$html =  '<div id="show-all">';
$html .= '<a href="#" data-url="{{ url(\'/ajax-custom\') }}" class="active-all">Click Me</a>';
$html .= '</div>';

$block->title(_p('Most Active Members'));
$block->content($html);

});

new Core\Route('/ajax-custom', function(Core\Controller $controller) {
	echo '<div class="message">Howdy! I am an AJAX response.</div>';
});
```

Thanks

**Comment by cespiritual** [comment]
I have solved this using the old method of creating blocks, calling for the external html file that show the template. With the new method I can't make ajax to work.

Thanks

**Comment by RaymondBenc** [comment]
Everything in the first example looked good, just a minor change needed.

```php
$html .= '<a href="#" data-url="' . $block->url->make('/ajax-custom') . '" class="active-all">Click Me</a>';
```

The **data-url** was using the HTML version of creating a URL. With this new line, it worked for me.
