### ISSUE TITLE
Subscribed membership package issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#432]
I have subscribed members, purchased with Subscribe module.
But there no information block about their membership package and end of package time or so things.

**Comment by Data66PF** [comment]
They are not able to see it at yoursite.com/subscribe/list/ ?

**Comment by Ylmzef** [comment]
There listed only order info.
I mean membership package info like as currently membership or expiration date of package etc.

**Comment by Ylmzef** [comment]
@Data66PF i'm still waiting answer for this issue..

**Comment by Data66PF** [comment]
It has never shown the end time though. It shows in their subscriptions what they bought but has never had extra details.

**Comment by one44** [comment]
Not using this but when I did I seem to remember it showed which package like Normal, Silver Gold etc which then by knowing which package gave indication of month, year etc that that package applied to.

**Comment by Ylmzef** [comment]
Than clients can't know the expiration date?

**Comment by Data66PF** [comment]
On the v3 page that shows the users subscription, it only shows this:
Subscriptions
Purchase ID#:
1
Membership:
Gold
Status:
Active
Price:
$5.00 one time and then 5 monthly

There is no date showing so the user still doesn't know when it expires.

However, in the themes that showed the activity points and membership detail in the welcome block, it shows this:
Order #1 (Gold)
September 27, 2015
That still doesn't show when it expires or for how long the Gold plan should run but it does show the purchase date.

I'll confirm it to at least put the date back in there and a way to see them (link someplace)

**Comment by RaymondBenc** [comment]
I fixed an issue with the image not showing, however as for the date expiring, how is this set? Its a subscription, it ends when the user cancel the payment from PayPal.

**Comment by Data66PF** [comment]
On a set subscription such as one month, one year, etc, it doesn't show the end date. Recurring doesn't need to show an end date like you said. But a one month or whatever would need to show when the subscription started or when it ends for the user to know.

**Comment by Ylmzef** [comment]
When do you want fix this?

**Comment by Ylmzef** [comment]
@neil96 @phpfoxdev @Vivian-phpFox @RaymondBenc @robert9592  can you fix this in v4.2.0 please?

**Comment by Data66PF** [comment]
Once more, please do NOT tag everyone

**Comment by neil96** [comment]
Fixed on V4.2.1
