### ISSUE TITLE
Events issue with End time.

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#433]
Under events when you create an event you are asked to put a start time but no where does it ask for an end time. on the original events in V3 you were able to enter such information.

**Comment by one44** [comment]
Yes this is an important problem as some events are over 1 or two days etc.

**Comment by Data66PF** [comment]
please search before posting. duplicate of #256

**Comment by html5ravi** [comment]
Also i want to add some extra field under sub category for ex: Sports --> Badminton, here i want add a field called "entry fee", how to add this in under sub category?

**Comment by Data66PF** [comment]
@html5ravi please post questions at the community http://community.phpfox.com as this area is not for questions.
