### ISSUE TITLE
I wanna make Feeds to be shown to all users not only friends.

### ISSUE THREAD

**Issue by zaioxer** [moxi9/phpfox#434]
(PHPFOX Developer version 4.0.7)
I wanna make the feeds to be shown to all users, not only friends , So when any user makes poll , everyone can see his poll not only his friends.
How Can I figure this out please?

Please Help me.
Thanks in advance.

**Comment by one44** [comment]
Change in adminPC setting site settings I believe.

**Comment by zaioxer** [comment]
@one44 Can you be more specific please?

**Comment by one44** [comment]
1 go into adminpc 
2 click settings
3 click site settings
4 find friend only yes/no and change to no

**Comment by Jinkers** [comment]
Note that questions are to be asked in the PHPFox Community as this trackers is for bugs only in relation to the core product. Community at http://community.phpfox.com

**Comment by zaioxer** [comment]
Solved
By going to /index.php/admincp/setting/edit/?group-id=general
And Switching "Off" (Friends Only Community).
