### ISSUE TITLE
short URLs not working

### ISSUE THREAD

**Issue by vookster** [moxi9/phpfox#436]
The server is running nginx. The account "vookster"  is using latest phpfox v4

We are unable to enable the short url from admin and htaccess file

http://www.vookster.com/index.php/satyavathi/setting/url/
If we set 1 instead of 2 on the file: /home/vookster/public_html/PF.Base/file/settings/server.sett.php, then short URLs will work, but images will not work. If we revert it, the images will work and short URLs wont work. We have tried this many times, but no luck 

The .htaccess used for the account vookster is given below:-

===========================================
root@hosted-by [/home/vookster/public_html]# cat .htaccess
# START PHPfox Rewrite
<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f

    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
        RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
        RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
        RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2

        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d

        RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite
===========================================

Kindly guide us to resolve the issue. 

Thanking You.

**Comment by Ylmzef** [comment]
Try updating counters on admincp.

**Comment by vookster** [comment]
Already added the .htaccess rule and tested still the same issue.

**Comment by muhammadnaeemahsan** [comment]
its really problem v4.0.5 to v4.0.7 i also facing

**Comment by vookster** [comment]
Please give us quick solution the site down at this time.

**Comment by Ylmzef** [comment]
It's not same .htaccess rule as you mentioned at first post.
Please check it again.

**Comment by vookster** [comment]
The same rules already used in .htaccess file for the domain "vookster.com", still the same issue. You can refer the .htaccess file. Kindly let us know the exact rewrite rules that should work on ngnix

===========================================
# START PHPfox Rewrite
<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f

    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
        RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
        RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
        RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2


        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d

        RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite
========================================

As we have already gone through the link https://github.com/moxi9/phpfox/issues/132,  the Short URL in the AdminCP is designed for Apache mod_rewrite. That specific rewrite will not work on Nginx.Kindly let us know the rewrite rules work on Ngnix

**Comment by Data66PF** [comment]
issue #376
