### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#439]
There is a very big issue with index page. this page shows us 1 background image and sign up window and login bar and not show other thing.
But when load page index it load ads image and other things that relevant to other pages. it increase loading time and size. you can see this >> load index http://community.phpfox.com/ and save as on you computer and see folder images and files or http://tools.pingdom.com/...

**Comment by RaymondBenc** [comment]
This is more theme related, as the default theme hides other blocks in order to focus on the registration of the site. The blocks are controlled by Admins in the AdminCP and via Apps.

**Comment by muhammadnaeemahsan** [comment]
how to we set?
