### ISSUE TITLE
Forum only shows 5 replies to threads

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#44]
On PF community thread replies don't all show up. This one, for example, http://community.phpfox.com/forum/thread/51902/https-issue/ , should show 9 replies but it only shows 5 and there is no "view previous" or "view all" that I can find. You can scroll through the various threads that show more than 5 replies to find more examples.

**Comment by RaymondBenc** [comment]
Fixed locally. We will push fixes to the community tomorrow.
