### ISSUE TITLE
Friends Profile page 

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#440]
When we open friends profile page.
ads url not show proper in v4.0.7
![ad error](https://cloud.githubusercontent.com/assets/12130785/9560529/aafe6dea-4e32-11e5-9ec6-2efeed8ac9fb.png)

**Comment by Data66PF** [comment]
Did you test at the phpfox community? http://community.phpfox.com . I don't see an issue with it there.
