### ISSUE TITLE
Page pic (avatar)

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#441]
Seems this image cannot be changed or updated??????
![2015-08-28 09_49_48-south africa adult social networking community bdsm swingers looking for adu](https://cloud.githubusercontent.com/assets/13656046/9560978/8a8ec0aa-4e32-11e5-85c1-df0e922e5667.jpg)

**Comment by Data66PF** [comment]
Did you test at the phpfox community? http://community.phpfox.com .

**Comment by one44** [comment]
It seems like the block is not square as an Image 300x 300 or 350 x 350 leaves a small white line underneath.

**Comment by one44** [comment]
Ok found how to change image but white line remains on phpfox forum as well as in above image.

**Comment by one44** [comment]
the white line is still an issue even in community site.

**Comment by Data66PF** [comment]
I think that is by design to add a border in case there are dark images on light bg or vice verse.

**Comment by one44** [comment]
Borders should be on image as I do not see anywhere to add or not add borders and if that is the case it should be round the whole image not just at bottom.
