### ISSUE TITLE
Realy upgrade from v3 to v4

### ISSUE THREAD

**Issue by CimborNet** [moxi9/phpfox#442]
I'm serious.
Somebody can write a complete step by step instructions for updating the live site from version 3 to version 4.

What I mean. In the process of updating the site there are always some problems. Now with the release of version 4.0.7 to eliminate a lot of problems, but at the end of the update site appears button "View your site" and nothing happens. Clicking this button update starts from the beginning. And the frontend of site remains closed for users and for the administration. Cache cleaned. Apache restarted. Cache dir clean too. Memcache clened. Server full restart.

So I have some questions:
Step 1. 
On the live site I have the following directories in root directory:
file/
include/
module/
static/
theme/
etc...
I unzip master.zip file into my desktop.
Upload 3 dir (PF.Base PF.Site PF.Src) and 1 file (index.php) to root directory in my site and rewrite index.php file.
Right?

As a result, in my root directory of the site has the following folders: 
PF.Base/
PF.Site/
PF.Src/
file/
include/
module/
static/
theme/
etc...
Right?

Step2:
Then make "chmod 0777 PF.Base PF.Site"
Right?
Or I need make "chmod -R 0777 PF.Base PF.Site" for all subdir and file for this 2 folders?

Step3: 
Go to the http://mysite.com/index.php?phpfox-upgrade=true 
and start upgrade. Enter ID and KEY then see upgrade process...

When the update is finished at the bottom of the page there is a button to view the site. By clicking on this link, nothing happens! ((

As a result, in the PF.Base die I have a copy of the root directory site: file, include, module etc... Why?
Which of the folder after the upgrade, becoming the main: "PF.Base/file/pic/" or "file/pic" ?
What to do with URL shortcuts? If I turn on the REWRITE mechanism I lose all pictures. And only I copy all from directory "file" to "PF.Base/file" site displays pictures and other files (music, etc.).
Why?

PLEASE! Give my step by step instrution for upgrade from v3 to v4.

**Comment by muhammadnaeemahsan** [comment]
Have any 3rd party module using in v3?

**Comment by CimborNet** [comment]
No. Just official. no heve 3rd party modules. default theme. default settings. no more.

**Comment by Data66PF** [comment]
This is only for bugs. please post questions at the community http://community.phpfox.com
