### ISSUE TITLE
Unable to create menu in an app

### ISSUE THREAD

**Issue by abhimanyubind** [moxi9/phpfox#443]
I wanted to create a sub menu in my app but was unable see it in my app even after clearing the cache. Following is my app.json:

{
    "id": "Demo",
    "name": "My Demo App",
    "version": 1,
    "menu": {
    	"name": "Sub Menu1",
    	"url": "/submenu1",
    	"icon": "submenu"
    }
}

Please advise.

**Comment by Data66PF** [comment]
Please ask questions in the community. This is only for bugs
