### ISSUE TITLE
What are the differences between Developer Version and Premium Version

### ISSUE THREAD

**Issue by zaioxer** [moxi9/phpfox#444]
Hello Guys , 
I want to know what are the differences between Developer Version(Free) and Premium Version(Paid).

I mean that Can I use Developer version instead of buying premium version on my site?
If yes , then what are the differences between them ? Why do we pay $348 if Developer version if for Free?

Please Answer me ,

Thanks.

**Comment by Data66PF** [comment]
this is only for bugs. please ask questions at the community http://community.phpfox.com
