### ISSUE TITLE
Profile photo remove issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#446]
One of site user upload adult profile photo.
I removed it from users photos section on profile but profile photo still same..

And other photos still on server like as:
file/pic/user/2015/08/25e076dcbe7a5aae096df3a93293caa0_50.jpg
file/pic/user/2015/08/25e076dcbe7a5aae096df3a93293caa0_100.jpg
file/pic/user/2015/08/25e076dcbe7a5aae096df3a93293caa0_200.jpg
file/pic/user/2015/08/25e076dcbe7a5aae096df3a93293caa0_300.jpg
file/pic/user/2015/08/25e076dcbe7a5aae096df3a93293caa0_400.jpg

**Comment by Data66PF** [comment]
Did you clear cache?

**Comment by Ylmzef** [comment]
Yes, like as said photos still under file folder.
Cache nothing to do with it.

**Comment by voarsh** [comment]
Jeeze. I thought phpFox sorted these issues in V 4.
A two year old V3 site of mine had delete record photos on server, feeds belonging to OTHER users, although it belonged to SOMEONE else. Basically, the system had too many IDs and it was very buggy with old sites.

If V4 turns out to be JUST a makeover, I'll be annoyed.

**Comment by Data66PF** [comment]
Did you go in admincp and edit the user there and upload a photo you want them to use for now? That would replace the original photo. As for deleting originals, it should delete from the server when you upload the new one in admincp.

**Comment by Ylmzef** [comment]
No i do it on profile page removed on photos section.

**Comment by Data66PF** [comment]
Then do it how I mentioned as that will upload one to replace it.

**Comment by Ylmzef** [comment]
But i don't want to change photo.
I want remove it because it's adult picture.

**Comment by one44** [comment]
This was an issue in V3 as well as wwhen members changed avatars the old avatars were retained and just took up server space.

**Comment by voarsh** [comment]
Yes.
I believe that still happens now.
I can't get PROOF just this minute, but I might also add that from an admin perspective I can only change a users profile picture, I cannot remove it. (Convenience)
I can upload a new one and delete it in their album, but I am pretty sure a thumbnail sort of image remains. (That is if photos are removed properly as well)


Kind regards,
Reese Jenner

**Comment by Data66PF** [comment]
I have tested again. The proper way, and the only way, to get the profile pic to remove from the site AND the server (which works fine in V3 too as I use V3 on my live sites and tested there)

1. Go to admincp
2. Find the user whose pic you want to change.
3. click to edit the user
4. Click Change This Photo where you see their profile pic
5. Load a different photo for it
6. Clear cache

This removes if from the site and server. If you want a different process, please post a feature request when that section is open in the community.

**Comment by Ylmzef** [comment]
Again, i want to "remove" it not "change".
The process replace the photo only, why i change user's photo or with what?

**Comment by voarsh** [comment]
Do you mean Data, that through AdminCP, when 'changing' a user's picture in AdminCP, it deleted previous one? (Even though their photo remains in their "Profile Picture" album under their account......
Date: Fri, 18 Sep 2015 05:17:57 -0700

**Comment by Data66PF** [comment]
For me, when I do it the way it was designed to be done (if an admin wants to change a user's profile pic) then it works fine after a cache clear. There is no other way to do it by default product. It does delete from the server (v3 and v4) as I tested and also as I've seen on my own live sites (V3).

**Comment by Data66PF** [comment]
It seems like you want more than the script is designed to do.

If you have a user image that you don't like, then logically, you would want to remove and replace it. It seems illogical to only want to delete it from the server but still let the user use it. Replacing an image that is not allowed, in the default way, removes it from the server AND replaces the user image. For me, on my sites, I simply load a default image I made for just such an occasion and I inform the user that I changed their image as the original was not appropriate.

**Comment by one44** [comment]
Data have you checked the file directory as all the images are there. In my upgrade I found all the old profile duplicated images in the old file directory and had to manually clear them.

**Comment by Data66PF** [comment]
Yes I did check. They are deleted in my live sites and in my test sites. The images deleted from 3.8 and from v4 when I tested. Note that my v4 is a live dev site on a server and 5 local test sites. All of them deleted when I do it via the admincp method mentioned. For my v3.8 sites, same thing. If I do it the way mentioned, it deletes.

**Comment by Ylmzef** [comment]
Okay than i'm going replacing user photo with my own sefie photo nice :+1:
