### ISSUE TITLE
The word "Topics" is misaligned after publishing a blog

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#449]
After a blog is published the word "Topics" is too far to the left when displaying in the feed. I am sure it is a simple fix. Thanks and good job on this release!

**Comment by Data66PF** [comment]
Did you test at the phpfox community? http://community.phpfox.com . Screenshots are always helpful.

**Comment by Scot74** [comment]
Here is an image...
![capture2](https://cloud.githubusercontent.com/assets/14036909/9621102/05ee07d0-50e8-11e5-8d91-ccbb6b511bb5.PNG)

**Comment by Scot74** [comment]
Well...

**Comment by Scot74** [comment]
What does the addition of an "enhancement" label mean?

**Comment by Data66PF** [comment]
It means this is not a critical issue, it is a design issue.

**Comment by Scot74** [comment]
I totally agree.

**Comment by Data66PF** [comment]
I can't see this in our current version. Are you able to reproduce it at our demo https://v4.phpfox.com ?

**Comment by neil96** [comment]
This is very old issue. Feature topic changed it to hash tag. We have two solution for this issue.
- Add back feature topic (actually topic is tag). But we already have hash tag.
- Close this issue.

**Comment by Data66PF** [comment]
I think adding back tags is a good idea as v3 had both hashtags or normal tags to choose from. Most scripts use tags separately from hashtags though. In the future, we should look at improving this so clients can use both (for blogs and forum threads) as it's better for searching if we have actual tags in those areas at least. :)

**Comment by neil96** [comment]
The feature topic don't support any more as comment at #1064

**Comment by Data66PF** [comment]
We need to keep tags. Those of us that use tags need them for our sites. We can't use v4 without tags.

**Comment by robert9592** [comment]
The setting for choosing use hashtags or tag will be bring back in v4.3.0
