### ISSUE TITLE
Gravatar overlaps the typing prior to hitting enter

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#452]
I noticed this occurs when typing in the comment field once there is a second line and prior to hitting enter. Once enter is pressed, it displays fine. I noticed it occurring when commenting on a blog.

**Comment by Data66PF** [comment]
Did you test at the phpfox community? http://community.phpfox.com . Screenshots are always helpful.

**Comment by one44** [comment]
Same issue on my site

**Comment by Scot74** [comment]
Here is an image...
![capture](https://cloud.githubusercontent.com/assets/14036909/9621062/85d8c24c-50e7-11e5-8778-d849ca74d272.PNG)

**Comment by Scot74** [comment]
Well...?

**Comment by Data66PF** [comment]
This is marked a bug. It is a minor cosmetic fix but should be addressed.

**Comment by Scot74** [comment]
Thanks

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in 4.0.10 *staff note YPFOXNEUTRON-46 *
