### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#453]
When using the whats up to place a link in the wall if there is no pic a blank space. Needs to be able to place a pic if no pic loaded like facebook.

![2015-08-31 05_35_27-bdsm south africa uk usa london ny durban gauteng free adult dating](https://cloud.githubusercontent.com/assets/13656046/9571745/12c48f38-4fa3-11e5-9f81-5948b19ad019.jpg)

**Comment by Data66PF** [comment]
No matter what I do, I can't reproduce this on my upgraded test site. I copy and paste the link in the status share and after I hit to share it, it shares to the wall but doesn't show a blank space like your image, it only shows that before I share it.

**Comment by one44** [comment]
I think it does this when the link is to a page without an image

**Comment by Data66PF** [comment]
I'll try some more but like I mentioned, if the site doesn't pull an image, it only shows that empty block before I submit it. After I submit it, if the image is empty, it moves over to the left and that block is not there.

**Comment by Data66PF** [comment]
I tested with your link and that particular link is sending a blank white box as the image.

<img alt="" src="https://s0.wp.com/i/blank.jpg">

Have you tried another link that doesn't grab an image and seen the same issue? Note that if you use developer browser console and check the image path, if they are sending a blank white box as their image then that is what is going to show up.

**Comment by one44** [comment]
ok i see the problem
