### ISSUE TITLE
comments on pages

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#454]
Adding comments on pages is faulty it does not expand to show comment just one two lines..

**Comment by Data66PF** [comment]
Please provide a screen shot of what you mean.

**Comment by one44** [comment]
![2015-09-05 11_41_41-jump list for adobe photoshop cs6 64 bit](https://cloud.githubusercontent.com/assets/13656046/9698729/3c11f410-53c3-11e5-84f6-95f59f5f3132.jpg)
![2015-09-05 11_42_04-jump list for adobe photoshop cs6 64 bit](https://cloud.githubusercontent.com/assets/13656046/9698730/40d58e8a-53c3-11e5-9b12-acac70f28d73.jpg)

**Comment by Data66PF** [comment]
I don't see any issue. It has a scroll on the right that lets you scroll up and down to see what you've typed before you submit the comment.

**Comment by one44** [comment]
Yes but it only shows two lines when a long entry is made it is difficult to check and edit.

**Comment by Data66PF** [comment]
Please post feature requests in the forum for now as we need to clear up the script bugs before checking for features and the feature request section is where we will check once we are at that point. Thank you.
