### ISSUE TITLE
Issue with theme_template_body__end hook

### ISSUE THREAD

**Issue by abhimanyubind** [moxi9/phpfox#456]
The hook theme_template_body__end does not work as expected. In earlier version it used to add the code added in the hook to the site as well as in the administration area. Now it adds the code only in the administration area. Please look into this.

**Comment by Data66PF** [comment]
What are you trying to do? Did you follow the new tutorials for how to work with themes?

**Comment by abhimanyubind** [comment]
I want a hook that adds a script and css tag in the head which should be accessible on all the pages.
