### ISSUE TITLE
Photo Thumbnails counter update issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#457]
I did not change anything but im getting following error when im trying update Update Photo Thumbnails counter:

Exception thrown with message "imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Premature end of JPEG file
"

Stacktrace:
#17 Exception in /home/xxxxxx/public_html/PF.Base/start.php:134
#16 Whoops\Exception\ErrorException in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/image/library/gd.class.php:219
#15 Whoops\Run:handleError in <#unknown>:0
#14 imagecreatefromjpeg in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/image/library/gd.class.php:219
#13 Phpfox_Image_Library_Gd:createThumbnail in /home/xxxxxx/public_html/PF.Base/module/photo/include/service/callback.class.php:1339
#12 Photo_Service_Callback:updateCounter in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:1347
#11 eval in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:1347
#10 Phpfox_Module:callback in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:400
#9 Phpfox:callback in /home/xxxxxx/public_html/PF.Base/module/admincp/include/component/controller/maintain/counter.class.php:32
#8 Admincp_Component_Controller_Maintain_Counter:process in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:969
#7 Phpfox_Module:getComponent in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#6 Phpfox_Module:getController in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:307
#5 Phpfox_Module:setController in /home/xxxxxx/public_html/PF.Base/module/admincp/include/component/controller/index.class.php:654
#4 Admincp_Component_Controller_Index:process in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:969
#3 Phpfox_Module:getComponent in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#2 Phpfox_Module:getController in /home/xxxxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1278
#1 Phpfox:run in /home/xxxxxx/public_html/PF.Base/start.php:89
#0 require in /home/xxxxxx/public_html/index.php:7

Also i'm getting errors users search on adminc and new signups cant login into site they geting errors too..

**Comment by Ylmzef** [comment]
I fixed it. I checked debug mode and it was enabled by your staff without my knowledge for this:
https://github.com/moxi9/phpfox-sms-captcha/issues/2

Please let me know when you connect and do default value any settings like debug mode.

Thanks.

**Comment by Ylmzef** [comment]
It's still bug.

**Comment by Data66PF** [comment]
check your own comment from the 25th when you said "I fixed it"

**Comment by Ylmzef** [comment]
Yes but when i disabled it after that it was fixed.
But when i re enable it, it's still issue for the counter update..

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
