### ISSUE TITLE
Cant Enable Legacy Theme From Admin

### ISSUE THREAD

**Issue by Javierfernandez93** [moxi9/phpfox#458]
Hi! i'm trying to enable "Legacy Theme" on PhpFox 4 Admin, and after i do it the changes never update! Still looking Neutron Theme

**Comment by Ylmzef** [comment]
You are not alone :+1: 
http://community.phpfox.com/forum/thread/52444/cannot-change-to-legacy-theme/

**Comment by Data66PF** [comment]
confirmed in that thread per my quote
> I've tested on a fresh install. It seems as though the legacy theme is using the same css and html as >the neutron. I compared the files. So, it installed fine but I don't think it exported the css and html >when they exported it for the store.

**Comment by RaymondBenc** [comment]
Issue with this specific theme should be resolved. Please uninstall and re-install the theme and let us know how it goes.

Thanks!

**Comment by Ylmzef** [comment]
It's working now fine but there some bugs.
I'll posted it soon after a good research..

Thanks!
