### ISSUE TITLE
UserName is not saved ok by signup

### ISSUE THREAD

**Issue by Javierfernandez93** [moxi9/phpfox#459]
After i make a signup testing, i cant log in by UserName, buy when i use my Administrator account for see if is there the new info, i saw that the new user in their User Name has "user-1" instance of the username that i chosen for it  .

Another fix to do list! Please fix it because we're paying for a service, and you system is not working!

**Comment by Data66PF** [comment]
Did you set the registration setting to allow username to be entered? It would show two entries if you did, one for full name (which is their displayed name) and one for user name. If you didn't set that, then it will not allow for a user name to be entered and will make a user name #.

**Comment by Javierfernandez93** [comment]
Thanks For help! i resolved! :+1:
