### ISSUE TITLE
PHPfox Store Navigation Logs Me Out

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#46]
Logged into the store with my license key etc. User expects that since user logged in with the required info and got into their account that they can then navigate and do stuffs.

User is mistaken because any navigation to apps continually requires logging back in. It would be a better user experience if the user stayed logged in and did not have to constantly input their license info. 

For those with multiple licenses, perhaps it just asks which license they want to download / purchase stuff for. It should not require logging back in to view their downloads, account info, etc.

**Comment by Data66PF** [comment]
In case some at the forum do not come here to post, users are saying they can't log in from win 7 on ff and chrome. Worth testing that too. My tests were on win 8.1 pro with ff latest messed up version.

**Comment by RaymondBenc** [comment]
@Data66PF do they get an error message when trying to login?

**Comment by Data66PF** [comment]
Yes they get this {"error": "Unable to find this product."}

**Comment by RaymondBenc** [comment]
Are you able to get the clients info? If you are, please email it to me and I can check the DB.

Thanks for following up on this with us!

**Comment by saphiaduong** [comment]
![3](https://cloud.githubusercontent.com/assets/13254313/8594347/233c4b6a-266a-11e5-970f-000ffde81206.png)
![4](https://cloud.githubusercontent.com/assets/13254313/8594352/2c579696-266a-11e5-8379-0fb0e4dbcc80.png)
![5](https://cloud.githubusercontent.com/assets/13254313/8594356/34ec44be-266a-11e5-8426-d1234a1a3a86.png)

**Comment by RaymondBenc** [comment]
@Data66PF I fixed the initial issue with the logging in. We now keep a session so the user can stay logged in. This session also applies to when purchasing apps. I still need to add a logout. Will keep this issue open until that is fixed and I look over the clients issue.

**Comment by RaymondBenc** [comment]
@saphiaduong can you open a ticket here? http://www.phpfox.com/contact/
I wasn't able to find a license with those details in our DB. If you get in touch with us we can take a closer look.

Thanks!

**Comment by saphiaduong** [comment]
thank RaymondBenc . 
I have requested support in http://www.phpfox.com/contact/.
I sent PHPfox License, License ID and License Key

**Comment by saphiaduong** [comment]
I use the License ID and License Key installations for v4. it works.

**Comment by Data66PF** [comment]
Is this a developer license?

**Comment by saphiaduong** [comment]
![7](https://cloud.githubusercontent.com/assets/13254313/8594853/30e36b68-266f-11e5-8f79-75fa17ef8f96.png)

**Comment by RaymondBenc** [comment]
Thanks. Checking on the support ticket.

**Comment by RaymondBenc** [comment]
Licensing issue should now be resolved. The fix I added should also fix it for many other clients having issues.

**Comment by RaymondBenc** [comment]
I've updated the "My Downloads" area with a **Logout** link now.

**Comment by Data66PF** [comment]
Navigation and logout button are working fine for my tests. :) Hopefully the other client will update this if it is fixed for them too.
