### ISSUE TITLE
Block 3 issue on forum posting page.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#460]
I added Google Adsense code to Side Wide Block 3, but when i try posting topic on forums it's showing behind forum tools.

![download](https://cloud.githubusercontent.com/assets/8562514/9596347/e91c906e-5073-11e5-8ea3-61b440489a60.png)

**Comment by Data66PF** [comment]
What theme are you using? I tested with a normal ad, not google, and it shows fine like it does at the PF community.

**Comment by Ylmzef** [comment]
Default theme aslo it's not about normal ad it's about adsense with block way.

**Comment by Data66PF** [comment]
I know it was adsense in sitewide block. I was testing a normal sitewide block ad as any ad should work. I'll see if I can get my adsense account working for my development site.

**Comment by Data66PF** [comment]
Tested and for me, it shows behind the menus

![google forum](https://cloud.githubusercontent.com/assets/6908282/9787466/172dff3c-5791-11e5-8ff0-e4afbaa1a505.png)

This is not ideal. Recommend to hide block 3 or move its location for forum post/edit sections to fix this bug.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in 4.0.10
