### ISSUE TITLE
Incorrect formatting

### ISSUE THREAD

**Issue by websistema1** [moxi9/phpfox#461]
If you use Ukrainian or Russian language, some messages and comments on the website contain incorrect text - text encoding broken.
http://community.phpfox.com/forum/thread/52609/incorrect-formatting/

**Comment by websistema1** [comment]
This is a sample page (http://vsitut.com/blog), which shows formatting errors (scroll down)

**Comment by websistema1** [comment]
![2015-09-03_221204](https://cloud.githubusercontent.com/assets/14079310/9668312/7fa2938c-5289-11e5-955f-136f41169650.jpg)

![2015-09-03_221929](https://cloud.githubusercontent.com/assets/14079310/9668411/fd6543b4-5289-11e5-81e1-8ff64a10c67a.jpg)

These are examples of the wrong format. But the majority of the text is displayed correctly.

**Comment by Data66PF** [comment]
as I don't know for sure, I'll mark this a bug for @RaymondBenc to see as there are many sites that run this and other non latin languages/

**Comment by websistema1** [comment]
Dear developers! It's been almost 2 months after the publication - The fault is ignored. When the error is resolved? - I look forward to. Thanks in advance.

**Comment by Data66PF** [comment]
@phpfoxdev @RaymondBenc @neil96 or someone in our core devs. Please fix this asap. We have clients that cannot use the site like it is. thank you.

**Comment by websistema1** [comment]
Dear developers! I can not upgrade to version 4 - you do not fix the bug. What should I do? I bought 6 components of the upstream developer YuNet for version 4 - I can not use them. I'm really looking forward to fix.

Sorry for the bad english. Best regards and thank you beforehand.

**Comment by Criotin** [comment]
Привет websistema1.
Попробуй использовать патч для кириллицы и правильное обрезание фраз.
Hello websistema1.
Try to use a patch for the Cyrillic alphabet and the correct cutting phrases.

Патч для кириллицы.
The patch for Cyrillic.

1. In file: module\language\include\service\phrase\process.class.php

Before: $this->cache()->remove('locale', 'substr'); 
After:  $this->cache()->remove('language', 'substr'); 

Before:  $aPhrases = Phpfox::getLib('xml.parser')->parse(file_get_contents($sDir . $sFile)); 
After:  $aPhrases = Phpfox::getLib('xml.parser')->parse(file_get_contents($sDir . $sFile), 'UTF-8'); 

2. In file: include\library\phpfox\database\driver\mysql.class.php

After the code: return Phpfox_Error::set('Cannot connect to the database: ' . $this->_sqlError());
}
Insert:  $this->query('SET NAMES utf8'); 

3. In file: include\library\phpfox\parse\input.class.php

Before:     public function cleanTitle($sUrls)
    {
        $sUrls = trim(strip_tags($sUrls));
        $sUrls = $this->_utf8ToUnicode($sUrls, true);   
        $sUrls = preg_replace("/ +/", "-", $sUrls);   
        $sUrls = rawurlencode($sUrls);   
        $sUrls = str_replace(array('"', "'"), '', $sUrls);
        $sUrls = str_replace(' ', '-', $sUrls);
 
        $sUrls = str_replace(array('-----', '----', '---', '--'), '-', $sUrls);
        $sUrls = rtrim($sUrls, '-');
        $sUrls = ltrim($sUrls, '-');
   
        if (empty($sUrls))
        {
            $sUrls = PHPFOX_TIME;
        }
   
 
        $sUrls = strtolower($sUrls);
 
        return $sUrls;

After:     public function cleanTitle($sUrls)
    {
        $sUrls = trim(strip_tags($sUrls));
        $sUrls = $this->_utf8ToUnicode($sUrls, true);   
        $sUrls = preg_replace("/ +/", "-", $sUrls);       
        $sUrls = str_replace(array('"', "'", '.', ',', ';', '/', '\\', '`', '+'), '', $sUrls);
 
        $sUrls = str_replace(' ', '-', $sUrls);
        $sUrls = str_replace('_', '-', $sUrls);
        $sUrls = str_replace(array('-----', '----', '---', '--'), '-', $sUrls);
        $sUrls = rtrim($sUrls, '-');
        $sUrls = ltrim($sUrls, '-');
   
        if (empty($sUrls))
        {
            $sUrls = PHPFOX_TIME;
        }
   
        $sUrls = rawurlencode($sUrls);   
        $sUrls = strtolower($sUrls);
 
        return $sUrls;
    } 

Before:  $sNewTitle = substr($sNewTitle, 0, Phpfox::getParam('core.crop_seo_url')); 
After:  $sNewTitle = rawurlencode(substr(rawurldecode($sNewTitle), 0, Phpfox::getParam('core.crop_seo_url'))); 

After the code: private function _utf8ToUnicode($str, $bForUrl = false)
    {

Insert: return $str;


Правильное обрезание фраз.
Correct cutting phrases.

In file: include/library/phpfox/parse/output.class.php

Before: $str = substr($html, $position, $tagPosition - $position);
After: $str = mb_substr($html, $position, $tagPosition - $position,'UTF-8');

Before: $sNewString .= substr($str, 0, $maxLength - $printedLength);
After: $sNewString .= mb_substr($str, 0, $maxLength - $printedLength,'UTF-8');

Before: $sNewString .= substr($html, $position, $maxLength - $printedLength);
After: $sNewString .= mb_substr($html, $position, $maxLength - $printedLength,'UTF-8');

**Comment by Data66PF** [comment]
Thank you for the tips.
We do not recommend using unofficial source edits as that will void any support and could make the script unstable. As we are working on this and other language bugs, we recommend for you to wait to see when we can get the issue resolved. Should you decide to edit the source files, please note that any bugs created by it will not be covered by us. We are not responsible for damages caused to your site by source edits.

**Comment by websistema1** [comment]
Thank you. I do not use the patches. I look forward error correction from the developers.

**Comment by RaymondBenc** [comment]
In 4.2 I have applied a test fix. Due to this case being rather unique we could not build it into the core just yet. In order to enable this test fix once you have 4.2 installed you need to create a new file here:
**PF.Base/file/settings/debug.sett.php**

In that file add
```
<?php
define('PHPFOX_LANGUAGE_SHORTEN_BYPASS', true);
```

Once this has been added, what it does is prevent the shortening of text strings. The goal with this is that we will use CSS in the future to shorten these strings instead of PHP, which is what is causing the issue as it also depends on what PHP version you are using.

Please test these fixes and report back once you have 4.2 installed.

Thanks

**Comment by websistema1** [comment]
After the release of version 4.2 I will definitely check it out.
Thank you

**Comment by websistema1** [comment]
Many thanks! Correction of working - I do not see now the error. Can I upgrade version 3.8.0 to version 4.2 if I use the patch file debug.sett.php?
Sorry for the bad english. Thanks in advance.

**Comment by Data66PF** [comment]
Please note that 4.2 is an RC version so you would want to upgrade a development site first.

**Comment by Data66PF** [comment]
Is this working for everyone?

**Comment by websistema1** [comment]
I've successfully updated the site to version 4.2. Errors formatting is not found.
Thanks for the help.
