### ISSUE TITLE
profile feed issue

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#463]
The profile index feed block is not showing on all members feeds as it should. Settings checked and set to community and everyone still not showing even when checked with admin view.
![2015-09-02 05_07_29-new notification](https://cloud.githubusercontent.com/assets/13656046/9622504/1ac12e20-5134-11e5-96e1-caecdc1678b7.jpg)
![2015-09-02 05_06_08-new notification](https://cloud.githubusercontent.com/assets/13656046/9622486/d451878c-5133-11e5-996f-16e9c86f99c5.jpg)

**Comment by ASNLifestyle** [comment]
I also have an issue were I get this error message in the feeds every now and then.
TypeError: $(...).val(...) is undefined

**Comment by one44** [comment]
I think this is a controller issue between V3 and V4

**Comment by one44** [comment]
Refer  issue 471
