### ISSUE TITLE
Keep getting this error in feeds

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#464]
TypeError: $(...).val(...) is undefined

**Comment by websistema1** [comment]
Such mistakes I have. They emerged after installation Сometchat. Contact support Сometchat.

**Comment by ASNLifestyle** [comment]
ty

**Comment by websistema1** [comment]
See forum thread - http://community.phpfox.com/forum/thread/52358/сometchat/

**Comment by Data66PF** [comment]
Photos with adult images are not allowed here. Please search before posting. https://github.com/moxi9/phpfox/issues/341

**Comment by ASNLifestyle** [comment]
Comet chat is not the issue. What is next step.

**Comment by Data66PF** [comment]
Please see the bug link I posted. You'll need to wait for the fix as posted in the other bug. Thanks.

**Comment by ASNLifestyle** [comment]
I can not find the the link can you give it to me please.

**Comment by Data66PF** [comment]
It is in my comment above from Sept 3. Here is it again though https://github.com/moxi9/phpfox/issues/341
