### ISSUE TITLE
Manage button issue for pages.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#466]
![download](https://cloud.githubusercontent.com/assets/8562514/9644932/0e4c91f8-51c9-11e5-8355-5005f5262ea3.png)

**Comment by Data66PF** [comment]
Where are you seeing this please? I am at the PF community site and logged in as Admin. I click in the main Pages index page and click the search box. I don't see that manage button there at all.
![pagegithubissue](https://cloud.githubusercontent.com/assets/6908282/9686257/0d9f058c-52f1-11e5-881a-238ff9d18fc9.jpg)

**Comment by Ylmzef** [comment]
First go to any your page than click on photo link than check the photo search bar.

**Comment by Data66PF** [comment]
Confirmed on a page/group with no cover photo, if you go to the Photo section of this page/group, the manage button is misaligned. This is a minor design issue (not a critical bug).

**Comment by neil96** [comment]
This issue is duplicate with #847

**Comment by Ylmzef** [comment]
This for Neutron theme also i think you need to mark new tickets as duplicate. This ticket from 2 Sep anohter ticket from 18 Dec.

**Comment by neil96** [comment]
We fixed this issue both for neutron and bootstrap.
