### ISSUE TITLE
refresh nor working

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#468]
When you join a page the page must be manually refreshed to place a comment and to show you have joined the page.

**Comment by one44** [comment]
Using 4.0.8 and this still seems to be an issue that when you join a group or page no automatic refresh must do a manual refresh to show you have joined the page group.

**Comment by Ylmzef** [comment]
For me too!
Chrome 45
Windows 10

**Comment by one44** [comment]
Even on community site

**Comment by Data66PF** [comment]
Please open a new bug report and reference this one
