### ISSUE TITLE
Number of members listed on a page

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#469]
Is there a limit or a read more or scroll feature? See Image.
![2015-09-03 15_31_03-new notification](https://cloud.githubusercontent.com/assets/13656046/9659586/94eafb2c-5251-11e5-9a31-408dae74c94e.jpg)

**Comment by Data66PF** [comment]
Questions should be asked at the community as adding a view more or extending the amount shown would be a feature request or customization, not a bug.
