### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#470]
Please help me to resolve issue in my website.  we install cometchat in v4 .

We receive error in main page   index.php 
![error](https://cloud.githubusercontent.com/assets/12130785/9676009/b4115086-52de-11e5-9922-a879418a9275.jpg)

and also we facing issue in comments box
![error 2](https://cloud.githubusercontent.com/assets/12130785/9676036/2df3b416-52df-11e5-8ab0-c4838ace4280.jpg)

**Comment by Data66PF** [comment]
third party add ons are not supported. please see the developer.
