### ISSUE TITLE
Profiles set before upgrade to default landing page are blank

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#471]
If you have set your site to use a different default landing page for the profile, such as profile.info, then the upgrade shows a blank profile for users with no info filled in. 

admincp/setting/edit/?module-id=profile#profile_default_landing_page

testing on my live dev site, if I set that setting to profile.info as the default landing, it causes me not to be able to click and view the wall. I think maybe this is another setting that is removed but it also needs to change the setting back to Wall for upgrading sites.

**Comment by one44** [comment]
This does need a quick fix for those of us with live sites who have upgraded.

**Comment by Data66PF** [comment]
Did you set the setting back? The only thing I can think of is for you to back up the database and make the change via sql query for any users that manually set their landing pages.

**Comment by one44** [comment]
Yes working fine now thanks
