### ISSUE TITLE
Avatars on pages load slowly

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#475]
![2015-09-05 16_06_30-bbw bdsm south africa uk usa london ny durban gauteng adult dating](https://cloud.githubusercontent.com/assets/13656046/9699573/32647d0a-53e8-11e5-9a49-d0aeeec0dd7f.jpg)
After members on a page is clicked to show all members the pop up window takes ages to load the avatars. Confirmed on community site as well. Says  Members(20) and when you click on it the pop up windo appears but avatars load slowly or not at all.

**Comment by Data66PF** [comment]
Confirmed at the PHPfox community.

**Comment by RaymondBenc** [comment]
Issue resolved for 4.0.8 with https://github.com/moxi9/phpfox/commit/6b05dc3e2fed1f84660624387ee79cdbeafb99da#diff-7763fb035e81ce4900d1762ac6072662R83
