### ISSUE TITLE
Pasting links into the status update field

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#478]
When attempting to paste links into the "link" status update field "http://" is left in front of a link that has been copied and pasted.

Like the following.

http://http://??????????????

**Comment by Jinkers** [comment]
If you are asking a question, please do so in the forums at the community; http://community.phpfox.com as this tracker is only for bugs.

Otherwise, this is how it should function. It pastes directly what you copied.

**Comment by Scot74** [comment]
Do you perceive me to be asking a question? I was not. I was stating a fact. The fact is, when I copy a link and then paste it into the status update "link" field it leaves "http://" in front so that there are two.

Was I not perfectly clear in my previous articulation?

Did you not see the example above?

"http://http://??????????????"

I beg your pardon, this *is not* "how it should function".

![capture](https://cloud.githubusercontent.com/assets/14036909/9701860/b5a23a18-5406-11e5-81bd-2a77ebeefa5a.PNG)

**Comment by Jinkers** [comment]
I do apologize. I misread your first post in regards to the 'link' section, and I myself don't have the 'link' section enabled. As you can see, having an image with the first post helps clarify things.

**Comment by Scot74** [comment]
Ok. The initial supplied "http://" momentarily disappears but then comes back right after you insert and click paste, leaving it the field and it kills the link when users "share" it.

**Comment by Data66PF** [comment]
You shouldn't have those Link buttons at all. I see them on my local upgraded testing site so I'll confirm the bug that the extra, unused buttons still show. 

For pasting links, just copy and paste the link into the status share box. The new V4, if you test at the community demo, only has Status and Photo for the "buttons". The rest are not used.

**Comment by Scot74** [comment]
Thanks.

**Comment by Scot74** [comment]
Does that mean it will be fixed with the next download patch?
