### ISSUE TITLE
In feed message notification

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#479]
When a comment is added ro a post in the feed a notification is sent to the last poster and I assume the original person who started the thread but when you click on the notification it takes you to the original personas wall post who started the post on their wall but only shows first post and not the full thread with all comments and the last post you have been notified about. You have to do a manual page refresh to see all the posts.

**Comment by Data66PF** [comment]
I can confirm this but it does the same thing on my v3 site.

**Comment by Data66PF** [comment]
I can still reproduce this in 4.1.2 tests
