### ISSUE TITLE
Rewrite does not work

### ISSUE THREAD

**Issue by manny12** [moxi9/phpfox#48]
I created the .htaccess on the root, but the rewrite did not work.

**Comment by RaymondBenc** [comment]
Did you enable it from the AdminCP? via **AdminCP > Settings > Short URLs"

**Comment by manny12** [comment]
Yes i did so, but no love. It does not work

**Comment by RaymondBenc** [comment]
Okay, send us an email at: http://www.phpfox.com/contact/

If you provide your sites FTP details we can take a look at whats wrong as I am unable to confirm it locally and on our community.

**Comment by Data66PF** [comment]
This works fine on my test site as well. I created the .htaccess and loaded it to the root where I have the phpfox test site installed. The server supports mod_rewrite.

**Comment by RaymondBenc** [comment]
@Data66PF Yeah that is what I am thinking that the server might not support mod_rewrite.

**Comment by manny12** [comment]
Resolved, worked after i upgraded my Debian to the latest distro. Thanks a lot.

**Comment by RaymondBenc** [comment]
@manny12 thanks for updating us. Glad it worked!
