### ISSUE TITLE
Show more members on pages

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#480]
There is a bug on pages only group or communities pages allow the pop up for more then 12 members to be shown all other page groups do not have pop up function working so only 12 members of that page can be shown. Confirmed in phpfox community.
![2015-09-06 07_44_09-new notification](https://cloud.githubusercontent.com/assets/13656046/9702753/0ecd6d5a-546c-11e5-90a3-65e385b5c5be.jpg)
![2015-09-06 07_44_37-hi56 social networking community](https://cloud.githubusercontent.com/assets/13656046/9702755/183f8116-546c-11e5-950c-91bbad379a05.jpg)

**Comment by Data66PF** [comment]
confirmed at the community http://community.phpfox.com/pages/1/
