### ISSUE TITLE
Module Photo - Adult content

### ISSUE THREAD

**Issue by Fill1992** [moxi9/phpfox#481]
The ability to classify photos for adults was really convenient. In the new V4 I miss this feature, however. If this re-installed? And it will also show videos?

**Comment by Data66PF** [comment]
Confirmed that I see no way to mark a photo as mature yet the setting is still there in user group settings. This should be fixed as many clients use this feature.

**Comment by Fill1992** [comment]
I would like to see this feature genuine, we operate with a phpFox adult community, the function is therefore very important.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
