### ISSUE TITLE
Pop up in feed

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#483]
The pop up in the feed when friends are confirmed has a popup window showing how many friends in common and at the bottom a space for a message but the pop up dissapears before one can reach the space to send a message.

**Comment by Data66PF** [comment]
Non adult screenshot? :) I recall your site lol.

**Comment by one44** [comment]
I cannot do a screen shot as pop up disappreats to quickly LOL

**Comment by one44** [comment]
Ok had some sleep so did a page capture while curser over name LOL
![2015-09-08 05_13_36-greenshot](https://cloud.githubusercontent.com/assets/13656046/9725750/4f663328-55e9-11e5-9922-72481c1a5e92.jpg)

**Comment by one44** [comment]
Same on community site

**Comment by Data66PF** [comment]
I'll confirm it but it does stay up long enough for me to click the items. Perhaps he can adjust the timing though.

**Comment by one44** [comment]
LOL you must be quick I cannot no matter how many times I try.

**Comment by Data66PF** [comment]
It seems to stay on for almost 5 seconds for me.

**Comment by one44** [comment]
are we talking about same pop up mine disapears the moment I move the curser.

**Comment by Data66PF** [comment]
I over over the username in the feed. It shows the popup as you show it. In the popup, I can add as a friend or message. I can move the mouse over the add a friend, at the PF community and can just make it to that and click if I'm fast enough within that about 5 seconds. Sometimes though, it leaves within a few seconds so it depends on how bashful it is I guess lol. Anyway, it's confirmed for him to look and maybe add a longer delay.

**Comment by one44** [comment]
Checked in edge same issue thought it might be another FF issue
