### ISSUE TITLE
The Verification Mail never sent

### ISSUE THREAD

**Issue by Javierfernandez93** [moxi9/phpfox#485]
Hi! everyone i make a signup test and when it shows a message "An verification mail sent", i look for incoming mail on my mail account but isn't there, also on spam!. I dont know if is the smpt server, or its an problem from PHPFox

**Comment by Data66PF** [comment]
I can't reproduce any issues with sending verifications. Please use something like Mandrill (tutorial at scripttechs.com if you need a tutorial) and see if your site mails get out better.
