### ISSUE TITLE
Photo categories can not delete/rename

### ISSUE THREAD

**Issue by Offgrid99** [moxi9/phpfox#486]
Can not delete default categories in AdminCP
can edit/delete blog, forum etc. categories but no option to delete photo categories unless I am missing something...

![photo_categories 1](https://cloud.githubusercontent.com/assets/14171394/9724761/cbe9a25c-55aa-11e5-9158-09d444c2aa66.jpg)

When category is selected instead of Edit/Delete pop up i see this....

![photo_categories 2](https://cloud.githubusercontent.com/assets/14171394/9724768/d611985c-55aa-11e5-83c7-b4c3ae8d20db.jpg)

**Comment by Jinkers** [comment]
I don't see any default categories. What version are you using. 4.0.7?

**Comment by Jinkers** [comment]
Also similar instance report in iss #122. Perhaps try the information listed there also.

**Comment by Offgrid99** [comment]
That worked
