### ISSUE TITLE
Re sending Activation email Error

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#488]
Just upgraded my live website from v 3.8 to 4.7. My community is set to email verification for membership. If we resend  verification email to those who did not activated their accounts previously ,phpfox shows  following error.

preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead

**Comment by Data66PF** [comment]
Is your server updated per the requirements to at least php 5.4?

**Comment by aakash83** [comment]
i changed my hosting and now it is working.
