### ISSUE TITLE
Google Adsense doesn't work

### ISSUE THREAD

**Issue by stanojevicdejan** [moxi9/phpfox#489]
Hi, 

I have problem with adding adsense code to my site: www.rijaliti.tv
When I put same code on another site it works, but id doesn't work with my phpfox site.
I use SiteWide Controller, and Block 13 

Plese help me

Cheers

**Comment by Data66PF** [comment]
Is it new google code and is this v4? I don't think block 13 is one that works. Did you try block 7?

**Comment by Data66PF** [comment]
This is not for v3 issues. Please post in the forum as google ads work fine on my v3 sites.

**Comment by stanojevicdejan** [comment]
Hi,

I use v.8

 This is my code:

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-4215505034484023"
     data-ad-slot="7335037197"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

Please give me link for "google ads work fine on my v3 sites"
