### ISSUE TITLE
Login AS user feature removed? 

### ISSUE THREAD

**Issue by voarsh** [moxi9/phpfox#490]
LOGIN AS USER feature in V3 was useful for testing and doing some support actions which are not always possible via editing a user. 

Can someone confirm this has been removed? And if so, can it be brought back?

**Comment by one44** [comment]
works for me

**Comment by Jinkers** [comment]
I'm with @voarsh here. I can't find an option to view the website as a different user. @voarsh, Are you using a clean install of v4 or are you using an upgraded v3.8?. @one44 I believe you have an ungraded site, and perhaps is why you still have this feature?

**Comment by one44** [comment]
Yes upgraded site

**Comment by voarsh** [comment]
I wasn't even aware you could upgrade a V3 site. I threw it all away and went to a clean install of V4. I solved the issue - permissions issue. Thanks.


Kind regards,
Reese Jenner

**Comment by one44** [comment]
Have you gotta backup of the old site you can restore and then do an upgrade

**Comment by voarsh** [comment]
Yes I have a backup. Any documentation on how you upgrade?

**Comment by one44** [comment]
http://support.phpfox.com/browse/
