### ISSUE TITLE
Mobile - "What's up" not easily visible

### ISSUE THREAD

**Issue by voarsh** [moxi9/phpfox#492]
Apparently, my user seem to be quite DUMB, they don't realize that here is a little => next to their name on the navigation to see more options to post, I can't seem to spot this in the CSS/HTML, and I wanted to know if phpFox intends to simply this. Say, remove this and have it the same as desktop version, and/or put posting before the feed starts so it is at the top (the way it used to be)? 

(WEBSITE VIEW)
![4951894978985984](https://cloud.githubusercontent.com/assets/10189051/9769123/15ae17d0-5720-11e5-83b8-181891b6b3a7.png)

**Comment by Data66PF** [comment]
Features will not be addressed via the bug tracker but we will have a feature request system in the community soon. For questions like this, please ask at the community http://community.phpfox.com
