### ISSUE TITLE
Why I cannot pay to phpfox through paypal?

### ISSUE THREAD

**Issue by Alexlim91** [moxi9/phpfox#494]
Dear phpfox,

I willing to buy Nebula theme but i cannot pay on phpfox when during the checkout. It show this message to me "We re sorry, but your transaction couldn t be completed using the selected card Visa x-0903. This happened because it has been denied by the card issuer". But previously it wont show this kind message when i purchase on other site. I only happen on phpfox site.

Thank You

**Comment by Data66PF** [comment]
This is only for bugs with our script. Please contact Paypal.
