### ISSUE TITLE
Edit Theme Broken

### ISSUE THREAD

**Issue by Offgrid99** [moxi9/phpfox#495]
I made a couple copies of the default theme to play around with them and when i deleted one of the NON Default themes I got this message

![theme_deleted](https://cloud.githubusercontent.com/assets/14171394/9778725/591e4310-5742-11e5-850c-4080fc902a8a.jpg)

**Comment by Data66PF** [comment]
Did you clear cache and did the error go away? Is the theme deleted?

**Comment by Offgrid99** [comment]
![theme_deleted_2](https://cloud.githubusercontent.com/assets/14171394/9802408/f468034c-57e7-11e5-963c-a84e09df3844.jpg)

**Comment by Offgrid99** [comment]
once i click on Edit i get the "something went wrong" message

Cleared cache & still receiving the error

**Comment by Data66PF** [comment]
v4.0.7 tested by making a theme and then clicking Remove Theme and it removed fine. I cannot reproduce this in client version v4.0.7

**Comment by AnthonyKing** [comment]
change theme/ check the files in the pf base

**Comment by Data66PF** [comment]
The theme files for V4 are in PF.Site/themes .
