### ISSUE TITLE
search bar problem with legacy theme

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#497]
if we click inside the search area( legacy theme) a panel opens which displays search results. but if we type nothing and  don't want to search and  click anywhere on the page this panel don't close automatically. only way to close it is to navigate away from current page or do a page refresh.
![image](https://cloud.githubusercontent.com/assets/406030/9794632/88d6fe80-57ec-11e5-8dcc-e1a05f590814.png)

**Comment by Data66PF** [comment]
Confirmed with win 10 and chrome browser.

**Comment by rox123time** [comment]
I am sharing My code,Hopefully works for you just open panel.html.php file for search and in jquery after is copy paste this.

  //hide it when clicking anywhere else except the popup and the trigger
			$(document).on('click touch', function(event) {
			  if (!$(event.target).parents().addBack().is('#header_sub_menu_search_input') || !$(event.target).parents().addBack().is('._panel')) {
				$('#panel').hide();
				$('._panel').removeClass("active");
			  }
			});

          //Show popup when clicking Searchbox
			$(document).on('click touch', function(event) {
			  if ($(event.target).parents().addBack().is('#header_sub_menu_search_input')) {
				$('#panel').show();
			  }
			});
			
			// Remove Body Class when click on other than search icons
			$("._panel").click(function(){
			if(!$("#panel").visible)
			{
			$("body").removeClass("in-search-mode");
			 $('#panel').show();			 
			}
			else
			{
			$('#panel').hide();
			$('._panel').removeClass("active");
			}
				
			});
			
			
			// Stop propagation to prevent hiding "#panel" when clicking on it
			$('#panel').on('click touch', function(event) {
			  event.stopPropagation();
			});

**Comment by robert9592** [comment]
We have not supported theme "Legacy" anymore.
