### ISSUE TITLE
nitification like image

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#499]
When a member likes an image the person who placed the image clicks on notification and routine does not end shows loading image gets stuck must do a manual refresh to see image. Tested in FF and Edge,

**Comment by Data66PF** [comment]
Tested on my dev site, win 10 and FF 40 but the image loads fine for my test.

**Comment by one44** [comment]
will keep an eye as it seems to happen quite regularly

**Comment by Data66PF** [comment]
Feel free to friend me on the community and we can test there but I'm divided in time between that and my main scripttechs site plus my other sites.

**Comment by Data66PF** [comment]
I was unable to reproduce this. Are you still able to?

**Comment by one44** [comment]
As discussed it seems to happen on the first image once a manual refresh dome works fine.

**Comment by Data66PF** [comment]
Cannot reproduce and no other clients have posted that they can.
