### ISSUE TITLE
Odd issue installing apps

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#50]
Actually, it's more an odd issue after the apps are installed.

Have a fresh dev site installed so you've not installed any apps.

Go into admin and go to the apps and click to get some.

Install the video one for example. (I actually installed all the freebies at the same time)

Clear cache in admincp. 

Go to the front end and share a video in the video section (this is the one I tested first).

It shares fine but once you've done that, you've now got no add button. It has disappeared and you can't add more. (I did refresh the screen, logged in with a different browser, different user, etc)

Come back the next day and the add button is back. I am thinking there is some funkiness going on with cache or something, right after installing an app because this doesn't happen again after.

**Comment by RaymondBenc** [comment]
Could you email me some login details for your dev site? I got your email with the link but can't sign up on the site ATM. Thanks!

**Comment by Data66PF** [comment]
Done :)

**Comment by RaymondBenc** [comment]
Thanks! Its working now for me. So, to reproduce the error I would now install a new app then clear cache. Correct?

**Comment by Data66PF** [comment]
Yes. One that has not been installed before. It seems to be only right after installing. It works the next day.

**Comment by RaymondBenc** [comment]
Tried to reproduce it with installing the **Facebook Login**, no dice. If you can still reproduce, check this file after:
http://yoursite.com/Apps/PHPfox_VideoFeed/assets/autoload.js

See if the JS is loading for you. This app uses JS to load the link to share a video.

**Comment by Data66PF** [comment]
I'll do that. :) Thanks for testing.

**Comment by RaymondBenc** [comment]
Ran into an odd issue just now on our community, the **Facebook Login** button is gone for me. Does it show up for you?

**Comment by RaymondBenc** [comment]
oh nevermind, there it is. :)

**Comment by Data66PF** [comment]
I see it too. FB has been having app problems lately. Could have been that.

**Comment by BrunoSette** [comment]
The facebook Login button is gone for me too.

**Comment by BrunoSette** [comment]
http://www.provasdaoab.com.br/phpfox/index.php/

**Comment by RaymondBenc** [comment]
After investing this a little further, I can only reproduce this if I do not have short URLs setup. @Data66PF when you reproduced this issue do you recall if you had short URLs?

**Comment by RaymondBenc** [comment]
@BrunoSette your issue should be solved with the fix introduced here https://github.com/moxi9/phpfox/commit/09e3784dbf3a7402b9f3e7a84775061eeebe5267

**Comment by BrunoSette** [comment]
O don't have short url. I will change to short URL to see if it works.

**Comment by Data66PF** [comment]
I don't recall. I broke my dev sites so can't test again atm. :)

**Comment by BrunoSette** [comment]
I changed for short url and is working now, thanks!
