### ISSUE TITLE
No information about gender

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#502]
There no information about gender for profiles.

**Comment by Data66PF** [comment]
confirmed

**Comment by voarsh** [comment]
@RaymondBenc, @Data66PF 
I am still experiencing this bug. Gender text is NOT visible and I cannot select a gender. Changing DB values does nothing and accounts cannot be modified since no gender is selected (because I can't).
My version is: 4.1.1(build 3)

**Comment by Data66PF** [comment]
Please upgrade to current release and be sure you revert theme and sync css, and clear cache. Backup any changes you made first.

**Comment by voarsh** [comment]
Thanks. ^^ resolved.
