### ISSUE TITLE
search field not visible in profile

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#503]
when a profile page (index, blog etc) is scrolled down the profile menu is in front of the search field.

**Comment by Data66PF** [comment]
What search field?

**Comment by Data66PF** [comment]
Found it. Only on profile.photo, profile.blog, not at profile.index as I don't see a search on that.

I think this is by design but will mark it confirmed.

**Comment by lordofnos** [comment]
search field from main menu ;)

**Comment by Data66PF** [comment]
oh that's different as the profile has it's own search field.

**Comment by Data66PF** [comment]
Do you prefer this be marked not a bug then as the global search is something different than the profile search?

**Comment by lordofnos** [comment]
it is a bug because when i am on a profile page i probably want to use the main search too

**Comment by Data66PF** [comment]
Let me test for that then.

**Comment by Data66PF** [comment]
I can see the issue but I don't think this is something that anyone would do because if they were searching, then they would just be typing it in, not opening it and then scrolling down to search. However, I will mark it a bug/enhancement. This means, it is not a crucial bug but a minor inconvenience to be looked at after some of the major bugs are resolved.

**Comment by lordofnos** [comment]
when theres a top menu on blog, music, event etc. the search field slides in from the main menu an overlays the site. this is imho how it has to behave on profile pages too. do i miss something here?

**Comment by Data66PF** [comment]
Like I mentioned, I put it as a bug for him to look at but it is more important to fix critical errors first. These sort of things are not stopping the site from working and a few other bugs are, such as the users can't log in after registration bug. We need to focus on the critical bugs first as those make the site not usable. These smaller bugs will get fixed if he deems them a bug but first, the critical stuff must be addressed. Thanks for posting for us though. :)

**Comment by lordofnos** [comment]
yes of cause... i am looking forward to get a stable version too ;) just mentioned this here for the sake of completeness. only a small css issue here.
