### ISSUE TITLE
share on pages discussion

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#504]
When discussion the forum thread form is used in pages/groups a share button appears but does nothing it should be a comment block or a share block and comment block. There is a share button
![2015-09-12 16_58_33-cuckold bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult d](https://cloud.githubusercontent.com/assets/13656046/9832085/4d80bbc0-5970-11e5-8dd3-609aedc7c7c8.jpg)
![2015-09-12 16_58_51-cuckold bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult d](https://cloud.githubusercontent.com/assets/13656046/9832088/5174ceb0-5970-11e5-8e2c-190544f4f795.jpg)

 above admin on the page.

**Comment by one44** [comment]
Normal posts have same issues
![2015-09-13 06_28_58-network connections](https://cloud.githubusercontent.com/assets/13656046/9835248/38a3348c-59e1-11e5-9363-c2f10f2d5634.jpg)

**Comment by Data66PF** [comment]
Addressing only one issue. I am not sure what you mean with the discussion in pages issue. I go to my page/group http://community.phpfox.com/wog/ and in the feed, I see some discussions. I click the share button thing and it drops down the share thing like you show. I click share and it gives me options to share the discussion.

**Comment by one44** [comment]
There are two ways to add discussion one is on the wall the other is with forum by clicking discussion at the top and this seems to give the issue.

**Comment by Data66PF** [comment]
I still don't see any issue on the PF community. I go to my page that I linked before. I see a discussion thread in the feed and click the share thing. It opens a share option.

I then click Discussions and am at the group's discussion (forum) that lists all of the threads. I click to open one of the threads and click the share button thing and it opens a share/edit/ etc option area.

**Comment by one44** [comment]
ok I am the idiot as you have to click on the word share and not the black line. It would make more sense id the word was in a button.

**Comment by Data66PF** [comment]
Yes click the word share as there are other things to do in that options box sometimes, such as edit, delete, report. :) You can style it as a button if you prefer though.

**Comment by one44** [comment]
These little things may seem unimportant to a coder but for users of the site and non coders it is a big issue as it impacts user satisfaction and navigation. Have you looked at oxwall and seen their user friendliness and service.

**Comment by Data66PF** [comment]
I don't see any issues with them being links but again, it can be changed in your css. It isn't hard to make it look like a button if you add some css code. I don't use oxwall as it is not that stable.
