### ISSUE TITLE
Registration Form Missing Confirm Button During Invite Process

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#506]
Hello,

I was testing the invite and registration process and noticed a small issue. When a user receive a invite from a friend and try to registrate the form on domain.com/user/register doesnt has a confirm, send or register button.

Is possible to conclude the using enter to send the information, however I think that isnt a natural process, since in general forms include a button to conclude the process.

**Comment by Jinkers** [comment]
Are you using the recaptcha app at all? If so the form auto submits once that is activated.

**Comment by leandrotavaresrocha** [comment]
No. I am not using captcha

**Comment by Data66PF** [comment]
I cannot reproduce this.

I have default theme enabled, recaptcha is not enabled.

I have registration enabled as it is required to have that enabled.

I invited myself on one of my emails. When I enter the email, it goes to the registration form and I see a sign up button.

**Comment by leandrotavaresrocha** [comment]
Well, I am in a travel now. Once I arrived I will screenshot the form.

**Comment by leandrotavaresrocha** [comment]
I made a test and seems that this issue is related with the app "phpfox recaptcha", because even when disabled the app hide the signup button. If someone else is using this app and could confirm I would be grateful

**Comment by Data66PF** [comment]
The recaptcha is designed that way because once the user does the recaptcha correctly, then it autosubmits the form. This is to avoid someone somehow bypassing recaptcha so this is working as designed if using that app.

**Comment by leandrotavaresrocha** [comment]
But the point is that even with recaptcha disabled the button is hidden. I deleted the app and the button returned, however couldnt reinstall to check if was just a cache issue or the app is really hidding the signup button even when is disabled.

**Comment by Data66PF** [comment]
You said you deleted the app and the button returned. The app does not hide the button when the app is not installed. I've already posted that I could not reproduce this on a site without recaptha.
