### ISSUE TITLE
Neutron Theme Mobile Sidebar

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#507]
Hello,

I was testing the v4 mobile version and found a UX issue related with the sidebar. 

This sidebar is not intuitive, since it display the blocks that are in right sidebar and sometimes the icon overlap important  content. Other times when opened the panel cant be full scrolled so it stop at half of the sidebar content. Sometimes when there is no block assign the icon still being displayed, however it dont open.

I think that considering that confusion between user is the same of lose user, this sidebar panel should be reworked. In my community I just hide, however I think for some users this can not bs the best option.

**Comment by Data66PF** [comment]
Please post one issue per bug report. Please search before posting. #156
