### ISSUE TITLE
language app import starts and get screen blanked....installation exiting.

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#509]
fresh installation v4.0.7
copy all the files into root directory
did 0777 the specified folders.
fire the domain
entered the id and key
enter the database details.
started the installation...
table creations done
language app import starts and get screen blanked....installation exiting.
kindly help

**Comment by Data66PF** [comment]
Please search before posting. #367

**Comment by haisay** [comment]
I'm says that the social network script not able to install in my server. I'm not trying to add any app. Just installing the fresh phpfox-v4.0.7

**Comment by Data66PF** [comment]
It is the same issue. Please read it again.

**Comment by haisay** [comment]
Dear Data, im not installing or importing anything. What i;m says that the phpfox v4.0.7 not able to install in my server. 
simply says that the script installation not completing.

**Comment by Data66PF** [comment]
ok this says language app not able to install. Note that issues with installing are not covered in bugs as it would be a server issue. You can pay for install service or post a question in the community.

**Comment by haisay** [comment]
Dear Data,
Thanks for your support. Im using this script from 2009. with littil bit familiar with the server and script. So i request you that kindly share with us possible mistakes.

the phpfox script required configurations are matches with the server.

Kindly share if have any tool for required config checking.

Thanks
