### ISSUE TITLE
Installing error 

### ISSUE THREAD

**Issue by BrunoSette** [moxi9/phpfox#51]
I tried to install but I got the error: 

"Unable to open config file."

**Comment by RaymondBenc** [comment]
Was this related to the other bug report (#52) in regards to folder permissions? That error only comes up if it is unable to write to the settings folder.

**Comment by Data66PF** [comment]
http://scripttechs.com/article/352/how-to-install-phpfox-v4-on-xampp-local/ for anyone having issues installing the dev, I had posted that by request. Hope it helps.
