### ISSUE TITLE
Featured images do not show on the login page

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#511]
Apart from the fact that there needs to be a way to select what images are shown on the login page, a second batch doesn't get displayed at all. Initially, I featured about 8-10 images and they automatically cycle through just fine. Later, a week later, I "featured" three additional images and they *do not* show up on the login page.

**Comment by Data66PF** [comment]
How many total do you have featured? You said "8-10" and then added 3 more. Please let us know the count.

**Comment by Scot74** [comment]
12

**Comment by Jinkers** [comment]
After each round of featured images I add we cleared cache and redid the counters and it works fine. Have you tried these functions and similar natured ones?

**Comment by Scot74** [comment]
I have not tried that. How does one reset the counters? What are "the counters"?

**Comment by Data66PF** [comment]
According to Ray, counters should be updated every few months. I don't have a technical explanation for it though, just know that it updates the counts and tends to make content links work if they were broken before. Someone else would need to explain it better. Just don't run any that say for v1 to v whatever. don't run any that say to only run them once after upgrading from v2 to v3. 

Best to backup the site before running counters if you are not sure what they do. 

Go to Maintenance >> Counters and select the ones that are not specific as mentioned above. Clear cache after.

**Comment by one44** [comment]
Counters are in admincp under maintenance.

**Comment by Data66PF** [comment]
Still unable to reproduce this issue.
