### ISSUE TITLE
Friend Suggestion Alignment

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#512]
The friend suggestion alignment is incorrect.

![2015-09-17 06_36_14-bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult dating](https://cloud.githubusercontent.com/assets/13656046/9925062/abe0da9e-5d06-11e5-8e20-eb5cb3e63daf.jpg)

**Comment by Data66PF** [comment]
Where are you seeing friend suggestions?

**Comment by one44** [comment]
It shows in block three and is set as a block

**Comment by Data66PF** [comment]
yeah but I can't get mine to show at all. I've got members. They have their locations set. It seems not to show on a fresh install. At least not for me yet.

**Comment by one44** [comment]
Must be only in upgrade sites then.

**Comment by Jinkers** [comment]
Are you using the Wisteria Theme? I remember seeing this somewhere, but was resolved when I updated the site.

**Comment by one44** [comment]
Yes wisteria theme and 4.0.7

**Comment by Data66PF** [comment]
Did you update the theme and clear cache?

**Comment by one44** [comment]
Yes but it may be a css issue as \I spent ages changing the css colors and am reusing the same file so may have to redo the css will check later

**Comment by one44** [comment]
reloaded wisteria theme still same issue

**Comment by Data66PF** [comment]
I still can't get the block to show up on my site and I have several members with the same criteria.

**Comment by one44** [comment]
Will see what happens when 4.0.8 is released.

**Comment by Data66PF** [comment]
Is this resolved?

**Comment by one44** [comment]
No still same issue

**Comment by Data66PF** [comment]
For the life of me I can't get this block to show. I think it might be a carry over from v3. I'll have to test an upgraded site.

**Comment by leandrotavaresrocha** [comment]
I am using a fresh install and there is a friend suggestion block in admincp, however it doesnt display at the frontend.

**Comment by Jinkers** [comment]
Check on default Neutron Theme and Wistera, still unable to find this on a fresh install.

**Comment by one44** [comment]
Mine displays but alignment still wrong.

**Comment by Data66PF** [comment]
Hopefully someone else can test this as I also still can't get it to show up on any of my test sites.

**Comment by one44** [comment]
Settings
![2015-10-18 14_41_08-admin cp block manager bdsm south africa _ uk _ usa _ london _ ny _ durban_](https://cloud.githubusercontent.com/assets/13656046/10564097/d1d1604e-75a6-11e5-8fed-51bd91a67ee5.png)
![2015-10-18 14_41_34-admin cp block manager add new block bdsm south africa _ uk _ usa _ london](https://cloud.githubusercontent.com/assets/13656046/10564099/d84bc2d4-75a6-11e5-9483-1a6cbcdc8da5.png)

**Comment by Data66PF** [comment]
That's what I have. I have no idea what is up with this but will keep trying to figure it out.

**Comment by Data66PF** [comment]
As most of us can't even get the block to show, I'll mark this a bug to be looked into so we can either disable it from showing as a block in admincp or make it work if it was not something removed.

**Comment by Gatsby-PF** [comment]
When I see an object displaced from its position like this, it has previously been found that a css edit error/omission was the cause, in or around the positioin: relative/absolute for the block in question.

A post I made earlier had a friend count object eclipsing the Friends word in the profiles friends block. As it went, the semi-colon ; was missing from the end of the hex color code for "Friends". After correction, the object assumed its correct position.

Your site looks like it has some css customization going on so perhaps something  is amiss? Although I followed my nose on the above issue, you could also use Notepad++ "Compare" plug in to compare existing anything to the original anything, detecting and displaying every difference.

**Comment by Data66PF** [comment]
I can confirm this on a client site I just upgraded from V3 to V4.1. The suggestion block has a bad alignment issue as shown in the bug report.

**Comment by robert9592** [comment]
Fixed for v4.1.1
