### ISSUE TITLE
The string "Sign Up" can not be translated

### ISSUE THREAD

**Issue by davchy** [moxi9/phpfox#514]
Neutron Theme (supplied with the script) - splash screen - registration form. 
I have translated the key "user.sign_up" and "user.sign" but the text still appears in English. I used the "Find Missing Phrases", but no other key was found.
Other texts (for example, Full Name) is translatable.

(All previous relates to newly added language.)

**Comment by Data66PF** [comment]
Did you fully clear cache after? https://github.com/moxi9/phpfox/issues/408 and please search before posting

**Comment by davchy** [comment]
Yes, I deleted the cache. I did it first.
I use version 4.0.7, fresh installation.

I do not understand that you can not reproduce it.

1) to search for the missing phrases for English (master)
2) create a new language from English (master)
3) to search for the missing phrases for a new language (unnecessary in relation to point 1, but in each case)
4) to set the new language as default
5) Edits individual keys
6) I delete cache
7) the result see the attached screen

![screen shot 09-20-15 at 09 18 am](https://cloud.githubusercontent.com/assets/14294270/9979811/f997e9d2-5f7f-11e5-9232-7d8d569afb9c.PNG)
![screen shot 09-20-15 at 09 24 am](https://cloud.githubusercontent.com/assets/14294270/9979810/f9963ee8-5f7f-11e5-92df-6ba2493ede67.PNG)
![screen shot 09-20-15 at 09 23 am](https://cloud.githubusercontent.com/assets/14294270/9979812/f99a7c42-5f7f-11e5-80e3-3b8c87bc973b.PNG)

**Comment by Data66PF** [comment]
Again, this is a duplicate. See the bug report I linked where even the client says it is fixed now. Wait for v4.0.8 release please.
