### ISSUE TITLE
Access for own Blocks

### ISSUE THREAD

**Issue by Fill1992** [moxi9/phpfox#516]
Unfortunately, you can not set the access for blocks in AdminCP. :/

**Comment by Data66PF** [comment]
The feature request area is at the community. If you want to make blocks with specific access, you can make them as a developer and put permissions in.

**Comment by Fill1992** [comment]
How? I don't found :/

**Comment by one44** [comment]
http://community.phpfox.com/forum/122/neutron-v4-feature-requests/
