### ISSUE TITLE
Notification of comment on a link posted

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#517]
When someone who has posted a link is notified of a comment on that link the code is showing when the notification is clicked on to see the comment.

![2015-09-21 03_58_11-android porn app takes secret photos of users bdsm south africa _ uk _ usa _ l](https://cloud.githubusercontent.com/assets/13656046/9984324/a0096a08-6015-11e5-8c31-3e5dda9b6ca1.jpg)

**Comment by AnthonyKing** [comment]
CHECK the code yourelf maybe the code blocks are not inserted corrctly

**Comment by one44** [comment]
What code blocks this is from a standard install this has nothing to do with blocks created.

**Comment by Data66PF** [comment]
Confirmed. To see the issue:

1. User a posts a link to user b's profile wall by going to their profile and copying and pasting a link in their status share.

2. User b logs in and comments on that post.

3. User a logs in, clicks their notification of that comment and is taken to that specific feed item. It is then that we see the code shown in the above image.

Tested with default Neutron theme on win 10, firefox latest version. V4.0.7
