### ISSUE TITLE
Log In Sign Up error

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#518]
i logged out of my site and found out that the submit
![screenshot 950](https://cloud.githubusercontent.com/assets/12142143/10001574/ad9132fe-60a2-11e5-9deb-b45a139944c9.png)
 button for sign up form is missing and the log in form is not visible, i had to press TAB to enter my log in details. please help me solve this issue

**Comment by Data66PF** [comment]
There is no submit button when using recaptcha as the recaptcha auto submits it after.

In regards to log in, I can't reproduce any issue with unedited default theme.

**Comment by AnthonyKing** [comment]
i fixed the error, i install bgchager,  after i disabled it worked fine
