### ISSUE TITLE
Status updates issue on profile page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#519]
I'm searching my old status updates on my own profile but some status updates not showing.
Tested on phpfox community.

**Comment by Data66PF** [comment]
How are you searching? I scrolled down to see and it seems like all of my feeds are loading.

**Comment by Ylmzef** [comment]
For me not. Im looking my old forum post but i can't find it on my newsfeed.

**Comment by Data66PF** [comment]
Was it deleted or maybe it was moved to another duplicated post perhaps? Is it just one feed you are missing? If so, then it was probably changed or moved or something like that.

**Comment by Ylmzef** [comment]
No i can find it on forums search.

**Comment by Data66PF** [comment]
If it is just one thing then it is probably something that was changed, deleted, moved or something. If it is many, then it would need to be looked at. I can't seem to reproduce any issue as my profile feed goes way back with a lot of things on it.

**Comment by Data66PF** [comment]
Which thread was it?

**Comment by Ylmzef** [comment]
Example: http://community.phpfox.com/forum/thread/52619/why-you-don-039-t-fixing-bugs/

**Comment by Data66PF** [comment]
But I see that one in your feed on your profile.

**Comment by Ylmzef** [comment]
I can't find it as my self profile.
If you want  i can provide my login details you can check it.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8 fixed

**Comment by Ylmzef** [comment]
Still not working cleaed cache and updated counters also tested on phpfox community too.

**Comment by Ylmzef** [comment]
I'm waiting for this please check it!

**Comment by Data66PF** [comment]
Please open a new bug as this has a fix linked in it where the coders fixed it. Please remember that some of your threads were closed into the archives as a different user got upset and was swearing in them. Those will not show on your profile.
