### ISSUE TITLE
chmod 0777 to PF.Base/file/ 

### ISSUE THREAD

**Issue by BrunoSette** [moxi9/phpfox#52]
The instruction to Give write access to the folders PF.Base/file/ can't be done because the /file/ is not in the git anymore.

**Comment by Data66PF** [comment]
http://support.phpfox.com/getting-started/installing-phpfox/ it says 

Once you have uploaded all the files/folders. You need to grant full read/write access (usually 0777) to the following 2 folders:

    PF.Base/
    PF.Site/

**Comment by RaymondBenc** [comment]
@Data66PF Thanks 

I've updated the dist instructions with the new folder path.
