### ISSUE TITLE
Missing Payment Gateway

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#521]
The pre-sales features for Neutron at http://www.phpfox.com/#intro  represented both PayPal and 2Checkout gateways as being included under the "Monetize" features category.  

To quote exactly:

"Payment Gateways API

We have included with our product support for both PayPal and 2Checkout giving you the best of what both companies can provide for online payments."

Upon going to set up the Gateways, I find only PayPal, no 2Checkout.

**Comment by Data66PF** [comment]
confirmed v4.0.7

**Comment by RaymondBenc** [comment]
The feature set for v4 was initially brought over from v3. Due to legal reasons we will not include support for 2checkout with our core product. It is still part of the v3 source code and can actually be taken from there if needed. We are developing an app to use Stripe instead.

**Comment by Data66PF** [comment]
Ok we need to remove it from the sales page features please
