### ISSUE TITLE
Vistors Page when registration is disabled

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#524]
When registrations are disabled   visitors page  still contain a signup button which is not clickable though. it should contain a message that registrations are disabled.
![image](https://cloud.githubusercontent.com/assets/406030/10029171/db744f70-6170-11e5-85c4-a6177b82c9e6.png)

**Comment by Data66PF** [comment]
confirmed on my live dev site.

**Comment by NetworkCycles** [comment]
I got this also when I switched to Invite Only site. 
I had to clear out my browser cookies to make it go away.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
