### ISSUE TITLE
How I can escape string in app?

### ISSUE THREAD

**Issue by ngontt** [moxi9/phpfox#525]
I am querying on App, but I can't escape string
Example:
->where('u.full_name="' . $sUserName. '")
in normal way, I can use $this->escape($sUserName), but function escape is missing on Model.
Thanks for support.

**Comment by ngontt** [comment]
I also found another problem:
In mail controller, when I scroll down, ajax still load and message "No messages found here." append again and again.
http://ngon.work/mail_error.png

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
