### ISSUE TITLE
can change password of user in phpfox4

### ISSUE THREAD

**Issue by tunghdt91** [moxi9/phpfox#526]
Hello.. i try change password in phpfox 4.. but it say old password false..
i try to other site, and it too..
Please check

**Comment by Data66PF** [comment]
I've seen this on a few fresh installs. Confirmed in 4.0.7 from this original bug report. https://github.com/moxi9/phpfox/issues/221

Testing on dev and now my admin account is messed up. I was able to change from a password with only letters to a password with letters and a number. That worked fine. However, when I tested again, I was unable to change from the new password, letters and a number, back to a password with just letters. (not sure if that has anything to do with it). Note that I had changed the password successfully two times before to all letters. 

Now, when trying to change the password, it showed the bad password error. When I tried again, it shows this now:

Whoops\Exception\ErrorException thrown with message "Undefined variable: _SESSION"

Stacktrace:
#15 Whoops\Exception\ErrorException in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/session/storage/session.class.php:85
#14 Whoops\Run:handleError in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/session/storage/session.class.php:85
#13 Phpfox_Session_Storage_Session:remove in /home/mysite/public_html/mysite/PF.Base/module/user/include/service/auth.class.php:522
#12 User_Service_Auth:logout in /home/mysite/public_html/mysite/PF.Base/module/user/include/service/auth.class.php:139
#11 User_Service_Auth:__construct in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:248
#10 Phpfox:getObject in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:857
#9 Phpfox_Module:getService in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:474
#8 Phpfox:getService in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:550
#7 Phpfox:getUserId in /home/mysite/public_html/mysite/PF.Src/Core/Controller.php:17
#6 Core\Controller:__construct in /home/mysite/public_html/mysite/PF.Src/Core/Route/Group.php:10
#5 Core\Route\Group:__construct in /home/mysite/public_html/mysite/PF.Site/Apps/PHPfox_Base/start.php:201
#4 require_once in /home/mysite/public_html/mysite/PF.Src/Core/App.php:74
#3 Core\App:__construct in /home/mysite/public_html/mysite/PF.Base/include/library/phpfox/plugin/plugin.class.php:91
#2 Phpfox_Plugin:set in /home/mysite/public_html/mysite/PF.Base/include/init.inc.php:177
#1 require in /home/mysite/public_html/mysite/PF.Base/start.php:34
#0 require in /home/mysite/public_html/mysite/index.php:7
