### ISSUE TITLE
Cover pics

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#527]
When uploading a cover pic the image is not renamed. This causes a problem if a member uploads a image with the same name as another members cover image, the wrong image is called. This is an issue in pages but could be on members walls as well.

**Comment by Data66PF** [comment]
I'll try this but have never heard of this before and don't know of a solution for your users loading the same name of the image.

**Comment by Data66PF** [comment]
For me, the script changes the photo names to random numbers. It is not using the actual photo name for the photo. Did you have rename photos to true prior to upgrading? That setting is no longer in v4.

**Comment by one44** [comment]
have no idea what it was in V3

**Comment by Data66PF** [comment]
check in the database settings just in case as my v4.0.8 changes the file name to random numbers for cover photos. I didn't check for normal photos.

**Comment by one44** [comment]
Seems to be numbers so will keep an eye on things and see if problem keeps happening. I am om 4.0.8 now.

**Comment by Data66PF** [comment]
ok as I loaded two photos with the same name to test and each one was changed and neither is getting confused so it seems an odd issue on your site perhaps.
