### ISSUE TITLE
Site Slow Down

### ISSUE THREAD

**Issue by Alexlim91** [moxi9/phpfox#528]
Hi Script Techs,
I facing serious problem with my phpfox website speed. When i log out the website load fast when i login to my account / admin account the website slow down. I got ask my hosting provider they got help me check the status then they found the phpfox script is overload please see the link below and the attachment. 
http://buddyzpage.com/debug/trace.php?file=trace.2646832878.xt&memory=0.3&time=0.03
Please help me fix this problem.
Thank You

**Comment by Data66PF** [comment]
This is the bug issue tracker for phpfox v4 neutron. This is not for product support. Please post at the community http://community.phpfox.com if you want to get advice for your site from other clients.
