### ISSUE TITLE
Well I want to report some bugs.... For Phpfox

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#531]
Well I have been a very closer observer of phpfox for a long time I see you are doing a great job. Well I am very assured you will do more for better in the future. But for now I have some bugs to report for in Neutron well I hope this would a help too.
1) If you are from company and you want to create a page you don't get to create a page rather you have to crate a profile and then create page please fix this
2) As a page administrator in Neutron you don't get to see how visitors you get for Page.
3)When you are sending a private message to another member in Neutron and the message is photo and you send it and you don't get to see the thumb nails of the image rather you get to see the address where the image is uploaded in the server and you can't even send multiple images at time and simultaneously please fix this bug.
4) While you are writing something in What's up? option the left top side if you keep writing a lot you don't get to see the share button developers of Phpfox please fix bug.
5) Lets say I upload an image to my profile and what did it show in the name of the image the name I gave the image in my computer different name for different images and different name of image for users why not make it default site name. In facebook if you upload an image it shoes in its name facebook not vlcsnapshot112 if I upload the image from a snapshot I took from VLC media player. But in phpfox it says in the top of the image vlcsnapshot112 Please fix this.....
This are the bugs I see for Now 
And Sir please if you can you add an IM(Chat) to Neutron like in Nebula.

**Comment by Data66PF** [comment]
Please note that  the things you want are feature requests. Please post feature requests, one per thread (don't post more than one request in a thread) here, http://community.phpfox.com/forum/122/neutron-v4-feature-requests/.

When posting things that are actual bugs, please post only one bug per issue here too. Note that bugs are things that make the script not work and are errors. They are not missing features or features you want changed. Thanks.
