### ISSUE TITLE
Reordering Menu Link Positions

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#533]
Does anyone have an issue dragging and dropping to relocate menu items under Admin Panel/Menu?

When I drag to relocate a link from the bottom of the menu toward the top, it moves in the Admin Panel, but when I clear cache it does not take to the screen.  When I go back to Admin Panel/Menu, it is back where it was at the bottom.

**Comment by one44** [comment]
Did you save the changes

**Comment by Data66PF** [comment]
I cannot reproduce this. V4.0.8. Cleared cache after changing the menu. There is no Save button, it automatically saves.

**Comment by Gatsby-PF** [comment]
Hmm...
No unusual errors in the DB log, and all other admin settings take ok. I will make a backup of the DB and go in and see if I can't change a variable manually.
Might not be a bad idea to bump up one notch to the on 4.0.8 while I'm at it.
