### ISSUE TITLE
long listing titles

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#534]
after 39 chars the listing title gets a break and price, time and user tags went out of the box...

**Comment by Data66PF** [comment]
screen shot please

**Comment by lordofnos** [comment]
simply test it on community site... there´s a listing from me with looooong title ;)

**Comment by majdmike** [comment]
![long listing titles 534_1](https://cloud.githubusercontent.com/assets/14811094/10057922/b79eac8a-6210-11e5-977e-cee98d4ff051.jpg)
![long listing titles 534_2](https://cloud.githubusercontent.com/assets/14811094/10057923/b7a049dc-6210-11e5-9ba5-0f88b7387add.jpg)

**Comment by lordofnos** [comment]
![listing](https://cloud.githubusercontent.com/assets/13225682/10058462/dd4c6f82-6245-11e5-957d-0a9d40b15e17.jpg)
