### ISSUE TITLE
create music album

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#535]
when uploading a song there´s no way to create an album or to put the song in a consisting album

**Comment by Data66PF** [comment]
In order to put a song in an album, you first go to the album, http://community.phpfox.com/music/browse/album/view_my-album/ choose one of yours there or make a new one, and then click the pencil icon in the top right when viewing the album. Select to Upload New Track

**Comment by lordofnos** [comment]
thats clear so far but it is not intuitiv. in 3.8 it was like putting a photo into an album... just a listview... very nice
