### ISSUE TITLE
long album titles

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#538]
when the title for a music album is too long it gets under the album cover

**Comment by Data66PF** [comment]
Please provide links to your tests or screenshots as it makes it faster for us. Since it's just me testing, and there are hundreds of bugs for him to fix, it really helps to have complete reports. Thanks.
http://community.phpfox.com/music/browse/album/
Confirmed at the PF community

**Comment by lordofnos** [comment]
![albumtitle](https://cloud.githubusercontent.com/assets/13225682/10108061/124d3e58-63bf-11e5-8622-fc23d23eb44c.jpg)
