### ISSUE TITLE
upgrade not working for me

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#540]
i followed all the steps on how to upgrade manually and when i enter the url 'http://www.yoursite.com/index.php?phpfox-upgrade=true' with my domain, it does not go to the next step to input my license and when i access the admin panel > system overview i see that i still have 4.0.7
![screenshot 958](https://cloud.githubusercontent.com/assets/12142143/10059454/5443106e-624b-11e5-9f68-2b0ea2c5c9d4.png)

**Comment by Gatsby-PF** [comment]
Is your system trying to force the install over encrypted connection (https://)? 4.07 failed to install under https://, and was only allowed to do so under http:// (mirrors the exact same symptom you describe with exception that it was a new install).


Just a reminder to create a backup archive of your entire installation in webroot, and a SQL dump backup of existing database so you can go back in time if it crashes.

**Comment by Data66PF** [comment]
Are you sure this is the paid client version you are trying to install? Are you sure the domain is listed at http://store.phpfox.com/download for your licensed account? I upgraded sites yesterday and they all went fine.

**Comment by AnthonyKing** [comment]
yes i am sure, the domain is licensed

**Comment by AnthonyKing** [comment]
i upgrade and after the upgrade was finished i tried to view my site but it showed a blank page even when i try to refresh

**Comment by Data66PF** [comment]
enable debug. yoursite.com/PF.Base/tools/debug.php and you'll need your license id and key in order to enable debug. Then go to your site and see what shows for errors.

**Comment by AnthonyKing** [comment]
ok i'll try that

**Comment by AnthonyKing** [comment]
i got this Missing "phpfox.json" file.

**Comment by Data66PF** [comment]
Perhaps you didn't get all of the files uploaded.

**Comment by Data66PF** [comment]
When you downloaded, are you sure you downloaded from the client download and NOT from the github?

**Comment by AnthonyKing** [comment]
yes under license domain, i clicked download

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox-dist try the download from that one.

**Comment by AnthonyKing** [comment]
ok i'll try that one

**Comment by AnthonyKing** [comment]
![screenshot 959](https://cloud.githubusercontent.com/assets/12142143/10077610/51efdb80-62e1-11e5-9145-f3cefa4eab43.png)
i got this error after i tried that

**Comment by Data66PF** [comment]
are you sure the files are uploading fully and you have folder permissions done?

**Comment by AnthonyKing** [comment]
yes i followed http://support.phpfox.com/upgrading-phpfox/manually-upload-files/

**Comment by AnthonyKing** [comment]
i just tried it again still same error
if i install it from the start, and restore my sql back will i have my apps and users back?

**Comment by one44** [comment]
Yes just make sure you save the file directory.

**Comment by AnthonyKing** [comment]
i saved the sql the file directory i did not save

**Comment by AnthonyKing** [comment]
![screenshot 962](https://cloud.githubusercontent.com/assets/12142143/10084190/6bcf1cca-6302-11e5-8d2e-630f4c451cef.png)
tried it again but still the same error

**Comment by Data66PF** [comment]
Is it the error from above the last one you posted as that one doesn't show the error? If so, "failed to open" usually means permission issues or the file isn't there. Did you check the server for that file? Did you double check folder permissions for that specific folder and file? I don't normally have to change any permissions like the one shown though but maybe the server is setting the files to some other type of permission.

**Comment by AnthonyKing** [comment]
yes i checked the file and even the code in the file

**Comment by AnthonyKing** [comment]
i have deleted all the old files in hope of recovering the saved data i have, thank you for your help and attention

**Comment by Gatsby-PF** [comment]
@AnthonyKing:  Just tried and the web update url just redirected to the normal 4.0.7 home page. Does this upgrade process require Composer?  The original installation was the Git-less version.

**Comment by Data66PF** [comment]
I've upgraded several sites using the manual method and have not been running into issues, all on various servers. Are you using https? Try not using https just for the upgrade and see if it works. Then, turn it back on if you had it on before.

**Comment by AnthonyKing** [comment]
I tried to upgrade but after that error, i decided to start from the bottom but now i have a new bug/error
when i clear the cache i shows me a different page, not like when  i was clearing the cache in 4 . 0 7 and i stayed in the admin panel. plus there are # tags when page/website refreshes itself 
![screenshot 977](https://cloud.githubusercontent.com/assets/12142143/10098591/ba2f1ac0-6382-11e5-8edc-1064b9716d9a.png)
![screenshot 978](https://cloud.githubusercontent.com/assets/12142143/10098592/ba48cf6a-6382-11e5-9e41-b35e1fd1f80a.png)
![screenshot 979](https://cloud.githubusercontent.com/assets/12142143/10098593/ba610a6c-6382-11e5-860b-06a34b33a626.png)
![screenshot 980](https://cloud.githubusercontent.com/assets/12142143/10098594/ba74e726-6382-11e5-8378-aaf3830f1584.png)

**Comment by Data66PF** [comment]
Perhaps try another host? Maybe the host doesn't support PHPfox v4. I've installed and upgraded more sites and still not having issues other than one at ipage but that isn't good hosting for this script.

When you upgraded did you follow all of the steps here for after upgrade steps that need to be done? http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view, load a profile pic if you've never joined my site before as that will automatically put you in the verified users to see tutorials.

**Comment by AnthonyKing** [comment]
i have an account at your site, and my host supports phpfox, it's interserver,

**Comment by AnthonyKing** [comment]
i was running 4.0.7 without any problems, i only encountered errors on 4.0.8

**Comment by Gatsby-PF** [comment]
@Data66PF: If the https question was directed to me, see my above post as I was  certainly aware of and allowed for this.  I just did a cold install and selective DB transplant and it is done.

Would be so much easier if a FTP/SSH overwrite based upgrade similar to what WHMCS does, and an supplemental MySQL "Kit" query file (if new tables/fields are associated with the upgrade) that can be executed form phpmyadmin or the like.

@AnthonyKing: try creating a new folder and test database and attempt a new installation to those under http:.  

If that does not work, then try changing the foldername "freedomstand" to "welovethepresident" and see if you have better luck (i.e. your issue in encountering political keyword based interference).

**Comment by Data66PF** [comment]
I'm guessing the renaming to welovethepresident was a joke since PHPfox is based in Sweden and doesn't care whether someone loves the president or not. :)

As for the selective transplant, be very careful as clients that tried that got bitten due to the change from v3 to v4 passwords being bcrypt now and so without running the upgrade routine, that password field wasn't properly done as the routine had to be run to convert it. This 4.0.8 includes a fix for an issue with some upgraded sites that didn't run the routine properly before and so, not running the routine could cause issues with users logging in and password issues. Just a word of caution.

**Comment by AnthonyKing** [comment]
i think maybe the error was caused by trying to upgrade more than once

**Comment by Gatsby-PF** [comment]
In many places in Africa in which Botswana is located (see second image posting), the word freedom has come to be regarded as synonymous with the word "coup". But the domain does not appear to be hosted in Africa as I has assumed it might, neither is it hosted in Sweden.

I also posted in another thread on the MD5 vs Bcrypt issue, however this having been a 4.07 to 4.08 upgrade, that was not thought to be a concern.  The operation went off without issue.

**Comment by Data66PF** [comment]
so is this resolved then?

**Comment by AnthonyKing** [comment]
freedomstand is a page under 1botswana.com, and yes it is resolved, i just want to know what i did wrong so that when  the 4.0.9 comes i could upgrade without any errors

**Comment by Data66PF** [comment]
I've closed this since it is resolved. Perhaps it was an issue when the files were ftp to the server? Not sure.
