### ISSUE TITLE
Installation exiting without completing the v4.0.7

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#541]
I'm sorry to say that, we are not able to fresh install the script in our (bigrock.com) server. I checked all the parameters required which u r said.

Current configuration of My server.
pache Version 2.2.29
PHP Version 5.4.37
MySQL Version 5.6.22-71.0
Architecture x86_64
Operating System linux
Perl Version 5.10.1
Kernel Version 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64
cPanel Pro 1.0 (RC1) 

Yes I confirmed that it is not in mysql strict mode.

after entering the database configuration details starts to creation of tables. Table creation completing then starts to import apps. Starts to import apps then screen land to blank...  

Please let us know how we can rectify the issue.

**Comment by Data66PF** [comment]
I don't see a license on that domain name. Perhaps it wasn't set on your account at http://store.phpfox.com/download . Maybe that is why it won't install perhaps as I'm not having issues installing sites with the client version. Developer version isn't for live installs.
