### ISSUE TITLE
Random Errors when E-Gifts is turned on

### ISSUE THREAD

**Issue by rizwanssyed** [moxi9/phpfox#542]
Hello,
I am having random errors when I turn on E-Gifts. The errors appear on the wall of a staff member but not on regular user' wall. Also when I go to home wall the same errors appear in great numbers. Please address this issue. I am running V4.0.8
![error](https://cloud.githubusercontent.com/assets/14812079/10081299/b242a112-630d-11e5-8254-26e6c5f49fe2.png)

**Comment by Data66PF** [comment]
I'm getting TypeError: $(...).val(...) is undefined for mine. I'll confirm this needs to be looked at.

**Comment by manny12** [comment]
My e-gifts does not show at all. Both for registered users and admin. I did a fresh install of V4.0.8
