### ISSUE TITLE
Blank notification

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#543]
You commentent on my profile but i get this blank notification.

![download](https://cloud.githubusercontent.com/assets/8562514/10089396/61c2f7d0-6323-11e5-8f20-024cae6da247.png)

**Comment by one44** [comment]
I am finding notifications clear and disappear so if you get 2 and click on one the second is gone..

**Comment by Data66PF** [comment]
I'll probably regret this lol, but can you comment on my profile a few times so I can test both things being mentioned?

**Comment by one44** [comment]
No Problem

**Comment by Data66PF** [comment]
Ok it didn't disappear until I clicked on both notifications so I can't confirm that.

As for the first issue above, I didn't get any blank notification but I hadn't done a relationship status. Can someone please comment on the relationship status I just did?

**Comment by one44** [comment]
I am not sure if these are all related but i get message notifications and when I click to see the message the notification is removed but no message opens. Is an intermittent problem as most messages do show.

**Comment by Data66PF** [comment]
Message notifications in email?

**Comment by one44** [comment]
No idea but I would assume it is the internal mail system

**Comment by Ylmzef** [comment]
On email blank too for me..

**Comment by AnthonyKing** [comment]
i would say clear cache, check counters and missing settings/files

**Comment by Ylmzef** [comment]
it's from community. :smile:

**Comment by Ylmzef** [comment]
![download](https://cloud.githubusercontent.com/assets/8562514/10115448/3c932594-6408-11e5-9b1e-d12d3d1bb012.png)

**Comment by Data66PF** [comment]
I just updated my status, http://community.phpfox.com/profile-data66/ , and changed my notifications so I would get an email. Would someone please go comment on it so I can see the email?

**Comment by Ylmzef** [comment]
I can't because you removed me as friend :smile:

**Comment by Data66PF** [comment]
I don't recall removing you. Feel free to friend me and we can test.

**Comment by Data66PF** [comment]
Cannot reproduce at the community
![relat stat](https://cloud.githubusercontent.com/assets/6908282/10305375/e0a873ea-6bed-11e5-97fb-24726070de70.png)

**Comment by Ylmzef** [comment]
What was your first changed for relationship?

**Comment by Data66PF** [comment]
That was my first one. My other user had not set a relationship before that one.

**Comment by Ylmzef** [comment]
It can be type of profile update..

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-58 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.

**Comment by Data66PF** [comment]
No, it was already marked fixed.
