### ISSUE TITLE
Compose message privacy issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#544]
Searching username showing all site users names not only friends on compose new message.

**Comment by Data66PF** [comment]
confirmed at phpfox community.

**Comment by Data66PF** [comment]
Marked critical as it impacts site privacy and this is pretty important to all sites.

**Comment by Gatsby-PF** [comment]
Is it possible that when certain issues such as this are cleared up, that a url to the corrective code changes can be posted so the affected files related to issues such as this can be differentially patched as corrections are made without having to wait for the release of the next minor branch?

**Comment by Data66PF** [comment]
It is always posted when he closes it.

**Comment by Data66PF** [comment]
For those of you using V4, please go in user group settings and set the Mail setting for Can only send messages to Friends to True. This really should automatically be set with the site default at a friends only community, but for some reason, it does not respect that setting. this is a good solution for now though.
