### ISSUE TITLE
Blocks on pages index

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#545]
Blocks are not showing on pages.index

**Comment by Data66PF** [comment]
I can confirm this. I can't put a block on pages.index but I can in other areas of the site. V4.0.8.

**Comment by AnthonyKing** [comment]
share a screenshot

**Comment by Data66PF** [comment]
We don't need a screenshot. I've confirmed the bug. There is no screenshot as there is no block appearing on the page so there isn't anything to take a screen shot of.

**Comment by AnthonyKing** [comment]
it wont hurt if i try to help, i am trying to understand maybe there is a block in mine or i missed this bug somehow

**Comment by one44** [comment]
![2015-09-26 05_56_26-program manager](https://cloud.githubusercontent.com/assets/13656046/10115728/af5e6b0a-6413-11e5-9c1f-abb6185020c8.png)

**Comment by AnthonyKing** [comment]
ok that one i can not try to fix, i thought it was on your site

**Comment by RaymondBenc** [comment]
This is currently theme based. Our default theme has this area hidden, I'll check why and see if we can remove it.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8

**Comment by one44** [comment]
Fixed works fine.
