### ISSUE TITLE
Mutual Friends Pop Up box 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#546]
when we click on Mutual Friend link a pop up box open.in this pop up user list is incomplete and profile pic is missing.
![mutual friend issue](https://cloud.githubusercontent.com/assets/13433124/10098928/c9a86aae-63a2-11e5-8e6c-b57c5baa8088.png)
![mutual friend missing pic and other](https://cloud.githubusercontent.com/assets/13433124/10098933/cf71dc90-63a2-11e5-9cb5-5e91cb704627.png)

**Comment by Data66PF** [comment]
I think it has a limit to limit the load. I'll have to test this tomorrow when I'm on.

**Comment by Data66PF** [comment]
I can confirm an issue with the popup when hovering over the username in the feed for example. It doesn't show the images and doesn't show all 7 (if there were 7) for example. Tested at the community with win 10 and firefox latest.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-27 *
