### ISSUE TITLE
members.index wall

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#547]
On this wall the members friends and pages groups are shown but it just keeps adding as new members and new pages are joined. This is either a bug or design omission as in any social site a member can have over 100 friends and belong to many groups, It needs cleaning up.

**Comment by Data66PF** [comment]
What do you mean? Do you mean profile.index? I checked a few and the block of friends is restricted to show only a certain amount and then you can click to see the rest.

The pages one, I've not see one with enough to show an issue but I do recall a bug already posted for the pages block. Perhaps you mean that bug.

**Comment by one44** [comment]
I mean members .index page http://one44.net/Daddy_Peter/  I see the friends is limited maybe there is a setting somewhere as I have 15 showing but I have 27 lines with three in a line of the pages on my site on my index page as admin and a member of most pages and groups.

**Comment by Data66PF** [comment]
There is no members. index page though. Do you mean user/browse, profile.index, pages.index, or something else?

**Comment by one44** [comment]
The page you go to when you click the members avatar

**Comment by Data66PF** [comment]
profile.index as I had first said. Ok I don't see any issues with the friends block. For the pages block, do you mean this issue? https://github.com/moxi9/phpfox/issues/425 if so then this would be a duplicate.

**Comment by one44** [comment]
Same issue yes I will close this one

**Comment by Data66PF** [comment]
Thanks and we do appreciate all the help with bugs. I know I don't say it often but I get so busy with all the things I do. Anyway, thanks.
