### ISSUE TITLE
Friends (X) block in profile page displaying "Frien#"

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#548]
The word Friends is being eclipsed by the variable showing number of friends in the profile page so that it displays as Frien# instead of Friends #.  Using Firefox 41 over Windows 7.

**Comment by Gatsby-PF** [comment]
I need to clarify that this affects the block to the right of the profile, not the equivalent in the profile navigation bar

**Comment by Data66PF** [comment]
Screen shot would be helpful. You can blur out names.
