### ISSUE TITLE
"Show users online status when hovering over avatar" setting does not work

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#549]
When setting the 

Display User Online Status

to Yes

(setting quote: This produces an "is Online" message when the avatar is hovered over),

hovering over the users avatar, only pops up the users name (which is redundant and useless because username is already part the avatar), but online status does not display when user is known to be online.

The friends online block in the Home page does accurately detect and display friend online.

**Comment by Data66PF** [comment]
The way this worked is that the only time Online showed was when the avatar was hovered over in the recent logins block. Checking my v3 site, that is how it works. It also shows there on the user profile but that part was removed in v4 so I think this is working as designed but I'll test further on my dev site.

**Comment by Gatsby-PF** [comment]
It wouldn't be a bad idea to consider bringing this option back. For instance, it is much better to poke someone when you know they are online, then an offline poke.

I think it is closer to the mark that it no longer worked after changes were made in V4, and no one wanted to fix it.  It seems ridiculous to include a select option when it only pertains to the most limited, remotely usable functionality as you describe.

Either the option should be fixed to include hovering over profile and feed area avatar (which additionally would have to respect the users invisibility privacy setting), or if not, it should be removed as a select option altogether for the reason mentioned above.

**Comment by Data66PF** [comment]
Confirmed that the online is not showing. v4.0.8
