### ISSUE TITLE
[Adsense] Only shows on reload

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#550]
In relation to: https://github.com/moxi9/phpfox/issues/118

We are indeed on 4.0.7, did all the proper upgrade steps, including clearing cache. We still need to F5 or refresh each page before the adsense will show up. I didn't notice any mention of this in the 4.0.7 update, unless I missed it, but I do not think it was fixed yet, at least for us.

Opened this new bug as I'm not sure notifications are seen now that it was closed in the other one.

Thanks. :)

**Comment by Ylmzef** [comment]
Same issue!

**Comment by Data66PF** [comment]
Please ensure you are on 4.0.8. I cannot reproduce this on my test site with latest Google async ad.

**Comment by GloriousKoch** [comment]
I shall have our dev update to 4.0.8 soon and reply back our results. :)

**Comment by Data66PF** [comment]
Cannot reproduce on v4.0.8. I enabled google ad via a sitewide block. I view the site and it immediately shows in firefox and I don't have any ad blocker enabled. I am testing with default Neutron theme, no edits done.

I browsed around the site and each page I opened had the ad showing up immediately.
I am using the new google async ad
```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- site -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="mypub"
     data-ad-slot="myid"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

**Comment by WebSurge** [comment]
I am on v4.0.8 have it on sidewide with v4.0.8 and get this error: Uncaught TypeError: e.data.indexOf is not a function

**Comment by Data66PF** [comment]
What are you making? Are you making a google block ad with the new code from google? You need to get the newest ad code. You also need to make sure your site is fully accessible to guests as google ads are guests and they don't allow their ads behind closed sites unless you do special stuff for that. Fern used to have an add on for it but he's not around any longer.

**Comment by WebSurge** [comment]
We have fixed that error it came down to cometchat. 

Majority of the pages load fine the first time, but there are pages that we need to reload a second time in order to see the ads for example the music page.

**Comment by Data66PF** [comment]
I still cannot reproduce this for areas that allow the ads to display, including music page. V4.0.9 tested with default theme and no add ons. Using nginx server by phpfoxsolutions with all of the requirements. Tested with chrome and no ad blockers enabled.

**Comment by GloriousKoch** [comment]
We switched to the async code on 4.0.8 and ads are showing as intended now. Thanks. :)

**Comment by sandeeprvarma** [comment]
Facing this issue with v4.1.2. Added js code in a script tag on a page which require a page reload to create dynamic iframe.
