### ISSUE TITLE
share error / bug

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#551]
i enabled the twitter share option and now the share option is displayed ontop of the status update share status button, plus i also enable share on facebook and gmail but they are not displayed on the share option
![screenshot 1004](https://cloud.githubusercontent.com/assets/12142143/10113058/f4f18e46-63e0-11e5-83ca-f5ee89b037fc.png)

**Comment by Data66PF** [comment]
These are no longer supported in v4 but I see that we can still get to the settings. Will confirm so we can disable the access to the unsupported settings.

**Comment by AnthonyKing** [comment]
thank you,

**Comment by Data66PF** [comment]
You can use my bufferapp for posting to social media if you want. I use it on my sites but mine are v3 so I use the v3 version.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by AnthonyKing** [comment]
thank you.

**Comment by Data66PF** [comment]
Fixed 4.0.10
