### ISSUE TITLE
 refresh not working #468 

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#552]
Refresh when joining pages and groups is still an Issue. This still same on community site.

**Comment by Data66PF** [comment]
please next time link it inside the comment as then it creates a link :) #468

**Comment by one44** [comment]
ok sorry

**Comment by Data66PF** [comment]
just tested at the community using win 10 and firefox latest. I don't have any issue to Like a page and immediately post a comment. It worked for my test.

**Comment by one44** [comment]
check groups and pages also you will see the join tag disappears but as there is no refresh it looks as if you have not joined.

**Comment by Data66PF** [comment]
Ok I see the issue in a group. Odd, it didn't happen when I tested a page. 

1. Join a group
2. Try to post a status to the group feed without refreshing the page.

You will note that when you join the group, you don't show in the Members block.
You also can't share to the page as it looks like it eats the comment (status post)

http://community.phpfox.com/pages/601/

**Comment by majdmike** [comment]
When you JOIN a group the page doesn't refresh and the issue appears but when you UNJOIN the group the page refreshes automatically and everything appears fine. Meaning half the process is correct and maybe you only need to add the same refresh code to you JOIN that you have under the UNJOIN

**Comment by Data66PF** [comment]
This is already marked a bug.

**Comment by SalmanKhan86** [comment]
same issue in v4.0.8. looks like not fixed yet in v 4.0.8.
when i like page it does't refresh and like disappear.i tested it on Windows 7 both Chrome and Mozilla having same problem

![page like not refresh](https://cloud.githubusercontent.com/assets/13433124/10475825/73857ef6-7265-11e5-9289-d5849ba83839.png)
