### ISSUE TITLE
Feeds update issue after friend remove

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#553]
When i removed any friend on my profile the "is now friends with" feed post removing on new feed but still showing on both profiles.

**Comment by AnthonyKing** [comment]
wait you removed someone as a friend, but you can still see their feed?

is it old feed or recently posted status

**Comment by Data66PF** [comment]
@AnthonyKing he means the message in the feeds for this person "is now friends with" that person. 

@Ylmzef when you clear cache does the message go away?

**Comment by Ylmzef** [comment]
I cleared cache and updated all the counters but it's still there.

**Comment by Data66PF** [comment]
Can you explain a bit? Do you mean it removes from the main feed but still shows on the profile?

**Comment by Ylmzef** [comment]
Yes

**Comment by Data66PF** [comment]
I can confirm that the feed remains on the profile but I think this is how it's designed as the profile feed is simply a feed of all activity for that person. At one time, that person became friends with someone. The only way to delete the feed item is to manually remove it. 

I'll mark it a bug but I think it's working as designed. However, a core developer will determine that.
