### ISSUE TITLE
Uppercase and lowercase issue for hastags

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#554]
When you click hastags on trendig hastags block all hastags showin lowercase.
But when you click on newsfeed it's showing as posted.
Uppercase letters are very important for hastags..

https://github.com/moxi9/phpfox/issues/331#issuecomment-143393141

**Comment by Data66PF** [comment]
I cannot reproduce this at the community. I see a cap in the trending block and I also made a Hello tag to show in the feed. Both show with caps.
![hashtag1](https://cloud.githubusercontent.com/assets/6908282/10189712/06111a90-6736-11e5-8c0b-28aa5544249f.png)
![hashtag2](https://cloud.githubusercontent.com/assets/6908282/10189715/07a011c2-6736-11e5-9029-5662980335e0.png)
Please provide further steps to reproduce it.

**Comment by Ylmzef** [comment]
Click the links on trending topics.
Not on feeds.

**Comment by majdmike** [comment]
Can't repeat it either
![hashtag repeating](https://cloud.githubusercontent.com/assets/14811094/10238320/fcd389c0-688b-11e5-85e6-7ca6ffe89bea.jpg)

**Comment by Ylmzef** [comment]
Like as i said you need click on Trending Topics block not on newsfeeds.
http://community.phpfox.com/hashtag/helloworld/

**Comment by Data66PF** [comment]
I can confirm this at the community when clicking the tag in the tab block. I don't know if this is a bug or improvement but will mark a bug for a core developer to check.

**Comment by Ylmzef** [comment]
It's fixed on v4.0.9 you can mark this ticket as fixed and closed.

**Comment by Data66PF** [comment]
Thank you for letting us know. Please note that a ticket creator can also close a ticket. :)

**Comment by Ylmzef** [comment]
I know but you need mark as fixed i think?

**Comment by Data66PF** [comment]
No they mark as fixed if they put an actual bug fix. It is closed out if the issue is resolved.
