### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#555]
Error:    Captcha failed. Try again.

when we sign up we receive error in app reCAPTCHA 

when we disable reCAPTCHA Enabled>  signup successful

**Comment by AnthonyKing** [comment]
did you enter the keys correctly, and the settings at google?

**Comment by muhammadnaeemahsan** [comment]
YES 
enter the keys correctly

i am not robot > verified and next page show and then error

**Comment by muhammadnaeemahsan** [comment]
please see in www.todaylogin.com

**Comment by AnthonyKing** [comment]
did you disable it?
![screenshot 1012](https://cloud.githubusercontent.com/assets/12142143/10141754/885c0c54-660e-11e5-9687-430ad11f5792.png)
![Uploading Screenshot (1013).png…]()

**Comment by muhammadnaeemahsan** [comment]
yes due to user difficulties. i disables

**Comment by AnthonyKing** [comment]
yeah i see why, because mine is also giving me a problem, i checked all my details at google and checked my keys, but when i click it, it says it failed
