### ISSUE TITLE
Removed user's message notification issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#556]
I sended a message to anohter user.
Than i removed message sender user on site wihtout reading the message.
But i see still the message notification on left menu i click on message button on left menu the notification removing but after 5min orso it's appearing again.

**Comment by Data66PF** [comment]
Are you going to yoursite.com/mail and clicking the Mark all Read?

**Comment by Ylmzef** [comment]
After that the notification removed but it's not a solution for not expert site users like as me and others.
This same as this ticket https://github.com/moxi9/phpfox/issues/553 
The system not cleare sql after removing users etc.

**Comment by Data66PF** [comment]
I think this is how it's designed as the message was sent so the notification was already sent so it can't delete the notification in your account as it is your notification. The notification doesn't belong to the other user, it belongs to you. I'll ask what they think though.

**Comment by Ylmzef** [comment]
It's nothing something else from database inflate..

**Comment by RaymondBenc** [comment]
Is the issue here that if I send a message to User 1 and then after remove User 1 from the site the notification count is still there?

**Comment by Ylmzef** [comment]
Yes

**Comment by Ylmzef** [comment]
Still waiting for this issue..

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-103 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.
