### ISSUE TITLE
No option for theme flavor removing

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#557]
I can't find any option to removing theme flavors.

**Comment by AnthonyKing** [comment]
just create a new 1, same name as the 1 u want remove

**Comment by Ylmzef** [comment]
After that? I have still the flabor?
It's not a solution.

**Comment by Data66PF** [comment]
Confirmed. A button to remove flavor is needed.

**Comment by one44** [comment]
It was there in 4.0.5 I think
