### ISSUE TITLE
Debug mode issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#558]
When enabling debug mode site content (i think mysql part) loading very very slowy!
v4.0.8
Upgraded site
Windows 10
Chrome 45

**Comment by Data66PF** [comment]
Debug mode is meant only to check the site for issues and is best enabled during slow traffic times and then disabled right after debugging is done. It is not advised to leave debug enabled.

**Comment by Ylmzef** [comment]
I don't leave it enabled.
I enabled it for checking somethings but it can't be done due the slowy loading time.
