### ISSUE TITLE
Widgets Not Working on Groups

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#560]
Hello,

I was testing my community and noticed that when we click at widter inside the page management area, we are redirected to the landing page as there were no option to add a widget.

I think that since widget always cause some problem this feature was removed, however the link to him still in pages.

**Comment by Data66PF** [comment]
I cannot reproduce any issue with v4.0.8 on my test site using default Neutron theme. My widget adds just fine.
