### ISSUE TITLE
View This Page Overlap

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#561]
In the page management there is a "view this page" with an arrow icon right above the widget. The icon is in the right place, however the phrase is being displayed  displayed at left under the leftsidebar.

**Comment by Data66PF** [comment]
Please always post screen shots of things like this.

**Comment by Data66PF** [comment]
I see no view this page icon. Are you testing at the community? If so, please post a screenshot as I can't find what you are posting about.
