### ISSUE TITLE
Bug in Page editor - duplication of meta content in blogs

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#562]
Hi,
I tried to edit my "meta Title" and other meta content of one of my blog by visiting "page editor" by right bottom corner button. It edited successfully but it overwritten  the same "meta title " , meta keywords n all to all other blogs. 
Means whatever the recent edit i save in meta content of any blog that overwritten in all other blogs automatically. which gives same meta title, description and keywords to all of the blogs.  It means spoiled seo of site and waste of content.

Please rectify it ASAP and if u get any solution then please tell it on the spot , dont wait for any update launch as it's harming my site reputation alot in terms of google.

**Comment by Data66PF** [comment]
I can confirm an issue with this that needs further testing by a core developer. V4.0.8 FF test.

**Comment by RaymondBenc** [comment]
Are you trying to edit the meta data of a specific blog and not just the general blog page?

**Comment by shakti7188** [comment]
yes, i m sure that i m trying to edit meta data of a specific blog and not of main blog page.

**Comment by shakti7188** [comment]
guys, have you removed this bug ?

**Comment by RaymondBenc** [comment]
Fixed for next build.

Patch https://github.com/moxi9/phpfox/commit/618bfb562cb1d31c72a95a8d5fac73edb906820f

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-11 *
