### ISSUE TITLE
Add new admin for a page is not working

### ISSUE THREAD

**Issue by mackaby** [moxi9/phpfox#563]
Go to page / edit / admins

When clicking the search field, it's not possible to enter any name to add as admin.

**Comment by Data66PF** [comment]
I cannot reproduce this as I just had to add one to test another bug. Worked fine for me in win 10, FF browser.

**Comment by mackaby** [comment]
Actually, this seem to only be an issue if you are not already a "friend"
with the person you want to assign as admin. It might be more of a use case
than a bug.

**Comment by Data66PF** [comment]
Ok this is working as designed. Please post a feature request at the PHPfox community if you want this feature and perhaps a third party developer can make an app for it.
