### ISSUE TITLE
Approving new page/group members not working in Firefox

### ISSUE THREAD

**Issue by mackaby** [moxi9/phpfox#564]
Go to - page - approve new member (when a page is requiring membership and a user has joined).

Overlay for selecting members to approve is missing in Firefox. The outcome is that admin can't manage applications.

**Comment by Data66PF** [comment]
I see the checkbox in FF and Chrome but I don't see anything to actually approve the user. Confirmed v4.0.8

**Comment by mackaby** [comment]
Are you using windows or mac? I checked again and I still can't see the overlay in FF / Mac (haven't checked FF / Windows)

**Comment by Data66PF** [comment]
As I marked this a confirmed bug, I am saying that I can confirm the issue. :)

**Comment by RaymondBenc** [comment]
I'm on FF Mac and I see the overlay as long as I hover over the users image. When I click the checkbox, using the default theme I get the "With Selected: (1)" activated, from where I can approve or deny the user.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed 4.0.10
