### ISSUE TITLE
video app not working

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#566]
i was trying to use the video app to share videos, but i get errors when i try to share and view the video, i had to unistalll and delete the video menu. please help me solve this issue.
![screenshot 1019](https://cloud.githubusercontent.com/assets/12142143/10173022/88f87f9c-66e2-11e5-9979-7f548fe2200b.png)
![screenshot 1020](https://cloud.githubusercontent.com/assets/12142143/10173023/89113d66-66e2-11e5-823b-cd661f4da35d.png)
![screenshot 1021](https://cloud.githubusercontent.com/assets/12142143/10173024/8920463a-66e2-11e5-8776-1d2e0c3e2a05.png)
![screenshot 1022](https://cloud.githubusercontent.com/assets/12142143/10173025/89338cfe-66e2-11e5-8fa0-16f6423cec8a.png)
![screenshot 1023](https://cloud.githubusercontent.com/assets/12142143/10173026/894c4c94-66e2-11e5-9db2-15f46fa79625.png)
![screenshot 1024](https://cloud.githubusercontent.com/assets/12142143/10173027/895b192c-66e2-11e5-8b75-289baed6effb.png)
![screenshot 1025](https://cloud.githubusercontent.com/assets/12142143/10173028/89929c6c-66e2-11e5-9ad7-bf726233b61d.png)
![screenshot 1026](https://cloud.githubusercontent.com/assets/12142143/10173029/89ab9e9c-66e2-11e5-87d5-d38ed2863103.png)

**Comment by Data66PF** [comment]
Video app issues are not posted in this area as this is only for the default PHPfox. Please post issues with apps in their issue trackers.  https://github.com/moxi9/phpfox-videofeed
