### ISSUE TITLE
Language Import 

### ISSUE THREAD

**Issue by h22mike** [moxi9/phpfox#567]
When I try to import language it says Successfully installed language pack, but it will never appear in Language menu.

**Comment by Data66PF** [comment]
If you are using an app, you would need to let us know. If you are trying to manually import, let us know and please make sure you are using the v4.0.8 version.

**Comment by h22mike** [comment]
Yeah. Updated to 4.0.8 using manual importing. I got both v4 language packs and v3 language packs, none of them work. Does v3 language pack work on v4 at all?

**Comment by Data66PF** [comment]
You can't use V3 packs. As for V4, you must install them from the store which is to prevent piracy.

**Comment by Data66PF** [comment]
I don't see any issue with the v4 packs in the store and tested them all.
