### ISSUE TITLE
Facebook Open graph  tags problem

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#568]
When We Share our Phpfox community root url to Facebook it don't show any feature Image . Facebook debugger shows some warnings .. here is the results which facebook debugger shows when we try to open phpfox community website.
https://developers.facebook.com/tools/debug/og/object?q=community.phpfox.com

**Comment by Data66PF** [comment]
The facebook share feature is not available in V4. You can use the Buffer App which is in the store if you want to share to facebook.
