### ISSUE TITLE
I can't upload any video in that module

### ISSUE THREAD

**Issue by stultitia1** [moxi9/phpfox#57]
I was trying upload a youtube video in the video module, but when I paste the link and do it click Add, appears a blank page with this link domain_name/index.php?do=/video/add/url/ and does nothing.

That's worried me because my enterprise bought two licenses of phpfox and that module was working right and and suddenly stopped working.

Thanks

**Comment by RaymondBenc** [comment]
Are you able to reproduce this on our live community? 

In regards to the **video module** is this the [app](http://store.phpfox.com/product/778/video-feed) you are referring to?

**Comment by Data66PF** [comment]
Is this one resolved for you with version 4.0.3? Note that there is no upload video feature in V4 so if you meant that, then you would want to wait for an app for uploading videos to be available in the store.

**Comment by Data66PF** [comment]
closed due to no response

**Comment by aliraza170** [comment]
anyone can help ? When I upload video it shows us empty page 

https://www.funkodia.com/index.php?do=/video/add/url/

**Comment by neil96** [comment]
Hi @aliraza170 ,

You can ask question on our [community](https://community.phpfox.com/forum/) for help.

Regards.
