### ISSUE TITLE
Block People (carried over from support forum)

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#570]
Reference the thread on the support forum.
http://community.phpfox.com/forum/thread/52810/block-people/

It has been agreed that there is a missing feature that allows users the ability to block unwanted users (i.e. Nigerian scam artists, pervy perps, ISIS recruiters) etc....

On the pre-sales features page:
http://www.phpfox.com/features/

Under  "Account Privacy" menu selection, it was represented that, quote:

"We give the ability for your users to block other users on the site. They can manage these users from their "Privacy Settings" page and remove them at anytime. "

The "Blocked Users" tab under privacy settings is there, however, I am at a loss to explain to others users why there is a blocklist status area with no ability to add users.

This is a very important feature as it is a users only defense, and to raise the importance of that point it was noted that one of the senior phpFox programmers  (who will remain unnamed to protect his privacy) uses a password to protect messaging access to himself. No complaints to same, he is doing a great job on a great product.

**Comment by Data66PF** [comment]
I'm not sure what you mean about the password to protect access to himself. I don't know of anything our core developer is using to protect access to himself at the community. 

As for the blocking issues, I can confirm that I can't see the Block User button now at the community and at my test site.

**Comment by Gatsby-PF** [comment]
Thanks for flagging this bug Data66PF.

I attempted to contact him regarding a possible security issue.  Had I not been blocked by a password when attempting to convey the issue privately by clicking on the messaging link in his profile, I would not have had to resort to lesser secure notification by posting the advisory in his profile page yesterday.

**Comment by Data66PF** [comment]
Most likely, he's disabled messaging in his privacy settings.

**Comment by Data66PF** [comment]
As for the security issue, use hello@phpfox.com to send a ticket to the sales desk with Security Issue as the reference please.

**Comment by Data66PF** [comment]
Also note that you can always contact data66 at the community or at ScriptTechs to report stuff if needed.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
