### ISSUE TITLE
Delete Original Photo After Resize (V4) 

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#571]
Maybe I misunderstand. I thought this setting would be awesome but it seems like it is not doing what I assume would be done and that is saving space. 

So I changed a profile picture after I changed the setting "Delete Original Photo After Resize". I also went to the setting and did unlimited image size (0). 

The image uploaded was 3.95mb and was 3648 x 2736 
and in this folder PF.Base/file/pic/photo the following was added. 

9fc3d7152ba9336a670e36d0ed79bc43.jpg 3.95mb 
9fc3d7152ba9336a670e36d0ed79bc43_100.jpg 3kb 
9fc3d7152ba9336a670e36d0ed79bc43_1024.jpg 79kb 
9fc3d7152ba9336a670e36d0ed79bc43_150.jpg 4kb 
9fc3d7152ba9336a670e36d0ed79bc43_240.jpg 8kb 
9fc3d7152ba9336a670e36d0ed79bc43_500.jpg 26kb 
9fc3d7152ba9336a670e36d0ed79bc43_75.jpg 2kb 

So it looks like it renamed the original photo and it may have deleted the original image/name it still kept the renamed 3.95mb photo...even though it won't be used. 

So my point of view of this is it is a bug or I don't understand their description. 

"When a user uploads an image the site will create thumbnails of this image, and uses the thumbnails around the site. 
If you enable this setting the original file (that the user uploaded) will be deleted after the thumbnails have been created. " 

I think Data checked out the photo module as well and said it didn't work.

"Please try it with a photo in the photo section as this is for photos. " by Data
"ok I tested and it's not working now. Please post the bug at github. " by Data

**Comment by Data66PF** [comment]
I can confirm that the setting is not working for photos loaded. I tested a photo in the photo section and the original is still on the server. This used to work.

**Comment by RaymondBenc** [comment]
I tested to enable the feature and it deleted the original photo for me. I checked the code and it takes CDN and image watermarking. Are any of those options enabled?

**Comment by Data66PF** [comment]
For my tests, I'm not using the setting to delete original after loading to CDN if you mean that. I'm using the setting that was made a few years back in response to client requests to delete original photo after upload. For my tests, the original is still there. Are you saying that now, the setting doesn't work with normal uploading and only works with CDN?

**Comment by RaymondBenc** [comment]
No. I have CDN disabled. Its a stock install. I enabled the global setting **Delete Original Photo After Resize**. Then tested to upload a new image and it deleted the original photo.

**Comment by Data66PF** [comment]
This is odd. On my new server with nginx, this is working. On my old server it wasn't working. I don't know how to explain why.

**Comment by PhpFoxJohnJr** [comment]
I just upgraded my server as well yesterday...did a fresh install and it has nginx on it already...don't know if it is correct since it was already on it.  But, I enabled the setting settings/photo/settings/  -Delete Original Photo After Resize to YES.

Like I said above when you go to that folder right after I upload the new profile image...I get seven images...and the top one (although renamed...has same size as the original - which I assumed would be this larger size image would be deleted).  How many images are showing up in that folder when you change a profile image.  It should only be 6 images...the ones with the size after the underscore...right?

**Comment by PhpFoxJohnJr** [comment]
Oh yeah...I have no cdn or anything fancy yet :)   just a new SSD with more Ram

**Comment by Data66PF** [comment]
I don't believe this setting was ever for profile images. I believe it was for photos. We had a discussion in the old forum about making a setting for profile images but at the time, could get no feedback from clients for how they really wanted it to work for profiles so a setting was never made.

**Comment by PhpFoxJohnJr** [comment]
WOW!  never knew that....will check on photos.  The first time...I was on the photos...this time I just happened to be being the profile image thing.

Though you would think it would work there...as phones are getting better and better and images taking on phones these days can give prints the size of 4 feet by 8 feet which as you know the web only needs a 1 meg camera really.  But we can't change the phones and we can't expect people to go home and resize their image before posting.  I did not have an issue before when I had a 1tb hard drive but now with the ssd I only have 250 gigs...and it could become an issue....just giving thoughts here...not actually worried or mad :)

**Comment by Data66PF** [comment]
As this issue is not for the main photo section but for profile photos, this is something we never changed back in v3 as the core developers could not get feedback for how clients wanted it for profile pics. Changing this would be an enhancement or feature request so will let a core developer determine if it will be enhanced.

**Comment by PhpFoxJohnJr** [comment]
I understand closing as this issue is small compared to the amount of bugs this version has.  But honestly there would be no reason not to have this.  Like asking people since you have a front windshield wiper on your car and it works great but we could not get enough feedback on putting a back windshield wiper.

**Comment by Data66PF** [comment]
That is not the issue. It is a functional issue. If we do this one way, it will make it so that users cannot get their profile photos if they want to re-use them. 

Actually, I see that the option to choose profile photos from already uploaded photos has been removed anyway so that point is now moot as we don't have that option. 

I'll reopen this to be looked at improving since users now cannot select from already uploaded photos as their profile photo.

**Comment by Data66PF** [comment]
Marking a bug for us to check the profile photos to ensure they delete the orignal from server if the option to delete original is selected.

**Comment by PhpFoxJohnJr** [comment]
Not sure what you found now, but as I tell my kids "You need to start thinking with brains"...speaking to the developers of course.  I look at my galaxy s5 which is already two years old and the minimum picture size is 2.4 meg and the largest is 16 meg.  Most people are just going to grab the highest since even then you can have 1,000's of pictures on your phone with a cheap $10 sd card of 8 gigs.  So if you looked at my example you would see it generates enough images (even a 1024 pixel wide) to supply anyone with the images the need.  So now deleting the original on anything seems kinda of dumb to me.  Second, with ram costing so much and phpfox no as fast as we always hope...many have started using SSD and even a 256 GB is costing over $40 per month...so as you can see any time you can reduce space it is a benefit for program and not just a functional issue of the program.  But like I said before...we have bigger bugs to fry :)

**Comment by Data66PF** [comment]
Status on this @RaymondBenc ?

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#20
