### ISSUE TITLE
Timeline not responsive due to failing image resizing

### ISSUE THREAD

**Issue by HuseyinOezoguz** [moxi9/phpfox#574]
Some images in the timeline are not resized when you use mobiles. That end in breaking responsiveness: You have to scroll the horizontal bar. And so the UX with mobile on PHPFox is broken.
![imageresizing](https://cloud.githubusercontent.com/assets/14735486/10235085/814953c6-6899-11e5-844b-6fe8a6a0ca87.jpg)

**Comment by AnthonyKing** [comment]
i just checked http://community.phpfox.com/photo/ the responsiveness is working, is that your own site ?

**Comment by HuseyinOezoguz** [comment]
No, its on the community page, but not in the photos, but here: http://community.phpfox.com/ (timeline). I just uploaded a big-sized image. Try it out with scaling your browser window, that is the result here (with Chrome and Firefox):

![notresizing](https://cloud.githubusercontent.com/assets/14735486/10247709/36e4c2b6-691b-11e5-9fbb-474a6bb98963.jpg)

It just do not resize, so the size breaks the responsiveness.

**Comment by AnthonyKing** [comment]
i checked your profile, it was responsive and the picture did not lose quality, which web browser are you using, i'm using google chrome

**Comment by HuseyinOezoguz** [comment]
Not my profile, just the timeline, when you press "Home" left. I use Google Chrome aswell, but the same issue arises with Mozilla Firefox.

**Comment by AnthonyKing** [comment]
ok i see it now,

**Comment by Data66PF** [comment]
Please note that it is the Feed. Timeline is something on profiles that we used to have but do not have in v4. Just a terminology difference. For developers looking at this bug, look in the main feed and disregard references to "timeline".

**Comment by HuseyinOezoguz** [comment]
Ah ok, I did not know this terminology. Yes, I mean that "feed". I think its just a resizin issue.

**Comment by Data66PF** [comment]
Always state your device and os, and also browser. I cannot reproduce any issue with the images in the main feed when visiting with an iPhone 5c on default safari browser, iOS version 9.0.2

**Comment by SalmanKhan86** [comment]
i have tested it with Android OS with chrome browser.I image is looking fine but Thread link word is cut off.
![screenshot_2015-10-11-18-04-13](https://cloud.githubusercontent.com/assets/13433124/10416794/e2d66f2e-7042-11e5-81ec-a215426a3159.png)

**Comment by Data66PF** [comment]
I'm able to reproduce this on my iPhone 5c now, including the cut off text.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by AnthonyKing** [comment]
i think u need to check the bootstrap code.

**Comment by Data66PF** [comment]
Fixed 4.0.10
