### ISSUE TITLE
Tagging a friend

### ISSUE THREAD

**Issue by majdmike** [moxi9/phpfox#575]
Dear all, I'm running V4.08 PF
New issue with tagging a friend from anywhere on the website. Whenever anyone tags me in a post (ex @ME), I do not get any notifications on the notifications bar or emails telling me to check it out. Their is no way for me to find the tag except to look on the fee.
Second:
Can it be done to add a button or a block on the user profiles to checkout tags that the user is tagged in by other users such as posts, pictures and videos and provide the user with privacy options for that?

Thank you
@Data66PF 
@RaymondBenc 
MZ

**Comment by AnthonyKing** [comment]
I think the button / block is not needed since you can see the notifications and you can edit privacy settings i you do not want people to tag. i also think that the block or button or setting needed is the one you can categorize people in different groups, so that you can say for example myphp friends can tag me everywhere, while my css friends can tag me in only photos and the rest of the community can tag me in status update i approve to be tagged on

**Comment by majdmike** [comment]
I like that as well but I see a problem with the notification tracking and that is if you clear your notification then it's gone. So if we create a page that looks similar to let's say the hashtag pages (the page that appears when you click the hashtag with all hashtag posted in the pass) and link that to a menu for both personal profile and friend's profile and give the ability to control it as in to show or hide it.

**Comment by AnthonyKing** [comment]
yes that page would be very useful

**Comment by Data66PF** [comment]
Feature requests are not accepted in the bug tracker. Only bugs are for this area please. Post feature requests in the community where there is a section for it.

In regards to tags, they must be on specific items that make it into the feed. It cannot be status posts and things like that. Please see this bug https://github.com/moxi9/phpfox/issues/334
Was that how you were testing?

**Comment by majdmike** [comment]
@data66pf 
That is a very similar or maybe the same bug #334. What my testing process was to make a new post and @ the user in it. 
I don't know of any other way to tag a person.

**Comment by Data66PF** [comment]
The way it was fixed, as mentioned in the other report, is that when you go to an item such as a photo and tag a user in it, it works and sends a notification. Anything else would need a customization.
