### ISSUE TITLE
HashTag search

### ISSUE THREAD

**Issue by majdmike** [moxi9/phpfox#576]
Dear all, I'm running V4.08 PF
A new issue, searching a hashtag in the search bar. When posting a post and going to the search bar and search the hash nothing appears except for "No search results found."
Clicking on the hash it works fine, as in when you click a hashtag "#helloWorld" all the pass tags appear but when searching the "#helloWorld" nothing appears. 
As you can see I posted here:
![hashtag repeating](https://cloud.githubusercontent.com/assets/14811094/10238646/89369732-6890-11e5-8698-8981aeede3ac.jpg)

But when you search:
![helloworld search](https://cloud.githubusercontent.com/assets/14811094/10238665/cc906828-6890-11e5-8196-008b0f83e904.jpg)

Searching the hashtag without the hash (#) doesn't pull a post but it pulls a user.

Thank you
@Data66PF 
@RaymondBenc 
MZ

**Comment by AnthonyKing** [comment]
search hello world, HELLOWORLD

**Comment by majdmike** [comment]
@AnthonyKing 
Searching the plane text doesn't search anything BUT user names.

**Comment by majdmike** [comment]
Actually, the search bar displays content under hello world or helloWorld but nothing about the hashtag helloWorld

**Comment by AnthonyKing** [comment]
try to search 1 #helloworld

**Comment by majdmike** [comment]
Doesn't display any content except "No search results found."
@AnthonyKing

**Comment by AnthonyKing** [comment]
its not working, i just tried, just try to make something like http://community.phpfox.com/ where there is a trending topics since it shows the hashtags

**Comment by majdmike** [comment]
@AnthonyKing Searching the trending topics doesn't populate on top of the search either? I haven't tested that yet.

**Comment by Data66PF** [comment]
Hashtags have not been included in the global search before. It would need to be a feature request.
