### ISSUE TITLE
Edit Profile - Switching From "Basic Info" to "About Me"

### ISSUE THREAD

**Issue by majdmike** [moxi9/phpfox#577]
Dear all, I'm running PF V4.08
I have a new issue to post, it might be AJAX related but I'm not sure.
When the user wants to update their information and go to the "Edit Profile" tab and lets say fill the first page which is the "Basic Information" and clicks "Update" in the button of the page to save. 
NEXT the user would want to change the "About ME" tab so they go up and click the "About Me" tab withOUT refreshing and modify the page and "Update". Here's the issue, the "Basic Information" page would save and update fine but the "About Me" page wouldn't save or update. If you then refresh the page then the "About Me" page would reset to whatever it was before and work fine BUT then going back to the "Basic Information" page WITHOUT refreshing and modifying it wouldn't save and update. So you would have to refresh and reenter your changes and update. Doing this process the other way around, as in updating the "About Me" first then the "Basic Information" tab without refreshing gives the same result.

Thank you
@Data66PF 
@RaymondBenc 
MZ

**Comment by Data66PF** [comment]
Please stop tagging me in posts. Thanks.

**Comment by majdmike** [comment]
I apologize

**Comment by Data66PF** [comment]
It's ok but I got something like 20 emails this morning from github and it was just a bit much :)

**Comment by majdmike** [comment]
Sorry I'm still a rookie at this

**Comment by Data66PF** [comment]
It's fine :) Thanks for the reports.

**Comment by Data66PF** [comment]
Confirmed at the community. using ff on win 10

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
