### ISSUE TITLE
Send Button Missing 

### ISSUE THREAD

**Issue by whookka** [moxi9/phpfox#578]
I hope this is not a repeat...I searched but could not find a similar issue

attached is and image the send button is missing after choosing message icon 
![message-item](https://cloud.githubusercontent.com/assets/13561300/10239271/36f59924-6899-11e5-936f-1714b44754a8.jpg)

**Comment by Data66PF** [comment]
This is how it is designed. You hit enter to send. Thanks for posting though.

**Comment by PhpFoxJohnJr** [comment]
This should be reopened

https://community.phpfox.com/forum/thread/54347/send-button-and-comment-buttons/
Neil	
October 31, 2016  #14	
On 4.6.0 features meeting, I will discuss with team about this feature. Could someone make a request on our github repo again.

**Comment by neil96** [comment]
@PhpFoxJohnJr It should be a feature request my friend.
