### ISSUE TITLE
Cant Save a Profile Twice

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#579]
While editing a profile is not possible to save any modification without reload the page if you already saved some information.

To test this issue:

1- Go to Edit Profile (/user/profile/)
2- Go to About Me and Digit any information at about me box.
3- Hit save and the information will be recorded
4- Insert more information at about me box
5- Hit save and nothing will happens.

**Comment by majdmike** [comment]
I posted this issue yesterday, 
https://github.com/moxi9/phpfox/issues/577
I believe it might be an AJAX related issue. And I think the easiest solution is to force refresh AJAX after a major button such as "UPDATE" or "SAVE" is clicked anywhere in phpfox's script.
