### ISSUE TITLE
Constant Image upload/deletion issues

### ISSUE THREAD

**Issue by Davetheraveuk** [moxi9/phpfox#580]
Hi,

I am having constant image issues. They are:
-Image upload is sluggish and sometimes does not happen at all.
-AJAX icon is always displaying image is uploading - but nothing else happens and site freezes often.
-Unable to delete images as Admin or a regular user.

Is this a known bug or something?
Is there a fix or work-around?
These issues are bugging the *** out of me as I cannot get to the bottom of what is causing it.
phpfox version: 3.8.0
Server type: Shared.
url: https://www.anonbook.org/

**Comment by Data66PF** [comment]
This bug tracker is for v4 only. Please be sure to use a licensed client version for your website and to host with good providers. Please post V3 issues like this in the community as it is a site issue.
