### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#581]
i just refreshed my site and found this error hiding in the feed
![screenshot 1034](https://cloud.githubusercontent.com/assets/12142143/10260187/79013844-6972-11e5-9321-dd6e993fe661.png)

**Comment by AnthonyKing** [comment]
this happend after i checked the counters, check missing setting, checked unknown files and cleared the cache

**Comment by jubelum** [comment]
I am having the same issue, I always get Script Error on my website... is there any fix for this?

**Comment by AnthonyKing** [comment]
i still want to know the solution

**Comment by Ylmzef** [comment]
Upgrade your hosting/server

**Comment by AnthonyKing** [comment]
i think the problem was that i enabled the dislike button, and it did not show anywhere in my site, after i disabled it the script error did not appear, and i hope it was the last time i see it

**Comment by AnthonyKing** [comment]
nope the error still appears, not at the top, but now at the button

**Comment by AnthonyKing** [comment]
how do i upgrade my hosting/server

**Comment by AnthonyKing** [comment]
@jubelum what module did you install/ apps

**Comment by jubelum** [comment]
I have recaptcha, younet videochannel, facebook login... but I reinstalled my website...

**Comment by Data66PF** [comment]
duplicate https://github.com/moxi9/phpfox/issues/522
