### ISSUE TITLE
Photo Dropdown Menu Missing

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#583]
In V3 was common that modules section have a menu at left of the content with link to areas like all content, friends content, my content. This menu become a drop down menu and now is displayed at left of the module name on the top bar, however photo module dont have one and without this feature is impossible to access certain photo module areas like albums.

**Comment by Data66PF** [comment]
Confirmed as blogs and other areas have it.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
