### ISSUE TITLE
Forum Dropdown Menu

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#584]
In V3 was common that modules section have a menu at left of the content with link to areas like all content, friends content, my content. This menu become a drop down menu and now is displayed at leftnof the module name on the top bar, however forum module dont have one anymore and the old menu has some important link like new threads, my threads and subscribed threads.

**Comment by Data66PF** [comment]
I can confirm but am not sure if this is a bug or new design.

**Comment by RaymondBenc** [comment]
This is more theme related. We can work in a new theme that takes this into account, however I need to close this as a bug report as its nothing problematic with the core itself.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
