### ISSUE TITLE
Search Tab Function Not Working Properly

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#586]
I noticed that the search function is not working properly in version 4.0.8. When I try to input any text in to the search tab, the script "delete" letter that I type so fast that I cant write a full term to search.

This issue is related with a topic at phpfox community here:
http://community.phpfox.com/forum/thread/52847/search-does-not-work/

**Comment by Data66PF** [comment]
I can reproduce this in chrome on a fresh install. I cannot reproduce it at the community when using chrome though.

**Comment by RaymondBenc** [comment]
Issue has been resolved yesterday in another bug report. 4.0.9 will include this fix and I re-tested it now and was not able to reproduce it again. If the issue comes up again, please open a new case.

Thanks for taking the time to report issues to us.

**Comment by SalmanKhan86** [comment]
In how many days V 4.0.9 out
