### ISSUE TITLE
Cover Reposition Not Working [4.0.8]

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#587]
The feature of cover reposition is not working properly on pages. When we click on manage cover > reposition nothing happens.

**Comment by Data66PF** [comment]
Confirmed at the live community, using ff on win 10

**Comment by leandrotavaresrocha** [comment]
I tested this issue in v4 and still not working. Should I open a new issue or this issue can be reopenened?

**Comment by Data66PF** [comment]
Please open a new issue and in the description please reference this report.
