### ISSUE TITLE
missing setting

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#588]
my site is missing alot of setting, and when i go to maintenance > missing settings after it searched the missing settings it goes back to admin dashboard. the screen shot shows a difference between my live site and my localhost  site
![screenshot 1068](https://cloud.githubusercontent.com/assets/12142143/10290848/c898ae4c-6ba6-11e5-9a0b-b19833bc00b8.png)
![screenshot 1069](https://cloud.githubusercontent.com/assets/12142143/10290849/c8c7cf4c-6ba6-11e5-8d8c-4586893ca458.png)
![screenshot 1066](https://cloud.githubusercontent.com/assets/12142143/10290894/07f4dfe8-6ba7-11e5-87d5-743c42f35f30.png)
![screenshot 1067](https://cloud.githubusercontent.com/assets/12142143/10290895/080bfebc-6ba7-11e5-95c4-0aa8d66d8344.png)

**Comment by Data66PF** [comment]
There are many settings removed from v4 as they are not used. If you have a specific setting that needs to be disabled in v4 that you are seeing in your test site, let us know the setting and we'll completely disable access as they can cause issues if you enable the ones that are not being used.

**Comment by AnthonyKing** [comment]
ok i'll let you know of any settings that needs to be disabled
