### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#589]
when i try to tag someone.
1. i type my status/comment and when i click @name_of_user it displays something like @profile+number even when i click submit it still displays the @profile+a number i just want to display name of user
and i am still waiting for the script error fix
![screenshot 1070](https://cloud.githubusercontent.com/assets/12142143/10291794/02ee234c-6bac-11e5-9383-839a9d306a7e.png)

**Comment by Data66PF** [comment]
Make sure the user has a username. It will show as profile+number if they don't have their username changed to a username. Please only post one issue per issue report.
