### ISSUE TITLE
responsice styles not working properly on some sections

### ISSUE THREAD

**Issue by d1a8lo24** [moxi9/phpfox#59]
On your own demo for phpfox 4.0, the splash screen or welcome scree doesn't align correctly when the screen starts to resize for smaller devices. the left panel where the login box is, it shrinks to make a white margin of 35px. on the left but the outlines of the login box still show, which doesnt look right, not only that at certain sizes you can't even login or register. because this 2 forms are hidden.

here is a screen shot for a screen at 980px width and stays like this to about 400px. also the register form stays hidden with out any other options.
![social networking community - powered by phpfox 2015-07-10 17-38-21](https://cloud.githubusercontent.com/assets/5483411/8631432/ca2f7936-272a-11e5-9392-cf445e8d3f8d.png)

Now browsing the site I also notice that the mobile menu if you're login or just browsing as a guest on a mobile device, on the photo section the mobile drop down or left slider is blank there is no content for the menu. well, it is there but is hidden by something. On the rest of the sections there is no problem 

Here is a snapshot on how the mobile menu should look.
![sign up and start using phpfox social networking community - powered by phpfox 2015-07-10 17-47-24](https://cloud.githubusercontent.com/assets/5483411/8631480/f51cbe00-272b-11e5-9a73-5f11ef4dc60a.png)

And here is how it looks when you looks when you're in the photo section
![photos social networking community - powered by phpfox 2015-07-10 17-47-56](https://cloud.githubusercontent.com/assets/5483411/8631484/0df98e6c-272c-11e5-8c4f-1aeb4841cb9d.png)

**Comment by lilman446** [comment]
I see this issue as well on my iPhone.
