### ISSUE TITLE
Issue not completely fixed

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#590]
https://github.com/moxi9/phpfox/issues/483

This is still an issue  avatars not showing in friends pop up.
![2015-10-06 15_42_04-bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult dating](https://cloud.githubusercontent.com/assets/13656046/10310314/a3e568e2-6c41-11e5-89d7-387689eb1ff9.png)

**Comment by Data66PF** [comment]
We've not released the fix yet as a release. Once released, you would test with default theme and be sure to run the upgrade routine mentioned at scripttechs so you can pull in all of the fixed files.

**Comment by Data66PF** [comment]
I'll leave this open for after we upgrade the community once 4.0.9 is released.

**Comment by one44** [comment]
I have removed rounded I no longer use it.

**Comment by one44** [comment]
i Have checked on 4.0.9 still same issue.

**Comment by Data66PF** [comment]
Reproduced at the community in the feed when able to hover over the username in the feed and see one with a lot of mutual friends. Click to see the popup to show the rest of the mutual friends and some images are missing.

**Comment by Data66PF** [comment]
Fixed as seen at the live community 4.0.10.
