### ISSUE TITLE
Phrase Var not parsed in mail signature

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#591]
I made some test and seems that when we use a phrase var in the admincp setting to create a multilingual mail signature the script doesnt parse it to a text. Instead of I receive the translated term I receive a {phrase_var=""}.

**Comment by AnthonyKing** [comment]
i got that too,

**Comment by Data66PF** [comment]
I can confirm this in emails to my email inbox in thunderbird on win 10.

**Comment by leandrotavaresrocha** [comment]
Lately I received an email with a phrase_var in the title so seems that this issue is occuring not only with phrase_var in the email body, but also with the phrase_var in the title.

**Comment by AnthonyKing** [comment]
if you are on a localsite and you have a code editor, search for phrase_var

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8 fixed
