### ISSUE TITLE
Social Sharing and Booking Marking Issue

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#593]
I think that this feature was removed, however as is possible to access I searching by "social" in the settings area decided to open a issue. 

Previously phpfox has a feature to enable a social share button for twitter and facebook that appear in the feed form. Actually these settings still avaliable, however they dont appear correctly when enabled.

**Comment by Data66PF** [comment]
duplicate #551 for these to be removed.
