### ISSUE TITLE
No way to change frontpage images and text

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#597]
Please don't close this issue without fixing .
Lot of phpfox community owners(according to number of threads posted related to this on PF community forum) want to customize the front page images and text ( creating communities for fine cooking etc) but there is no option available in admincp to do this.
Only ways to do it either changing core files OR if we feature an already uploaded image (still we cannot edit text) .
 As manually changing core files is not a wise solution  there should be an option in admincp to do this.

Please consider it as a bug and not  a feature request because it is our basic right to customize our phpfox community according to our audience type.
Thanks

**Comment by Data66PF** [comment]
This is not for feature requests and that is a feature of the script. This was already marked working as designed before by a core developer. You will need to have an app to change how this works as bugs are things not working and features are changes to the script. This area is only for bugs. There is an area on the forum for feature requests.

**Comment by Data66PF** [comment]
I will mention this to the developers to see if there could be an app released for it. We don't want any additions or changes to the core product. Apps are meant to extend the core without modifying it.

**Comment by aakash83** [comment]
so if my community is not related to  cooking , music etc then what should i do  when members ask me why this pics and text are there which are totally irrelevant. even those images are not stored on my website. I have a solution for this if  it  is acceptable for phpfox devs. 

 if the images are stored locally on our web server we can easily upload new images matching our community type with same names to replace old ones .at least it is easy way to change those images without modifing core files. thanks

**Comment by one44** [comment]
Front Page Images

PF.Base\module\core\include\component\controller\index-visitor.class.php..

**Comment by aakash83** [comment]
Thanks one44 but i was looking for a solution without modifing core files.

**Comment by Data66PF** [comment]
It is meant for a developer to do apps though. This is theme related too. It can be changed via themes. As I said though, I'll ask the core developers if they want to release an app for this. Note that they are extremely busy with bugs, which is why we made the feature request area at the community. so that third party devs could start on some apps that people want, rather than having everyone wait for our core developers to have time to make apps such as this.

**Comment by Jinkers** [comment]
@aakash83. Just to clarify the process a bit more from the above.

To set an image on this page, it is a matter of featuring an image from your site. I suggest doing this from the default admin account (which you shouldn't really be using as an account, more of a backup in case of emergencies). 

As for the text portion in the bottom right hand corner, it actually updates based on the image that is displayed and gets the text from the title field of each photo.

![image](https://cloud.githubusercontent.com/assets/7270030/10353961/d552276a-6da6-11e5-80ad-22d558716bc7.png)

While this process is fine for some, I agree for the less technical minded (no offence intended) it does make sense for the images to be controlled from the AdminCP. If you wish for app developers to take a further look at this request, as recommended by @Data66PF, post a request at http://community.phpfox.com/forum/122/neutron-v4-feature-requests/
