### ISSUE TITLE
Account Setting Neutron Android OS Responsive problem 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#600]
when we go to Account Setting in Android OS

![screenshot_2015-10-08-15-47-32](https://cloud.githubusercontent.com/assets/13433124/10365066/f7bac99c-6ddd-11e5-836a-99f3dc3b2ec8.png)

**Comment by Data66PF** [comment]
confirmed iPhone 5c at the community

**Comment by phpfoxdev** [comment]
The same issue with - https://github.com/moxi9/phpfox/issues/375

**Comment by Data66PF** [comment]
Ok This was for account settings and that was for Register. I didn't realize they would be considered the same since one is when logged out and the other logged in. Do we close one @phpfoxdev

**Comment by phpfoxdev** [comment]
It's closed due to the duplication of #375 and will be released in next version.
