### ISSUE TITLE
Register&Login Button Neutron Android OS Responsive problem 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#601]
when i am not logged in click on blogs somewhere than a pop up box open Notify me 'you need to be logged in to do that''  in this Register and login button can be toggle button. Android OS Problem
![screenshot_2015-10-09-12-43-32](https://cloud.githubusercontent.com/assets/13433124/10389297/ec3dbc18-6e8d-11e5-8e1a-d3d297cc8815.png)

in same way when i go to member timeline and click on Message icon then same problem found!

![screenshot_2015-10-09-12-45-50](https://cloud.githubusercontent.com/assets/13433124/10389213/58028966-6e8d-11e5-9900-d445d6758004.png)

**Comment by Data66PF** [comment]
duplicate #394
