### ISSUE TITLE
Default Name Neutron Android OS Responsive problem 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#602]
for members who has't uploaded his profile pic.default name rewrite feature can't place Alphabet in middle of box .

![screenshot_2015-10-09-12-50-21](https://cloud.githubusercontent.com/assets/13433124/10389348/65ceb67c-6e8e-11e5-9bfc-6c00ef51dee2.png)

**Comment by Data66PF** [comment]
confirmed iPhone 5c at the community

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-66 *
