### ISSUE TITLE
Like icon Neutron Android OS Problem 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#603]
like icon functionality not working properly in Android OS.when i am click on like icon.it do nothing. try many times on Member timeline's but do it nothing.
![screenshot_2015-10-09-12-55-16](https://cloud.githubusercontent.com/assets/13433124/10389446/3db954e8-6e8f-11e5-88e8-e0b59b9ae376.png)

**Comment by Data66PF** [comment]
duplicate #598
