### ISSUE TITLE
Like Count Icon Neutron Android OS Responsive Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#604]
like icon when its show total like count then not being in responsive style.Although its looks fine when its not showing total count. Android OS
![screenshot_2015-10-09-12-57-06](https://cloud.githubusercontent.com/assets/13433124/10389906/8294e0f2-6e92-11e5-98df-43f06825a6ec.png)

![screenshot_2015-10-09-13-00-41](https://cloud.githubusercontent.com/assets/13433124/10389927/aa52343c-6e92-11e5-9819-2f29e7584fa1.png)

**Comment by Data66PF** [comment]
Confirmed iPhone 5c

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed 4.0.10
