### ISSUE TITLE
Pages Neutron Android OS Responsive problem 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#605]
when we go to pages. its not responsive Android OS

![screenshot_2015-10-09-13-04-37](https://cloud.githubusercontent.com/assets/13433124/10389974/178bb8ac-6e93-11e5-9540-8d0b68d65a7f.png)

**Comment by Data66PF** [comment]
cannot reproduce iPhone 5c, v4.0.9 at the community

**Comment by SalmanKhan86** [comment]
it is due to large image can't be responsive

**Comment by Data66PF** [comment]
This appears fixed in 4.1.1 as I'm testing with a large image and there is no scroll showing.
