### ISSUE TITLE
Forum attachments to not display in line, and canot be deleted.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#607]
This is possibly relate to issue #515 since closed.

Attaching an image uploads correctly does not display. Opening Managing Attachments after attaching and I see

Attachments
whatever.JPG - Delete - ', url: 'https://yoursite.com/index.php/file/attachment/'}); $.ajaxCall('attachment.inline', 'id=4', 'GET'); return false;">Use Inline 

Selecting Use Inline and saving (for which the entire url: 'https://yoursite.com//index.php/file/attachment/'}); $.ajaxCall('attachment.inline', 'id=4', 'GET'); return false;">Use Inline is one link) 

does not cause the image to display in line.

Selecting Delete and saving does not delete the attachment.

**Comment by Data66PF** [comment]
Cannot reproduce in 4.0.9 at the community http://community.phpfox.com/forum/thread/52955/image-attachment-test-inline-per-bug-report/ I attached the image using inline attachment. I first attached one image of a fox. I then deleted it using the delete option in manage attachments. I then added another image that you see in the thread via inline attachment. It seems to function fine.

**Comment by t2nttn** [comment]
I saw code in recent post here: http://community.phpfox.com/forum/116/playground-testing-area/

**Comment by Data66PF** [comment]
I don't see code in it. Note that you need to log in to view my image as my privacy settings are for community.

**Comment by t2nttn** [comment]
I though quote or attachment ID shouldn't display here. Did you see in recent post phrase like: "[quote=51305]", "[attachment="594:view"]", "Comment,[quote=425668]", "[img]http://community.phpfox.com/file/attachme..."

**Comment by Data66PF** [comment]
That is how it works. This bug is not for that.
