### ISSUE TITLE
User configuration: Automatic friend assignment option 

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#608]
V4.08 -Patched, Apache/Debian, Firefox 41, Windows 7
The automatic friend assignment option under user configuration filters out users of any user group but administration.  Registered or staff group members do not show as a selectable option.

**Comment by Data66PF** [comment]
It is only for admin. If you want to add other groups, please post a feature request at the forum area for it. This is meant for safety but also that setting creates a huge load on the server and should only be set for someone that doesn't log into the site often.

**Comment by Gatsby-PF** [comment]
Emily Smith...Administrator?  Boggles the mind.  
BTW Looking much less like brevis rosea Eudyptes pachyrhynchus today.

**Comment by Data66PF** [comment]
That is a general admin account for us to use when checking the site since it is a friends only community. That account doesn't get on often.
