### ISSUE TITLE
Loss of Profile Info-Editor After Installing Numerous Pathches in V4.08

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#609]
Has anyone who has implemented the recent bug patches associated with the latest series of bug closures now have any issues accessing the info-editor in their profile?  I for one, am no longer able to access it for any group.

**Comment by Data66PF** [comment]
Please do not implement by patches. Please wait for a release.

**Comment by Data66PF** [comment]
Cannot reproduce but I run the upgrade routine, I don't do it by patches as the routine needs to run for the clean up as shown in the tutorials at scripttechs for final steps. Note that I only load the git stuff on a local. Always wait for a release before implementing any of the changes from here.
