### ISSUE TITLE
short url problem (Urgent!!)

### ISSUE THREAD

**Issue by Alexlim91** [moxi9/phpfox#610]
Hi Guys, 

I really need you guys help, why after i enable the short url in the admincp for phpfox neutron. My website become error and showing coding error. 
Please refer to this link:

http://scripttechs.com/forum/thread/2739/short-url-problem-urgent/
Thank You

**Comment by Data66PF** [comment]
This is only for bugs, not server issues or site issues. Please post in the forum or at scripttechs for site issues.
