### ISSUE TITLE
Like  comment or pic in pages/groups

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#611]
When a member likes a page or group content etc does not reflect in main feed.

**Comment by Data66PF** [comment]
It works on my test site. I uploaded a photo to my page/group. It shows in the main feed and in the page/group feed. I Liked the photo in the page feed and the like shows on the main feed. Note that it won't add a new item to the feed if you mean for it to add a separate item.

**Comment by one44** [comment]
I think what you are saying is it shows in the photo that shows in the main of the original post feed but it does not show if the feed has a number of posts in between as a new post like when a person updates their status.

**Comment by Data66PF** [comment]
Yes, that's how it's always worked though unless you used the setting in v3 to add comments as feeds. I think at that point it showed. For v4, that setting is not available nor is the feed filter that let folks choose to see new or top content.

**Comment by one44** [comment]
Which to me is a design fault as it is needed so that on an active site members can see something that is trending with likes.

**Comment by Data66PF** [comment]
many things that bogged down the script were removed. Most likely, this was one that was removed due to that. However, I'm sure your favorite developer can do a customization to put things how you want them. As long as you have the server to support the settings, it should be ok.

**Comment by SalmanKhan86** [comment]
for me it does reflect in main feed.

**Comment by one44** [comment]
@SalmanKhan86  Is that as a new post in feed or with the original post in the feed? My point is that if the original post is 100 posts down the main feed it will be missed by a lot of members but if added as a new post aggregated each time someone Likes or the original post is moved to the head of the feed showing all the likes this will show what is trending.
