### ISSUE TITLE
Pages posting issue on upgraded site

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#613]
When i post sommeting on any pages, it's not showing after posted.
I reflesh the page than i can see what i post.
Upgraded site.
v4.0.8

**Comment by SalmanKhan86** [comment]
it show immediately after posted i checked on windows 7 OS working fine here

**Comment by Data66PF** [comment]
Please upgrade to 4.0.9 and do all of the steps required after upgrading.

**Comment by Data66PF** [comment]
Cannot reproduce at the PHPfox community 4.0.9
