### ISSUE TITLE
Mail Message Send Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#614]
when i received message from someone i reply to it first time using http://community.phpfox.com/mail
then same message post in loop three or four times.Windows 7 OS.
Although i tested it on PF Community but in V 4.0.9 its working fine for me.
pls test at your end

![mail msg problem](https://cloud.githubusercontent.com/assets/13433124/10480852/5c1df1ba-728a-11e5-81bf-d947a9b87c77.png)
![mail msg send](https://cloud.githubusercontent.com/assets/13433124/10480855/5e23b198-728a-11e5-8731-4ae655669f7d.png)

**Comment by Data66PF** [comment]
It could have been during the upgrade. I'll close this as I tested and it works fine at the community and you mention it works fine on your local tests.
