### ISSUE TITLE
Report Posted With Choose One...

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#615]
if i have't choose any thing when i report any content it still reported with choose one.. selected option.
Windows 7 OS
![report photo](https://cloud.githubusercontent.com/assets/13433124/10481709/2911c6ce-7290-11e5-9e34-fb538d95ecef.png)

**Comment by Data66PF** [comment]
confirmed 4.0.9 at the community

**Comment by AnthonyKing** [comment]
and the submit button does not work

**Comment by Data66PF** [comment]
The submit works, it just doesn't show it. A core developer will check the issue though.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-72 *
