### ISSUE TITLE
No Block members Button

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#616]
Cannot locate block member button. Have a blocked members report on profile but cannot find a block member button to actually block a member.

**Comment by Data66PF** [comment]
This is workiing for me on my test site after setting the user group permissions to be able to be blocked. I cannot reproduce any issue.

**Comment by Data66PF** [comment]
![block user](https://cloud.githubusercontent.com/assets/6908282/10483660/8782e414-724e-11e5-9b65-22416b5aa17a.png)
from the community

**Comment by one44** [comment]
Mine says report this user and remove this user only is this a language issue???

**Comment by Data66PF** [comment]
Did you follow all of the steps for after an upgrade? Did you check the user group settings, noting that admin user is set to NOT be blocked so the setting won't show.

**Comment by one44** [comment]
Will check have just checked settings and is correct will log in as non admin and check.
![2015-10-14 15_12_27-admin cp bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult](https://cloud.githubusercontent.com/assets/13656046/10484605/4b043d20-7286-11e5-816f-d6df7a585540.png)

**Comment by one44** [comment]
Ok Thanks I see it when am not admin all three show Report, remove and block.

**Comment by Data66PF** [comment]
You're welcome. It only shows on the user groups that can be blocked by other members too. :)
