### ISSUE TITLE
video feed

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#618]
i uninstalled video feed since it was working, after i upgraded i installed it again thinking it will work properly this time, but i found the errors and videos from the video feed app that i uninstalled in version 4.0.8, so i want to know how do i removed the saved app data so that when i install it starts as if it is the first time i install it

**Comment by Data66PF** [comment]
This is not for issues with apps. Please post video feed issues in the video feed app issue tracker.

**Comment by AnthonyKing** [comment]
i posted there a long time ago, i was hoping someone will reply me when i post it here

**Comment by Data66PF** [comment]
I'll remind him that there are issues posted in some of the apps but the core right now is getting the focus in order to finish up all of the bug reports. Thanks for your report though.

**Comment by AnthonyKing** [comment]
yeah, i can see you guys are working really hard
