### ISSUE TITLE
v4.09 Admin Config DB Settings Failure

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#619]
Fresh install, out of the box 4.09, new database.
Adminstrator >> Settings >> Site setting changes take persistently.
Adminstrator >> Settings >> Security setting do not take, and the there is an update status indicator wheel that keeps spinning to the far lower right because it is perpetually unsuccessful trying to write.
When leaving the security settings, any settings set are in their original default state.

Exact same setup that was being used successfully with 4.08.
Forced https.

**Comment by Gatsby-PF** [comment]
Hmmm!?.
For some unknown reason, this seems to not be the case now and settings are now retentive. 
I am nonetheless curious to know if anyone else out there has encountered this. If everything remains stable over the next day or two, I will close this.

**Comment by Data66PF** [comment]
It could be a cache issue with the server. sometimes that can lag. Can this be closed if the issue is resolved?

**Comment by Gatsby-PF** [comment]
Seems to be okay now so why not.
