### ISSUE TITLE
Facebook Error?

### ISSUE THREAD

**Issue by BrunoSette** [moxi9/phpfox#62]
Whenever I go to my main url page I see this message:

"Invalid Scopes: publish_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions"

Then it redirect to a Not Found Page: 

http://www.aprovasocial.com.br/index.php?facebook-process-login=true&error_code=100&error_message=Invalid+Scopes%3A+publish_stream.+This+message+is+only+shown+to+developers.+Users+of+your+app+will+ignore+these+permissions+if+present.+Please+read+the+documentation+for+valid+permissions+at%3A+https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Ffacebook-login%2Fpermissions#_=_

**Comment by Data66PF** [comment]
http://scripttechs.com/article/353/fix-facebook-publish_stream-error/ that fixes it for v3. Not sure if it is also needed for v4. You do need your app to be approved at Facebook for publishing.

**Comment by RaymondBenc** [comment]
Is this for the v4 app? We don't request for **publish_stream** and do not include in the URL **facebook-process-login**

**Comment by Data66PF** [comment]
Is this one resolved for you with version 4.0.3? Please ensure the social sharing is off as that is not part of V4 yet.

**Comment by Data66PF** [comment]
Closed due to no response
