### ISSUE TITLE
v4.09  User profile Info edit box does not open

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#620]
v4.09 fresh install, new DB
Windows 7, Firefox 41 and Chrome.
This issue was  previously closed on an appeal to not patch files, however the result is the same,

The user in their profile can still not set user info in the info box. Selecting "Info" only yields an empty screen, not the edit box that used to show up before 4.09 related changes.
Forced https:, however it worked satisfactorily under this condition under prepatched v4.08.

**Comment by Data66PF** [comment]
Did you go to Edit profile and add the info there first?

**Comment by Gatsby-PF** [comment]
Nice call. I thought they were two different ways of doing the same thing, whereas the profile Info link is only to edit existing About Me content created first in edit profile > about me tab.

**Comment by Data66PF** [comment]
Yes :) that is how it works. It's hard to explain it without a written tutorial. I do have some front end user guides I let people use on their sites but I don't think I wrote one for this. Anyway, it's a good idea to do front end guides for your users as stuff like this is not something they'll know.
