### ISSUE TITLE
Responsive: Images and thumbnails are cropped in « Photos »

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#621]
Tested on Chrome Version 46.0.2490.71
![john_and_i_in_greece__ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529249/7a7e62da-739c-11e5-9f66-084d643ce2cb.jpg)

**Comment by Data66PF** [comment]
Please always state the device you are using to test. Please note that if testing a desktop, don't do it by resizing the window.

**Comment by Data66PF** [comment]
Cannot reproduce on an iPhone5c with safari browser.
