### ISSUE TITLE
Hours and minutes are cropped in "Events"

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#623]
For field "Start Time".

Tested on Chrome Version 46.0.2490.71
![create_an_event_ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529295/d90188dc-739c-11e5-8b62-194492126c6c.jpg)

**Comment by SalmanKhan86** [comment]
there is little css issue in this .
add
.table .table_right .js_datepicker_core_start select{width:9%;} will fix this issue

**Comment by Data66PF** [comment]
confirmed with iPhone 5c

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-74 *
