### ISSUE TITLE
Search is not working for "Pages"

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#625]
The page "kool" is available, but you can not find it using the search option for "Pages".
Tested on Chrome Version 46.0.2490.71
![pages_ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529391/e2810008-739d-11e5-91c4-5253d42c7820.jpg)
![pages_ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529393/e80558da-739d-11e5-8037-ed69661fa1ba.jpg)

**Comment by Data66PF** [comment]
Note that it is a friends only community. Note that this issue is in another bug report. https://github.com/moxi9/phpfox/issues/424

**Comment by t2nttn** [comment]
if so, I think pages of non friends shouldn't display in pages index.

**Comment by Data66PF** [comment]
That is mentioned in the other bug. Yes, they should not show for a friends only community. It will be addressed in the linked bug.
