### ISSUE TITLE
album error

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#627]
![screenshot 1146](https://cloud.githubusercontent.com/assets/12142143/10530611/b6cbb2bc-73a9-11e5-9c81-a736b5ae8ed8.png)
![screenshot 1147](https://cloud.githubusercontent.com/assets/12142143/10530629/e132abc8-73a9-11e5-88b9-aa74d61d4a49.png)
i tried to create a new album but all i get is this error

**Comment by Data66PF** [comment]
Cannot reproduce v4.0.9. Please check folder permissions on your site. Please test with default theme and no apps or third party modules installed.

**Comment by AnthonyKing** [comment]
![screenshot 1164](https://cloud.githubusercontent.com/assets/12142143/10540782/7850cbfa-740b-11e5-96e2-525555983385.png)

**Comment by Data66PF** [comment]
Permissions in PF.Base/file/ folder for pic and also inside the pic folder?

**Comment by AnthonyKing** [comment]
![screenshot 1167](https://cloud.githubusercontent.com/assets/12142143/10544790/b4efc182-7425-11e5-99d8-8229581c2a49.png)
![screenshot 1165](https://cloud.githubusercontent.com/assets/12142143/10544791/b505caf4-7425-11e5-8eb1-e0d7ae2b77a5.png)
![screenshot 1166](https://cloud.githubusercontent.com/assets/12142143/10544792/b564c86a-7425-11e5-9b7a-7204aac4bfce.png)

**Comment by AnthonyKing** [comment]
which permissions should i have set in my files 0755/0644/or what?

**Comment by AnthonyKing** [comment]
.

**Comment by Data66PF** [comment]
I don't know but this issue is not seen on other client sites or my tests so you will need to check your server settings perhaps or maybe see if an app, module, customization is causing you issues.
