### ISSUE TITLE
ads issue

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#628]
i wanted to sponsor a picture in my feed, it directed me to a page which displayed "your order has been processed", then i clicked home to check if the picture will appear in my feed, i found an error "Uncaught TypeError.......", went to my admin panel clear the cache, went to my site again and the error was gone, checked if i had any pending payments / approval, found none. Then later  i tried to sponsor another picture in my feed, i got a different error which is very annoying
![screenshot 1148](https://cloud.githubusercontent.com/assets/12142143/10530924/2fc81b9a-73ac-11e5-89dc-74588885dd90.png)
![screenshot 1156](https://cloud.githubusercontent.com/assets/12142143/10530928/3728e87e-73ac-11e5-9ad7-77fc34c6b4fc.png)

**Comment by Data66PF** [comment]
I'm not able to reproduce this on my v4.0.9 test site with default neutron theme.

**Comment by AnthonyKing** [comment]
if i see the error again i'll post images
