### ISSUE TITLE
Loss of message delete feature

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#629]
4.08 had the little X box underneath each private message channel that allowed it to be deleted if clicked. It appears to have AWOL (absent without leave) in 4.09.  All appropriate permissions seem to be enabled.

**Comment by Data66PF** [comment]
![archive mail](https://cloud.githubusercontent.com/assets/6908282/10539409/5eb0f4f6-73cd-11e5-919e-faeff574bada.jpg)

You need to click archive and then select them.

**Comment by Gatsby-PF** [comment]
Thank you.
