### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#632]
When a post is made and another member comments on that post a notification is sent to the person who made the original post. However when the notification is clicked on it takes you to the original post with no site of the comment in the feed unless you manually refresh the page.

**Comment by Data66PF** [comment]
Did you test this at the live community demo?

**Comment by Data66PF** [comment]
http://community.phpfox.com/profile-data66/?status-id=1514 could use some comments on that to test

**Comment by Data66PF** [comment]
#479

**Comment by one44** [comment]
Sorry did check must have missed my other post as I did mention it in the community and was not sure if I posted it here.
