### ISSUE TITLE
Setting to add genders is removed

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#633]
This is a critical setting for many sites as they want and need to add or change genders. The setting used to be core.global_genders but that setting is set to NULL in the database so it is not assigned to a setting in admincp now. Site owners running websites that require variations or changes to the genders need this for their communities.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-81 *
