### ISSUE TITLE
Mixed Content Errors with New v4

### ISSUE THREAD

**Issue by jason1234h** [moxi9/phpfox#634]
I'm getting mixed content errors resulting from:

1. The stock images with the new version. Apparently they're fetched insecurely from moxie
2. Some content/css fetched from Google

I'm going to try to fix it myself. I'm running a dedicated IP and SHA-2 SSL. Just concerned that my changes may be overwritten if I update it.

**Comment by Data66PF** [comment]
Please post what you are seeing and where you mention they are coming from. This doesn't have enough info for us to check. Thank you.

**Comment by jason1234h** [comment]
I can only find one:

"http://fonts.googleapis.com/css?family=Open+Sans:300,400,600"

But I know the stock images also cause it because they're fetched from another site over http:// (moxie.com I believe).

**Comment by Gatsby-PF** [comment]
You will see the URL
@import url(http://fonts.googleapis.com......
 in default.css under PF.Base >> theme >> default >> flavor >> default.css
and
PF.Site >> themes >> some digit >> flavor >> somedigit.css

If you change from http: to https:, then your calls to Googleapi will be https. Also Google should also return the gstatic content as https as well so you should be good. You can verify in Firefox under 
Tools / WebDeveloper /Webconsole.

Also, although I did not try the following, if the 

http://googleapi.com were changed to just

//googleapi.com..... (no http or https)
then your browser should auto select https if the site is encrypted, but if not then http instead. 

If that is the case (and say it works), then carrying that forward in future PHPfox releases would make it compatible with both http and https deployments.

**Comment by Gatsby-PF** [comment]
That should be the first line in you default.css under PFBase theme and somedigit.css under PFSite themes.

Changing the http to https results in secure connection to Googleapi.  Google will also now provide static content over https as well.

**Comment by Gatsby-PF** [comment]
The images issue is associated with:

PF.Base/module/core/include/component/controller/index-visitor.class.php
that phones home to moxi9 and hotlinks images that are displayed on your site.
This was discussed in another thread.

**Comment by Data66PF** [comment]
@Gatsby-PF can you please link the other issue report for us to see?

**Comment by jason1234h** [comment]
It appears to be the stock images (two total) OR any image uploaded by the admin and featured to replace the stock images. The stock images are the camera/photographer and the other one.

**Comment by Data66PF** [comment]
Is this still an issue?

**Comment by jason1234h** [comment]
Since I have combed through all the code and added https:// to any content served as http:// it hasn't been an issue. I don't know if it has been fixed in the code. My personal copy has been changed:

I changed the links for the captcha, googleapis, and the images from http:// to https:// and it appear to be working fine.
