### ISSUE TITLE
Portrait Cover In Pages and Profiles Issue

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#636]
Photos in portrait (height much more bigger then width) get clumsy when uploaded in pages or profiles as covers. The image is compressed due the "height" CSS rule in .pages_header .pages_header_cover img and  .profiles_banner .cover>img.

**Comment by Data66PF** [comment]
Cover photos need to be specific sizes. https://github.com/moxi9/phpfox/issues/313
