### ISSUE TITLE
Admincp member Search problem

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#638]
member search function in  admincp is not working properly.  for example  we  search for  a member XYZ and the function returns us  10 results . Now you select one member and perform any action e.g ban , approve etc . after that the page will refresh automatically and  redirect you to member list and you lost your  search results. so we have to repeat the search process if you still want to do something with other 9 searched members.
example 2:  if we have a 200 unverified members (pending email verification)  and  we search for  pending email verification members  and lets say we got  2-3 pages   and we select all members on page one and   send them verification email by using the button. after this page will refresh and redirect you to  your memberlist and again you will lose your search results. so to send  verification email to the members on other 2 pages( which you searched) we need to  repeat the search process.

tested with chrome on  win 10.

**Comment by AnthonyKing** [comment]
when i try to resend the verification email, i get 'Undefined variable: aUser'

**Comment by Data66PF** [comment]
This is how it is designed. It has always worked like this. To change how the script works, please file a feature request in the feature request category at the PHPfox community forum.
