### ISSUE TITLE
Settings to enable again

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#64]
By request to put these in one bug report per Yoda (Ray). See Yoda  to complain, bring light saber and cookies. *Note that it is normally best to have one bug per report but this was requested to put here for remembering to add them back. If you find other settings needed, please add them to the list in a comment.

Would be nice to have the admin search again so we can easily find the settings.
User login method (email, username, both) (actually, all of the user settings are missing)
Browsing Users Default Order
Date of Birth (Start)
Date of Birth (End)
Check For Promotions

**Comment by NetFriend2015** [comment]
Hello Data66,

As you requested.
Would you please include a terms and conditions to the signup process, and get new members to agree to them?

Thanks.

**Comment by davidvin** [comment]
Just updated to v4.0.4... still don't see content settings for TinyMCE / WYSIWYG.

Also, still don't see option to include terms and conditions in signup process, where did you put that?

Thanks

**Comment by Data66PF** [comment]
Did you ensure to do the steps in my tutorial, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view. Viewing requires that you uploaded a profile photo.

**Comment by Data66PF** [comment]
Note that this bug did not mention tinymce so that needs to go in a new bug
