### ISSUE TITLE
Change user name

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#640]
When a member changes their user name in My Account front end it does not check if name already in use.

**Comment by Data66PF** [comment]
I cannot reproduce this for Username. Displayname can always be the same as it is just what is displayed. Username, however, gives me an error any time I try to put it at one that exists. Tested with 4.0.9 with a registered user account group.

**Comment by one44** [comment]
Ok I see For some reason the Online members app shows user name whereas site uses display name.

**Comment by Data66PF** [comment]
ok I'll close this and you would want to contact that developer for a fix.
