### ISSUE TITLE
Pages Discussion Search Not Working [4.0.9]

### ISSUE THREAD

**Issue by pootato** [moxi9/phpfox#642]
The pages discussion search does not work.

**Comment by Data66PF** [comment]
I can confirm at the community in my group, http://community.phpfox.com/wog/forum/ when I try the search that is in that section, it instead searches the whole site and does not just search that discussions area.

**Comment by pootato** [comment]
Note that it does not search within the pages discussion area at all.

**Comment by Data66PF** [comment]
That is what I said. :)

**Comment by pootato** [comment]
You said "whole site" which would include pages. :P

**Comment by Data66PF** [comment]
As I said "it instead searches the whole site" that shows that it is not searching within the pages discussion but is instead "searching the whole site". Our core devs can see that it needs to search inside the pages' discussions and not the whole site.

**Comment by phpfoxdev** [comment]
fixed, will be released in next version

**Comment by Data66PF** [comment]
Fixed 4.0.10
