### ISSUE TITLE
Menu Ordering

### ISSUE THREAD

**Issue by SpeakLife** [moxi9/phpfox#643]
Hello,

If you go to the Admin Panel and click on Menus, you will see a section for main and footer. When I try to re-order the menu either within the footer or main section using google chrome browser, I can see the red circle appear indicating it is saving my changes. However it doesn't actually save my changes. I can re-order the links to say;
Home ,  Invite , Privacy ,  Terms , Contact Us 

and yet it reverts back to; 

Invite, Contact Us, About, Privacy, Terms.

I have tested this on all browsers and it doesn't save my changes when I try to reorder the menu by dragging one link above another.

Thanks,
SpeakLife

**Comment by Gatsby-PF** [comment]
This was a previous issue #533 "Reordering Menu Link Positions" which was closed because the tester could not duplictate the issue. Don't know why, I still have the issue. I wonder if these positions get saved in a data base or get written a file?  If a file, it could be the system is unable to write to the file due to insufficient permissions.

**Comment by SpeakLife** [comment]
Thanks for responding. I hope they fix it as it is still not resolved.

**Comment by Jinkers** [comment]
It is working perfectly fine for me. Are you using an upgraded site or a fresh install? What version are you running and have you tried clearing both your sites cache and your browsers?

**Comment by SpeakLife** [comment]
@Jinkers I am using an upgraded site and my current version is 4.0.9 Yes I cleared my cache and it still doesn't update the menu when I change the order.

**Comment by Data66PF** [comment]
I cannot reproduce this on an upgraded site using 4.0.9 and default Neutron theme. No plugins, no modules, no themes are left on this site from v3. I moved the main menu and footer menus around and they changed for me on the front end like they should. 

I do not have mod_sec restricting admin functions.
I do not have open_basedir restricting PHPfox functions (it is disabled)
I have current requirements (minimum of PHP 5.4)
I have cleared cache from admin cache setting and from browser

For those of you with issues, please check with debug enabled and please check with developer browser debug. Make sure ajax is working on your sites as some clients had corrupted files that caused ajax not to work and made various things not work on their sites.

**Comment by SpeakLife** [comment]
I too have 4.0.9 using default Neutron Theme. I have no custom mods on my site.

I do not have open_basedir restricting PHPfox functions (it is disabled)
I have current requirements (minimum of PHP 5.4)
I have cleared cache from admin cache setting and from browser

Not sure why it isn't working for me. You mentioned ajax. Is there a place I can search for this in the phpfox settings or is this something my web host would have to verify on my server?

**Comment by Data66PF** [comment]
"For those of you with issues, please check with debug enabled and please check with developer browser debug. "
Doing those will help see if there are issues on your site. Browser developer debug can show various issues that PHPfox debug doesn't.
In another issue report you posted that you do have apps on your site. Please note that apps could interfere if they are causing issues. Test without apps installed, perhaps on a development site (set up per the license terms).
