### ISSUE TITLE
Suggestions block issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#644]
Upgraded site
v4.0.9
Chrome v46
Windows 10

![naamloos](https://cloud.githubusercontent.com/assets/8562514/10595996/2c9f01be-76df-11e5-9f8f-1e9e803ee69e.png)

**Comment by Jinkers** [comment]
Duplicate of #512

**Comment by Data66PF** [comment]
Please search before posting. Thank you.
