### ISSUE TITLE
Can't add a block app to admincp.index

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#645]
Hi,

I'm trying to create an app that will add a block to admincp.index

The code used is this:

```
new Core\Block('admincp.index', 1, function(Core\Block $block) {

$html= "HELLO";

	$block->title(_p('Load System'));
	$block->content($html);

});

```
But I get the error that you can see in the attach file. If I change the controller to another one it works fine, only admincp.index gives this error.

Thanks
![error](https://cloud.githubusercontent.com/assets/1458586/10603270/048e4cbc-7715-11e5-8c35-98922d51d0f3.jpg)

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/294

**Comment by Data66PF** [comment]
Please post this info in your other bug for this. Thank you!

**Comment by AnthonyKing** [comment]
@cespiritual one of your apps crashed my website, the load system app. i clicked get it, then #654

**Comment by Data66PF** [comment]
For those looking, this is not for posting bugs of third party developer's apps. Please contact them via their support or at my own scripttechs site as he is on there too.

**Comment by AnthonyKing** [comment]
i'll post a feature request to help contacting developers

**Comment by Data66PF** [comment]
We already have plans for making Pages on the forum for developers. :) Otherwise, you can contact him via his posted method or on scripttechs as he is there.

**Comment by AnthonyKing** [comment]
ok thank you

**Comment by Data66PF** [comment]
You're welcome. We hope to have improvements done soon for everyone. :) Things are in the works.
