### ISSUE TITLE
Not able to remove the "Site Name" Text

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#646]
"user1's quiz from October 20, 2015: rszfjkdsfjdsej. Take Free Fun Quizzes & Tests. Cool Online Fun Quiz & Test. Fun Quizzes and Fun Tests by Site Name."

when i share the quiz in facebook the description shows "Site Name".

How can remove the "Site Name".

I changed the site name in Setting. But the above issue is still there.

**Comment by Data66PF** [comment]
Facebook sharing is not part of the V4 script now. You can use my Buffer app that shares to fb, twitter, etc. As far as the default sharing from V3, that is not supported in V4.

**Comment by Data66PF** [comment]
I'm going to confirm this though as it doesn't work in Buffer either. The sitename phrase appears not to be picked up properly when it works fine in v3 for default and buffer. This could cause other issues with other apps or other site things that use the sitename phrase.

**Comment by Data66PF** [comment]
I can still reproduce this in 4.1.2

**Comment by neil96** [comment]
Fixed on V4.2.0
