### ISSUE TITLE
JavaScript error in theme admin

### ISSUE THREAD

**Issue by jpbu** [moxi9/phpfox#647]
File PF.Base/module/theme/template/default/controller/admincp/manage.html.php has a wrong jQuery selector (missing a closing bracket) in line 71:
`$('._colorpicker:not(.built').each(function()`
This causes a JavaScript error at least in Safari browser, causing some of the theme admin functions not to work properly

**Comment by Data66PF** [comment]
This is my line 71 of the same file in v4.0.9 client version
`$('._colorpicker:not(.built').each(function() {`

**Comment by jpbu** [comment]
I posted the line as is, what I wanted to say is that the jQuery selector must be
`$('._colorpicker:not(.built)')`
instead of
`$('._colorpicker:not(.built')`
The bracket inside the selector with the quotes is not closed.

**Comment by Data66PF** [comment]
I see that. I also see it in other places in this file like this. I wonder why it causes an issue in safari but not in other browsers. I'll leave this open for a core developer to see as I can't reproduce any issue with admin functions using win 10 and other browsers.

**Comment by neil96** [comment]
Fixed in v4.0.10 staff note *YPFOXNEUTRON-106*
