### ISSUE TITLE
Binary files returned incorrectly - always delete output buffer before writing file?

### ISSUE THREAD

**Issue by jpbu** [moxi9/phpfox#649]
I encountered a bug that uploaded profile images were not returned correctly, the binary content apparently having one additional byte at the beginning. I was not able to figure out the root cause for this, but adding `ob_clean` before writing out the file content with `echo @file_get_contents($sPath);` in file PF.Base/include/library/phpfox/phpfox/phpfox.class.php solved the issue on my dev machine. I also found several online sources calling this as a best practice when writing out files in this manner.
Would it do any harm to add this clean operation to the product?

**Comment by Data66PF** [comment]
Is this still an issue in 4.1.2?

**Comment by jpbu** [comment]
I think it is fair to close this bug, since it wasn't answered or analysed within two months and it is unclear whether this was a specific problem on my environment.
