### ISSUE TITLE
Avoid using web urls when referencing local files

### ISSUE THREAD

**Issue by jpbu** [moxi9/phpfox#650]
I encountered a problem with profile image cropping when testing on a local dev machine where I had turned on basic authentication. It turned out that the code in PF.Base/module/user/include/component/controller/photo.class.php calls `@getimagesize` with the external web url (http://.../index.php/file/pic/user...) of the image, and this failed due to missing authentication.
For both performance and security reasons, I think it would be better to reference the file by the local file system path, given that it is already stored on the server.
Other points in the code might be affected as well, so there should be a general utility to transform external urls in the internal path.

**Comment by phpfoxdev** [comment]
Hi, just make sure we are on the same page, "where I have turned on the basic authentication", could you detail detail on what you changed here, in comparison with default setting?

**Comment by jpbu** [comment]
Hi, I enabled basic authentication in apache http server to generally secure my local dev environment, see e.g. https://wiki.apache.org/httpd/PasswordBasicAuth. This way access to all resources on the http server is protected by a login popup displayed by the browser.

**Comment by Data66PF** [comment]
Is this still an issue with 4.1.2?

**Comment by jpbu** [comment]
Since this was more like a general improvement suggestion, I don't think it is fixed since nobody commented on this bug ticket (unfortunately I can't double check in the source code on github since it is gone and I don't use phpfox any longer). I think it is fair to close it as "won't fix" though.
