### ISSUE TITLE
my Draft Blog Can't Edit neither able to delete.

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#651]
I create a blog and save as Draft.

again i open the blog in my blog option.

but the issue is that when i click the option button the menu appearing( not showing the menu completely. Over lapping the left side menu bar)  edit and delete. but i'm unable to locate my mouse there.

please check and confirm

**Comment by Data66PF** [comment]
Please state what browser, OS, screen resolution you used and please provide a screenshot.

**Comment by haisay** [comment]
I used Google chrome and Mozilla both of them showing the issue.
OS: Window7.

**Comment by phpfoxdev** [comment]
will be released in next version

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-89 *
