### ISSUE TITLE
two recaptcha 

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#652]
![Uploading Screenshot (1199).png…]()

**Comment by AnthonyKing** [comment]
![screenshot 1199](https://cloud.githubusercontent.com/assets/12142143/10652667/ba9aa3ea-7858-11e5-8082-460ec566fd44.png)
how do i prevent this from happening?

**Comment by Jinkers** [comment]
This isnt a bug with the core product and should be posted at the community. But it looks like this is a cache issue. Have you cleared both site and browser?

**Comment by Data66PF** [comment]
Please post recaptcha issues in the bug tracker for recaptcha.

**Comment by muhammadnaeemahsan** [comment]
same issue with us

**Comment by Data66PF** [comment]
https://github.com/moxi9/reCAPTCHA You would need to post it there.

**Comment by AnthonyKing** [comment]
@Jinkers after i hit refresh twice, the error goes away
