### ISSUE TITLE
Messages Reply Problem Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#653]
when i want to reply to someone and i click on message than text input type box position disappear into left and right screen. Also menu link in not working and keep scrolling background area
i am testing it on PF Community website Android OS chrome browser.

![screenshot_2015-10-08-15-54-16](https://cloud.githubusercontent.com/assets/13433124/10663820/0d2e44e4-78dc-11e5-9562-cdc4c09d709a.png)

**Comment by neil96** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-104*
