### ISSUE TITLE
New app causes website shutdown

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#654]
i tried to install an app to see my system load (RAM and CPU), when i clicked GET IT i got an error, and now i can not access my site.
![screenshot 1201](https://cloud.githubusercontent.com/assets/12142143/10676063/fa870cf4-7903-11e5-9643-22fd1f8b0e62.png)
![screenshot 1202](https://cloud.githubusercontent.com/assets/12142143/10676064/faa3326c-7903-11e5-9008-84802cbc7890.png)

**Comment by AnthonyKing** [comment]
and when i debug it, i get "Missing "phpfox.json" file."

**Comment by Data66PF** [comment]
This is not for posting app bugs.

**Comment by Data66PF** [comment]
App works fine for me. It is heavy so don't install it on servers that don't have the resources.

**Comment by AnthonyKing** [comment]
i managed to install it, the only way i could contact the developer was through the issue they posted on github(i think you saw the notification), 

And for those that might experience the same issue. i went to PF site/apps and deleted the app file

**Comment by cespiritual** [comment]
Anthony, please... contact me at: contacto @ paxcreative.pt
