### ISSUE TITLE
Status share bug

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#655]
Hello World!

 **Try share that:**

``` şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şi şişşşşşşşşş şşşşşşşşşş şşşşşşşşşşşşşşşşşşşşşş```

When I share it on my website, it's showing an error like this:
> "TypeError: e is undefined"

When I share it on the phpfox community forum, it doesn't display my shared status.. 

**My master language is English on my phpfox website**

**Comment by phpfoxdev** [comment]
will be released in next upgrade

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-112 *
