### ISSUE TITLE
Hashtag Bug

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#656]
I know, hashtag module is updated but still has problem

**For example:**
I wrote 2 status..
**First:**
> #Şaka lan!

**Second:**
> #şaka lan!

If a letter is an Turkish character like (ş), it's case-insensitive
I clicked #şaka hashtag and I saw only #şaka with lowercase .. Not #Şaka ...

**Comment by phpfoxdev** [comment]
will be released in next upgrade

**Comment by amarsaurabh** [comment]
I had activated this hashtag in my phpfox, it was working fine.  But, after I installed BASE5 theme from  the phpfox store, it stopped working

**Comment by Data66PF** [comment]
You can't use a v3 theme on a v4 site.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-114 *
