### ISSUE TITLE
Forum Title Bug: html code

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#660]
If a forum thread has a title with (') etc. it looks like this:

![2015-10-23_13-31-56](https://cloud.githubusercontent.com/assets/13890542/10690450/a63ad91e-798a-11e5-8778-e9bd4cf17df9.png)

**Comment by Ylmzef** [comment]
It's not SEO friendly also it cant be desinged for working as special characters issue in title tag.
I hame same issue with chrome 46 and windows 10 on pf community.

**Comment by perayknox** [comment]
Also on the link.. You can see the url

**Comment by Data66PF** [comment]
Ok I'll leave this open for another dev to check but before it was marked working as designed as it's always been this way.
