### ISSUE TITLE
responsive bug

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#661]
I know, you said it:

> "it's not a bug" 

**but**, I think, it's a problem.. Please fix it.. Everything is okay on profile but there is a responsive bug when I visit the homepage/feed.

It means, it is feed's css/less problem.
**please note that**: it's same on my asus zenfone 5 and iphone 5s too..

![2015-10-23_13-48-14](https://cloud.githubusercontent.com/assets/13890542/10690779/d2cf477e-798c-11e5-9a6d-edc19161bdec.gif)

**please note that**: it's same on my asus zenfone 5 and iphone 5s too..

**Comment by Data66PF** [comment]
Please search before posting. Duplicate #574

**Comment by perayknox** [comment]
I dont understand.....!
It's a bug but you're saying not.. Why you're not fix it?

**Comment by Data66PF** [comment]
It is a duplicate. I said that it is a duplicate and linked the confirmed bug for you. Please follow the other bug reported for this as that one was already confirmed. Please search the issue tracker before posting so you don't post duplicates. Thank you.

**Comment by tikklyric** [comment]
@Data66PF it's bad for mobile users.. it must be fixed..

**Comment by perayknox** [comment]
@Data66PF Sorry, I saw this duplicate issue. It was "reproduce".. But you changed that to "bug" 8 days ago.  It's okay now.

**Comment by Data66PF** [comment]
@tikklyric please read my comment. I said this is a duplicate. I linked the confirmed bug that will be fixed. Please be sure to read our comments when we close something and follow to the original bug if something is a duplicate.
