### ISSUE TITLE
Collapsible blocks issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#662]
When you click on block tittle it's closing/opening all block.

![download](https://cloud.githubusercontent.com/assets/8562514/10708153/e097bec8-79fe-11e5-86f2-53c5342b3bc1.png)

**Comment by tikklyric** [comment]
It's not an issue. It's a function. :)

**Comment by Ylmzef** [comment]
@Data66PF Can you check this please?
On v3 you can collapsible per block but now it's not so.
When you click on "Recent Discussions" it's closing "Sponsored" too.

**Comment by Data66PF** [comment]
I can see the issue in the forum. It seems to close the sponsored block content. Weird. I tried on the core.index-member and those don't close the sponsored block. I think it's just in the forum it is doing this but I'll confirm it.

**Comment by Ylmzef** [comment]
On other pages too please check: http://community.phpfox.com/music/

**Comment by Data66PF** [comment]
I'm sure they will check. I was just confirming it. :)

**Comment by Data66PF** [comment]
Fixed in 4.0.10.

**Comment by Ylmzef** [comment]
It's still issue on pages like as for followers block.
When i click on it the box apear but the block closing.

**Comment by Data66PF** [comment]
Followers block? Is that a third party block? If so, please see that developer. If not, please post a new issue for this.

**Comment by Ylmzef** [comment]
It's not 3th party bock: http://community.phpfox.com/phpfoxproducts/

**Comment by Ylmzef** [comment]
So you use on community  3th party bocks too?

![download](https://cloud.githubusercontent.com/assets/8562514/11263931/8413b666-8e8f-11e5-888b-1ea45751bc74.png)

**Comment by Data66PF** [comment]
No but that's why we asked what block you meant. Please open a new bug report for this issue. Please show that screenshot you just showed and that it is for the Pages followers block. I misunderstood what you had said for the location. The screenshot that you just put is more helpful to see which block to test. Thanks.
