### ISSUE TITLE
News feeds/Satus updates issues

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#664]
Im getting status updates issue after upgrade to 4.0.9.
On profile page when i scroll to end of page im getting "There are no new feeds to view at this time." and can't see old updates.
On pages/groups page i can't see any posts/status updates i get there too "There are no new feeds to view at this time."

Upgraded site
v4.0.9
chrome 46
windows 10

**Comment by Data66PF** [comment]
How far back are you trying to see? I checked my profile, http://community.phpfox.com/profile-data66/ and kept scrolling back but didn't want to stay there a long time trying to scroll down further to the end of time lol. How far back do I need to go to see?

**Comment by Ylmzef** [comment]
I posted number from 1 to 50.
You can check it: http://community.phpfox.com/darbeg/

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/328  confirmed at the community that the issue I presented before is still an issue as noticed in the client's feed with the missing feeds.

**Comment by Ylmzef** [comment]
Now it's totally can't load the feed on profile page when click on view more button or scroll down.
This realy critical bug need fixed ASAP!

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-123 *

**Comment by Ylmzef** [comment]
You forget to mark as fixed.
