### ISSUE TITLE
PhpFox

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#666]
Well I would like to report some bugs.
1)#phpfox-videofeed In the video tab I clicked to play video and then I click in my profile to stop the video from playing but the video dialog disappears but I can still listen the audio of the video even if without seeing the video please Fix it....  If I may also recoomend can you please let our user play video while the video is still between the feeds without poping up still in the feed. and add an option to resize or minimize video player for videos which is uploaded to my site.
2)I sent a message to a member saying "hi" 3 or 4 hours ago and he sent me "hello" message before 2 hours I just read it 45 minutes early but it keeps pooping up saying I have a new message even now each time I REFRESH MY PAGE?
3) the ad box in the right side of the window gets to hide while I scroll to see more feed it scrolls with the feed.In this case if the ad's get to hide how are going make money using advertise please fix this error. Make the ad get to stay where they are but the feed can get scrolled PLEASE FIX this error. ad has to stay in the right side.
4) While you are posting by writing in the What's Up? While you are writing a long continuous word Firefox button scroll bar get to minimize while you are writing and after you posted it its arrangement is very weird because it is not how a paragraph you should be post please fix error.
http://community.phpfox.com/Brook/ Oct.21 Post even didn't look like as other posted please fix
5)The whole phpfox website is not compatible with java based mobile phone browsers Opera mini8 see it your self you can login see feeds in arranged way but you can't still see Phpfox menu or other thing even you can't still open see more feeds tab,like something,comment something,share something from java based phone using opera 8 or UC browser or other browser. Please fix this make phpfox compatible with other mostly used browsers for java based phones.
6) Add Dislike button next to like button Please..........in everywhere
7) Page administrator can't see how many like, share, or views the get from there page Please if you can add some thing for page Administrators to use as an Admin of Page.
8) Page and Groups are 2 different things so please differentiate them please page can be created by any one but groups must be created by members and also it must be easy to create a group and and groups must be added to Menu too.

**Comment by Data66PF** [comment]
I see you already posted these. Please note we take one issue per report and please only post bugs, feature requests are posted at the forum.
