### ISSUE TITLE
)#phpfox-videofeed @Bug

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#667]
#phpfox-videofeed In the video tab I clicked to play video and then I click in my profile to stop the video from playing but the video dialog disappears but I can still listen the audio of the video even if without seeing the video please Fix it.... If I may also recoomend can you please let our user play video while the video is still between the feeds without poping up still in the feed. and add an option to resize or minimize video player for videos which is uploaded to my site.

**Comment by Data66PF** [comment]
Please post bugs for apps in the app's issue tracker. This one is just for bugs with the core product.
