### ISSUE TITLE
Ad's Bug

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#669]
the ad box in the right side of the window gets to hide while I scroll to see more feed it scrolls with the feed.In this case if the ad's get to hide how are going make money using advertise please fix this error. Make the ad get to stay where they are but the feed can get scrolled PLEASE FIX this error. ad has to stay in the right side

**Comment by Data66PF** [comment]
Please post feature requests in the community as this is how it is designed. At this time, we need to focus on bugs that make the script break and not on feature requests to change how it already works. After we are done fixing bugs that break the script, it is possible we will then go to the community feature request section and see what enhancements we can then add.
