### ISSUE TITLE
Settings in theme for apps

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#67]
When making apps, we need a way to check module (for old modules) and user group settings. This used to work in the html.php file:

```{if Phpfox::ismodule('blog') && Phpfox::getUserParam('blog.add_new_blog')}```

It no longer does.

**Comment by RaymondBenc** [comment]
Reopened issue until we add info to our docs about it.

**Comment by Data66PF** [comment]
I've tried this based on the example and it isn't working for me. It returns blank though the user is the admin and the module is active.

**Comment by RaymondBenc** [comment]
Can you paste sample code and what file is it being added to?

**Comment by Data66PF** [comment]
i'll email it to you
