### ISSUE TITLE
Posting  #Bug

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#670]
While you are posting by writing in the What's Up? While you are writing a long continuous word Firefox button scroll bar get to minimize while you are writing and after you posted it its arrangement is very weird because it is not how a paragraph you should be post please fix error.
http://community.phpfox.com/Brook/ Oct.21 Post even didn't look like as other posted please fix

**Comment by Data66PF** [comment]
Please post a screen shot.

**Comment by Data66PF** [comment]
Please post a screenshot or please tell us the word as I can't think of a word that is long enough to cause an issue. Please make sure you are testing actual words and not just random letters as that wouldn't be a normal representation of anything someone would do on a website.
