### ISSUE TITLE
Phpfox Comitabality #Bug

### ISSUE THREAD

**Issue by GreenMan123** [moxi9/phpfox#671]
The whole phpfox website is not compatible with java based mobile phone browsers Opera mini8 see it your self you can login see feeds in arranged way but you can't still see Phpfox menu or other thing even you can't still open see more feeds tab,like something,comment something,share something from java based phone using opera 8 or UC browser or other browser. Please fix this make phpfox compatible with other mostly used browsers for java based phones.

**Comment by Data66PF** [comment]
Please search for bugs posted as this is already posted. Please be very specific if you have a specific bug that is not already posted as this is too general. Note that we are enhancing the mobile aspect.
