### ISSUE TITLE
Can't create pages inside admincp

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#675]
Hi,

I'm trying to create a page inside admincp for a new app.

First step was to create the admincp menu by creating the file admincp.component_controller_index_process_menu.php under the hooks folder with this code

```
<?php

$aMenus['<i class="fa fa-diamond"></i> Monitoring System'] = 'admincp.monitoring';
```
Then on start.php I add this code:
```
new Core\Route('/admincp/monitoring', function(Core\Controller $controller) {
	$controller->block(2, function(Core\Block $block) {
		return 'Empty Block...';
	});
	
	return $controller->render('index.html');
});
```
And I get this error message I send in attach.

Is this a bug, or am I missing something?

Thanks

![error](https://cloud.githubusercontent.com/assets/1458586/10725735/321cc9be-7bc6-11e5-9a80-5e8bf3e753a8.jpg)

**Comment by Data66PF** [comment]
Is this still an issue in 4.1.2?

**Comment by cespiritual** [comment]
Hi,

Yes, I have just tested on 4.1.2 and I still get the error.

Thanks

**Comment by neil96** [comment]
To create a page inside adminCP, please follow these steps:
- File app.json, add these code:
```
 "admincp_menu": {
    "monitoring":"your_app_name.monitoring"
  },
  "admincpMenu": {
    "monitoring":"your_app_name.monitoring"
  }
```

- File  start.php, add these code:
```
(new Core\Route\Group('admincp/your_app_name', function () {
    new Core\Route('/monitoring', function (\Core\Controller $Controller) {
//your code here
        return $Controller->render('index.html');
    });
}));
```

**Comment by cespiritual** [comment]
Hi,

Will this work on 4.1.x or is this solution only for the future 4.2?

Thanks

**Comment by neil96** [comment]
This feature already worked before. New menu will display below your App icon, so we don't need icon.

**Comment by cespiritual** [comment]
I have ignored the other solution and use only this one given by you. I removed the hook for menu, also.

Then I added this to json:

´´´ "admincp_menu": {
    "Monitoring":"ces_monitoring_system.monitoring"
  },
  "admincpMenu": {
    "Monitoring":"ces_monitoring_system.monitoring"
  },
 ´´´

and this to start.php

´´´(new Core\Route\Group('admincp/ces_monitoring_system', function () {
    new Core\Route('/monitoring', function (\Core\Controller $Controller) {

        return $Controller->render('index.html');
    });
}));
´´´

But no menu shows on admincp.

Did I miss any step?

Thanks

**Comment by neil96** [comment]
Please try with this app: 
[phpfox-app-ces-monitoring-system-v1.zip](https://github.com/moxi9/phpfox/files/85485/phpfox-app-ces-monitoring-system-v1.zip)
It's working.
![screen shot 2016-01-11 at 16 27 37](https://cloud.githubusercontent.com/assets/15936115/12230102/6ce57608-b880-11e5-9b04-74e32073ab1f.png)

**Comment by cespiritual** [comment]
Sorry... I didn't express myself in the right way. What I need is to create a page inside admincp and not inside my app. I want to add a menu link to the admincp menu on the left, with an icon, that open a page in admincp to show my app.

Raimond told me in another thread that I need to follow the steps on the first topic, but I get that error message.

Thanks

**Comment by cespiritual** [comment]
Also I noticed that when I click on the link inside my app I get the same error message that show on the first topic. I didn't install yet your app, just follow your steps.
