### ISSUE TITLE
Cancelled members 

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#676]
There is still an option in admincp to list reasons for cancelling membership but no way to call the list

![2015-10-26 16_59_51-admin cp dashboard bdsm south africa _ uk _ usa _ london _ ny _ durban_ gaut](https://cloud.githubusercontent.com/assets/13656046/10732648/b9d5254e-7c03-11e5-9614-7213c097b26f.png)

**Comment by Data66PF** [comment]
Confirmed that we need to add the menu link  yoursite.com/admincp/user/cancellations/feedback/ to the default script for clients to see the cancellation feedback as it still works but is not anyplace they can find now. It used to be there in V3.
