### ISSUE TITLE
forum post edit bug

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#677]
When I edit a forum post, it's link is invalid. 

![2015-10-27_00-25-52](https://cloud.githubusercontent.com/assets/13890542/10744375/19c46a30-7c42-11e5-9280-8d1724847d70.png)

**Comment by perayknox** [comment]
Updated:

![2015-10-27_00-25-52](https://cloud.githubusercontent.com/assets/13890542/10744421/85f81f12-7c42-11e5-8e40-45e7b12c08e5.png)

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-119 *
