### ISSUE TITLE
Mobile Google Adsense Slot Error

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#678]
I'm using Google Adsense (Responsive Ad slot)

**System**: Android Lollipop
**Browser**: Firefox for Android

![photo_2015-10-27_00-e35-57](https://cloud.githubusercontent.com/assets/13890542/10744535/4c1acb68-7c43-11e5-88d0-897379e47126.png)

**Comment by Data66PF** [comment]
Have you tried settings in Google for your ad? Are you using the latest Google code as they've changed some things recently and I had to remake my ads too.

**Comment by perayknox** [comment]
Yeap, I'm using the latest codes and I'm using also responsive ad. (Google AdSense)
