### ISSUE TITLE
Event Finish Time

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#679]
There is no event finish time. And when I create a new event, it's start time x, it's finish time x+7months..

![2015-10-27_01-18-47](https://cloud.githubusercontent.com/assets/13890542/10745285/fcf9478e-7c48-11e5-8146-762461f7144f.png)

**Comment by Data66PF** [comment]
Please search before posting. https://github.com/moxi9/phpfox/issues/256 as Ray mentioned there, the ability to add a finish time to events was removed but you could get a developer to add it back.

**Comment by ASNLifestyle** [comment]
it should be part of the core otherwise why even have it offered sounds kinda crappy when I pay over 300 USD for this. Just saying and others agree.
