### ISSUE TITLE
Not found error for site profile pics

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#68]
NetworkError: 404 Not Found mysite.com/file/pic/user/2015/07/09a308fc1abd0d60d3f181224ebc9d53_50_square.jpg

Testing on local and live. I looked and these images are not being generated. Permissions are fine. I checked the old setting for "keep non square images" since the templates seems to use those, and it seems to be set. I'm not sure if it's being used though as the images are not being made. For the profile photo I loaded, there is just one image made. No small images are generated.

If we go to admincp/maintenance/counters/ and update the user photos, it then gets the image but we have to do that every time we change our profile photo. Note that the profile photo does not show that it loads when clicking the upload button, it just spins and spins. Also reported by client in phpfox forum.

**Comment by RaymondBenc** [comment]
I think I know what the issue is. After you upload a new image do you create a thumbnail on the next step? Believe when we don't create one it does not create those smaller images.

**Comment by Data66PF** [comment]
It's not getting to the next step. It keeps staying on the loading thing, spinning and spinning.

**Comment by RaymondBenc** [comment]
ah okay. This might be something else then. Even on our community?

**Comment by Data66PF** [comment]
works on pf site. not working on my devs or the client's site.

**Comment by Data66PF** [comment]
Well system overview is not updating my version number. I have the most recent one that I can get, 4.0.1 but it shows the rc in overview. I know this is updated version as it doesn't show all those fun settings that it did before.

**Comment by RaymondBenc** [comment]
I'll give it a go on your dev site

**Comment by RaymondBenc** [comment]
I was able to upload and resize an image. When you have time try to download the latest built from this repo. Thanks!

**Comment by Data66PF** [comment]
Will this repo work on a client licensed site? That dev is a licensed one. Yeah this is odd. It does work today. It didn't work when I tested it yesterday.
