### ISSUE TITLE
language selection bug

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#681]
I'm using Turkish language and my master language is english.. But There is no Turkish language selection on user account settings page...

When I save the settings after change something, it selects the English again... It's bad.

![2015-10-27_02-19-53](https://cloud.githubusercontent.com/assets/13890542/10746297/0af831ac-7c52-11e5-9f0d-68aa2116a1e6.png)

**Comment by Data66PF** [comment]
Did you use a V4 language pack from our apps store? Only language packs made for v4 would work in v4.
