### ISSUE TITLE
Add Phrase button is again missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#684]
https://github.com/moxi9/phpfox/issues/282
That fix has been unfixed as v4.0.9 does not seem to have the add phrase button as a client reported to me and as I confirm on my 4.0.9 live test site. Please test with client version. It appears that the recent fix was not brought over with the 4.0.9 updated files. Please do note to test with client version as the fix was to remove the techie only button to allow it to show on client sites.

**Comment by RaymondBenc** [comment]
If I got into the Community AdminCP to **> Settings > Language**

I get on the top right hand menu: New Language | New Phrase | Manual Import | Find More Language Packs

What do you get on your live site?

**Comment by Data66PF** [comment]
None of that shows on my live 4.0.9 client version. It shows on my tech version though.

**Comment by one44** [comment]
Working for me on upgraded site from 3.8
![2015-11-06 12_12_10-bucket3 jpg 100 after taxes stolen by corruption and self enrichment and was](https://cloud.githubusercontent.com/assets/13656046/10994585/02ec72bc-8480-11e5-8335-47c271fd7a83.png)

**Comment by Data66PF** [comment]
Really odd as a client had posted to me and their site doesn't have it and my development site also doesn't have it, from the download in the client account. I'll grab the github client download and see if there is a difference.

**Comment by one44** [comment]
There are a lot of strange on off issues lol

**Comment by Data66PF** [comment]
Loading the files from Github has restored all of the buttons. I'll close this for now but if they disappear again, we'll need to look into the issue.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-684 *
