### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#685]
i don't know how to explain this, but i want to know how to prevent this from happening again
![screenshot 1214](https://cloud.githubusercontent.com/assets/12142143/10806414/c26b42c0-7ddd-11e5-9e86-7c62419a27aa.png)
![screenshot 1215](https://cloud.githubusercontent.com/assets/12142143/10806415/c2bcddd8-7ddd-11e5-9aa8-8f7006ed652a.png)
![screenshot 1217](https://cloud.githubusercontent.com/assets/12142143/10806450/0ec707e4-7dde-11e5-9261-3830d1d9a873.png)

**Comment by Jinkers** [comment]
Are you currently updating any files or doing anything in a different tab that is linked to your PHPFox install?

**Comment by Data66PF** [comment]
Please ask questions at the community. This is not a bug.

**Comment by AnthonyKing** [comment]
i was deleting files in file manager
