### ISSUE TITLE
v3 app's page still on v4

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#686]
Before upgrade to v4 i had pages for apps on v3
After upgrade to v4 still have the pages under profile and when i click the page it's can't accessible.

**Comment by Ylmzef** [comment]
Stil waiting for this issue.

**Comment by Data66PF** [comment]
Confirmed in 4.1.2 testing.

1. have a v3 site and make a few test apps in it. 
2. View your profile and you will see those test apps have Pages for them, which is correct as v3 apps make Pages too.
3. Upgrade the site to 4.1.2
4. View your profile after the upgrade and you will see your test apps listed in the Pages but you can't view them as these should not show up and they don't work.

**Comment by Ylmzef** [comment]
Thanks!

**Comment by Ylmzef** [comment]
@neil96 @phpfoxdev @Vivian-phpFox @RaymondBenc @robert9592  can you fix this for v4.2.0 please?

**Comment by Data66PF** [comment]
Please do not tag everyone.

**Comment by Data66PF** [comment]
Status on this @Vivian-phpFox ?

**Comment by neil96** [comment]
Fixed on V4.3.0
