### ISSUE TITLE
Can't post link in status post

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#687]
At the PF community and on my test site 4.0.9. It is not possible to post a status share link such as http://scripttechs.com when typing in the url. This worked previously. I see, in developer browser debug a 500 internal server error or 400 bad request for both sites as it seems not to be able to find the ajax. 

POST http://community.phpfox.com/static/ajax.php 400 (Bad Request)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)http://mysite.com/static/ajax.php

Using short urls or long urls makes no difference. This worked on 4.0.8 without issues. I do not know what is causing this but it's at a client site, at the community and at my live test site using client version 4.0.9.

**Comment by Data66PF** [comment]
Marked critical as I don't know what else this could be impacting.

**Comment by aakash83** [comment]
working fine for me  on ver 4.0.9 . i can post any link in status share.

**Comment by Data66PF** [comment]
I've not been able to on the community or test site and a client reported it.

**Comment by Data66PF** [comment]
If typing the url manually, it does not work. If copying and pasting, it works. Please test by manually typing in the url. This used to work.

**Comment by aakash83** [comment]
i can post link by manual typing also. but  not always it works. when i use https  sometimes it shows a message that  the status is submitted but will be shown after admin approval ( but i am already posting with admin account). sometimes when i manually type a link  and click the share button it don't respond. however most of the times it works fine and I can post links by manually typing and by copy paste ( all type of links  http, https  and just www.)  another thing  is that  if we   share a link  without  www   it is not  treated as a web link and in feed  it shows like  simple text.

**Comment by Data66PF** [comment]
Thanks for testing. It needs to be looked at as the errors are at the live community and my live test site. I will test more on my local test sites too. Something odd is happening with these.

**Comment by perayknox** [comment]
It's working only for paste url..

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-131 *
