### ISSUE TITLE
Users profile photo album issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#688]
If users havent any photos except created album photos, photos tab not showing under profile.
Example: users have only profile photos under "Profile Pictures" album than the photos tab not showing in profile menu. Also there no albums for cover photos and timeline photos.

**Comment by Data66PF** [comment]
I'll confirm this but I believe it has always been this way as the profile photo album is a special internal album.

**Comment by Data66PF** [comment]
Fixed in v4.1.0 *staff note YPFOXNEUTRON-193 *
