### ISSUE TITLE
Ajax Problem, I found the source of the problem !! 

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#689]
I'm searching about this problem and this problem is everywhere... 

Forum ajax problem is only for Turkish language or another latin-ext characters..

![2015-10-30_14-55-58](https://cloud.githubusercontent.com/assets/13890542/10845333/a34a9bb0-7f0f-11e5-9314-d1eb236767a2.png)

when I change this word to the "tamamini", it's working fine..

**Comment by perayknox** [comment]
![2015-10-30_15-03-54](https://cloud.githubusercontent.com/assets/13890542/10845314/78302b34-7f0f-11e5-9998-098a2f5bcd31.png)

**Comment by Data66PF** [comment]
please do not post duplicates. Please post this to your other bug report for ajax issue.

**Comment by Data66PF** [comment]
Please note that we do not support third party products and please ensure you are using a v4 language pack.

**Comment by perayknox** [comment]
There is a ajax problem, are you understand it? It's not about language pack because I've tried with fresh install with v4 pack.

**Comment by perayknox** [comment]
For example:

Character limit is 5
My word is application (11 letters)
It will convert to : "appli" because there is 5 letter limit.

But if it contains turkish letter like: karışıkmış
It will convert to: "karı?" 

because a turkish character is exactly two characters for php!!!

You can learn this with substr (php function)

If you will use turkish character, you should use mb_substr!

**Comment by Data66PF** [comment]
I had mentioned to please keep this to your other bug report for ajax as this is a duplicate. Please post in your original bug report that you made for this issue.

**Comment by perayknox** [comment]
But you closing my all issue reports so Im opening new issue!

you ve been read this problem so why you dont report this bug still and saying post it to the original post..

ASUS'umdan gönderildi.

-------- Orijinal Mesaj --------
Başlangıç:Data66 <notifications@github.com>
Gönderme:Sat, 07 Nov 2015 18:55:03 +0200
Bitiş:moxi9/phpfox <phpfox@noreply.github.com>
Bilgi:perayknox <eyup.c.elma@gmail.com>
Konu:Re: [phpfox] Ajax Problem, I found the source of the problem !!  (#689)

**Comment by Data66PF** [comment]
I didn't close the other one. Please go look at the one I linked. It is not closed. It is still open.

**Comment by Data66PF** [comment]
If you look at the right box, on the bug report here https://github.com/moxi9/phpfox/issues/658 the status is Cannot Reproduce. It is not closed though. A but that is closed will show closed at the top of it on the left like this one shows.
