### ISSUE TITLE
Many Twemoji Images Fail to Display

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#691]
The Twemoji add-on does not display all selected images. This is a brand new virgin install as the add-on was intended to install and operate.

Used Firefox 41.02
On Windows 7 Professional
PHPfox 4.09
Test Ran using smiley button under forum comments.

1. Here is the emoji selection dialog that opens when clicking on the smiley button:
![whats available-fullset](https://cloud.githubusercontent.com/assets/14284710/10864345/192069c2-7fe3-11e5-9f61-932601286a6e.png)
Note that all images show (dl'd successfully by the browser).

2. Each emoji was selected from left to right, in descending rows until all were selected into the forum comment area as follows:
![what was selected-fullset](https://cloud.githubusercontent.com/assets/14284710/10864352/6cc3f058-7fe3-11e5-80e6-af976054054b.png)

3. When the forum comment was submitted, here is what displayed:
![what displayed-fullset](https://cloud.githubusercontent.com/assets/14284710/10864356/8812e882-7fe3-11e5-89ce-d2c19fc04c48.png)
Note that although many emoji images are missing, their placeholders are not.  The system reserved a space for them, however the placeholder was never populated with the emoji.  Firefox web console does not even show that access to a url was attempted for the missing object. It does however for the successful images.

4. Emojis that failed to display: (circled).
![what did not display-fullset](https://cloud.githubusercontent.com/assets/14284710/10864374/1831061a-7fe4-11e5-88e6-3feee30f2a5b.png)

Selecting any of these emojis on a onesey-twosey basis (not all emoticons at once) will track the same go or no-go results depending on which emojis are selected.

ALSO:  
The smiley button also appeared in the message edit dialog, but does not open the emoji selector at all.

**Comment by Data66PF** [comment]
This is only for the core product. Please post issues with apps in the app's github issue tracker.

**Comment by Gatsby-PF** [comment]
I have invested enough time in this.  I will debug my own version for my own purposes. Anyone in my operation who installs an App from the PHPfox admin panel from this point forward will be fired on the spot.

**Comment by Data66PF** [comment]
In case you change your mind, this is the issue tracker for twimoji. https://github.com/moxi9/phpfox-twemoji-awesome/issues . I don't know of a way to transfer issues or I would have.
