### ISSUE TITLE
500 Internal Server Error - Some users can't access the site

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#693]
Here is more about what it says:

500 Internal Server Error
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, webmaster@profoundprophecy.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

**Comment by Data66PF** [comment]
This is only for bugs, not for server issues. Please contact your host or post in the community at http://community.phpfox.com but don't post any sensitive information in the community as it is an open forum.

**Comment by AnthonyKing** [comment]
what changes did you make before you got that error
