### ISSUE TITLE
No way to disable a Phpfox default Module

### ISSUE THREAD

**Issue by anhbinu** [moxi9/phpfox#694]
On Phpfox v4, I try to disable Pages module, but no place to do this even I have accessed link like v3. List of core module not display. I have to disable via database by run the query
[code]update `phpfox_module` set is_active = 0 where module_id = 'pages'[/code]

**Comment by Data66PF** [comment]
Please ask questions at the community for things like this. This is not a bug. Default modules are disabled at AdminCP >> Maintenance >> toggle modules
