### ISSUE TITLE
Profile photo not displaying properly

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#697]
When a user don't have any profile picture phpfox creates a picture using characters from user name. but this picture is not displaying properly on mobile devices( tested with iPhone 6) and web browsers ( tested with chrome) . On home page it displays properly  but when viewing a user profile it don't.
Phpfox 4.0.9.

**Comment by Data66PF** [comment]
as mentioned in the other issue tracker about this, this is a duplicate. Please search before posting to avoid duplicates. https://github.com/moxi9/phpfox/issues/393
