### ISSUE TITLE
email subject page "{title"}  error

### ISSUE THREAD

**Issue by DuCarlion** [moxi9/phpfox#699]
received an email from a page like on phpfox V4 demo/community
**** liked a comment you made on the page "{title"}
the phrase looks broken
shouldnt the " be within or without the {}?
this appears to by why the title is not the page title perhaps?
this was email subject the contents appear to load the page title correctly
as is all else correct within the content. link etc
unsure however if a bug or is site specific and may need confirmation
signed up and posted on request
may be doubled due to time taken

**Comment by neil96** [comment]
Fixed in v4.0.10 staff note *YPFOXNEUTRON-143*
