### ISSUE TITLE
Problem with install v4

### ISSUE THREAD

**Issue by auzunov** [moxi9/phpfox#70]
When I am trying to install I see only "Loading installer" and rotating circle. Thats all.

http://community.phpfox.com/forum/thread/52025/problem-with-install-v4/

**Comment by RaymondBenc** [comment]
I am unable to reproduce this on my local install. Install cases are hard for us to debug here, get in touch with us [here](http://www.phpfox.com/contact/) and we get take a look on your install.

**Comment by Anna3anana** [comment]
Ticket 876.
