### ISSUE TITLE
Creating a Page in AdminCP  - Page Not Found Error

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#700]
Clients are having all sorts of issues making pages in admincp. I've just done several tests using 4.0.9 and firefox browser though I don't think it's browser related. The page works only one way.

WORKS:
1. Make the page title
2. Put content in the left

DOESN't WORK;
1. Put content in the left
2. Make page title

If we do it the second way, it will say the page cannot be found. We need to make this work both ways for clients. It seems that the second way has an issue with making the url.

**Comment by aakash83** [comment]
There is another problem with pages. I opened this issue about  4 months ago but at that time data did not considered it as bug. But it is a bug. if we create a page and use  php or  html code in it. when later we try to edit  that page  most of the php or html coding disappears.

**Comment by Data66PF** [comment]
Please keep bugs to one issue at a time. If you would link for me the bug you posted we can look again but we could have thought you meant the Pages module as that would not take html.

**Comment by aakash83** [comment]
it was very clear which module i was talking about. anyways i mentioned it in my post now.

**Comment by Data66PF** [comment]
That one was closed as you opened a new issue to separate the bugs. Where is the new issue you opened? I see Ray fixed some of those bugs in that report already.

**Comment by aakash83** [comment]
if you see at the end when i asked you about opening a new issue for this bug. your reply was to not open because you can't  reproduce it....

**Comment by aakash83** [comment]
anything else was fixed.

**Comment by Data66PF** [comment]
The only one left in that report was the notification one and it was also in another bug so it was closed. Your issue about adding html is not in that bug report. This is what is in that bug report:
1. When we try to modify the pages ( about us , privacy policy) and save them we got an error "Page is missing data" this happens even if try to make a new page same like about us etc.
2. I have two user accounts when i sent a PM to other account i am not getting any notification for new message.
3. I created an announcement but it is not appearing anywhere on the index page ( logged in and non logged in pages).
4. when we receive a notification about anything e.g. new friend request or post likes etc, the notification is not disappearing even we click on it . the blue counter remains there. i am having this issue on community.phpfox.com also.

Now you see why we ask for one issue at a time per report as it is easier to manage. Note that the bug you reference has nothing in it for adding html to the pages. Please open a report for that if there is not one so we can check it Thanks.

**Comment by aakash83** [comment]
https://github.com/moxi9/phpfox/issues/41#issuecomment-120495231

**Comment by aakash83** [comment]
just read  last two commentss

**Comment by Data66PF** [comment]
Again, we go by the original report and it had too many issues in it. Please post another bug or find the one for the html issue as this tracker here is not for that issue. Thanks.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-144 *
