### ISSUE TITLE
Creating Page in AdminCP - No Menu Made

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#701]
V4.0.9 any browser

Go to AdminCP >> Pages and click to Create A Page.
Enter a Title for the page.
Make sure the select for Add to Menu is at Yes.
![newpageaddmenu](https://cloud.githubusercontent.com/assets/6908282/11020202/10358c94-85e6-11e5-9a24-881057d4d4d2.png)

Enter any content for it.
Click Save and you will be brought to the front of the site, viewing the page. 
Go back into AdminCP.
Clear Cache.
Check front of the site and you will see no menu.
Check database phpfox_menu table and no menu has been made.

**Comment by one44** [comment]
Is menu not created when menu made in admincp using url for menu?

**Comment by Data66PF** [comment]
When making a page in Admin, it automatically makes a menu for you if you have it selected to. It worked fine in V3 but seems not to be working in V4.

**Comment by Data66PF** [comment]
Updated bug report with image.

**Comment by one44** [comment]
I am using 4.0.9 and find I make the page first then make the menu using the url generated and have no problems.

**Comment by Data66PF** [comment]
This isn't about adding one after. This is about the setting in the make a page that is not working. It is set to automatically make a menu. Clients are having problems as they expect it to make a menu since it shows the setting to make a menu. Yes, we can manually make one. That is not what this bug is though. Please test the setting shown.

**Comment by Data66PF** [comment]
This works to make a menu but the menu is not taking the page name for the menu it is taking the code or words from the left.

**Comment by robert9592** [comment]
Fix for v4.1.1

**Comment by Data66PF** [comment]
This is not fixed. It still shows the left content as the menu name.

**Comment by robert9592** [comment]
Fixed for v4.1.2
