### ISSUE TITLE
Blank (or Black) Share Bar

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#704]
Hi,

I noticed that when I click in the "share" button in a status update published by someone in a page a black panel appear however there is no option in there.

Take a look at the Screenshot:

![communities social networking community](https://cloud.githubusercontent.com/assets/5342341/11048789/083d4392-8721-11e5-9378-a58f3889c5b8.png)

**Comment by Jinkers** [comment]
I can confirm this is empty on the community and my installs. However, not sure if it designed this way or not since it is a page/group.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-148 *
