### ISSUE TITLE
None of the changes to Language Phrases reflecting

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#705]
I have a copied the language pack, defaulted it and renamed several phrases which include title of "Events", "Forums" etc., cleared the cache as well.. none of them are reflecting on my website. I understand some of the fields are still hard coded, however nothing at all changing is bit puzzling to me. I'm on latest patch of PHPFox V4. Is this really a bug or am I doing something wrong? If I am going wrong somewhere, can someone point me in the right direction or if its a bug, I believe it should be taken on high priority as nothing wrong (not even a single phrase is changed), so when is it expected to be resolved?

**Comment by Data66PF** [comment]
duplicate https://github.com/moxi9/phpfox/issues/226
