### ISSUE TITLE
Rating Photos is Missing but Setting in User Group is Still There

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#707]
We had a feature to allow photo rating in V3. Clients liked having this setting. The setting still shows in user group settings but there is no rating showing front end. We should consider bringing it back or removing the setting from user group settings. This is a client request to bring it back though.

**Comment by AnthonyKing** [comment]
this is a quote i got from somewhere "Any sale—from the smallest consumer item to the largest enterprise-wide solution imaginable—is about much more than simply providing a product or service. A sale is really about delivering a promise to the customer. Unfortunately, many companies have no idea what their sales promise is. They may have a company vision or a mission statement, but those don’t address the specific processes the company uses to deliver value to its customers."

**Comment by Data66PF** [comment]
Thanks but that doesn't apply to this bug that I've marked a bug. Please when posting comments make them relevant to the bug/issue itself. We are aware of client satisfaction and have many things planned that we will post about soon. Making comments and posts that don't pertain to the issue at hand can slow the developers from fixing them as our programmers are here just to program and fix code.

**Comment by Data66PF** [comment]
Fixed in v4.1.0 *staff note YPFOXNEUTRON-156 * Setting removed.
