### ISSUE TITLE
Editing Page in Admin CP , Coding disappears

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#708]
if we create a page same like about us or privacy in admin cp and use php or html code in it. when later we try to edit that page most of the php or html coding disappears.  I am using v 4.0.9 .

**Comment by Data66PF** [comment]
Using Chrome I can confirm that when making a static page in AdminCP I cannot see the code I had entered before. Tested by getting a game from miniclip games and posting the embed code. The code completely disappeared when I went to edit the page after.

**Comment by robert9592** [comment]
Fixed in v4.2.0
