### ISSUE TITLE
Email setting error would cause problem on some features.

### ISSUE THREAD

**Issue by levelel** [moxi9/phpfox#709]
If server failed to send welcome email to new user due to email server setting problem (or anything else that could potentially cause problem to email sending) would prevent new user to login to site after signing up. But the user account is still created, so he/she can still login after a refreshing of the page.

The same problem would cause page or button not responsive if that function triggers email sending. For example, when a user send a friend request, the send request button seems not function at all. However, the request has been sent anyway, it's just the email not sending freezes the button.

**Comment by Data66PF** [comment]
Is this something you have tested again in V4.0.10 which we just released?

**Comment by levelel** [comment]
Signing can go through now when email settings are incorrect. But sending friend request form does not appear at all. I guess it's some css layout problem, but not sure. I am using default theme with some color tweaking, no css modifications.

**Comment by Data66PF** [comment]
When you upgraded did you ensure to follow http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ final upgrade steps tutorial? Log in to view.

**Comment by levelel** [comment]
How to log in to the page? After signing up, still says "no permission to view"

**Comment by Data66PF** [comment]
The big announcement block at the top of the page mentioned to load a profile pic to be moved to verified user group, free.

**Comment by Data66PF** [comment]
Is this resolved after you followed the final upgrade steps?
