### ISSUE TITLE
Group Duplicate Feeds not longer available?

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#71]
the option is not longer available in feed module...

**Comment by Data66PF** [comment]
Closing as this is found in Settings >> Activity Feed

**Comment by Data66PF** [comment]
Reopened as another client can't find the setting but I have it in all of my testing sites. Upgraded and fresh installs. Client ran the find missing settings he says.

**Comment by lordofnos** [comment]
the setting has no effect on my site

**Comment by Data66PF** [comment]
I don't see it working if I post several blogs, they don't get grouped in the feed. I know it doesn't work with html5 mass uploader as it never supported that before. Will confirm.

**Comment by neil96** [comment]
This feature is removed on V4, Some upgrade sites still see this setting, but it won't apply when you change it. This setting will be removed in next version so you won't be confused
