### ISSUE TITLE
Footer issue on profile pages

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#710]
http://community.phpfox.com/darbeg/

![download](https://cloud.githubusercontent.com/assets/8562514/11167483/fb33379c-8b62-11e5-8af9-896925fa07e8.png)

**Comment by Data66PF** [comment]
Community is now updated to 4.0.10. The footer does move down for me when scrolling down, testing on chrome on win 10.

**Comment by Ylmzef** [comment]
It's still issue for me on community.
You don't need wait for timeline loading.
I have now more status updates think as a new users don't have any status update.

**Comment by Data66PF** [comment]
Please test with 4.1.1 as we cannot reproduce issues on our test sites. The community is not running 4.1.1 yet.

**Comment by Ylmzef** [comment]
"commented 20 days ago" it was for 4.0.9
