### ISSUE TITLE
send invite page not properly displaying on Iphone 6

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#711]
Send invite page has layout issue on iphone 6.
![image](https://cloud.githubusercontent.com/assets/406030/11168101/4b34f62c-8b81-11e5-827f-a59af7effd66.png)

**Comment by Data66PF** [comment]
Are you testing on our http://community.phpfox.com as it is running v4.0.10?

**Comment by aakash83** [comment]
fixed in 4.0.10
