### ISSUE TITLE
responsive layout issue while browsing "Pages" from mobile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#712]
While browsing my website from iPhone 6 i noticed phpfox (4.0.9) is displaying a normal  version of user created pages and not the responsive one. I further tested it on an Android phone and result was same.

**Comment by Data66PF** [comment]
Please update to v4.0.10 and test with default neutron theme after you ensure to run all of the steps for after upgrading, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ , log in to view that and upload a profile photo to move to the verified user group to see tutorials.

**Comment by aakash83** [comment]
fixed in 4.0.10
