### ISSUE TITLE
Apps listening complex on admincp

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#715]
So i can't follow which app new etc.

![download 1](https://cloud.githubusercontent.com/assets/8562514/11171774/cfbc015c-8bf8-11e5-9df9-9b9c1c2d5fb5.png)

**Comment by Data66PF** [comment]
This would be a feature request for the store and not a core bug. We are updating the store soon.

**Comment by Ylmzef** [comment]
It's loading fine on http://store.phpfox.com/apps but it's on admincp so i think this phpfox/admincp issue and nothing to do with store.

**Comment by Data66PF** [comment]
Yes but we are making changes to the store and so things will be changing soon with the views.
