### ISSUE TITLE
Can't Upload Cover Photo and Photo On Status.

### ISSUE THREAD

**Issue by Akony1** [moxi9/phpfox#717]
![untitled](https://cloud.githubusercontent.com/assets/15871954/11183233/32846824-8ca3-11e5-8c02-c737c48f004f.png)
When i upload cover a photo. It's show 100% and don't work. Just show loading.... in 5 min and Nothing. 
- Post Photo On Status like this. 
- I try firefox, IE or chmod 777 but it's also don't work.
Please help me fix it. I use PhpFox lasted version.

**Comment by Data66PF** [comment]
This is either a server or setting issue for your site. Cannot reproduce at the phpFox community or my testing site.
