### ISSUE TITLE
How to install video Feed App in PHPFox V4.0.7

### ISSUE THREAD

**Issue by fnfcircles** [moxi9/phpfox#718]
Can anyone guide me how to install Videofeed and Facebook Connect Apps in Phpfox V4.0.7.

I have a website http://fnfcircles.com/ and I tried to install videofeed app through Find new apps in Apps and add github url https://github.com/moxi9/phpfox-videofeed and click on Submit but error occurs (Unable to load the URL "https://raw.githubusercontent.com/moxi9/phpfox-video/master/app.json") 
I download Videofeed zip file and also tried to import File from my computer but circle continues moving and nothing happened.

Regards

**Comment by Data66PF** [comment]
Questions for how to do things should please be posted at the community at http://community.phpfox.com as the issue tracker is just for bugs. You need to get the apps from the store link in admincp rather than using the github method.
