### ISSUE TITLE
V4.0.10 App uninstaller lockout

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#720]
Firefox 42 on Windows 7 Professional
Younet Apps.

When going to uninstall an app, the system prompts for admin credentials but cannot move out of that screen to complete the uninstall once credentials have been entered.  No apps can be unistalled.

I was attempting to upgrade the younet core, uninstalling existing apps first.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/330 please see if it is the same issue but note that in the comments in my tests I had not changed the admincp url so I don't think it is related to that part of the report there. If this issue is the same, it can be closed and referred to that bug.

**Comment by Gatsby-PF** [comment]
Your last post says "This fix is something being fixed in the store. It's not with the core script but with a store issue and should be resolved soon".  This was a YouNet app that was installed independently without assistance of the stores installer.
I have uninstalled same apps successfully in V4.08 and 4.09. 

It is doubtful that the bugs are the same, but I will be running more troubleshooting tests to better isolate the ownership of this issue... Fox or YouNet upgrade incompatiblity. I will let you know what I find.

**Comment by Gatsby-PF** [comment]
The emoji app uninstalled without issue, but YouNet does not.  YouNet core is breaking the uninstaller with this upgrade.

**Comment by Data66PF** [comment]
Our techs are looking at the other bug too. If that is the same as this one, someone will fix it. If this one is not the same as that one, we can keep it open if you would like. Thank you for helping test this.

**Comment by Data66PF** [comment]
This issue might be something you need to check with the developer, YouNet as the emoji uninstalled fine so it could be they need to update the core some.
