### ISSUE TITLE
facebook mail empty phpfox V3

### ISSUE THREAD

**Issue by wetricks** [moxi9/phpfox#721]
hello, 
all the user wich created an account with facebook have the mail empty.
i can't find it in my admin cp and can't send us any email.

thanks to help me.

sylvain

**Comment by Jinkers** [comment]
Perhaps try posting at https://github.com/moxi9/phpfox-facebook/issues It seems this is more an issue the app than the core, especially if you are running 4.0.10.

**Comment by Data66PF** [comment]
Please post at the V3 issue tracker as this is only for v4 issues. https://github.com/moxi9/phpfox-v3-dist/issues
