### ISSUE TITLE
Pages Submenu Missing

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#722]
I noticed that the pages/groups sections is missing its "submenu" where are displayed my pages, friends pages and pending approval. Without this menu is almost impossible to know if there are some page that was not approved.

**Comment by Data66PF** [comment]
I can confirm this on my live development site.

**Comment by Data66PF** [comment]
Fixed in v4.1.0 *staff note YPFOXNEUTRON-184 *
