### ISSUE TITLE
Profile Pic Upload Problem Max 1MB GIF

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#723]
when i upload profile pic a gif image 1.23 MB in size then upload box keep Scroll in rounded circle.
it does't show any warning msg. to stop Box Scroll we have to Refresh page.Tested it on PF Community Chrome Browser Windows 7

**Comment by SalmanKhan86** [comment]
![profile pic upload bug](https://cloud.githubusercontent.com/assets/13433124/11233074/e0fda6da-8ddf-11e5-9cf6-9e9c7fc0a3fd.png)

**Comment by Data66PF** [comment]
I can reproduce an issue in 4.1.0 build 2 on my test site with it not stopping with an error to show the file is too large.

**Comment by robert9592** [comment]
Fixed in v4.2.0
