### ISSUE TITLE
missing sign in button on visitors page 

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#724]
In version 4.0.10 there is no option to sign in for mobile users . the visitors page only shows sign up form.  I tested it on my website and also phpfox community site  using iPhone 6. this issue is only for mobile version . In the top right corner there is a drop down menu but it don't work( not responding).

**Comment by PhpFoxJohnJr** [comment]
I have 4.0.10 installed and I when I go to the mobile version on a galaxy S5 I see on the top right side a bracket facing down for a dropdown box and when I click on it...it has the word login.  When I click on that it brings me to a login page....and I can login ok...

**Comment by Data66PF** [comment]
Fixed in v4.1.0 *staff note YPFOXNEUTRON-196 *
