### ISSUE TITLE
Menu Problem in Small Screen Size

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#725]
when i open site in Small Screen Device ex:- in ipad mini then side menu is not looking proper. A horizontal scroll bar comes in it.
Second Problem:- when i add or edit new Menu item ex: Market Place.then item name not appear properly.when i remove space in between them then its looks fine.Problem in space between them. 
Tested it V4.0.10 With Chrome browser Also in PF Community Site horizontal scroll bar Problem.
![menu space bug](https://cloud.githubusercontent.com/assets/13433124/11233889/879b6f1a-8de8-11e5-9064-59ac641cc5cf.png)

**Comment by Data66PF** [comment]
Please post one issue per ticket. Will check the side menu issue.

**Comment by Data66PF** [comment]
I'm unable to reproduce the first issue in our 4.1.0 to be released this week.
