### ISSUE TITLE
Empty private messages can be sent

### ISSUE THREAD

**Issue by Optiroot** [moxi9/phpfox#727]
Hello, I found a bug (I guess it is, because this I think shouldn't happen):
If you open private messages with someone and you just hit 'enter', it will send an empty message.
I don't think is too great as thing...

Tested with PHPFox V4.0.10!

**Comment by Data66PF** [comment]
confirmed. We need an error message to show if there is no text in the text box and a check to make sure it does not send a blank message. Tested at the live community.

**Comment by neil96** [comment]
I think we don't need error message, just disable submit form if message is blank.
