### ISSUE TITLE
No way to do SHIFT+SEND on private messages

### ISSUE THREAD

**Issue by Optiroot** [moxi9/phpfox#728]
I noticed that isn't possible to do SHIFT+SEND on private messages, which is a strange thing, because it' really useful...
I sugget to mark this as an en enhancement.
The problem born on mobile too, because there is no 'shift+enter' but we'll need a button to send a message, on mobile. While SEND, makes a new line.

Please, add this feature, at least in 4.1, as I saw that it is in production via blog.

Another question: I don't have understand good one thing of the post (http://blog.phpfox.com/2015/11/18/upcoming-site-updates-new-staff/), what does mean "We currently use a public repository on Github for our version control. With the development of our future versions we will be shifting to our internal git repository in order for our development team to have better control over core updates and our QC to monitor and test these changes."?

Means that this repo con GitHub will be closed? Or what?
At least will the developer edition still be here, on GitHub? Because someone could need it...
Thank you!

**Comment by Data66PF** [comment]
http://store.phpfox.com/product/944/shift-enter please use the free app. Please do not post feature requests in the github as it is only for bugs. Please post questions and feature requests at the community.
