### ISSUE TITLE
pictures on visitor index

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#73]
i can not change pics in index-visitors without modifying core files. is there any option i have missed?

**Comment by RaymondBenc** [comment]
This feature hasn't been documented yet, however if you feature any image from your Photo section it should show up there after cache has been cleared. Let us know if this works on your end.

Thanks!

**Comment by Data66PF** [comment]
In case you didn't see where to feature a photo, 
![feature photo](https://cloud.githubusercontent.com/assets/6908282/8650264/8c54cc80-293f-11e5-910d-fbcfbb0d4326.png)
Then look at front end as a guest.

**Comment by lordofnos** [comment]
works fine thanks
