### ISSUE TITLE
Invalid Page  URL still have a page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#732]
Ver 4.0.10
Phpfox  creates a fake page when you enter an invalid page URL  for example if you try  http://community.phpfox.com/pages/5678   . We can get a fake page which even have a display picture.  It should only show a page not found message.

**Comment by Data66PF** [comment]
Confirmed in v4.1.0 and we could even see Like or Claim for this fake page.

**Comment by aakash83** [comment]
not fixed in latest release.

**Comment by Data66PF** [comment]
We've not released this one yet. The fix was marked after our release. The fix would be for upcoming releases.

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-221 *
