### ISSUE TITLE
Date n time disappers when thread title is long

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#734]
If a thread is having a long title then when somebody reply to that thread  the feed entries  don't show date and time on our home page. an example from  phpfox community  site is shown below.
![image](https://cloud.githubusercontent.com/assets/406030/11274702/57182d54-8eda-11e5-8639-ef5060a13173.png)

**Comment by Data66PF** [comment]
Cannot reproduce in our v4.1.0 to be released this week.

**Comment by aakash83** [comment]
I took this screenshot from phpfox community site. and you can see  time is not displayed on your replies.

**Comment by aakash83** [comment]
I don't know which version phpfox community is running. but this is a fresh screenshot.
![image](https://cloud.githubusercontent.com/assets/406030/11338581/40f10fc8-91f5-11e5-99a4-c902617177be.png)

**Comment by Data66PF** [comment]
I mentioned that I tested V4.1.0 which is to be released this week. As it has not been released yet, the community is not running that version yet.

**Comment by aakash83** [comment]
not fixed in new version.

**Comment by Data66PF** [comment]
tested 4.1.2 and still cannot reproduce this. If you can reproduce it in 4.1.2 please open a new ticket.
