### ISSUE TITLE
Formatting problem with long titled forum threads

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#735]
Ver 4.0.10
when we have a long titled forum  thread it is not correctly displayed. for example I have a test post having  title "test8888888888888888888888888888888888888888888888888888888888888888888888888888888888888822222222222222222222222888888".   and this is how it looks.  
![image](https://cloud.githubusercontent.com/assets/406030/11274813/e6125d4a-8eda-11e5-83da-4c6ee17e9fd5.png)

**Comment by Data66PF** [comment]
Ok this one is needing to be fixed for each theme that comes with the script. Neutron is showing as above, with issues as seen. Our new Bootstrap has issues with the Recent posts block only, from my tests. 

Staff, please test and fix both themes, Neutron and Bootstrap for the issues you will see.

Tested in v4.1.0 to be released this week. Using chrome on win 10.

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-223 *
