### ISSUE TITLE
Pages Discussion Bug 1

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#736]
4.0.10
Steps to Reproduce 
Goto Pages >> Discussion >> New Thread
Message box has a defualt  text " Your Reply"  It should be  "Your Message" as this is the first entry .

**Comment by Data66PF** [comment]
Confirmed in V4.1.0 that we are using the default "reply" phrase. We would need to add a phrase perhaps

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-224 *
