### ISSUE TITLE
Collapsible page followers block issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#738]
https://github.com/moxi9/phpfox/issues/662#issuecomment-158005984

**Comment by Data66PF** [comment]
Though I can reproduce this in the community 4.0.10, I cannot reproduce it in my testing of our 4.1.0 to be released this week.

**Comment by neil96** [comment]
I can reproduce this issue and I fixed it on V4.1.1.

**Comment by Ylmzef** [comment]
It's still issue on v4.1.1
