### ISSUE TITLE
Using BBCode [color=#hexvalue] generates empty comment

### ISSUE THREAD

**Issue by Optiroot** [moxi9/phpfox#739]
I found a bug that if you do something like this in a comment:
`[color=#fff]Example text[/color]`
Gets generated an empty comment, instead of giving an error or showing the text colored.
But if you use the name of the color, it works.
`[color=white]Example text[/color]`
Makes the text white.

**Comment by Data66PF** [comment]
Confirmed in v4.1.0 but I don't know if this is a safety filter. Core developers will determine.

**Comment by robert9592** [comment]
Fixed for v4.1.1

**Comment by Data66PF** [comment]
Works in Neutron but not in Bootstrap in my tests.

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-227 *
