### ISSUE TITLE
Item permissions for content lacking community only permission

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#740]
In the permissions for content items, the scope of access jumps from friends only to all of the internet including entire logged in community.  Sites with culturally cohesive communities that want to share content among the entire community but deny the non-authenticated internet cannot do so now.  Please consider adding a community level scope of access control to the items permissions.

**Comment by Data66PF** [comment]
This would be a feature request and not a bug, however, I'll ask if we can keep it open to discuss it among the developers. Do I understand:

1. Site is not set to friends only community
2. Current content posting(blogs, photos, quizzes, etc) privacy options are everyone, friends, friends of friends, yourself, no one. 
3. You want to add the privacy option Community to the selection. This option would mean that all logged in users could see it.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#18
