### ISSUE TITLE
Notification tag not received by users

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#742]
I noticed that if someone tag another users in a post or in a comment, the tagged user doesn't recive any notification; and I know that this feature exists because is in the languages phrases:
`user.user_name_tagged_you_in_a_status_update`
And:
`user.user_name_tagged_you_in_a_comment`
There are strings to translate the notification text.
So it's a bug?

**Comment by Data66PF** [comment]
confirmed on v4.1.0 testing with bootstrap theme in a status share comment and tagging a friend in the comment. No notification was received in the site notification flag area.

**Comment by optiroot** [comment]
Any update about this?

**Comment by Data66PF** [comment]
Confirmed again in 4.1.2 tested with neutron theme.

**Comment by robert9592** [comment]
Fixed in v4.2.0
