### ISSUE TITLE
Photo album description cuts off the description at two and a half lines

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#744]
The photo album description text focus area allows description an multiple lines of text, but the text that gets displayed when browsing the photo album gets cut off at two and a half lines.

Opening the editor again confirms that the text has been chopped off past that point.

**Comment by Data66PF** [comment]
Cannot reproduce in our 4.1.0 which will be released this week.

**Comment by Data66PF** [comment]
Can you still reproduce this in 4.1.2? If so, please provide a screen shot.
