### ISSUE TITLE
Flavour isssue

### ISSUE THREAD

**Issue by AnthonyKing** [moxi9/phpfox#746]
when i use the flavour i created in version 4.0.9 i get a stalked web display, like button is out of place, when i hover on some links, i see a black lining at the top, plus the day after i upgraded to the new version i tried to use a new theme and i got an error and when i use the default theme with no custom flavour, everything is in it's right place
![screenshot 1245](https://cloud.githubusercontent.com/assets/12142143/11379338/85ee16f8-92f8-11e5-982c-6d1360b7551b.png)
![screenshot 1244](https://cloud.githubusercontent.com/assets/12142143/11379359/a59592ec-92f8-11e5-97b4-291a683b12b8.png)

**Comment by Data66PF** [comment]
Please be sure you are not using our 4.1.0 yet as we mentioned it is not for use until we post our release blog.

If using v4.0.10, please be sure you did all of the steps http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view and load a profile pic if you've never joined before so you can see tutorials. One of the most important things to do is sync css after upgrading and clear cache.

**Comment by Data66PF** [comment]
Please try our 4.1.0 build 2 release and please ensure to follow all of the after upgrade steps provided in my tutorial.

**Comment by AnthonyKing** [comment]
sorry for the late reply, i will upgrade again,
