### ISSUE TITLE
No Error Message When Choosing Non Friend for Private Message

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#747]
This issue is reported at the live community by an upset client. He had typed a very long response to me and then tried to send it only to have it disappear.

My privacy is Friends Only for messages.

We need an error that shows to a user if they select to send a message to someone with privacy at friends only and if that person is not friends. Perhaps, "You cannot message this person at this time due to privacy settings. Please add to friends."  or something like that.

We need the message not to clear from the screen if we don't put that message before they start typing. IMO the message should show before they even get to type anything. However, if it doesn't work to do that in the code, we need to give the user time to save that message (example, they could copy and paste to a document) so they don't lose it.

**Comment by robert9592** [comment]
Fixed for v4.1.1

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-228 *
