### ISSUE TITLE
missing phrase

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#75]
"...liked your photo album "{phrase var='photo.profile_pictures'}"

**Comment by RaymondBenc** [comment]
I wasn't able to reproduce this locally. Was this post made in v3 or was it created in v4?

**Comment by Data66PF** [comment]
![notification phrase](https://cloud.githubusercontent.com/assets/6908282/8650888/db144482-2943-11e5-8dcb-592246ca001b.png)

**Comment by lordofnos** [comment]
thanks data66pf... same in notification email

**Comment by RaymondBenc** [comment]
Fixed pushed to public dist as well https://github.com/moxi9/phpfox-dist/commit/51c9bc215e43e4a3b9f54353d3bb0fb3205c91af
