### ISSUE TITLE
Ajax call stop working on 4.1

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#750]
Hi,
I have several apps for v4 that uses ajax calls on tabs, but all the calls stop working after installing 4.1.0

Did something changed in the way we use ajax?

I'm using this method here:

http://support.phpfox.com/apps/ajax/

Thanks

**Comment by cespiritual** [comment]
Ok, after upgrading to build2 the bug was fixed and all is working just fine.

Thanks

**Comment by Data66PF** [comment]
Closed as this is fixed for build2
