### ISSUE TITLE
Bootstrap Theme Options Issue

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#751]
I have a weird issue when I try to work with the new bootstrap theme that came with version 4.1.0build2.

Any change in the theme made in the theme manager (like adjust the header-background color or add a css line in the editor) make the theme stop to load the css files. I receive just a screen with all content, but no style like a pure html page.

**Comment by Data66PF** [comment]
Confirmed that it seems to give an internal server error when trying to edit bootstrap but have no issues editing nebula theme.

**Comment by Data66PF** [comment]
I see that it is looking for theme 13 on my dev site but bootstrap is not named a number like the rest of the themes. It is an actual name "bootstrap". Not sure if that is the issue.

**Comment by Data66PF** [comment]
I fixed this in my test sites by changing PF.Site/themes/bootstrap to PF.Site/themes/13 and by changing the database entry in phpfox_theme to use the folder 13. 
For those looking, 13 is the number automatically assigned to this theme for my install. You find the number when you edit the theme and see the ID in the url.

**Comment by rn2020** [comment]
Hi Data66PF 
i tried your solution , but it not work , when i change the name to the same number i have it in the theme, than i see the theme is change to the old one not bootstrap ,,,,, ,,, how can we solve that as it is important to change the them like colors and logo and other setting ,  

Best

**Comment by Data66PF** [comment]
when you click to edit bootstrap, it should show a number. On all of my installs, the number is different. This worked on my installs. 

As I mentioned though, you would be best to wait for a fix from the team. It won't be something coming today as it's already the weekend. I don't know when the next release will be.

**Comment by Data66PF** [comment]
Fixed in 4.1.0 build 3 to be released today.

**Comment by Data66PF** [comment]
Fixed  *staff note YPFOXNEUTRON-244 *

**Comment by rn2020** [comment]
thanks
