### ISSUE TITLE
Events after upgrading to 4.1.0 and b2 not shown on event site

### ISSUE THREAD

**Issue by hemsom** [moxi9/phpfox#752]
Hello,

the events created before isn't shown more on the site events. You can click them in site home and edit them but not shown anymore on events. If you create new events, they are listened in events.

Whats to do?
![snip20151127_22](https://cloud.githubusercontent.com/assets/15756413/11442561/9e86a282-9516-11e5-9b0d-2a042ecddba3.png)
![snip20151127_23](https://cloud.githubusercontent.com/assets/15756413/11442565/abb227ba-9516-11e5-925d-91e15c507a69.png)

**Comment by Data66PF** [comment]
When you click to see All events, do they show? Are these events ones that already started?

**Comment by Data66PF** [comment]
I'll mark this a bug since I see that the bootstrap allows us to View All events as we want. The Neutron theme is missing this. We need the menus to allow us to View All.

**Comment by Data66PF** [comment]
This appears resolved in build 3.
