### ISSUE TITLE
Bootstrap Theme Can't Change Logo

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#753]
This works fine in Neutron. In Bootstrap, I cannot get the logo to change. I'm seeing a 500 internal server error as it appears to look for theme 13 but in the folders, this theme is the only one not named as a number but with an actual name. I don't know if that is what causes this issue though. 
v4.1.0build2 Chrome on Windows 10

http://mysite.com/admincp/theme/manage/?id=13 that is for bootstrap but the folder is named bootstrap

http://mysite.com/admincp/theme/manage/?id=2 that is for neutron and the folder is named 2

In PF.Site/themes I have folder 2 and folder bootstrap but I don't have folder 13 like the id shows. 

Note that I see the same issue for any changes I try to make in Bootstrap.

**Comment by Data66PF** [comment]
I fixed this in my test sites by changing PF.Site/themes/bootstrap to PF.Site/themes/13 and by changing the database entry in phpfox_theme to use the folder 13. 
For those looking, 13 is the number automatically assigned to this theme for my install. You find the number when you edit the theme and see the ID in the url.

**Comment by aksaklani** [comment]
I can't change the theme logo, header color or anything else.. If I try then the entire theme is broken after that. So I need to revert back the theme.

**Comment by Data66PF** [comment]
Partially fixed in v4.1.0 build 3 as the logo uploads but it doesn't display for bootstrap so that part is being worked on.

**Comment by robert9592** [comment]
Fixed for v4.1.1

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-243 *
