### ISSUE TITLE
Store Issue: Products Not Listed 

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#754]
Hi,
On my profile in the store the apps and modules are not listed, although I see them listen on other developers profiles.

See it here: http://store.phpfox.com/techie/u/cespiritual

Thanks

**Comment by Data66PF** [comment]
Confirmed. Need @RaymondBenc to check.

**Comment by rn2020** [comment]
it list it with me but i cant install from the store . it gave me load without finish install

**Comment by Data66PF** [comment]
Please don't post comments that are not on topic to the bug report. The issue of not installing is in a different bug report for Chrome browser. Please post on the forum if you have other issues with installing apps as this report is not for that issue.

**Comment by rn2020** [comment]
ok.sorry for tha

**Comment by Jinkers** [comment]
As per requested by data, the apps arent showing up on my account/page either http://store.phpfox.com/techie/u/gamekrib
