### ISSUE TITLE
Client Version gitignore upgrade issues

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#757]
Per this thread http://community.phpfox.com/forum/thread/53296/please-remove-gitignore-for-client-version/ please remove the gitignore from Client Version as it is causing issues for upgrading.

>it is not bug.. only hard for manage project..
such as.
i'm have phpfox code v4.0.8, and i add git all file.. (but default when i setup , have some .gitignore file)
and now i copy all code from v4.1 .but when upgrade appear bug.. i want revert to v4.0.8
but i can't using git. because some file ignored (not manage by git)
-> i think .git only for dev. so when phpfox realease new version.. should remove all .gitignore file
or only ignore file auto generate (such as cache, photo ...) >

**Comment by robert9592** [comment]
Fixed in v4.1.1
