### ISSUE TITLE
Redundant links when creating new page

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#758]
Post v4.1.0b2 update
Default (non-bootstrap) theme

A page was created. After entering the page 

home  info  discussions  photos  events  menu selections appear properly in the page nav bar above right.

However, additionally:

Home
Info
Discussions

appear as additional links left justified at the far left of the page, and

Gear symbol
Photos
Events

appear as additional links right justified at the far right of the page.
This issue did not exist in previous versions, and appears to be limited to page, nowhere else.

**Comment by Data66PF** [comment]
I'm not able to reproduce this on my v4.1.0 b3 site. Make sure you followed all the steps in my final steps tutorial for upgrades. Make sure you sync css if changing themes and clear cache after. I tested on win 10/ chrome.

**Comment by Gatsby-PF** [comment]
I really didn't think you would, but I had to rule that out. Thanks for checking.

**Comment by Gatsby-PF** [comment]
The issue was related to additional code that dropped a new div: 
profiles_second_nav at the end of
/public_html/home/PF.Base/module/pages/template/default/block/photo.php
I could find nothing in the admin contols or block settings that would enable or disable this, I could have missed something, so to get up and running, I removed everything past line 107.
A prior version 10-19 did not have this code in that file.

No other issues were detected within the page as a consequence of removing the code.
This involved the default theme, not bootstrap.
