### ISSUE TITLE
Whole Feed is disturbed.

### ISSUE THREAD

**Issue by warrisdeepsingh** [moxi9/phpfox#759]
I just updated from 4.0.7 to 4.1.0b2
and whole feed is like this 
![capture](https://cloud.githubusercontent.com/assets/10062636/11455324/8694e490-967e-11e5-8518-0cff04036c0c.PNG)

**Comment by Data66PF** [comment]
Please make sure you followed all of the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/  log in to view.

**Comment by warrisdeepsingh** [comment]
You do not have permission to view this article.

**Comment by Data66PF** [comment]
Please read the instructions at my site for getting the free access enabled. It is a big green announcement and very hard to miss.

**Comment by warrisdeepsingh** [comment]
Updated to b3 still same issues

**Comment by warrisdeepsingh** [comment]
![k](https://cloud.githubusercontent.com/assets/10062636/11473156/f5809908-9796-11e5-9879-fe9d3f573dbe.PNG)

**Comment by Data66PF** [comment]
I'm not having this issue with the default themes. Perhaps your issue is related to this bug report, #763

**Comment by warrisdeepsingh** [comment]
ohk thnks for help,

i just used my bck of 4.0.7 and going to upgrade to v4.1.0b3 again following your guide

**Comment by warrisdeepsingh** [comment]
just upgraded same issue and there is no revert option in theme. i am using green sea

**Comment by warrisdeepsingh** [comment]
![capture](https://cloud.githubusercontent.com/assets/10062636/11493455/aca07400-981e-11e5-9f54-44140dae49b8.PNG)

**Comment by Data66PF** [comment]
The not found images is a different bug report that has been fixed for our next release.
