### ISSUE TITLE
Pages top navigation issue 4.1.0b2

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#760]
Just upgraded my community  and after that i followed all post upgrade instruction from scriptechs. Pages top navigation is not properly displaying as shown below.
![image](https://cloud.githubusercontent.com/assets/406030/11457287/0473b762-96a5-11e5-8e03-f785cd8ca5c4.png)
![image](https://cloud.githubusercontent.com/assets/406030/11457288/0b78d394-96a5-11e5-9d88-5c4adec226c8.png)

**Comment by Data66PF** [comment]
When posting would you please state which theme you are using as we now have two themes that come with the script. Thanks. I think that is Neutron theme? Is that correct?

**Comment by aakash83** [comment]
yes this is  neutron.

**Comment by Data66PF** [comment]
duplicate of #758

**Comment by Data66PF** [comment]
Actually, it doesn't look like a duplicate. The other one is for new pages and double menus.

**Comment by Data66PF** [comment]
I can confirm this with Neutron theme for pages without a cover image.

**Comment by robert9592** [comment]
fixed for v4.1.1

**Comment by Data66PF** [comment]
Fixed in v4.1.1 *staff note YPFOXNEUTRON-255 *
