### ISSUE TITLE
no image found constantly 

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#761]
no image found constantly on every page how to fix v4.1.0 b3 safari
using Neutron theme currently i looked in the image folder path and it's blank '../../../../PF.Base/theme/frontend/default/style/default/image/' 

![screenshot 2015-11-29 15 08 51](https://cloud.githubusercontent.com/assets/3644262/11459881/a0da986a-96ae-11e5-8bd0-12a04238352c.png)

**Comment by Data66PF** [comment]
Please search before posting. Duplicate #756
