### ISSUE TITLE
Theme issue 4.1 V3 build Sync CSS Issue

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#763]
It seems the bootstrap theme is clashing with existing themes on upgrade????
![2015-11-30 08_42_50-new notification](https://cloud.githubusercontent.com/assets/13656046/11470633/13e9f4d6-9768-11e5-93bc-d6da59557766.png)

**Comment by Data66PF** [comment]
Did you sync css for your theme?

**Comment by one44** [comment]
Sync and revert is what causes issue.

**Comment by Data66PF** [comment]
Bug for sync and revert issues.

**Comment by Data66PF** [comment]
Please test with 4.1.2 and let us know if this is resolved. Please let us know, if it is not resolved, how you are making your css changes as they won't overwrite if done in Admincp editor.

**Comment by one44** [comment]
Please close issue
