### ISSUE TITLE
Bootstrap - Developer Test App Not working

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#766]
From this thread, http://community.phpfox.com/forum/thread/53355/new-bootstrap-theme-developers-test-app/ , the developer test app:

https://github.com/moxi9/phpfox-base
http://store.phpfox.com/product/790/developers-test-app

Is not working in Bootstrap. The menus don't show at all. 
Works fine in Neutron theme though.

**Comment by robert9592** [comment]
fixed for v4.1.1
