### ISSUE TITLE
Bootstrap theme (BUG?)- Uncaught ReferenceError

### ISSUE THREAD

**Issue by edwingrivera** [moxi9/phpfox#768]
Team- I reviewed the Bootstrap theme and I am receiving an error (Uncaught ReferenceError: iOpeningDelayTime is not defined). Not sure if is a BUG or if there is something that I need to change in the configuration. We can see all feeds and these messages are appearing on top of the feeds. We are not receiving messages with the "neutron" theme. Please advise and thanks for your continued support.
![phpfox unexpected error](https://cloud.githubusercontent.com/assets/13394648/11513456/4128b520-9841-11e5-9fd9-4e60aec66fdd.PNG)

**Comment by Data66PF** [comment]
I only saw this error once but now I can't reproduce it in v4.1.0 build 3. Tested with chrome and ff browsers.

**Comment by Data66PF** [comment]
Can you reproduce this in 4.1.2?
