### ISSUE TITLE
Pages | Can Not Disable Pages

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#77]
Creating 'Pages' is something we want to reserve until later for our users, and it's the only feature it seems that we can't disable by default from the back end. We had to use CSS to hide it from the menu. Is it possible to get a proper, enable/disable for this feature?

**Comment by Data66PF** [comment]
I don't see a setting to disable it either. I only see menus but not one for pages. We need settings for modules so we can disable those we don't want to use.

**Comment by GloriousKoch** [comment]
I noticed this was put in the recent update, but my Page options still don't show an option to enable/disable them. Did I miss something possibly?

![image](https://cloud.githubusercontent.com/assets/6254165/8662255/eaf08fee-298b-11e5-9055-c9525bb4d354.png)
