### ISSUE TITLE
Music album image uploaded does not display

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#771]
The uploaded music album photos do not display in the album, but still shows as being uploaded in the edit album dialog.

**Comment by Gatsby-PF** [comment]
It does display the pic when All Albums, or My Albums are opened. But once the album is opened there is no image in there.  Not sure if it is supposed to be there or not.

**Comment by Data66PF** [comment]
I'm testing with bootstrap theme and when I click the album, I see the cover to the left of the play button. V4.1.0 build 3

**Comment by Data66PF** [comment]
Just tested with Neutron and can still see the image next to the play button. Do I need to do something else?

**Comment by Gatsby-PF** [comment]
Using Neutron theme. Inspector is showing that there is a 200 X 200 px area reserved to the upper left of the play buttons but no image. Web console is showing that it loaded a 200px image, but image the entire area left of the play buttons is empty.

**Comment by Gatsby-PF** [comment]
Further information - the server is throwing a 404 error for a nonexistent css file.
[error] [client IP Address] File does not exist: /scrubbed-server-path/PF.Site/themes/2/flavor/music_static_css_default_default_browse.css, referer: https://scrubbed-domain.tld/index.php/music/

**Comment by Data66PF** [comment]
I had that issue before when my upgrade didn't fully work on my local installs. My live dev is working fine for this though. A tech will need to see if they can reproduce this as I cannot on my live site.

**Comment by Gatsby-PF** [comment]
When you get a minute, can do an inspect within the album and highlight the html that has to do with that image and send it.  I want to compare the url you get and he one I am seeing, which has some strange character runs such as 
data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

**Comment by Data66PF** [comment]
``` <img data-src="http://mysite.com/file/pic/music/2015/12/f69018c5a7ff44f023a8f0116d7d5122_200_square.jpg" src="http://mysite.com/file/pic/music/2015/12/f69018c5a7ff44f023a8f0116d7d5122_200_square.jpg" alt="" class="_image_200 image_deferred  built has_image"> ```

**Comment by Gatsby-PF** [comment]
The source html for the correctly displaying image while in album selection catalog

<img class="_image__200_square image_deferred built has_image"
alt="The correct image description"
src="https:/scrubbed-domain-name.tld/index.php/file/pic/music/2015/12
/a1ec208d5dfb00f6e760ccdd2703b951_200_square.jpg
></img>


The source html for the non-displaying same image while in the album source trace

<img class="_image_200 image_deferred built has_image" alt=""
src="data:iage/gif;base64,R01G0Dh...H5BAEAAAAALAAAAAABAAEAAAIBRAA7"
DATA-SRC="https:/scrubbed-domain-name.tld/index.php/file/pic/music/2015/12
/a1ec208d5dfb00f6e760ccdd2703b951_200_square.jpg"
></img>

**Comment by Gatsby-PF** [comment]
If your system created that css file.
music_static_css_default_default_browse.css
I wonder if there is a way I can get my hands on that. Maybe it just failed to generate for whatever reason and this will go away once the system sees the file there (fingers crossed).

**Comment by Data66PF** [comment]
Well if you don't have it for that, you probably don't have it for all the others. Looks like about 20 files are in mine.

**Comment by Gatsby-PF** [comment]
I do have it for all the others, that is the strange thing.  When do these get created, 

when you sync? 
upon install for all services? or 
when the service is called into use for the first time?

**Comment by Gatsby-PF** [comment]
The css war re-synced and now I see the music css file. After cache clearing, and re-upload of the image, 
the log error went away as the system can now 200 on the music .css file;
the image still fails to display in the album, however the bad url show above is no longer there;
what shows up in its place is
<div class="music_album_view">
		    <span class="no_image_item i_size_200"><span></span></span><div class="mav_info">

neither web or network consoles show any attempt to load the image.
			</div>

Where the bad image used to be.

**Comment by Data66PF** [comment]
I think this could be due to the css bug posted in another bug report for sync css maybe.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/763 I realize the issue mentioned is different but if your issue is due to sync css, then it would be related to that issue.

**Comment by Gatsby-PF** [comment]
I recopied the 4.1.0b3 distro files over the installation (not an upgrade, but a patch remember?). 

Deleted all css from the themes directory leaving only 2.css you sent and verified all permissions writable;

Re-synchronized, cleared all caches and created new child css by opening and walking through all modules/apps one by one, and verified the css was created;

Uploaded new album photo from the album edit icon in the album.

Photo displays for that album in the page where you select all albums (catalog i guess), but not in the album itself to the left of the listing of all songs to the right.

In addition, the inspector source displays the same results as the last code entry I made above. I honestly think at this point starting to believe that there is supposed to be no image there.

**Comment by Gatsby-PF** [comment]
I did a fresh writeover of the 4.1.0b3 patch. Deleted all css files, and place only the default 2.css you sent. Verified file writability then created child css files by opening and walking through each module including music. Uploaded new photo from music album. Photo displayed for that album in the all albums select page, but not in the album.  Since I isolated my theme, reverting to original starting point, I can safely make the argument that there is a bug somewhere, or the photo is not supposed to display in the album to the upper left of the vertical row of songs on the right.

**Comment by Gatsby-PF** [comment]
Yes I cleared caches after syncing.

**Comment by Data66PF** [comment]
Let's make sure we are on the same page, literally lol. I viewed all albums and clicked one to see the songs in it. I see the album on the left and the songs (I only had one) on the right. Is that correct?
![stewart scripttechs test site](https://cloud.githubusercontent.com/assets/6908282/11574049/6bb4bbbc-99d7-11e5-9754-9c0e3563d60f.png)

**Comment by Gatsby-PF** [comment]
Yeah that what I was expecting. Who is that Rod Stewart?

**Comment by Data66PF** [comment]
yes lol one of my fave singers

**Comment by Gatsby-PF** [comment]
The Motown song with the Temptations was incomparable.  Anyways, is 4.1.0b3 compatible with direct install? I want to install as new (db, install, default theme all new) and if it works, pull the current db back in to see if it still works, and if it works, pull the current theme back in.

**Comment by Data66PF** [comment]
The files aren't here in this github if you mean install from github. I don't know if that works now.

**Comment by Gatsby-PF** [comment]
4.1.0b3 new install went without issue. When creating albums, the image showed correctly in catalog and the album.  Installed and synced custom theme and created second album. Image showed correctly in album catalog, but not in either of the two albums. I do not know what this sync is supposed to do, but some album photo class or setting in a class is not being carried to the custom theme during the process.  It is nearly impossible to address this manually thanks to the single line css. So at this point, either the sync deficiency gets corrected, or I do without the photo on the album. There is no other defect anywhere on the site using this theme this was the last item.

**Comment by Gatsby-PF** [comment]
Okay, a brand new install, brand new database.
I can create album, upload pic, upload song, and see photos in album catalog and album.
I create a flavor changing nothing and make it the default.
The image drops out of the album.
When I change back to the default theme (virgin 2.css), clearing caches or not, syncing or not
The image permanently stop showing in the album.

**Comment by Gatsby-PF** [comment]
This issue persists on a brand new 4.1.1 installation. Neutron theme.
It has actually degraded in the sense that only the top 20% of the photo in the album catalog displays, and the remaining area is white.  The image does not display at all in the album itself.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/763 the sync css issue for non-default theme is found there. If your issue is with sync css, then this would be a duplicate.

**Comment by Gatsby-PF** [comment]
Brand new install, theme included (not bootstrap). If it is sync css issue, you should be able to duplicate it by going through the last 5 lines of the 2nd post directly above your last post.

**Comment by Data66PF** [comment]
Can you still reproduce this in 4.1.2?
