### ISSUE TITLE
Admincp Addon page issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#772]
![download 1](https://cloud.githubusercontent.com/assets/8562514/11533975/b53195a6-990c-11e5-8e9a-872a37d94138.png)

**Comment by Data66PF** [comment]
What is the issue? You didn't post anything.

**Comment by Ylmzef** [comment]
As can be seen in the screenshot; The navbar of the addons page apear on page contents.

**Comment by Data66PF** [comment]
Yes but it is working for me. I can search in it, etc. However, I'm sure this is one of the areas being updated so I'll leave this bug open for a tech to check.

**Comment by Ylmzef** [comment]
It's not about functional system.
It's about design.

**Comment by Ylmzef** [comment]
When do you want fix this?

**Comment by Data66PF** [comment]
This is resolved in 4.1.2.
