### ISSUE TITLE
Redirect After SignUp setting in User Settings does not redirect.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#773]
New signups walk right past the configured page and the system does what they have always done. Using web url.

**Comment by Data66PF** [comment]
What page are you redirecting to so I can test?

**Comment by Gatsby-PF** [comment]
It was a YN  app page. I never thought to retry it on a non app page, let me do that and rule that before you test. I'll get back.

**Comment by Gatsby-PF** [comment]
This time it was just set to redirect a blog article. As Raymond would put it...
"No Dice".

**Comment by Data66PF** [comment]
Ok I see. You are not redirecting to a section but a specific thing within a section. Will try that tomorrow.

**Comment by Data66PF** [comment]
I cannot reproduce this. I chose a blog article and set it for the registration redirect after sign up. Once a new user signs up, they go to that page without issue. I'm using short urls on this site. Tested in firefox with neutron and bootstrap themes. 4.1.1 build 3

**Comment by Data66PF** [comment]
For kicks and giggles, I also tested Redirect after login, found in user settings since the title mentioned the one in user settings. I put a different blog in that one and it went to that one properly too.

**Comment by Gatsby-PF** [comment]
You just got some kind of magic box there. Thats what I need to get.

**Comment by Data66PF** [comment]
LOL
