### ISSUE TITLE
Admincp member Search wrong phrase

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#774]
Steps to reproduce
Goto AdminCp >> Search >> Click view More search options  and we get  more options for search . but  the button text is still  "View More Search options "  it should be  disabled or "View Less Search options" . because when we click on it for second time   it closes the advance search options opened when we first clicked on it to get more search options.
using latest release with chrome.

**Comment by robert9592** [comment]
Fixed in v4.2.0
