### ISSUE TITLE
Bootstrap Theme . Message Delete Button Styling

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#775]
![image](https://cloud.githubusercontent.com/assets/406030/11571085/f016efa6-99fa-11e5-9f70-0bbead8d8f60.png)

Using latest phpfox version with chrome

**Comment by Optiroot** [comment]
I don't think this is a bug but is a wanted thing: it's confusing just because there isn't any border between the two "X blocks", but I guess it is wanted, even because it looks nice.

**Comment by aakash83** [comment]
button is hiding receivers names also.

**Comment by Optiroot** [comment]
I make the purpose to close this issue as "delete messages" buttons have been moved to the left and now aren't painful anymore with v4.1.1.
