### ISSUE TITLE
Bootstrap Theme Home Page Block Allignment

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#776]
I have New members app  installed and on home page  New member block and  feed block are not correctly aligned.
![image](https://cloud.githubusercontent.com/assets/406030/11571242/a8f1e4e0-99fb-11e5-9f09-2c078294fbf4.png)

**Comment by Optiroot** [comment]
I have this too, but I don't think is a bug/glitch.

If you want to fix this, it's enough to use this CSS:
`div.col-md-3.col-sm-3#left { margin-top: 30px; }`

And/or wait for a core DEV or PHPfox staff answer.

**Comment by Data66PF** [comment]
Cannot reproduce in 4.1.1 after reverting theme as sync css didn't bring in the updates.

![newmem](https://cloud.githubusercontent.com/assets/6908282/11640527/f3360f1a-9d00-11e5-9c45-39148d6d75a4.png)

**Comment by aakash83** [comment]
fixed in 4.1.1.
