### ISSUE TITLE
Bootstrap Theme . Editing a Page , Chrome vs firefox

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#777]
When We edit a page  we get different options under same tab in different browsers. Below you can see chrome and firefox example. In firefox we can't see option for vanity URL and Check URL.
![image](https://cloud.githubusercontent.com/assets/406030/11571541/2f7840f8-99fd-11e5-9baf-d03e3cb2e263.png)
![image](https://cloud.githubusercontent.com/assets/406030/11571563/599e97ba-99fd-11e5-9471-d1ad11f6c5b0.png)

**Comment by robert9592** [comment]
Fix for v.4.2.0
