### ISSUE TITLE
Upgrade Taking Place Check back in a few minutes.

### ISSUE THREAD

**Issue by editmike** [moxi9/phpfox#78]
I have installed PHPFOX V4 and it has came up with this message.

"Upgrade Taking Place
Check back in a few minutes."

cant any one help me get the site online??

Thanks

**Comment by Data66PF** [comment]
Upgrading v4 is different than v3. Please wait for the upgrade instructions to be posted.

**Comment by editmike** [comment]
I havnt upgraded I have only installed V4. and thats what came up.

**Comment by Data66PF** [comment]
Ok we are posting here and in the forum. Since the forum is for troubleshooting, before posting bugs, let's continue there and if it looks like a bug, it can come here. Note that I am not having an issue installing.

**Comment by editmike** [comment]
is there a way we could email?

**Comment by Data66PF** [comment]
This developer build says for local installs. On your local computer.

**Comment by editmike** [comment]
is it not ready to be uploaded on a online sever?

**Comment by Data66PF** [comment]
This is a developer build. This is not the client version. Please see the license terms in the readme. Here is the tutorial for installing developer builds if you have trouble with the install from the readme, http://scripttechs.com/article/352/how-to-install-phpfox-v4-on-xampp-local/

**Comment by editmike** [comment]
when its on a local host? can i then upload it on my online sever?

**Comment by Data66PF** [comment]
No. The readme license specifically states
"We permit the usage of our developers build on a localhost web server without public access to the server."
If you want it on a server, please purchase a license and use the client version.

**Comment by editmike** [comment]
I have purchased a oicense but that zip file u get from the shop.phpfox site dosent work

**Comment by Data66PF** [comment]
Ok. This one you won't want to use for your live site. It doesn't allow installing apps and has some things disabled as it is only for developers. Try getting the client version from here, https://github.com/moxi9/phpfox-dist

**Comment by Data66PF** [comment]
http://support.phpfox.com/getting-started/requirements/ make sure your server meets the requirements.

**Comment by editmike** [comment]
ok thanks, i will message again if i run in to any problems

**Comment by Data66PF** [comment]
I can be reached at my scripttechs.com site more than here. However, if you do run into issues, enable debug via the instructions posted in the readme for this version.

**Comment by editmike** [comment]
i have a  license what one do i pick?
Premium
Developers

**Comment by Data66PF** [comment]
Premium

**Comment by Data66PF** [comment]
http://support.phpfox.com/getting-started/installing-phpfox/ follow the guide

**Comment by Data66PF** [comment]
http://blog.phpfox.com/2015/07/08/accessing-your-licenses-orders/ in case you are not sure how to get the license id and key

**Comment by editmike** [comment]
Thanks worked :)

**Comment by Data66PF** [comment]
Great!

**Comment by editmike** [comment]
now to work out how to change the name from phpfox and the back images on the login page :)
