### ISSUE TITLE
Bootsrap theme . user hover popup showing wrong status

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#781]
In bootstrap (latest version with chrome)theme when we hover over a user's name a popup appears . But the online/offline status shown by phpfox is not correct. moreover it only shows online status and don't show anything when a user is offline. also when  we hover over the status button  we get "undefined" text.
![image](https://cloud.githubusercontent.com/assets/406030/11610868/ccfebfaa-9bb0-11e5-9cb2-5c2cad112f95.png)

**Comment by Data66PF** [comment]
Please test with 4.1.1 that we released today.

**Comment by Data66PF** [comment]
Cannot reproduce this in 4.1.1 for the default feature of showing is online (shows a small green dot to indicate the user is online). We never had anything to indicate offline as it wasn't necessary since it doesn't show a green online.

**Comment by aakash83** [comment]
not fixed in 4.1.1 . Still  having same issue.

**Comment by Data66PF** [comment]
Can you still reproduce this in 4.1.2?

**Comment by aakash83** [comment]
yes . almost every member is shown as online . but in reality nobody is online.

**Comment by Data66PF** [comment]
I cannot reproduce this on my development live site or at our demo http://v4.phpfox.com .

**Comment by Data66PF** [comment]
I still cannot reproduce this. Please check your setting for Active Session, admincp/setting/edit/?group-id=server_settings

**Comment by aakash83** [comment]
@Data66PF  same problem even after changing active session time. any way to  clear this session table from DB??
