### ISSUE TITLE
Opening notification (messages, friend request and notifications) doesn't reset counter in Bootstrap theme

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#786]
If you receive a notification in the notification area like a message, a friend request or a simple notification even if you open the notification the counter (like 1, 2) doesn't reset to zero.

To reset it, you should reload the page. Reloading, shows 0 notifications.

This happens in Bootstrap theme, I don't know in Neutron because I have an active community and I can't change the theme.

![image](https://cloud.githubusercontent.com/assets/12573563/11669609/f280fc80-9dfd-11e5-9e79-3c45003be0e3.png)

I mean these. It's just a my problem?
Because I don't find any other post about this and is carrying on this problem from the first Bootstrap release.
Now even with 4.1.1 the problem persists.

**Comment by Data66PF** [comment]
Confirmed for bootstrap. Neutron is not doing this in my tests. v4.1.1 build 3 tested.

**Comment by optiroot** [comment]
Any update on this from a core developer? Could be nice to see it fixed...
I saw that in 4.1.2 so much bug have been solved, so maybe this could be included in the next one? 
Thank you!

**Comment by Data66PF** [comment]
This is also confirmed on the live PF demo (for our techs to see).

**Comment by neil96** [comment]
Fixed on V4.2.0
