### ISSUE TITLE
Admin Cannot See All Content

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#788]
This is a big issue and has been for clients before. Admin must be able to see everything posted on the site, regardless of privacy or "friends only community". 

Admin setting in user group setting for Core:

Can view private items posted on the site. is at True
Privacy settings for the Admin group for:Can view all items regardless of privacy settings? is at true
Friends only Community is at True
Friends Only feed is at True

I am testing at the demo and logged in as the admin. Client posted a blog for me to check a bug but I can't see it as we are not friends. I am admin. I should see everything on that site. Yes, we have a free app but this is something that should be default in the script as it used to work. It needs to work again.

http://demo.phpfox.com/blog/ can't see any blogs there at all.

**Comment by Vivian-phpFox** [comment]
Confirmed, happened in previous version (4.07; 4.0.10)

**Comment by neil96** [comment]
Fixed on V4.1.2

**Comment by Vivian-phpFox** [comment]
Fixed in V4.1.2

**Comment by Vivian-phpFox** [comment]
Fixed in V4.1.2
