### ISSUE TITLE
'View More' Link in Messages

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#789]
The 'view more' link the messages chat window is not loading previous messages outside of the default amount of the most recently pulled ones. Instead of pulling more messages, the link is performing a reload of the page behind the chat window. Test on my site running 4.1.1 and the PF Community. Unable to test on the new demo.

**Comment by Data66PF** [comment]
Confirmed at the community which is 4.0.10. Confirmed on my 4.1.1 live test site.

**Comment by robert9592** [comment]
Fixed in v4.1.2
