### ISSUE TITLE
Bootstrap Visitor Page is Blank in Block 2

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#790]
We have some blocks for Bootstrap for the core.index-visitor page but they are not working and we have a blank front page where the sign up is for block 2. Testing at the phpFox demo

![bootstrapvisitor](https://cloud.githubusercontent.com/assets/6908282/11683678/54f56f4a-9e3a-11e5-818a-3fc8148b902d.png)

**Comment by neil96** [comment]
Fixed on V4.2.0

**Comment by phpfoxdev** [comment]
Meanwhile, just "sync css" to get template updated, issue shall be fixed

**Comment by Data66PF** [comment]
Sync css breaks sites so for anyone looking, please backup the site if you have a custom theme before you press sync css.
