### ISSUE TITLE
Status share after sharing a link will not post

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#791]
Editing this as I've found that the issue is after sharing a link in the status share. If I then go and try to post any other status share, I get the "must be approved" message first. Then after that, I just can't share any until I totally refresh the page. Note that this is admin account so there is no approval needed to post. The issue is something to do with sharing links in the feed. It is causing something to break. See below comments by a developer that also tested.

*below is the original bug report
Testing at the live demo. Posted a status share:

This is Donna(data66) logged in to our admin account. Please note this is for all of our staff and not just my own account.

That share won't get posted as it gives a note that it must be approved first. Note that it is an admin account and the settings are for no moderation. I then tried again and notice that we cannot post a share with () as it will just not post at all. There is no place in admin where these show to approve either.

**Comment by Data66PF** [comment]
Please note to test without a space as I put one for the title but use something like I posted for my name.

**Comment by Data66PF** [comment]
You might have to test on the demo and with chrome browser using win 10. I'm not sure. I'll test more on my dev site too. Steps I did before sharing that status:

1. Added a video from youtube to the feed
2. added a link to the feed
3. tested some html code blocks in the forum

**Comment by Data66PF** [comment]
Ok tested again. The issue appears after sharing a link in the feed. Once I do that, if I try to do another status share, I get the error that it must be approved and I now can't share this. So it works before posting a link but not after posting one.

**Comment by Jinkers** [comment]
After doing a full page refresh (f5), this allows the usage of the () again. Perhaps something isn't exiting /escaping correctly from the url grabber?

**Comment by Vivian-phpFox** [comment]
Confirmed, happened in previous version (4.07; 4.0.10)

**Comment by robert9592** [comment]
Fixed in v.4.1.2
