### ISSUE TITLE
No Latin characters’ bug in blog

### ISSUE THREAD

**Issue by Rodios** [moxi9/phpfox#792]
Phpfox v4.1.1 
If you in home page or photos or etc. and you click on blog if the characters’ are no Latin it appears like the image below but when you refresh the page, it become ok 
![latin](https://cloud.githubusercontent.com/assets/16224843/11686507/a6dbba9a-9e89-11e5-8b5c-b02d864dd798.PNG)

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/461 duplicate
