### ISSUE TITLE
Post a blog issue

### ISSUE THREAD

**Issue by Rodios** [moxi9/phpfox#793]
Phpfox v4.1.1
When I post a new blog, in feed and in profile appears like the image below, 
if this is normal can you maket it little bigger.
![demo](https://cloud.githubusercontent.com/assets/16224843/11686679/ef4e1be6-9e8a-11e5-913b-30a46a021312.PNG)

**Comment by Data66PF** [comment]
I can see the issue and marking as an enhancement as it is very small for a preview in the feed. Not sure if we can fix it but leaving it open for a tech to test.
