### ISSUE TITLE
Inviter: bottom half of email addresses being cut off

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#794]
Inviter email entry box cuts off bottom half of email address text due to insufficient "height: 20px" set in inline css on line 95 of file:

PF.Base/module/invite/template/default/controller/index.html.php

Changed height to 40 and full text displayed okay.

**Comment by Data66PF** [comment]
Confirmed at phpFox demo, http://demo.phpfox.com/invite/

**Comment by neil96** [comment]
Fixed in v4.2.0
