### ISSUE TITLE
Synchronous XMLHttpRequest are deprecated and will be removed from browsers in future

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#796]
I know that is really hard to fix this, because most of PHPfox could stand on.
But is really important to take advice about as in future could be removed from browser.
Synchronous XMLHttpRequest is old and causes detrimental effects on the users experience.

Moreover, Chrome is already showing the alert on Javascript console when you open Dev tools (F12).

**Comment by Data66PF** [comment]
@neil96 can we have someone check this?

**Comment by optiroot** [comment]
Anything new about this?

**Comment by RaymondBenc** [comment]
@optiroot Thanks for your feedback. We use jQuery by default to execute all of our AJAX calls and it by default has async set to true. Does your warnings identify what file/line it is coming from? I have the dev console open when working with the product and haven't seen a warning in regards to this when using our base product.

**Comment by optiroot** [comment]
Hello Raymond, it seems that from 4.2 the problem isn't here anymore, it seems to be okay.

Anyway, the older versions didn't identified from which lines that came from, it was just an advice from Google Chrome in the Dev console.

Now everything is okay, so I can close this.

Thank you!

**Comment by optiroot** [comment]
Hello,

the problem appeared again...

Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/12573563/13202413/3bbea308-d89a-11e5-86f6-60b29b8d68c2.png)

**Comment by neil96** [comment]
I can't reproduce this issue on any sites I have. Which version of your browser?

**Comment by optiroot** [comment]
The problem is that this notice appears rarely, so it's hard to tell you the steps...
In any case, at me it happens on Firefox last version, Edge, and in Chrome version 48.0.2564.116 m

I can't tell you the steps to do this...

**Comment by neil96** [comment]
Can I test on your site?

**Comment by optiroot** [comment]
Of course. I can even give you sample logins, but I can't post it here.

Where can I send you it?
I'm in the PF Community too, so if you prefer I can send you via PM.

Let me know!

**Comment by neil96** [comment]
Email me: neil@phpfox.com Thanks!

**Comment by optiroot** [comment]
Done!

Thank you.

**Comment by neil96** [comment]
![github-796](https://cloud.githubusercontent.com/assets/15936115/13355194/b0ecd20e-dcd1-11e5-962b-7bffc64d84bb.png)
Thanks for email. 
I tested on your site, I saw this error from plugin **cometchat** not our core script.

**Comment by optiroot** [comment]
Okay, you're right. I've checked, sorry for the problem. I thought it was a phpFox issue.
I close this!

Thank you.

**Comment by neil96** [comment]
No problem! :)
