### ISSUE TITLE
Photo accept after upload dialog needs to be wider.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#798]
4.1.1 Neutron theme.
After you upload a photo, but before you edit and accept it into the album, the dialog that allows this editing of photo name, and adding a category is extremely narrow and anorectic ( about an inch and a half wide) and left justified. It should be a third to half the width of the container and center justified.

**Comment by Data66PF** [comment]
I don't see an issue on my live test site 4.1.1 build 3 Neutron in firefox browser. I loaded 6 photos but only took a screen of the top ones.
![v411photos](https://cloud.githubusercontent.com/assets/6908282/11716366/5f25506a-9f17-11e5-92d0-7fc32696012b.png)

**Comment by Gatsby-PF** [comment]
I can adjust it easily.
