### ISSUE TITLE
Profile Pic Upload Problem Max Size(larger then our limit)

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#799]
By Default in admincp profile pic upload size is defined 550 kb.
But when someone upload profile pic greater then this limit size upload box keep scroll in rounded circle.it does't show any warning msg. its must show warning msg to end user regarding larger limit.
![profile pic upload problem max size](https://cloud.githubusercontent.com/assets/13433124/11708242/176f5f56-9f33-11e5-86b7-9857561255df.png)
 

like that its show in Cover pic and status share post

Upload failed. Your file (1 Mb) is larger then our limit: 500 kb

**Comment by neil96** [comment]
#723

**Comment by SalmanKhan86** [comment]
i think this is different case from previous one. 
pls double check this.

**Comment by neil96** [comment]
We also fixed this case in #723
