### ISSUE TITLE
How can I enable/disable a module in the admin interface ?

### ISSUE THREAD

**Issue by JulienHenchoz** [moxi9/phpfox#8]
Hi,
On PHPFox 4.0 (rc2), I can't seem to find where to enable/disable modules in the administration interface. In the "Techie > Modules" I only see the 2 modules I created myself, and note the whole list.

I searched for this in the knowledge base and found the answer for PHPFox 3.x (http://unity.moxi9.com/kb/article/227/disable-or-enable-a-module-feature-cms), but this screen doesn't exist anymore in the last version.

Thank you,
Julien

**Comment by RaymondBenc** [comment]
With the fix I provided above this still won't show all the core modules by default. We wanted to separate our core completely from the list. If you wish to view the core modules and you have installed this patch you can pass **?view=all** in the URL to view all the modules.
