### ISSUE TITLE
Activity Feed | 'Invisible' Activity Feed

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#80]
The activity feed on the main dashboard and profiles is acting wonky for multiple users. It sometimes doesn't show up and needs a refresh. Sometimes your mouse can hover over one of the 'boxes' in the feed and click it and then it all shows up again as well.

**Comment by Data66PF** [comment]
I don't see this issue on the live v4 demo at community.phpfox.com nor on my test sites. Do you have any v3 addons installed? Did you make any changes to your site?

**Comment by GloriousKoch** [comment]
We installed the recatchpa addon in the back and made the option change to show "all activity" on the dashboard vs. just those you're friends with. Other than that, no changes have been made. Any other ideas of what could cause it if it's not those?

**Comment by Data66PF** [comment]
Does your server fully meet the requirements? Are you using the current 4.0.1 version? do you see the same thing on the live demo?

**Comment by GloriousKoch** [comment]
Server meets the requirements. I do believe I may have found the issue. I disabled Activity Feed AJAX and it seems to load normally each time now. Though, not sure if THAT would be a new bug on it's own or if that's just something random I encountered.

**Comment by Data66PF** [comment]
Oh God don't enable those ajax settings. They had mega issues in V3.

**Comment by GloriousKoch** [comment]
Would you say ALL ajax should be disabled? It mentions it being less of a performance hit on your server/bandwidth, it's it not as significant as it sounds?

**Comment by Data66PF** [comment]
I don't know what is fixed or not but I don't use the sitewide ajax (issues), any of those ajax cache settings, I have a list on my site someplace about what I enable and don't but I don't think the settings are now contained within the "cache" settings. I think they got scattered.

**Comment by RaymondBenc** [comment]
The setting **Activity Feed AJAX** is not needed any longer since the site loads by default via another AJAX method and that specific setting should be disabled as we will remove it from our setting line up.

Once disabled, does everything then work as it should?

**Comment by GloriousKoch** [comment]
Yes @RaymondBenc, it appears it's working okay now with the AJax Activity Feed turned off. Would you recommend using or not using the Site Wide Ajax in the main settings? How much of a difference does it make on bandwidth/resources on vs off? Thanks :)

**Comment by Data66PF** [comment]
Closed as the original issue is resolved.
