### ISSUE TITLE
Bootstrap theme | Forum listing shows weird; bad CSS provided

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#801]
As v4.1.1 the forum listing shows bad, and in mobile layout practically every word is a breaked one because of the too much big font.

Screenshot attached:
![image](https://cloud.githubusercontent.com/assets/12573563/11710009/6049b4e0-9f1c-11e5-9418-33fb09bfbeb9.png)

**Comment by Data66PF** [comment]
Confirmed with bootstrap, iPhone 5c safari browser. Live test site 4.1.1.

**Comment by robert9592** [comment]
Fixed in v4.1.2
