### ISSUE TITLE
Bootstrap theme | Menu in pages not possible to translate

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#802]
I don't know if for Neutron it translates but I think not.
In the phrases there isn't any string to translate the menu in pages and groups.
I mean this one:
![image](https://cloud.githubusercontent.com/assets/12573563/11710042/a3301074-9f1c-11e5-90cf-b9982d517042.png)

I translated every string of the module "Pages" so they are hardcoded?

**Comment by Vivian-phpFox** [comment]
It's hard code, will be improved later

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/226 just referencing

**Comment by optiroot** [comment]
Okay!

I'm going to translate them using jQuery in hard-way from some hours.
Can I share here how to do so?

**Comment by neil96** [comment]
Fixed on V4.1.2

**Comment by optiroot** [comment]
You're fast as hell!
I don't do nothing more, lol!
