### ISSUE TITLE
Edit Cancel Comment Not Working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#804]
when i edit my comment on someone post then click on cancel button in text editor 
its display me object object not my comment
tested it on 4.1.3
![comment edit cancel option](https://cloud.githubusercontent.com/assets/13433124/11710391/c509fffc-9f44-11e5-8c41-aa42b7fa6033.png)

**Comment by Vivian-phpFox** [comment]
Can not reproduce on V4.1.1

**Comment by Optiroot** [comment]
In fact this has been fixed without knowing of it in v4.1.1, because in 4.1 it was still present!

Great job!

**Comment by Data66PF** [comment]
Cannot reproduce at the live http://demo.phpfox.com on v4.1.1 version.

**Comment by SalmanKhan86** [comment]
it is still there in v 4.1.1 pls check and Resolve it

**Comment by SalmanKhan86** [comment]
why its closed here.pls open it

**Comment by SalmanKhan86** [comment]
Sorry Working fine.....
