### ISSUE TITLE
Neutron Theme - Profile Custom Field Font is Too Light to Read

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#808]
4.1.1 Neutron theme. Have some custom fields made and answer all of them so you can see the issue. The font color is way too light to read. Even for block headings on the profile page, the default font color is too light. The image below is magnified but if you test this, you will see that it is hard to read. We need to fix this please.

![profilefont](https://cloud.githubusercontent.com/assets/6908282/11727609/bd0d5110-9f52-11e5-84fc-d4010c300cbb.png)

**Comment by Data66PF** [comment]
This is an upgraded site and another client can reproduce this. You will need to test a few upgrades to get the issue to show as I have two other sites that don't show it as that light font but instead have it as a black font. The image above is from my live dev site.

**Comment by Data66PF** [comment]
This is resolved by having to click Revert theme but this theme was never changed so we have an issue with upgraded sites and requiring to revert theme which will end up angering clients that have made customizations when they have to lose those for every upgrade. Leaving this open to check for that.

**Comment by neil96** [comment]
We have no way to fix this issue without revert theme. Because to fix this issue, we have to change color (variable). Once we change variable, we have to revert theme.
