### ISSUE TITLE
New user redirect replaced slashes for dots in url

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#809]
The url finally attempted the redirect to blog article but it rewrote dots in the url to forward slashes. Here is what happened...

url set in new user redirect path (under user and registration settings) is:
https://my-scrubbed-site.com/index.php/module/article/articleX

when the site gets redirected after new user logs in, here is how the url gets rewritten:
https://my-scrubbed-site/com/index/php/module/article/articleX

The browser goes 404 because the domain name and index file got corrupted and no longer has a valid servername.

I am not using short urls.

**Comment by Data66PF** [comment]
I tried setting up https to test on my xampp on winblows but it failed. I'm not sure how to make it work.

**Comment by Gatsby-PF** [comment]
XAMPP is usually https out of the box without doing anything, you can use their default certificate rather than create one as it is just for testing on https://localhost anyway.

**Comment by Data66PF** [comment]
Yes you can use the same license.

**Comment by Data66PF** [comment]
I had this happen for my Latest Activity app that I made as I was trying to make view more to go to view_latest but it replaces it to be view/latest so I can now confirm this.

**Comment by Gatsby-PF** [comment]
What concerns me is that you did redirect successfully to a blog page in another post. So sometimes it works and sometimes it doesn't.  I don't like those kind of issues as the fix can be hard to prove out.

**Comment by Gatsby-PF** [comment]
Request that this issue be given priority for the next release as it is a severe disruption to new user experience and makes it impossible for site leader to redirect to a terms of service after signup.

**Comment by Data66PF** [comment]
@phpfoxdev please assign someone to this. Thanks :)

**Comment by neil96** [comment]
I tried many times but I can't reproduce this issue. If you want to redirect to internal link, don't put full url. Example your site is: *https://my-scrubbed-site.com/*, you want to redirect after "sign in"/"sign up" to *https://my-scrubbed-site.com/index.php/module/article/articleX*; just put in setting **"module.article.articleX"**
You can put full url here, but don't forget **http** or **https** on your link.

**Comment by Gatsby-PF** [comment]
100

**Comment by Gatsby-PF** [comment]
One hundred people out of one hundred will not know to do it this way unless there are explicit instructions for  a format spec for the setting at the setting. To get this straight, you did not try it with url format of:
https://my-scrubbed-site.com/index.php/module/article/articleX 

but rather just "module.article.articleX"? 
Without https:?

Donna did you understand what he just said? I am not sure I do.

**Comment by neil96** [comment]
This is my setting value:
![screen shot 2015-12-28 at 09 51 45](https://cloud.githubusercontent.com/assets/15936115/12013414/d336d7dc-ad48-11e5-9f80-5e2f96873b52.png)

After login, site will redirect to:
![screen shot 2015-12-28 at 09 52 14](https://cloud.githubusercontent.com/assets/15936115/12013418/e9841568-ad48-11e5-86d5-8b44a9b1a128.png)

If your site use https, it auto add https to url. If your site use short url, it will auto remove index.php.

**Comment by Gatsby-PF** [comment]
First off, let me say thanking you first for having picking up this issue (on Christmas Eve no less), and thanks to Donna(Data66PF) for interceding on this.

I tried it on two occasions with two different pages and the system ignored it and went where it always goes with no redirect defined.

This happened for both
forum.thread.4.terms-of-use-agreement
and
gettingstarted.article.article_7

each with its own new test user tested in series.
I noticed your redirected to a category, whereas these are actual TOU articles, one in forum, and one on an app page.

**Comment by Data66PF** [comment]
blog.7.christmas this works on non https site. I can't test with https.

**Comment by Gatsby-PF** [comment]
I was actually wondering how well the server was going to play with this formatting under the forced TLS regime. I do not understand what is the difficulty of parsing an ordinary url versus instead having to go with an internal format like this. Google is now giving preference to https sites in site rankings, and browsers are increasingly going to give http users a harder time, so it might be a good thing that those developing and testing the scripts take this into account.

**Comment by Gatsby-PF** [comment]
Is someone waiting for something from me on this?

**Comment by neil96** [comment]
Does it work on your side when you put setting like *blog.7.christmas*?
I tested and it worked with https.

**Comment by Gatsby-PF** [comment]
blog.5.newyears

I really hate to say this. Nothing.
