### ISSUE TITLE
Music Module

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#811]
Music uploads but does not playback.

**Comment by Vivian-phpFox** [comment]
Can not reproduce on V4.1.1.

**Comment by Data66PF** [comment]
Have you tested at our demo? What browser are you using? What OS? Are you on mobile or desktop?

**Comment by Gatsby-PF** [comment]
Could not reproduce on 4.1.1. Also check server fault log, browser content load issues in web and network consoles when trying to play song.

**Comment by Data66PF** [comment]
I'm unable to reproduce this on Neutron theme with chrome browser, win 10. Tested to play it in the main music section and then where it showed up in the profile and main feed. Do we need to do anything else to test?

**Comment by one44** [comment]
Using 4.1.0(build 2) and firefox  old uploads work but new uploads not playing.

**Comment by one44** [comment]
Ok tested in edge and shows format not supported but in FF shows as if it should play.
![2015-12-13 12_19_35-music bdsm south africa _ uk _ usa _ london _ ny _ durban_ gauteng _ adult dat](https://cloud.githubusercontent.com/assets/13656046/11766514/f64e12d2-a193-11e5-8f78-385e2271896e.png)
![screenshot-one44 net 2015-12-13 12-13-35](https://cloud.githubusercontent.com/assets/13656046/11766516/fcb9b1bc-a193-11e5-98bc-da197cedc92c.png)

**Comment by Data66PF** [comment]
cannot reproduce in edge browser with 4.1.2.
