### ISSUE TITLE
Like Unlike not working properly in v 4.1.1 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#812]
when i like my own comment its not working properly in news feed .After click on like its stay like not unlike but like icon display in front of it we have to refresh page to get it convert to unlike and After that same for unlike we click it like icon disappear but its stay unlike here. Tested on v 4.1.1 Chrome  and Mozilla Windows 7 having same problem.Also Bootstrap and Neutron Theme having same Problem.
![like unlike problem 4 1 1](https://cloud.githubusercontent.com/assets/13433124/11739556/67193e5c-a012-11e5-9ed7-b324a9100be6.png)

**Comment by Vivian-phpFox** [comment]
The text "Like/Unlike" only change after refesh page

**Comment by robert9592** [comment]
Fixed in v4.1.2
