### ISSUE TITLE
Cursor Problem in v 4.1.1

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#813]
when we roll over cursor over some section like send friend request section ,Report a section then its appear some special cursor instead of normal mouse cursor. Tested with v 4.1.1 chrome and Mozilla having same problem.

![img_20151211_153513](https://cloud.githubusercontent.com/assets/13433124/11741395/dccd407e-a01e-11e5-9956-0eedcda63458.jpg)
![img_20151211_154420](https://cloud.githubusercontent.com/assets/13433124/11741399/e1685628-a01e-11e5-8926-760f4763009c.jpg)

**Comment by SalmanKhan86** [comment]
Also in add cover photo

![img_20151211_155412](https://cloud.githubusercontent.com/assets/13433124/11742054/fabc669c-a022-11e5-86ce-aa676ef8485e.jpg)

**Comment by aakash83** [comment]
Also when you open a previously sent message it appears like this

**Comment by robert9592** [comment]
Fixed in v4.1.2
