### ISSUE TITLE
Can't able to share page post

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#814]
i can't able to share page post that i join recently.when i click on share icon... its does't show anything to me.tested it on v 4.1.1 
![page post share problem](https://cloud.githubusercontent.com/assets/13433124/11742278/9695b5a4-a024-11e5-8607-d645b0a922b0.png)

**Comment by Vivian-phpFox** [comment]
Confirmed, happened in previous versions

**Comment by Data66PF** [comment]
Normally status updates are not things that can be shared as it was designed that way.

**Comment by SalmanKhan86** [comment]
we have to enable it. in this way page post can reach to maximum users

**Comment by Data66PF** [comment]
It is marked a bug for fixing so this improvement is being looked at being added.

**Comment by robert9592** [comment]
Fixed in v4.1.2
