### ISSUE TITLE
[Bootstrap] JS errors

### ISSUE THREAD

**Issue by MichelangeloF** [moxi9/phpfox#815]
Plus there are 2 JS Error

"unreachable code after return statement main.js:2324:3
unreachable code after return statement ajax.js:434:2"

![immagine](https://cloud.githubusercontent.com/assets/11875594/11754954/482af4da-a04f-11e5-8cd1-9c5c2f166a60.png)

**Comment by Data66PF** [comment]
The phrase issue is already posted https://github.com/moxi9/phpfox/issues/226 . Please only post one bug per report. Since the js issue was not posted, we will deal with only the js issue in this ticket.

**Comment by neil96** [comment]
It just warning, not a bug.
