### ISSUE TITLE
Problem with redirects

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#817]
I am not sure whether it is a bug or not but  If a phpfox based community is set to be accessible only by members and a non logged in member when clicks on a link ( suppose a photo or file) which somebody shared on another website like facebook or twitter. Then system asks him to first log in so he can view that item. but  after logging in  phpfox  redirect him to index page and not to that item.
  
for example . If we directly open www.oursite. com /admincp/    then  phpfox asks us to first log in so we can access admin panel   but when we do the sign in step then phpfox redirect us to index page and not admin panel.

**Comment by Data66PF** [comment]
I cannot find the "same page redirect after login" setting that we used to have. my v3 site has it admincp/setting/edit/setting-id_86/

**Comment by robert9592** [comment]
Fixed in v4.1.2
