### ISSUE TITLE
Top menu problem on IOS 9

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#819]
tested with safari and chrome on iphone 6 with latest phpfox and bootstrap theme.

1:  when we click  menu button we get an expanded  menu but  if we click on it second time it don't collapse. so it remains open all the time.
![image](https://cloud.githubusercontent.com/assets/406030/11760572/69da304a-a0a0-11e5-8919-cab44e75c977.png)

**Comment by Data66PF** [comment]
Please post one bug per report. Please put your second bug in a new report.

**Comment by robert9592** [comment]
Fixed in v4.1.2
