### ISSUE TITLE
Buttons on quizzes 

### ISSUE THREAD

**Issue by jameskenney** [moxi9/phpfox#82]
When taking a quiz, some buttons will not show as being selected but only disappear. Buttons that disappear when selected will not be registered as being selected when you submit the quiz. 

![buttons](https://cloud.githubusercontent.com/assets/11656698/8655230/73feacbc-2955-11e5-9c23-3a67536ea927.jpg)

**Comment by RaymondBenc** [comment]
I believe this issue is related to this bug #58, we fixed in an earlier build.

This fix will be released to our Premium clients build later today.

**Comment by Data66PF** [comment]
Closed as fixed with the other issue and tests on the PF community show it works.
