### ISSUE TITLE
Cannot comment/upload photos as a page

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#820]
I know that in V3 there was an option that gave the user the possibility to use the account as a Page, but in v4 I can't find this option.

In fact, if you have a page and you try to upload photos in the "photos" section (and not from the homepage of the page, where you can select the method), you'll publish the photo as the user and not as the page.
Theremore, if you comment a post in your page, the comment is made by the user and not the page.

If only the user could choose to login as a page this problem'd be solved.

I don't know if is possible using Neutron, because I'm using the Bootstrap theme and with it you can't (or at least I don't find the place where to do it).

**Comment by Data66PF** [comment]
This is how it is designed in V4.

**Comment by optiroot** [comment]
Okay, maybe you mean that the fact to login as page is not designed in V4, but the fact that you should can comment and upload photos as a page yes.

Because this makes impossible to a page to follow users, at least with comments.
I think is a bug because the problem is if you comment on the page and not in the main feed.

**Comment by Data66PF** [comment]
Cannot reproduce. Tested with 4.1.1 neutron and bootstrap.

![my test page scripttechs test site](https://cloud.githubusercontent.com/assets/6908282/11767558/ed085462-a17f-11e5-8a98-15730f6d04b5.png)

**Comment by Data66PF** [comment]
There is no feature now to log in as page and act as a page on the site. It was removed so we cannot go to the pages' photos, for example, and upload a photo. For that, you would need a customization or to wait for other features to be added later.

**Comment by optiroot** [comment]
Okay, and for photos is as you say, but about comments? Try commenting a post that you made as page; and if you comment it, it shows up the user name and not the page's name.

So the problem is more for comments than photos...
Because the page should can interact with users, at least with comments.

**Comment by Data66PF** [comment]
That would be a feature request as that is not part of the features of our script at this time.

**Comment by optiroot** [comment]
Even if I think it should be of default because pages don't have much sense in this way, I'll ask in the request forum.

**Comment by Data66PF** [comment]
Right now we have to focus on getting the bugs fixed. We can't focus yet on adding new features. Once the script has most of the bugs fixed, we can look at other things. :)

**Comment by PhpFoxJohnJr** [comment]
"That would be a feature request as that is not part of the features of our script at this time."

Sorry, it should not have been removed...the was a reason for it.  There was no reason for removing it or is it another opportunity for someone in La La land to make an app :)
Sorry for the sarcasm but that excuse is getting old.
