### ISSUE TITLE
Sharing link as page doesn't work in some cases | Bootstrap theme

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#821]
If you publish in a page a link with text, there will be problems.
I tried with YouTube videos links.
So:
If you paste in the post a YouTube link then you write below, the post cannot be published.

If you paste in the post a Youtube link then you write before the link, all text will be deleted and will be shown just the embed video.

The only way is by pasting the link of the video, wait that the embed below shows, then delete the link and for last write content.

**Comment by Data66PF** [comment]
I believe this is working as designed or it used to be marked that way as the paste url needs to be grabbed and has always broken if text is added with it.

**Comment by optiroot** [comment]
Yes, it's right but normally you could be enabled to go on new line and write; at least an error message to the user could be useful, because it breaks the post layout.

**Comment by robert9592** [comment]
Fixed in v4.2.0
