### ISSUE TITLE
Cannot share a page post | Bootstrap theme

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#822]
If you try to share a post made by a page of the community, you can't and simply doesn't shows up the options.
Three dots to click are shown, as here:
![1](https://cloud.githubusercontent.com/assets/12573563/11762981/2994291a-a0f9-11e5-9a97-2cad7d59e6e7.PNG)

But if you click it, will show up an empty menu, as here (in the red circle):
![2](https://cloud.githubusercontent.com/assets/12573563/11762986/42460c94-a0f9-11e5-94a0-c090bee152a7.png)

**Comment by Data66PF** [comment]
please search before posting https://github.com/moxi9/phpfox/issues/814
