### ISSUE TITLE
Cannot share a post without text

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#823]
You can share posts made by other users without problems, but if you try to share a post from an user and you don't write anything in it, there will be the error that comes out if you try to public a post without text "add some text to your post" or something similiar (I use a language pack)

I'm using the Bootstrap theme.

I think should be possible to users to SHARE content without write anything... or not?

**Comment by Data66PF** [comment]
Please post feature requests at the forum for now as we need to focus only on bugs that break the script. This is how the script is designed.
