### ISSUE TITLE
bootstrap theme :Clicking "Sitename" Not always working

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#824]
tested on Iphone 6 with safari and chrome  having latest phpfox

when we are not on index page and for example we are on blogs page  .then clicking the site name 
(having a link to index page) on top don't  redirect  us to index page.
This bug is related to #819 . The current issue can be reproduced when the top menu is in expanded form.

**Comment by robert9592** [comment]
Fixed in v4.1.2

**Comment by aakash83** [comment]
@robert9592 I can still reproduce this issue in 4.1.2 . #819 is fixed now.
