### ISSUE TITLE
Can poke someone whos privacy poke permissions was set to No One.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#825]
The privacy permission poke still allows another to poke when set to No One. Pokee was admin, poker was another admin. This necessitates my having to audit the privacy permissions as if one is not working, others might not be either.  Is not every privacy permission tested and certified before issuing each new release (as lots of bug fixes can create new bugs in privacy settings for each round)?

**Comment by Data66PF** [comment]
Admins are allowed all permissions though. Did you test with non-admin accounts?

**Comment by Gatsby-PF** [comment]
Okay, just tested with registered user and could not poke. Closing.
