### ISSUE TITLE
SEO for PHPFox

### ISSUE THREAD

**Issue by jason1234h** [moxi9/phpfox#827]
I need the following settings for menu items, homepage, and other pages that are not password protected.

1. index/No Index option
2. Follow/No Follow option
3. No Archive option
4. No Image Index option
5. No Snippet option
6. Meta Title field
7. Meta Description field
8. Page Keyword field
9. Google Focus Words field

**Comment by jason1234h** [comment]
Not sure how to do SEO for my site without it.

**Comment by Data66PF** [comment]
Please post feature requests at our community in the feature request system. This tracker is only for bugs. Thank you. http://community.phpfox.com/forum/122/neutron-v4-feature-requests/
