### ISSUE TITLE
Bootstrap Feeds Missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#828]
4.1.1 Bootstrap theme. If we post in the feed and then try to post another status share, it is eaten and not posted. Main feed and profile feeds tests.

1. Log in with any user. I used admin user.
2. In bootstrap theme post a status share
3. Right after that one, post another status share. The post is eaten.
4. Post another and this one will post fine.

This was tested on the live demo and on my live development site.

https://youtu.be/p3y2tZIMsik video of the test.

**Comment by robert9592** [comment]
Fixed in v4.1.2
