### ISSUE TITLE
[Developers Section] Not listed on developers page

### ISSUE THREAD

**Issue by Jinkers** [moxi9/phpfox#829]
My developers account (KribApps) is not currently listed on the developers page of the PHPFox Store/Community (http://store.phpfox.com/techie/browse). I have filled out all areas of the profile in the account settings and still nothing. Have monitored for about a week and still I do not show. My profile is however accessible by direct link (http://store.phpfox.com/techie/u/gamekrib).

**Comment by Data66PF** [comment]
Store issue assigned to @RaymondBenc
