### ISSUE TITLE
Friend Page | Wonky Friend Page Doesn't Have Options

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#83]
Not sure if this is still in the works, but guessing not as it's a stable release, so posting as a bug. Going to your personal friends page doesn't let you do anything to manage friends. You can't remove them, organize them, or create lists as it seems you should be able to.

![image](https://cloud.githubusercontent.com/assets/6254165/8663608/fbe06e82-299a-11e5-9567-97e7262096e0.png)

**Comment by RaymondBenc** [comment]
At the moment it only allows to manage friends by placing them in specific lists that exist. To add a list, this is done when managing privacy settings, like when posting to the feed.

I'll leave this case open so we include the ability to add custom lists on this page as well as it does seem odd that we can't do that from here.

**Comment by Data66PF** [comment]
@GloriousKoch please test on the PF community as the feature has been enhanced.

**Comment by GloriousKoch** [comment]
Just went to check Community site. I notice there's now a "Manage Friends" button there but it's currently not clickable (for me at least).

**Comment by RaymondBenc** [comment]
Issue has been resolved for our next release, later today.
