### ISSUE TITLE
PF Community - Private Messages are Duplicating

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#830]
I've had several clients sending me pm messages and these are duplicating. Different clients, different devices, etc. This is just one example.

![pfcommunitypmdup](https://cloud.githubusercontent.com/assets/6908282/11780502/6904200e-a230-11e5-88f7-c5e6beeb033f.png)

**Comment by Gatsby-PF** [comment]
I have never seen that before.

**Comment by Gatsby-PF** [comment]
I have never seen that before.

**Comment by robert9592** [comment]
Fixed in v4.1.2
