### ISSUE TITLE
Mobile view login popup disappearing before it can be selected

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#832]
Invite only system. 
Tested on Firerox User Agent Switcher.

When first accessing the site, not logged in, in Android Smartphone screen resolution, user normally arrives at the sign-up dialog by default. 

To just login using mobile, the user has to click the down arrow symbol in the extreme upper right corner first. When hovered over, this arrow opens a pop-up with a "Login" option just below.  When attempting to move the cursor to the login option in the popup, the popup disappears as soon as the cursor leaves the down arrow cursor limit (before it can get to the command in the pop-up). This is similar to that issue we had with the user-info tooltip disappearing.

End result being, no one can log in using mobile (easily). If I try hard enough and long enough I can manage to catch it once in a while.

**Comment by robert9592** [comment]
Fixed in v4.1.2

**Comment by Gatsby-PF** [comment]
This is continuing to do the same thing after the upgrade to 4.1.2  Login button disappears before you can reach it. Since this is an invite only system, the inviter displays by default.  When attempting to access the login button, it disappears before I can click on it.  Using Firefox user agent switcher in Android which I know is not a perfect substitute.
