### ISSUE TITLE
Profile side panel mode issues in mobile

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#833]
Test Setup: Enter user profile with About me and some friends in friends block.
Firefox user agent switcher in Android mode.

There were two issues discovered using mobile Smartphone resolution when opening someones profile as described above, and then entering into the side panel by clicking the left pointing chevron (arrow) on the right of the display. This should bring About Me and Friends and Pages into view.

1. Is the About Me block title area partially covered by the breadcrumbs bar at the top? I had to adjust it downward about 40px.

2. When Hovering over username on Friends avatars, only partial user info tool tip was available and it looked broken.

**Comment by Data66PF** [comment]
@neil96 or other techs, we need testing for this

**Comment by neil96** [comment]
I can't reproduce this issue. Could you give us some screenshot?
Please testing on real device. Because on mobile don't have event hover, so I ignore point 2.

**Comment by neil96** [comment]
I will reopen this issue if you provide more information. Thanks!
