### ISSUE TITLE
Page view issue in mobile

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#834]
When viewing a page in mobile Smartphone resolution using Android simulator, 

the layout has multiple overlapping objects, 
the breadcrumbs menu overlaps the photo, and
photo and events links in the page menu go missing.

**Comment by robert9592** [comment]
Fixed in v4.1.2

**Comment by Vivian-phpFox** [comment]
Fixed in v4.2

**Comment by Gatsby-PF** [comment]
This was not fixed in v4.2. Doing same thing with neutron default theme.

**Comment by neil96** [comment]
This issue will be fixed in 4.2.0, not 4.1.2.
