### ISSUE TITLE
Song posted in activity feed has most of title cut off in mobile

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#835]
Smartphone resolution bug in Android simulator.
A song posted by the system in the activitiy feed shows the entire playbar, albeit compessed, but the title letters are large H1 22px, and most of the title gets cut off and does not wrap around. Very hard to tell what song you are going to listen to.

Also, the playbar and title should be left justified to use more of the available area inside the content area for title and playbar.

**Comment by Data66PF** [comment]
Simulators don't do well in testing responsive themes as the theme tends not to see it as a mobile device and sees it as whatever screen you actually have. That's what I was told anyway. We will test this though, on a device to see if we can get your issue. Please be sure to post screenshots when posting visual bugs.

**Comment by Data66PF** [comment]
@neil96 or other staff, we need testing

**Comment by robert9592** [comment]
FIxed in v4.2.0
