### ISSUE TITLE
Theme installing problem

### ISSUE THREAD

**Issue by raviji** [moxi9/phpfox#838]
Version: 4.1.1

1. Am not able to install any theme from store, for ex: Wisteria theme tried many times to install but its not working. Any solution for this?
2. Short url also not working.

**Comment by Vivian-phpFox** [comment]
Cannot reproduce in V4.1.1

**Comment by raviji** [comment]
Ok then can you fix these in version: v4.1.2? 

Please share me how to install theme? this also cannot reproduce?

**Comment by Data66PF** [comment]
Note that if you are using chrome browser, it won't work right now. Use a different browser. If you are using other browsers and it still won't work, please see the various forum posts in our community as it would be a server issue that you would need to fix.
I cannot reproduce this issue on my live development site.
