### ISSUE TITLE
Store - Developers profile on phpfox - suggestion

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#839]
Some suggestions for improvement:

1 - Add a "see more" button to the end of the reviews so we can read all the text.
2 - Add a "see more" button on the bottom of the apps so it can list more apps.
3 - Add text box on the right collumn so members can write to the developer

Thanks

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#17
