### ISSUE TITLE
[Pages] Can Not Disable Page Feature

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#84]
This is in relation to a previously closed issue. I notice it went out as a fix but it's still not giving me the option to disable pages or even remove it from the sidebar menu. I'm currently running the 4.0.1 software which is labeled on the bottom of the module info. Here is the previous issue which it was addressed: https://github.com/moxi9/phpfox/issues/77

Here are some images as references:

No Option To Disable:
![image](https://cloud.githubusercontent.com/assets/6254165/8668967/77dc986a-29de-11e5-8461-dce1f10e7981.png)

Shows Up On The Menu:
![image](https://cloud.githubusercontent.com/assets/6254165/8668972/85cc2972-29de-11e5-9697-8ddc84881277.png)

No Option To Remove It From The Menu:
![image](https://cloud.githubusercontent.com/assets/6254165/8668984/90c32c72-29de-11e5-9641-47bbf356dce1.png)

**Comment by Data66PF** [comment]
Go to Maintenance and click Find Missing Settings. Once that runs, clear cache. Then go to Maintenance and click Toggle Modules

**Comment by Data66PF** [comment]
That pulls it without the phrases so I'm now running Find Missing Phrases found in Settings >> Language and click to the left of the English language and select it from there.

**Comment by GloriousKoch** [comment]
I just ran the following steps and now when I reload the page, nothing comes up except the title on top left. What caused this and how can I repair it? Thanks.

![image](https://cloud.githubusercontent.com/assets/6254165/8670511/d2339be4-29eb-11e5-8fb9-db0ba061900b.png)

**Comment by Data66PF** [comment]
Did you wait for it to run as it takes a few minutes? Did you clear cache after?

**Comment by GloriousKoch** [comment]
Yes, waited for it to complete for sure and then did the clear cache. The 'guest' main page seems fine with the registration box still there, however, when logged in, that's all that shows in the image above.

**Comment by GloriousKoch** [comment]
Okay update:

When I go and disable the Pages feature, it does the blank screen. When I re-enabled it, it comes back, but still then left with the issue of not being able to disable the Pages feature.

**Comment by Data66PF** [comment]
Always enable debug if you see issues on your site.

**Comment by Data66PF** [comment]
Ok I have debug on my site and if we try to disable Pages, we get the following:

Calling a Service from an invalid Module. Make sure the module is valid or set to active. (pages::pages)

**Comment by GloriousKoch** [comment]
Can you direct me on how to enable debug for the site? We plan on being very active, so anything I can do to help with info while submitting issues here, I'd like to do with the best info for the devs. :)

**Comment by Data66PF** [comment]
Did you read the readme? It says how.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox at the bottom of the readme. don't leave debug enabled for a live site once done debugging just rename the file.

**Comment by GloriousKoch** [comment]
Excellent thanks. I've read a whole lot the past couple weeks getting excited for this new version. Thanks for your patience while I gather it all in. :)

**Comment by Data66PF** [comment]
My scripttechs.com has tutorials for v3 which should help some in v4. Will add some for v4 at some point too.

**Comment by GloriousKoch** [comment]
Closing this issue and consolidated updated information into a new one for easier reference for the devs here: https://github.com/moxi9/phpfox/issues/89
