### ISSUE TITLE
Ads | New Placement

### ISSUE THREAD

**Issue by Skeaten** [moxi9/phpfox#840]
When i want to create a new Placement the block loading endless.
I use version 4.1.1
![unbenanndt](https://cloud.githubusercontent.com/assets/16337531/11871410/b26b5b4e-a4cf-11e5-961f-242bb1a5ea43.png)

**Comment by neil96** [comment]
Could you tell us which browser and OS you are using? it's working fine on my side.

**Comment by Skeaten** [comment]
Hey Neil,
I use Windows 10 64 bit with the newest Update. 
I tested it with Google Crome and Microsoft Edge.

**Comment by Data66PF** [comment]
Cannot reproduce with win 10 and latest chrome. Using 4.1.1 build 3, Neutron theme.

**Comment by Skeaten** [comment]
How i can fix it? Its a Clean installation.

**Comment by Data66PF** [comment]
Enable debug and check for errors. Check with developer browser console to see if there are errors there. Make sure mod_sec on the server is not interfering (tweak it if it is).

**Comment by Skeaten** [comment]
Failed to load component: ad. [..]/PF.Base/module/ad/include/component/block//.class.php)

**Comment by Data66PF** [comment]
was that the full error code? it looks like it is trying to load a block for the ad module. Did you add anything such as a block or app or module to your site?
