### ISSUE TITLE
phpfox inserting security token in wrong spot, breaking the form

### ISSUE THREAD

**Issue by mikemakuch** [moxi9/phpfox#841]
I have a form with an action url and in the cached template phpfox is inserting the security token code in the wrong place. Here is the line of code in the template;

```			<form method="post" action="{php}Phpfox::getLib('phpfox.url')->makeUrl('mrccommunity.onboarding2');{/php}"> ```

and here is the corresponding line of code in the cached template;

```        <form method="post" action="<?php Phpfox::getLib('phpfox.url')->
<?php echo '<div><input type="hidden" name="' . Phpfox::getTokenName() . '[security_token]" value="' . Phpfox::getService('log.session')->getToken() . '" /></div>'; ?>makeUrl('mrccommunity.onboarding2'); ?>">```

as you can see the security token is inserted in the middle of the action value. What is going on?

Thanks
Mike

**Comment by mikemakuch** [comment]
I just realized what's likely happening. The template parse is seeing that ">" of the -> operator and erroneously believing that is the closing ">" of the form tag. Question is how do I get around it?

**Comment by neil96** [comment]
Please try again with this form:
<form method="post" action="{url link='mrccommunity.onboarding2'}" enctype="multipart/form-data">

Your form is strange with our default code.

**Comment by mikemakuch** [comment]
What form?

**Comment by mikemakuch** [comment]
Ok, I fixed it by doing this;

```                        <?php 
                        $tmp = '<';
                        $tmp .= 'form method="post" action="';
                $tmp .= Phpfox::getLib('phpfox.url')->makeUrl('mrccommunity.onboarding2');
                        $tmp .= '"' . '>';

                                echo $tmp;
```

You're parse is kinda lame IMHO.

Thanks
Mike

**Comment by mikemakuch** [comment]
Ah, so I should finish RTFM! Thanks.

**Comment by Data66PF** [comment]
In the future, please post questions in our community once you've checked the developer documentation at our knoweldgebase. Thanks.
