### ISSUE TITLE
videofeed in phpfox v4.1

### ISSUE THREAD

**Issue by Goudarzi-hahram** [moxi9/phpfox#842]
hello:
After upgrade to phpfox v.1.0
videofeed , plugin does not work

**Comment by Data66PF** [comment]
Can you please describe the issue in more detail? I'm not having an issue on my development site with adding a video to the video section.

**Comment by Data66PF** [comment]
Are you testing on 4.1.1 build 3 or 4.1.0? Do you have long urls or short urls enabled on the site? What theme are you testing? Does it not work at all or does it only work on Vimeo videos for example?

**Comment by Data66PF** [comment]
We've fixed this in the app. Please click to get the app again in order to get the fix.
