### ISSUE TITLE
Bootsrap theme . Feed Styling Issue on mobile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#844]
latest phpfox version ,Tested on Iphone 6 with  chrome
When an item e.g. a photo  is liked by 3-4 persons then the entry in feed showing member names is not properly displayed as shown in screenshot.

![image](https://cloud.githubusercontent.com/assets/406030/11911427/38969fe4-a615-11e5-93b9-38e14ee7c25b.png).

**Comment by Data66PF** [comment]
confirmed with iPhone 5c on PF demo

**Comment by robert9592** [comment]
Fixed in v4.2.0
