### ISSUE TITLE
Bootsrap theme(mobile version) Pages header issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#845]
Latest phpfox  iphone 6  and chrome
Header menu and buttons on a page having a long  name are not properly displayed.
![image](https://cloud.githubusercontent.com/assets/406030/11911507/e9e6f92c-a617-11e5-93be-24ae1ba4f262.png)

 Sometimes  for short named pages edit page button is overlaping with other buttons.
![image](https://cloud.githubusercontent.com/assets/406030/11911499/bd6d2722-a617-11e5-94d7-4c99f023f67e.png)

**Comment by robert9592** [comment]
Fixed in v4.2.0
