### ISSUE TITLE
Bootsrap theme . Pages discussions wrong hyperlink

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#848]
latest phpfox  , chrome and a page having no forum posts.

![image](https://cloud.githubusercontent.com/assets/406030/11911574/2f8deb78-a61a-11e5-97a8-7bae1ca03ee0.png)

**Comment by Data66PF** [comment]
confirmed 4.1.2

**Comment by neil96** [comment]
Fixed on V4.2.0
