### ISSUE TITLE
Bootstrap Theme , photo battles ,styling issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#849]
latest phpfox with chrome 
Go to photos >> photo battles >> open full mode
Now sometimes we get a proper display sometimes photos are overlapping. To reproduce this issue we need to  try several times as it loads different photos each time . so photos having big size are not properly displayed.

**Comment by Data66PF** [comment]
Photo battles is not a feature of V4. If you have it enabled, please disable it and let us know how you enabled it as I don't even see the settings in 4.1.2.

**Comment by aakash83** [comment]
it was enabled by default.

**Comment by Data66PF** [comment]
I don't have this on my sites. Nor do I see it at our demo.

**Comment by Data66PF** [comment]
Photo battles were removed from V4 but I see the direct link is still accessible. We need to completely disable access to disabled features. Will bug this for us to disable the link. Third party developers can make the photo battle feature as an app.

**Comment by robert9592** [comment]
Fixed in v4.2.0
