### ISSUE TITLE
[Pages] Brings Regular Members To Membership Page

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#85]
When a regular member clicks the menu option to use the Page Create feature, it brings them to the memberships page instead.

![image](https://cloud.githubusercontent.com/assets/6254165/8669021/d87c3dc4-29de-11e5-8eb5-75d7282d8209.png)

This does not happen when an Admin clicks it, as it brings them to the proper section.

**Comment by Data66PF** [comment]
Did you check your user group settings?

**Comment by GloriousKoch** [comment]
That was it. Sorry, had a derp moment and didn't even think to check that. Sorry, and closing. :)
