### ISSUE TITLE
Bootsrap theme . forum navigation issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#850]
latest phpfox with chrome on windows 10

after creating a new forum thread  and when we are on the new thread page there is no way to go back to  other part of forum . only way is to click the forum button on main menu.
![image](https://cloud.githubusercontent.com/assets/406030/11911657/382658c6-a61d-11e5-865b-a33699485e6d.png)

**Comment by Data66PF** [comment]
tested in 4.1.2 and I can reproduce this. There is no breadcrumb or left menu for navigation.

**Comment by robert9592** [comment]
Fixed in v4.2.0
