### ISSUE TITLE
Bootsrap theme . cannot select forum threads and replies

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#851]
we do have select and unselect buttons on a View thread page but  we dont have nay check boxes. also select un select  thread or replies buttons are not working.
![image](https://cloud.githubusercontent.com/assets/406030/11911673/c5080596-a61d-11e5-8214-34f5349ca8a3.png)

**Comment by Data66PF** [comment]
Cannot reproduce in 4.1.2 chrome on win 10 desktop view. I can select several threads. I can unselect them by clicking the Clear all and it works for me.

**Comment by neil96** [comment]
Fixed on V4.2.0
