### ISSUE TITLE
Bootsrap theme . forum thread (and replies) author name cropped

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#852]
latest phpfox with chrome
![image](https://cloud.githubusercontent.com/assets/406030/11911685/3a12761e-a61e-11e5-9d76-a68be9ada51b.png)

**Comment by Data66PF** [comment]
confirmed in 4.1.2 but this is working as designed. however, will mark a bug in case it can be fixed just for the forum thread view.

**Comment by robert9592** [comment]
Fixed in v4.2.0
