### ISSUE TITLE
Bootstrap Theme-moving a thread to another category

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#854]
latest phpfox with chrome on win 10.

create a thread  in a category e.g. computers  after that  move it to another category .now  come back to main forum page . we can still see post count 1 in computers . but when we open it we can't see any post. 
![image](https://cloud.githubusercontent.com/assets/406030/11911726/7182dee4-a61f-11e5-9637-a503f52549d6.png)

**Comment by Data66PF** [comment]
cannot reproduce this in 4.1.2. Note that you might need to clear cache if your server is slower to respond.

**Comment by aakash83** [comment]
@Data66PF  Event after clearing cache i can still having same issue.
