### ISSUE TITLE
Bootstrap Theme - forums- items per page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#855]
latest phpfox with chrome
Goto Forum  and from left menu  when we choose forums which is by default chosen we have option to select how many items per page we can view( using the drop down menu on right) . but form all other three menu  items (New Posts , My Threads , Subscribed Threads)  we only have  option  (20 items per page) .
![image](https://cloud.githubusercontent.com/assets/406030/11911739/38c8dce2-a620-11e5-856c-18c50b821db5.png)

**Comment by Data66PF** [comment]
As with the other issue reported, I think this should be removed. We should just show the default categories if we show anything. That menu with sort, show, and when is not needed in the forum area.

**Comment by robert9592** [comment]
Fixed in v4.2.0
