### ISSUE TITLE
Bootstrap Theme - Search issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#856]
latest phpfox with chrome
when use the main search located on top  our url look likes this 
http://www.yoursite.com/search/?q=test

when we use  search form a module  like forum polls   our serach page url looks like 

http://www.yoursite.com/forum/search?s=1&search%5Bsearch%5D=test
http://www.yoursite.com/photo?s=1&search%5Bsearch%5D=test

**Comment by Data66PF** [comment]
I don't see any issue. This is how it is designed as the search is specific to that module.
