### ISSUE TITLE
bootstrap theme - cannot select events

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#858]
Goto pages >> select any page and  create event.  after that come back to  Page events page . now we dont have any option to select  a single event. we do have a  select all  button  but that one is also not working. 
![image](https://cloud.githubusercontent.com/assets/406030/11911839/b596ec66-a623-11e5-90d3-650800b57b0e.png)

Important Note : most of the places where you used these select buttons ,they are not working. one example is this one and one is when we are viewing a forum thread #851

**Comment by Data66PF** [comment]
confirmed 4.1.2

**Comment by robert9592** [comment]
Fixed in v4.2.0
