### ISSUE TITLE
Bootstrap Theme ."Share"  behaviour

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#859]
Latest Phpfox with chrome
Not sure whether it is  bug or not.

when we want to share a feed item( photo ) which was posted by another member  on our wall it says we should add some text. but  if we select "share on a friends wall" then there is no such restriction to add text.   in my opinion there should be no restriction when we share that item on our wall also.

**Comment by Data66PF** [comment]
Sharing to your own wall is a status post and this is how it was designed but I'll leave this one open for another team member to also see what they think.

**Comment by neil96** [comment]
I agree with @aakash83
