### ISSUE TITLE
bootstrap theme - "Share " issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#860]
When somebody share a photo and appears in feed we can share it on our wall or on a friends wall  but   if the status contains only  text   then when we click share button  it only shows option to   share with friends which we select as shown below.
![image](https://cloud.githubusercontent.com/assets/406030/11911919/5545f240-a627-11e5-9e36-f8d20d59f00d.png)

**Comment by Data66PF** [comment]
This is how it is designed.
