### ISSUE TITLE
Message Pop Up Box is Not Closed

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#861]
When I reply to messages, and from there want make a status update, by clicking "What's up?", the message box is still displayed, the screen below is updated but this box ask do you want to leave this page. and close.
Same is the case in case of Search when, replying to messages when we click on Search the Message box overlaps the Search Window. Tested with v 4.1.1 Both Chrome and Mozilla having same problem.
![message box overlap status update](https://cloud.githubusercontent.com/assets/13433124/11912631/9cbd637a-a66c-11e5-8d5a-149e57adc66f.png)
![messsage box not closed](https://cloud.githubusercontent.com/assets/13433124/11912636/a6d480fa-a66c-11e5-99a1-636aff3cb793.png)

**Comment by Data66PF** [comment]
I can reproduce this on the 4.1.2 site when replying to a message, the box should close after. Tested with bootstrap theme. We can manually close it though so it's not a huge issue. I partly think this is working as designed but fixing it could improve the experience. Problem is, a small amount of clients would want it to stay open. Not sure of a "best" solution.

**Comment by neil96** [comment]
Fixed on V4.2.0
