### ISSUE TITLE
No option to disable activity points

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#862]
There's no option to disable activity points, I' know some people like to have activity points on their website, but their just not for my site :) I'm sure there's other sites, that dont want them :)

**Comment by Data66PF** [comment]
I can confirm that when we enabled showing activity points, I can't find the setting where we enabled to disable showing them. We used to have one. Could we please add it back? Option to enable/disable showing activity points in that profile drop down where they show.

**Comment by Lukey199223** [comment]
Thank you for registering it as a bug :)

**Comment by neil96** [comment]
Fixed on 4.2.0
