### ISSUE TITLE
No Create an Album button for Photo Albums

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#863]
V4.1.2 and previous. We have in the photo section only an option (button) to upload an image. We see no option (button) to create an album. However, if we go to the music section, we can either upload a song or create an album. We should have this uniform in the site. Please add a create an album button in the photo section as we have in the music section.

You'll see the create an album if going to music/browse/album/view_my-album/

Marking a bug as the phrase in the photo/albums/view_myalbums/ shows Upload a new image rather than Create an Album.

**Comment by RaymondBenc** [comment]
This issue was moved to moxi9/phpfox-feature-requests#1
