### ISSUE TITLE
Alizarin theme- Forum features not working

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#865]
I'm slowly checking for bugs in the Alizarin theme just incase phpfox doesn't know about them already :) 

I Just checked the forum page, and none of the features (bold, text change colour etc) are working I'm not sure if this is a bug or I've done something wrong in my css, I think its a bug though as I haven't gone near the forum page

**Comment by Data66PF** [comment]
Those features are not part of the default script. You must be using an app.
