### ISSUE TITLE
Theme installation issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#866]
I'm gettin following error when trying to install the Green Sea theme with Phpfox v4.1.1

> # Exception thrown with message "Undefined variable: folderTheme"
> # 
> # Stacktrace:
> #13 Exception in /home/xxx/public_html/PF.Base/start.php:182
> #12 Whoops\Exception\ErrorException in /home/xxx/public_html/PF.Src/Core/Theme.php:184
> #11 Whoops\Run:handleError in /home/xxx/public_html/PF.Src/Core/Theme.php:184
> #10 Core\Theme:make in /home/xxx/public_html/PF.Src/Core/Theme.php:115
> #9 Core\Theme:import in /home/xxx/public_html/PF.Base/module/admincp/include/component/controller/app/add.class.php:64
> #8 Admincp_Component_Controller_App_Add:process in /home/xxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:1010
> #7 Phpfox_Module:getComponent in /home/xxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:531
> #6 Phpfox_Module:getController in /home/xxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:318
> #5 Phpfox_Module:setController in /home/xxx/public_html/PF.Base/module/admincp/include/component/controller/index.class.php:656
> #4 Admincp_Component_Controller_Index:process in /home/xxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:1010
> #3 Phpfox_Module:getComponent in /home/xxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:531
> #2 Phpfox_Module:getController in /home/xxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1318
> #1 Phpfox:run in /home/xxx/public_html/PF.Base/start.php:136
> #0 require in /home/xxx/public_html/index.php:7

**Comment by neil96** [comment]
On V4.2.0, we have new way to install theme. So, this issue should close.
