### ISSUE TITLE
Edit Profile ZIP/Postal Code: Issue

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#867]
While editing profile, ZIP/Postal Code: accepts any input as opposed to just numbers.
testing with v 4.1.1
![pin code bug](https://cloud.githubusercontent.com/assets/13433124/11948900/3352d872-a89f-11e5-8eae-9b48df405d3f.png)

**Comment by Data66PF** [comment]
As there are countries that use both letters and numbers, this needs to be like that. https://en.wikipedia.org/wiki/List_of_postal_codes
