### ISSUE TITLE
Profile name is duplicated while sharing Photo

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#868]
Profile name is duplicated while sharing photo status update. 
test with v 4.1.1
![photo share functionality](https://cloud.githubusercontent.com/assets/13433124/11948925/81e9e78c-a89f-11e5-8748-3f9d9d3a5c22.png)

**Comment by Data66PF** [comment]
I tested this in 4.1.2 and it seems fine to me as I am resharing something that someone else posted. It shows the original poster's name in the image and then above that, it shows my name. The image is giving attribute (acknowledgement) to the original poster of the image. To me, this is how I want it to work on my websites as my authors would want others to know that they originally shared the item.
![statuspost](https://cloud.githubusercontent.com/assets/6908282/11958897/86487584-a898-11e5-8ebd-92893d01b059.jpg)

**Comment by neil96** [comment]
I think this issue because you shared your own post.

**Comment by SpaniNet** [comment]
It's not a bug, you can share your own posts.
