### ISSUE TITLE
Neutron Template Overlap...

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#87]
If you have pictures enabled in the "Like" module settings then the pictures cover the "Like" button and it wont work.

![overlap](https://cloud.githubusercontent.com/assets/13330878/8671091/3b34a346-29f0-11e5-84c6-2ebce5532ee2.jpg)

**Comment by RaymondBenc** [comment]
Was this setting enabled in v4 or in v3?

**Comment by orgazilla** [comment]
Upgraded from V3 to V4.

**Comment by Data66PF** [comment]
marked as a bug as we need to remove the setting or fix the alignment
