### ISSUE TITLE
Users cant login

### ISSUE THREAD

**Issue by Sethrono** [moxi9/phpfox#871]
My users cant login after successful registration. I also cannot login to the admin account. My issue appears similar to a closed issue that was posted earlier https://github.com/moxi9/phpfox/issues/279  . I strongly suspect the issue to be a bug because I had not done anything invasive when the problem arose, I was only configuring filezilla, and it had not yet connected to my server. Other than that, I had earlier installed the sms captcha app which I un-installed soon after. I also installed the video feed and recaptcha app, but my site was stable for over 24 hours after this modification. I have posted the issue on the community website under the link http://community.phpfox.com/forum/thread/53596/i-cant-login-to-my-admin-account/  , data66 advised me to upgrade a user to an admin directly from the database but Im sceptical of this solution because now it appears that all my users cannot login consistently. Kindly assist

**Comment by Data66PF** [comment]
Making a second admin is advised.

As for not logging in, that is normally an issue with the database with crashed tables. Have your host check. 

That other issue was due to the clients not running the upgrade routine as it has a new password routine if upgrading from v3 to v4.
