### ISSUE TITLE
Not display the image properly in Quiz module.

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#874]
I create Quizzes.
upload Banner 
save

now i can see the image uploaded not display properly.

please check.

**Comment by Data66PF** [comment]
Please provide a screenshot of the issue.

**Comment by Data66PF** [comment]
Images that are the proper size look fine to me at our demo. As we got no response for a screenshot, we will close this for now. Please open a new issue if you still see issues after our 4.2 release.
