### ISSUE TITLE
Like Feature is not working Properly in Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#875]
when we like any post in timeline or in news feed then its not reflect to its like count.when we refresh it its show feed like count. Tested with Android OS Neutron Theme Chrome Browser v 4.1.2

when i press like count not shown.
![screenshot_2015-12-24-14-30-08](https://cloud.githubusercontent.com/assets/13433124/11992720/48ec3384-aa4f-11e5-8622-77759671a9fa.png)

 when i refresh page now its show count..
![screenshot_2015-12-24-14-31-11](https://cloud.githubusercontent.com/assets/13433124/11992732/65ac707e-aa4f-11e5-85f1-8022404a1d7b.png)

**Comment by robert9592** [comment]
Fixed in v4.2.0
