### ISSUE TITLE
Edit Thread Issue

### ISSUE THREAD

**Issue by Rodios** [moxi9/phpfox#878]
When i edit a thread the edit page include all forum Attachments.
Version: 4.1.2-b4

**Comment by Vivian-phpFox** [comment]
Kindly add more info and screenshort to reproduce this issue

**Comment by Rodios** [comment]
When i edit a thread from Thread Tools the edit page include all forum Attachments.
![capture](https://cloud.githubusercontent.com/assets/16224843/12000754/fdf7b092-aae4-11e5-854c-4e975f8e5a2f.PNG)

**Comment by neil96** [comment]
Fixed on V4.2.0
