### ISSUE TITLE
Mobile template doesn't work...

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#88]
If you view profile on the mobile device, the letters from the comments are in a vertical line...

Like this...

H
E
L
L
O

**Comment by RaymondBenc** [comment]
Issue fixed on live community and pushed to client dist https://github.com/moxi9/phpfox-dist/commit/4b7a8417afa986f3219f50cc656e170b5a6bb26c

**Comment by orgazilla** [comment]
Thank you!
