### ISSUE TITLE
Mail signature not appearing on invites sent

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#883]
When sending invitations, the signature does not show us so all the invietee gets is this

Jo Schmoe invited you to weapparenetlydontknowwhatweredoing.com
To access you invite go to this link
http://weapparentlydontknowwhatweredoing.com/irwu-42u-ut24u982irr98wifu9ursf9ry9eu98
The invite message stopped here.

This is where the signature and brief sumary of what the site is about is supposed to appear, but does not.

When the email validation message arrives, the signature DOES show up in that message. Not the original one. So no one knows what the site is even about when they are invited.

The sitename chosed for the example has nothing to do with you or PHPfox.  It is what I as an invitee would think of naming a site that sends me only half an invitation.

**Comment by neil96** [comment]
Fixed on V4.2.0
