### ISSUE TITLE
One New Update in Feed - No New Feeds

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#885]
4.1.2 demo as it's more active to test on. Be on the main feed in bootstrap or neutron theme. Tested with chrome on win 10. Below is how I've been able to get this to reproduce consistently.

Scroll down the feed to grab more feeds. 
Then, go back up to the top of the feed.
 In another tab, go look at github issues (as an example) and come back to the site after a minute or two. 
You will see the 1 new update.
 Click that and you will see There Are No Feeds to View at This Time message.
![412feedno2](https://cloud.githubusercontent.com/assets/6908282/12019098/ccb8c050-ad39-11e5-928f-3821e370046b.png)

**Comment by Vivian-phpFox** [comment]
Fix on V4.2
