### ISSUE TITLE
issue 824 is not fixed but marked as fixed and closed.

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#888]
Issue #824  is marked as fixed and closed but i can still reproduce it.

**Comment by Vivian-phpFox** [comment]
Can you reproduce this issue on demo site?

**Comment by aakash83** [comment]
no on demo site it is working fine. which version you are using on demo site??

**Comment by neil96** [comment]
https://v4.phpfox.com/ is using V4.1.2.
We can't reproduce this issue on any sites we have.

**Comment by Data66PF** [comment]
Is your site an upgraded site from v3 before?

Are you using any apps or third party products?
Have you made any changes to bootstrap theme and did you remember to Revert Theme when you upgraded (noting that if you made any changes to it, those changes would be erased)
