### ISSUE TITLE
a bug for a long username

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#889]
upgraded from v3.8.0(build 1) to v4.1.2
line going top left side
how to fix

![screenshot 2015-12-29 18 36 38](https://cloud.githubusercontent.com/assets/3644262/12053808/a75567ac-aeea-11e5-998f-44d0b60d2aea.png)

**Comment by robert9592** [comment]
Fixed in v4.2.0

**Comment by wlongdonstudio** [comment]
when 4.2.0 releasing?
