### ISSUE TITLE
[Pages] Disabling Pages Module Turns Entire Site Into Blank White Screen

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#89]
Consolidated information from: https://github.com/moxi9/phpfox/issues/84

Upon disabling the module for member created Pages, the entire website will turn into a blank screen while signed in.

Per @Data66PF:

"Ok I have debug on my site and if we try to disable Pages, we get the following:

Calling a Service from an invalid Module. Make sure the module is valid or set to active. (pages::pages)

This could be because the pages module is the only one that is a menu but not in the menu list."

**Comment by RaymondBenc** [comment]
Fix pushed to client dist build https://github.com/moxi9/phpfox-dist/commit/e43d713e58b5590496da6a584ae6512e2dcd0f0b
