### ISSUE TITLE
Logout Disappears on Low Screen Resolutions

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#890]
Posted by a client in the forum. He has no logout buttons on his themes (neutron and any based on neutron).
1024*768 resolution
![no logout](https://cloud.githubusercontent.com/assets/6908282/12054790/68acc4be-aef4-11e5-8476-a18ae9fe5a55.jpg)
Screen shot is from my dev site when I tested with that low resolution.

**Comment by ajaymenonv** [comment]
I will await for it

**Comment by neil96** [comment]
Fixed on V4.2.0

**Comment by ajaymenonv** [comment]
Hi how can i get V4.2.0

**Comment by Data66PF** [comment]
Please watch our blogs for the release and for updates, http://blog.phpfox.com/
