### ISSUE TITLE
forum new post redirecting to a category because:

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#891]
because "thread" phrase missing in url..

**video**: https://streamable.com/zz52

everytime, new problems.... and everytime, Im installing it again. I think that: maybe it is really big script in the markets but it has so many bug...

**Comment by perayknox** [comment]
I changed themes. it isn't related with theme or fresh install. :)

**Comment by Vivian-phpFox** [comment]
Can not reproduce in V4.1.2

**Comment by Data66PF** [comment]
https://v4.phpfox.com/forum/thread/12/test-iplik-ba%C5%9Fl%C4%B1k-t%C3%BCrk%C3%A7e/ unable to reproduce

**Comment by perayknox** [comment]
it's not related with turkish title!!!!!!!
I tried it different titles without turkish character!!!

**Comment by perayknox** [comment]
it's not related with turkish title!!!!!!!
I tried it different titles without turkish character!!!

You're working without test it!

I'm capturing a new video. wait and change the "closed" tag for this issue please.

**Comment by perayknox** [comment]
Look, the video is here:
https://streamable.com/y4jx

**Comment by Data66PF** [comment]
I did test. I tested with and without the turkish characters before and I tested again. It was closed because we cannot reproduce it. https://youtu.be/BWM7La1Gga8 my testing again, on video.

**Comment by perayknox** [comment]
but believe me, I installed the phpfox again and this problem still here.. I'm using v4 language pack and also I tried with fresh install and English language pack (default lang, default settings, default everything)

**Comment by Data66PF** [comment]
Ok that is odd. Please give us more information about:

Do you have short urls enabled?
Is the script in the root or in a subfolder or subdomain?
Is https enabled?
Do you have any app at all installed?
What theme?
Any changes to the theme?
Any ads enabled or added to the site?

Can you think of anything you may have set or changed that is different from our default install?
Can you please test at our demo to see if you can reproduce it there? http://v4.phpfox.com 
If you can reproduce it at the demo - what browser, os? Is it desktop or mobile?

**Comment by perayknox** [comment]
Okay DATA66,

Do you have short urls enabled? ** = Yes**
Is the script in the root or in a subfolder or subdomain? ** = In the root**
Is https enabled? ** = No**
Do you have any app at all installed? ** = No**
What theme? ** = I tried with both of two (bootstrap and neutron**
Any changes to the theme? ** = No, fresh install......**
Any ads enabled or added to the site? ** = No**

**Comment by Data66PF** [comment]
This is also important though that I had asked:

Can you please test at our demo to see if you can reproduce it there? http://v4.phpfox.com 
If you can reproduce it at the demo - what browser, os? Is it desktop or mobile?

**Comment by perayknox** [comment]
@Data66PF you already tested it on your demo. and it's not a browser problem. anyway. you know.
