### ISSUE TITLE
Username tag in Comments is showing profile-number rather than username.

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#894]
On live demo, per client post in the phpFox forum, if we tag someone in a comment it will show the profile-number rather than username. Note that tagging is working fine in a status post itself. It is only when doing the @ username tag in a comment that it is messing up.
https://v4.phpfox.com/profile-1766/?status-id=240
![tag comment](https://cloud.githubusercontent.com/assets/6908282/12064415/b3735c50-af90-11e5-9cd4-e829299d91c7.jpg)

**Comment by AnthonyKing** [comment]
i saw an issue like this one time, i think you can fix this issue by enabling the username on registration.

**Comment by Data66PF** [comment]
Thanks for the tip but we need it to be consistent. It works in status share and should work in comments for those that want more secure sites. Having username on registration can make the site a bit less secure (from what I was told by a security expert).

**Comment by robert9592** [comment]
Fixed in 4.2.0
The tag will show user full name instead of username.
