### ISSUE TITLE
Status Share What's Up Disappears on Low Resolution

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#895]
This could be related to bug #890 but in case that fix didn't fix this issue too, I'm posting this for the client. 
Posted by a client in the forum. He has no what's up status share input area on his themes (neutron and any based on neutron).
1024*768 resolution
See image in bug #890 and note that the What's up input is missing and should be right above the share. If this issue is already resolved with the fix for the missing logout, please feel free to close it.

**Comment by ajaymenonv** [comment]
I will await for this fix

**Comment by robert9592** [comment]
resolved with the fix for the bug #890
