### ISSUE TITLE
module.category.article format not working for new user redirect.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#896]
Regarding 
New user redirect replaced slashes for dots in url #809
I know this issue was closed, but I need to verify the test procedure used.

I AM able to redirect successfully to page set as follows (over https://)
blog.5.newyears
in the "URL Redirect After Login" setting area.

What still does not redirect is when I set the same thing in the
"Redirect After SignUp" setting just below the one above in user settings (first time redirect for new users).

Can developer (Neil) verify that he used the second one, "Redirect after Signup" for his test, and not the "URL Redirect after Login" one?  For the second one, a new user needs to be created first and then used to log on for the first time to see if the page successfully redirects per your settings.  Is that how the test was done?

Can he also verify that he intentionally left the first one blank before running the test because otherwise how do you know that the article you redirect to (assuming its the same one) was made by the first setting or the second one if they are both set?

Thanks.

**Comment by Data66PF** [comment]
@neil96 please verify. I'll note that I tested non https redirect on sign up and it worked but as my xampp is being a snot, I can't get https to work to test it with that.

**Comment by neil96** [comment]
I tested both with http and https,  "Redirect after Signup" and "URL Redirect after Login".
But I will try again.

**Comment by Gatsby-PF** [comment]
Thanks Donna and neil96,
URL "Redirect after Login" is fine. Please ensure "URL Redirect after Login" is empty when testing "Redirect after Signup" using a new user that never signed in yet. That is what I am doing when this issue occurs.

**Comment by Data66PF** [comment]
that is how I did my tests but will let Neil and the rest of the testers try with https as that is what your issue is posted for. I just wanted to make sure there wasn't an http issue.

**Comment by neil96** [comment]
I setup a new serapate https site for this issue, but I can't reproduce it again. Could you double check your settings or your server config again?

**Comment by Gatsby-PF** [comment]
Thanks for testing.
