### ISSUE TITLE
Dislike are settings accessible

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#898]
The feature "Dislike" was removed as it caused instability before and was meant to be added back as an app by third party developers (for the few clients that use it). 

admincp/setting/edit/?module-id=like#allow_dislike

We need to remove access to the setting as Dislike doesn't work and isn't supported as Ray has said a few times. (unless we add the feature back and fix the feed instability it caused before)

**Comment by robert9592** [comment]
Fixed in 4.2.0
