### ISSUE TITLE
Bootstrap theme . top menu while viewing a member profile on mobile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#899]
Using latest phpfox  on Iphone 6 with chrome
When we are viewing a member profile and  scroll down the page   top menu buttons are overlapping.
It is only when we are viewing someone else profile. not our own.

![image](https://cloud.githubusercontent.com/assets/406030/12086645/63ec3dc0-b2cc-11e5-8dc5-81803bcef5dc.png)

**Comment by Data66PF** [comment]
Do you get the same issue at our live demo http://v4.phpfox.com ?

**Comment by Data66PF** [comment]
Unable to reproduce the issue at our demo using a test user with friends and viewing the profile but I'm testing on iPhone 5C

**Comment by aakash83** [comment]
but i can reproduce it on demo site using iphone 6 with chrome

**Comment by aakash83** [comment]
![image](https://cloud.githubusercontent.com/assets/406030/12108728/2bb141bc-b37b-11e5-993d-85ae9579d653.png)

**Comment by neil96** [comment]
I can reproduce this issue with normal account.
