### ISSUE TITLE
Nginx & Apache rewrite fail.

### ISSUE THREAD

**Issue by cuteemo** [moxi9/phpfox#900]
I cant find the issue.

I Upload the pictures.
![jquery](https://cloud.githubusercontent.com/assets/5604827/12087396/d7ae1f70-b2d2-11e5-9b6f-4a46c2b81ba6.PNG)
![plesk](https://cloud.githubusercontent.com/assets/5604827/12087412/eb926de8-b2d2-11e5-9030-bd620c51f53f.PNG)

**Comment by Data66PF** [comment]
This is not a bug but a server or user issue. For questions about server set up or other issues please use our help community at http://community.phpfox.com for licensed clients.

**Comment by cuteemo** [comment]
okay, thanks
