### ISSUE TITLE
Comparison Save Button Not Labelled

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#901]
V4.1.2 in the admincp/subscribe/compare/ when making comparisons for subscriptions, the save button is just a red block. It doesn't say it's a Save button. This is non-intuitive for the clients as Red normally is a color for No/Stop and not a Go associated sort of color. Please add the Save phrase to the button. 

Please see V3 screenshot Vs V4 screenshot.

V4:
![v4 compare save](https://cloud.githubusercontent.com/assets/6908282/12091892/e46d2fc2-b2c7-11e5-827f-24560eae6ab8.png)

V3:
![v3 compare save](https://cloud.githubusercontent.com/assets/6908282/12091896/ebd1991a-b2c7-11e5-8fb9-e53942357ed9.png)

**Comment by robert9592** [comment]
Fixed in v4.2.0
