### ISSUE TITLE
Inline Javascript widgets in blocks not displaying.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#902]
Javascript widgets in custom html blocks are not displaying regardless of how the blocks get set up. Some aspects of the widgets are working, i.e. they attempt to make connections to the site, and the browser can identify content as secure or unsecure, but nothing displays even when browser mixed content protection is off and caches are cleared.

What is the intent of these blocks, are they not to allow users to customize with widgets, ad codes (not necessarily from Google)?

Here is the source for widget I tested (US based AccuWeather) if you want to try it.
http://www.accuweather.com/en/free-weather-widgets/current

**Comment by Data66PF** [comment]
I cannot reproduce this as shown at the PF community thread. I have google ads and I have this widget displaying fine.

![scripttechs test site](https://cloud.githubusercontent.com/assets/6908282/12099522/164a98f2-b2f7-11e5-8d78-12ca20ccc9a6.png)

**Comment by Gatsby-PF** [comment]
So what were your block setup parameters?
What browser did you use to test?
Did you just paste the widget code as is?

Mine was set to sitewide,

**Comment by Data66PF** [comment]
Chrome and firefox on win 10
default block settings for html block
pasted the code as is
core.index-member but will try sitewide.

**Comment by Data66PF** [comment]
Just tested sitewide with bootstrap theme this time, firefox browser. no issues seen. I can grab a short video if necessary.

**Comment by Data66PF** [comment]
I'll try this more on my live dev site tomorrow. Getting a bit late now to try on it as I don't leave these sort of things running on my test sites (on live servers)

**Comment by Gatsby-PF** [comment]
Thanks for answering this. At this point, I will be attempting to identify what difference exists between yours and mine on this. It looks good on your side.

**Comment by Data66PF** [comment]
The image was from a linux based nginx server. not sure what else you might need to test. I also tried on my winblows localhost but had issues with google not liking localhost so went back to live and google seems to work too but I've disabled them both for now. Will help test more tomorrow. :)

**Comment by Gatsby-PF** [comment]
Accuweather was http only and did not play well with Firefox on https only site even with the security bypassed. I found an https widget and it worked. I cover it more in https://community.phpfox.com/forum/thread/53693/important-issues-in-ad-model-in-phpfox-v4/.

**Comment by Data66PF** [comment]
That widget is more complex than a simple google ad, or the weather one, for example. It most likely requires being put in as an app and using the javascript assets file. However, I'm not great with js so will as @neil96 to have a look or have someone have a look please.

**Comment by neil96** [comment]
This is not a bug.
Because your site is using https, but external js you want to load use http. Browser prevents external http js for security.
Please find another widget or change your site to http.
