### ISSUE TITLE
AdminCP Responsiveness Issues

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#903]
The Administration Control Panel has some responsiveness issues on desktop and mobile devices.

Like this issue in Settings >> Countries >> [Country] Translate:

http://SITE.com/dev/index.php/admincp/core/country/

![Image of an Issue in Admin CP](https://community.phpfox.com/file/attachment/2016/01/111d6820fd1aff7bc3d775e041fb1efa.png)

**Comment by Data66PF** [comment]
Thanks for your report. When posting issues, would you please state the screen resolution if using desktop, the os and browser? If using mobile, please state the device, os version and browser. Thanks!

**Comment by Data66PF** [comment]
I can reproduce this on my macbook pro using chrome browser. I have 4 language packs installed. When I click to Translate a country, it has the popup shown and the box for the other packs is outside the popup as shown. 13 inch monitor on this macbook pro.

**Comment by SpaniNet** [comment]
I am using PHP Fox v4.1.2 and tested it in:

- Desktop
- Screen resolution: 1366 X 768
- OS: Windows 10, Ubuntu 15.10 and Linux Mint 17.3 Rosa
- Browser: Firefox 43.0.2, Vivaldi 1.0.344.37 (Beta 2), Iceweasel 38.2.1

**Comment by neil96** [comment]
Fixed on V4.2.0

**Comment by SpaniNet** [comment]
👍
