### ISSUE TITLE
Featured and online users page issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#904]
The pages not working:

/user/browse/?view=featured

/user/browse/?view=online

**Comment by SpaniNet** [comment]
Me neither.

When I access one of this pages only appear the featured members:

##### /user/browse/?view=featured
##### /user/browse/?view=online

**Comment by Data66PF** [comment]
As there is no filter now to show featured and online, this would be a feature request to add those sections to view. We are not looking at feature requests yet but please post those at the community in the feature request system for now.

**Comment by Ylmzef** [comment]
/user/browse/?view=featured this link showing under Featured Block on users page.

**Comment by Data66PF** [comment]
It's not showing under mine. Can you provide a screen shot?

**Comment by Ylmzef** [comment]
![h8olbui3bzomaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/8562514/12184296/aa4d2a02-b594-11e5-9bf4-e0b8843ba8b9.png)

**Comment by Data66PF** [comment]
Confirmed when there are enough featured users to see the View All link.

**Comment by neil96** [comment]
Fixed on V4.2.0
