### ISSUE TITLE
Can't post after warning message on forms

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#905]
Add a attachment on forum topic than click on send button after notice "Provide a reply."
The button can't clickable.

**Comment by Data66PF** [comment]
confirmed 4.1.2. tested on chrome/win 10

1. go to a thread and click reply
2. only try to attach something (don't put any text in the reply box)
3. Hit submit
4. you'll see a warning to provide a reply. click to close that and try to add text in the reply box but you can't click to submit it as it's a red "no" symbol thing and the submit is grayed out.

**Comment by robert9592** [comment]
Fixed in v4.2.0
