### ISSUE TITLE
New Video Module in 4.2

### ISSUE THREAD

**Issue by rodgerholl** [moxi9/phpfox#906]
I read the post about video module coming in 4.2.  
Hope this includes video upload.   Users love to upload photos and videos..  They hate to upload to a different service,  then link to them.

I would like to comment about my desired functionality in video module.   I have modified the v3 video module to run in v4 and to use Vimeo as the video hosting platform.
User uploads video,  Server accepts video,  transfers it to Vimeo ,  Vimeo handles all the encoding , thumbnails player etc...  the Video module then just converts the video records to look like it was a  shared video (ie a pasted URL from the old V3 module).

Just hoping that the new video module will get close to functionality.

**Comment by Data66PF** [comment]
Please don't ask questions in github as this is only for bugs. Please ask at the community https://community.phpfox.com
