### ISSUE TITLE
Phrases with spelling errors

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#907]
I've found phrases with spelling errors. These are some:

##### facebook.this_method_has_been_depreciated_since_v2_dot0_dot7_dot

depreciated >> deprecated

##### custom.arelation_does_not_have_relation_data_id_or_with_user_id

aRelation >> a Relation

##### language.invalid_language

Invalid language ID#. >> Invalid language ID #.  or  Invalid language #ID.

**Comment by Data66PF** [comment]
confirmed 4.1.2

**Comment by neil96** [comment]
Fixed on V4.2.0

**Comment by SpaniNet** [comment]
👍

**Comment by Spaninet** [comment]
Another wrong phrase (v4.2.0):

##### page.menu_page_privacygegrre_fad58de7366495db4650cfefac2fcd61

Privacygegrre

**Comment by Spaninet** [comment]
##### custom.a_relation_does_not_have_relation_data_id_or_with_user_id

a Relation does not have relation_data_id or with_user_id

**Comment by neil96** [comment]
**page.menu_page_privacygegrre_fad58de7366495db4650cfefac2fcd61** does not have in default code, it added when you create new page in adminCP.
**custom.a_relation_does_not_have_relation_data_id_or_with_user_id** I updated in V4.2.1

**Comment by Spaninet** [comment]
True, it's a test page I've created.
