### ISSUE TITLE
Sponsor in Feed is Not Showing Sponsor Ad in Feed

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#908]
v4.1.2. Bootstrap and Neutron themes. Setting for user group, testing Sponsor in Feed. 

Set to true for Admin user group for this test. I've tried with all variables to the setting from free sponsor ad to paid and it is not showing in the feed. It shows in the ad sponsorships in admincp so the ad is being made but it is not being shown. This used to work only for photos and it would show them at the top of the feed while the sponsor ad was active.
![sponsor feed](https://cloud.githubusercontent.com/assets/6908282/12141974/4ea55376-b442-11e5-9962-753d32033816.png)

These are the settings, found in user group Feed settings:
feed.feed_sponsor_price
feed.can_sponsor_feed  this is for allowing free sponsor ads (handy for admin user to test)
feed.auto_publish_sponsored_item
feed.can_purchase_sponsor this setting is only for the paid setting and the phrase is a bit confusing.

Anyway, set the setting to allow you to test this. I suggest to set it for the free sponsorship as the pay with points has a bug.
Go to front end and find a photo you've added to the site.
Click the Edit pencil icon and choose sponsor in feed
Check the main feed and the photo should now be showing at the top of it but it is not. You can try with other user groups to see if it shows up and it still doesn't.
You can see the ad is active here, admincp/ad/sponsor/

**Comment by neil96** [comment]
Fixed on V4.2.0
