### ISSUE TITLE
Purchase with Points Not Showing Completed Purchase

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#909]
Chrome and Safari test. Macbook Pro El Capitan v10.11.2 Neutron theme tested first.
Set up the activity point conversion rate and enable Purchase with Activity Points admincp/setting/edit/?module-id=user
In User Group Settings under the User settings, enable Can purchase with activity points?
Make sure this user you will test with has enough points to test.
Try to purchase a sponsor in feed ad, a normal ad, a marketplace item, anything that you can purchase with points.
You will see that the purchase does not "complete" and it appears that nothing happens. This used to progress to the completed stage at one time.
If you go check your invoices, site.com/marketplace/invoice/   (as the user you just tested for the purchase) you will see it marked as paid so the process worked but it just didn't show the user that it worked.

**Comment by robert9592** [comment]
Resolved for 4.2.0
