### ISSUE TITLE
Sponsored Photos Do Not Show

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#910]
Chrome. Macbook Pro El Capitan v10.11.2 Neutron and Bootstrap themes tested.
Enable the User Group setting to allow the user to sponsor photos. My test was with it being a free sponsorship.
1. Go front end and sponsor one of your photos.
2. Go to the main photo.index page and see nothing changed.
3. Look in AdminCP in Blocks and note that the sponsor photo block is not even there so we need to add it manually but we need to fix this so that the block is again in photo.index controller as it was before and clients shouldn't have to add it.
4. Once you add the sponsor block to photo.index, check with bootstrap and it's fine as the block shows.
5. Test with Neutron and the block does not show so we need a solution for Neutron theme.

Requested fix is two things:
1. Make the sponsor block for photo.index 
2. Make the sponsor block show for neutron

Request tests for sponsor items to ensure we are showing them for other modules that allow sponsoring.

**Comment by neil96** [comment]
Fixed on 4.2.1
