### ISSUE TITLE
Hid the menu in home page  from guest 

### ISSUE THREAD

**Issue by rn2020** [moxi9/phpfox#911]
we can hid the menu in the home page from not register user 
make this option in menu
1- for hid all menu from the guest 
 2-  for each menu to chose by group 
example 

like if you have three groups A B C 
than i can chose from menu when i edit each link to chose like  blog to be show for B and event for c and like that 

this important for phpfox to make it great and easy for admin to what he want ,   if yo can make for each group than make one option to hide the menu for guest

**Comment by Data66PF** [comment]
The issue tracker is not for feature requests and is only for bugs that keep the script from working as it is designed to work. Please post feature requests in the feature request section at the community. https://community.phpfox.com . Thank you.

**Comment by rn2020** [comment]
oh sorry , ok i will , as i did it here as it is important and it is like issues , as it is good for phpfox , ok from now i will do there

**Comment by Data66PF** [comment]
Reopening to look at as we can't manage our menus per another client too.

**Comment by neil96** [comment]
Fixed on V4.3.0
