### ISSUE TITLE
Can't Edit Event Country

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#912]
Per a thread at the community, we cannot edit events for the country. Even creating a new event, I cannot chose anything other than United States.

If I change my country in edit profile to something else, such as United Kingdom, then all of the events I made will change automatically to that country. This is not ideal as some clients have worldwide events they would do. The event should allow a user selection for the country rather than automatically having one that is not able to change. I've never seen this issue before.

On another test, have a user who has no country selected in their profile settings. Create an event and choose any country you want, other than United States. 
Look at this event and it shows United States though you chose Angola or whatever you chose.

This should allow country to be blank for those that do online events; it should allow a user to select any country for the event other than their profile setting for country; it should not pull any info from the user's profile entry for country as it is messing it up.

**Comment by wlongdonstudio** [comment]
I've been having this issue for the longer

**Comment by robert9592** [comment]
Fixed in v4.2.0
