### ISSUE TITLE
Issues in the Feed when post link from out side 

### ISSUE THREAD

**Issue by rn2020** [moxi9/phpfox#913]
there is issues in the last verstion 4.1.2 as when somone post link from out side network in the feed than it show the link the preview the site but there is space in the feed with big empaty , so feed show by high space 
![feed issues](https://cloud.githubusercontent.com/assets/16052496/12143470/e06f9e2a-b491-11e5-984e-b5aa27945621.png)
![feed issues 2](https://cloud.githubusercontent.com/assets/16052496/12143482/f79a921c-b491-11e5-92c6-5bf5149a3f45.png)

**Comment by Data66PF** [comment]
Not sure what we can do here as yahoo.com has a normal image for their site logo but youtube has a huge one. This looks to be an issue with the image grabbed from the shared site. Perhaps we can add a max size?

**Comment by robert9592** [comment]
Fixed in v4.2.0
