### ISSUE TITLE
View more link issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#916]
View more links not working on news feed.

**Comment by Data66PF** [comment]
Are you testing at our demo? What browser and os?

**Comment by SpaniNet** [comment]
Works good in Demo site and in my Dev. site.

**Comment by Ylmzef** [comment]
Phpfox v4.1.2
Neutron theme
Chrome
Windows 10

**Comment by Data66PF** [comment]
I cannot reproduce an issue either, on win 10 and chrome. Please check your browser settings. Please test at our demo.

**Comment by Data66PF** [comment]
Please disable any apps you have, clear cache, and test again as we cannot reproduce this on our demo or on my dev site with win 10 and chrome browser. Tested both neutron and bootstrap themes.
