### ISSUE TITLE
Photos do not shift into position properly

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#917]
Per a presales ticket, testing on the demo, when scrolling down, the photos do not shift into position properly. This leaves big gaps sometimes and small gaps that are not professional looking.
Please see these images provided by the ticket request.
![phpfox_photo 1](https://cloud.githubusercontent.com/assets/6908282/12168208/c82115e8-b4fe-11e5-967b-87c16977e003.jpg)
![phpfox_photo 3](https://cloud.githubusercontent.com/assets/6908282/12168211/c92fc10a-b4fe-11e5-929e-f7a525aa3194.jpg)

**Comment by SpaniNet** [comment]
I have seen this bug since v4.1.0.

**Comment by robert9592** [comment]
Fixed in v4.2.0
