### ISSUE TITLE
Bootstrap Theme - Pages Photos 

### ISSUE THREAD

**Issue by Lidercan** [moxi9/phpfox#918]
Pages Photos will not be reduced in Pages Feed  on mobile.

**Comment by SpaniNet** [comment]
Photos in Page's feed are not responsive in Bootstrap and Neutron themes.

**Comment by Data66PF** [comment]
https://v4.phpfox.com/pages/67/ cannot reproduce an issue using iPhone 5c at the demo. I loaded some big images there.

**Comment by SpaniNet** [comment]
See screenshot:

![Screenshot](https://community.phpfox.com/file/attachment/2016/01/88ae92f0a71f4798540732d4b21f82f3_view.png)

**Comment by Data66PF** [comment]
Please ensure testing is being done from a mobile device and not by resizing the browser or with emulators as sometimes emulators are not as reliable as actual devices. Is that image from a mobile device?

**Comment by SpaniNet** [comment]
Sure, these are two screenshots made from a mobile device.

##### OS: Android 5.1
##### Screen Size: 5.0"
##### Screen Resolution: 1280 x 720 pixels
##### Browser: Latest Firefox stable version

**Comment by SpaniNet** [comment]
I still reproduce this issue in other mobile devices.

Please label it as a bug.

**Comment by Spaninet** [comment]
Fixed in v4.2.0
