### ISSUE TITLE
Phrases for previous versions of PHP Fox

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#920]
Not a BUG.

Can you delete all the phrases from deprecated versions of PHP Fox to make translating easy.

Example:

##### feed.method_deprecated_since_2_dot1_dot0beta1

Method deprecated since 2.1.0beta1

**Comment by Data66PF** [comment]
Marked a bug as we need to clean up the script.

**Comment by SpaniNet** [comment]
Sorry. I  closed the BUG accidentally.

**Comment by neil96** [comment]
Fixed in V4.2.0

**Comment by Spaninet** [comment]
The script has not been cleaned.

##### facebook.this_method_has_been_deprecated_since_v2_dot0_dot7_dot

**Comment by neil96** [comment]
**facebook.this_method_has_been_deprecated_since_v2_dot0_dot7_dot** this phrase will clean on V4.2.1
