### ISSUE TITLE
Pages SubCategories Not Showing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#923]
4.1.2 demo, https://v4.phpfox.com/pages/category/1/entertainment/ example is that one. It should show a listing of all of the subcategories for that main category.  Bootstrap and Neutron are missing it.

See V3.8 for a reference:
![subcats pages](https://cloud.githubusercontent.com/assets/6908282/12198055/9e357648-b5da-11e5-852c-674f0007044c.jpg)

**Comment by neil96** [comment]
Fixed on V4.2.0
