### ISSUE TITLE
Profile info page still showing nothing.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#924]
This still issue in v4.1.2

https://github.com/moxi9/phpfox/issues/234
https://github.com/moxi9/phpfox/issues/271
https://github.com/moxi9/phpfox/issues/133

**Comment by Data66PF** [comment]
http://scripttechs.com/article/372/phpfox-v4-profile-info-block-to-show-relationship-and-other-info/ log in to view that tutorial but it still works if you want to do that. I'll leave this open so we can enable that block by default though.

**Comment by Data66PF** [comment]
Marked a bug as the info doesn't show anything even with the info filled in. The tutorial I linked is just to get the default block to show  up again.

**Comment by Ylmzef** [comment]
Still bug in v4.2

**Comment by neil96** [comment]
We didn't mark this issue as fixed. Please wait for next version.

**Comment by Ylmzef** [comment]
@neil96 

@RaymondBencRaymondBenc closed this in b4a2742 on 13 Aug 2015
