### ISSUE TITLE
What's Up Long Key Hang Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#925]
when i long press one key in whats up box.After press for long time then click on share after that whole Application and browser hang.Nothing Working Browser Windows show not Responding
Testing with 4.1.2 Windows 7 OS Mozilla and chrome having same Problem
![news feed updates11111](https://cloud.githubusercontent.com/assets/13433124/12215603/9ecf4208-b6ea-11e5-9e06-30f7a45c7b76.png)

**Comment by Data66PF** [comment]
Does it do that at the demo? It could be a safety or anti-spam measure if it does also do it at the community as no one will post a status of just one letter hit for a long period of time. Try an actual post (actual words)

**Comment by SalmanKhan86** [comment]
where i can check demo
http://demo.phpfox.com/ is not working
It could be a safety or anti-spam measure but it does't hang in middle process.our Application stop working.why its hang

**Comment by Vivian-phpFox** [comment]
You can check on: https://v4.phpfox.com/

**Comment by SalmanKhan86** [comment]
same problem here on https://v4.phpfox.com/.after press long key its hang not allowed me to click no where.show page unresponsive in chrome. 
![v4 status share](https://cloud.githubusercontent.com/assets/13433124/12215966/8b979a88-b6f8-11e5-80cd-893814cdcf34.png)

![page unresponsive](https://cloud.githubusercontent.com/assets/13433124/12215972/b5647caa-b6f8-11e5-9dea-9eb19370883e.png)

**Comment by SalmanKhan86** [comment]
Not Responding Problem in Mozilla Browser 
https://v4.phpfox.com/
![same problem mozilla](https://cloud.githubusercontent.com/assets/13433124/12216020/68a74828-b6fa-11e5-8066-cdbb2f3c5a02.png)

**Comment by robert9592** [comment]
fixed in v4.2.0
