### ISSUE TITLE
Cannot Attach Polls to Forum Thread

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#926]
I searched the issue tracker before posting because I thought I had seen this posted. Please close it if it is a duplicate as I could not find another post.

In 4.1.2 and 4.2.0 have the user group allowed to attach polls to a thread (it is enabled by default but be sure you are using a group that can).

Go make a thread and look for the button to attach a poll and it is not to be found in bootstrap or neutron themes.

Here is an image of where it should be, from v3.8:
![forum poll](https://cloud.githubusercontent.com/assets/6908282/12217277/c291c948-b6c9-11e5-9446-fe2ac9456561.png)

**Comment by neil96** [comment]
Fixed on V4.2.0
