### ISSUE TITLE
Html codes in recent forums block

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#927]
Under sub-forums recent block shows html codes.

![camgbsmcawscae80uwhq3lbawcasecmc9ebyic4qf1swcadxrdsgiu2gbseby4p8dlgmoe9lod1iaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/8562514/12219172/6d45a112-b737-11e5-9d50-14ce1f115ba1.png)

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/212 please see Ray's comments there as we do not support html and so feeds such as the recent posts will show code if images are in them.

**Comment by Ylmzef** [comment]
It's BBCode.

**Comment by Data66PF** [comment]
Yes but the block shows as html as that's how they've always done. Even at the PF forum it is like that. You can see in the other issue that Ray already answered about this. He answered the same thing in a few other bugs. However, he did make that html free app for those that still want to allow it on their sites, complete with the warning about security.
