### ISSUE TITLE
user::featured Block in user.browse doesn't work

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#929]
The block user::featured located in user.browse is not working.

##### http://SITE.com/admincp/block/ >>  user::featured [ACTIVATE]

PHP-Fox v4.1.2

**Comment by Data66PF** [comment]
I cannot reproduce this. It is working for me and for other clients who posted a but for view more. https://github.com/moxi9/phpfox/issues/904 you can see it works in that image

**Comment by SpaniNet** [comment]
Now it's working in fresh installation. Last version.
