### ISSUE TITLE
"New polls on site name daily" Hard coding in polls sharing in facebook

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#930]
When I share a poll in facebook  "New polls on site name daily"  message are appearing in place of "New polls on www.mysitename.com daily".

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/646 staff, please see that reference where this was fixed for quizzes and please do the same for polls.

**Comment by neil96** [comment]
I also fixed this issue (and other relate issue) on #646 .
