### ISSUE TITLE
techie-version

### ISSUE THREAD

**Issue by Chriscxa** [moxi9/phpfox#931]
Techie-version was removed here, but where developers download the "last" version now?

**Comment by Data66PF** [comment]
This is only for bugs and not for questions. Developers download it from their accounts at https://store.phpfox.com/download . You can contact us via our contact form there if you have more questions.

**Comment by Chriscxa** [comment]
Sure. But then you have to update your www.phpfox.com!
 Remove old links and old content for developers (fork repo etc)!

**Comment by Data66PF** [comment]
Things will be updated soon. We've been working on it.
