### ISSUE TITLE
Events don't appear in the events page after upgrading

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#932]
All my events don't appear in events page and my events page after upgrading from v4.1.1 to v4.1.2.

##### /event/?view=my

Can be accessed only with links from posts in the feed or from search page.

![Screenshoot](https://community.phpfox.com/file/attachment/2016/01/05deac8e03f2379c8818b70a383c26ef.png)

**Comment by Data66PF** [comment]
Did you make sure the site is not set to Friends Only Community?
Did you make sure the events are not expired events?

**Comment by Data66PF** [comment]
I can't reproduce this on my upgraded live development site. When I click the sort to view All Time, I can see all of my events.

**Comment by SpaniNet** [comment]
I see them if I sort to view All Time and when I edit them an refresh page.

**Comment by Data66PF** [comment]
If the events are not Upcoming events then you need to click All time as the default only those events that are coming up.
