### ISSUE TITLE
Hashtag + URL in Feed

### ISSUE THREAD

**Issue by EroFacies** [moxi9/phpfox#933]
Hashtag and a URL in the Feed
Hashtag without function

https://v4.phpfox.com/profile-2681/?status-id=414

**Comment by SpaniNet** [comment]
Hashtag link disappears when posted with a link.

Tested in Demo and in My Site.

v4.1.2

**Comment by Data66PF** [comment]
This is how it is designed to work. You cannot post both. Raymond answered this before with more technical explanations as to the reason.

**Comment by EroFacies** [comment]
in all social networks, I can post a #hastag and a URL,
see Twitter or FB. Why is this not possible in phpFox?

**Comment by Data66PF** [comment]
This is how it has always worked due to how it is designed. When we are looking at improvements, perhaps we can look at this at that time.

**Comment by neil96** [comment]
Relate with #821
