### ISSUE TITLE
Banned e-mail & IP address issue 

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#934]
I've banned a user e-mail the user can't login into the site.
But the user group showing still as registered user in admincp search page.

Also same for IP address ban the user group still registered and it's only affects logins not complete site.

**Comment by Data66PF** [comment]
This is how it is designed. You need to go to the user search in AdminCP if you want to ban the user there too as the ban filters are separate from the user bans. This allows you to ban a user for a specified time from the user settings or to set global bans in the ban filters. Also, setting a user as banned in the user settings will not add them to the ban filters. It has always worked this way. I had a feature request in once to change how this works but right now, this is working as it is designed.

**Comment by Ylmzef** [comment]
For e-mail: Why the "Ban User:" option listed when you ban a mail address than?

For IP address: In v3 was it completely site for IP, If you banned a IP address the visitor cannot reach to site and get a only message about IP ban on all pages.

**Comment by Data66PF** [comment]
I use v3.8 on two live sites. The ban is not for the user in the search filters. The ban filters are different. You might be thinking of how cloudflare bans an IP from accessing the server. The phpFox script can't do that as it can only ban it from the site itself. 

The option is there so the user cannot sign up. Same for the IP address. It will ban them from joining the site. 

You can see the v3 ban filter tutorial here that shows how they work, https://store.phpfox.com/kb/article/503/how-to-set-the-ban-filters

To ban a user a little better, also ban them in the user search in admincp. Click to the left of the user name at the drop down selector and select to ban them that way. 

So, there are two ways to ban. Ban them from registering here at this url, admincp/ban  or ban them from logging in here at this url, admincp/user/browse/ . One way (admincp/ban) will keep them from registering again if you deleted them (to get rid of their content, such as spammers). The other way (admincp/user/browse) is mainly to ban a user that has broken your rules and you just want to ban for a while and then unban later perhaps.
