### ISSUE TITLE
User edit page profile picture issue in admincp

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#935]
![byrkaabagqiecbagaabagqiecbagaabagqiecawnoaaatwvvxmgqiaaaqiecbagqiaaaqiecbagqiaaaqiegi8gqgr8fiuqaaecbagqiecaaaecbagqiecaaaecbagqidcewp8hqnbqcv7fvpgaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/8562514/12245122/24fa7dda-b8a7-11e5-83fd-fe7896b496f3.png)

**Comment by Data66PF** [comment]
I can only reproduce this for users without an image. Will mark a bug.

**Comment by robert9592** [comment]
Fixed in 4.2.0
