### ISSUE TITLE
Event : Displaying members who changed their RSVP

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#937]
Latest Phpfox with bootstrap Theme.
Don't know this is a bug or Not .

If a user joins an event and  his name starts appearing under attending list  then after if he changes his mind and  select " Not attending " .  Then we  get a new list having names of all those members who first committed to join and later changed their mind. In My opinion we don't need to display names of those who changed their option .

**Comment by Data66PF** [comment]
I believe this is how it works on fb. Anyway, this is how it is designed and not a bug. We can look at improvements based on client suggestions at a later time.
