### ISSUE TITLE
Event: Changing RSVP needs a page refresh

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#938]
Latest Phpfox with bootstrap Theme.  
When we change event's RSVP option it don't update instantly and we need to refresh page to  view updated status.

**Comment by Data66PF** [comment]
I can confirm on v4.2 using safari browser on a mac. I am not sure if this is as designed so will mark a bug for our core developers to determine.

**Comment by robert9592** [comment]
Fixed in v4.2.1
