### ISSUE TITLE
issue with notifications about long named items on mobile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#939]
latest phpfox with bootstrap theme on Iphone 6 using chrome

When we receive a notification about a long named item (in this case a photo) .it is not displayed properly.
![image](https://cloud.githubusercontent.com/assets/406030/12290221/cbf3ee66-b9e0-11e5-921c-b54509f1ad20.png)

**Comment by robert9592** [comment]
Fixed in v4.2.0
