### ISSUE TITLE
Birthday Settings Missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#940]
We need to bring back (into view) the birthday settings for:

Enable Birthday Notices
Show Empty Birthdays
How Many Days in Advance to Check for Birthdays

as these show in the Upcoming Events block but we can't control it now and we have clients unable to see the birthdays on their sites but they can't control the settings. If using the search tool for settings, all three of those show up but when clicked, they don't show for use.

We also need the Cache setting for birthdays as that controls how this is cached. Please see in V3 if you are not sure where to find these as I don't have access to my database right now to find it. :)

**Comment by robert9592** [comment]
Fixed in v4.2.1
