### ISSUE TITLE
Profile Designer Setting Enabled but Designer Missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#941]
Per a client request. The profile designer appears to have been removed but the setting is available. 
![design profile](https://cloud.githubusercontent.com/assets/6908282/12300240/8e787946-b9e8-11e5-9bbc-0c98ca99e2b2.png)

Location (in v3) is at http://site.com/username/designer/  (I replaced the site name and username in that link, it is just for reference as to where it was found). It also had a link in menus to click Customize Profile and on the profile there was a button Design Profile.

A few clients (two so far that I know of) are asking for this feature to be brought back. I don't know if that is possible, it is not something I would allow on any sites due to the possibility of bad code (hacks) to be entered (as happened on one of my sites before). 

We need to determine if we will remove the setting or if we will put the feature back. If we choose to put it back, we need to research how to do that safely without getting client's hacked. (perhaps a more basic designer that does not allow adding of code). 

I prefer at this time to remove the setting and research more later as to how to safely allow profile designing.

**Comment by robert9592** [comment]
Fixed in v4.2.1
