### ISSUE TITLE
Invite expirations

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#944]
Currently, invites seem to be open ended. There are no visible provisions for time limiting an invite in terms of number of days to expiry. There is related setting (invite expiration) in the database. In admincp, there is only an activation points per invite setting. 

This is a security concern because with no automatic expiration after a set time, the risk of any email account compromise later on could result in successful signup by un-inteded imposters. Email hacks, especially Gmail are commonplace so the need for an expiration is justified. I am visualizing that on expiration, the system should automatically send an expiration notice to the non-responding invitee. What is the current developer consensus regarding this features having being apparently disabled?

**Comment by Data66PF** [comment]
Due to possible security issues for websites we should consider putting the setting back.

**Comment by robert9592** [comment]
Fixed in v4.2.1

**Comment by Gatsby-PF** [comment]
Is there a time limit set-ability on this feature?

**Comment by Gatsby-PF** [comment]
I do not see any time to expiration settings associated with this bugfix. So how is invite expiration supposed to work now?

**Comment by Gatsby-PF** [comment]
Never mind I found it. disregard this.
