### ISSUE TITLE
iPhone Smileys Show Added to Post but Change to Symbols

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#945]
Putting this as a bug because it will cause confusion for users. v4.1.2 and v4.2.0. iPhone 5c, iPad and Macbook tested. Safari browser.

Using an iPhone, post a thread or thread reply. (I'm sure this issue is for any module though) 
Click your iPhone smiley button and insert one of the smileys. It will show in the thread just fine.
Visit from a computer and it will show as a symbol ߘ as seen here, https://v4.phpfox.com/forum/thread/26/iphone/?view=60
However, viewed by the iPhone and it shows fine.

We need a way to show an error "input not allowed" or some solution to make them work if we are going to allow those.

**Comment by Ylmzef** [comment]
It's showing fine for me with chrome.

![download 1](https://cloud.githubusercontent.com/assets/8562514/12373880/46c17d06-bc8a-11e5-8f2c-a93d643c001e.png)

**Comment by RaymondBenc** [comment]
Are these the built-in smillies that the iPhone provides?

**Comment by Data66PF** [comment]
Yes. If not allowed, it should give an error or something perhaps?

**Comment by RaymondBenc** [comment]
Fixed in 4.3.0.

**Comment by neil96** [comment]
This is common problem. I tested on facebook and the same problem.
![screen shot 2016-06-02 at 10 25 22](https://cloud.githubusercontent.com/assets/15936115/15739512/97025c56-28da-11e6-9b48-4abebed59990.png)
More information: https://support.apple.com/en-us/HT203261
