### ISSUE TITLE
User group permissions for blocks missing

### ISSUE THREAD

**Issue by phpfoxmetro** [moxi9/phpfox#947]
There is no way to manage block permissions in v4.  To recreate, 

Part A:
1.  Create a new block
2.  Select Sitewide
3.  Try and restrict "Guest" usergroup, or any other group, from seeing the block.

Part B:
There is no way to manage permissions on blocks that already exist out of the "box".

"we can't manage blocks without a way to manage blocks" - credits ScriptTechs.Com

**Comment by Data66PF** [comment]
Marking a bug so we can look at this process as we need to be able to manage blocks we are using. Clients cannot code app blocks or edit apps they are buying. Making an admin created block, we are stuck without a way to select a user group. This is very important for site management. 
For a temporary solution to this, clients can log in and see this tutorial, http://scripttechs.com/article/377/hide-blocks-from-guests-phpfox-v4/ but it is only to hide a block from guests. So it won't allow block management if you want to hide from specific user groups.

Staff - Please see v3 for how blocks are able to be managed by user group and please put back a method for clients to be able to manage blocks.

**Comment by phpfoxmetro** [comment]
For a more permanent solution, see...  http://scripttechs.com/forum/thread/3029/v4-blocks-question/page_1/

**Comment by robert9592** [comment]
Fixed in v4.2.1
