### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#948]
When coding pages in admincp once saved the code does not word wrap but stretches on a long single line. this makes it difficult to do fixes and additions.

**Comment by Gatsby-PF** [comment]
It does the same thing in a message thread too, blowing way past the right limit of the text area. Just hold one letter down to repeat in a long line to test.

**Comment by Spaninet** [comment]
This error is also in v4.2.0.

**Comment by neil96** [comment]
Fixed on V4.2.1
