### ISSUE TITLE
[Browse Members] Toggles Needed + More Options?

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#95]
As shown, the two 'blocks' are shown on the 'browse members' page. There's no way that I can find to disable these two if we want. I mainly would like to disable the Recommended Users one.

Would it also be possible to add a block to this page that by default shows ALL the members where you can set the number shown on the page and by default sorted in some way? Would then have a 'next page' type of deal to keep browsing. Perhaps alphabetically sorted by default?

![image](https://cloud.githubusercontent.com/assets/6254165/8686128/85c31c42-2a51-11e5-83e0-49087befc61e.png)

**Comment by Data66PF** [comment]
I can't find the friend's settings now. In there should be the setting to disable for "friend suggestions". I also don't see a block for recommended users.

It would be nice if All members showed, like before, but I know this is a huge burden on servers and caused issues for shared sites or those on low end servers. I guess a toggle for those that want to use this heavy feature would be ok.

As for now, go to the right and at the bottom for the search, click it without setting any search criteria and it should bring up the members.

**Comment by Data66PF** [comment]
Confirmed as a bug as we don't have a way to disable the recommended users now. However, checking here, admincp/setting/edit/?module-id=friend and friend suggestions is disabled on my test site so that block shouldn't show anyway.

**Comment by RaymondBenc** [comment]
The fix I sadly have to say is that we needed to remove the editing of that setting page as many of the settings provided there are not used and defaulted to specific values for v4. The **friend suggestion** is not a setting related to these blocks.

An app would have to be created to hide these specific blocks, which could either be done with Javascript or CSS.

**Comment by lueung** [comment]
Was this issue ever resolved? or will 4.3 fix this? I see in v4.2.2, it keeps adding to people to the recommended users and no way to disable it.
