### ISSUE TITLE
Songs in Album dont play well in mobile devices

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#950]
When I play a song in an album it sounds bad in mobile devices. In desktop it sounds well.

Tested in Demo.

**Comment by Data66PF** [comment]
I cannot reproduce this with an iPhone 5C on our 4.2 test site. What mobile device are you using? Please give specifics of device, browser and os.

**Comment by SpaniNet** [comment]
Fixed in v4.2.0
