### ISSUE TITLE
Only shows on reload

### ISSUE THREAD

**Issue by sandeeprvarma** [moxi9/phpfox#951]
Facing similar issue as in issue-550 with v4.1.2. Added js code in a script tag on a page which require a page reload to create dynamic iframe.

**Comment by Data66PF** [comment]
Isn't this the same issue as #949 ?

**Comment by sandeeprvarma** [comment]
I am facing this issue after adding code to new pages i have created from admin panel. It seems like page is loaded using ajax and it does not render code written in <script></script> for the first time. Is there any way we can fix this?

**Comment by Data66PF** [comment]
If this is the same as the issue posted for google ad then this is a duplicate and can be closed so our developers don't take time looking at the same thing. Is it the same issue?

**Comment by sandeeprvarma** [comment]
I am not using Google ad code but it looks similar issue.

**Comment by sandeeprvarma** [comment]
It is fixed? It's very urgent.

**Comment by neil96** [comment]
Could you show detail example? 
Some Js functions only work when reload page, but we are using ajax mode, so please make sure your js code also work in ajax mode.

**Comment by sandeeprvarma** [comment]
<div id="embed_container"></div>
<script src="//myurl.com/js.php" type="text/javascript"></script><script>var iframeObj = new Object();iframeObj.module="embed";iframeObj.style="min-height:350px;min-width:300px;";iframeObj.src="//myurl.com/pop.php"; if(typeof(EmbedIframe)=="function")EmbedIframe(iframeObj);
</script>

In the above code EmbedIframe function generates an iframe and adds data to it.

**Comment by neil96** [comment]
I can't reproduce with your script you gave, Could you give me real above js url?

**Comment by sandeeprvarma** [comment]
Please check on my site http://dev1.browwwse.com/phpfox/
Please go to Explorer->my to see the issue. 
Username: testuser@cometchat.com
pass: user123

**Comment by sandeeprvarma** [comment]
Can you please provide a fix for this ASAP?

**Comment by neil96** [comment]
I checked on your demo, this js file *"10005.cometondemand.net/js.php?type=core&name=embedcode"* use some events "onload", this event only run when page reload. This is not a core bug.
Please fix this issue on your side. You can use this plugin **get_master_files** to make your js file alway load.
