### ISSUE TITLE
Flow 

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#952]
When site is upgraded from V3 to V4 the file structure is wrong as it retains file structure as
file
modules
include
PH base/file
Ph site
PH src
static
This means that flowplayer will look in /file directory and not PH Base/file for any new music uploads. I fixed my issue by merging to File directories into one at PH Base/file.

**Comment by neil96** [comment]
I can't reproduce this issue with default music player. After upgrade from V3 to V4, we need delete folder    *include* and *module*, merge folder *file* to *PF.Base/file*, folder *static* to *PF.Base/static*. This action not require, but some third-party may can't load old data.

**Comment by one44** [comment]
This was an issue on my site but fixed as per merging two file directories.
