### ISSUE TITLE
Privacy Issue - Upcoming Birthday Shows Age

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#953]
V4.2 staging server. Privacy setting is to just show month and day. Works fine on the profile but the upcoming birthday block is showing the age. This was fixed in v3 at one time. This is important as some of us don't want that showing so we then have to change the year for now. It is expected, and seems logical, that if someone hides their year in the privacy settings then that means they don't want it public knowledge. :) 
![birthday age](https://cloud.githubusercontent.com/assets/6908282/12394042/734f7a4c-bdc7-11e5-8322-4643ae3c4738.png)
![birthday privacy](https://cloud.githubusercontent.com/assets/6908282/12394043/74a843ba-bdc7-11e5-9e97-b6967a7fb980.png)

**Comment by robert9592** [comment]
FIxed in v4.2.1
