### ISSUE TITLE
Egift Button Does Not Show if Birthday is not Set

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#954]
v4.2.0 RC. Staging Server. Added Egifts to a category for all year egifts. Tested on a few profiles and it worked fine except if the user has not added a birthday to their profile. This is not working right as it should not rely on whether the user has a birthday added since these gifts are set to be all year long.
Please see the image. Top is with a birthday and bottom is without.
![gift w bd](https://cloud.githubusercontent.com/assets/6908282/12395468/cc360ab0-bdcf-11e5-8b21-8c61910c9de8.png)
![gift no bd](https://cloud.githubusercontent.com/assets/6908282/12395471/d0767cfe-bdcf-11e5-866c-cb9065e4a6c1.png)

**Comment by robert9592** [comment]
Fixed in v4.2.1
