### ISSUE TITLE
Notification Links for Comments on Profile go to 500 Internal Server Error

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#956]
Staging server.
Have a comment made on your wall by another user. See the notification in the flag. Click the flag and see the notification and click that.

https://stage.phpfox.com/profile-3/?comment-id=13

It goes to internal server error.

**Comment by SpaniNet** [comment]
I get a blank page.

**Comment by Vivian-phpFox** [comment]
This issue happen when debug mode enabled, same as issue #971

**Comment by neil96** [comment]
@Vivian-phpFox Yes, but we have to fix this issue.

**Comment by neil96** [comment]
Fixed on 4.1.2
