### ISSUE TITLE
Video App Bucket Does not Change

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#957]
I am not clear on the client's issue so will quote it.
https://community.phpfox.com/forum/thread/53832/importnat-for-4-2-for-video-app-it-should-be-not-zencoder-com/

the issues is the Provide the S3, CloudFront or Custom URL not change even we put our S3 link it keep phpfox bucket
https://s3.amazonaws.com/phpfox-test-video/
it not change to our
they missed to let the custome buckt change as we change our buckt but it keep phpfox bucke
see
we upload our videos but it link to the link blow
they missed to let the custome buckt change as we change our buckt but it keep phpfox bucke
see
we upload our videos but it link to the link blow
https://s3.amazonaws.com/phpfox-test-video/16/01/1.
i want to my s3 and i found the videos there but the problem that the video in site not read the right link it go to phpfox link

**Comment by rn2020** [comment]
also there is another one reported 
I already replace my Custom URL Amazon but my video still point to this url
https://s3.amazonaws.com/phpfox-test-video/16/01/1...



https://community.phpfox.com/forum/thread/53845/video-bug-for-4-2/

**Comment by RaymondBenc** [comment]
Fixed in 4.2.0 stable
