### ISSUE TITLE
[STAGE] Shared videos don't occupy all space available

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#958]
Shared videos in Stage site don't occupy all space available.

Tested in desktop.

![Screenshot](https://stage.phpfox.com/file/pic/photo/2016/01/ecd455241562ae1d531d3abff0337b79_1024.png)

**Comment by Data66PF** [comment]
Please add the feature request at the community section for feature requests.

**Comment by Spaninet** [comment]
This is not a feature request.

Shared videos should adapt (responsive) to space available.
