### ISSUE TITLE
[v4.2.0] Videos URL

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#959]
The URL of videos page is https://stage.phpfox.com/v/ instead of https://stage.phpfox.com/videos in v4.2.0.

![Screenshot](https://stage.phpfox.com/file/pic/photo/2016/01/f31a093c99f5f1cb4e731936c7494010_1024.png)

**Comment by Data66PF** [comment]
If we change this, we need to let clients that are using the videofeed app know to delete it as that uses /videos

**Comment by SpeakLife** [comment]
That is a good idea Donna because I had to delete my other video feed that was using /videos. So I'm now using the /v.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#15
