### ISSUE TITLE
[v4.2.0] Video tab is not in the profile feed

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#961]
Video tab don't appear in profiles.

![Screenshot](https://stage.phpfox.com/file/pic/photo/2016/01/bfb917e18fd1f247310d814b325715bb_1024.png)

**Comment by Vivian-phpFox** [comment]
Video tab only show up on the sites dashboard and not pages/profiles

**Comment by SpaniNet** [comment]
OK. Video tab should be added to profiles.

**Comment by Spaninet** [comment]
@Data66PF Please label this issue as enhancement. Thanks.

**Comment by Data66PF** [comment]
Please post a feature request at the community.
