### ISSUE TITLE
[BLOG] Video App Link

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#962]
In this blog entry http://blog.phpfox.com/2016/01/18/phpfox-4-2-rc-released/ the link to video app page in KB don't work.

Non working link: https://docs.phpfox.com/display/FOX4MAN/Setup+Video+App

Working link: https://docs.phpfox.com/display/FOX4MAN/Setting+Up+the+Video+App

**Comment by Data66PF** [comment]
We changed the article. I'll fix the blog but please don't post issues here for that. We have mentioned in the blog for the kb to post those at the forum in the section for KB questions :)

**Comment by SpaniNet** [comment]
I forgot that.
