### ISSUE TITLE
layout issue 4.2

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#963]
see attached image of nav
![screenshot-localhost 2016-01-19 02-42-52](https://cloud.githubusercontent.com/assets/13656046/12406560/c1e49298-be56-11e5-8dd9-b72523c40882.png)
 blocks

**Comment by Vivian-phpFox** [comment]
Do you sync CSS and clear cache?

**Comment by one44** [comment]
Yes on dev site

**Comment by one44** [comment]
Ok has to do with css from old install will need to redo css all over LOL
