### ISSUE TITLE
Pages Founders Block Missing

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#965]
When pages started shows member and not founder. Admin block missing.

**Comment by Data66PF** [comment]
Do you mean the Founders block? (Setting is Show Pages Admins) . Enabled at staging site now and I don't see the Founders block.

**Comment by Vivian-phpFox** [comment]
By default, block "Page Admins" in pages.view is disabled. This block work fine after enabled. Should enable this block in next version.
