### ISSUE TITLE
Blank area unter Photo when inserting news link

### ISSUE THREAD

**Issue by chickchecker** [moxi9/phpfox#967]
When you insert a news link in phpfox from a magazine... there is a gib blank area under the article photo in phpfox. Checke here for examples: https://v4.phpfox.com/profile-3249/

**Comment by Vivian-phpFox** [comment]
Kindly check again with V4.2.0 RC. We'll update the live demo when stable is ready

**Comment by Data66PF** [comment]
Works fine on staging server, https://stage.phpfox.com/profile-3/

**Comment by chickchecker** [comment]
Cannot reproduce?

Please scoll down: https://v4.phpfox.com/profile-3249/

and look at the blank area without text under 2 postings. Thats not normal.

**Comment by Data66PF** [comment]
As we said, the demo is not 4.2 and asked for you to please test on 4.2 which I provided a link to. This issue is resolved in 4.2.

**Comment by chickchecker** [comment]
ok thank you!
