### ISSUE TITLE
status post photo - share button not working. v4.2

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#968]
hi, in new update V4.2 . on member.index - in status post block- photo tab - "share" button is not working. 

I tried it on my local it doesnt work. i tried it on your v4.2  stage demo, it worked only once after that it stopped working . the button look like it is always pressed. i tried "shift+F5" but nothing helped.

Snapshot of your stage.phpfox site here : https://drive.google.com/file/d/0B2ZiaiRQS0Mbd1QzdDFrcUd5TUU/view?usp=drivesdk

**Comment by Data66PF** [comment]
confirmed the font is too light and it won't load sometimes. it works sometimes and it doesn't work sometimes. We need to check with several tests. Used a macbook pro with chrome browser.

**Comment by Vivian-phpFox** [comment]
This issue happen when you post the over size photo. The error message will be shown

**Comment by neil96** [comment]
Fixed on V4.2.1
