### ISSUE TITLE
Bug on view profile image page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#97]
there are two bugs on the view profile picture page. 
1:When we click on a user's profile picture (e.g  this is link to Raymond's profile pic http://community.phpfox.com/photo/album/profile/42592/profile-natio/) we get this following view . you can clearly see that one picture is repeated several time .

![image](https://cloud.githubusercontent.com/assets/406030/8689393/4f0c966e-2aa7-11e5-9cac-a7cf5e4efc2c.png)

2: on the same page when we scroll down ,with every scroll  we are getting following message.

![image](https://cloud.githubusercontent.com/assets/406030/8689419/92fdaf48-2aa7-11e5-9255-341631b1baa6.png)

Also we have  several comment boxes.

![image](https://cloud.githubusercontent.com/assets/406030/8689431/c4087244-2aa7-11e5-956d-94c57d412df3.png)

**Comment by Data66PF** [comment]
I can see the issue in the album but those photo ID numbers are all different. As for the second issue, you already reported it in another bug report.

**Comment by RaymondBenc** [comment]
Issue has been resolved for 4.0.4, which should be released later today.
