### ISSUE TITLE
duplicate comments on videos

### ISSUE THREAD

**Issue by EroFacies** [moxi9/phpfox#970]
comments on videos are showing up as duplicate

V4.2.0 RC

https://stage.phpfox.com/v/play/619

lg

**Comment by Data66PF** [comment]
https://stage.phpfox.com/v/play/654/ cannot reproduce. What browser and os are you using for testing? When submitting the comment, are you sure you are not hitting enter twice?

**Comment by EroFacies** [comment]
funny
- Call link ...
- Enter text, text twice
- 2 times when everything goes normal

**Comment by Data66PF** [comment]
What browser and os are you using for testing?

**Comment by EroFacies** [comment]
Browser edge and chrome

**Comment by Data66PF** [comment]
Os? What os?

**Comment by EroFacies** [comment]
Win 10

**Comment by Data66PF** [comment]
tested with win 10 with edge and chrome and can't reproduce. perhaps our team can test further.

**Comment by neil96** [comment]
I can't reproduce too.

**Comment by Data66PF** [comment]
Please see bug #1062 @neil96 for more info for testing this as it is on the staging server. Thank you :)

**Comment by Vivian-phpFox** [comment]
Cannot reproduce
