### ISSUE TITLE
missing buttons on browse photos page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#972]
version 4.2 RC ( stage.phpfox.com) using chrome and win 10

![image](https://cloud.githubusercontent.com/assets/406030/12419352/c849a646-beb5-11e5-89ff-acf11759bc31.png)

**Comment by aakash83** [comment]
clearly a bug because we cannot goto to next photos even by using keyboard arrows. imagine a community having thousands of photos and photo module allows us to browse only 15 of them.

**Comment by robert9592** [comment]
Fixed in 4.3.0
