### ISSUE TITLE
Top Buttons styling

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#973]
phpfox 4.2 (stage.phpfox.com) using chrome and win 10
The top right buttons are looking odd . it was nice to style them the same way we had in  version 4.1.
![image](https://cloud.githubusercontent.com/assets/406030/12419503/d4b97bc6-beb6-11e5-8ae2-3f417fd7a462.png)

**Comment by Data66PF** [comment]
This is the new design and looks nice as it is easier to see. You can change styling via the theme css.
