### ISSUE TITLE
IM Chat Conversations Missing After Accepting Friend Request

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#974]
I made a video of this one if needed. Using macbook and chrome browser. Be on the main feed page. 
Be on an account that has a friend request showing in the top notification.
Be on an account that had some chats with some friends previously so that you should have had a list in conversations before. (do not get that open yet as the bug might not show)
Click the friend notification and click to accept friend request.
Don't navigate or anything but now click the IM Chat button and it will open but you have no conversations showing though you had some already.
Close the IM chat popup.
Go to another page such as blog and click to refresh the page.
Open the IM chat and now the conversations show.

**Comment by RaymondBenc** [comment]
Can this be reproduced in the latest build of 4.3.0? I followed the steps provided to reproduce the issue and wasn't able to.

**Comment by Data66PF** [comment]
this is working fine in 4.3
