### ISSUE TITLE
 The answer button is not working at forum

### ISSUE THREAD

**Issue by cympgo** [moxi9/phpfox#975]
The answer button is not working at the forum , are you blind link.

**Comment by Data66PF** [comment]
Please be more specific. Do you mean the v4.2 staging server, the v4.1.2 demo or the live community? 
Do you mean the Reply button?
What browser and OS are you using?

**Comment by cympgo** [comment]
the answer button in version 4.2 in the forum is not opening the modal response. It is running on my server . 4.2 test site that you are released with the same problem the answer button on the forum. of a look there https://stage.phpfox.com/forum/thread/8/my-new-test/

**Comment by Data66PF** [comment]
Confirmed at the staging server. Uncaught Error: Syntax error, unrecognized expression: #/ 
The reply button url is https://stage.phpfox.com/#/
clicking the button redirects me to the home page
tested in chrome on mac.
