### ISSUE TITLE
Delete Feed X

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#976]
No delete feed button for admins etc in feed.

**Comment by Data66PF** [comment]
![delete feed](https://cloud.githubusercontent.com/assets/6908282/12422454/114af564-be95-11e5-845b-ca3cabb56311.png)

**Comment by Data66PF** [comment]
Are you able to delete the feeds via the button shown in the image?

**Comment by neil96** [comment]
I can't reproduce. Tested with nornal account on chrome, ubuntu.
