### ISSUE TITLE
[v4.2.0] Redirect to Dashboard when Language Pack is set as default

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#977]
When setting as default new Language Pack redirects to Dashboard when is set successfully. In v4.1.X doesn't redirct. I shows the message at the same page.

**Comment by Data66PF** [comment]
I can reproduce this but am not sure if this is a bug or as designed so will wait to see what our other staff say.

**Comment by Spaninet** [comment]
@neil96

**Comment by neil96** [comment]
Fixed on V4.2.1
