### ISSUE TITLE
Issue with Amazon CDN S3  App on phpfox

### ISSUE THREAD

**Issue by srikumar101** [moxi9/phpfox#978]
I have installed Amazon CDN S3 app. S3 bucket name and other required details are provided in the app. Photos get saves on S3 which I can see when I log into AWS. But those images don't appear on the site.

**Comment by RaymondBenc** [comment]
What URL does it use when viewing a photo? Is it the local URL for your site?

**Comment by srikumar101** [comment]
Hi Raymond, 

Thank you for responding. When I have Amazon CDN App enabled, here is what happens:

1) When image is uploaded, image is stored in Amazon S3, when I navigate to S3 bucket from AWS, I see image files correctly uploaded and saved - CORRECT
2) However, it also stores the images on EC2 instance file system - NOT SURE if this correct as storing files on EC2 instance is expensive, when CDN is enabled, it should only store the files in CDN if I am not wrong. 
3) Images uploaded while CDN was enabled doesn't show up on web page as explained in the issue description - When I attempt to right click and inspect the element to see where it is pointing to (local URL or CDN) I don't see any link to photo. 
4) When I disable Amazon CDN, all images show up and this time they are pointing to local URL

So, to answer to your question, when Amazon CDN is enabled, it is neither pointing to local URL nor CDN bucket. My assumption is that there is some configuration missing which should update the relative path of image and attachment files to point to CDN URL correctly when CDN is enabled.

**Comment by Data66PF** [comment]
Where are we on this @RaymondBenc

**Comment by neil96** [comment]
We have a setting "CloudFront URL" in S3 App. Please check and be sure you put it correct.

**Comment by srikumar101** [comment]
HI Neil,

I have provided the bucket URL and it is correct as it saves the photos
when I go check in S3 directly, its just that it doesn't DISPLAY on the
webpage when AWS S3 app is enabled.

Regards,
Srini

**Comment by neil96** [comment]
Can I test on your site?

**Comment by srikumar101** [comment]
Sure.. can you email me on srikumar101@gmail.com?

**Comment by neil96** [comment]
Please email for me neil@phpfox.com. Thanks!

**Comment by neil96** [comment]
@srikumar101 thanks for your email.
I saw your bucket name was strange. Maybe you put an Elastic Beanstalk bucket there.
I put my S3 bucket on your site, it's working fine.

Please create new S3 Bucket (https://console.aws.amazon.com/s3) and try again.

If it don't work again, tell me know.

**Comment by neil96** [comment]
Note: With current version, you have to select US location. Otherwise, app will return wrong url. This issue is fixed on 4.3 by adding more setting (bucket url), which will be released in next few days. If you can't wait, please submit a ticket with your site information, I'll help/fix on your server.

**Comment by srikumar101** [comment]
yes.. that worked for US standard region. when is V4.3 expected to be
released?

**Comment by Data66PF** [comment]
It will be released this week.

**Comment by GQTool** [comment]
Hi, I am checking to see if this is still an issue?

I am running version 4.3.2 and have included all the required information:
- Key
- Secret
- Bucket name
- Cloudfront url

But as described here I am having the same issue with being able to post to the bucket, but not pull them down to Phpfox.

As stated previously:

> ... when Amazon CDN is enabled, it is neither pointing to local URL nor CDN bucket. My assumption is that there is some configuration missing which should update the relative path of image and attachment files to point to CDN URL correctly when CDN is enable

This is still occurring, unless there is a particular reference the bucket location that is not correctly specified in the app?

**Comment by neil96** [comment]
@GQTool if you have a question, please ask on our [community](https://community.phpfox.com/forum/).
If you found a bug, please open a new issue, you can link to relate issue.

**Comment by GQTool** [comment]
Thanks, did that!  Was just checking to see if it was still a bug. Don't worry found the issue and fixed it.
