### ISSUE TITLE
IM Chat Notification Remains at 1 Even with No New Messages

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#979]
Staging server. Testing on macbook pro with chrome and safari. Using admin and registered user accounts.

I always show 1 message but there are none. Please see the video.

https://stage.phpfox.com/v/play/818

**Comment by RaymondBenc** [comment]
Fixed in 4.2.0 stable.

Staging server also updated.

**Comment by Data66PF** [comment]
This issue is still seen on 4.2.1 staging site.

**Comment by RaymondBenc** [comment]
Fixed in 4.3.0.
