### ISSUE TITLE
Bug-Album photos loading is endless with a new comment entry for each photo loading.

### ISSUE THREAD

**Issue by warrisdeepsingh** [moxi9/phpfox#98]
![screencapture-community-phpfox-com-photo-album-profile-408088-emilysmith-1436928585471](https://cloud.githubusercontent.com/assets/10062636/8689828/87abbc7a-2aca-11e5-9978-8f0b3d50a9f0.png)

Just open the link and scroll down,The page will start loading and will show ###### No photos have been added yet. <h6> Endlessly and with a new comment entry for each loading.

[link to the ablum!](http://community.phpfox.com/photo/album/profile/408088/emilysmith/)

**Comment by Data66PF** [comment]
Confirmed. Win 8.1pro, firefox latest browser. PF community.

**Comment by orgazilla** [comment]
Why is this still open? This problem needs to be fixed!

**Comment by RaymondBenc** [comment]
Issue has already been fixed for our next release, which should be out to clients today.
