### ISSUE TITLE
RSS Settings Link Missing from AdminCP Settings Menu

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#981]
Per a forum thread by a client, the settings for RSS feeds are missing from the AdminCP Settings listing. We can find it by direct url, admincp/setting/edit/?module-id=rss but that is not user friendly for clients. Please add the menu link for this back to the Settings section. Thanks!

**Comment by robert9592** [comment]
Fixed in v4.2.1

**Comment by SpaniNet** [comment]
Link to RSS page in forntend missing. Can be accessed directly going to http://SITE.com/rss/ if short urls enabled or http://SITE.com/index.php/rss/ if not.

**Comment by Data66PF** [comment]
This has been like that since v3 so you can add a menu if you would like but this is how it has been from v3 and into v4.
