### ISSUE TITLE
TOS and Privacy Policy Pages Still Missing

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#982]
These are required for every site and used to also show a checkbox on the registration (the setting option is found here in v3, admincp/setting/edit/setting-id_243/ ).

I had made a tutorial to add these back, as a temporary solution but we need to add these back for clients because the only way to get these to work right, as the linked tutorial shows, is to go in the database to enable them. http://scripttechs.com/article/361/add-pf-v4-privacy-tos-about-pages-back-w-agreement-on-registration/ 

Marking this a bug since these pages are required in just about every worldwide location.

**Comment by Gatsby-PF** [comment]
Please verify proper operation on http and https.

**Comment by robert9592** [comment]
Fixed in v4.2.1
