### ISSUE TITLE
The problem with the hashtag

### ISSUE THREAD

**Issue by Criotin** [moxi9/phpfox#983]
Hello
I've updated to version 4.2.0 phpfox and found a strange thing.
All blogs having a hashtag with the Russian capital letter "P" stopped to display.
I installed a clean version phpfox 4.2.0, but it remained the same problem.
An example of hashtag: #Ребенок

**Comment by Data66PF** [comment]
It seems to work at the staging https://stage.phpfox.com/hashtag/%D0%A0%D0%B5%D0%B1%D0%B5%D0%BD%D0%BE%D0%BA/

**Comment by Data66PF** [comment]
Still seems to work for me https://stage.phpfox.com/blog/34/hashtag-test/

**Comment by Criotin** [comment]
Thus recorded in table hashtag

![tag](https://cloud.githubusercontent.com/assets/15389101/12524113/ee372244-c16b-11e5-81e5-3c31a161a6f7.png)

**Comment by robert9592** [comment]
Fixed in v4.3.0
