### ISSUE TITLE
adding Friend notifications wrong phrase

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#985]
tested on stage.phpfox.com 

when we send  a friend request to a member and  he/she accepts it  then the notification we get  says" He/ she added  you as a friend " it should   be  like  " he/she  accepted your  friend request".

**Comment by Data66PF** [comment]
IMO this is fine as it is as phrases are easily managed in the phrase manager and we will have clients that like it the way it is, some that change it to something completely different, and some that want it like you mention. The best solution is for each client to use the phrase manager and change it how you want it. IMO, this is working as designed.

**Comment by Data66PF** [comment]
This issue was moved to moxi9/phpfox-feature-requests#24
