### ISSUE TITLE
short url

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#986]
4.2.0(build 7)
I've done this several time. The server settings is correct it's not working.

**Comment by Gatsby-PF** [comment]
The above comment references the following community support issue:
https://community.phpfox.com/forum/thread/53865/short-url-on-v-4_2/

**Comment by Data66PF** [comment]
Unable to reproduce any issue on the staging with short urls. https://stage.phpfox.com/user/browse/

**Comment by Data66PF** [comment]
What exact issues are you experiencing?

**Comment by wlongdonstudio** [comment]
I'm not able to enable this...
It just disables the site once I update the .htaccess

**Comment by Gatsby-PF** [comment]
Isn't this where you got into trouble on your previous update attempt?

**Comment by wlongdonstudio** [comment]
this is a different update...

**Comment by neil96** [comment]
I created some notes about Short Urls here: http://scripttechs.com/forum/thread/3066/phpfox4-short-url-notes/. I hope it can help you.

**Comment by Data66PF** [comment]
Are you still having this issue with 4.2.2 and after doing the steps in the tips linked?
