### ISSUE TITLE
PHPfox Facebook Base 

### ISSUE THREAD

**Issue by wlongdonstudio** [moxi9/phpfox#987]
PHPfox Facebook Base when enabled is not bringing in any of the user information how to gather those info as if the person signed up on the site?

v4.2.0(build 7)

**Comment by optiroot** [comment]
Do you mean the PHPfox App "Facebook login"? If you mean that, there is support just for PHPfox, the support for Apps made by PF Devs is in the community forum, here:
https://community.phpfox.com

**Comment by Data66PF** [comment]
Did you make sure  your app at facebook is set up with their new standards and with proper permissions for the script to retrieve the info? Is the app at facebook approved by facebook?

**Comment by djasha** [comment]
same problem for me v4,2 build18
all good with facebook and permissions, problem with the phpfox not showing the details taken from facebook (name. age, location, etc)

**Comment by lordofnos** [comment]
is this solved or does it work for someone?

**Comment by Data66PF** [comment]
This is not marked a bug or solved yet. It needs more testing.

**Comment by lordofnos** [comment]
all i can say is that i do not get any user information in... no e-mail or name only the profile pic shows up.

**Comment by optiroot** [comment]
Tested, I have the same problem. So I guess it can be confirmed as a bug. There are so many people saying this.

**Comment by ajaymenonv** [comment]
by when can we expect this to be resolved as even i am facing the same issue.

**Comment by RaymondBenc** [comment]
Fixed in 4.3.0
