### ISSUE TITLE
[v4.2.0] Admin can't send messages to members

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#988]
Admin user cannot send messages to other memebers but members can send messages to admin.
The message button in profiles don't work when logged as admin only.
Can send a message to a member if I click in messages icon at header then click in compose and search for a member.

**Comment by Data66PF** [comment]
can't reproduce on staging server. please check your permissions for the admin user group.

**Comment by Spaninet** [comment]
Permissions are fine.

Bug still in clean installation.

**Comment by Data66PF** [comment]
I'm testing on the staging server and don't have an issue on my macbook pro in chrome browser. What browser, os are you using?

**Comment by Spaninet** [comment]
I'm using latest Firefox for Windows.

**Comment by one44** [comment]
try checking the new IM app.

**Comment by Data66PF** [comment]
Can't reproduce on 4.2.2 https://v4.phpfox.com or at my dev site. One site has IM chat enabled, the other doesn't.

**Comment by Spaninet** [comment]
I upgraded the site that had this issue to last version and now admin can send messages to members.

I think that this issue was fixed in 4.2.1/2.
