### ISSUE TITLE
Order Apps on Block position

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#989]
Hi,

One of the things missing on apps when we compare it with modules, is the possibility to order them inside the same block position. I have installed v4.2 and I don't see yet a solution for this.

This is my contribution to solve this:

Now we have this code on start.php to show a block:
```
		$object->block('core.index-member', x, $View->render('@ces_marketplace/block.html', [
			'content' => $html
		]));

```
With this code I can create a setting to allow clients to set the block position by changing the value of 'x' but I can't allow them to set the order of the app. So this is my recomendation:
```
		$object->block('core.index-member', x, y, $View->render('@ces_marketplace/block.html', [
			'content' => $html
		]));

```
By adding a 'y' you can set the value of the order position of the app inside the block position 'x', and then I can create a setting to allow the client to set the order of the apps manualy.

Can this be donne?

Thanks

**Comment by Data66PF** [comment]
For our core developers looking at this, this is important as some blocks need to be above other blocks but right now, we can't set their position in relation to other blocks in that same block location. We used to be able to set the order of blocks within modules in v3.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/539 duplicate

**Comment by jhayden2000** [comment]
having an issue with this right now. would be nice to have a solution
