### ISSUE TITLE
Bug-With profile Music, photos, polls, quizzes, and blogs.

### ISSUE THREAD

**Issue by kizzel777** [moxi9/phpfox#99]
When you are on your own profile and click music. There is nothing.
![capture](https://cloud.githubusercontent.com/assets/3060221/8691707/26a3e4ba-2a7b-11e5-8ec2-500fc55707f5.PNG)

**Comment by kizzel777** [comment]
The same issue applies to blogs and photos.

**Comment by Data66PF** [comment]
Did you load some music and other things? Did you upgrade from v3.8 with the "show empty tabs" active?

**Comment by kizzel777** [comment]
Yes I upgraded from v3.8. I did not have "Show empty tabs" active.
There are things uploaded in the picture above I uploaded 6 songs and none of them are showing up, same with "photos, polls, quizzes, and blogs.

All of them show the page above.

**Comment by Data66PF** [comment]
Did you run the counters found in Maintenance? Not the ones that say for lower versions such as v1 or v2? Backup the site before running counters.

**Comment by kizzel777** [comment]
Thank you for that information Data. I have done the counters, cleared the cache and am still having the same issue.

**Comment by Data66PF** [comment]
We are unable to reproduce this on our live community or our test sites.
