### ISSUE TITLE
FTP Selection Missing Phrase in Drop Down

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#991]
core.Ftp  could be due to the cap letter there.
Go to admincp/setting/edit/?group-id=ftp_account
Click the drop down to select one and you will see that FTP is missing as there is a blank space for it. 
![missing name](https://cloud.githubusercontent.com/assets/6908282/12510382/84252192-c0d7-11e5-8004-74b5df8ee5ef.png)

**Comment by neil96** [comment]
Fixed on 4.2.0

**Comment by Vivian-phpFox** [comment]
Design was changed
