### ISSUE TITLE
Email change issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#992]
I changed my account email address in "Account Settings" page but i wrote wrong email address.
So try no way to change it again..

**Comment by Data66PF** [comment]
Are you saying that at your site you can't change the email? Did you check user group settings?

**Comment by Ylmzef** [comment]
Please try change your email on phpfox demo but write wrong email address.
So you cant change the worng entered email if "Logout After Changing Email" setting enabled.

**Comment by Data66PF** [comment]
If you changed it to the wrong one, then you would need to log in with the one you changed it to. You can't expect the script to know you put the wrong email.  This is a user issue, not a script bug. The setting can be disabled for logout after changing email. If a user puts the wrong email, there is nothing the script can do as it is then on the admin of the site to change it when the user contacts them.
