### ISSUE TITLE
tags block

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#995]
Have upgraded site from V3 and tags block does not show. If I transfer dev site files excluding the settings folder. to live site server it shows but disappears when cache is cleared. V4.2 and firefox.

**Comment by Data66PF** [comment]
Please test with apps disabled and with default theme. Please check with debug enabled and please check with developer browser console for issues. As it works on your dev site, this appears a site issue and not a bug but we will test with an upgraded site too. Is this in any specific section of the site or all over the site?

**Comment by one44** [comment]
Just tested default front page.

**Comment by Data66PF** [comment]
Do the tag blocks show in other areas of the site? Blog for example?

**Comment by one44** [comment]
will test

**Comment by neil96** [comment]
Did you test it?

**Comment by one44** [comment]
Yes and NO I am stumped

**Comment by Data66PF** [comment]
is this still valid in 4.2.2?
