### ISSUE TITLE
Mail popup

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#996]
Mail popup to send mail is not working. have upgraded site from V3 and FF. All other popups seem to be working like must be friends to send mail but not the send mail popup. Works in test 4.2 site but not on live site. dev is fresh install. Even if all files from dev transferred to live site still mail popup does not work? Correction stops working if another member is added to dev site only opens while only admin as a member. Are friends so should work?

**Comment by Data66PF** [comment]
Please test with apps disabled and with default theme. Please check with debug enabled and please check developer browser console for issues when clicking the mail.

**Comment by one44** [comment]
I do not think it is an issue with the apps as send mail does not work on dev site which is a clean new install. The tags show on the dev site but that is not a main issue for me right now it is getting mail and pages working.on the live site.

**Comment by one44** [comment]
This shows as well  GET 
https://syndication.twitter.com/widgets/timelines/paged/682834601614639104 [HTTP/2.0 200 OK 0ms]

**Comment by Data66PF** [comment]
Since we are not having a twitter timeline in the default script, can you check for any apps or plugins that you had for twitter?

**Comment by one44** [comment]
I have same problem on my dev site which is a clean install so am setting up a 4.1.2 site to see if that works on same server.

**Comment by one44** [comment]
ok set up a dev 4.1.2 site and works perfect
