### ISSUE TITLE
Pages Links

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#997]
Links on pages when section opened not working to open pages.

**Comment by Data66PF** [comment]
I am unclear what you mean. Please give detailed steps to reproduce and screen shots. Please always state your version and the browser and OS you test with.

**Comment by one44** [comment]
Sorry I have placed in other posts LOL V4.2 upgraded site. I think it id the rc version as it does not have claim page but demo does.
![screenshot-stage phpfox com 2016-01-24 13-38-42](https://cloud.githubusercontent.com/assets/13656046/12536024/604b46fa-c2a0-11e5-850b-492ac7295349.png)
