### ISSUE TITLE
liking an item as guest

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#998]
tested with latest demo(stage.phpfox) using chorme  desktop and mobile version

Non logged in member when hit the like button a popup appears asking them to log in but in background that item is shown as liked.

![image](https://cloud.githubusercontent.com/assets/406030/12535760/0db9c5b8-c28e-11e5-859d-c5a668d7d939.png)
![image](https://cloud.githubusercontent.com/assets/406030/12535765/39a54670-c28e-11e5-98fa-770ed10a5a53.png)

**Comment by Data66PF** [comment]
I'll confirm that the like button changes color when clicked as a guest and the Unlike appears in liked comments.

**Comment by neil96** [comment]
Fixed on V4.2.1
