### ISSUE TITLE
Friend Count in Guest View is Too Light

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#999]
Macbook pro el capitan on chrome. Viewing my profile as a guest on a 12 " monitor. https://stage.phpfox.com/profile-3/ issue was reported prior to release but it seems the issue is back again. We can see the count if we hover over it but if we don't hover, we can't see the count.
![friend count](https://cloud.githubusercontent.com/assets/6908282/12535938/d12c2f62-c262-11e5-8248-0b960c72e008.png)

**Comment by neil96** [comment]
Fixed on 4.2.1
